### ISSUE TITLE
[Management API] Expose `phone` on `UserGrantView`

### ISSUE THREAD

**Issue by maennchen** [zitadel/zitadel#1117]
**Is your feature request related to a problem? Please describe.**
Currently the gRPC Model for `UserGrantView` contains `email` but not `phone`.

**Describe the solution you'd like**
Expose `phone`.

**Describe alternatives you've considered**
None

**Additional context**
* https://github.com/caos/zitadel/blob/71df1bcd0e5731404c1bf4699dea59fb8c23c3d5/pkg/grpc/management/proto/management.proto#L2890

**Comment by adlerhurst** [comment]
At the moment the priority of this enhancement is low for us.

**Comment by hifabienne** [comment]
will close this issue at the moment, as we won't add the information to the user grant, if we see that this is a need for multiple customers we can reopen the issue
