### ISSUE TITLE
Already existing setup jobs are never reexecuted

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#1258]

**Comment by adlerhurst** [comment]
@eliobischof  is it still open and which milestone should it be assigned?

**Comment by eliobischof** [comment]
@stebenz  I think you fixed this?

**Comment by fgerschwiler** [comment]
@eliobischof @stebenz Is this fixed? Can we close this?

**Comment by stebenz** [comment]
@fgerschwiler  this should be fixed, otherwise, I think we can close it anyway as it stale for a long time
