### ISSUE TITLE
Outbound Webhook Support

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#13]
ZITADEL should provide a way to register web hooks for certain events.

For example if a developer wants to receive all user.create events he should be able to define a rule which invokes a endpoint.

**Comment by skomski** [comment]
This would be really useful for our setup. We want to run zitadel with several hundred tenants and we need to run propagation logic to external services across tenants on specific events like user creation/updates/deactivations/sign-outs etc.
Maybe this would also be possible in the future with your JavaScript Actions API but I think it would be much more maintainable for us with a extern microservice and webhooks.

**Comment by fforootd** [comment]
Config wise it definitely needs to be more easy to maintain a event and webhook setting then an action. Since it would be purely config and no code 😁

**Comment by MadL1me** [comment]
@hifabienne I would love to contribute to Zitadel. Can I take this feature to implement? While implementing, can I do both the frontend/backend parts?

**Comment by hifabienne** [comment]
Hei @MadL1me 
Thanks for your offer.
We actually are not ready yet to tell you how we would solve webhooks and how to subscribe to the events.
We will discuss this internally (will probably take us 1-2 weeks) and get back to you afterward.
I hope this is ok for you.

**Comment by MadL1me** [comment]
Yes, it is ok. Would be waiting for you

**Comment by hifabienne** [comment]
This issue will be closed in favor of https://github.com/zitadel/zitadel/issues/7246
With the new actions we allow users to trigger their own code and not have to implement it in ZITADEL directly. 
Actions V2 description: https://github.com/zitadel/zitadel/issues/7235
