### ISSUE TITLE
review zitadelctl

### ISSUE THREAD

**Issue by thesephirot** [zitadel/zitadel#1409]
List for findings on documentation/review zitadelctl:

1.

- [x] this should reference to zitadel, not orbos. 
- [x] Same with the orbctl command. if orbctl is needed, that needs to be stated or deleted. the need for .orbfile is unclear
- [x] gopass is referenced but not explained, a new installation might need a new/another masterkey and/or explanation for what it is used

```
$ ./zitadelctl
zitadelctl launches zitadel and simplifies common tasks such as updating your kubeconfig.
Participate in our community on https://github.com/caos/orbos
and visit our website at https://caos.ch

Usage:
  zitadelctl [command]

Examples:
$ mkdir -p ~/.orb
$ cat > ~/.orb/myorb << EOF
> url: git@github.com:me/my-orb.git
> masterkey: "$(gopass my-secrets/orbs/myorb/masterkey)"
> repokey: |
> $(cat ~/.ssh/myorbrepo | sed s/^/\ \ /g)
> EOF
$ orbctl -f ~/.orb/myorb [command]
```

2. 

- [ ] no interactive secret list is provided as stated in help

```
$ ./zitadelctl -f ~/.orb/zitadelctl help writesecret
Encrypt a secret and push it to the repository.
If no path is provided, a secret can interactively be chosen from a list of all possible secrets
```

when used:

```
$ ./zitadelctl -f ~/.orb/zitadelctl writesecret
ts="2021-03-11T14:48:34+01:00" err="Key must be provided eighter by value or by file path or by standard input" src="/go/src/github.com/caos/zitadel/cmd/zitadelctl/cmds/writesecret.go:49"
ts="2021-03-11T14:48:34+01:00" err="Key must be provided eighter by value or by file path or by standard input" src="/go/src/github.com/caos/zitadel/cmd/zitadelctl/cmds/root.go:87"
```

it seems to work, when a "value" is set. therefore a (write/read)secret list option would be suitable
```
./zitadelctl -f ~/.orb/zitadelctl writesecret --value="value"
? Select a secret:  [Use arrows to move, type to filter]
> zitadel.emailappkey
  zitadel.googlechaturl
  zitadel.keys
  zitadel.tracingserviceaccountjson
  zitadel.twilioauthtoken
  zitadel.twiliosid
```

3.

- [ ] version is empty

```
 ./zitadelctl -v
zitadelctl version
```

4.

- [ ]  connection to gke cluster is not possible:

```
$ kubectl create ns caos-system
namespace/caos-system created
$ kubectl create ns caos-zitadel
namespace/caos-zitadel created

......

$ ./zitadelctl -f ~/.orb/zitadelctl takeoff --kubeconfig  ~/.kube/config
ts="2021-03-11T16:22:55+01:00" msg="Failed to connect to k8s"

```

it works at @ orbos cluster though

5.
- 

- [ ] nipointer when not using --gitops flag

```
$ ./zitadelctl -f ~/.orb/zitadelctl readsecret
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x25d1fd3]

goroutine 1 [running]:
github.com/caos/zitadel/cmd/zitadelctl/cmds.ReadSecretCommand.func1(0xc000243600, 0xc00000cd40, 0x0, 0x2, 0x0, 0x0)
	/Users/christianjakob/caos/internal/zitadel/cmd/zitadelctl/cmds/readsecret.go:31 +0xf3
github.com/spf13/cobra.(*Command).execute(0xc000243600, 0xc00000cd20, 0x2, 0x2, 0xc000243600, 0xc00000cd20)
	/Users/christianjakob/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002422c0, 0xc0004fff38, 0x8, 0x8)
	/Users/christianjakob/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/christianjakob/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/Users/christianjakob/caos/internal/zitadel/cmd/zitadelctl/main.go:28 +0x285
```

6.

- [ ] node labels are fixed to 
```Node-Selectors:  orbos.ch/pool=management```

database and zitadel operator rely on the above label, there are not present e.g. in an gke environment

7. 

- [x] namespaces is fixed to caos-system
```
 ./zitadelctl -f ~/.orb/zitadelctl --gitops takeoff
ts="2021-03-15T12:09:17+01:00" err="Failed to deploy zitadel-operator into k8s-cluster: applying serviceaccount zitadel-operator failed: namespaces "caos-system" not found" src="/Users/christianjakob/caos/internal/zitadel/operator/zitadel/kinds/orb/reconcile.go:40" version="latest"
```
If the namespaces is fixed anyway, it should be created. Or set as variable

8. 

- [x]  secret orbconfig gets not created and should be named zitadel config. (as this is zitadel operator)
```
Volumes:
  orbconfig:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  caos
    Optional:    false
  ...
   MountVolume.SetUp failed for volume "orbconfig" : secret "caos" not found  
    
 ```

**Comment by eliobischof** [comment]
8.) The orbconfig originally comes from ORBOS and is also shared with ORBOS operators. Also the ZITADEL operators root kinds are called Orb. For defining a better wording (ubiquitous language) maybe we should start a Github discussion...

**Comment by eliobischof** [comment]
2. I think this works as expected?

**Comment by eliobischof** [comment]
3. Can't reproduce this one with the binary from https://github.com/caos/zitadel/releases/tag/crdoperatormerge-review-dev

I think for local builds this was fixed recently

**Comment by eliobischof** [comment]
4. Could you retry, plz?

![image](https://user-images.githubusercontent.com/12727842/111303083-697b5f80-8654-11eb-91c2-9324b3122c06.png)

**Comment by eliobischof** [comment]
5. this is WIP

**Comment by eliobischof** [comment]
6. Node selectors should be configurable. Could you show me your configs, plz?

**Comment by adlerhurst** [comment]
@eliobischof @stebenz @thesephirot is it still open and which milestone should it be assigned?

**Comment by fgerschwiler** [comment]
@eliobischof @stebenz @thesephirot Is this issue already solved? Or can this be closed?

**Comment by stebenz** [comment]
@fgerschwiler this should be fixed, otherwise, I think we can close it anyway as it stale for a long time
