### ISSUE TITLE
Logout on iOS returns error

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#1924]
This issue is to track the error reported by @buehler that logging out on iOS returns `error terminating session`

The reason has not been found out yet. We'll have to deploy a new versions with more detailed logging.

**Comment by livio-a** [comment]
/remind me to check again in two weeks

**Comment by buehler** [comment]
stale or fixed? :-)

**Comment by livio-a** [comment]
good question... at least no one has reported it anymore 😄

**Comment by livio-a** [comment]
closing this as no one reported it anymore, please reopen if it reoccurs
