### ISSUE TITLE
Restore command doesn't recognize when restore job is completed

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#2008]
**Describe the bug**
ZITADEL operator is stuck on waiting for restore job to complete

**To Reproduce**
`zitadelctl restore...`

**Expected behavior**
Command should go on when restore job is completed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Version: zitadelctl 1.21.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by adlerhurst** [comment]
Could the problem be an exeeded commit deadline?

https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html
