### ISSUE TITLE
Whitelabel Preview / Actual Font Color does not match

### ISSUE THREAD

**Issue by maennchen** [zitadel/zitadel#2058]
**Describe the bug**

When whitelabeling Zitadel, the font color of the preview and the actual login page do not match.

**To Reproduce**

1. Go to Organisation Whitelabeling
2. Put `#253143` as Background Color
3. Put `#374251` as Primary Color
4. Put `#c55353` as Warn COlor
5. Put `#e9e8df` as Font Color

**Expected behavior**

The actual login page should use the Font Color as the secondary button font color as in the preview, the secondary button uses the primary color instead.

The links in the footer (TOS / Privacy Policy / Help) should probably also use the font color and not primary.

**Screenshots**

![preview](https://user-images.githubusercontent.com/333918/126774404-cddf8a70-f159-4482-9664-3392752c3d89.png)
![real](https://user-images.githubusercontent.com/333918/126774408-28870345-7220-469a-ab9d-c5c48e2153ed.png)

**Additional context**

n/a

**Comment by livio-a** [comment]
Hi @maennchen 

And i can see that some color combinations will cause issues.

But I believe the primary color is used on purpose for the font color of the secondary button and links, as it was before enabling private labeling. But i will have to check with my colleagues.

**Comment by fgerschwiler** [comment]
@juergrinaldi can you please checkt this?

**Comment by fgerschwiler** [comment]
relates to #3024

**Comment by peintnermax** [comment]
Issue is fixed in v2
