### ISSUE TITLE
Plans to have Python3.8 Quickstart examples at https://docs.zitadel.ch/docs/quickstarts/introduction/ ?

### ISSUE THREAD

**Issue by gc-ss** [zitadel/zitadel#2062]
### Discussed in https://github.com/caos/zitadel/discussions/2061

<div type='discussions-op-text'>

<sup>Originally posted by **gc-ss** July 23, 2021</sup>
Love this project!

Are there any plans to have Python3.8 Quickstart examples at https://docs.zitadel.ch/docs/quickstarts/introduction/?
</div>

**Comment by gc-ss** [comment]
https://github.com/caos/zitadel-examples/tree/main/python3/service_user

**Comment by mffap** [comment]
@gc-ss I'm closing this issue, since the example seems to be what you were looking for and there hasn't been activity on the issue since.
