### ISSUE TITLE
Landing on wrong organization after initializing user

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#2093]
After initializing my user (after registering org) from the email-link, I get redirected to the first organization in my list, if I have more than one org I'm linked with.

This is not very 'safe' from a UX perspective, as I can easily make changes on the wrong org if I don't see this. As a user I expect a seamless flow within the new org.

(I didn't upload a screenshot for data protecting reasons)

**Comment by hifabienne** [comment]
@juergrinaldi I just tested this, I created an new organisation with a new user
Then initialized the user with this email. After this i was logged in with my user on the new created organisation.
Do I miss something? Do I need to give the user some memberships in between?

As I know we did use the first organisation in the begining, now we choose the last organisation you have been on when leaving the console.

**Comment by juergrinaldi** [comment]
hmpf. I can't recreate it anymore either. :-/
Because of that, I'll closse the issue (and we can re-open it, if someone will stumbles over this again)
