### ISSUE TITLE
Optimization: if User aready initialized, code from mail doesn't work

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#2095]
If I initialize a new user and enter the code from the initializing email and I click the link in the email again I get to the prompt to enter the code.

If I click on 'Next' it says that the code could not be found. From a UX perspective I expect the application to tell me that the user is already successfully initialized and - ideally - redirect me to the login prompt.

**Comment by juergrinaldi** [comment]
*bump*

**Comment by hifabienne** [comment]
will close this issue as we got rid of the initial state and mail.
also we will move to the new typescript login , so this will not be implemented at the moment
