### ISSUE TITLE
Chrome suggested password does not work on org register

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#2099]
**Describe the bug**
When I use suggested password from chrome, 
then the password does not comply with the requirements (missing symbol)
and the 'save' button stays inactive

**To Reproduce**
1. Go to https://accounts.zitadel.dev/register/org
2. Fill in the form
3. Let click on use suggested password
4. Password does not pass the check
5. Add symbol manually

**Expected behavior**
When I click 'use suggested password'
then the password is filled in, complying with the validation
and the save button is active

**Screenshots**
Step 3
![image](https://user-images.githubusercontent.com/1366906/127457469-23aa00da-74d5-4da6-8e68-e2063b79a39d.png)

Step 4
![image](https://user-images.githubusercontent.com/1366906/127458762-e43f6b26-dcfc-44f0-815d-8275842c2bab.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 
 - Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by livio-a** [comment]
I did not find any possibility to tell autocomplete to use special characters (nor any other pattern)
From what i've read chrome does it randomly.  So you might get special character, but there's also a chance not having a number in it.

**Comment by mffap** [comment]
Google offers a form to give feedback, if Chrome does not follow the accepted patterns: 
https://support.google.com/chrome/answer/7570435

` If a website doesn't accept a password suggested by Chrome, let us know. `

have you tried this?

It seems to look for the relevant input field attributes `maxlength` and `pattern` (https://www.chromium.org/developers/design-documents/password-generation). Pattern does not seem to be set in our case.

**Comment by mffap** [comment]
related #4196

**Comment by mffap** [comment]
To my knowledge there's currently no way to influence the behavior of Chrome in a meaningful way, thus closing this issue for now.
