### ISSUE TITLE
Intermit Build Cache Issues

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#2102]
**Describe the bug**
We see intermit cache issues when working with GHA as cache.

This happens across branches and looks random which job actually breaks 🤷 

We experience this since #2027 and tried to fiddle around with #2083 and #2086 

CC @livio-a @eliobischof

**Comment by fforootd** [comment]
For further tracking the related issue https://github.com/docker/buildx/issues/681

**Comment by fforootd** [comment]
Some examples to this 

```
#14 [go-test 1/4] COPY . .
161
#14 ERROR: blob not found
162
------
163
 > [go-test 1/4] COPY . .:
164
------
165
Dockerfile:18
166
--------------------
167
  16 |     ## Go test
168
  17 |     FROM go-base as go-test
169
  18 | >>> COPY . .
170
  19 |     #Migrations for cockroach-secure
171
  20 |     RUN go install github.com/rakyll/statik
172
--------------------
173
error: failed to solve: failed to compute cache key: blob not found
174
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```

**Comment by fforootd** [comment]
https://github.com/caos/zitadel/runs/3190017719?check_suite_focus=true#step:5:167

```
#10 [artifact 3/5] RUN apk add -U --no-cache ca-certificates
150
#10 ERROR: blob not found
151

152
#12 [internal] load build context
153
#12 transferring context: 414.67kB 0.0s done
154
#12 CANCELED
155
------
156
 > [artifact 3/5] RUN apk add -U --no-cache ca-certificates:
157
------
158
Dockerfile:53
159
--------------------
160
  51 |     ARG OS=linux
161
  52 |     
162
  53 | >>> RUN apk add -U --no-cache ca-certificates
163
  54 |     
164
  55 |     COPY --from=prod-go-build /go/src/github.com/caos/zitadel/zitadelctl /app/zitadelctl
165
--------------------
166
error: failed to solve: failed to compute cache key: blob not found
167
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```

**Comment by fforootd** [comment]
Ok this is new but not great

https://github.com/caos/zitadel/runs/3221111899#step:5:725

**Comment by decaby7e** [comment]
Hey our team is having a similar issue with our CI. Don't know if this is the best place to comment on that but though it might be useful to know.

**Comment by adlerhurst** [comment]
Hi @decaby7e 
Thanks for your input. At the moment we have no other workaround found than deactivating the cache and wait 🙈

Enjoy your weekend

**Comment by fforootd** [comment]
It looks like the buildkit error should be fixed https://github.com/docker/buildx/issues/681#issuecomment-934211900

I will open a PR for this
