### ISSUE TITLE
operator: unable to upgrade to go 1.17

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#2405]
**Describe the bug**
The tests or maybe other parts of the code fail because of bug fixes in the code of x509.

**To Reproduce**
1. run operator tests with go1.17

**Expected behaviour**

no fails

**Additional context**

action: https://github.com/caos/zitadel/pull/2308/checks?check_run_id=3652203655#step:5:404

golang changes: https://golang.org/doc/go1.17#minor_library_changes

**Comment by fgerschwiler** [comment]
Due to releasing v2 where we will not need the operator anymore, we will close this issue

Operator no maintenance
