### ISSUE TITLE
Multifactor Setup UX failure

### ISSUE THREAD

**Issue by virth** [zitadel/zitadel#2412]
**Describe the bug**
The multifactor setup screen is not very intuitive could use some UX improvements. There are two radio buttons to choose the MFA method, none of them is selected so you should the next button should initially be deactivated.

For a non technical expert user basically there is an enabled blue primary button and some technical buzzwords on the screen. Most of the users will just click the button without reading the text and end up on a screen which they don't know what to do next. Unfortunately MFA is not (yet) common sense. Especially with non technical Users it needs really good UX design to be understood.

**To Reproduce**
1. Register a new user
2. Confirm registration e-mail
3. Login with the new user
4. Now you will get asked if you want to setup MFA
5. The "next" button is enabled even none of the radio button options is enabled

**Expected behavior**
At least the next button should be disabled when there is no option selected. But I have more suggestions how to improve UX here:

1. Deactivate "next" button when there is no option selected.
2. Add option "I'm not interested" instead of the skip button.
3. Improve description text to clear things up. Suggestion : _**Increase your account's security by enabling Two-Factor Authentication:**_

Screen design suggestion:

![image](https://user-images.githubusercontent.com/18188015/134464838-699b878d-4c8e-4a76-a7ef-2240f2c5ff76.png)

**Screenshots**
Current design:
<img width="516" alt="Screenshot 2021-09-23 at 08 16 15" src="https://user-images.githubusercontent.com/18188015/134462202-066ccb67-3850-4853-9e3d-74fc34803ba4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome, Firefox
 - Version: All versions

**Smartphone (please complete the following information):**
 - Device: Huawei Mate P30 Pro
 - OS: Android
 - Browser: chrome
 - Version: all versions

**Comment by adlerhurst** [comment]
hi @virth 

thanks you for your report. We will have a look at it.

cheers

**Comment by virth** [comment]
It's now a lot better in the new version. Therefore I close this.

**Comment by virth** [comment]
Fixed with #4474
