### ISSUE TITLE
[Docs]: Guide for Passwordless registration with link

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#2478]
generell usage: request link to register a device for passwordless usage
  1. ImportHumanUserRequest: request link directly on creation
  https://github.com/caos/zitadel/blob/bd2e7d8133f9541e160f00b368083afb7ae13736/proto/zitadel/management.proto#L3008
  2. Existing Users: 
    2.1. request link:
https://github.com/caos/zitadel/blob/bd2e7d8133f9541e160f00b368083afb7ae13736/proto/zitadel/management.proto#L587-L590
returns https://github.com/caos/zitadel/blob/bd2e7d8133f9541e160f00b368083afb7ae13736/proto/zitadel/management.proto#L3322-L3326
    2.2 send link: https://github.com/caos/zitadel/blob/bd2e7d8133f9541e160f00b368083afb7ae13736/proto/zitadel/management.proto#L599-L602

when requesting the link directly (1. or 2.1.) you have the possibility specify whether the use should use a platform (device itself, e.g. FaceID) or crossPlatform (stick, e.g. SoloKeys) authenticator by appending a `requestPlatformType` query param (`platform`, `crossPlatform`, `unspecified`) to the link
if not provided or set to `unspecified` the type will not be restricted and all possibilities of the device are taken into account

**Comment by fgerschwiler** [comment]
estimate: 0.5d
