### ISSUE TITLE
[Docs]: Concept of claim mapping

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#2485]
We should explain the concept of inbound (external attributes to internal data model) and outbound claim mapping, optimally with a short example. Audience could be Solution Architect.

**Comment by hifabienne** [comment]
@mffap Do you mean with actions to metadata?
Would be great if you could write a user story according to this with some acceptance criterias.
As a [type of user], I want [some goal] so that [some reason].

**Comment by mffap** [comment]
> @mffap Do you mean with actions to metadata? Would be great if you could write a user story according to this with some acceptance criterias. As a [type of user], I want [some goal] so that [some reason].

I think this might be relevant to Actions, yes or to extenal idp templates, maybe? You anyways need a way to map data from external providers to internal 

You can see what I mean for example here: 
- https://github.com/mschwartau/keycloak-custom-protocol-mapper-example/blob/master/README.md
- https://is.docs.wso2.com/en/latest/guides/dialects/add-claim-mapping/

But I haven't got the question again, so we can also close it if you want. 

User Story is basically: 
As a Developer I want to understand what I need to configure/add as action, so that I can customize the claims within my token.

**Comment by mffap** [comment]
Maybe related to: https://github.com/zitadel/zitadel/issues/4373

**Comment by mffap** [comment]
@hifabienne I think this is resolved with 
https://github.com/zitadel/zitadel/issues/3997
and
https://github.com/zitadel/zitadel/issues/4909
