### ISSUE TITLE
2021-11-09 Various findings in ZITADEL console

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#2646]
- [x] under 'Projects' the action button (Aktionen) is missing translation in english

- [ ] There is a side scrolling appearing on smaller resolutions in 'Application' (where the PKCE/Code/JWT,.. selection is happening. Sidescrolling should be strongly avoided. Rather use a rescaling and on even smaller screens the flex layout to trigger (linebreak)

- [x] There are different namings for status (state). Better go with one. (my suggestion: status) (example: under org/projects it's state, under users it's status)

- [x] Table menu (where you can edit multiple entries) has both activate/deactivate clickable (active) no matter the current status. one should replace the other in this instance as it doesn't make sense to have both at the same time. with non-paired actions (like delete, for example) it should be grayed out instead.

- [x] in the organisation dropdown in the header: when I type a search query it filters the list (as it should) but if I close the dropdown and re-open it, the search query is still there but the list ist unfiltered again until i re-trigger the search query (by adding/subtracting characters)

- [x] right side bar (details/activity) doesn't remember the last tab i had open. it should stay on the tab the user last selected (as different users have different needs on the information provided by the sidebar. 
_Alternative: combine the two tabs as details doesn't seem to take much space anway_
- [x] also: the width of the sidepanel seems a bit too big for what is needed for it's content. this lessens the space for the main content. (300px seems plenty)

**Comment by juergrinaldi** [comment]
- [ ] the contrast on the link items (blue text) in dark theme is way too low, especially on certain boxes:

![image](https://user-images.githubusercontent.com/48990649/140940480-b871b073-2be4-48e4-9782-979db9a5be9f.png)
![image](https://user-images.githubusercontent.com/48990649/140935207-87aa7393-c753-44ef-bd5f-4ff2a60a9f21.png)

we should darken the background and the boxes (or alternatively make the boxes darker than the background) and modify the link color.
_colors: #18AFF4, #292726, #201E1D_
![image](https://user-images.githubusercontent.com/48990649/140939173-736c006a-6765-483b-83d1-a30d48802a89.png)
![image](https://user-images.githubusercontent.com/48990649/140939811-3c24dc04-904a-4cfd-9351-b74372d5d0d8.png)

less severe change (but still lacking some contrast): _colors: #6076E6, #292726, #201E1D_
![image](https://user-images.githubusercontent.com/48990649/140939936-b4b6252a-e410-4619-bcef-98a60985c888.png)
![image](https://user-images.githubusercontent.com/48990649/140939978-97d91d0a-1fa3-494c-9c16-1af33dd02899.png)

**Comment by fgerschwiler** [comment]
@peintnermax can I close this issue? Is everything solved?

**Comment by peintnermax** [comment]
yes. can be closed
