### ISSUE TITLE
Login interface text changes disappear after saving (but seem to be saved correctly)

### ISSUE THREAD

**Issue by sebastianbuechler** [zitadel/zitadel#2661]
**Describe the bug**
When changing login interface texts and saving them the view gets reloading and the default values appear again. After a couple of seconds, a text appears with "Newer Version exists" and a refresh button. Everything seems to be saved properly since it appears after refreshing. 

**To Reproduce**
1. Go to 'Organisation' -> 'Login Interface Texts'
2. Select any textbox and change to a new value
3. Save and see the new definitions disappear

**Expected behavior**
I expected the new definitions of the texts to stay after saving. It was confusing that they disappeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/42775578/141447078-60774644-62af-4764-86a7-8a577d48944e.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 94.0.4606.8

**Comment by adlerhurst** [comment]
Hi @sebastianbuechler thanks for your report.

@peintnermax will have a look at it.

**Comment by peintnermax** [comment]
This will be the fix https://github.com/zitadel/zitadel/pull/2666 but it's behaviour has still to be tested for V2
