### ISSUE TITLE
Profile should work without loginscreen/userselection

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#2738]
**Describe the issue**
Given I use the [b2b-example application](https://github.com/caos/zitadel-examples/tree/main/b2b-nextjs) and 
Given I'm already logged into the application
When I click to "Edit Profile" (https://console.zitadel.ch/users/me)
Then I have to select my account again to be redirected

**Expected behavior**
Directly get to my profile (with the correct private-labeling / app context).

**Comment by fgerschwiler** [comment]
In my opinion we should do something similar to oidc "login_hint"
I should be able to redirect to some console urls and send a login_hint as parameter, if this is set the console will send this to  the login and the user should be authenticated directly

**Comment by peintnermax** [comment]
You can now add login_hint as parameter to trigger an auth flow with the username.
