### ISSUE TITLE
Delete Organisations

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#2758]
IAM_OWNERs should be able to delete an organisation and we might as well give this feature to ORG_OWNERs as well
When deleting an organisation all unique constraints should be removed, so the organisation can be created again. The complete organisation should not be shown somewhere and no users and applications be able to authenticate. Also all grants made to this organisation should be removed.

Delete in ZITADEL means a new events org.deleted, all events still exist in the eventstore.

- [ ] Command
       Delete Unique constraints from the whole org
       Remove project grants
- [ ] Delete event contains grace period, only IAM-Owner can see the organization during the grace period. After this org is completely removed
- [ ] Projection, Handle the event in each projection
- [ ] Users of deleted organization are not able to login
- [ ] Test

**Comment by mffap** [comment]
Can you explain what you mean by delete in terms of data? 

I believe for logging and analytics it should be possible to correlate data  to 'deleted' organizations, at least for a period of time, say 18 months. How would this play together with GDPR automation/anonymization?

**Comment by fforootd** [comment]
IMO the deletion process is not "final". The `IAM_OWNER` can still access the data in the eventstore.
Still the ORG might transition into a deleted and afterwards (maybe) invisible state for the `ORG_OWNER`.

Maybe the better lifecycle is to first "archive" (make the org read-only and deactivated) and then "delete" (make invisble and release unique constraints) an ORG.

**Comment by fgerschwiler** [comment]
First implement a deactivate process

**Comment by peintnermax** [comment]
https://github.com/zitadel/zitadel/pull/3834 Deactivating and reactivating is implemented here, but there's a bug on reactivating organizations on the backend.
