### ISSUE TITLE
API endpoint not fulfilling reliable

### ISSUE THREAD

**Issue by sueess** [zitadel/zitadel#2760]
**Describe the bug**
During the creation of an organization in our tool we send multiple requests to Zitadel to create and configure the IAM organization. We always wait for the response of each request before we trigger the next. However, we often get errors from Zitadel, which show that the last call wasn't fully fulfilled (e. g. the organization not yet exists).

Reportduction: After creation of the organization we check with https://api.zitadel.ch/management/v1/orgs/me/members/_search if the bot is already a manager. Sometimes we get that the org is not yet there, sometimes we get an empty list of manager. Conclusion: The work was not really done when we get the response of a request.

`message: 'Organisation doesn\'t exist (AUTH-Bs7Ds)',`

**To Reproduce**
1. create organization (and set Bot as manager) --> returns organizationId
POST: https://api.zitadel.ch/management/v1/orgs

2. Set additional user as manager
POST: https://api.zitadel.ch/management/v1/orgs/me/members

3. grant project
POST: https://api.zitadel.ch/management/v1/projects/{project_id}/grants

**Expected behavior**
If an endpoint return, the action should be fulfilled and upcoming request should operate on the new data base.

**Comment by fgerschwiler** [comment]
Hi @sueess 
Thanks for your report we will have a look at this and give you a feedback.

**Comment by livio-a** [comment]
Hi @sueess 
We're still analysing how to solve the problem properly. In the meantime we implemented  a workaround and deployed it to production this morning.
Could you please check if you still get the error?

As background information:
Every api call which alters information within ZITADEL is handled by our "Command Side". It will create an event with all the relevant information and store in in the database. We internally subscribe to these events and create / update all necessary projections. These projections will be used for query calls. For more info: https://docs.zitadel.ch/docs/concepts/zitadel/architecture/

Apparently you were faster with the processing of some calls than we were with updating the projection table.
I'll leave this issue open until we find a proper solution.

**Comment by sueess** [comment]
Thanks @livio-a for the fast tackling of the issue! We will observe if the problem appears again and let you know.

**Comment by MajaEffenberg** [comment]
We tested the flow of adding a new organization again in the steps mentioned above. We didn't get previous error related to non-existent organization, but we ran into another problem.

When we want to set additional user as manager via POST: https://api.zitadel.ch/management/v1/orgs/me/members (step 2) , we get a response with status 403 and message: `'No matching permissions found (AUTH-5mWD2)'`. As I understand it is due to the fact that the service user who created the organization is not yet assigned as its manager and he does not have the permissions to add an additional manager to this organization.

We would expect that when we get the response of a creating oranization request, the user who created the organization will be right away manager and will have rights to perform operations on the organization such as adding new managers or granting projects.

**Comment by adlerhurst** [comment]
hi @MajaEffenberg 

Thanks for your report. We will have a look at it and give you feedback as soon as possible.

**Comment by adlerhurst** [comment]
hi @MajaEffenberg 

We deployed a fix to production which should resolve this problem. 

Enjoy your weekend

**Comment by MajaEffenberg** [comment]
@adlerhurst  We ran across the same issue today, in the same organization creation flow in our tool. After creating the organization, when we tried to set additional user as manager, we got an error with the message:
`message: 'Organisation doesn\'t exist (AUTH-Bs7Ds)',`

**Comment by adlerhurst** [comment]
Hi @MajaEffenberg we will implement a fix for the 404. tracking issue: https://github.com/zitadel/zitadel/issues/3489

**Comment by adlerhurst** [comment]
the fix for v1 is deployed on zitadel.ch. The fix for v2 is currently in review

**Comment by livio-a** [comment]
@adlerhurst fix vor V2 has been merged a while ago, right? i believe we can close this

**Comment by MajaEffenberg** [comment]
Unfortunately, this error repair for us again after long time without problems. 

It appeared in the same flow when, after creating an organization, we try to assign additional manager to this organization.
POST: https://api.zitadel.ch/management/v1/orgs/me/members
Error message: `message": "No matching permissions found (AUTH-5mWD2)`

**Comment by livio-a** [comment]
Hey @MajaEffenberg thanks for letting us know.

I need to check with @adlerhurst and will give you feedback by Monday.

**Comment by livio-a** [comment]
> Hey @MajaEffenberg thanks for letting us know.
> 
> I need to check with @adlerhurst and will give you feedback by Monday.

@MajaEffenberg we found a potential issue in the auth checks because of recent changes and are testing a fix: #5500

**Comment by sschoeb** [comment]
@livio-a thanks for checking. Seems to work perfectly fine for us now. So we think we could close the issue.
