### ISSUE TITLE
Implement Apple for Identity Brokering

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2761]
As an administrator of ZITADEL I want to be able to allow my users to use their apple login, so they do not have to create a new account.

**Acceptance criteria**
- [x] I am able to add apple as an identity provider to my instance or organization
- [x] I only have to configure client id, *team ID*, *key ID* and *private key* ~client secret~, the rest is provided by ZITADEL (issuer, etc)
- [x] I am able to login with my apple account
- [ ] If apple does have some design requirements, the login button does show it
- [x] Apple is implemented as provider based on our identity provider templates
- [x] I can add the apple provider in the console

Depends on #2998 

**Additional Information**
Apple developer account is needed.
https://developer.apple.com/help/account/configure-app-capabilities/configure-sign-in-with-apple-for-the-web

Assumptions:
1. Create Service and app in developer portal
2. Create Key, Download it
3. On create of the idp key has to uploaded
4. Apple version of "JWT Profile" as basic auth
5. Scopes can't be used as normal, problems with specific scopes

**Comment by fgerschwiler** [comment]
Estimate: 2-3d

**Comment by zifeo** [comment]
@hifabienne any timeline on this? Apple enforces its sign-in on some case, so this becomes a hard requirement to test & deploy Zitadel for us.

**Comment by hifabienne** [comment]
@zifeo as soon as we have ZITADEL V2 published for all our customers we will start implementing more social providers. I think this will be around July

**Comment by sh-TU** [comment]
@hifabienne screenshot's on zitadel's website got apple sign in button so it's weird it's about to be implemented yet. Or I am missing something in my setup? 

![Image](https://user-images.githubusercontent.com/91042553/234599058-c3780d76-5f2e-480e-96dc-8d7bb9524b06.png)

**Comment by hifabienne** [comment]
Hei @sh-TU 
You are right. At the moment we do not support apple and facebook.
We will change that on the website as long as we do not have it supported

**Comment by jerimy-TU** [comment]
A +1 from me on this one, we considering the move to Zitadel, however we have an iOS app live (in addition to our web platform) and we can't remove the sign in with Apple button, because we also use Google sign-in (Apple requirement).

**Comment by lukasver** [comment]
+1 on this one too!. We are releasing a mobile app and we are using Zitadel exclusively for sign-in so we would need to add the "Sign in with Apple" button to be approved for the store release.
Also feel this would be important to increase Zitadel adoption because ATM by not having this feature, anyone wanting to release mobile apps on iOS needs to have an auth alternative to support this button.

**Comment by hifabienne** [comment]
I see that the demand is pretty hight for this. I will have a look that we get it into one of the next Sprints.

**Comment by iyobo** [comment]
I will suggest one AC. Apple also demands that when a user deletes their account, that devs also disconnect that user's apple ID from our Sign in with Apple app. Revoking their apple tokens essentially.

Please have a way to do this automatically, or failing that, define a way for us to map the apple access token to some field so we can do so ourselves when our user delete themselves.

**Comment by matmedev** [comment]
@hifabienne Could you share some insights about the ETA of Facebook and Apple support?

We're currently evaluating Zitadel for an upcoming project, but as @lukasver mentioned above, "Sign in with Apple" is a blocking issue in terms of releasing a native iOS app.

**Comment by iyobo** [comment]
Alternatively, provide a way for IDPs to have a logo we can upload like we do branding. We can use generic OIDC with apple, but they just have guidelines as to what that button should look like.

**Comment by hifabienne** [comment]
Sorry, we actually wanted to implement it earlier, but had some higher priorities.
The goal is to implement it in the current quarter.

**Comment by Sipioteo** [comment]
Hi, i tried to add manually apple as an identity provider. It result in this error:
```
value length must be between 1 and 200 runes, inclusive
```

There is a way to avoid this error and add the client secret? (You know, apple client secret is in fact a JWT and mine is 309 chars long)

Thank you

**Comment by fforootd** [comment]
> Hi @hifabienne , i tried to add manually apple as an identity provider. It result in this error:
> 
> ```
> value length must be between 1 and 200 runes, inclusive
> ```
> 
> There is a way to avoid this error and add the client secret? (You know, apple client secret is in fact a JWT and mine is 309 chars long)
> 
> Thank you

Hi we plan to implement Apple ID soon. If I remember correctly in the next 2-4 weeks.
Looking at the spec it deviates in more ways from OIDC then our generic provider can cope.
So even if we extend the secret string size it will not work sadly.

**Comment by Sipioteo** [comment]
I managed to implement it with the new session and oidc API.
I retrieve the apple email of the user and use it to make the login (or the signup), then with the new api i will provide the access, id and refresh tokens to the user as it was normally logged.

It works really, really well

**Comment by fforootd** [comment]
> I managed to implement it with the new session and oidc API. I retrieve the apple email of the user and use it to make the login (or the signup), then with the new api i will provide the access, id and refresh tokens to the user as it was normally logged.
> 
> It works really, really well

Nice to hear, would you mind sharing some example code?

**Comment by Sipioteo** [comment]
> > I managed to implement it with the new session and oidc API. I retrieve the apple email of the user and use it to make the login (or the signup), then with the new api i will provide the access, id and refresh tokens to the user as it was normally logged.
> > It works really, really well
> 
> Nice to hear, would you mind sharing some example code?

First of all I used this library to simplify the work: [github.com/Timothylock/go-signin-with-apple/apple](github.com/Timothylock/go-signin-with-apple/apple)

Then i redirect the user to the apple auth endpoint with this piece of code:
```go
appleAuthUrl, _ := url.Parse("https://appleid.apple.com/auth/authorize")

q := appleAuthUrl.Query()
q.Add("response_type", "code id_token") // Important to get the user data: email,name on first login. on second login you will get only the email.
q.Add("client_id", appleClientID)
q.Add("redirect_uri", appleRedirectUri)
q.Add("state", "state")
q.Add("scope", "name email") // Important to get the user data: email,name on first login. on second login you will get only the email.
q.Add("response_mode", "form_post") // Important to get the user data: email,name on first login. on second login you will get only the email.

appleAuthUrl.RawQuery = q.Encode()

if c.Query("debug") != "" {
	return c.JSON(fiber.Map{
		"authUrl": appleAuthUrl.String(),
	})
}
return c.Redirect(appleAuthUrl.String(), fiber.StatusFound)
```

After that i will wait to the redirect uri the apple reply. I will manipulate it with this code:
```go
secret, _ := apple.GenerateClientSecret(appleSecret, appleTeamID, appleClientID, appleKeyID)
client := apple.New()

vReq := apple.AppValidationTokenRequest{
	ClientID:     appleClientID,
	ClientSecret: secret,
	Code:         c.FormValue("code"),
}
var resp apple.ValidationResponse
err := client.VerifyAppToken(context.Background(), vReq, &resp)
if err != nil {
	return err
}
claim, _ := apple.GetClaims(resp.IDToken)

email := ""
if (*claim)["email"] != nil {
	email = (*claim)["email"].(string)
}

codeVerifier, codeChallenge, err := genPKCE() // Needed for native app implementation
if err != nil {
	return err
}

code := ""
if c.FormValue("user", "") != "" {
	data := gjson.ParseBytes([]byte(c.FormValue("user")))

	code, err = auth.GetCodeFromOauthProvider(
		"apple_fix",
		"",
		email,
		auth.AdditionalData{
			Email:               email,
			Name:                data.Get("user.firstName").String() + " " + data.Get("user.lastName").String(),
			GivenName:           data.Get("user.firstName").String(),
			FamilyName:          data.Get("user.lastName").String(),
			CodeChallenge:       codeChallenge,
			CodeChallengeMethod: "S256",
		})

} else { // Cacatch if for some reason apple not sends user informations or if it is the second login
	code, err = auth.GetCodeFromOauthProvider(
		"apple_fix",
		"",
		email,
		auth.AdditionalData{
			Email:               email,
			Name:                email,
			GivenName:           email,
			FamilyName:          email,
			CodeChallenge:       codeChallenge,
			CodeChallengeMethod: "S256",
		})
}
if err != nil {
	return err
}

return c.Redirect(fmt.Sprintf("%s?code=%s&code_verifier=%s", nativeCallback, code, codeVerifier))
```

There is just a little security issue because i gave the user the codeverifier instead of creating it into the client. This is because i don't have time to prepare a cache system to store the pkce when the auth request start, this code is meant to work with a mobile app.

Let's say that for now the thing is working, when it will be ready an official full apple integration in zitadel i will probably drop this "spaghetti code"

Hope this help.
