### ISSUE TITLE
Implement Microsoft Live as Identity Provider

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2762]
Because Microsoft is not completely OIDC compliant we should implement it as provider
Depends on #3001 

**Acceptance criteria**
- [ ] Add Microsoft as default provider
- [ ] Login with microsoft
- [ ] Register with microsoft
- [ ] Docs: Add microsoft to identity providers to show users the default settings

**Comment by fgerschwiler** [comment]
Estimate: 2-3d

**Comment by hifabienne** [comment]
still relevant

**Comment by hifabienne** [comment]
waiting for #3001

**Comment by hifabienne** [comment]
I will close this issue since it is included in the identity provider templates: #4431
