### ISSUE TITLE
Skip / Display Login Success Page

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#2840]
At the moment we always display the login success page after a user was successfully authenticated and before redirecting to the callback. This was introduced with #1849 as native apps, esp. desktop apps would intercept the callback and let the user agent stay on the last rendered page (select account, password, ...).

For non native apps this change was not ideal and might lead to errors. As a short workaround #2839 will change the behaviour and display the success page only for native apps.

In the future, devs should be able to decide whether they want to display / skip the page for their app.

**Comment by peintnermax** [comment]
This seems to be resolved. Right? @livio-a

**Comment by livio-a** [comment]
The problem itself was resolved with the workaround mentioned above, but we've had customers which only had **mobile** native apps, but no desktop ones. They wanted to hide the success page.
But this feature is urgent at all.
