### ISSUE TITLE
Loginflow Redesign

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2942]
All uses should be able to register and login in ZITADEL without any problems

- [x] https://github.com/caos/caos-internal/issues/187#
- [ ] Register passwordless as default
- [x] https://github.com/zitadel/zitadel/issues/2982
- [x] https://github.com/zitadel/zitadel/issues/2998
- [ ] UI Customization

**Comment by mffap** [comment]
Milestone tracking: https://github.com/zitadel/zitadel/milestone/23

**Comment by mffap** [comment]
what's the difference to #3992? is that issue redundant?

**Comment by hifabienne** [comment]
This issue here is about the ux and from a user perspective how the login flow should be, the issue #3992 is about some technical/backend stuff. E.g use eventstore v2 instead of v1, store usersessions and authrequest in eventstore instead of separat tables, etc.

**Comment by hifabienne** [comment]
will close this issue for now, as we have our new typescript login for the future
