### ISSUE TITLE
SAML2 Service Provider (SP)

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2947]
## SAML 2.0 Support as SP

We should enable ZITADEL to work as SP with SAML 2.0 IdP.

## Questions to answer with the Spike

- [x] How do we want to implement SAML SP?
  - https://github.com/crewjam/saml
  - https://github.com/russellhaering/gosaml2
- [x] Do we need our library? Do we need to extend it?
  - As there are already existing SP implementations, I would currently use something existing until we are sure that we need something separate
- [x] Do we want to use another library?
  - Yes, will limit the invested time for implementation and standard covering
- [x] Which bindings do we want to support?
  - Currently POST and Redirect binding, maybe artifact if necessary
- [x] What should be configurable?
  - Defined with the outline of the Generic SAML Template
- [x] Rough outline of the Generic SAML Template?
  - MetadataURL and/or Metadata as file
  - NameId Format
  - AuthnRequestsSigned
  - WantAssertionsSigned

## Acceptance criteria

- [ ] Generic SAML2 IdP can be configured
- [ ] Users are able to authenticate with a SAML provider (old Login)
- [ ] Terraform can apply Generic SAML2.0 IdP
- [ ] Add Management functionalities to the Management and Admin API
- [ ] Extend Read functionality in the resource api
- [ ] Add Documentation
- [ ] Custom Attributes

**Comment by fgerschwiler** [comment]
tracked in #2941 this will be losed

**Comment by fforootd** [comment]
@hifabienne I think we should use this issue to track our effort in regard of becoming a SAML2 SP

**Comment by fforootd** [comment]
Relates to #4431

**Comment by claytonoliveira** [comment]
I guess this would be a great feature for many B2B SaaS 😄

**Comment by matthiastz** [comment]
Great feature idea

**Comment by TakumiHaruta** [comment]
Our customer wants to use SAML IdP. This feature will be very helpful 👍🏻

**Comment by mffap** [comment]
@claytonoliveira @matthiastz @TakumiHaruta What's the SAML IdP that should integrate with ZITADEL? Any specific tools / IAM that you know are popular in your user base?
That info would help us when we implement SAML SP, as we could test integration against the external identity providers directly. Thanks for the help.

**Comment by mffap** [comment]
+1 from a discovery call
Provider seems to be SAP (internal employees)

**Comment by fforootd** [comment]
> This is honestly the only think keeping me from implementing this app as the auth service for my company.

Thank you for letting us know, we for sure have this on the radar, but no ETA yet.
Would you mind sharing what identity source you would like to connect from?
This helps us validate the effort for this.

**Comment by claytonoliveira** [comment]
> @claytonoliveira @matthiastz @TakumiHaruta What's the SAML IdP that should integrate with ZITADEL? Any specific tools / IAM that you know are popular in your user base? That info would help us when we implement SAML SP, as we could test integration against the external identity providers directly. Thanks for the help.

@mffap we've seen Microsoft AD and SAP Cloud Identity, but i guess that if you implement SAML 2 standard it will work plenty of IdP on the market.

**Comment by TakumiHaruta** [comment]
@mffap 
Sorry for the late reply. Our customers want to use Microsoft AD or Okta as SAML IdP

**Comment by mffap** [comment]
Thanks for the feedback. That helps since as we can focus our testing efforts. 

@claytonoliveira While there is a standard we've seen for OIDC that many providers do not follow the standards and need some kind of special treatment (one reason why a generic OIDC template for external identity providers is not sufficient, but requires vendor-specific templates).

**Comment by karatekaneen** [comment]
Our customer would want to use their [Shibboleth IdP](https://www.shibboleth.net/) to authenticate with us. Would be awesome to make it work with Zitadel

**Comment by matthiastz** [comment]
Sorry for the late reply. I can second the importance of Microsoft AD / Azure and the ones already named. But as @claytonoliveira already said, once a big player like MS SAML is supported, it probably works for others as well (or with minor additions)

**Comment by OneCyrus** [comment]
Support for Microsoft ADFS would be great.

**Comment by fforootd** [comment]
> Support for Microsoft ADFS would be great.

Which version are we talking? 
Of the top of my head I think ADFS 2016 supports openid connect as well, which zitadel already can use.

**Comment by gpascual4qima** [comment]
Is there any update(calendar)  related to this integration of SAML as IdP?

**Comment by hifabienne** [comment]
We have now figured out what we have to implement and will estimate the issue in the next refinement.
No timeline yet when we will take it into a sprint, but the goal would be in the current quarter.
