### ISSUE TITLE
Migration Process Documentation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2976]
Customers should be able to easy change from another system to ZITADEL.

**Acceptance Criteria**

- [x] New section "Migration" in docs/guides
- [x] https://github.com/zitadel/zitadel/issues/4314
- [x] https://github.com/zitadel/zitadel/issues/5152
- [x] https://github.com/zitadel/zitadel/issues/5176
- [x] Specific Considerations for migration from 
  - [x] Auth0 (eg, [exporting hashes](https://auth0.com/docs/troubleshoot/customer-support/manage-subscriptions/export-data#user-passwords))
  - [ ] Keycloak
- [x] Move [Export and import with ZITADEL](https://zitadel.com/docs/guides/integrate/export-and-import) to the migration section

**Comment by hifabienne** [comment]
Keycloak blog article is in progress

**Comment by mffap** [comment]
I've add "custom identity management" and add a sub-task to this list. We often get questions around migrating from an exisitng database where password hashes are stored.

**Comment by bman46** [comment]
Any updated on this? Specifically the KeyCloak migration guide.

**Comment by mffap** [comment]
> Any updated on this? Specifically the KeyCloak migration guide.

@bman46 the keycloak guide will take another couple of weeks. Just as a disclaimer: the user migration will not be smooth until ZITADEL supports PBKDF2 hashing (https://github.com/zitadel/zitadel/issues/4157)

What are you struggling with? Maybe we can help you out in the meantime.

**Comment by bman46** [comment]
Haven't attempted it yet, so no issues. I was just looking to see if there was any official documentation on the topic before I attempt it.

**Comment by mffap** [comment]
> Haven't attempted it yet, so no issues. I was just looking to see if there was any official documentation on the topic before I attempt it.

Sure. I'll ping you when the guide is out. In case you want to start migrating already and you run into any questions, let us know - best over on [discord](https://zitadel.com/chat) or in a discussion here.

**Comment by mffap** [comment]
+1 question about migrating users when using social logins / external IDPs from current auth provider to zitadel

**Comment by mffap** [comment]
Follow-ups: 
- https://github.com/zitadel/zitadel/discussions/5626
- #118
