### ISSUE TITLE
Social Login Integration

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2982]
Customers should be able to use their existing accounts in ZITADEL.
Add more default providers.

- [ ] Clean up external identity provider process (login/register)
- [ ] #2761 
- [x] #2762 
- [ ] Github
- [ ] Integrate new providers (not oidc compliant)

**Comment by mffap** [comment]
@hifabienne is this one being replaced by https://github.com/zitadel/zitadel/issues/2998? Can we open issues for the individual social login providers that are higher prio, please?

**Comment by hifabienne** [comment]
Yes it is. So i will close this one. I think it was still from the okr last year
