### ISSUE TITLE
Customer Portal

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2987]
As a customer, I want portal, so that I can configure my ZITADEL instance and manage my subscriptions.

- [x] #3142 
- [x] Setup a new ZITADEL instance
- [x] Change an existing instance
- [x] Manage my subscriptions

**Comment by mffap** [comment]
Portal should allow to handle referral codes. 

This can be related to handling promotional codes, but also includes enabling the referring user to share the info (eg, a code) with the referred user.

**Comment by fgerschwiler** [comment]
Discussion with @fforootd 
Do we really need a separate customer portal?
Shouldn't we integrate as much as possible into the console? So our customers have everything at one point.
In this case only the setup process has to be integrated in the marketing page.

--> Console should be enabled to pull the license key from the subscription service, additionally the license key can be entered directly.

**Comment by mffap** [comment]
Can you outline what will be part of the customer portal? Abstract yes/no is not helpful IMO.
Something like choosing deployment location, payment and subscription info, etc. might be not relevant in a self-hosted instance.

**Comment by fforootd** [comment]
## Scenarios

I think we have the following scenarios here, each of those does have a slightly different need:

- Open Source - oss does not have something special to it, but maybe customers want to change on the fly to "support services"
- Support Service - customers might want to contract a support agreement and in doing so unlock certain enterprise features
- Public Cloud - customers want to change their tier, Domain Name and Data Location
- Dedicated Instance -  customers want to define/change their provider, data location, scaling, ...

### SaaS Special Requirements

- Customers need the ability to change  (up and downgrade) "tiers" which allow for certain features and usage limits depending on the tier

## Common Features across all scenarios

- Select Tier / Scenario
- Billing / Payment
- Subscription management (ZITADEL should be able to fetch its licensing state from an API)
- Depending on the subscription features should be enabled or disabled

**Comment by mffap** [comment]
related:
#2695
#151

Customer portal should also provide info for support requests
- Some kind of system ID
- Basic information / debug info to attach to support requests
