### ISSUE TITLE
High Quality Documentation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#2995]
Our key result is to get a high quality documentation of ZITADEL.

- [x] #3036

**Comment by mffap** [comment]
One thing that flew around: Postman supports GRPC now. Maybe worth exploring, if it'd make sense to check it out for ZITADEL API.

**Comment by eliobischof** [comment]
> 

Same for Insomnia

**Comment by mffap** [comment]
@eliobischof We should consider a guide on ZITADEL administration topics. For OSS users and new in the virtual instance, every customer will need to configure the whole IAM System. IMO such a guide should give an overview of the system and steps to take from there (creating orgs, setting up managers, configuration of IAM options, ...)

**Comment by mffap** [comment]
We need to document
- [ ] User self-serve register (incl. binding to domain)
- [ ] Creating users via API
- [ ] Creating users via Console
