### ISSUE TITLE
Improve external login provider handling

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3001]
At the moment we have to different flows with the external login providers. The register and the login flow should be the same.

**Acceptance criteria**
- [ ] Registration with attribute overview if auto register disabled
- [ ] Auto register if auto register enabled (how to handle not filled required fields?)
- [ ] One callback endpoint for all providers no matter if login or register
- [ ] Use userinfo instead of id token

**Comment by fgerschwiler** [comment]
Estimate: 2d

**Comment by hifabienne** [comment]
I will close this issue since @livio-a did do something on this end
