### ISSUE TITLE
zitadel settings for users

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3029]
To have the possibility to change and store the console ui settings, we need some possibility to store settings on a user.
E.g how does the dashboard look, which columns I like on my tables, some filters

**Acceptance criteria**
- [ ] command side for user setting
- [ ] projections for user settings
- [ ] queries for user settings
- [ ] tests
- [ ] key value store

**Comment by fgerschwiler** [comment]
Estimate: 2d

**Comment by hifabienne** [comment]
I will close this because we have it currently in the session storage and we could also use the user metadata for it
