### ISSUE TITLE
Event API

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3034]
As an administrator I want to be able to access all events that happend in ZITADEL, so I can track the changes on all ZITADEL resources.

**Acceptance Criterias**
- [x] #4906 
- [x] #4907

**Comment by fforootd** [comment]
@fgerschwiler you might want to translate this into EN 😁

**Comment by gaetancollaud** [comment]
Will you provide a streaming API ? So we don't have to pull the events but you push them ?

**Comment by fforootd** [comment]
Hi - @gaetancollaud 


We haven't completely settled on the design yet. What for sure will come  to live is a pull based API. But besides that an improvement could be a push based approach. Out rough idea is to extend our actions capabilities to run wasm code that can be triggered with events and then emit the event to a target.

If you could wish. What technology/framework/standard would you like to see?

**Comment by gaetancollaud** [comment]
I mean if you have some kind of webhook that would already be nice.

My wish? 
 - Kafka
 - Grpc streaming endpoint
 - Webscoket
 - MQTT over websocket
 - Graphql subscription

Whatever suits you to be honest. I guess you know best the constraints you have. As soon as you have a streaming API I'm good.

**Comment by gaetancollaud** [comment]
I've no specific use case right now. But I don't like pulling, because it's a waste of resources on both sides. Not to mention the implementation overhead on the client side (pulling, making diff, etc. etc.)

**Comment by fforootd** [comment]
Ok, thanks.

The reason to be a little back holding on push based concepts is that it hands down to us how we deal with backpressure if the target system is not available. Other than that I agree with you.

**Comment by gaetancollaud** [comment]
> The reason to be a little back holding on push based concepts is that it hands down to us how we deal with backpressure if the target system is not available. Other than that I agree with you.

This is completely understandable.

Again, a webhook where you discard fail request is already a really good start.

**Comment by hifabienne** [comment]
@eliobischof @fforootd I have added some more descriptions especially filter possibilities and data.
What do you think?
And what is your opinion on how the customers get the data?
I see different possiblities:
Pull:
- Event API
- Logs e.g Stdout

Push:
- Webhooks
- Actions

**Comment by fforootd** [comment]
I think we should provide this in the first place as a pull API and later bringt it to actions (with #4265 )

The API in my mind should look like /audit in this endpoint i want to have a stream of changes consisting of audit events (the eventstore mainly) and access events (the usage tables)

For easy devex i think we should focus on how to make this easy queriable by providing params so that also Console could profit)

I am open wording changes 😁

**Comment by eliobischof** [comment]
> 

Agree with first implementing pull based queries in regards to backpressure issues.

**Comment by hifabienne** [comment]
#4907 #4906
