### ISSUE TITLE
Current Documentation Quality

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3036]
As a developer, I want to have up-to-date and easy-to-read documentation that works, so that I can use and integrate ZITADEL fast and with confidence.

# Quickstarts

## Language
- [x] #3311 

## Login
- [x] #3042 
- [x] #3043
- [x] #3044
- [x] #3045

## Calling ZITADEL API
- [x] #3046
- [x] #3047

## Securing an API
- [x] #3048
- [x] #3049

# Other
- [x] #3050
- [x] #3051
- [x] #3052
- [x] #3053
- [x] #3054
- [x] #3055

# Missing
- [x] #3217 

# Follow-up
- [ ] Controllable Videos
- [ ] (Projects): "Where to go from here" links
- [ ] (B2C): Federation
- [ ] lowercase common nouns
- [ ] sentence case all titles
- [ ] Prerequisites call ZITADEL API .net and go: DRY

**Comment by hifabienne** [comment]
@eliobischof can we close this for now? Because we decided to take no actions here for the moment
