### ISSUE TITLE
Update installation guides

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3051]
Description

Document running ZITADEL v2
- [x] Locally
- [ ] On k8s
- [ ] Docker
- [x] Docker Compose
- [ ] Systemd?
- [ ] Nomad?

Update the existing documentation.

**Acceptance criteria**
- [ ] Correct
- [ ] Concise
- [ ] Engaging
- [ ] Up-to-date

**Comment by pr0gr8mm3r** [comment]
Will there be an official way/guide to run v2 on docker (compose)? I'd like to host a small instance (100 users max). I already have some docker containers on my server and would love to be able to easily add zitadel behind my existing reverse proxy and to not have to spin up an entire kubernetes cluster.

I already tried for v1, but couldn't find a prebuilt image for the console. Will it be moved into the main zitadel image for v2?

**Comment by eliobischof** [comment]
Console will be served directly from the ZITADEL binary. Very easy to run however you want.

**Comment by eliobischof** [comment]
#3817 merged
