### ISSUE TITLE
Run a set of core (e2e) frontend tests with firefox

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3067]
I got feedback that the login returns 'user not found' when in firefox. I was able to reproduce one, but not consistently. Unfortunately these events are currently not logged (not yet linked to a user). 

I propose to run set of core tests with different browsers. We don't have to overdo it, since Chrome, Safari and Firefox are pretty much represent the current market share. To my knowledge Chrome/Safari work both off the Chromium Engine, which is also default for Cypress. So I propose to run a subset also against Firefox browser, if possible.

**Comment by fforootd** [comment]
At what point does this happen?

I just checked this with my Firefox (96.0.1) and the passwordless login did work as expected.

**Comment by mffap** [comment]
Entering email and then next (sorry, should have written that down). 

Same here, worked after ca. 3 time perfectly. The initial hint came from a user, which stated that FF did not work for him but Chrome (yesterday).

Not a big priority, but maybe sensible to test different browsers, in case it's not much effort.

**Comment by mffap** [comment]
@fforootd @eliobischof @thesephirot do we run e2e tests on different browsers with cypress? in that case this issue could be closed and hopefully we catch any issues while expanding coverage

**Comment by thesephirot** [comment]
actually they run with chrome or electron headless, but can be configured to run with multiple browsers. We could add this to the "release run", cause it would slow the PR run quite significant

**Comment by thesephirot** [comment]
https://github.com/zitadel/zitadel/pull/4161
