### ISSUE TITLE
[Console] SAML IdP SP configuration

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#3094]
Description

- [x] GUI to add new SAML Applications( comparable to an OIDC Application)
- [x] Configureable to set either [Metadata](https://www.samltool.com/idp_metadata.php) as xml-file, or URL where the file is available
- [x] Maybe also possibility to set Application-Name?

**Acceptance criteria**
- [x] User can configure new SAML applications to add SPs

**Comment by juergrinaldi** [comment]
So würde ich es angehen. Vorteil hier wäre, dass die verschiedenen Applikationstypen auf einer Ebene wären und für den User weniger Klicks sind:

![saml-step01](https://user-images.githubusercontent.com/48990649/156177103-7203f4d3-be7a-49c9-8ced-49838946fb36.png)

![saml-step02](https://user-images.githubusercontent.com/48990649/156177119-b7d5c748-251f-4b90-b70f-09b2e0fc49de.png)


Alternativ - sofern das 1-Ebene-Konzept nicht geht - könnte man auch vorab eine Weiche machen um zwischen OIDC/SAML:
![saml-alternative-pathing01](https://user-images.githubusercontent.com/48990649/156177128-10a36f51-ad68-4618-9ced-1c9f67230759.png)

@stebenz Man müsste dann noch einen kurzen Beschreibungstext (siehe 1. Screen, Lorem Ipsum) angeben.
