### ISSUE TITLE
Design ZITADEL Customer Portal

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3142]
The customer portal is a separat application from ZITADEL. Our customers are able to create a login for their organization and manage all their instances in there, aswell as their invoices.

**Acceptance criteria**
**Instances**
- [ ] List all instances of a tenant
- [ ] Create a new Instance
       **Required Attributes:**
       - System/Org Name
       -  Admin User (E-Mail, First-, Lastname, Username)
       - Default Subscription: Free
       **Optional**:
       - Subscription: Pay as you go
       - Option: Custom Domain (custom domain needs to be verified after creation (acme challenge), make clear that the domain is really important to set as early as possible (passwordless, etc))
       - Option: Data locality region
       - Option: Extended SLA
       - Payment Method: Billing Data including Billing contact (important to know the country (mwst))
       - Payment: Discount coud
- [ ] Instance Detail
       - Usage
       - Metrics 
       - Info
- [ ] Change Instance:
       - System name
       - Subscription: Free - Pay as you go
       - Option: custom domain
       - Option: Data locality region
       - Payment Method: Billing Data including Billing contact (important to know the country (mwst))
       - Payment: Discount coud
- [ ] Verify domain
      - a domain has to be verified before you can use it for your instance
      - e.g acme challenge (analog org domain verification in console)

**Users and Role Management**
- [ ] add a new user
- [ ] change role of a user

**Invoices**
- [ ] change payment method
- [ ] change payment contact details
- [ ] list invoices
- [ ] download invoice

**Organization Detail**
- [ ] show detail (creation date, name, etc)
- [ ] delete organisation (includes all instances, maybe with grace period)

**Profile Page**
- [ ] show profile data 
- [ ] redirect to zitadel for edit? 
- [ ] authentication methods should somehow be able to configure (console, or directly in profile page)
- [ ] Change newsletter / Mailinglist subscriptions

**Support Requests**
- [ ] Create support request --> create issue in private github repo 
- [ ] If possible show created requests

**Next Ideas:**
- [ ] Referral code possibility
       - The customers should be able to generate a referral code, when the code is used by another customer they will get 
- [ ] Get Infos about the organization and use cases (function (dev, ceo, product management, sales, etc), market (b2b, b2c), industry (tech, health, etc), how did you hear about zitadel)
- [ ] Reporting for us
       - Number of Organizations and Users
       - Time from Creation of the organization to first instance in "pay as you go" tier
       - Count of used Referral codes and whicht organisations do recommend us
- [ ] Register open source and dedicated instances

**Comment by fgerschwiler** [comment]
estimated: ?? @juergrinaldi

**Comment by juergrinaldi** [comment]
I tried to combine the inputs and mockups from https://whimsical.com/customer-portal-CEBjdiSms4PhvYEEiGhkuo 
The screendesigns below are additional to the wire frame mockups from above (whimsical). 

Instance Overview:
![01-instances](https://user-images.githubusercontent.com/48990649/156575761-349c22ea-5c11-4ffc-bb49-05358a623210.png)

New Instance:
![02-new-instance](https://user-images.githubusercontent.com/48990649/156575764-e4dca1cf-ac7e-49c0-83b1-3870187ee2c1.png)

Edit Instance:
![03-edit-instance](https://user-images.githubusercontent.com/48990649/156575765-d487e4ef-7ef7-4775-8271-556492f62a2f.png)

**Comment by juergrinaldi** [comment]
I replaced the 'new instance' and 'edit instance' screenshots above regarding some comments of @fgerschwiler about 'general information' and domain verification.

**Comment by juergrinaldi** [comment]
Onboarding process:

![00a-onboarding](https://user-images.githubusercontent.com/48990649/161500796-f2a1e2c9-7010-4a37-9eb3-f1d332755ff8.png)

![00b-onboarding](https://user-images.githubusercontent.com/48990649/161500799-5621de70-2ae8-4fbe-a6de-7b60d92c2d56.png)

![00c-onboarding](https://user-images.githubusercontent.com/48990649/161500800-1606617b-a6e1-4636-91dd-9b492450f881.png)

![00d-onboarding](https://user-images.githubusercontent.com/48990649/161500804-7107368e-f6aa-4996-9b61-f9a016ce9925.png)

![00e-onboarding](https://user-images.githubusercontent.com/48990649/161500805-2ce154eb-c43b-4ff9-ad2b-14d54a7d70d7.png)

**Comment by juergrinaldi** [comment]
Here are some inputs regarding design elements. for further reference and things like hover states etc. see the style sheets from our console UI or ask @peintnermax. he will gladly help you out.  for access to the console files, please contact @fgerschwiler (you might be asked to give us your IP for whitelisting).

The branch for the new console design is 'cnsl-rhl-nav' or on https://console-alpha.netlify.app/ 
basic design is in https://github.com/caos/zitadel/blob/cnsl-rhl-nav/console/src/styles/input.scss

Here are some of the colors and typography visualized and tagged:
![99-design infos](https://user-images.githubusercontent.com/48990649/161500909-08124c20-82f1-4039-b0dc-677525f8daef.png)

**Colors:**
```
#BBBAFA
#FF2069
#41CABA
#FFFFFF
#8795A1
#CF4C3D
#3BC37D

#0F1522
#111827
#1A253C
#283E67
#293243
#403E3E
```

**Comment by buehler** [comment]
Hey @juergrinaldi 

Is there a similar picture for the "light theme"?

**Comment by peintnermax** [comment]
generated from dark primary (#bbbafa) and light primary (#5469d4)

--theme-dark-primary-50: #ffffff;
    --theme-dark-primary-contrast-50: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-100: #ffffff;
    --theme-dark-primary-contrast-100: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-200: #ffffff;
    --theme-dark-primary-contrast-200: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-300: #f3f3fe;
    --theme-dark-primary-contrast-300: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-400: #d7d7fc;
    --theme-dark-primary-contrast-400: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-500: #bbbafa;
    --theme-dark-primary-contrast-500: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-600: #9f9df8;
    --theme-dark-primary-contrast-600: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-700: #8381f6;
    --theme-dark-primary-contrast-700: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-800: #6764f4;
    --theme-dark-primary-contrast-800: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-900: #4b48f2;
    --theme-dark-primary-contrast-900: #ffffff;
    --theme-dark-primary-A100: #ffffff;
    --theme-dark-primary-contrast-A100: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-A200: #ffffff;
    --theme-dark-primary-contrast-A200: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-A400: #e8e8ff;
    --theme-dark-primary-contrast-A400: hsla(0, 0%, 0%, 0.87);
    --theme-dark-primary-A700: #d1d1fd;
    --theme-dark-primary-contrast-A700: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-50: #ffffff;
    --theme-light-primary-contrast-50: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-100: #ebedfa;
    --theme-light-primary-contrast-100: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-200: #bec6ef;
    --theme-light-primary-contrast-200: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-300: #8594e0;
    --theme-light-primary-contrast-300: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-400: #6c7eda;
    --theme-light-primary-contrast-400: hsla(0, 0%, 0%, 0.87);
    --theme-light-primary-500: #5469d4;
    --theme-light-primary-contrast-500: #ffffff;
    --theme-light-primary-600: #3c54ce;
    --theme-light-primary-contrast-600: #ffffff;
    --theme-light-primary-700: #2f46bc;
    --theme-light-primary-contrast-700: #ffffff;
    --theme-light-primary-800: #293da3;
    --theme-light-primary-contrast-800: #ffffff;
    --theme-light-primary-900: #23348b;
    --theme-light-primary-contrast-900: #ffffff;
    --theme-light-primary-A100: #ffffff;
    --theme-light-primary-contrast-A100: hsla(0, 0%, 0%, 0.87);
