### ISSUE TITLE
Switch default asset storage from s3/gcs to database

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#3181]
We should switch the default asset storage to a db table.
The asset data should no really put a lot of preasure towards the db.

- [x] Store assets into seperate table
- [ ] Apply data locality option to assets
- [x] Implement etag for CDN caching

**Acceptance criteria**
- [x] Assets are stored in the db and delivered through zitadel
- [x] Caching assets in the CDN is possible

**Comment by livio-a** [comment]
locality in db implementation depends on https://github.com/caos/zitadel/issues/3224

**Comment by fgerschwiler** [comment]
@livio-a Can I close this issue? In my opinion the locality in the assets is not different as for the rest. And this is tracked in an other issue.
