### ISSUE TITLE
settings page

### ISSUE THREAD

**Issue by fgerschwiler** [zitadel/zitadel#3215]
Since each customer gets a system by its own some kind of configurations should be able to change in console.

**Acceptance criteria**
- [x] Design
- [x] Default Language (string)
- [x] Different Secret Generators 
- [x] Notification Providers (edit and view)(1 SMTP, SMS type twilio)
- [x] Notification Providers only view (filesystem, log)
- [x] OIDC configuration
- [ ] E2E Tests

**Comment by fgerschwiler** [comment]
**Secret Generators:** 
Define how some kind of secrets should look like (e.g Code in Password Reset Mail)
All Generators exist in each system, the admin is able to change the configuration

**Attributes:**
Length: 6
Expiry: '1h'
IncludeLowerLetters: false
IncludeUpperLetters: true
IncludeDigits: true
IncludeSymbols: false

**Generator Types**
ClientSecretGenerator
InitializeUserCode
EmailVerificationCode
PhoneVerificationCode
PasswordlessInitCode

**Comment by fgerschwiler** [comment]
**Notification Providers:**

**SMTP**
One smtp configuration is able

Attibutes:
From (string hi@zitadel.ch)
From Name (string, ZITADEL)
Tls (bool, true/false)
Host (string, smtp.gmail.com:465)
User (string)
Password (string)

Password should be able to change separatly.

**SMS**
None or Multiple SMS configurations are able, when they are added they are not active. Activate/Deactivate should be possible.
At the moment only the provider twilio is able, soon their should be more possible probiders:

**Twilio**
SID (string)
From (string, sender name)
Token (string)

Token should be able to change separatly (its like a password)

**Comment by fgerschwiler** [comment]
**OIDC Configuration**
The token times of the oidc configurations should be configured. Configuration is always existing, but the user is able to change it.

Attibutes:
DefaultAccessTokenLifetime: 12h
DefaultIdTokenLifetime: 12h
DefaultRefreshTokenIdleExpiration: 720h #30d
DefaultRefreshTokenExpiration: 2160h #90d

**Comment by juergrinaldi** [comment]
I tried to arrange the new settings somewhat accordingly to the existing settings.

Overview:
![zitadel-settings-overview01](https://user-images.githubusercontent.com/48990649/159913680-40803a41-c627-4b5f-90ba-9f703d233306.png)

![zitadel-settings-overview02-solo](https://user-images.githubusercontent.com/48990649/159913698-49153da5-a769-4f66-8ee3-69f71a1fe519.png)

Language:
![zitadel-settings-language01](https://user-images.githubusercontent.com/48990649/159913780-caf9461f-8026-45bb-a615-8accad6e39e8.png)

Secrets:
![zitadel-settings-secrets01a](https://user-images.githubusercontent.com/48990649/159913874-4c4c113d-075e-4d2e-82a0-5f4d32988f19.png)

![zitadel-settings-secrets01b](https://user-images.githubusercontent.com/48990649/159913876-dbb25739-f96e-4fcd-b60f-8ae7e377a1b6.png)

Notifications:
![zitadel-settings-notifications01a](https://user-images.githubusercontent.com/48990649/159914004-cd369a92-0a6c-4a33-8fdc-73800ca2bdd5.png)

![zitadel-settings-notifications01b](https://user-images.githubusercontent.com/48990649/159914012-0c0fbec9-3f37-4fd5-8be1-f6ef51c4bb69.png)

![zitadel-settings-notifications01c](https://user-images.githubusercontent.com/48990649/159914014-7c0f57ea-163a-4a73-b969-48566123c85d.png)

![zitadel-settings-notifications01d](https://user-images.githubusercontent.com/48990649/159914016-ed736e02-12f6-4c72-8325-1a42dc695442.png)


OIDC:
![zitadel-settings-oidc01](https://user-images.githubusercontent.com/48990649/159913809-fe53bcb6-6b0c-41fd-bdf3-0d27aced09a4.png)

**Comment by juergrinaldi** [comment]
@fgerschwiler i added @peintnermax as new asignee (hope that's what you have in mind) and also changed some of the labels.

**Comment by fgerschwiler** [comment]
@juergrinaldi @peintnermax there is an issue for the frontend, which linkes to this one. #3231 
So I think this can be closed, due to design is done, only the implementation is missing
