### ISSUE TITLE
Customer Portal Backend

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3216]
To enable our customers to create a new instance and manage their subscriptions, etc. we will build our own customer portal. For this a backend is needed, which connects all necessary apis. (Mailjet, Stripe, Bexio, ZITADEL)

Create Instance flow: https://app.diagrams.net/#G14bRmSWuPpfXKzNvWvHDdPezx1ytZoe2Q

- [ ] Customer Portal basic structure
- [ ] ZITADEL connection
- [ ] stripe connection
- [ ] mailjet connection
- [ ] bexio connection
- [ ] basic reporting possiblities

**Comment by fgerschwiler** [comment]
**ZITADEL**

- Create a new zitadel instance (cli or api)
- Change data locality
- Change domain (system, organisation)
-

**Comment by fgerschwiler** [comment]
Stripe

- Create customer
- Change billing adress
- Add discount
- Add Options/Packages (SLA, domain, etc.)

**Comment by mffap** [comment]
Mailjet

- Add new customers to transactional mail workflows (welcome, ...)
- React to changes in subscription / userinfo (eg, metadata, email)
- Add customers to marketing campaign when opt-in during sign-up
- Subscribe to news (double-opt in)

**Comment by mffap** [comment]
> Stripe
> 
> * Create customer
> * Change billing adress
> * Add discount
> * Add Options/Packages (SLA, domain, etc.)

- Billing email Address
- Instructions to set invoice address in stripe or automate by setting that address automatically
- Show past invoices
- Download invoices
- Show open invoices

Last points could provide a better UX as we go to ex-post payment.

**Comment by fgerschwiler** [comment]
**Bexio**

- Add Customer
- Add invoice
- Close invoice
- Handle Value-added tax
