### ISSUE TITLE
Create new tenant

### ISSUE THREAD

**Issue by fgerschwiler** [zitadel/zitadel#3223]
create a new tenant with all initial data.

**Acceptance criteria**
- [x] Create initial events
- [x] Create sequence
- [x] command to setup tenant

**Comment by fgerschwiler** [comment]
**Initial events:**

- Secret Generators
- Notification Provider: SMTP Config
- NotificationProvider: Twilio Config?
- Notification Provider: Debug: Log/Filesystem
- Policies (Login, Branding, etc)
- OIDC Config
- Lifetimes
- Default Org
- Admin User

**Comment by adlerhurst** [comment]
Notification Provider: Debug: Log/Filesystem is IMO valid for local/dev mode but not for a production use case. I recommend creating an additional provider called "projection". This provider writes the notifications into a database table. This table should be available through api and Console.

**Comment by livio-a** [comment]
@adlerhurst there are some left check boxes above. are these done and can this issue be closed or do we need to implement them?
