### ISSUE TITLE
Handle locality in eventstore and projections

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3224]
As a ZITADEL customer I want to be able to choose the region where ZITADEL runs.

**Acceptance Criteria**
- [ ] The eventstore stores the locality as separat column
- [ ] The locality is taken from the context sent in the request
- [ ] The projections have a locality column
- [ ] The "old views" have a locality column

**Comment by livio-a** [comment]
from Cockroachdb v22.1: https://www.cockroachlabs.com/docs/releases/v22.1.html
> CockroachDB now turns on support for hash-sharded indexes in implicit partitioned tables. Previously, CockroachDB blocked users from creating hash-sharded indexes in all kinds of partitioned tables including implicit partitioned tables using PARTITION ALL BY or REGIONAL BY ROW. Primary keys cannot be hash-sharded if a table is explicitly partitioned with PARTITION BY or an index cannot be hash-sharded if the index is explicitly partitioned with PARTITION BY. Partitioning columns cannot be placed explicitly as key columns of a hash-sharded index, including regional-by-row table's crdb_region column. [#76358](https://github.com/cockroachdb/cockroach/pull/76358)

eventstore.events has a hash-shareded index

**Comment by hifabienne** [comment]
Will close this issue as this is planned differently at the moment
