### ISSUE TITLE
Console auth user requirements

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#3248]
The console should be able to load privatelabelling and privacy policy data without specifying an orgId and therefore probably needs those request(s) on the auth service.

**Comment by fgerschwiler** [comment]
On the my profile page the request should go to the auth api:
- [ ] GetMyLabelPolicy
- [ ] GetMyPrivacyPolicy

In the console where I have an organization selected the request should go to the management api:
- [ ] GetCurrentLabelPolicy
- [ ] GetCurrentPrivacyPolicy
