### ISSUE TITLE
Console Redesign Findings

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3334]
I just tested the redesign of the console and this are my findings:

**Acceptance criteria**

**UI Consistence**
- [x] Not all the tables behave simliar, eg. On some tables i can click on the row, some don't, some have an edit icon at the end some don't
       - Projects: No Edit Button, Per click to detail
       - Roles: Edit Button, Click on row shows detail
       - ProjectGrants: Edit Button, Click on row shows detail
       - Users: No edit button, per click to detail
       - Authorizations: Edit button, click on row does nothing
       - Membership on org: No edit button instead plus, click on row redirects to user
       - Memberships on user: Arrow instead of edit, click on row does nothing
- [x] We still have some parts with auto saving (e.g project) and some without (e.g oidc config, users)  
       
**Navigation**
- [x]  I don't get why we have sometimes side nav (users) and sometimes the nav in the top changes (projects), for me the second top nav feels strange because I can't get to the items I had before (@juergrinaldi what do you mean about this?) This happens when I am on a Project Detail. I don't habe the main nav (Organization, Projects, Users, etc..) On the app detail no nav at all is existing
- [x] I think the system part in the navigation is confusing if the users don't have system. (Or do only IAM admins see this part of the nav?)

**Organisation:**
- [ ] If I click on a manager of an external org, this doesn't work. Maybe we should not allow redirects to external users (disable row)

**Projects**
- [x] Why is applications not a separat section?
- [x] If I am on the authorizations tab it is  confusing how to get back to the projects list
- [ ] For me the project grant detail is confusing (graphic), for me it is not really clear that this is the detail, and I can edit the roles, maybe its because we have a complete different view here

**Apps**
- [ ] Urls should be loger, I can see them if I want to know what it is, I need to copy and paste somewhere

**Authorization**
- [ ] The Detail of an authorization is confusing, I didn't get how to change it. (@juergrinaldi  do you have some input here?, or is it just me) 

**UserMemberships**
- [x] Behaviour is strange, if I click edit and go back I land on a completely different page (Organization)

**Actions**
- [ ] It is not possible to remove one trigger from a flow

**Comment by peintnermax** [comment]
If a user doesn't have iam.write permission than the breadcrumb and button to switch to system settings are not visible.. I guess the system breadcrumb was a good suggestion of @fforootd because it displays the hierarchy of the settings.

I think the new nav takes a little to get used to because we had a global navigation in the first place.. But once you understand how the breadcrumbs work you can quickly navigate back to the upper layers.

**Comment by peintnermax** [comment]
applications are not in a separate navigation item because theres enough space on the project detail and quick access to an application is more important IMO.
