### ISSUE TITLE
Helpvideos ZITADEL

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3365]
The idea is, to provide short videos with how-to's for specific features/workflows in zitadel (console).

for example:
- [ ] User management
- [ ] Setting up a project
- [ ] Setting up an application
- [ ] Handling 'Actions'
- [ ] How to manage Authorizations
- [ ] Setup ZITADEL with your corporate design/brand

etc.

**Comment by juergrinaldi** [comment]
Still on my radar

**Comment by hifabienne** [comment]
@juergrinaldi should we move this to backlog?
Or can we describe what the expectation is from this issue? 
Does not look like ready to implement for me

**Comment by juergrinaldi** [comment]
Yeah, it makes sense to put in backlog for now.
Allthough I don't think that it isn't ready for implementation, as it might be already useful for (new) customers/users.

(and I updated the initial comment with some examples.)

**Comment by juergrinaldi** [comment]
I'll close this issue as it probably isn't ready yet. We can re-open them as needed (and probably split in different issues per video).
