### ISSUE TITLE
Unable to Deploy

### ISSUE THREAD

**Issue by Alexei-Barnes** [zitadel/zitadel#3446]
**Describe the bug**
I have been unable to deploy ZITADEL onto EKS after a number of attempts. Bellow is a list of the problems I've encountered. I tried both the CRD and GitOps deployment modes.

Note that all of these bugs are for release v1.83.0
Initially I tried v1.83.1, but I was unable to pull the docker images for the release, so I reverted to the release prior to that.

**CRD Deployment**
https://docs.zitadel.ch/docs/guides/installation/crd

1. The cat with a heredoc for setting secrets is invalid bash. The heredoc does not close. Instead, the terminal simply waits for additional user input.
2. After performing `kubectl apply <files>` I get a validation error:
    ```
    ❯ kubectl apply --filename ./database.yml,./zitadel.yml
    error: error validating "./database.yml": error validating data: [ValidationError(Database.spec): unknown field "database" in ch.caos.v1.Database.spec, ValidationError(Database.spec): missing required field "spec" in ch.caos.v1.Database.spec]; if you choose to ignore these errors, turn validation off with --validate=false
    ```
3. If I provide `--validate=false` then I get:
    ```
    ❯ kubectl apply --filename ./database.yml,./zitadel.yml --validate=false
    database.caos.ch/database configured
    zitadel.caos.ch/zitadel unchanged
    ❯ kubectl --namespace caos-system logs database-operator-5d7bdf7c8d-r4jz9
    E0414 09:27:51.662703       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch 
    *v1.Database: failed to list *v1.Database: v1.DatabaseList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1.Database: 
    v1.Database.Spec: v1.Spec.Spec: unmarshalerDecoder: Object 'Kind' is missing in '{"selfReconciling":true,"verbose":true,"version":"1.0.0"}', error found in #10 byte of ...|":"1.0.0"},"version"|..., bigger context ...|econciling":true,"verbose":true,"version":"1.0.0"},"version":"v0"}}],"kind":"DatabaseList","metadata|...
    ```
4. Any modification to the structure of `database.yml` leads to the same issues as I'm about to describe with `zitadel.yml`.
5. The ZITADEL pod log is simply:
    ```
    ❯ kubectl --namespace caos-system logs zitadel-operator-5f9cc76c85-svr88
    panic: invalid tree: <nil>
    
    goroutine 255 [running]:
    github.com/caos/orbos/pkg/treelabels.MustForAPI(0x0, 0xc000699500, 0xc000a044e0)
            /go/pkg/mod/github.com/caos/orbos@v1.5.14-0.20211102124704-34db02bceed2/pkg/treelabels/api.go:17 +0x37e
    github.com/caos/zitadel/operator/database/kinds/orb.AdaptFunc.func1(0x0, 0x2c209d8, 0x2c209d8, 0x2c209d0, 0x2c209e0, 0x0, 0xc0007787e0, 0xc0003dc120, 0x0, 0x0, ...)
            /go/src/github.com/caos/zitadel/operator/database/kinds/orb/adapt.go:89 +0x53a
    github.com/caos/zitadel/pkg/databases.connection(0x0, 0x2c209d8, 0x2c209d8, 0x2c209d0, 0x2c209e0, 0x0, 0x2f00dd8, 0xc0004821c0, 0xc00055fc00, 0xc00055f9d8, ...)
            /go/src/github.com/caos/zitadel/pkg/databases/connection.go:101 +0x304
    github.com/caos/zitadel/pkg/databases.newCrdConnection(0x0, 0x2c209d8, 0x2c209d8, 0x2c209d0, 0x2c209e0, 0x0, 0x2f00dd8, 0xc0004821c0, 0xc00055fc00, 0xc00055fc00, ...)
            /go/src/github.com/caos/zitadel/pkg/databases/connection.go:62 +0xf3
    github.com/caos/zitadel/pkg/databases.NewConnection(0x0, 0x2c209d8, 0x2c209d8, 0x2c209d0, 0x2c209e0, 0x0, 0x2f00dd8, 0xc0004821c0, 0xb44400, 0x0, ...)
            /go/src/github.com/caos/zitadel/pkg/databases/connection.go:29 +0x139
    github.com/caos/zitadel/operator/crtlcrd/zitadel.(*Reconciler).Reconcile(0xc0001ae480, 0x2ec31f8, 0xc0005998c0, 0xc0006d91f0, 0xb, 0xc0006d9180, 0x7, 0xc000599800, 0x0, 0x0, ...)
            /go/src/github.com/caos/zitadel/operator/crtlcrd/zitadel/zitadel.go:41 +0x437
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0007a6dc0, 0x2ec31f8, 0xc000599860, 0xc0006d91f0, 0xb, 0xc0006d9180, 0x7, 0xc000599800, 0x0, 0x0, ...)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114 +0x247
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a6dc0, 0x2ec3150, 0xc0007bfbc0, 0x27ac080, 0xc0003dc040)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311 +0x305
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a6dc0, 0x2ec3150, 0xc0007bfbc0, 0xc00006af00)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266 +0x205
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0006e2080, 0xc0007a6dc0, 0x2ec3150, 0xc0007bfbc0)
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227 +0x6b
    created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
            /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:223 +0x4d2
    ```

**GitOps Deployment**
https://docs.zitadel.ch/docs/guides/installation/gitops

Using gitops deployment, I simply get:
```
❯ kubectl -n caos-system logs database-operator-685d9878bb-v4gzm --follow
ts="2022-04-14T09:51:01Z" err="cloning repository from git@github.com:Alexei-Barnes/zitadel-test.git failed: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type." src="/go/src/github.com/caos/zitadel/cmd/zitadelctl/cmds/root.go:42"
```

**To Reproduce**
1. Deploy a kubernetes cluster with `eksctl cluster create`
2. Follow either the CRD or GitOps installation instructions.
3. Pods crash

**Expected behavior**
I expect the installation guides to lead to a functional deployment.

**Screenshots**
GitOps error:
![image](https://user-images.githubusercontent.com/82444470/163363883-95054afd-3a45-4d77-8509-78fb1c5522f0.png)

CRD database error:
![image](https://user-images.githubusercontent.com/82444470/163363969-4ce1d688-7f04-4ba3-b335-9c4c21cc1529.png)

CRD heredoc issue:
![image](https://user-images.githubusercontent.com/82444470/163364116-e17f7828-4211-4d11-8197-ab43a95af150.png)
(This is from ZSH rather than bash, but the behaviour is identical in each)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 via WSL on top of Windows 10
 - Browser Chrome
 - Version 100.0.4896.88
 - EKS is using Kubernetes version 1.21

**Additional context**
Please let me know if any additional context is required.

**Comment by eliobischof** [comment]
@Alexei-Barnes did you create the github deploy key using the `zitadelctl configure` command?

**Comment by eliobischof** [comment]
@Alexei-Barnes About the non-terminating heredoc. With these changes, it should work: #3448

**Comment by Alexei-Barnes** [comment]
Long weekend coming up - I'll check in every now and then. If anyone wants any further information, for me to try anything, or to pair with me I'm happy to help.

I'll try having a read of the relevant source code for the CDR flow and see if I can understand why that's unhappy with the config files.

**Comment by eliobischof** [comment]
@Alexei-Barnes I think these two PRs fix the crd mode installation: #3448, #3462

**Comment by Alexei-Barnes** [comment]
Nice! I'll try the latest release now 👍

**Comment by eliobischof** [comment]
If you want to try the prerelease, you can download it like this: `curl -s https://api.github.com/repos/caos/zitadel/releases/tags/fix-db-crd-operator-dev | grep "browser_download_url.*zitadelctl-linux-amd64" | cut -d '"' -f 4 | sudo wget -i - -O /usr/local/bin/zitadelctl`

**Comment by Alexei-Barnes** [comment]
This is fixed, I can deploy with CRD mode! 🎉
Thanks 😁

**Comment by eliobischof** [comment]
Nice!
I'll leave the issue open for the gitops deploy key problem.
Thank you for reporting the issues.

**Comment by fforootd** [comment]
@eliobischof is still a valid thing?

**Comment by eliobischof** [comment]
@Alexei-Barnes do you still need a working deploy key from zitadelctl for the v1 GitOps mode?

**Comment by eliobischof** [comment]
Please reopen, if it is still relevant

**Comment by Alexei-Barnes** [comment]
@eliobischof No, this is no longer needed, thank you! 👍
