### ISSUE TITLE
Cap Instance Requests and Minutes

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3463]
Due to the new pricing model we need to cap the requests when the limit is reached.

**Acceptance criteria**
- [ ] How to know that the limit is reached
- [ ] Return error in instance interceptor

**Comment by eliobischof** [comment]
Todo:
- [ ] Customer Portal reconciles Cloud Armor Rules
- [ ] If possible, it uses redirect rules to /admin/instances. (Not possible via GUI, but according to the [docs, it should work](https://cloud.google.com/armor/docs/bot-management#redirect_302_response))

**Comment by fforootd** [comment]
Replaced with an internal issue
