### ISSUE TITLE
⚠️ IMPORTANT NOTICE ⚠️ - Relocation of this project

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#3471]
## What happens

In order to improve our commitment to ZITADEL with its libraries and tools being open source, we will relocate this repository to the newly created [ZITADEL organisation](https://github.com/zitadel).

## When will this be done

Beginning from **27.04.2022** this repository will be newly located here -> [zitadel](https://github.com/zitadel/zitadel) 

### Container Images

The container images will newly reside under **ghcr.io/zitadel/zitadel:latest**

### Git Remote

As by [Github's documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization) we recommend the following:

```text
All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL.
```

```bash
git remote set-url origin git@github.com:zitadel/zitadel.git
```

**Comment by livio-a** [comment]
When updating the zitadel operator deployment from a version 1.83.3 or less to 1.83.4 or higher you will need to either:
 - make a takeoff with the new zitadelctl image
 or
 - uopdate the version in the zitadel.yaml and patch the deployment of the operator simultaneously, e.g.:
 `kubectl -n caos-system set image deployment/zitadel-operator zitadel=ghcr.io/zitadel/zitadel-operator:1.83.4`
