### ISSUE TITLE
Check for new events on query side

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3489]
When a new object is created, the read model needs some time to update the model. If the object is read during this time the API will respond with a "Not found error"

**Acceptance criteria**
- [ ] The query side should check for new events and apply it to the read model
- [ ] At the moment the most important objects are: 
      - Organisation
      - User
      - Manager Roles of user (user had no permissions)
- [ ] It should work on all get object requests (not on lists/searchs)

**Comment by livio-a** [comment]
obviously not only creation of objects is affected, but also updates: https://discord.com/channels/927474939156643850/927866013545025566/969449145586810910

**Comment by adlerhurst** [comment]
the fix for v1 is deployed on zitadel.ch. The fix for v2 is currently in review

**Comment by livio-a** [comment]
https://github.com/zitadel/zitadel/issues/2760#issuecomment-1166901512
