### ISSUE TITLE
`UpdateUserName` API endpoint not accepting new username

### ISSUE THREAD

**Issue by jdclarke5** [zitadel/zitadel#3537]
**Describe the bug**
Attempt to update username using PUT endpoint https://docs.zitadel.ch/docs/apis/proto/management#updateusername results in error `invalid UpdateUserNameRequest.UserName: value length must be between 1 and 200 runes, inclusive`

**To Reproduce**
Send an update username request like below to https://docs.zitadel.ch/docs/apis/proto/management#updateusername.

**Expected behavior**
Should be able to update username.

**Screenshots**
![](https://user-images.githubusercontent.com/14137523/165882666-c8592011-3d29-4d9d-bc6e-b71a66f7cc97.png)

**Additional context**
Currently self-hosting ZITADEL on `v1.83.2`.

**Comment by livio-a** [comment]
Hi @jdclarke5 

Thanks for the issue. Seams like we're having an issue with the REST/gRPC mapping.
I'll take a look at it shortly.
