### ISSUE TITLE
Cannot set identical phone number after deleting

### ISSUE THREAD

**Issue by jdclarke5** [zitadel/zitadel#3538]
**Describe the bug**
Cannot set same phone number after deleting. This may be a manifestation of a more general issue.

**To Reproduce**
1. Set a phone numbers
2. Delete the phone number
3. Set the same phone number
4. See error: `Errors.User.Phone.NotChanged (COMMAND-wF94r)`

**Expected behavior**
Should be able to set any phone number after deleting.

**Screenshots**
![](https://user-images.githubusercontent.com/14137523/165899271-ee18d2be-efd2-4931-8db8-f5fc68f729f5.png)

**Additional context**
Currently self-hosting ZITADEL on v1.83.2.

**Comment by adlerhurst** [comment]
hi @jdclarke5 

Thank you for your report. We have a look at it as soon as possible.

Happy weekend!

**Comment by adlerhurst** [comment]
your bug will be fixed after https://github.com/zitadel/zitadel/pull/3544 is merged
