### ISSUE TITLE
[v2] cli add autocompletion

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#3572]
Description

The user should be able to add autocompletion through a cli call (e.g. `zitadel completion bash`)

**Acceptance criteria**
- [ ] it is possible to add the autocompletion of ZITADEL to .bashrc
- [ ] if a user writes zitadel in his terminal and presses tab the user gets proposals of what to do

**Comment by doncicuto** [comment]
@hifabienne and @adlerhurst, maybe this issue could be closed? I've checked that Zitadel already has the cobra completion included:

![image](https://github.com/zitadel/zitadel/assets/30386061/21c8fd09-4d75-4bf2-8d0b-0197bfb662f8)

or do you need a more specific completion definition?
