### ISSUE TITLE
Reduce startup times

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3588]
For being able to scale more reactively, reduced startup times could help.
One way of achieving that could be to separate init and start phases.

We do have 3 different parts right now: start, setup and init
The start should not check the projections

**Acceptance Criteria**
- [ ] Start should not check projections
- [ ] Spooler should not check for all instances if they are done, just check last cycle

**Comment by livio-a** [comment]
to reduce the startup time even more, we might change the order in ZITADEL itself as well (listen before starting projections)
will have to check if possible

**Comment by adlerhurst** [comment]
@eliobischof can this one be closed?

**Comment by eliobischof** [comment]
> @eliobischof can this one be closed?

No. Added the question label and a better title and description.

**Comment by eliobischof** [comment]
@fforootd @livio-a
FYI, terraform-provider-google doesn't support cloud run jobs, yet.
https://github.com/hashicorp/terraform-provider-google/issues/11743

**Comment by fforootd** [comment]
Hm, thats a bummer, in that case we need to think of something else 😁

**Comment by eliobischof** [comment]
Maybe we can run a cloud run job using the gcloud terraform provider https://github.com/terraform-google-modules/terraform-google-gcloud

@livio-a , when we deploy an init/setup job using a newer image tag, is the old revision still allowed to serve traffic during the job execution?

**Comment by livio-a** [comment]
The old revision must serve traffic until the new is ready
IMO it might even make sense to then gradually swift traffic from the old to the new revision
