### ISSUE TITLE
Console findings

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3595]
1. login, no MFA, password changed: whitescreen:

![Image](https://user-images.githubusercontent.com/47860090/166648532-20df7c41-cc41-444c-b510-d5c37b2c5e0f.png)

page reload to console took 5 - 10 seconds. this is a bad first impression to customers.

2. landing page:

![Image](https://user-images.githubusercontent.com/47860090/166648653-2b76b567-9ae5-4250-8c17-76dc1d9a6f9a.png)

which effect does "Spitzname" have? that is not explained

3. metadata

![Image](https://user-images.githubusercontent.com/47860090/166649152-128ec8ae-f02d-4e0a-9436-9f7887efd096.png)

why am I able to enter Metadata if I do not have permissions? that should be checked before the dialog

4. popup

![Image](https://user-images.githubusercontent.com/47860090/166649908-1bb82632-eebb-432e-96ae-b798b893775a.png)

the first popup occured after the 2nd page reload, why not at first? (with an option to disable it if needed)

5. first logout

![Screenshot 2022-05-04 at 10 51 33](https://user-images.githubusercontent.com/47860090/166650272-719738b6-2c6c-4189-b7ed-9e0ab09c5292.png)

the logout leads to an white page with state="" in the URL. the customer should have an appropriate feedback for the logout. reload of page does not change this behavior.

6. re login

![Screenshot 2022-05-04 at 10 53 11](https://user-images.githubusercontent.com/47860090/166650627-548c7713-dfd1-4b61-889d-a57cf4fb62fd.png)

after a new console load, my username gets prefixed with "smartive". the login is successful.
the login name is correct in personal info

![Screenshot 2022-05-04 at 10 55 46](https://user-images.githubusercontent.com/47860090/166650898-bae946a6-9bb3-41f1-8da9-b11180bb09a6.png)

7. create a new user

if there is an option to PRE verify the email, wouldn`t it make sense to have the option for phone as well?

![Screenshot 2022-05-04 at 11 00 12](https://user-images.githubusercontent.com/47860090/166651582-1b36a9f7-e779-4161-930d-ca1dda1d3624.png)

8. infobutton link

![Screenshot 2022-05-04 at 11 01 13](https://user-images.githubusercontent.com/47860090/166651756-890ae162-3361-4e93-8f3f-57bc93aed5aa.png)

the infobutton in the top left corner (besides the domain) leads to the projects overview page, I would have expected the users overview page as I am editing a user

it is correct on the "benutzer" page though

![Screenshot 2022-05-04 at 11 03 04](https://user-images.githubusercontent.com/47860090/166652031-9dbaf5a8-666b-476b-9776-9b0a2f643668.png)

9. infobox text
![Screenshot 2022-05-04 at 11 04 11](https://user-images.githubusercontent.com/47860090/166652186-9a31ca22-a02a-418f-8445-e69b8a20b7f7.png)

"per Du" oder "per Sie". ?

10. new Project

![Screenshot 2022-05-04 at 11 06 08](https://user-images.githubusercontent.com/47860090/166652454-e52bf246-6d0a-48c7-bc93-04d5f6e16912.png)

to my taste, this dialog and the checkboxes should have an info button for further informations, it is pretty technical.

here, this issue is solved fine

![Screenshot 2022-05-04 at 11 08 45](https://user-images.githubusercontent.com/47860090/166652898-0085e058-5759-48d2-a642-254dfe34ee66.png)

11. new application

when a new application is created but no URL is defined, an error occurs, why don't we add a link to the missing information?

![Screenshot 2022-05-04 at 11 09 34](https://user-images.githubusercontent.com/47860090/166653206-dfd03d7d-1293-4219-af3f-1e00e42bdfab.png)

If I enter the URL "manually", "no changes found" error occurs when I hit save button

![Screenshot 2022-05-04 at 11 10 02](https://user-images.githubusercontent.com/47860090/166653284-fed8fa1a-847d-4cf2-8ed8-15eee61b70b5.png)

after I entered the 2 url i was not able to save the application. the check of OIDC config was still failing, no matter which elements I saved. this leads to a "dead end" 

![Screenshot 2022-05-04 at 11 09 34](https://user-images.githubusercontent.com/47860090/166653567-70476dd8-be22-40bd-a12c-5fdb34ecc269.png)

**Comment by thesephirot** [comment]
I guess that might be misleading to some of our customers @  "breadcrumbs"

<img width="341" alt="Screenshot 2022-05-05 at 14 23 59" src="https://user-images.githubusercontent.com/47860090/166923141-611561dd-2927-4d55-99e9-b3999ab3483e.png">
