### ISSUE TITLE
[v2] Change to database config

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#3600]
Add possibility to define the database type in the configuration of ZITADEL.

**Comment by AmreeshTyagi** [comment]
Hi, any plan to initiate discussion on this in near future?

**Comment by hifabienne** [comment]
Hi @AmreeshTyagi 

We don't have a timeline yet for this. Probably we will have a look at this in 1-2 months.
Its planned to start with the possibility to use Postgres as DB.

**Comment by adlerhurst** [comment]
hi @AmreeshTyagi 

The transition to non postgres compatible databases will take more time. This issue is used to track the changes of the configuration. I link your comment in this issue: https://github.com/zitadel/zitadel/issues/3598

**Comment by AmreeshTyagi** [comment]
ok. I understand. Providing postgres compatible first is an obvious choice because of driver compatibility. 

Would be waiting for MySQL plan. Thanks for the response.

**Comment by livio-a** [comment]
closing this as we did the config changes in https://github.com/zitadel/zitadel/pull/4068 and generell database support is tracked in https://github.com/zitadel/zitadel/issues/3598 and postrges https://github.com/zitadel/zitadel/issues/3898
