### ISSUE TITLE
Documentation for PAT is missing

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3678]
Description
Personal access tokens are currently only documented in the API. There's a blog how-to (https://zitadel.com/blog/new-personal-access-token). There should be a guide explaining PAT and how to set it up via API or Console.

**Acceptance criteria**
- [ ] PAT Guide done

**Comment by mffap** [comment]
@hifabienne @livio-a we should provide a guide with an working example on how to use PAT tokens with ZITADEL. See also https://github.com/zitadel/zitadel/discussions/4009#discussioncomment-3190650

**Comment by abogdanov37** [comment]
Hello everyone! I want to understand how to work with PAT. But can't find any documentation or examples. May be some draft are avaliable or any example in client library?

**Comment by abogdanov37** [comment]
> Hello everyone! I want to understand how to work with PAT. But can't find any documentation or examples. May be some draft are avaliable or any example in client library?
Hi! I spent some times to dig into .NET client source codes. If I understand right PAT can be send as usual JWT token. If that to authenticate action on resource server I should go with PAT to Zitadel `/oauth/v2/introspect` endpoint to check token and get full information. Do my thoughts right way or any other options?

**Comment by fforootd** [comment]
Hi - A pat in ZITADEL is basically a ready to use token which can be used as Authorization Header.

To check this token it normally should be, as you concluded correctly, sent to the introspect endpoint.

**Comment by abogdanov37** [comment]
> 

Thank you for reply! Have a nice day!
