### ISSUE TITLE
failed events and views not showing

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#3737]
**Describe the bug**
The tables of `failed events` and `views` don't have entries

**To Reproduce**

1. Click on instance
1. Click on `Views` or `Failed Events` 

**Expected behaviour**

there should be some entries in the table

**Additional context**

You will find additional information in your logs.

**Comment by livio-a** [comment]
was fixed with https://github.com/zitadel/zitadel/pull/3743
