### ISSUE TITLE
Update and improve docs for software architecture

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3756]
[Architecture ](https://docs.zitadel.com/docs/concepts/architecture) docs should be reviewed. Based on some conversations I added some FAQ regarding our software below.

Security
- How are passwords encrypted?

Observability
- What logs do you provide? (Audit vs. System)
- How can I export the logs

Database
- What Databases do you support?

**Comment by mffap** [comment]
@fforootd can you please check if this is done? I know we did some rework, not sure if the points above are fully reflected.

**Comment by fforootd** [comment]
Currently still missing is 


>     What logs do you provide? (Audit vs. System)
>     How can I export the logs

**Comment by mffap** [comment]
relates to #3739

**Comment by fforootd** [comment]
Since I documented this we can close this.
