### ISSUE TITLE
Document self-hosting recommendations

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3757]
It might be useful to collect best practices and general recommendations for users that want to self-host ZITADEL. Based on current conversations, it might make sense to provide some information around the following topics. We could put it under [Installation](https://docs.zitadel.com/docs/guides/installation)

System requirements: 
- Compute
- Database
- Storage

Operational
- Load balancing
- Redundancy
- Backups

 Operational security
- DoS Protection
- Rate limiting
- TLS

**Comment by mffap** [comment]
Relates to https://github.com/zitadel/zitadel/discussions/2079

**Comment by mffap** [comment]
Asked again here: https://discord.com/channels/927474939156643850/927474939156643853/1017360779747536947

**Comment by mffap** [comment]
@eliobischof @fforootd are these points currently answered in the docs in your view? What's missing from that list?

I think we did a good improvement with https://docs.zitadel.com/docs/guides/manage/self-hosted/production

**Comment by fforootd** [comment]
I think that's fine for the moment.

Lets see first what else people want to see.
