### ISSUE TITLE
User Register Broken

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#3763]
When trying to register a new user the following error is stated:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/9879976/171486472-5606a5e9-6452-4f8e-94e1-d37e9dbe96dc.png">

I tested this in our QA env and could reproduce this.

Also relates to @Alexei-Barnes [note in discord ](https://discord.com/channels/927474939156643850/927866013545025566/981549915014578256)

**Comment by Alexei-Barnes** [comment]
Wait, nevermind, I'm bad at docker and didn't actually use the updated software 😭
