### ISSUE TITLE
Terraform provider for ZITADEL

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#3782]
Description

- [x] Create terraform provider for ZITADEL resources
  - [x] action
  - [x] domain
  - [x] domainpolicy
  - [x] labelpolicy
  - [x] lockoutpolicy
  - [x] loginpolicy
  - [x] org
  - [x] passwordcomplexitypolicy
  - [x] privacypolicy
  - [x] project
  - [x] projectrole
  - [x] user
  - [x] projectgrant
  - [x] usergrant
  - [x] orgmembers
  - [x] projectmembers
  - [x] projectgrantmembers
  - [x] API appilcation
  - [x] OIDC application
- [x] Create pipeline to publish terraform provider on terraformhub
- [x] Create example files to use the terraform provider

Github Repository:
https://github.com/zitadel/terraform-provider-zitadel

**Acceptance criteria**
- [x] all necessary resources in ZITADEL can be created through a terraform file
- [x] example files to create all different resources are present

Location of the current WIP https://github.com/zitadel/terraform-provider-zitadel

**Comment by 0x1DA117** [comment]
It would be nice if you could also consider creating a Pulumi provider as well. Pulumi is similar to Terraform, but uses actual programming languages.

They offer a bridge between Terraform and Pulumi to minimize the effort: https://github.com/pulumi/pulumi-tf-provider-boilerplate

They do also have a Pulumi-native way to write a provider: https://github.com/pulumi/pulumi-provider-boilerplate

**Comment by fforootd** [comment]
Hi @0x1DA117 

Thanks for the input. Once we finish our work on the TF provider I think we could work on an pulumi Implementation (in what ever way).

I created a [separate issue](https://github.com/zitadel/zitadel/issues/3875) for the further tracking.

**Comment by fforootd** [comment]
@stebenz since this is in alpha, can we close this and work with the issues from the TF repo?

**Comment by stebenz** [comment]
Sure we can.
