### ISSUE TITLE
Docs for LDAP

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3793]
As a developer I want to be able to connect my LDAP to ZITADEL for login. 

**Acceptance Criteria**
- [ ] I am able to setup a Dex by following the docs
- [ ] I am able to login with a user from my ldap

**Comment by fforootd** [comment]
Ok, let me describe a way with `Dex`

**Comment by FabienZa** [comment]
Hello Florian, I would very much like to know the way to use Zitadel with an LDAP Server by using Dex ! :smile:

**Comment by fforootd** [comment]
👍 I think i can get to that in the next 14 days

**Comment by joostmacantanl** [comment]
Any update on this?

**Comment by hifabienne** [comment]
Hei @joostmacantanl Unfortunately not.
We have decided to implement #5068 and #4609 in the next two months so, we will currently not focus on the dex docs

**Comment by joostmacantanl** [comment]
Implementing LDAP as an Identity provider would render the need for Dex obsolete for my purposes anyway so that's great, thank you for the update.

**Comment by hifabienne** [comment]
We have implemented an ldap identity provider. Due to this Dex is currently not relevant.
You can find the documentation here:  https://zitadel.com/docs/guides/integrate/identity-providers/ldap
