### ISSUE TITLE
Broken Debug/Heathcheck endpoint

### ISSUE THREAD

**Issue by Ruakij** [zitadel/zitadel#3803]
**Describe the bug**
The endpoint for the healthcheck `http://localhost:8080/debug` doesnt work, but instead redirects to `http://localhost:8080/`.

```sh
$ curl -f http://localhost:8080/debug
<a href="/">Moved Permanently</a>.
```

**To Reproduce**
1. Start basic zitadel-instance
2. Run healthcheck e.g. using netshoot in docker

**Expected behavior**
No redirect expected. Not sure what should be there.

**Comment by livio-a** [comment]
@Ruakij do you still need help with this?

there are multiple endpoints under `/debug`:
- `/debug/healthz` <- will always return HTTP 200 OK when the binary started
- `/debug/ready` <- will return HTTP 200 OK if status check are ok, will immediately return NOK when a status check fails
- `/debug/validate` <- will return HTTP 200 OK if status check are ok, tests the checks separately
- `/debug/metrics` <- returns metrics about api calls, ... (if configured)

```bash
 ~ curl -i http://localhost:8080/debug/healthz
HTTP/1.1 200 OK
Date: Mon, 15 Aug 2022 11:15:28 GMT
Content-Length: 2
Content-Type: text/plain; charset=utf-8

ok
```

**Comment by livio-a** [comment]
seems like this is solved. please reopen if you still need help
