### ISSUE TITLE
Email-Address config-option ignored for initial Admin-User

### ISSUE THREAD

**Issue by Ruakij** [zitadel/zitadel#3804]
**Describe the bug**
When setting the email-adress of the admin-user, the field for its email-adress is, by default empty and will then be autogenerated.
Populating this Address wont set the value, but still auto-generate it.

Either the field in [defaults.yaml ](https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/defaults.yaml#L222) or [steps.yaml](https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/admin/setup/steps.yaml#L14), not sure, because they are so similar.

**To Reproduce**
1. Set config-option `DefaultInstance.Org.Human.Email.Address` from [defaults.yaml ](https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/defaults.yaml#L222) and /or  `S3DefaultInstance.Org.Human.Email.Address` from [steps.yaml](https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/admin/setup/steps.yaml#L14) to some valid value.
2. Deploy Zitadel
3. Open console
4. Specified Email-Address doesnt work

**Expected behavior**
When the Address field is set, Zitadel should use this value as admin-user Email-Address.

**Comment by Ruakij** [comment]
Okay, so the address is not fully ignored, but its not the login-email-adress of the initial user.

**Comment by eliobischof** [comment]
@Ruakij the login name is not equal to the email address.
It is `<username>@<org-name>.<instance-domain>`.

See https://docs.zitadel.com/docs/manuals/user-login#login-username

Please reopen if this answer doesn't help you.

**Comment by Ruakij** [comment]
Yeah, sorry. I noticed that too O.o
So sorry, I should have RTFM more closely :)
