### ISSUE TITLE
Authentication callback url with query params not supported

### ISSUE THREAD

**Issue by rtrompier** [zitadel/zitadel#3818]
**Describe the bug**
Login callback url with query params seem not supported.
If my callback url is `http://localhost:4200/?oidc-callback=login` the redirect url generated by Zitadel is `http://localhost:4200/?oidc-callback=login?code=CFHA2RC3EEJIWACkrv48UBXOvYmOxQP9TFW6ykPYaIxzyQ&state=ed8583599c52454780fd5456a11e69c6`

**To Reproduce**
1. Create a client with a callback url containing query params
2. Login
3. Analyse the response url

**Expected behavior**
Zitadel should generate a callback url taking into account the existing query params
The url should be `http://localhost:4200/?oidc-callback=login&code=CFHA2RC3EEJIWACkrv48UBXOvYmOxQP9TFW6ykPYaIxzyQ&state=ed8583599c52454780fd5456a11e69c6`

**Comment by hifabienne** [comment]
Hi @rtrompier 
Thanks for your issue. We will have a look at this. And get back to you.

**Comment by livio-a** [comment]
Hey @rtrompier 

I've just opened a PR fixing this issue in the OIDC library: https://github.com/zitadel/oidc/pull/185
We'll provide a fixed ZITADEL version within the next few days. I'll let you know.

**Comment by livio-a** [comment]
ZITADEL V1 fix: https://github.com/zitadel/zitadel/pull/3852

**Comment by rtrompier** [comment]
Hi there,
Is the new version 1.84.5 is deployed for SAAS users ?

**Comment by livio-a** [comment]
@rtrompier This is now deployed both on zitadel.ch as well as zitadel.cloud
