### ISSUE TITLE
Add start/stop and teadown commands to installation docs 

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3824]

**Comment by hifabienne** [comment]
@eliobischof Can we close this?

**Comment by eliobischof** [comment]
> @eliobischof Can we close this?

No, it's still relevant.

**Comment by hifabienne** [comment]
> 

Please define what should be done in this issue. Till this i will move it to the backlog, looks not ready to start

**Comment by eliobischof** [comment]
I'll move it to *needs more info*, as we should discuss what exactly we want to do

**Comment by hifabienne** [comment]
I will close this for the moment, as it is not specified,
