### ISSUE TITLE
Add redirect_uri config description to OIDC docs

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3825]

**Comment by eliobischof** [comment]
> @eliobischof Can we close this?

I don't know. @mffap this was your requirement. Is it still relevant?

**Comment by mffap** [comment]
> I don't know. @mffap this was your requirement. Is it still relevant?

I'm not clear what this means based on the title tbh.

**Comment by eliobischof** [comment]
does it maybe come from [this discord message](https://discord.com/channels/927474939156643850/927866013545025566/986351681442824279)

**Comment by eliobischof** [comment]
Closing, as requirements are not clear
