### ISSUE TITLE
describe running ZITADEL with systemd

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#3826]

**Comment by hifabienne** [comment]
@eliobischof Can we close this?

**Comment by eliobischof** [comment]
> @eliobischof Can we close this?

No, it's still relevant.

**Comment by hifabienne** [comment]
> > @eliobischof Can we close this?
> 
> No, it's still relevant.

Please define what should be done in this issue. Till this i will move it to the backlog, looks not ready to start

**Comment by eliobischof** [comment]
I haven't recognized a need from the community for this one, so I guess we don't need to plan it for now.
