### ISSUE TITLE
Delete Instance

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3850]
We need a delete instance function. If something failes during the create instance process in the customer portal it should be possible to rollback everything. This also includes deleteing an instance so it is possible to create the same again.

- [ ] Command
       - Remove unique constrains
       - Delete Event on instance
- [ ] Query
- [ ] Update all projections
        - No data with the delete instance id is existing anymore
- [ ] Test
- [ ] Users should not be able to login after
- [ ]

**Comment by fforootd** [comment]
Relates to https://github.com/caos/caos-internal/issues/461

**Comment by livio-a** [comment]
@stebenz started on this yesterday
