### ISSUE TITLE
Contribution Guide v2

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3861]
Update and complete contribution guide for v2

- [ ] Backend / Login: document workflow / configurations
- [x] Console @peintnermax 
- [ ] Testing

**Comment by peintnermax** [comment]
console contribution is here: https://github.com/zitadel/zitadel/pull/3891

**Comment by hifabienne** [comment]
This is duplicate #3673

**Comment by mffap** [comment]
there's an linked PR on this.
