### ISSUE TITLE
[config] allow to change domains

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#3874]
If I deploy ZITADEL i want to be able to reconfigure the following values on each setup. 
```
ExternalPort:
ExternalDomain:
ExternalSecure:
```

At the moment it's only possible to set these values on the first setup.  
The goal is to change these values on each setup.

The proposal is to implement setup steps which are repeatable. These steps should be ensured each time one of the following commands is executed:

- `zitadel start-from-init`
- `zitadel setup`

ZITADEL should verify the defined values and, if not set as defined during the command execution, create events and update the required projections.

The repeatable step to change the 3 values above should create the following events:

- update redirect uris of ZITADEL Console application
- update domain of instance
- update domain of orgs

These events should impact the following projections: 

- generated instance domains (EXTERNALDOMAIN)
- generate org domains (EXTERNALDOMAIN)
- generated login names (username@org-name.EXTERNALDOMAIN)
- oidc config of zitadel project console app (http[s]://EXTERNALDOMAIN:EXTERNALPORT)

Attention: This change will break existing configurations

**Comment by jadedevin13** [comment]
Passing a config file might be better so that it would be easier to create kubernetes configs or docker compose. Having two commands would make it harder to dockerize it.

**Comment by fforootd** [comment]
@jadedevin13 interesting thought, the reason why we currently use two commands is the point that zitadel can start without doing things like schema migrations.

**Comment by adlerhurst** [comment]
The commands already exist they just will be updated. 

We created multiple commands because not all of the checks have to be made after each restart. If you want ZITADEL to do all the checks you can use `start-from-init`. Which will initialize the database, create the events from the setup steps and start ZITADEL at the end.
