### ISSUE TITLE
Generating domains with special characters

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3879]
**Describe the bug**
If I create an organisation with some special characters, this are included in the generated domains. E.g Fabi's --> fabi's.zitadel.cloud

**To Reproduce**
1. Create a new customer portal organisation with a special character

**Expected behavior**
We should remove all the special characters (excluded - and .)

- [ ] Special Characters should not be able to add on a domain
- [ ] Customer Portal should show error when special characters included in domain

**Comment by livio-a** [comment]
we still should solve punycode (unicode representation for hostnames)
