### ISSUE TITLE
ZITADEL Resources shall be provisioned through GitOps

### ISSUE THREAD

**Issue by thesephirot** [zitadel/zitadel#3881]
Description

Resources such as Projects, Applications, Users, Authorizations shall be provisionable through a GitOps approach such as Argocd, etc. 

**Acceptance criteria**
- [ ] installation of a clean ZITADEL is done 
- [ ] a example application gets registered through gitops and is able to authenticate

**Comment by fforootd** [comment]
relates to #3782

**Comment by hifabienne** [comment]
@fforootd Can I close this issue?

**Comment by fforootd** [comment]
Lets close it for the moment
