### ISSUE TITLE
Help Icon for Keyboard Shortcuts not selectable with Keyboard

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3909]
Currently the help for the keyboard shortcuts can't be accessed by keyboard navigation. make it selectable and make it visible as selected (see example of selection border in Customer Portal, or below):

![Image](https://user-images.githubusercontent.com/48990649/177757493-10b56dfc-69b5-48d8-b970-db5752b464e2.png)

**Comment by hifabienne** [comment]
This is a dublicate https://github.com/zitadel/zitadel/issues/4797
