### ISSUE TITLE
Create new User with mandatory fields only showing

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3910]
As an admin I want to create users with the mandatory fields most of the time, so this is the only infomraiton that should be shown. Other fields are collapsed and can be expanded.

**Acceptance Criteria**
- [ ] When creating a user I only see all the required fields
- [ ] I have a link to expand, If I click it I get some additional fields that are not mandatory

![Image](https://user-images.githubusercontent.com/48990649/177758087-838354d6-3d43-4b8f-8a62-c4ed097e5b1e.png)

![Image](https://user-images.githubusercontent.com/48990649/177758397-b8476d4c-d45f-42a2-9535-667d225de61a.png)

**Comment by hifabienne** [comment]
I would remove it, they can fill it in the edit section

Can we also show how the login name looks? like on the registration from? 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/38692350/177788943-b8854ed8-4992-4dff-8c20-b44f7345bca9.png">

**Comment by hifabienne** [comment]
Will close this for now, as this will change with #6433
