### ISSUE TITLE
Changing User Name Behavior

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3917]
Why does the user have to press on modify when he wants to edit the username and why is it not a normal input field to edit like the other (first name, last name etc..)?

![Image](https://user-images.githubusercontent.com/48990649/177764422-8c767751-7156-49c4-93dc-604d6f70322a.png)

It's an unnecessary click for the user.

Especially since it is one coherent form in 'create new user'

**Comment by peintnermax** [comment]
I'd let this as it is as long as there are two seperate API request that have to be made.
If the backend provides a simple method for changing the profile, I would take another look.
