### ISSUE TITLE
Phone number Validation behavior

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3918]
As an admin or end user I want to be able to enter my phone no matter of the format without it being refactored while typing.

**Acceptance Criteria**
- [ ] I am able to enter spaces while entering my phone number
- [ ] I can enter 00XX as country prefix (it changes when I click save)
- [ ] I am able to enter 00 and a non swiss prefix
- [ ] The number is not formatted while I enter it
- [ ] The number is formatted when I click enter
- [ ] I am able to choose the country prefix with a dropdown

**Additional context**

see google contacts for a good example how to implement it (TL;DR: allow all inputs and after saving trunkate it to a coherent template (no spaces, country prefix with +, etc..)

The copy text is not very intuitive on how to enter the phone number (no example, not stating any format (i.e. country prefix)). this issue might get obsolete if the following things are improved:

![Image](https://user-images.githubusercontent.com/48990649/177766386-94deccd7-79ca-40c2-8cfe-9becf5deb0b3.png)

**Comment by doncicuto** [comment]
Hi @hifabienne and @juergrinaldi,
I've been working on this issue and think it's ready, could you assign it to me? Also I'd like to discuss my suggested solution before I send my PR [here](https://github.com/zitadel/zitadel/discussions/5115).

Cheers!

**Comment by hifabienne** [comment]
Hei @doncicuto Thank you very much. 
I think @juergrinaldi should have a look at it from the ux perspective and @peintnermax would be the right one for frontend implementation.

**Comment by juergrinaldi** [comment]
@doncicuto @hifabienne I added my comments in #5115 . But generally speaking it looks good to me. 👍
