### ISSUE TITLE
Toastmessages Change

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#3920]
As an user of ZITADEL console I want to see the errors as easy as possible, and they should not disappear after I while so If i missed it I don't know what happend.

**Acceptance Criteria**
- [ ] Critical error messages do not disappear after a while (for example errors on forms (missing inputs, wrong format, etc..))
- [ ] Critical errors disappear only when I close them or when I redo the action (e.g resend the form)
- [ ] The error message is shown next to the input that is wrong

**Comment by hifabienne** [comment]
will close this issue at the moment, has never been mentioned by a customer
