### ISSUE TITLE
Access ZITADEL APIs guide outdated

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#3975]
With v2 the following guide needs to be updated: 
https://docs.zitadel.com/docs/guides/api/access-zitadel-apis

The scope `urn:zitadel:iam:org:project:id:69234237810729019:aud` changes for every instance. To find out the correct ID, a user must navigate to the domain-org and select the project `ZITADEL`.

![image](https://user-images.githubusercontent.com/1366906/179219989-bab96bf9-8f66-4958-8567-bdaae6c78596.png)

Also references to zitadel.ch should be removed.

**Comment by livio-a** [comment]
IMO we should also take a look at it in #3573 and we'll have to change this the following section anyway so we could as well state it there
![image](https://user-images.githubusercontent.com/9405495/179687656-37d49ec0-b97c-4cd4-9e3f-491666a0ae16.png)

**Comment by fforootd** [comment]
I think @livio-a is right we should display that info directly to the user.

Btw. Some of that info is already present in the env.json

**Comment by livio-a** [comment]
update the scopes / guides in #4112

**Comment by fforootd** [comment]
Since #4112 was merged I think we can /close this
