### ISSUE TITLE
Document Metrics Endpoint

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3985]
The metrics endpoint should be integrated in the documentation.

**Acceptance criteria**
- [ ] Add metrics endpoint
- [ ] How can customers access data from the metrics
- [ ] What kind of metrics are included
- [ ] Document how users know if ZITADEL is running, healthz endpoint, readiness, etc.

**Comment by mffap** [comment]
@fforootd can you please have look at this and do a first version until 19.9.
I would suggest one page under APIs with a brief description of what we have and where to find it. Maybe explain how to authenticate (if different than: https://docs.zitadel.com/docs/guides/integrate/access-zitadel-system-api or https://docs.zitadel.com/docs/guides/integrate/access-zitadel-apis)
