### ISSUE TITLE
Login Screens Design

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3986]
Go over all login flow screens and define ux/ui/text improvements or if the screen is ok. Some parts we already had with the prototype test. 

**Acceptance criteria**
- [x] Select User
- [x] Username
- [x] Password
- [x] Setup MFA Choose
- [x] Setup MFA OTP
- [x] Setup MFA U2F (Universial Second Factor)
- [x] Setup MFA Done
- [x] Passwordless Choose
- [x] Passwordless Registration
- [x] Passwordless Registration Done
- [x] Init user
- [x] Init user done
- [x] Password Change
- [ ] Link User (External Identity Provider)
- [x] Register

**Comment by juergrinaldi** [comment]
I added all my findings very crudely here in this doc and - as mentioned by @fforootd - not made any issues out of them.
https://docs.google.com/document/d/195TRoG6_JF7DPDgwJbunNLUw5gmM8RK-kW7js83cXx8

Let me know what you think and if you need more informations on some parts.

**Comment by mffap** [comment]
@juergrinaldi is this issue complete, then? Do we have everything as per checklist above?

**Comment by juergrinaldi** [comment]
except Link User, yes.

**Comment by fforootd** [comment]
> except Link User, yes.

Are you still working on this? Since it is not assigned I am confused 😁

**Comment by juergrinaldi** [comment]
Isn't that a set design from the ID providers and not up for discussion?
i.e. if you choose Google/Gmail Login, that it will get handed over to Google for the identification process and with that coming with the Google UI?

Or did I missinterpreted the input above?

**Comment by fforootd** [comment]
Well yes but as the data is returned from an external provider there are two potential ways of dealing with it:

A) we autoregister the user there is no action needed
B) The user is allowed to link his user to an existing user in zitadel, in which case there is the need of a guided process to make this happen

**Comment by juergrinaldi** [comment]
oh. I see. I wasn't aware of that. (I was expecting A)
I'll take another look then.

**Comment by hifabienne** [comment]
I will close this issue. We have created others for each page and I think most of it is already implemented
