### ISSUE TITLE
Add more customization to private labeling

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3988]
The private labeling policy should have more customization possibilities

**Acceptance criteria**
- [ ] Add customization defined in #3987 
- [ ] Command
- [ ] Query
- [ ] Tests

**Comment by fforootd** [comment]
We need to wait for https://github.com/zitadel/zitadel/issues/3987 to complete to further proceed with this

**Comment by hifabienne** [comment]
Will close this issue as the feature is described in the linked issue, when we see it will be relevant/start the implementation we will have a look what it is needed
