### ISSUE TITLE
Evaluate framework for login flow templates

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3989]
To have more flexibility on the login screen design, we want to enable some html templates. At the moment the login is implemented with gohtml. this decision should be questioned and a framework that allows adjustments to the ui should be evaluated
Possibility Liquid

**Acceptance criteria**
- [ ] Evaluate Template Framework
- [ ] Define how this can be implemented within ZITADEL

**Comment by peintnermax** [comment]
I'd preferably use a frontend framework like nextjs or svelte (-kit) for the new UI, something capable of hydrating the UI in the most efficient way, such that assets are not reloaded on every server side call, and for user customization I would use shopifys liquid templating which is also opensource.

https://shopify.dev/api/liquid

**Comment by hifabienne** [comment]
@fforootd @peintnermax are you on this issue? Or do we have some other issues for this and close it or put it to backlog?
Please remove you from the assignee list if you are not working on it

**Comment by fforootd** [comment]
We settled for nextjs since we have prior experience and wanted something that can be rendered on a server.

I am currently not working on this.

**Comment by peintnermax** [comment]
started a project with nextjs 13 and tailwindcss. Will migrate ownership to soon 👍

**Comment by hifabienne** [comment]
Ok so I will close this issue since we did evaluate.

**Comment by SaraiQX** [comment]
Hi everyone, 
Great thanks to this solution. Just wonder will sevltekit template be expected?
