### ISSUE TITLE
Define how to refactor login

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#3992]
We already know that the ZITADEL login flow should be refactored. This will contain different tasks that need to be clarified. e.g Remove eventstore v1 completely, user same components for the same things (identity brokering), passwordless register, etc. 

**Acceptance criteria**
- [ ] Use eventstore v2 instead of v1
- [ ] store authrequests in eventstore
- [ ] ...

**Comment by adlerhurst** [comment]
slides 5 and 6 of the following jamboard: https://jamboard.google.com/d/1kz646GB_MXmHjX4sq05dXW3IwO2b35Fv3_rIjTMp8Ys/edit?usp=sharing

**Comment by adlerhurst** [comment]
drawings: https://jamboard.google.com/d/1ShViHHPeuBEidaRZPrxgUkXzISGUK6ow1kF85bEl-TU/edit?usp=sharing

**Comment by hifabienne** [comment]
I will close this issue. We do have separat issues for the eventstore part #4947 
and the refactoring has to do with the new login api
