### ISSUE TITLE
[Database]: improve statements / indexes to reduce full table scans

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#3995]
At the moment there are a lot of full table scans, which decrease performance of the api and furthermore require more resources of the database itself.

Improvements can be made by fixing the order of the columns of the primary keys (instanceID must always be first)

**Acceptance criteria**
- [ ] Identifiy slow statements
- [ ] Improve statements

**Comment by fforootd** [comment]
Some of this is subject to be improved with #3898 

We park this until we release #3898

**Comment by livio-a** [comment]
performance was improved a lot by #4300 by creating two indexes (one for the write models and one for getting the latest active instances) and further changes in the spooling process

the changes in the spooling process could be applied to the old views (auth and admin) as well

**Comment by livio-a** [comment]
multiple PRs that focused other issues also reduced this problem, incl.
- https://github.com/zitadel/zitadel/pull/4612
- https://github.com/zitadel/zitadel/pull/4632

**Comment by hifabienne** [comment]
@adlerhurst can we close this issue? since we did already merge some prs that should have improved? Or did I read the comments wrong?
