### ISSUE TITLE
[OAuth]: add more claims to introspection response

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#3996]
RFC7662 Token Introspection https://datatracker.ietf.org/doc/html/rfc7662#section-2.2 specifies that only claim `active` is required to be returned. Additionally we also return `scope`, `client_id`, `username` and all requested claims according to userinfo response (incl. `sub`, `iss`)

We should also add `token_type`, `exp`, `iat`, `nbf`,  `aud`, `jti`
This would also allow libraries to cache the response more efficiently.

Requires changes to the OIDC Library.

**Acceptance criteria**
- [x] the claims above are returned on the response
- [x] documentation

**Comment by livio-a** [comment]
fyi @buehler

**Comment by fforootd** [comment]
this to some degree relates to #3997
