### ISSUE TITLE
Rate limits need to be updated for zitadel.cloud

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4000]
Update the rate limits with the correct domains under zitadel.cloud

- [ ] https://docs.zitadel.com/docs/apis/ratelimits/accounts
- [ ] https://docs.zitadel.com/docs/apis/ratelimits/api

Update the rate limit policy (how is the rate limit implemented): 

- [ ] https://docs.zitadel.com/docs/legal/rate-limit-policy

The latter has changed to my understanding (throttling and then blocked for some time).

**Comment by mffap** [comment]
@eliobischof maybe something for you?

**Comment by fforootd** [comment]
https://github.com/caos/zitadel.cloud/blob/main/armor.tf
