### ISSUE TITLE
Authorize endpoint returning a status 200 instead of redirect

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4002]
When calling a console link with login_hint parameter `?login_hint=[username]`, which is triggering a login flow with login prompt, the authorize endpoint is sometimes returning a 200 instead of a redirect and is therefore interrupting the login. The browser results in a blank page.

**Comment by livio-a** [comment]
@peintnermax i cannot reproduce this. Do you still get this issue and if so can you please share me a link or a HAR file?
