### ISSUE TITLE
Too many events on project grant audit

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4004]
**Describe the bug**
The change log on a project grant shows to many changes. It looks like there are all events from the whole project shown and not only of the project grant.

**To Reproduce**
1. Go to a projec grant in the console
2. See last changes
3. To many events

**Expected behavior**
Should only show events from the project grant

**Screenshots**
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/38692350/179952458-7793c21b-9c04-4e93-ae91-8d43efd28ff3.png">

**Comment by fforootd** [comment]
@hifabienne what about this ones prio?

**Comment by livio-a** [comment]
i fixed this while i had to fix other project grant stuff 😄
