### ISSUE TITLE
Session not terminated when logging out of console

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4013]
**Describe the bug**
Given I have an existing user
and the user is logged into the console
When I click on "Logout All Users"
Then I can login back by only providing my user name (no password/mfa prompt)

**To Reproduce**
As described above.

**Expected behavior**
When I click on "Lougout All Users" the sessions are terminated and I have to re-authenticate

**Screenshots**
![screencast-b2b-demo-rbxajm zitadel cloud-2022 07 21-10_54_19](https://user-images.githubusercontent.com/1366906/180173460-58c81eb8-c12a-408b-9016-31b26a2f1418.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Version 103.0.5060.114 (Official Build) (64-bit)

**Additional context**
- I cleared the application data before shooting the video
- Same behavior when logging out of a third party application
- The account selector is not shown to me. I assume this to happen when I login with a user that has the structure loginname@organization
.instanceDomain.zitadel.cloud

**Comment by mffap** [comment]
@hifabienne for prioritization. I won't open a new issue for the account selector for now, based on your assumption, that both issues might be connected.

**Comment by fforootd** [comment]
Interesting I just tried to recreate this but it did work as intended.

https://user-images.githubusercontent.com/9879976/180239018-cef19652-0951-4af3-91fc-14496604fe85.mp4

**Comment by mffap** [comment]
Both the account picker and signout through console seem to work now again (for me). You may close at your discretion, if you think this has been fixed.

**Comment by fforootd** [comment]
I this PR #3978 was the root cause for the problem you experienced here.

At least that was what i could reproduce locally 😁
