### ISSUE TITLE
SetUserMetadata throws User could not be found when updating on own user

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4025]
When setting user metadata on the logged in user (users/me), the management service throws ths error (User could not be found)

**Comment by hifabienne** [comment]
I think this error is strance, but an Set metadata method doesn't exist on the auth api.

**Comment by peintnermax** [comment]
The requests (for organization users and for the own user) are both made on the management service, either we provider a function for auth service or we should ensure it works on management

**Comment by hifabienne** [comment]
In my opinion you should use the management api, but for the own user you should send the id instead of the "me"
I guess this is the problem right now. We do the request by ID if you send "me" you will not find a user

**Comment by peintnermax** [comment]
the angular route has nothing to do with the api call. As you can see in chrome dev tools, the id is set 
<img width="385" alt="Bildschirmfoto 2022-08-02 um 13 44 08" src="https://user-images.githubusercontent.com/10165752/182366589-ade3d8bb-ed05-4487-9f33-615e7b089f5f.png">

**Comment by hifabienne** [comment]
I just tested all the different possibilities.
No matter if I go to edit account in the menu and set the metadata or if i choose my own user in the users list. I am able to set the metadata

**Comment by peintnermax** [comment]
seems to be an issue on my .app instance.. works fine with .cloud instances 🤔

**Comment by livio-a** [comment]
@hifabienne just discussed and tested with max as well... worked so far

one question still remains: edit account (my user) also calls management api because there is no endpoint on the auth api to edit the own metatada. Do we need the possibility to edit the own metadata or is it for other users only?

**Comment by fforootd** [comment]
My2cents. I don't think the user should edit his metadata, since it is only there to store additional fields used by services.

**Comment by hifabienne** [comment]
in my opinion we dont need it thats why it doesnt exist on the auth api. i dont see a use case where the user shoul add data himself

**Comment by livio-a** [comment]
@peintnermax can you please remove the edit from the "edit Account" page

**Comment by peintnermax** [comment]
Are you sure? If I remove it you need at least two users to edit metadata.. You can't open your own user on management site as it will redirect to users/me 🤔

**Comment by livio-a** [comment]
ok.. so the write permission is checked anyway, right? if so i believe we can close this issue

**Comment by peintnermax** [comment]
added the requirement for user.write to show the metadata section on /users/me in this PR https://github.com/zitadel/zitadel/pull/4136

**Comment by livio-a** [comment]
IMO displaying the metadata is ok for every user (auth api already allows that: `ListMyMetadata`), but they must not be able to edit / add them

**Comment by peintnermax** [comment]
true.. changed it to your suggestion 👍
