### ISSUE TITLE
endpoint end_session -- error 404 - not found

### ISSUE THREAD

**Issue by MLStoltzenburg** [zitadel/zitadel#4034]
**Describe the bug**
We have our own instance and when we tried to access the end session endpoint, we got http 404 error.

In this link you can see the available endpoints: https://auth.stolzlabs.com/.well-known/openid-configuration

We only got the 404 error at https://auth.stolzlabs.com/oidc/v1/end_session.

what are we doing wrong?

**Version**
Zitadel version v2.0.0-v2-alpha.43
The same happened in the older versions.

**Comment by fforootd** [comment]
Hi 

I think there could be a bug how the endpoint reacts. Currently you should receive a 302 that redirects to a broken link instead of returning a 200 code.

If you invoke the endpoint you should be logged out even thought the redirects makes no sense.

@livio-a lets us have a look on this on Monday.

**Comment by fforootd** [comment]
@MLStoltzenburg 

I can confirm there is a 🐞 if you directly call the `end_session` endpoint 😁 


However your application normally will call the endpoint while supplying at least the `id_token_hint` while optionally specifying additional params `post_logout_redirect_uri`, `state`. We built on the draft spec of [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html)

**Comment by MLStoltzenburg** [comment]
Hi,

You are right!
When I put the id_token_hint I got 302 where the redirecting to logout page was done, but I have a question.

How to know if the token has been invalidated? Because when I went back to the login page the user was still active.

BTW, I request the end_session endpoint directly and not using AppAuth or Webview.
I don't like when I open another screen over the App, so I developed the PKCE standard within the App and I got successful in the login process through webview.
I've been using the same routine with Keycloak for months and it's working great. My problem with Zitadel is when I need to log out. 
 
Another situation:
I ran the same command couple times via cURL and realized that it always returns 302, I believe that after the first logout with the same token the result should be "not permission" or "invalid token", but I'm not sure.

Thanks!

**Comment by fforootd** [comment]
> When I put the id_token_hint I got 302 where the redirecting to logout page was done, but I have a question.
> How to know if the token has been invalidated? Because when I went back to the login page the user was still active

So you were able to login without any need for authentication?

> BTW, I request the end_session endpoint directly and not using AppAuth or Webview.
> I don't like when I open another screen over the App, so I developed the PKCE standard within the App and I got successful in the login process through webview.

That's good to know. ZITADEL stores a cookie for each user-agent to handle the sessions of multiple users.
So what acutally work besides sending the id_token_hint is to just call the end_session endpoint with that cookie (__Secure-zitadel.useragent) present. This should invoke a 302 to the default post_logout_redirect (this is where we have the bug)

> I ran the same command couple times via cURL and realized that it always returns 302, I believe that after the first logout with the same token the result should be "not permission" or "invalid token", but I'm not sure.

This is somewhat undefined in the [spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ValidationAndErrorHandling) but I think it would be worth to return an error directly instead of redirecting
What are your thoughts on this @livio-a

**Comment by MLStoltzenburg** [comment]
@fforootd 

> So you were able to login without any need for authentication?

Yes! 
I noticed that even running the endession endpoint, the __Secure-zitadel.useragent is still active, but remember I ran it outside of the webview, so the Zitadel Cookies was not updated.

I believed that the token would be revoked after the session ended.

I tested another weird thing:
I opened a browser and executed the end session endpoint link with another user's id_token_hint and my active session disconnected!

For example: "In my browser I was logged in with user A, I opened a new tab and ran the end session endpoint with user B's token, so user A was also logged out"
 
In my opinion this cannot happen. Right?

**Comment by fforootd** [comment]
> I believed that the token would be revoked after the session ended.

The token should be immediately invalid, but since the session of the user persist you get a new one easily

> I opened a browser and executed the end session endpoint link with another user's id_token_hint and my active session disconnected!
>In my opinion this cannot happen. Right?

Hm this sounds like a precedence bug, @livio-a we should look into this one

**Comment by MLStoltzenburg** [comment]
> The token should be immediately invalid, but since the session of the user persist you get a new one easily

I understood! So, do I need to update   __Secure-zitadel.useragent to work fine?

I have an idea! Once I get the response, I'll update the cookie in my webview and check the result!
I know when I clear cookies in the webview the user has to enter a username again, but I would like the user don't do that, just enter their password, like on browser.

Question: What the cookies do i need update, only __Secure-zitadel.useragent or something else?

**Comment by fforootd** [comment]
> I understood! So, do I need to update __Secure-zitadel.useragent to work fine?

It only must be present during the call to end_session.

> Question: What the cookies do i need update, only __Secure-zitadel.useragent or something else?

I think you need to allow csrf cookies as well but only the cookie above is relevant for the user session.

**Comment by MLStoltzenburg** [comment]
@fforootd 

It works!
I got successful now!
I put the cookie in my direct command and I could do logout in right way.

The user now is inactive!

Thank you very much for your help!

**Comment by fforootd** [comment]
Awesome 👏

**Comment by livio-a** [comment]
fixed with #4054
