### ISSUE TITLE
Document NGINX setup

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4037]
## Description

We should document how to setup zitadel behind a nginx

Since we make use of http2 we need to force nginx to send upstream connections in the correct way.

**h2c**
`grpc_pass grpc://localhost:8080;`

**http2 (with TLS)**
`grpcs_pass grpc://localhost:8080;`

**pass host header**
`proxy_set_header Host            $host;`

**Acceptance criteria**
- [ ] Documented nginx setup

**Comment by fforootd** [comment]
FYI @hifabienne @eliobischof

**Comment by eliobischof** [comment]
I think we should list proxy examples minimally in https://docs.zitadel.com/docs/guides/installation/loadbalancing-example

**Comment by fforootd** [comment]
Well, the current example is way more then a simple advice for a config.

If think we should stick to config only examples.

Some parts of it can be applied to all proxies. E.g the tlsmode.

**Comment by eliobischof** [comment]
Or maybe even better: https://docs.zitadel.com/docs/guides/installation/http2-support

**Comment by eliobischof** [comment]
You are referring to the http2 support in particular, aren't you?

**Comment by fforootd** [comment]
> You are referring to the http2 support in particular, aren't you?

Mostly, but other things could be as well.

**Comment by eliobischof** [comment]
maybe we can pack the (new) tlsmode docs there too

**Comment by fforootd** [comment]
> maybe we can pack the (new) tlsmode docs there too. And rename the page to Proxy Configuration or Ingress Configuration or something similar?

Let me  make a proposal 😁
