### ISSUE TITLE
Domain verification setting is not respected

### ISSUE THREAD

**Issue by shedar** [zitadel/zitadel#4039]
**Describe the bug**
A newly added domain requires verification with the domain verification checkbox turned off on instance and org levels.

**To Reproduce**
1. Go to 'Instance -> Settings -> Domain Settings'
2. Uncheck 'Validate Org domains' and Save
4. Go to any Organization
5. Go  to 'Settings -> Domain Settings'
6. Uncheck 'Validate Org domains' and Save
7. Go to the organization "Domains"
8. Add a new Domain
9. The new domain is unverified

**Expected behavior**
A new domain is to be marked as verified if domain verification is turned off.

**Screenshots**
<img width="442" alt="Screenshot 2022-07-25 at 05 39 05" src="https://user-images.githubusercontent.com/477298/180685940-f795f097-7801-4877-801b-5950641beaea.png">
<img width="1309" alt="Screenshot 2022-07-25 at 05 39 37" src="https://user-images.githubusercontent.com/477298/180686006-62302f25-df5b-4e76-aa20-94199ad14683.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version [v2.0.0-v2-alpha.43](https://github.com/zitadel/zitadel/releases/tag/v2.0.0-v2-alpha.43)

**Additional context**

**Comment by hifabienne** [comment]
Hi @shedar 
Thanks for your report. I could reproduce your bug an we will have a look at it.

**Comment by fforootd** [comment]
This bug was also reported in our discord channel https://discord.com/channels/927474939156643850/927866047757959189/1000749796019146772
