### ISSUE TITLE
When uploading a new profile picture, not the new but the old is shown

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4049]

**Comment by peintnermax** [comment]
seems to be a caching issue because the name is the same as the old file

**Comment by fforootd** [comment]
This looks like an eventual consitency problem to me. What happens if you try to wait a few ms?

At least IMO the image is not cached. No cache-control header, which is an other problem 😁

**Comment by peintnermax** [comment]
Wait does not do it for me. Looks like its a problem with chrome. Firefox is working fine.
Seems like chrome is ignoring the change due to the same file name 🤷‍♂️
When disabling cache in chrome's dev tools the image gets replaced instantly..

**Comment by peintnermax** [comment]
also chrome seems to load the image from memory cache therefore ignoring the etag.. maybe a hash as the filename would do the trick.

**Comment by livio-a** [comment]
I will check why the cache header is missing. Etag should work once there's an cache header

**Comment by peintnermax** [comment]
Thx 👍
