### ISSUE TITLE
Usernames are not checked for duplicates across organizations

### ISSUE THREAD

**Issue by pr0gr8mm3r** [zitadel/zitadel#4051]
**Describe the bug**
It's possible to create multiple users with the same loginname when they're in different organizations.
Only works if you disable checking for whether the loginname contains the org domain.

**To Reproduce**
1. Create an organization
2. Create a user. Change its loginname to "user"
3. Create another organization
4. Create a new user in the second organization. Change its loginname to "user"
5. There is no error

**Expected behavior**
I expect to be warned about that, because one of the users can't login to the console anymore.

**Version used**
[v2.0.0-v2-alpha.43](https://github.com/zitadel/zitadel/releases/tag/v2.0.0-v2-alpha.43)

**Comment by fforootd** [comment]
Hi @pr0gr8mm3r, thanks for reporting this! 

I tried reproducing this one but i receive an error.

What I did:

- Create two orgs each with the "User Loginname must contain orgdomain" off
- Create a user in org 1 with the name "test1234@1234.123" - Success
- Create a user in org 2 with the name "test1234@1234.123" - Failed
- Create a user in org 2 with the name "test1234@1234.124" - Success
- Rename the user in org from "test1234@1234.124" to "test1234@1234.123" - Failed

![image](https://user-images.githubusercontent.com/9879976/181115949-73fc3064-5caa-411d-80b0-7572a373dad4.png)

@pr0gr8mm3r can you provide us screenshots from the two users?

**Comment by pr0gr8mm3r** [comment]
Hm, can't seem to be able to reproduce it anymore. Might have been a typo or something on my end.
Consider this closed, thanks for your quick response.

**Comment by fforootd** [comment]
👍 happy to help.

We like when people report potential issues.
