### ISSUE TITLE
Unable to run Zitadel from fresh install

### ISSUE THREAD

**Issue by mattmalec** [zitadel/zitadel#4053]
**Describe the bug**
When running a fresh install of Zitadel using the Docker Compose yaml provided from [the docs](https://docs.zitadel.com/docs/guides/installation/run), it will start fine. However, when navigating to `my.domain:8080/ui/console`,  the browser console shows:
```
ERROR TypeError: Cannot read properties of undefined (reading 'getMyPrivacyPolicy')
TypeError: Cannot read properties of undefined (reading 'getMyPrivacyPolicy')
ERROR TypeError: Cannot read properties of undefined (reading 'getMyUser')
```
and the background is completely white with no content.

For context, the host system I'm using is Rocky Linux 8.6 (`4.18.0-372.9.1.el8.x86_64`)

**To Reproduce**
1. Go to https://docs.zitadel.com/docs/guides/installation/run
2. On the host system, run
`wget https://raw.githubusercontent.com/zitadel/zitadel/v2-alpha/docs/docs/guides/installation/run/docker-compose.yaml`
3. Then run `docker compose up -d`
4. Navigate to `http://domain:8080/ui/console`
5. See error in browser console

We can also observe this behavior when running standalone without Docker as well.

**Expected behavior**
Zitadel to operate like normal so I have the ability to use it :)

**Screenshots**
![Screen-Shot-2022-07-27-01-16-28](https://user-images.githubusercontent.com/32992688/181166952-573c2697-da75-4c59-aaed-9f314aeb7ded.png)

**Desktop**
 - OS: macOS
 - Browser: Chrome
 - Version: 103.0.5060.134 (latest)

**Comment by fforootd** [comment]
Was resolved in a discord chat https://discord.com/channels/927474939156643850/927866013545025566/1001931812089647185

**Comment by jyio** [comment]
How was this resolved? I'm encountering the same issue.

**Comment by fforootd** [comment]
> How was this resolved? I'm encountering the same issue.

This error happend because the domain settings where not set properly for ZITADEL to start.
Or in other words. If you want to run ZITADEL on something else then http://localhost:8080 you need to configure that.

So for example if you want to run ZITADEL on http://my.domain:8080 you need to supply this configs to ZITADEL:

```
ExternalDomain: 'my.domain'
```

More infos can be found here. https://docs.zitadel.com/docs/guides/manage/self-hosted/custom-domain#standard-config

What deployment are you using?

**Comment by jyio** [comment]
That was the key insight. Thank you for sharing with the class 😉

I'm using the docker-compose deployment. I'm setting these options using environment variables.
Next little snag I ran into was end-to-end HTTP/2 with my reverse proxy, and of course it's also documented somewhere. With Caddy, for example, one would specify `reverse_proxy h2c://zitadel_host:8080`.
So far I'm still exploring and learning. I appreciate all the thought and effort that went into this amazing piece of work. *Thank you.*

Maybe the next version could have more informative errors? Or links in the quickstart guide to call out these common issues that are not necessarily encountered in a "production grade" deployment.

**Comment by fforootd** [comment]
> Maybe the next version could have more informative errors? Or links in the quickstart guide to call out these common issues that are not necessarily encountered in a "production grade" deployment.

True that is certainly something to improve 😁 

> Caddy, for example, one would specify reverse_proxy h2c://zitadel_host:8080.

Did you find our caddy docs or did you needed to fiddle this out?

**Comment by jyio** [comment]
Oh, I didn't realize you had Caddy docs. I found it now. My Google-fu is lacking :3
