### ISSUE TITLE
Can't create new account when already logged in before

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4056]
If I already used ZITADEL before (and with that have some login profiles already set), I can't get to the register form via website or direct URL (zitadel.cloud). I always land on the login form with no link to register new.

![Image](https://user-images.githubusercontent.com/48990649/181195121-a6bfc787-8081-4d54-b10b-874bed532216.png)

-> Solution: Have a 'Register' Link/Button (I suggest a tertiary, similar to 'Login here' on register page) on the Login Page at all times.

**Comment by hifabienne** [comment]
@juergrinaldi unfortunately this is not possible right now. The login page is hosted by ZITADEL and we can not include "custome" buttons on it.
We have 2 options when open the url zitadel.cloud
1. Show the ZITADEL Cloud Register"
2. If user already has some sessions show login/directly loged in to customer portal

@livio-a @fforootd what do you think about this?
In my opinion this is ok right now. So we show directly the login. Because most users will not have multiple customer portal users. 
4.

**Comment by juergrinaldi** [comment]
@hifabienne not sure if I understand that right ( 🙈 ) but I didn't mean a custom button. Just a "global" button that leads to the register form.

And I don't think it's okay the way it is. I understand that this usecase isn't hitting most of our customers and we don't have to optimize for this case, but since it's pretty much a user-flow breaking issue, I think we should provide a solution so users don't get 'stuck'.

**Comment by hifabienne** [comment]
From the ZITADEL perspective this would be a custom button. We are using our own system (login) for this. Which doesn't allow us to just include other buttons or elements. This is something we want to include in the future with the custom templates but at the moment not possible.

**Comment by livio-a** [comment]
@hifabienne i've just discussed with @juergrinaldi... we might have to do something like a custom button in the future, but first of all we need to wait for the implementation of handling multiple sessions in the customer portal anyway. @peintnermax  whats the status on this?

**Comment by peintnermax** [comment]
going to be merged.. https://github.com/caos/customer-portal/pull/384

**Comment by hifabienne** [comment]
@livio-a @peintnermax can we close this issue? I believe we would need to handle this when we are able to build own login own login ui?
