### ISSUE TITLE
After registration my new account isn't showing on login page

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4059]
As an end user I want to be authenticated if I had to enter all the needed authentication data to initialize my user already, so I do not have to reenter my username and my password.

At the moment I get redirected to the login page after registering (initialize), but the newly registered account is not showing in the select account list, but some of the old ones. This is very confusing as it isn't completely clear that I have to click on 'other user'.

Acceptance Criteria:
- [x] If I have just initialized my user and just created a new password I want to either be directly loged in or see the mfa prompt screen (depending on the settings of my organisation)
- [x] If I have just initialized my user without setting a new password (because I have already one), I want to see the password screen next and my just initialied user should be selected

**Comment by mffap** [comment]
I have realized this also in the my latest testing. It is frustrating to re-authenticate right after initializing the user.

This feedback came also up in a recent talk with a customer.

If high-security is an issue, there should be an opt-out possible imo.

**Comment by livio-a** [comment]
Got some feedback from customers related to this issue, where their users self register and need to reenter the password just after registration again.

**Comment by akaegi** [comment]
I can confirm that password re-entry after registration is now not needed anymore. Thank you for fixing that 🙂
