### ISSUE TITLE
DNS Verification not working

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4086]
I was reported with a problem around the DNS verification for the org domains and could reproduce it.

When verifying a challenge i.e `dig txt _zitadel-challenge.dns.rootd.ch` ZITADEL responds with an error `Domain verification failed (ORG-GH3s)`

**Comment by fforootd** [comment]
FYI @livio-a @hifabienne

**Comment by livio-a** [comment]
@fforootd can we have a look at it together? I've tried on multiple instances and it worked perfectly.

**Comment by fforootd** [comment]
Sure

**Comment by fforootd** [comment]
I tried it once more and could not reproduce this one.

Lets close it for now.
