### ISSUE TITLE
Bug: Primary Color not set in Login after changing it in Console Branding

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4095]
I changed the color in Console to a saturated blue and also set the logo. The logo change was deployed, but the color is still the old one on the login/register page:

![Image](https://user-images.githubusercontent.com/48990649/182383483-33e0d5a9-9fec-49a2-ae40-5faa910861f8.png)

![Image](https://user-images.githubusercontent.com/48990649/182383674-e92b2763-a9e1-41f9-b825-ec7fb9b87511.png)

Is this a cache issue? (simple reload didn't help)

**Comment by hifabienne** [comment]
@juergrinaldi yes this is probably a caching problem. reload with command + shift + r helped in my case
