### ISSUE TITLE
Active/inactive state on login prompt is missleading/inconsistent

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4096]
As a user I want to see the users I have already logged in and I can use to login again no matter of the state of the session.

**Acceptance Criteria**
- [ ] I only see the user session without the state of it in the select account screen

**Additional Information**

The active/inactive state on the user in the login prompt is missleading and inconsistent.

a) the label `inactive` implies that the user is set inactive (aka: non-usable) by admin or thelike.
b) I had the issue that the label showed 'active' while I wasn't properly logged in (aborted the login/verification process half way through)
c) IMO the information of the 'state' of the user is not as relevant to justify the additional text on the login prompt.

![Image](https://user-images.githubusercontent.com/48990649/182388032-18d49f6d-0db9-46c1-9c63-6ab3af1b8ae9.png)

Solution: I'd either get rid of the label or - alternatively - change it to 'signed out' (for inactive), while active has no label at all. (see Google for example)

**Comment by doncicuto** [comment]
I agree with @juergrinaldi, it has all the sense to remove the inactive label as is indeed misleading. I'd prefer to still show "signed out"

![image](https://github.com/zitadel/zitadel/assets/30386061/6fd6bec6-97f0-4af0-8aee-0dc2b55cf32f)

Also I agree to remove the active label

Could you confirm me that you still want this to be done @juergrinaldi and @hifabienne? Thanks!

**Comment by hifabienne** [comment]
hei @doncicuto 
Yes I think that would already be better to have the signed out instead of the inactive.

**Comment by hifabienne** [comment]
Done with https://github.com/zitadel/zitadel/pull/6364
