### ISSUE TITLE
Document how passwords/credentials are stored

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4108]
Description

We got a few questions about how we store passwords/credentials and which algos are supported. Only reference in our docs is currently [in the DPA](https://docs.zitadel.com/docs/legal/data-processing-agreement#pseudonymization--encryption) which less relevant for non-cloud users or technical details.

**Acceptance criteria**
- [ ] Document how passwords/credentials are stored
- [ ] Document which algos are currently supported or planned

**Comment by mffap** [comment]
@fforootd maybe something for you?

**Comment by fforootd** [comment]
Yes definitely let me write something for this on how we handle secrets.

@hifabienne i think this is placed best in concepts, do you think the same?

**Comment by hifabienne** [comment]
yes i think concepts are perfect
