### ISSUE TITLE
[OIDC]: Scope for requesting ZITADEL API access

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4112]
To get an access token for the ZITADEL API, the client has to request the project id of ZITADEL to be added to the audience using the scope `urn:zitadel:iam:org:project:id:{projectid}:aud`. For ease of use we should create a new scope for this:
`urn:zitadel:iam:org:project:id:ZITADEL:aud` or `urn:zitadel:iam:org:project:ZITADEL:aud`

Implementation detail: With the release of 2.0 we easily get the ZITADEL project id from the context.

**Acceptance criteria**
- [ ] when requesting an access token using the scope, then the ZITADEL project id shall be added to the audience of that token
- [ ] added to docs in the api scope section and replaced the current occurrences of the old scope
- [ ] update terraform to newest go-sdk to remove the need for the `projectID`

**Comment by fforootd** [comment]
Yes I think this would be a convenience feature. Actually I would assign it a higher prio. Since it feels like an easy fix.

**Comment by livio-a** [comment]
#4146 adds a `urn:zitadel:iam:org:project:id:ZITADEL:aud ` scope
this will be added in zitadel-go in https://github.com/zitadel/zitadel-go/pull/126

**Comment by fforootd** [comment]
I think we also need to update the `terrraform` to use the newest version of the go-sdk to get rid of the `projectID`

FYI @stebenz
