### ISSUE TITLE
automate release management for stable releases

### ISSUE THREAD

**Issue by thesephirot** [zitadel/zitadel#4116]
in order to provide our customers the option to use the last stable release we need to automate the creation of the stable tag for specific versions

**Comment by thesephirot** [comment]
#4110 
#4115

**Comment by thesephirot** [comment]
the file [release-channels.yaml](https://github.com/zitadel/zitadel/blob/main/release-channels.yaml) can be used to define the stable tag for a release. the pipeline will push the tag automatically

**Comment by adlerhurst** [comment]
@thesephirot i think the two branches mentioned are merged. Can this be closed?

**Comment by thesephirot** [comment]
@adlerhurst closing
