### ISSUE TITLE
Describe local frontend development

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4130]
Include e2e tests

**Acceptance criteria**
- [ ] Running e2e tests is easy
- [ ] Feedback times on local test code changes are fast
- [ ] Feedback times on local application code changes are fast

**Comment by hifabienne** [comment]
HAs to do with this one: https://github.com/zitadel/zitadel/issues/3861

**Comment by mffap** [comment]
@eliobischof can you link the current PR to this?
