### ISSUE TITLE
Check for places where we need to trim spaces

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4150]
We should trim spaces on requests. especialy on the login name.

**Acceptance criteria**
- [x] Trim space on create user
- [x] Trim space on login
- [x] Trim spaces on create org
- [ ] Check for all other requests

**Comment by livio-a** [comment]
#4217 handles the most important occurrences (username and orgname) and will fix the login issues

instances (domains) are already trimmed with the preparation functions... we need to get rid of the old functions and refactor them to the new preparation style to better ensure such cases

**Comment by fforootd** [comment]
Since the heavy stuff is trough we should consider this as a medium cleanup task

**Comment by peintnermax** [comment]
Instance name is trimmed on creation in customer portal with https://github.com/caos/customer-portal/pull/551

**Comment by hifabienne** [comment]
@livio-a @peintnermax can we close this?

**Comment by hifabienne** [comment]
I close this since we have trimmed it at the places we found it
