### ISSUE TITLE
[Epic] PBKDF2 Support

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4157]
As a developer I want to be able to import users with an existing password with PBKDF2 since this is the default in Keycloak and other systems and I want to be able to migrate my users.

In a first step we want to enable ZITADEL for a default hash algorithm that can be configured in the defaults.yaml, Users should be able to be imported with another algorithm and as soon as they change the password the next time, it will be changed to the default.

**Acceptance criteria**
- [x] #5530
- [x] zitadel/passwap#1
- [ ] #5413
- [x] #5417
- [x] #5416
- [x] #5418

**Later on**
- [x] zitadel/passwap#2

**Additional Context**
Current documentation here https://www.keycloak.org/docs/latest/server_admin/index.html#password-policy-types

**Comment by fforootd** [comment]
CC @hifabienne

**Comment by muhlemmer** [comment]
@adlerhurst. I've written https://github.com/muhlemmer/passwap which provides a unified API of different password hashing algorithms available in Go. I've already mentioned in our private chat if you guys want, we can fork it into zitadel and maintain it from here. The responses from @fforootd  and @mffap where positive over there, but no definite action was concluded.

The Readme is a stub, but the Godoc is complete, with an [example](https://pkg.go.dev/github.com/muhlemmer/passwap@v0.0.0-20230314182427-70049d7198fd#example-package). Currently it supports hashing and verifying the following algorithms:

- md5-crypt (legacy)
- bcrypt
- scrypt
- argon2i / argon2id

Adding a new algorithm such as #5415 typically takes (me) around 1 day.

There are a few chores to be done if / after we move it to zitadel:
- do we need to change the license? (currently BSD-3, zitadel uses Apache)
- expand the readme a bit more with things such a featues.
- add an auto-release tool / tag a first release

**Comment by adlerhurst** [comment]
love that. IMO it's definitely worth using your lib. I added the info to the more fine grained #5417. Made a note to discuss it during tomorrows planning. @hifabienne FYI

**Comment by muhlemmer** [comment]
Migration is done, the rest we discuss tomorrow. https://github.com/zitadel/passwap

**Comment by fforootd** [comment]
> Migration is done, the rest we discuss tomorrow. https://github.com/zitadel/passwap

I hope it preserved your rights. Last time @peintnermax migrated a project he lost admin access to it 😬

**Comment by kbumsik** [comment]
Hi, I am using Keycloak at work and we are considering Zitadel as a possible alternative because we are having problems in a B2B scenario as Keycloak having a bad "Organization"-like multi-tenancy support.

Since Zitadel explicitly positioned as a Keycloak alternative, it is natural that existing Keycloak users expect there is an easy way to migrate their existing Keycloak deployments to Zitadel. And PBKDF2 support seems to be a key for that.

Since Zitadel is not ready for this yet, we will first try Zitadel for a new internal service, and we would try migrating if we are happy with the trial :)

**Comment by fforootd** [comment]
> Hi, I am using Keycloak at work and we are considering Zitadel as a possible alternative because we are having problems in a B2B scenario as Keycloak having a bad "Organization"-like multi-tenancy support.

This was one of the reasons to build ZITADEL in the first place 😁 

> Since Zitadel explicitly positioned as a Keycloak alternative, it is natural that existing Keycloak users expect there is an easy way to migrate their existing Keycloak deployments to Zitadel. And PBKDF2 support seems to be a key for that.

Well that is a fair argument, let me bump this, we are committed to create a nice migration experience for kc users.
@hifabienne take note

> Since Zitadel is not ready for this yet, we will first try Zitadel for a new internal service, and we would try migrating if we are happy with the trial :)

Lets us know how it goes and if you have questions either open a GH Discussion or join our [Discord Chat](https://zitadel.com/chat).

**Comment by gdsmith** [comment]
Another Keycloak user here looking for a migration path. Seems like the lack of PBKDF2 support is a blocker for this. Any idea if/when this might get prioritised or any documentation on how we might get around this to import our Keycloak users into Zitadel?

**Comment by hifabienne** [comment]
hei @gdsmith 
So far the plan is to implement this feature in the next quarter.
