### ISSUE TITLE
User not correctly logged out on mobile

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4171]
**Describe the bug**
If the user is in the customer portal and clicks on logout user, he will be redirected to the login.
The state of the user in the list is still active. By selecting the user, he is instantly in the customer portal again, without entering a MFA. This only occurred on the mobile phone, in the browser on the computer it worked fine.

**Acceptance Criteria**
- [ ] If user clicks logout, he should not be active in the user selection list
- [ ] Password should be prompted again
- [ ] MFA should be prompted again
- [ ] Tested on mobile
- [ ] Tested on different browsers

**Comment by hifabienne** [comment]
@peintnermax is this ready to start or already in progress?

**Comment by peintnermax** [comment]
This is in progress right now

**Comment by peintnermax** [comment]
problem is that end_session is not called properly due to missing environment variables during build

**Comment by peintnermax** [comment]
fixed with https://github.com/caos/customer-portal/pull/511
