### ISSUE TITLE
Spaces Should be trimmed or not Allowed in Usernames

### ISSUE THREAD

**Issue by speatzle** [zitadel/zitadel#4172]
**Describe the bug**
When a User Modifies their Username they can accidentally add a Space to the end of it (Mobile Keyboards often do this Automatically). This Causes the User to be Unable to Login Since they don't know that they have a tailing Space that they need to add to Their Username.

**To Reproduce**
1. Go to Profile
2. Click on 'modify'
3. Add a Space to the End of the Username (happens automatically on Mobile)
4. Try to Login without the Space.

**Expected behavior**
Spaces Should trimmed or not be Allowed in Usernames.

**Comment by hifabienne** [comment]
#4150

**Comment by mffap** [comment]
@fforootd @livio-a what's the status on this? Who will be implementing the fix?

**Comment by fforootd** [comment]
I am not sure, since I was not in the planing yesterday

**Comment by livio-a** [comment]
will start with it this morning
