### ISSUE TITLE
Create a root redirect

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4177]
Description

We should create a redirect from the root path to either /ui/console or /ui/login.
This makes it more easy to access ZITADEL without an external proxy rule.

**Acceptance criteria**
- [ ] Redirect / to /ui/login (or something else)

**Comment by mffap** [comment]
Alternative could be to serve a page, like [pihole](https://github.com/pi-hole/pi-hole) handles this case. But I think they also switched to auto-redirect when using custom domains afaik.
![image](https://user-images.githubusercontent.com/1366906/187411103-65783961-1c37-4644-8ddd-5ce75cebba28.png)

**Comment by KaKi87** [comment]
Hello,
Will this also redirect logged in users to their dashboard ?
Thanks

**Comment by fforootd** [comment]
Hey @KaKi87 this redirects only from / to /ui/login.

By default, if a user does login, he is redirected to /ui/console.

However you can change the default redirect URI if you access /ui/console/settings?id=login

![image](https://user-images.githubusercontent.com/9879976/200937282-32ede743-e2c6-43c0-a1b3-6ccfdbf16f97.png)

**Comment by fforootd** [comment]
> , will either do nothing (and you may find your way back to your dashboard, which is still a bad experience), or log out out (and you'd have to log in again, which is indeed the worst experience).

Out of curiosity... that is not what you experience with ZITADEL right?

**Comment by KaKi87** [comment]
No, as I said, I checked. :)
