### ISSUE TITLE
Better ux for tertiary links

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4189]
Tertiary links are often not easy to recognize as links in the login ui. They should be shown in the primary color.
Example Password reset link

**Acceptance criteria**
- [ ] Tertiary links in key color

**Comment by hifabienne** [comment]
In customer portal better visible

<img width="618" alt="image" src="https://user-images.githubusercontent.com/38692350/184822600-6ca42161-d41c-40be-af52-11a28c60565b.png">

**Comment by juergrinaldi** [comment]
Note: I discussed with @peintnermax that we set the default as standard font color & underline, but implement the option to set a tertiary color and toggle underline on/off via custom design settings.

**Comment by juergrinaldi** [comment]
should be customizable with #3987

**Comment by peintnermax** [comment]
The password reset link on the `/password` page is the only occurrency in the login interface. #5012 fixes this issue

![Image](https://user-images.githubusercontent.com/10165752/211309830-4dde0f77-6d9b-4ca7-95bb-414549dea273.png)
