### ISSUE TITLE
Simplify registration

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4190]
At the moment the registration screen has a lot of unrequired fields. To make it easier only mandatory fields should be shown. 

**Acceptance criteria**
- [ ] Only username should be required
- [ ] FirstName, Lastname, Email as not required fields on register form
- [x] Remove Language #4425 
- [x] Remove Gender #4425 
- [x] Rename Lastname to Surname (This should be renamed everywhere not only registration) #4425 
- [x] Rename Firstname to First name #4425 
- [ ] Ensure Tab navigation highlighting works on all elements

**Comment by hifabienne** [comment]
I made a separate issue for the not required fields, because this has some impacts on the login flow as well for some actions like password reset, etc. https://github.com/zitadel/zitadel/issues/4386

**Comment by KaKi87** [comment]
> Rename Lastname to Surname

I was actually surprised while reading this on my registration page, I see this quite rarely, why choosing this form ?

Thanks

**Comment by hifabienne** [comment]
I will close this issue since it is included in the following: #4386
