### ISSUE TITLE
MFA Setup improvment

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4192]
Setup of mfa is to technical for users.

**Acceptance criteria**
- [x] Remove Radiobuttons, should be images instead (see screen below)
- [x] Add description (why you should choose mfa)
- [x] use 2fa instead of mfa (more popular)

**Comment by hifabienne** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/38692350/184828572-04d11b7d-fe1b-4785-8b94-37a68869667f.png">

**Comment by juergrinaldi** [comment]
Here are the icons as SVGs:
https://drive.google.com/drive/u/1/folders/12YBNNkaf01ZYAhn2FzOSidsRVEQ9bUty

**Comment by mffap** [comment]
@hifabienne do we have a description of all the mfa methods in the docs?

**Comment by virth** [comment]
MFA setup has already improved a lot! Thanks. Only thing missing is a link to «more information». This does not seem to be a «priority: high» anymore.

**Comment by hifabienne** [comment]
Yes this was actually one of my todos. to add a new issue for the open tasks and close this one.
Link to new issue: https://github.com/zitadel/zitadel/issues/4863
