### ISSUE TITLE
Add Google Cloud Run Deployment Guide 

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4200]

**Comment by mffap** [comment]
We should provide a small guide for a basic deployment. I believe this would be valuable in addition to our [Knative](https://zitadel.com/docs/self-hosting/deploy/knative), and it's the way we run ZITADEL Cloud anyways.

Got a request from discovery call, and also there were some related discussions in Discord: 

- https://discord.com/channels/927474939156643850/1055171929511833620
- https://discord.com/channels/927474939156643850/1027181249489547285
- https://discord.com/channels/927474939156643850/1027141309980479498
- https://discord.com/channels/927474939156643850/973564393134628954/973566782604472340

**Comment by hifabienne** [comment]
will close this issues as there is no content and description what is expected, feel free to reopen with more information
