### ISSUE TITLE
JWT access tokens for service users

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4208]
As a developer I want to be able to choose what kind of access token my service user gets, because some APIs require jwt tokens.

**Acceptance criteria**
- [x] users can specify the token type for service users (like with apps, default still opaque)
- [x] access tokens are returned according to the selected type
- [x] I can choose the type of the token on the service user (JWT, Bearer)
- [x] I get the specified token with my service user, per default I get bearer

**Comment by livio-a** [comment]
relates to #4176

**Comment by regbo** [comment]
I'd like to second this request. I have gateway services that control traffic and need to quickly verify tokens before forwarding them on to the final destination (where tokens are fully verified). With the current implementation both the gateway and the destination api must verify the tokens with an http lookup.

**Comment by fforootd** [comment]
> I'd like to second this request. I have gateway services that control traffic and need to quickly verify tokens before forwarding them on to the final destination (where tokens are fully verified). With the current implementation both the gateway and the destination api must verify the tokens with an http lookup.

Makes sense!

If I am oriented correctly we will work on this from the 23rd Jan.

**Comment by livio-a** [comment]
backend has been merged
@peintnermax you should be able to start with the frontend

**Comment by peintnermax** [comment]
@stebenz I noticed a typo in `updateMachineRequest`,  `setAccessTokenType`
same for the Machine Type

**Comment by stebenz** [comment]
@peintnermax as I find no typo in the UpdateMachineRequest and maybe also not fully understand your description, can you please point me to the typo?

**Comment by peintnermax** [comment]
https://github.com/zitadel/zitadel/blob/main/proto/zitadel/user.proto#L86
