### ISSUE TITLE
Stop waiting for consistency in e2e tests

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4213]
In e2e tests, we don't want to rely on the time gap of eventual consistency. For example, we don't wan't to rely much on runtime performance for running functional e2e tests. Instead, we want to monitor changes over releases #4214.

**Comment by mffap** [comment]
I disagree. You should rather define the wait times as variables in terms of non functional requirement.

E.g. we want to wait a max of 15 seconds until a newly created user is visible in the UI.

The wait times should be variables

**Comment by fforootd** [comment]
This relates to https://github.com/caos/caos-internal/issues/451

**Comment by eliobischof** [comment]
Why is this high priority?

**Comment by fforootd** [comment]
> Why is this high priority? And why is it "In Progess"? Changed to "Needs More Info"

I agree with the needs more info. Priority wise it feels like a mishap from my side.

**Comment by hifabienne** [comment]
We close it for now and will reopen if we see a need
