### ISSUE TITLE
Navigation to instance level not clear on mobile

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4221]
**Describe the bug**
The button to navigate to the instance is not visible on mobile.

**To Reproduce**
1. Open console on mobile

**Expected behavior**
Instance navigation on mobile view accessible

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: Android 12
 - Browser: Chrome 

**Additional context**
- Workaround: Switch to desktop view
- Workaround: Click on show all organizations in the organziation drop-down

**Comment by mffap** [comment]
@juergrinaldi @peintnermax fyi

**Comment by juergrinaldi** [comment]
this is considered/handled in #4834 and integrated in the main menu:

![nav01 - new_2](https://user-images.githubusercontent.com/48990649/207320443-97df2ef9-c8cb-4355-bbe9-578365383d06.png)
