### ISSUE TITLE
Role/membership deletion doesn't work properly

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4223]
**Describe the bug**
When deleting a role, only the selected role should be deleted. Instead, the role plus all the ones after it are deleted.

I tried adding them in different order and it gives the same result

**To Reproduce**
1. Create a user
2. Assign 4 random organization roles to the user
3. Delete the second one

**Expected behavior**
Only the selected role should be deleted.

**Screenshots**
Before:
![Screenshot 2022-08-21 at 17 02 49](https://user-images.githubusercontent.com/58290976/185797481-85a2b66b-d113-4928-8903-7497982007af.png)

After:
![Screenshot 2022-08-21 at 17 03 02](https://user-images.githubusercontent.com/58290976/185797486-dbd3941b-9d40-4af5-afa7-edd3f176715d.png)

**Desktop:**
 - OS: macOS Monterey 12.5.1
 - Browser: Safari

**Additional context**
ZITADEL: v2.1.1

**Comment by livio-a** [comment]
Hey @DavideWalder 
Thanks for this issue. I could reproduce it and looks like a frontend problem.
@peintnermax can you please have a look at it today.
