### ISSUE TITLE
Action "Flows" view is not updated when flows are changed

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4240]
**Describe the bug**
When a trigger is added or deleted, the "Flows" view is not rerendered (it is displayed correctly only after refreshing the page)

**To Reproduce**
Steps to reproduce the behavior: add or delete a trigger

**Expected behavior**
The component should always show the current state

**Desktop:**
 - OS: MacOS Monterey
 - Browser: Safari

**Comment by livio-a** [comment]
@peintnermax can you please check this? is it a frontend issue or eventual consistency?

**Comment by peintnermax** [comment]
I can confirm this is an eventual consistency issue. What's missing though is toast messages after adding, clearing the flow. Added them here #4247

**Comment by hifabienne** [comment]
@peintnermax I saw you already merged the pr. Can we close this issue then?

**Comment by peintnermax** [comment]
The PR fixed some toast messages but not eventual consistency. It's still a TODO until behavior is consistent. I'll add a task for this and other places where eventual consistency is a problem
