### ISSUE TITLE
Domain Verification - Change to opt-in

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4245]
## Description

I think we should consider switching to a default off state for the domain verification and suffix feature ZITADEL has. I see multiple reasons for this:

1. Easier for self-hoster since it enables them to use any username out of the box
2. Easier onboarding in ZITADEL Cloud
3. If a customer wants to verify its domain the feature can be enabled later on

## Questions

- What happens when the settings are turned on later?
- Should we allow to move users between orgs?

## Acceptance criteria

- [ ] Default Off - Username must contain Org domain
- [ ] Default Off - Validate Org domains
- [ ] Disable the "domains" tab when the settings are off to reduce confusion

<img width="394" alt="Screenshot 2022-08-24 at 15 45 51" src="https://user-images.githubusercontent.com/9879976/186434693-99245364-225b-45e7-b051-b5f2f88c3410.png">

@mffap @livio-a @peintnermax @juergrinaldi what do you think of this?

**Comment by peintnermax** [comment]
I'd also like to see this disabled per default.. 👍

**Comment by mffap** [comment]
Sounds good. We should however also look at the email templates: 
Either give an option to configure your own #4143 or make sure that the email templates are not confusing (eg, showing the technical domain name, instead of the username). @juergrinaldi I think we already have an issue for the Customer Portal.

**Comment by fforootd** [comment]
I think the templates just rely on the logonname which should be fine, right @livio-a

**Comment by juergrinaldi** [comment]
@mffap do you mean this issue? https://github.com/caos/customer-portal/issues/524 (not sure, if I should cross link or not)
it adresses this is issue just somewhat. But I mentioned it in my [docs for login flow improvements](https://docs.google.com/document/d/195TRoG6_JF7DPDgwJbunNLUw5gmM8RK-kW7js83cXx8/edit?disco=AAAAeUhumC8) and @hifabienne commented about it.

omg. i can't upvote this enough. getting rid of the suffix completely (for the user) is a big deal imo. we just have to make sure that a "normal" user isn't confronted with that at all.

**Comment by fforootd** [comment]
@livio-a and I will talk about this later today and document the conclusion

**Comment by fforootd** [comment]
## Concept Changes

To make for a better UX we change the default username behaviour to allow creating user in organization with any mail based username.

## Action Items

- [ ] Define new scope `urn:zitadel.iam:org:{id}` to allow invocation of orgid based auth request
- [ ] Update login to work with the new scope (the full username should me made ready as input field)
- [ ] Verify that the claims `urn:zitadel:iam:user.resourceowner:{id}`,  `urn:zitadel:iam:user.resourceowner:{name}`,  `urn:zitadel:iam:user.resourceowner:{primary_domain}` are filled with the new scope
- [ ] Change the default of "Username must contain Org domain" to OFF
- [ ] Make sure that the register uses the email as default username
- [ ] Update documentation settings as well as scopes and claims

## Future work

- [ ] Create a new username policy which allows and admin to set a schema for the usernames in its organization (see also this discussion https://github.com/zitadel/zitadel/discussions/3956)
- [ ] We need to define what happens when "Username policy" is enabled or disabled with existing users
- [ ] We should consider a way of migrating user between organizations

**Comment by livio-a** [comment]
relates to https://github.com/zitadel/zitadel/issues/1648

**Comment by fforootd** [comment]
@livio-a does start the work here

**Comment by fforootd** [comment]
@hifabienne
