### ISSUE TITLE
Database: Missing reconnect after connection reset by peer

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#4253]
**Describe the bug**

If ZITADEL looses the connection to the database, it's possible that the connection won't be reinitiated. I had the problem during a talk, where the connection got `reset by peer` and pgx didn't reconnect. I'm having the same problem if my mac switches to hibernate mode and ZITADEL and cockroach were running locally. 

The main problem is, that this error is hard to monitor and ZITADEL won't return any success message because no data can be received.

**To Reproduce**

1. start ZITADEL and cockroach locally
2. let it run during the night
3. wake up the mac from sleep mode
4. ZITADEL won't be able to reconnect to the database 

**Expected behavior**

ZITADEL should reconnect to the database or shut down

**Screenshots**

**Desktop (please complete the following information):**
- Processor: m1
- OS: macos 12.4

**Comment by hifabienne** [comment]
I will close this issue because its irrelvant, we did some changes in the storage since then. 
If needed we can reopen
