### ISSUE TITLE
Add E2E tests covering B2B Demo cases

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4282]
Before adding more tests, we remove the flakiness of existing tests, as we don't want to introduce more flaky tests.
Therefore requires #2293

**Comment by hifabienne** [comment]
@fforootd @eliobischof I believe you are not really working on this right now and from your comments I think this issue is for the backlog right now?

**Comment by eliobischof** [comment]
> @fforootd @eliobischof I believe you are not really working on this right now, so I can remove you both from the assignees? and from your comments I think this issue is for the backlog right now?

I'd say so too, yes.

**Comment by hifabienne** [comment]
close it in favor of other e2e test issues
