### ISSUE TITLE
Message=Instance not found when using the tutorial

### ISSUE THREAD

**Issue by fuomag9** [zitadel/zitadel#4305]
**Describe the bug**
`ID=QUERY-n0wng Message=Instance not found` when using the docker compose tutorial and going to http://yourip:8080/ui/console

**To Reproduce**
1. follow the tutorial at https://docs.zitadel.com/docs/guides/deploy/compose
2. Go to http://yourip:8080/ui/console

**Expected behavior**
Should not display an error and make me see the UI?

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version 12.5.1

**Comment by fuomag9** [comment]
Note: the console UI worked when connecting to localhost of the server via ssh port forwarding

**Comment by ovizii** [comment]
Why would you close this? The tutorial does not mention anything about port forwarding and not being able to connect from a different PC.
