### ISSUE TITLE
[Actions] Supply users with JSON Support

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#4311]
We have to find out if we have to extend the goja runtime to allow operations on the http responses. e.g. `JSON.parse(object)`, `JSON.stringify(object)`.

**Comment by fforootd** [comment]
A developer should be able to create and process JSON request and responses with a ZITADEL action.

**Comment by adlerhurst** [comment]
tested by: https://github.com/zitadel/zitadel/pull/4337/files#diff-6376a943548141dfbc97afe1a868db5e22eafaff2241609a47a7a53c6eebd57fR112-R118
