### ISSUE TITLE
Migration Guide Basics

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4314]
As a developer, I want to know what needs to be considered migrating from an existing auth system to ZITADEL, so that I can plan the migration accordingly.

**Context**
Provide an introductory overview of things to consider when migrating from an existing auth system to ZITADEL. This might include the following items: 

- Tenants: Instance vs. Organizations
- SSO: External IDPs, Account Linking, Brokering
- Project Grants
- Custom Claims: Application expects token to have certain claims; App can't be changed easily
- User required fields
- Password hashes (and supported algorithms)
- OTP
- Passwordless (same domain)
- Metadata
- JIT vs. Batch (overview)
- ...

**Acceptance Criteria**

- [ ] Guide on Migration Basics
- [ ] The guide covers the outlined topics

**Comment by hifabienne** [comment]
There are multiple possibilities how to import/create to ZITADEL.
First we should describe which possibilites and maybe find out what is the solutions our customers want

**Comment by mffap** [comment]
> There are multiple possibilities how to import/create to ZITADEL. First we should describe which possibilites and maybe find out what is the solutions our customers want

My suggestion would be to use a standard format like SCIM as baseline. So it's clear how the records from a DYI implementation should look like and a standardized format for import of user records.
