### ISSUE TITLE
Help/contact link in console

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4315]
We should add an easy accessible help/contact link in the console.
(I'd suggest the footer for this. Maybe even header (as an icon))

Of course the same goes for the customer portal see here: https://github.com/caos/customer-portal/issues/569

**Comment by hifabienne** [comment]
@juergrinaldi what do you want to achieve with this?
Where should the help link point? To the documentation?

**Comment by juergrinaldi** [comment]
@hifabienne I want to achieve that a user can get help from within ZITADEL if they get stuck on any step.
From the user's perspective the best would be a direct support to us (phone/email/messaging service) but at least provide additional information (docs) and/or a link to discord.

My initial idea was to just add a link to our support page from zitadel.com (where the user can get all the above mentioned).

But if we don't want to do the support work in Console and leave that to our customers, we should promote a help "link" implementation for our customer on the customization page in Console (_"add contact information for support, so your customers can reach out to you for help"_).
But the above mentioned should still be implemented in Customer Portal for **our** customers.

**Comment by hifabienne** [comment]
I will close this for now, as we have a link to our docs as well as a link to our social channels and discor
