### ISSUE TITLE
[Actions] add "customise token" flow types

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#4321]
As a developer I want to add custom claims to userinfo and access tokens because my application needs additional information I want to retrieve from ZITADEL.

create action during set user info to add custom claims (only extend)

- [ ] new flow type "customise token"
  - [ ] new trigger "pre user info creation" 
    - during user info is called (via endpoint or id token creation) 
    - allow http client, user- and org-metadata
    - `AppendClaim` function on input param (userinfo-object, token) to add additional claims
  - [ ] new trigger "pre access token creation"
    - during creation of access token via API
    - allow http client, user- and org-metadata
    - `AppendClaim` function on input param (userinfo-object, token) to add additional claims
- [ ] check if login flow has to be extended as well

_Originally posted by @adlerhurst in https://github.com/zitadel/zitadel/issues/4265#issuecomment-1237065338_

**Comment by fforootd** [comment]
Some thoughts we should allow to extend id and access token as well as the introspect endpoint.
