### ISSUE TITLE
CLI: Version command

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4334]
### Discussed in https://github.com/zitadel/zitadel/discussions/4329

<div type='discussions-op-text'>

<sup>Originally posted by **CMiksche** September  6, 2022</sup>
Currently there is no way of showing the current zitadel version. `zitadel version` doesn't exist.

Especially for debugging, that small feature would be helpful.</div>

Dev Note:
We already build the version into the `cmd/build` package. There's only the cobra command missing.

**Comment by adlerhurst** [comment]
Latest release of viper probided this feature by default
