### ISSUE TITLE
Cannot create user for a new organisation.

### ISSUE THREAD

**Issue by hernangonzalez** [zitadel/zitadel#4338]
**Describe the bug**
Cannot create user for a new organisation.

**Screenshots**
<img width="389" alt="Screen Shot 2022-09-07 at 22 53 50" src="https://user-images.githubusercontent.com/1162963/188990698-907326ac-dd80-46c8-b925-ce9a9a671a4e.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Browser Safari
 - Version Zitadel, homebrew, 2.3.4
 - Postgres

**Additional context**
Console log
```
WARN[4892] missing translation                           args="map[]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:206" error="message \"Errors.Invalid.Argument\" not found in language \"en\"" id=Errors.Invalid.Argument
```

**Comment by adlerhurst** [comment]
Thanks for the report. The missing translation is bad. 

I looked into the code and the error occurs if the email address is not valid. Did you pass an existing email address?

**Comment by hernangonzalez** [comment]
Yep, that was it. thanks @adlerhurst
