### ISSUE TITLE
Redirect users without manager roles to /ui/console/me

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4340]
If users without manager roles click on the ZITADEL logo in console, they land here:
![image](https://user-images.githubusercontent.com/12727842/189114376-9d4f6c6a-a6f6-49a6-9323-25d461620ea9.png)

Maybe, they should only be able to navigate to /ui/console/me.
What do you think, @juergrinaldi?

**Comment by juergrinaldi** [comment]
If I user has no managing roles or thelike, they should only see their profile page. and imo there shouldn't be a ZITADEL logo in the first place, as the user has/had no contact with the brand ZITADEL. (because they probably come from our client's branded login etc...)
