### ISSUE TITLE
User authentication: Additionally use email as loginname

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4344]
Currently users are identified by their loginname. Loginnames can either be a username suffixed by the org domain or an instance wide unique username (currently only email style). The question arose if it would be possible to enable to login by email as well (login by loginname would still be possible).

The idea was, that the identification (user matching) on the login screen would be possible with the email as long as it is unique / used on only a single user. If multiple users have the same email address - which is possible in ZITADEL and still should be - the login would not be possible by email. The login UI should handle that as if the email would not exist. And only authentication by loginname will be possible for these users.

**Acceptance Criteria**
- [x] Extend Login policy (default should be to allow email, and phone)
       - DisableLoginWithEmail (better naming?)
       - DisableLoginWithPhone (better naming?)
- [x] If user by loginname results in not found, search in email and phone
       - If user not found --> return error user not found
       - If more than one user found --> return user not found
- [x] If organisation is pre selected only user of this organisation will be searched
       - if org preselected, it is possible to have the same email multiple times
- [ ] Tests
- [ ] Docs

**Comment by livio-a** [comment]
@hifabienne and @fforootd please discuss that next week if possible so we can report back (at the latest the week after) to the client if and when it would be possible to do it.

**Comment by fforootd** [comment]
Generally Speaking I think we should allow multiple unique values for a user, e.g mail, phone, username, ...

So I think we should extend ZITADEL on that end. Although I am not sure how to proceed :grin: (yet)

**Comment by mffap** [comment]
Same would go for our own instance of ZITADEL, used for the customer portal on zitadel.cloud. It might reduce the confusion about the account names. People are used to sign-up to Saa-Services with their email address.

**Comment by hifabienne** [comment]
Discussed with @fforootd 
We think only the username should be used to login. But we like to allow to store the email in the username field.
With the following steps this should be enabled:
1. Suffix for usernames as optin: https://github.com/zitadel/zitadel/issues/4245
2. Allow rules for usernames: https://github.com/zitadel/zitadel/issues/4254
3. Remove the suffix/domain part completely, because this can also be done by rules in point 2.

**Comment by mffap** [comment]
We should use this issue to provide users with a guide on how to configure the system for this use case.

**Comment by fforootd** [comment]
> We should use this issue to provide users with a guide on how to configure the system for this use case.

You mean customers who had the "old" default?

**Comment by mffap** [comment]
> > We should use this issue to provide users with a guide on how to configure the system for this use case.
> 
> You mean customers who had the "old" default?

Ah ok, this becomes the new default? That was not clear to me from this discussion.

Still, we should provide a small concepts page with the options available, so that users can decide what to use.

**Comment by fforootd** [comment]
> Ah ok, this becomes the new default? That was not clear to me from this discussion.

I get that, since it is discussed in https://github.com/zitadel/zitadel/issues/4245

> Still, we should provide a small concepts page with the options available, so that users can decide what to use.

Great point it would make sense to explain the "feature" in the docs

**Comment by fdelucchijr** [comment]
This feature is very promising, as allows more mainstream users to interact with the login (custom domain based usernames isn’t the standard for B2C anymore), enabling more business to implement Zitadel without friction.
There’s any timeline for this feature for us fellow programmers to know when to spect the release?

**Comment by livio-a** [comment]
@fdelucchijr I start with this today. You can expect it to be release by early next week.
