### ISSUE TITLE
New domains show as verified if "Validate Org domains" is false

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4359]
**Describe the bug**
New domains show as verified even when they are not.

Side note: do "validation" and "verification" refer to the same action?

**To Reproduce**
1. Set "Validate Org domains" to false on both organization and instance
2. Create a domain
3. The domain shows as verified

**Additional context**
ZITADEL Cloud 2.3.3

**Comment by adlerhurst** [comment]
Hi @DavideWalder thanks for your report we will have a look at it

**Comment by DavideWalder** [comment]
> Hei @DavideWalder
> 
> I think we do have some problems with what validate and verified means and what the impact of the property validate org domains has.
> 
> At the moment ZITADEL works as intended, but as I read your issue I understood, that this might now be clear for the users.
> 
> In ZITADEL not verified domains do not have any impact. A domain has to be in the state verified so it can be used for the login. eg. verified domain zitadel.cloud --> login [user@zitadel.cloud](mailto:user@zitadel.cloud)
> 
> The property "validate org domains" enables or disabled if the verification process has to be done manually or if it is automatically added as verified. So if "validate org domains" = true --> A manual verification process of the domain is triggered (acme challenge) If "validate org domains" = false --> No manual verification process has to be done and the domain is automatically added as verified.
> 
> I see that this is confusing and not understandable for the users. I just don't want to make a quick change that might is confusing aswell. Let me check with my colleagues how we can improve this process and make it understandable and get back to you.
> 
> Let me know if my answer is understandable or if you still have questions.

Thanks for the explanation, one thing that might still be confusing is what happens in this case:
1. Set `Validate Org domains` to false
2. Create a domain
3. Set `Validate Org domains` to true
4. The domain still shows as verified

I would expect to either get an error when I turn on `Validate Org domains` or to see the domain as not verified (or at least distinguishable from the ones that were actually verified)

**Comment by hifabienne** [comment]
> > Hei @DavideWalder
> > I think we do have some problems with what validate and verified means and what the impact of the property validate org domains has.
> > At the moment ZITADEL works as intended, but as I read your issue I understood, that this might now be clear for the users.
> > In ZITADEL not verified domains do not have any impact. A domain has to be in the state verified so it can be used for the login. eg. verified domain zitadel.cloud --> login [user@zitadel.cloud](mailto:user@zitadel.cloud)
> > The property "validate org domains" enables or disabled if the verification process has to be done manually or if it is automatically added as verified. So if "validate org domains" = true --> A manual verification process of the domain is triggered (acme challenge) If "validate org domains" = false --> No manual verification process has to be done and the domain is automatically added as verified.
> > I see that this is confusing and not understandable for the users. I just don't want to make a quick change that might is confusing aswell. Let me check with my colleagues how we can improve this process and make it understandable and get back to you.
> > Let me know if my answer is understandable or if you still have questions.
> 
> Thanks for the explanation, one thing that might still be confusing is what happens in this case:
> 
> 1. Set `Validate Org domains` to false
> 2. Create a domain
> 3. Set `Validate Org domains` to true
> 4. The domain still shows as verified
> 
> I would expect to either get an error when I turn on `Validate Org domains` or to see the domain as not verified (or at least distinguishable from the ones that were actually verified)

Yes, we probably need some more states here. So we know if the domain got verified or "automatically" verified. I can also imagine to just change the mechanism, so you can set a property that says if verification is needed or not.

**Comment by DavideWalder** [comment]
@hifabienne I see, having the option as you suggested would make sense, thanks!

Feel free to close the issue

**Comment by hifabienne** [comment]
Problem was solved, will close this issue.
