### ISSUE TITLE
Can't reset label policy to instance default

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4360]
**Describe the bug**
When clicking on "Reset to Instance default" under Organization/Settings/Branding, I get this error:
```
Object could not be removed (DATAB-Efgt2)
```

**Additional context**
ZITADEL Cloud 2.3.3

**Comment by DavideWalder** [comment]
This also prevents the usage of the terraform provider, since the resource can only be created if there isn't one already, and
the existing resource can't be imported by ID since the `GetLabelPolicy` endpoint doesn't return the ID

**Comment by adlerhurst** [comment]
Hi @DavideWalder thanks for your report we will look at it asap

**Comment by stebenz** [comment]
@DavideWalder can you try it again on zitadel.cloud as we have now v2.4.0 , there should already be a fix in the new release, if there is still a problem with resetting to instance default, please don't hesitate to comment this issue again

**Comment by DavideWalder** [comment]
@stebenz Now it works (successfully reset to instance default and created a custom label policy with Terraform), thanks!!!
