### ISSUE TITLE
OIDC IPD styling parameter not working as expected

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4361]
**Describe the bug**
The effect of `STYLING_TYPE_UNSPECIFIED` and `STYLING_TYPE_GOOGLE` seem to be inverted.

with `STYLING_TYPE_UNSPECIFIED`:
<img width="436" alt="Screenshot 2022-09-12 at 16 11 02" src="https://user-images.githubusercontent.com/58290976/189675935-647f5bc7-daa1-4dbc-b33c-9ebba4ea18d9.png">

with `STYLING_TYPE_GOOGLE`:
<img width="441" alt="Screenshot 2022-09-12 at 16 11 43" src="https://user-images.githubusercontent.com/58290976/189676093-ad8fc7ef-8f61-44d9-afeb-047149d9f991.png">

**Additional context**
ZITADEL Cloud 2.3.3

**Comment by adlerhurst** [comment]
Hi @DavideWalder thanks for all of your reports looks like you have a detailed look into zitadel. Thanks for that ☺️ we will go through your reports asap

**Comment by hifabienne** [comment]
This is already fixed, but issue was not closed. Will close this now
