### ISSUE TITLE
Can't type username if organization name is too long

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4362]
**Describe the bug**
Aesthetics aside, it is not possible to type a user name if the domain overflows.

**Screenshots**
<img width="470" alt="Screenshot 2022-09-12 at 19 45 16" src="https://user-images.githubusercontent.com/58290976/189722086-d5d288bb-2041-4a5c-b07e-4589acfbd82a.png">

**Additional context**
ZITADEL Cloud 2.3.3

**Comment by adlerhurst** [comment]
I think we limit the amount of characters there. Default is 200 but it makes no sense there because its a combination of multiple values. Thanks we will fix it asap
