### ISSUE TITLE
Cannot change OIDC Token Lifetime Settings

### ISSUE THREAD

**Issue by swratten** [zitadel/zitadel#4364]
**Describe the bug**
When attempting to Adjust OIDC Token Lifetime settings on a fresh instance, an error is reported: OIDC Configuration not found

**To Reproduce**
1. Use Docker Compose example from Documentation
2. Login as zitadel-admin
3. Navigate to Instance Settings -> OIDC Token lifetime and expiration
4. Press Save
5. See error: OIDC Configuration not found

**Comment by stebenz** [comment]
We will have a look at it and give feedback ASAP.
