### ISSUE TITLE
Redirected to organization page when clicking on user

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4365]
**Describe the bug**
The organization page is shown instead of showing the user page

**To Reproduce**
1. Select an organization (starting from another one)
2. Go to "Users"
3. Click on a user
4. The page shown is the organization, not the user

**Expected behavior**
The GUI should show the user

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Additional context**
Happens with ZITADEL 2.4.0 and 2.3.3

**Comment by mffap** [comment]
@peintnermax I could reproduce this issue. Could you please have a look?
