### ISSUE TITLE
Mismatching scopes between documentation and code

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4366]
**Describe the bug**
The scope prefix doesn't match between documentation and code
https://github.com/zitadel/zitadel/blob/7a5f7f82cfe650c083167febd158895d4ce28148/internal/api/oidc/client.go#L22
https://github.com/zitadel/zitadel/blob/7a5f7f82cfe650c083167febd158895d4ce28148/docs/docs/apis/openidoauth/claims.md?plain=1#L34

Also, the name `rolename` can be confusing since the available fields are `key` and `displayname` (here I believe `key` is the correct one):
https://github.com/zitadel/zitadel/blob/7a5f7f82cfe650c083167febd158895d4ce28148/proto/zitadel/project.proto#L140

**Comment by livio-a** [comment]
Hey @DavideWalder 

The scope and claim are (almost) actually correct. The scope is without the `s` which makes kind of sense as you request a single role by it, e.g. `urn:zitadel:iam:org:project:role:key1` and / or `urn:zitadel:iam:org:project:role:key1` and the claim is with the `s` as it will return a list of roles:
```json
{
  "urn:zitadel:iam:org:project:roles": [
    {
      "key1": {
        "id1": "acme.zitade.ch",
        "id2": "caos.ch"
      }
      "key2": {
        "id1": "acme.zitade.ch"
      }
    }
  ]
}
```

But I've removed the {rolename} from the claim completely from the claim and changed it to {rolekey} in the scopes section: https://github.com/zitadel/zitadel/pull/4411
