### ISSUE TITLE
Introspection doesn't return the requested claims

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4367]
**Describe the bug**
By querying the introspection endpoint (using the [this implementation](https://github.com/zitadel/oidc/blob/550f7877f2ac22993ebd923e5f64cfbb9b225ab2/pkg/client/rs/resource_server.go#L14)) this claim `urn:zitadel:iam:user:metadata` is returned, even though in the [documentation](https://docs.zitadel.com/docs/apis/openidoauth/claims) it is declared as `When requested`.

Also, the scope parameter doesn't seem to have an effect, I tried requesting `urn:zitadel:iam:org:project:role:{mycustomrole}` but I always get the same response.

To pass the scope parameter I replaced [`IntrospectionRequest`](https://github.com/zitadel/oidc/blob/fca6cf94339eacb7db9b4f5fc5c9b8e66781c495/pkg/oidc/introspection.go#L11) with
```go
type IntrospectionRequest struct {
	Token string `schema:"token"`
	Scope string `schema:"scope"`
}
request := &IntrospectionRequest{
        Token: token,
        Scope: strings.Join(scopes, " "),
}
```

**Expected behavior**
I assume that, as stated [here](https://docs.zitadel.com/docs/apis/openidoauth/endpoints#introspect-response), it is possible to request specific claims, but I can't figure out how.

**Additional context**
The token is a service user PAT

ZITADEL Cloud 2.4.0

**Comment by mffap** [comment]
@DavideWalder do I understand correctly: you want to get the user metadata?
Not sure what you want to achieve from the description.

We have a guide on that where you can request the user metadata from the userinfo endpoint or include the data in the token: https://docs.zitadel.com/docs/guides/manage/customize/user-metadata

**Comment by DavideWalder** [comment]
> @DavideWalder do I understand correctly: you want to get the user metadata? Not sure what you want to achieve from the description.
> 
> We have a guide on that where you can request the user metadata from the userinfo endpoint or include the data in the token: https://docs.zitadel.com/docs/guides/manage/customize/user-metadata

Getting metadata and roles from the userinfo endpoint works, what I'm trying to understand is why when using introspection:
- I get the metadata even though I didn't request it (from the documentation it should only be returned when requested)
- I can't get the roles, which according to the documentation are available on request

**Comment by mffap** [comment]
Ok, thanks about the clarification. I was confused by the title. We'll have a look.

**Comment by livio-a** [comment]
Hey @DavideWalder 

I checked your issue and can explain most of it. First of all the `When requested` in the docs means that you will have to request the scopes during the authorization request. The scopes will then be granted to the resulting (access / id) tokens.

In your case (using a PAT) there's no authorization request and the PAT is automatically given the metadata (and resourceowner) scope.
When using a PAT the scopes will also automatically be enriched with all possible role scopes of the project the api is part of. If the service account is given any role in that project, then the role claim will be returned. Please checkout the extract of my introspection response using the api example (https://github.com/zitadel/oidc/blob/main/example/client/api/api.go):
![image](https://user-images.githubusercontent.com/9405495/191008442-1e4c877a-e076-4e32-ba5d-d0977f1e9424.png)

The documentation of the PAT and its usage is pending (#3678) We will definitely have to remember to mention these specifics.

**Comment by DavideWalder** [comment]
@livio-a Thanks for the explanation, I in fact misunderstood the `When requested` column. Also, I didn't get any role since the service user didn't have any grant on the project the API was part of.
