### ISSUE TITLE
Domain discovery (identity brokering) doesn't work

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4368]
**Describe the bug**
I'm trying to set up domain discovery so that organizations can have different branding/IDPs but keeping a single login page.

I followed the guide on [identity brokering](https://docs.zitadel.com/docs/guides/integrate/identity-brokering#4-send-the-primary-domain-scope-on-the-authorization-request), but I can't get ZITADEL to show the correct login page after entering the username.

**To Reproduce**
I created the following resources (n.b.: `private_labeling_setting` and `user_login`)

```tf
terraform {
  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "1.0.0-alpha.8"
    }
  }
}

resource "zitadel_org" "main_org" {
  name = "Main Org"
}

resource "zitadel_project" "main_project" {
  depends_on = [zitadel_org.main_org]

  org_id = zitadel_org.main_org.id

  name                     = "main-project"
  project_role_assertion   = true
  project_role_check       = true
  has_project_check        = true
  private_labeling_setting = "PRIVATE_LABELING_SETTING_ALLOW_LOGIN_USER_RESOURCE_OWNER_POLICY"
}

resource "zitadel_application_oidc" "application_oidc" {
  depends_on = [zitadel_org.main_org, zitadel_project.main_project]

  org_id     = zitadel_org.main_org.id
  project_id = zitadel_project.main_project.id

  name                        = "webapp"
  redirect_uris               = ["http://localhost:8080"]
  response_types              = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types                 = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE", "OIDC_GRANT_TYPE_REFRESH_TOKEN"]
  post_logout_redirect_uris   = ["http://localhost:8080"]
  app_type                    = "OIDC_APP_TYPE_WEB"
  auth_method_type            = "OIDC_AUTH_METHOD_TYPE_NONE"
  version                     = "OIDC_VERSION_1_0"
  clock_skew                  = "0s"
  dev_mode                    = true
  access_token_type           = "OIDC_TOKEN_TYPE_BEARER"
  id_token_role_assertion     = true
  id_token_userinfo_assertion = true
}

variable "google_oidc_client_id" {
  type      = string
  sensitive = true
}

variable "google_oidc_client_secret" {
  type      = string
  sensitive = true
}

resource "zitadel_org_oidc_idp" "google_oidc" {
  depends_on = [zitadel_org.main_org]

  org_id               = zitadel_org.main_org.id
  name                 = "Google"
  styling_type         = "STYLING_TYPE_GOOGLE"
  client_id            = var.google_oidc_client_id
  client_secret        = var.google_oidc_client_secret
  issuer               = "https://accounts.google.com"
  scopes               = ["openid", "profile", "email"]
  display_name_mapping = "OIDC_MAPPING_FIELD_EMAIL"
  username_mapping     = "OIDC_MAPPING_FIELD_EMAIL"
  auto_register        = true
}

resource "zitadel_login_policy" "login_policy" {
  depends_on = [zitadel_org.main_org, zitadel_org_oidc_idp.google_oidc]

  org_id                        = zitadel_org.main_org.id
  allow_external_idp            = true
  allow_register                = true
  default_redirect_uri          = "localhost:8080"
  external_login_check_lifetime = "240h0m0s"
  force_mfa                     = false
  hide_password_reset           = true
  idps                          = [zitadel_org_oidc_idp.google_oidc.id]
  ignore_unknown_usernames      = true
  mfa_init_skip_lifetime        = "720h0m0s"
  multi_factor_check_lifetime   = "12h0m0s"
  multi_factors                 = ["MULTI_FACTOR_TYPE_U2F_WITH_VERIFICATION"]
  password_check_lifetime       = "240h0m0s"
  passwordless_type             = "PASSWORDLESS_TYPE_NOT_ALLOWED"
  second_factor_check_lifetime  = "18h0m0s"
  second_factors                = ["SECOND_FACTOR_TYPE_OTP", "SECOND_FACTOR_TYPE_U2F"]
  user_login                    = false
}

resource "zitadel_domain" "domain" {
  depends_on = [zitadel_org.main_org]

  org_id = zitadel_org.main_org.id

  name = "localhost.com"
}

resource "zitadel_human_user" "human_user" {
  depends_on = [zitadel_org.main_org]

  org_id = zitadel_org.main_org.id

  user_name         = "human"
  first_name        = "firstname"
  last_name         = "lastname"
  display_name      = "displayname"
  email             = "human@localhost.com"
  is_email_verified = true
  initial_password  = "Password1!"
}
```

**Expected behaviour**
ZITADEL should match the domain `localhost.com` and present Google as IPD (as if passing the primary domain as a scope, which works)

**Screenshots**

![Screenshot 2022-09-13 at 20 20 08](https://user-images.githubusercontent.com/58290976/189980828-901b2d82-9b0c-4570-93f6-f450cb0b82aa.png)
![Screenshot 2022-09-13 at 20 20 14](https://user-images.githubusercontent.com/58290976/189980845-99e5cc14-eb4f-4b89-9873-9be3d8cfd454.png)

**Additional context**
ZITADEL 2.4.0

**Comment by hifabienne** [comment]
Hi @DavideWalder 

If I understand it correct, what you try to do is at the moment not possible.
We do not have the feature to link an existing user that has a local user right now, after entering the username.
The way to do this right now, is to click on the idp (e.g Google) button on the first screen, where you now enter the username. Then the user will be redirected to the idp. After authentication he gets back to the zitadel login screen and if we find no linkt user, we will show the option to link an existing user or register a new one. If auto register we create automatically a new user.

**Comment by DavideWalder** [comment]
Thanks for the explanation, this might be difficult since we need to be able to have multiple customers each with their own IDP that can't be shown to the others.

For example with might have three customers each using their own Azure AD IDP, but we can't show as login options
- Google
- Azure AD (customer 1)
- Azure AD (customer 2)
- Azure AD (customer 3)

Is this on the roadmap or is there an alternative way to do it? I can't use different URLs for different customers since customers are provisioned dynamically

**Comment by hifabienne** [comment]
At the moment what you try to achieve is only possible with the primary domain scope.
We do not have this on our roadmap right now. 
This Thursday we will have an internal meeting about some topics on how to improve the login flow. We will discuss this also and I will give you feedback after.

**Comment by hifabienne** [comment]
Just to understand correctly what you try to achieve:
The user gets to the login page and enters a loginname e.g fabienne@customer.ch
We can not find the user in ZITADEL but the domain customer.ch exists on an organisation.
We redirect to the branded page of the organisation

Or is is like:
The user gets to the login page and enters a loginname e.g fabienne@customer.ch
The user exists in ZITADEL, we go to the next step e.g password or passwordless
We show Identity providers beneath the input field, so the user is able to link to a user in an idp

**Comment by fforootd** [comment]
Ok, so in regard to discovery. You would be fine of doing discovery on the "username" and route the user towards an organisation based on that mechanic? 

In my mind the default could be to use the domain name suffix (when using the mail) to achieve this (somewhat close as we do it already).

Or do you have more complex needs for discovery? Because in that case we might opt more for an action to achieve the logic part.

One thing that is open though is to show the IDP to the user on the org login regardless of the users state based on the org settings. Right @hifabienne @livio-a 

@DavideWalder How urgent is this to you?

**Comment by DavideWalder** [comment]
The flow could be:
- the user is presented with the login page of the instance
- the user enters its email address
- discovery:
    - if the domain of the address matches one of the organization domains, the user will be presented with that organization's login page
    - if the domain doesn't match, stay with the instance settings
 
From what I understand, the only attribute that uniquely identifies a user across organizations is the login name (username@domain). This means that if a customer doesn't use a unique domain (for example some users might have an external email address, e.g.: @yahoo.com), the logic might be more complicated since nothing prevents an email from being reused in different organizations (this won't happen in our integration though). Same goes for the user name, which is not necessarily unique.

I don't see any other clean solution other than allowing domain discovery only for registered domains. This should not be a limitation since this feature is mostly needed for SSO customers, which have a specific domain.

Security concern:
This would allow any user to probe the login to see if a certain organization is registered (since it would trigger domain discovery). Do you see any issue associated with this?

In terms of urgency: this is currently blocking the onboarding of SSO customers (since they require a dedicated IDP)

**Comment by fforootd** [comment]
Ok, so I think in here are two action items then:

- Our "Domains" feature should be allowed to use as discovery feature based on the domainname
- After the discovery the user needs to be able to register and not only login.

@hifabienne @livio-a @adlerhurst what do you think of this... my2cents are the following

- Iteration of domains is fine with me... i see no way of avoiding that :grin: 
- We should allow register after discovery
- Chjange the behaviour of domain in this direction makes sense (actually I think we should allow customers to decide if domains are used for discovery and/or suffix of usernames)

> In terms of urgency: this is currently blocking the onboarding of SSO customers (since they require a dedicated IDP
Got it, we keep that in mind to raise the prio!

**Comment by hifabienne** [comment]
> Ok, so I think in here are two action items then:
> 
> * Our "Domains" feature should be allowed to use as discovery feature based on the domainname
> * After the discovery the user needs to be able to register and not only login.
> 
> @hifabienne @livio-a @adlerhurst what do you think of this... my2cents are the following
> 
> * Iteration of domains is fine with me... i see no way of avoiding that 😁
> * We should allow register after discovery
> * Chjange the behaviour of domain in this direction makes sense (actually I think we should allow customers to decide if domains are used for discovery and/or suffix of usernames)
> 
> > In terms of urgency: this is currently blocking the onboarding of SSO customers (since they require a dedicated IDP
> > Got it, we keep that in mind to raise the prio!

This sounds good to me. Probably we should extend a policy, to configure if domain discovery is allowed or not.

**Comment by DavideWalder** [comment]
> I created an issue to track this new feature: #4463
> 
> @DavideWalder In terms of urgency what does that mean in a timeline? When would you need this feature?

This is currently the only feature preventing us from using ZITADEL, as soon as the feature is in we can transition.

**Comment by DavideWalder** [comment]
Another question related to domain discovery:

Currently, for users from customers with unique domains, I can create a username from the local part of their email address and register the company domain, so that when logging in they can use their email.

Example:
`john.doe@acme.com` -> username: `john.doe`, organization domain: `acme.com`

This doesn't work if:
- The user has another domain in his email address (e.g.: `john.doe@yahoo.com`)
- There customer has multiple organizations (for example for production and testing)

The only solution I see to the first case is to ask the user to login with `john.doe@acme.com`

The only solution I see for the second case is to create different domains such as `test.acme.com` or `qa.acme.com`, and ask the user to login as `john.doe@test.acme.com`. Am I missing something?

**Comment by hifabienne** [comment]
> Another question related to domain discovery:
> 
> Currently, for users from customers with unique domains, I can create a username from the local part of their email address and register the company domain, so that when logging in they can use their email.
> 
> Example: `john.doe@acme.com` -> username: `john.doe`, organization domain: `acme.com`
> 
> This doesn't work if:
> 
> * The user has another domain in his email address (e.g.: `john.doe@yahoo.com`)
> * There customer has multiple organizations (for example for production and testing)
> 
> The only solution I see to the first case is to ask the user to login with `john.doe@acme.com`
> 
> The only solution I see for the second case is to create different domains such as `test.acme.com` or `qa.acme.com`, and ask the user to login as `john.doe@test.acme.com`. Am I missing something?

You can register multiple domains on an organization. So you can register acme.com aswell as yahoo.com and the user will be able to login with both loginnames. 
Example: username: john.doe,  organization domain: acme.com and yahoo.com, loginname: john.doe@acme.com and john.doe@yahoo.com

The second case depends on your usecase. why do you need multiple organizations? Do you want them to have different users for different use cases? Or do you want them to have different authorizations? So you can solve it by having different domains or by adding the user to one organization and give them different authorizations on different organizations.

**Comment by DavideWalder** [comment]
> > Another question related to domain discovery:
> > Currently, for users from customers with unique domains, I can create a username from the local part of their email address and register the company domain, so that when logging in they can use their email.
> > Example: `john.doe@acme.com` -> username: `john.doe`, organization domain: `acme.com`
> > This doesn't work if:
> > 
> > * The user has another domain in his email address (e.g.: `john.doe@yahoo.com`)
> > * There customer has multiple organizations (for example for production and testing)
> > 
> > The only solution I see to the first case is to ask the user to login with `john.doe@acme.com`
> > The only solution I see for the second case is to create different domains such as `test.acme.com` or `qa.acme.com`, and ask the user to login as `john.doe@test.acme.com`. Am I missing something?
> 
> You can register multiple domains on an organization. So you can register acme.com aswell as yahoo.com and the user will be able to login with both loginnames. Example: username: john.doe, organization domain: acme.com and yahoo.com, loginname: [john.doe@acme.com](mailto:john.doe@acme.com) and [john.doe@yahoo.com](mailto:john.doe@yahoo.com)
> 
> The second case depends on your usecase. why do you need multiple organizations? Do you want them to have different users for different use cases? Or do you want them to have different authorizations? So you can solve it by having different domains or by adding the user to one organization and give them different authorizations on different organizations.

First case:
I saw that it is not possible to register the same domain with multiple organizations (and rightfully so), so that option wouldn't work since I can have `@yahoo.com` users in more than one organization. Still, the different login name could be an acceptable compromise on the user side.

Second case:
In our usage of ZITADEL, we keep a 1:1 relation between ZITADEL organizations and our organizations (which are isolated environments). Access to multiple organizations is modelled by authorizations, so there will only be one user (with grants on `acme.com` and/or `test.acme.com`).

As you suggested, here the best solution would be to have only one organization in ZITADEL and multiple organzations on our side. This adds a lot of complexity to the integration though (I can't use ZITADEL organizations to model access to our organizations, since they wouldn't be 1:1). I'm going to defer this issue, once again the only compromise is that users that were initially created in `test.acme.com` will always have to login with that domain, which is acceptable.

**Comment by DavideWalder** [comment]
@hifabienne Regarding the unique organization holding all the users, this might be a viable option. I would then only create users in separate organizations when dealing with SSO, different IDPs or login settings.

**Comment by hifabienne** [comment]
@DavideWalder 

I am not sure how your complete usecase looks like. There might be solutions. But without understanding the use case it is difficult to help.

What I understood is:

Organization 1: CustomerA
- Users with usernames like john.doe@customerA.com --> they need SSO with an external IDP
- Users with usernames like john.doe@yahoo.com (any email) --> they don't need SSO with an external IDP

Organization 2: CustomerB
- Users with usernames like john.doe@customerB.com --> they need SSO with an external IDP
- Users with usernames like john.doe@yahoo.com (any email, but could be same domain as in other organizations) --> they don't need SSO with external IDP

- For the unique domains like customerA.com and customerB.com you would need domain discovery
- All users will be created/imported via API in ZITADEL. They will not register within the ZITADEL login flow.

**Comment by DavideWalder** [comment]
> @DavideWalder
> 
> I am not sure how your complete usecase looks like. There might be solutions. But without understanding the use case it is difficult to help.
> 
> What I understood is:
> 
> Organization 1: CustomerA
> 
> * Users with usernames like [john.doe@customerA.com](mailto:john.doe@customerA.com) --> they need SSO with an external IDP
> * Users with usernames like [john.doe@yahoo.com](mailto:john.doe@yahoo.com) (any email) --> they don't need SSO with an external IDP
> 
> Organization 2: CustomerB
> 
> * Users with usernames like [john.doe@customerB.com](mailto:john.doe@customerB.com) --> they need SSO with an external IDP
> * Users with usernames like [john.doe@yahoo.com](mailto:john.doe@yahoo.com) (any email, but could be same domain as in other organizations) --> they don't need SSO with external IDP
> * For the unique domains like customerA.com and customerB.com you would need domain discovery
> * All users will be created/imported via API in ZITADEL. They will not register within the ZITADEL login flow.

This is correct, if I understand you suggestion correctly I could create the `yahoo.com` users under a single organization (common to all customers, having many associated domains), and the others under their respective organizations with the registered domains (`customerA.com` and `customerB.com`).
The only caveat is the I need to dynamically register new domains as I encounter them (since I don't know which email users are going to use). This should be easy to manage though

**Comment by DavideWalder** [comment]
@hifabienne I realized now that the usage of domains is not mandatory, I can therefore disabled it with the option `user_login_must_be_domain` for the main organization, this solves the issue for `john.doe@yahoo.com`

**Comment by hifabienne** [comment]
> @hifabienne I realized now that the usage of domains is not mandatory, I can therefore disabled it with the option `user_login_must_be_domain` for the main organization, this solves the issue for `john.doe@yahoo.com`

Yes exactly, so if I understand you right, you can solve your problems?

**Comment by DavideWalder** [comment]
> > @hifabienne I realized now that the usage of domains is not mandatory, I can therefore disabled it with the option `user_login_must_be_domain` for the main organization, this solves the issue for `john.doe@yahoo.com`
> 
> Yes exactly, so if I understand you right, you can solve your problems?

Currently testing, but it seems like it for non-SSO users. I still need to create the users in different organizations though (otherwise if one customer doesn't want to enforce MFA or similar, none can). This is not an issue though, since I can disable domain discovery in all of them (aside from SSO customers). `GetUserByLoginNameGlobal` is a lifesaver

**Comment by hifabienne** [comment]
So I will close this issue, feel free to reopen or open a new one if you still have some other problems
