### ISSUE TITLE
Bug: Info-Icon on 'Domains' leads to 'Page not found'

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4370]
When I click on the little i-icon next to the title under 'Domains', i get to a 'page not found' in docs.

![Image](https://user-images.githubusercontent.com/48990649/190097668-bb6b3264-9e7e-4930-a574-03410e4c8125.png)

There seems something wrong with the anchor on the page @peintnermax as I tried to copy it manually and when I enter it in browser I get the same result:
https://docs.zitadel.com/docs/guides/basics/organizations#how-zitadel-handles-usernames

**Comment by hifabienne** [comment]
this was fixed in #4126
