### ISSUE TITLE
SAML Groups/Roles

### ISSUE THREAD

**Issue by jochumdev** [zitadel/zitadel#4373]
On [Discord](https://discord.com/channels/927474939156643850/927866013545025566/1019364909957533776) I asked for having Roles in the SAML IDP implementation.

"I've tried to setup Zitadel as IDP for Rancher as SP by using it's Keycloak SAML implementation, seems Rancher requires a Groups field, the SamlResponse from Zitadel doesn't include that: [zitadel/saml/.../attributes.go:59](https://github.com/zitadel/saml/blob/2a3e2f3282ca783f1bb72bc96ee46bfc5fff09a5/pkg/provider/attributes.go#L59) are there plans to add a "Roles/Groups" Field? "

As discussed in a call with @stebenz I'll provide a SamlResponse that includes them.

**Comment by harshana5** [comment]
Hi, this issue is blocking me to do a SSO with Amazon quicksights. I have a customer who would like to use zitadel to SSO Amazon quicksight.

**Comment by stebenz** [comment]
@jochumdev never received an example, but I created a follow-up issue, which should cover this with the possibility to edit the attribute names themselves.

@harshana5 this should also cover your blocking situation

I will close this issue in regard to #5014 if any more information or questions come up, please fill it in there.
