### ISSUE TITLE
Implement gzip encoding in ZITADEL

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4378]
Currently assets are transferred without content-encoding and therefore use lots of network traffic. Brotli encoding could improve transfer sizes by almost 10x.
<img width="344" alt="Bildschirmfoto 2022-09-15 um 15 36 39" src="https://user-images.githubusercontent.com/10165752/190418083-6796e730-05e2-4b96-ac7d-28561cd4bd73.png">
<img width="634" alt="Bildschirmfoto 2022-09-15 um 15 39 50" src="https://user-images.githubusercontent.com/10165752/190418859-06717cf2-1195-4562-91fd-583fc7e6a65f.png">

## Workaround

- [ ] Enable Compression in Google Cloud CDN (@eliobischof )

## Acceptance Criteria

- [ ] Implement gzip as default encoding type
- [ ] Extend config to disable gzip or configure additional compressions
- [ ] Test that API, Login, and Console is still working

**Comment by fforootd** [comment]
@livio-a i did a quick research on our CDN and LB side and they do not provide the option to gzip  the assets.

So I think our best option is to implement this in ZITADEL (i think certain api calls could also benefit from this)

**Comment by fforootd** [comment]
CC @hifabienne I think this has a medium prio, change if you feel otherwise

**Comment by fforootd** [comment]
Ok I was wrong https://cloud.google.com/cdn/docs/dynamic-compression

Since late September they support it:

![image](https://user-images.githubusercontent.com/9879976/192554188-671ec36e-1f11-438d-ac5e-21ccbb951a98.png)

@eliobischof can you check if we can quickfix this for the moment in the google cloud cdn
