### ISSUE TITLE
Register user with IDP not possible

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4387]
**Describe the bug**
If I like to register a user with an IDP I always get the error "User Not Found" (Command-4M0fs)
It looks like the process likes to link instead of creating a new user. 
No matter if I have enabled the auto register or not

**To Reproduce**
1. Create a google IDP according to the docs https://docs.zitadel.com/docs/guides/integrate/identity-brokering
2. Go to the login an click register with google use an account that doesn't exist already in ZITADEL
3. see error "user not found"

**Expected behavior**
It should be possible to create the user

**Screenshots**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/38692350/190602641-56913634-e575-4460-ad1e-67d72246b8e3.png">

**Comment by adlerhurst** [comment]
was fixed in https://github.com/zitadel/zitadel/pull/4363
