### ISSUE TITLE
console: add deferred load where eventual consistency may be an issue

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4388]
- [x] Actions after creation

**Comment by hifabienne** [comment]
@peintnermax are you working on this issue? can you please write a description according to a user story (as a user...) 
If you are not working on it, please remove you as assignee

**Comment by peintnermax** [comment]
Eventual consistency issues are difficult to address, as waiting for requests to be made is not always useful nor it provides a 100% success rate. Therefore closing this issue. The above mentioned deferred load has already been implemented.
