### ISSUE TITLE
SEO texts for login and register

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4391]
Users may want to customize their own SEO attributes for the hosted pages (excl. Console).
It's also unclear which language will be presented to robots.

![image](https://user-images.githubusercontent.com/1366906/190644864-b3edc950-e81c-497f-bf21-852ed4bfaa31.png)

**Acceptance criteria**
- [ ] Make Title meta-tags configurable
- [ ] Make Description meta-tags configurable

**Comment by peintnermax** [comment]
#4641 uses the description for the meta tag description, it is also configurable in console
