### ISSUE TITLE
Upgrading from version 2.4.0 to 2.5.0 on PostgreSQL results in a database error when accessing the console

### ISSUE THREAD

**Issue by lapin-b** [zitadel/zitadel#4394]
**Describe the bug**
When upgrading an established installation from version 2.4.0 to version 2.5.0, an HTTP request to the route `oauth/v2/keys` returns the HTTP code 500 with the following body:

```json
{
    "Parent": {
        "Severity": "ERROR",
        "Code": "42P01",
        "Message": "relation \"projections.keys3\" does not exist",
        "Detail": "",
        "Hint": "",
        "Position": 293,
        "InternalPosition": 0,
        "InternalQuery": "",
        "Where": "",
        "SchemaName": "",
        "TableName": "",
        "ColumnName": "",
        "DataTypeName": "",
        "ConstraintName": "",
        "File": "parse_relation.c",
        "Line": 1360,
        "Routine": "parserOpenTable"
    },
    "Message": "Errors.Internal",
    "ID": "QUERY-Sghn4"
}
```

The user sees a "blank" screen. Blank in quotes because the page template is rendered without the page body.

**To Reproduce**
1. Install version 2.4.0, the configuration is setup to use PostgreSQL
2. Execute the initial setup, you can login into the service as the admin if you wish with `/ui/console`
3. Install version 2.5.0 to update your executable
4. Restart the service
5. Access the console via `/ui/console`
6. Web page with the template rendered but no content

**Expected behavior**
I expect that the web console is rendered properly, either a redirection to the login steps or the user interface rendered.

**Screenshots**
While logging in debug mode, I saw this line in systemd's journal:

```
Sep 17 15:48:04 zitadel zitadel[7444]: time="2022-09-17T15:48:04Z" level=debug msg="executing check" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/init.go:199" execute=0 projection=projections.keys3
```

I would assume the migration is not executed ?

**Desktop (please complete the following information):**
Not relevant; issue is on the server side

**Smartphone (please complete the following information):**
Not relevant; issue is on the server side

**Additional context**
The PostgreSQL server is on version 14, as per the requirements in the README. The LXC container running ZITADEL is on Debian bullseye.

While working on other parts of my Ansible roles and playbooks, I *may* have accidentally downgraded the installation, although it's highly unlikely according to the git history on the file and the merge request opened by Renovatebot.

I haven't found any upgrade steps in the documentation ─ unless I really need some glasses ─ so I assumed that upgrading was a matter of replacing the binary and restarting the service.

**Comment by fforootd** [comment]
Hm this should work. Can you show us the commands and args you use to start zitadel with each run.

CC @adlerhurst

**Comment by lapin-b** [comment]
The command is the following: (relative to `/opt/zitadel` to keep the command short)

```
bin/zitadel start-from-init --masterkeyFile config/masterkey.txt --config config/config.yml --steps config/first_step.yml
```

If it should work, I assume that I misused the `start-from-init` command to make sure that the migrations are always applied ?

**Comment by adlerhurst** [comment]
Hi @lapin-b thanks for your report. I think the problem is, that an index name of the keys table is reused. Postgresql only allows the same index name per schema, cockroach allows per table. We will rename the index tomorrow.

**Comment by adlerhurst** [comment]
Hi @lapin-b sorry for the late reply. https://github.com/zitadel/zitadel/releases/tag/v2.6.0 fixes the problem
