### ISSUE TITLE
docs: knative-service.yaml is broken

### ISSUE THREAD

**Issue by thesephirot** [zitadel/zitadel#4427]
**Describe the bug**
the knative-service.yaml is broken:

https://docs.zitadel.com/docs/guides/deploy/knative

```
$ kubectl apply -f https://raw.githubusercontent.com/zitadel/zitadel/main/deploy/knative/zitadel-knative-service.yaml
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/zitadel/zitadel/main/deploy/knative/zitadel-knative-service.yaml": admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```
**To Reproduce**
$ kubectl apply -f https://raw.githubusercontent.com/zitadel/zitadel/main/deploy/knative/zitadel-knative-service.yaml

on a fresh knative cluster

**Expected behavior**
service should be created as with the command above

**Comment by thesephirot** [comment]
corrected in https://github.com/zitadel/zitadel/pull/4773

**Comment by fforootd** [comment]
> corrected in #4773

As i see it https://github.com/zitadel/zitadel/pull/4773 was closed not merged.

**Comment by thesephirot** [comment]
you are right, this was due to a duplicate

https://github.com/zitadel/zitadel/pull/4874

is the right one

**Comment by fforootd** [comment]
> you are right, this was due to a duplicate
> 
> #4874
> 
> is the right one

Got it, thanks
