### ISSUE TITLE
Implement IDP Templates

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4431]
As a ZITADEL developer I can easily extend the code with an additional identity provider, so I only have to implement the specific logic of the provider

**Acceptance Criteria**
- [x] External identity providers can be extended with additional providers
- [x] All providers share some basic informations that are needed alway
      - Enable/Disable just in time provisioning
      - Allow Linking with an existing user
      - Just in time update (Updated information on the provider will be written to the user in ZITADEL)
      - Enable/Disable auto register
      - Which fields should be mapped from the provider to ZITADEL
- [x] I am able to specify some additional fields provider specific
- [x] The required providers are implemented

**Required providers**
- [x] Generic OIDC
- [x] Generic OAuth 2.0
- [x] Generic JWT IdP
- [x] Github
- [x] Gitlab
- [x] Google
- [x] Microsoft AzureAD Tenants
       - Possibility to set emails to verified
       - AzureAD does not send amr and acr

**Additional Information**
Implement idp template possibility, get some inspiration from https://github.com/markbates/goth

**Comment by lukasver** [comment]
Hello! 
We are looking to add LinkedIn as IP for our application, so it would be helpful to have a template and/or know if you plan to add this IP any time soon.
Thanks!

**Comment by hifabienne** [comment]
On the field mappings of the username should be configurable if the username domain should be cut of or just taken as isl

**Comment by stebenz** [comment]
@livio-a, @adlerhurst  and me discussed the following:
- main logic as generic oidc, saml and oauth
- static logic for different providers in ZITADEL which uses the generic part as much as possible
- providers are static in the API so that you can, for example, add a google provider directly, for example in proto with a oneof to cover all provider types in one endpoint
- provider types are a static implementation in the frontend, to use the static definitions in the API

**Comment by fforootd** [comment]
We should discuss wether we include this in the current API design or use this opportunity to create a "new" API -> relates to https://github.com/zitadel/zitadel/pull/4864

**Comment by mffap** [comment]
Make the IDPs active by default

see #4896 (second bullet)

**Comment by loickal** [comment]
Hello!
We are looking to add Apple ID and Google as IP for our application, so it would be helpful to have a template and/or know if you plan to add this IP any time soon.
Thanks!

**Comment by hifabienne** [comment]
> Hello! We are looking to add Apple ID and Google as IP for our application, so it would be helpful to have a template and/or know if you plan to add this IP any time soon. Thanks!

Hi @loickal 
At the moment we do already have all oidc compliant idp. This means, google is already possible you can find the docs here: https://zitadel.com/docs/guides/integrate/identity-brokering
We will first implement the idps mentioned in this issue. After that we have a bigger list here, but we will see what is needed most by the community: https://github.com/zitadel/zitadel/issues/2998 
Or we also accept PRs, I think it will be much easier to contribute an additional IDP as soon as we have the templates
