### ISSUE TITLE
Reset password don’t work without orgdomain

### ISSUE THREAD

**Issue by fdelucchijr** [zitadel/zitadel#4441]
**Describe the bug**
When reseting password for an existent user with “User Loginname must contain orgdomain” domain option disabled generates the message “Check your email for code” with the error message "User could not be found" , and no email is sent (even when everything in smtp is working for email validation, initialization, etc).

Probably related to `internal/api/ui/login/password_reset_handler.go` line 21 or 26?. (I wanted to make a PR as this is a critical error in demonstrate my boss Zitadel as a solution for our Authz needs)

PD: Love your work guys!

1. Uncheck “User Loginname must contain orgdomain”. 
2. "Check reset password" in login page.
3. See the page.

**Desktop (please complete the following information):**
 - Browser safari
 - Version 15.6.1

**Comment by hifabienne** [comment]
Thanks for you report. We will have a look at it.

**Comment by hifabienne** [comment]
Hi @fdelucchijr 
I just tried this by myself and could not reproduce it.
Can you please answer the following questions?

1. Did you already login with this user before?
2. If you go to the detail page of this user in the ZITADEL console with an administrator account. Can you see the events on the side? Can you see if a code was generated and if an email was sent?
This should look something like this:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/38692350/192549596-6c864e50-98e4-422c-88c8-a24d28519743.png">

**Comment by fdelucchijr** [comment]
> Hi @fdelucchijr 
> 
> I just tried this by myself and could not reproduce it.
> 
> Can you please answer the following questions?
> 
> 
> 
> 1. Did you already login with this user before?
> 
> 2. If you go to the detail page of this user in the ZITADEL console with an administrator account. Can you see the events on the side? Can you see if a code was generated and if an email was sent?
> 
> This should look something like this:
> 
> <img width="356" alt="image" src="https://user-images.githubusercontent.com/38692350/192549596-6c864e50-98e4-422c-88c8-a24d28519743.png">
> 
> 
> 
> 

Hi @hifabienne 
The Zitadel cluster at my company is down for now (when I show my boss the Oauth2 Webview screen in our Flutter app they almost see it as blasphemy 🥲, I really loved your software as a developer standpoint).
I can only response the first question securely, but anything else I can help you with count on me.

1. Yes, but I tried also with a private browser window (also resetting the cache in the main window).

2. I don't remember if the code was generated or not, but the end result was not receiving the email.

**Comment by fforootd** [comment]
> The Zitadel cluster at my company is down for now (when I show my boss the Oauth2 Webview screen in our Flutter app they almost see it as blasphemy smiling_face_with_tear, I really loved your software as a developer standpoint).

Well that's a bummer :cry:, maybe we can lend a hand to advocate in an other direction?

**Comment by fdelucchijr** [comment]
> > The Zitadel cluster at my company is down for now (when I show my boss the Oauth2 Webview screen in our Flutter app they almost see it as blasphemy smiling_face_with_tear, I really loved your software as a developer standpoint).
> 
> Well that's a bummer 😢, maybe we can lend a hand to advocate in an other direction?

@fforootd Our CEO has already made up his mind for now, thank you for your kindness in replying.
That’s the reason because I was really active in the issues addressing friction with other models/architectures. She left me with the quote “Maybe we migrate in the future, let them grow till that time”, and that sound pretty decent coming from her. 
As I say the main issues was friction related to our already developed Flutter App, mostly in the native design perspective. I think is only a matter of time (as you already developed so so much in less time than the other related projects). Keep out the good work, I will follow you from close and recommend you every time I can.

**Comment by fforootd** [comment]
Thank you for the kind words, appreciate it :sunglasses: 

We definitely have some ideas in our minds to address for deeper integrations in mobile/native apps.

**Comment by fdelucchijr** [comment]
> Thank you for the kind words, appreciate it 😎
> 
> We definitely have some ideas in our minds to address for deeper integrations in mobile/native apps.

I will try to be present in the GH discussions related to that!
For now, @hifabienne can I help you with something more to reproduce this issue?

**Comment by hifabienne** [comment]
Hi @fdelucchijr 

We did have some issues, that the emails land in the spam folder.
So maybe you can check your spam folder?

The other thing is how does your SMTP configuration look like?
And could you look into the failed events section? https://docs.zitadel.com/docs/concepts/eventstore/implementation#failed-events 
If it failed to send the email you should probably see some errors there.

But as you said your cluster is down, it will probably be difficult to find out where the problem is. Since we did not have any other issues with sending emails, I think its somehow a configuration problem of the cluster.

**Comment by fdelucchijr** [comment]
@hifabienne I don’t see any rows in that tables, but the email is not in my spam. Probably is some configuration error, but as I mentioned in the first comment:

> no email is sent (even when everything in smtp is working for email validation, initialization, etc)

As is an issue irreproducible for now, I will close this issue and reopen it if I get to reproduce it. Thanks for your time and effort @hifabienne  @fforootd !
