### ISSUE TITLE
Extend Login Policy

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4462]
The login policy should be extended to be able to configure if some of the steps should be shown or not. At the moment it is not possible to disable that mfa setup is shown in the login, even if it is not forced. Also it would be great to disable if an email should be verified for login or not.

**Acceptance criteria**
- [ ] Extend login policy: disableMfaSetupInLogin
- [ ] Mfa Setup should not be shown during login, if its disabled

**Comment by hifabienne** [comment]
MFA Prompt is the timestamp defined in the login policy. If the timestamp is 0 the prompt should not show

**Comment by samarth-ramesh** [comment]
> . Also it would be great to disable if an email should be verified for login or not.

Any updates on that?

Or is that not in the roadmap for anytime soon?

Regards,
Samarth R
