### ISSUE TITLE
Can't access zitadel behind traefik reverse proxy

### ISSUE THREAD

**Issue by petrm** [zitadel/zitadel#4475]
**Describe the bug**
I am trying to set up zitadel using the provided docker image behind traefik proxy.
The first page of /ui/console starts loading and then an error appears in the browser console:

Refused to connect to 'http://sso.mydomain.tld/.well-known/openid-configuration' because it violates the following Content Security Policy directive: "connect-src 'self' sso.mydomain.tld".

Please note the **http://** in the error message. My zitadel is at https://sso.mydomain.tld with TLS.

I have following configuration in place:
```
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=sso.mydomain.tld
      - ZITADEL_EXTERNALPORT=443
```
Am I missing something else?

**Comment by petrm** [comment]
RTFM

I also had to change  --tlsMode disabled to  --tlsMode external, which now allows me to get to the login.
Is there an equivalent environment variable instead of the command line argument?

**Comment by fforootd** [comment]
I think at the moment it needs to be set https://github.com/zitadel/zitadel/blob/main/cmd/tls/tls.go#L32

Although it internally just sets:

```
tlsEnabled = false
externalSecure = true
```

@livio-a maybe make this argument optional could already solve this.
Default wise we could define the tlsEnabled and externalSecure that they reflect either `external` or `disabled`

**Comment by fdelucchijr** [comment]
@petrm probably is related to Traefik don't serve http2 by default, you must enable it in the Traefik Service to access some resources in Zitadel UI.

**Comment by petrm** [comment]
@fdelucchijr I opened a separate ticket where I already again wrote RTFM for myself and provided information that I added explicitly h2c to the traefik config.
Nevertheless, zitadel is the first application where I had to do that and I think it should be solved with `Upgrade: h2c`, right?

**Comment by fdelucchijr** [comment]
> I think it should be solved with `Upgrade: h2c`, right?

Probably, in my experience isn't needed.
Have you tried clearing the cache? (Typical Browser related question 😂😂😂, but in CORS 🤔🤷🏻‍♂️)

**Comment by petrm** [comment]
I added h2c explicitly to the reverse proxy configuration as mentioned above and it is now working fine.
I am just guessing that sending header Upgrade: h2c by zitadel would automatically switch to h2c, even if the client first asks for http/1.1.

**Comment by fforootd** [comment]
I am not sure how traefik handles this. But we recommend setting h2c/http2 explicit to avoid unwanted side effects.

Lets close this issue but feel free to discuss open this if the need arises.

**Comment by hanrea** [comment]
The reason for this issues is that the configuration is not processed ：

**Comment by hanrea** [comment]
This [function](https://github.com/zitadel/zitadel/blob/3c3bce1a6b665dab6731dbacaf65745cf1cb46ff/cmd/tls/tls.go#L25
) will overwrite `externalSecure` and `tls.enabled` config.Use ` --tlsMode external`  command   can solve it


This function breaks the consistency. Do you want to keep it？
