### ISSUE TITLE
Error 404 on first login to the console

### ISSUE THREAD

**Issue by petrm** [zitadel/zitadel#4476]
Environment: official docker image
On first login to the console and changing the default password, the console opens, but does not render fully. There are 404 errors in the Chrome console, for example accessing
https://sso.mydomain.tld/zitadel.auth.v1.AuthService/ListMyProjectOrgs

There are also errors in the docker log, sample:

zitadel  | time="2022-10-01T13:44:08Z" level=warning msg="asset in login could not be served" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/resources_handler.go:35" error="download failed: ID=DATAB-pCP8P Message=Errors.Assets.Object.NotFound Parent=(sql: no rows in result set)" file="policy/label/css/variables.css?v=2022-10-01T13:43:44Z" org=181421804890357795
zitadel  | time="2022-10-01T13:44:21Z" level=warning msg="asset in login could not be served" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/resources_handler.go:35" error="download failed: ID=DATAB-pCP8P Message=Errors.Assets.Object.NotFound Parent=(sql: no rows in result set)" file="policy/label/css/variables.css?v=2022-10-01T13:43:44Z" org=181421804890357795

Side note: it is not obvious from the official documentation that the username of the admin is zitadel-admin in org ZITADEL on sso.mydomain.tld -> zitadel-admin@zitadel.sso.mydomain.tld, the only place I found it in was the default sample config in the git repo.

**Comment by fforootd** [comment]
Hi - This looks like a http2 upstream problem.

What kind of proxy are you using? We provide some config snippets here https://docs.zitadel.com/docs/guides/manage/self-hosted/proxy

> Side note: it is not obvious from the official documentation that the username of the admin is zitadel-admin in org ZITADEL on sso.mydomain.tld -> [zitadel-admin@zitadel.sso.mydomain.tld](mailto:zitadel-admin@zitadel.sso.mydomain.tld), the only place I found it in was the default sample config in the git repo.

Great feedback 👍

Question: @livio-a  @hifabienne the version 2.7.0 with #4245 does this not change to just zitadel-admin?

**Comment by petrm** [comment]
Thanks, you are right, this was it. I added explicitly h2c to traefik config.
traefik.http.services.myservice.loadbalancer.server.scheme=h2c

**Comment by fforootd** [comment]
Great, let me close this issue then, feel free to reopen if you encounter further problems.
