### ISSUE TITLE
ZITADEL should allow IDP Login from customer portal

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4486]
At the moment we do have two separat accounts for ZITADEL customer portal and ZITADEL Instance. This makes it confusing for our customers in the onboarding process. The following parts need to be changed to be able to login with an external idp.

**Acceptance criteria**
- [x] #4487
- [ ] AddInstance allows to create with an user with an external idp
- [ ] ...

**Comment by hifabienne** [comment]
@fforootd can we close this? since we have discussed the possibilities we want to add to integrate console into customer portal.

**Comment by fforootd** [comment]
> @fforootd can we close this? since we have discussed the possibilities we want to add to integrate console into customer portal.

I think there are multiple steps for this. Let me create an issue for this with  the content of the gdocs we created and outline the options we have
