### ISSUE TITLE
Change instance setting domain suffix needs to migrate existing accounts, so they are able to login with the existing loginname

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4487]
At the moment it is possible to enable/disable domain suffix on the domain policy on a instance level. If it is disabled all usernames will just be computed without the suffix. This can result in duplicated loginnames, since there can exist multiple user with the same username but not the same loginname.

To be able to change the setting we should make a migration for all users.

**Acceptance Criteria**
- [ ] instance with domain suffix enabled should be disabled
       - [ ] test case: multiple users with same username e.g fabienne@acme.zitadel.cloud, fabienne@test.zitadel.cloud should still have this username if its disabled
       - [ ] 
- [ ] instance with domain suffix disabled should be enabled
     - [ ] if username is fabienne@zitadel.com and zitadel.com is registered as domain, we should just remove the suffix, this will result in the loginname fabienne@zitadel.com again
     - [ ] if username is fabienne@zitadel.com and zitadel.com is not registered, we should let the username fabienne@zitadel.com this will result in the loginname fabienne@zitadel.com@domain

**Comment by livio-a** [comment]
we also need change the unique constraints
