### ISSUE TITLE
SMTP send test mail

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4504]
As a administrator I want to be able to configure my SMTP and send a test email to find out if everything works before activating it for all my customers.

**Acceptance criteria**
- [ ] I can create a SMTP configuration and put it in a preview mode
- [ ] I can send a test email from a SMTP no matter of the state (preview/active)
- [x] I can deactivate an SMTP
- [x] I can activate an SMTP
- [x] I am allowed to have no active SMTP configuration
- [x] I am able to see the error messages that happen when an email can't be sent
- [ ] I am able to reset my SMTP configuration to the default of ZITADEL

**Comment by doncicuto** [comment]
@hifabienne you can assign this to me

**Comment by hifabienne** [comment]
hei @doncicuto 
Thank you very much. I think this issue is really valuable to ZITADEL. But unfortunately never made it to the top of priorities so far.

**Comment by doncicuto** [comment]
@hifabienne I'll start working on this as soon as #5503 is reviewed and merged

**Comment by doncicuto** [comment]
Alright! as #5503 was merged and is now live, I'm starting to work on this one.

**Comment by doncicuto** [comment]
Hi @mffap, @hifabienne, @peintnermax and anyvbody interested in this issue. 

As always I try to offer you a preview about this issue so you can send me your feedback. Also if @peintnermax has any 

I've started with the test for an existing configuration. In the providers table we'll find a new icon (is a flask):

![image](https://github.com/zitadel/zitadel/assets/30386061/ad6d5880-15a1-4f16-98a1-30b4c33496b0)

If we click the icon we'll open a dialog so we can set the recipient address. 

![image](https://github.com/zitadel/zitadel/assets/30386061/32033224-cb0f-483a-a7c1-f1b75d3ab2a0)

Once we entered an email and click the Test button we'll see the result of our test

![image](https://github.com/zitadel/zitadel/assets/30386061/9287cfb5-35b0-4bd3-a8bb-710317903739)

If no error is found:

![image](https://github.com/zitadel/zitadel/assets/30386061/07f1f557-9c9d-47a2-8e27-0c4268681c5e)

I'll try to add a spinner, and will set a border color (green/red) depending on the result...

Any comment so far? Thanks in advance

**Comment by hifabienne** [comment]
HI @doncicuto 
Thanks for looking into that I really like it.
Quick question, do you implement a request on the api side to be able to send a test email?
Or how do you plan on implementing it?

**Comment by mloepfe** [comment]
Hi

just an idea to make testing even easier. 

You could take the recipient address (as a default) from the current user. Because if I am an administrator and am configuring the smtp providers I most probably want to send the test email to me.

Best Matthias

**Comment by doncicuto** [comment]
Hei @hifabienne, yes there's a new endpoint in Zitadel Admin API:

![image](https://github.com/zitadel/zitadel/assets/30386061/0287a56f-3310-4fe0-b766-76f4e15845e5)

Hi @mloepfe thanks for the proposal, it totally makes sense, I'll try to add that default value

**Comment by doncicuto** [comment]
@JayPe69, right now the API expect the id of the smtp provider assuming that It has been created. I'm preparing a different endpoint that allows to send SMTP provider settings and test connection even if the smtp provider hasn't been saved

**Comment by doncicuto** [comment]
Sorry @JayPe69 these endpoints are new and you'll have to wait a bit until I finish this PR
