### ISSUE TITLE
Store access and execution logs

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4508]
Storing request audit logs and actions execution logs enables creating projections for fine grained metrics and quotas or for streaming execution logs.

- [ ] Access logs are stored in a table **logstore.access**, execution logs go to **logstore.execution**.
- [ ] An **access log entry** contains the instance id, the organization id, the timestamp, the request url, the request headers w/o the *Authorization* header, the response status and the response headers.
  An **execution log entry** contains the instance id, the organization id, the action id, the action run id, the timestamp and the log entry.
- [ ] Storing access logs and execution logs can be **disabled by configuration**.
- [ ] Update frequencies are configurable through minimal frequency and maximal bulk sizes.
  An update is triggered when any of the conditions occurs.
  By configuring the max bulk size and update frequency, memory usage and database computation costs are controllable.
- [ ] The **minimal frequencies** for access logs and execution logs are configurable.
  Configuring 0 seconds for update frequencies makes ZITADEL store the logs synchronously.
  The access logs minimal frequency defaults to 120 seconds.
  The execution logs minimal frequency defaults to 0 seconds (synchronously).
- [ ] The **maximal bulk sizes** for access logs and execution logs are configurable.
  Configuring 0 makes ZITADEL store the logs synchronously.
  The access logs maximal bulk size defaults to 100.
  The execution logs maximal bulk size defaults to 0 entries (synchronously).
- [ ] The **storage retention times** for access and execution logs are configurable independently and default to 45 days.
- [ ] **Ordering of access logs** is not guaranteed,
  **ordering of execution** logs is guaranteed.
- [ ] Access logs and execution logs can be **server side streamed** using the management API.

**Comment by hifabienne** [comment]
The access logs will maybe need some more information depending on what type. e.g if its something in the login we probably want to know on which client/project it happens

**Comment by eliobischof** [comment]
Do we also have to consider properties for easy GDPR deletion?

**Comment by fforootd** [comment]
> Do we also have to consider properties for easy GDPR deletion?

Yes, but it is tricky to handle... I mean in the access logs ip and ids might be affected by this, but whats even harder to achieve is the execution log for actions. Since a "customer" can write anything in there without prior knowledge.

I think we need to provide a lifecycle policy to delete logs in a scheduled manner. At least for the moment being i think this is the only way.

**Comment by eliobischof** [comment]
> > Do we also have to consider properties for easy GDPR deletion?
> 
> Yes, but it is tricky to handle... I mean in the access logs ip and ids might be affected by this, but whats even harder to achieve is the execution log for actions. Since a "customer" can write anything in there without prior knowledge.
> 
> I think we need to provide a lifecycle policy to delete logs in a scheduled manner. At least for the moment being i think this is the only way.

So the point above is enough ATM?

> The storage retention times for access and execution logs are configurable independently and default to 45 days.

**Comment by fforootd** [comment]
I think using 90 Days as default is better, but yes for the moment being it is sufficient

**Comment by eliobischof** [comment]
Suggesting the following changes:
- Storing access logs and execution logs can be ~disabled~enabled by configuration.
- If at least one of min frequency and max bulk is not 0, logs are asynchronously stored in bulks.
