### ISSUE TITLE
Enable configuring quotas

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4509]
Configuring quotas enables admins to block future usage based on previous usage.
- [ ] A quota for authenticated requests and action minutes each are configurable **for an instance** through the **system API** and the ZITADEL binary configuration in the **DefaultInstance** section.
- [ ] A **quota configuration** has a start time, a duration, and an amount of units (eg. number of requests, seconds, ...)
- [ ] The start time and duration determine the **quota periods**, after each the used units are reset.
- [ ] When the **quota for authenticated requests is reached**, ZITADEL responds with the status code 429 Too many requests for future authenticated requests to the instance.
  Also, it sets a Cookie value, so WAFs can block further traffic before it reaches ZITADEL.
- [ ] When the **quota for action execution minutes is reached**, ZITADEL doesn't run actions anymore, instead it marks new runs as failed with an error "no more action minutes available".
- [ ] An **email is sent** to quota creators and instance owners when 50 percent of a quota is reached, when 80 percent of a quota is reached and when 100 percent of a quota is reached.
- [ ] The **console shows a warning** on all pages when 50%, 80% and 100% of a quota is reached, only to quota creators and instance owners.
  This is also end-to-end tested
- [ ] **Metrics are exposed** for authenticated requests and action minutes in quota period and all time and for quota percentages.
  They are labelled with the instance id and the organization id.
- [ ] Data for authenticated requests, action minutes and reached quotas are asynchronously **projected from the logstore tables and eventstore.events table** (quotas) and stored in read models. (Relies on #4508)

**Comment by hifabienne** [comment]
I would add a reaction on 95% because with 80 the customers probably think they have a lot of time. 
But I think this will be configurable anyways from our perspective. And later on even the customer should be able to configure at what point he likes an information

**Comment by fforootd** [comment]
> When the quota for authenticated requests is reached, ZITADEL responds with the status code 429 Too many requests for future authenticated requests to the instance.
> Also, it sets a Cookie value, so WAFs can block further traffic before it reaches ZITADEL.

I think we should allow this reaction to be configurable. It could be `block`, `redirect`or `inform

**Comment by eliobischof** [comment]
> > When the quota for authenticated requests is reached, ZITADEL responds with the status code 429 Too many requests for future authenticated requests to the instance.
> > Also, it sets a Cookie value, so WAFs can block further traffic before it reaches ZITADEL.
> 
> I think we should allow this reaction to be configurable. It could be `block`, `redirect`or `inform`

We should handle inform separateley. ZITADEL also knows multiple channels like email, sms, stdout and file. The thresholds for messages, as @hifabienne mentionened, also should be configurable. IMO, the messaging config belongs together.

**Comment by fforootd** [comment]
I agree the channels should be kept to the existing ones!

**Comment by eliobischof** [comment]
Closing in favor of https://github.com/zitadel/zitadel/issues/4973
