### ISSUE TITLE
Login name doesn't correspond to the one entered by the user

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4513]
**Describe the bug**
If a different login name has been entered before, it is not possible to correct it unless the page is refreshed.

This might be tied to the `authRequestID` being the same

**To Reproduce**
1. Create a user with login name `john.doe@acme.com`
2. Enter the login name for a different non-existing user, as `john.doe2@acme.com`
<img width="483" alt="Screenshot 2022-10-09 at 13 13 17" src="https://user-images.githubusercontent.com/58290976/194754019-72a98e4b-9a39-43f5-894e-ed6ad4afd141.png">

3. Go back
<img width="450" alt="Screenshot 2022-10-09 at 13 13 23" src="https://user-images.githubusercontent.com/58290976/194754033-cea94f10-5ace-44f1-9b47-dd795479d8cd.png">

4. Enter the correct login name
<img width="479" alt="Screenshot 2022-10-09 at 13 13 28" src="https://user-images.githubusercontent.com/58290976/194754043-b94684d2-bd57-443e-b5cd-08386a08b6f8.png">

5. The login page still shows the first (wrong) login name
<img width="455" alt="Screenshot 2022-10-09 at 13 13 34" src="https://user-images.githubusercontent.com/58290976/194754056-41d0080c-3a7f-4189-9029-9739c731b465.png">

**Expected behavior**
The login name should be the one entered by the user

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**
ZITADEL Cloud 2.8.0

**Comment by hifabienne** [comment]
Hi @DavideWalder 

Thanks for your issue. We will have a look at it.
