### ISSUE TITLE
On boarding in console

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4564]
Sometimes it is difficult to users who got the first time to the ZITADEL console, to find out what they do have to do. We could make kind of a checklist they have to go through to solve the first tasks. The checklist could be shown in the dashboard. And after I have resolved one step I get back to the dashboard and the next point.

**Acceptance criteria**
- [ ] 1. Create a project (step is shown as resolved as soon as projects length > 0)
- [ ] 2. Create a client  (step is shown as resolved as soon as applications length > 0)
- [ ] 3. Branding (step is shown as resolved as soon as private labeling policy is added)
- [ ] 4. SMTP (This we should implement as soon as we have the test email #4504 )
- [ ] 5. Add a second user
- [ ] 6. Give the user some rights in ZITADEL

**Comment by mffap** [comment]
related #4298

**Comment by juergrinaldi** [comment]
As discussed with @peintnermax beforehand, here is a first draft of a new starting page in console to improve/encourage onboarding process for new users:

![zitadel-onboarding01a](https://user-images.githubusercontent.com/48990649/205915502-9d30edcc-7ed3-4a04-bce5-57b6487bbfd8.png)
(Picture 1 showing the new starting page (Home))

![zitadel-onboarding01b](https://user-images.githubusercontent.com/48990649/205915519-008045a3-08e1-432b-91b1-24b1f5c3eddf.png)
(Picture 2 shows the omipresent progress bar and the hover state of it with the detail view visible)

The idea behind this is that we want to guide new users with the most essential setup steps as a progress process. 
If the user is experienced with ZITADEL or doesn't want to see this progress view, they can opt-out by clicking on the link bottom right of the detail view (see above).
Also once they have completed the progress to 100%, they can "close" the progress (the above mentioned link will change to 'Congratulations! You've done it') and the Home view loses the progress indicators.

Which steps are relevant for a MVP is to discuss (or see above) but I'd go with a min-maxed approach.

Continuation in Issue #4835
