### ISSUE TITLE
Can't scroll in the "Edit roles" pane

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4568]
**Describe the bug**
When editing a project grant by opening the "Edit roles" pane, it is not possible to scroll.

Temporarily solved by using a vertical screen and zooming back.

**To Reproduce**
1. Create about 50 roles in a single project
2. Edit a project grant
3. Try to see all the roles

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**
ZITADEL 2.8.2

**Comment by DavideWalder** [comment]
Also, if roles are on multiple pages, only the ones selected in the current page are kept. So selecting `a-role` and `z-role` is only possible if they fit on the same page

**Comment by hifabienne** [comment]
Thanks for your feedback.
We will have a look at it
