### ISSUE TITLE
Identity Brokering Google IDP forces password change

### ISSUE THREAD

**Issue by swratten** [zitadel/zitadel#4570]
Seems the same as #4472 but for Google

**Describe the bug**
Initially user can login through idp after account creation, but after clearing localstorage, session storage & cookies or using incognito / private tabs / separate browser user is met with enter email code and new password.

**Additional context**
Using postgres as database if that may cause any extra edge-cases
Using V2.8.2 docker container

**Comment by hifabienne** [comment]
Hi @swratten 
Thanks for your report.
You are right. We will fix this asap.

**Comment by swratten** [comment]
Thanks @hifabienne.
It may be a separate bug, but when trying to auto register with the same idp, after the Oauth flow it will return to the same previous register account screen (choose username & password or External Idp as UI options).

**Comment by hifabienne** [comment]
@livio-a not sure but I believe this is already fixed right?

**Comment by livio-a** [comment]
Yes this was fixed with the latest improvements on IDPs
