### ISSUE TITLE
Default are not shown in Login Interface Texts/External user not found

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4572]
**Describe the bug**
The text is not shown if it the same as the default value (unlike for the other pages). This makes it harder to find where to edit a message.

**To Reproduce**

**Expected behavior**
The current values should be shown (as is the case for the other pages).

<img width="997" alt="Screenshot 2022-10-18 at 17 59 26" src="https://user-images.githubusercontent.com/58290976/196482618-7939f3b1-3c73-441f-98bb-f34a031c875b.png">

**Screenshots**
<img width="1000" alt="Screenshot 2022-10-18 at 17 57 47" src="https://user-images.githubusercontent.com/58290976/196482529-bd86b5fd-fb77-407c-90b4-ab512544e2fd.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**
ZITADEL Cloud 2.8.2

**Comment by hifabienne** [comment]
@peintnermax did you have a look at this? is it a frontend or backend problem? Or is it because the labels are empty?

**Comment by peintnermax** [comment]
<img width="519" alt="Bildschirmfoto 2022-11-21 um 16 25 37" src="https://user-images.githubusercontent.com/10165752/203092877-7497c415-7497-437f-a912-fcfe599a810f.png">

This is a backend issue.. externalUserNotFoundTexts from getDefaultLoginTexts return empty strings in contrast to others

**Comment by stebenz** [comment]
fix is included in #4733
