### ISSUE TITLE
Can't add a role to user through user-screen > "authorizations" > "new" if user already has role in that project

### ISSUE THREAD

**Issue by pr0gr8mm3r** [zitadel/zitadel#4577]
**Describe the bug**
Can't create add a role to user through user-screen > "authorizations" > "new" if user already has role in that project

**To Reproduce**
1. Create a user (without any roles)
2. Go to "Users" > Click on user > "Authorizations" > "New"
3. Assign a role of a project to the user
4. Works
5. Click "new" again on authorizations screen
6. Select another role **of the same project**
7. Get "User role already exists" error

**Expected behavior**
It should just add the role in addition to the already existing role on that project.

 - Version 2.8.2

**Comment by hifabienne** [comment]
Hi @pr0gr8mm3r 
An authorization should always be unique for the user and a project.
So if you already have an existing authorization and you like to add some more roles click on the existing row in the authorization table and you will be able to select which roles you like.

If you click on new, we do not append roles to an existing authorization.

![image](https://user-images.githubusercontent.com/38692350/196686284-e3a1bda8-5b82-48c6-ad2e-30e0653b603b.png)

**Comment by hifabienne** [comment]
Yes I agree with you.

**Comment by juergrinaldi** [comment]
I agree. And it should definitely be Option 1.

**Comment by hifabienne** [comment]
I have created a user story for this issue and will close this one. Feel free to subscribe to the new issue: https://github.com/zitadel/zitadel/issues/4952
