### ISSUE TITLE
Conflicting messages regarding email verification status

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4583]
**Describe the bug**
The user has been imported but needs to set the first password (imported with verified email). The frontend shows conflicting messages.

Also, this user was invited yesterday, but its code shows as expired when trying to set the password. The user still shows as `Initial`, is there a way to understand if the invitation code is expired? `user.UserState` doesn't have a specific value for that.

**To Reproduce**
1. Import a user with
```go
	clients.management.ImportHumanUser(
		middleware.SetOrgID(ctx, organization.Id),
		&managementpb.ImportHumanUserRequest{
			UserName: email,
			Email: &managementpb.ImportHumanUserRequest_Email{
				Email:           email,
				IsEmailVerified: true,
			},
			Profile: &managementpb.ImportHumanUserRequest_Profile{
				FirstName:         firstName,
				LastName:          lastName,
			},
		},
	)
```

**Screenshots**
![Screenshot 2022-10-19 at 17 40 53](https://user-images.githubusercontent.com/58290976/196740744-12d1e61a-3824-488d-ac2d-03a4903f74b5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**
ZITADEL Cloud 2.9.1

**Comment by DavideWalder** [comment]
Context:
In our integration, we report the invitation status from ZITADEL in our GUI, so that users know if:
- the invitation has been accepted
- the invitation is pending (and can be resent if the email was lost for example)
- the invitation expired (must therefore be refreshed), this is currently missing

**Comment by hifabienne** [comment]
@peintnermax I think its what we discussed here: https://discord.com/channels/927474939156643850/1019895518383583323/threads/1042021943202828369

What is the state?

**Comment by peintnermax** [comment]
The button for changing the email now doubles as sending the initial email.
https://github.com/zitadel/zitadel/pull/4776

**Comment by adlerhurst** [comment]
It looks to me like its also a projection problem. If I create a new user with verified email I have to enter a code on first login

**Comment by stebenz** [comment]
@peintnermax maybe there is also something we have to change in the console, if a user has a verified email, but is still initial as he has no way to login, the "This users email is not verified yet" is still displayed at the top, which is wrong in my opinion.

@adlerhurst I found the problem for that, if you needed an init-code but you set the email as verified at the same time, the emailverified event was never written.

@DavideWalder in your situation, if you create a user directly with a verified email, but you provide no way on how the user can login, for example a password, it's correct that the user still has the status "Initial". 

There is no state or similar to display if the send code is still valid, you only get the information if you try to verify your email for example. This would require a check in different intervals to compare the expiry times of the codes with the current time.
