### ISSUE TITLE
Can't disable watermark

### ISSUE THREAD

**Issue by pr0gr8mm3r** [zitadel/zitadel#4584]
**Describe the bug**
I can't disable the Zitadel watermark (and social icons in footer)

**To Reproduce**
1. Go to Settings > Branding
2. Expand section 'Advanced Behavior"
3. Section is empty

**Expected behavior**
I can disable the watermark

**Additional context**
#4498 contained a description of that bug, but was closed.

**Version**
v2.9.1 selfhosted with postgres as database

**Comment by hifabienne** [comment]
@peintnermax what is the progress of this issue?

**Comment by peintnermax** [comment]
Could not reproduce this issue tn the cloud. @adlerhurst Can you take a look if the labelpolicy is correctly returned with a postgres db as this could prevent the toggle to be shown?

**Comment by goran-hc** [comment]
I can reproduce this issue locally by starting the zitadel with [docker compose](https://docs.zitadel.com/docs/guides/deploy/compose).

I have same behaviour on organization and instance settings:
![image](https://user-images.githubusercontent.com/36618604/205688473-611fdd81-f8a5-4250-bd92-3917be855d53.png)

**Comment by hifabienne** [comment]
@pr0gr8mm3r @goran-hc 
I think we just found out what the problem is, since we could not reproduce it.
Do you have an add-blocker installed?
They sometimes block some inline things what results in not showing everything in the console.

**Comment by peintnermax** [comment]
Interesting.. we'll definately fix this classname and try to avoid _adv_ prefixes in future.. Thx for the hint 👍😎

**Comment by m1212e** [comment]
For future people visiting: You need to change this per organization, only changing the instance settings isn't enough. You can switch by clicking the settings button in the top right.
