### ISSUE TITLE
/ui/login/loginname times out with organization-only IDPs

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4587]
**Describe the bug**
When an IDP is defined on the organization only (not on the instance), `/ui/login/loginname` times out unless username-password is also allowed.
This works fine when the identity provider is set on the instance.

**To Reproduce**
1. Organization settings:
![Screenshot 2022-10-20 at 10 18 01](https://user-images.githubusercontent.com/58290976/196894913-dfdb0ab0-01a3-4d30-b952-fb2ed8b9dc27.png)
![Screenshot 2022-10-20 at 10 18 30](https://user-images.githubusercontent.com/58290976/196895021-e30ccbcc-71ef-4b53-a387-061222c0717e.png)
![Screenshot 2022-10-20 at 10 19 03](https://user-images.githubusercontent.com/58290976/196895138-46f6b7b8-8273-44a4-aec7-ca4fc6cd021f.png)

Change `Username Password allowed` to true in the organization settings, then this is shown:
<img width="499" alt="Screenshot 2022-10-20 at 10 27 02" src="https://user-images.githubusercontent.com/58290976/196897033-c594f92a-b1d8-4b1e-9fdf-266d574b6ec8.png">

**Expected behavior**
With `Username Password allowed` set to false, the user should directly be sent to the IDP login (as done when the IDP is set on the instance).

**Desktop**
 - OS: macOS
 - Browser Chrome

**Additional context**
ZITADEL 2.9.1 running in docker-compose

**Comment by DavideWalder** [comment]
Container logs (not sure if related):
```
zitadel-terraform-zitadel-1  | time="2022-10-20T08:26:54Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:60" error="timeout: context canceled"
```

**Comment by DavideWalder** [comment]
Found the issue, I set the wrong issuer in the IDP config. I guess no action required

**Comment by bithavoc** [comment]
@DavideWalder thank you ❤️

**Comment by oscarcalderonc** [comment]
It would be nice to get more descriptive logging indicating that there is an issuer mismatch or something. We struggled for a couple of hours today after an extra slash was in the issuer
