### ISSUE TITLE
Login Interface Texts policy bug when customizing OTP option text

### ISSUE THREAD

**Issue by pr0gr8mm3r** [zitadel/zitadel#4588]
**Describe the bug**
When I set the text for the OTP option, it is also applied on the u2f option of the 2fa prompt.

The bug seems to be here: https://github.com/zitadel/zitadel/blob/2bfa51da1c7a0be079a851521b13211f99fe69bf/console/src/app/modules/policies/login-texts/helper.ts#L101 (Notice that the u2f text is set to the otp text

**To Reproduce**
1. Go to Settings >Login Interface Texts > Initialize MFA Prompt
2. Enter something custom for "otpOption"
3. The console and the login frontend show the same text for both options

**Expected behavior**
I can customize the otp and u2f option texts independently.

v2.9.1

**Comment by fforootd** [comment]
Nice catch. 

@peintnermax I guess that's one for you 😁

**Comment by peintnermax** [comment]
@pr0gr8mm3r Didn't quite figure a way out to generate such a file,
```
const setters = Object.keys(map.initMfaDoneText).map((key) => {
      const setFcn: string = `set${key.charAt(0).toUpperCase()}${key.slice(1)}` as any;
      return (r5 as any)[setFcn](map.initMfaDoneText?.title ?? '');
    });
``` 
the request method name can't be indexed with a generated value like this in typescript or do you have any other idea..

**Comment by peintnermax** [comment]
@pr0gr8mm3r thanks for the hint.. created a [PR](https://github.com/zitadel/zitadel/pull/4600) 👍
