### ISSUE TITLE
Display all possible login names on user detail view

### ISSUE THREAD

**Issue by DoGab** [zitadel/zitadel#4593]
With version  > 2.9.0 it is also possible to login with the e-mail address or the phone number. If these features aren't disabled, display also these possible login names on the user detail view. Currently only the `username@domain` combination and `username` are displayed.

**Comment by peintnermax** [comment]
In order to show the data, the user profile has to be extended with this information backend-wise as a regular user has no access to request the policy.

**Comment by hifabienne** [comment]
We need the policy from the backend

**Comment by hifabienne** [comment]
Hei @DoGab 
As we start with scrum in January, we have created the related user stories to your request.
Feel free to track the releated user stories as we will close this one, to avoid duplicates: #4928 #4929
