### ISSUE TITLE
Console create organization use personal account by default

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4614]
When creating a new organization, the option "Use your personal account as organization owner" is disabled by default and a form is presented to the user.

I would suggest to enable the option by default to reduce friction for first-time users. There are certain cases where you want to be in control and create a new org-owner user when creating an org. Yet this feels like an advanced use case.

Option disabled:
<img width="706" alt="Screenshot 2022-10-26 at 09 30 22" src="https://user-images.githubusercontent.com/1366906/197962861-be025e2d-ff59-4abf-8541-3302a17d1b23.png">

Option enabled:
<img width="713" alt="Screenshot 2022-10-26 at 09 32 40" src="https://user-images.githubusercontent.com/1366906/197962932-b24cf1e0-eebe-4385-9e0f-cee23f445128.png">

**Comment by mffap** [comment]
@juergrinaldi do you agree?

**Comment by hifabienne** [comment]
I totally agree. This did already annoy me a few times.

**Comment by juergrinaldi** [comment]
> @juergrinaldi do you agree?

completely agree. 👍
