### ISSUE TITLE
Extend import user for external users

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4639]
At the moment it is only possible to import users with username and password. But some organizations do only allow login with an external idp. It should be possible to import the user directly with a link to the idp

**Acceptance criteria**
- [ ] Extend the import human user with external idp (idpid, userid, displayname)
- [ ] If only external idp is enabled on the org, no init mail should be sent

**Comment by mffap** [comment]
@DavideWalder for your info

**Comment by livio-a** [comment]
there aren't any initial mails if the email is imported as verified
