### ISSUE TITLE
DNS Verification Failed - ORG-GH3s

### ISSUE THREAD

**Issue by Foxtrek64** [zitadel/zitadel#4646]
**Describe the bug**
Wasn't sure whether to create a new issue or to bump #4086 but I am now encountering the same issue.

**To Reproduce**
1. Go to your organization's domain settings.
2. Add a new domain using DNS registration.
3. Create the `_zitadel-challenge` TXT record in DNS
4. Confirm with nslookup
5. Verify domain

**Expected behavior**
Domain verification should complete, but instead the error message `Domain verification failed (ORG-GH3s)` appears.

Tagging @fforootd and @livio-a as you guys were working on the initial issue. Do let me know if you guys would like to poke around in my org/instance and I'll get you the information and access.

**Comment by Foxtrek64** [comment]
Guess I'm going to close this ticket because it eventually resolved itself. I went to dinner and tried again when I came back and it verified successfully. Perhaps it had to do specifically with me basically "seizing" the domain as it was originally tied to an instance on zitadel.ch.

**Comment by Cadjoe** [comment]
Just make sure I'm doing this correctly. I'm setting the name to `_zitadel-challenge` and the content to the `DNS token`, correct?

**Comment by Cadjoe** [comment]
Nevermind! It definitely takes time, maybe 15-20 minutes, to propagate.

**Comment by fforootd** [comment]
> Nevermind! It definitely takes time, maybe 15-20 minutes, to propagate.

Yes, depending on your DNS server settings it can take some time to validate.
