### ISSUE TITLE
Error changing password: invalid UpdateMyPasswordRequest.OldPassword: value length must be at most 70 bytes

### ISSUE THREAD

**Issue by cedegi** [zitadel/zitadel#4647]
**Describe the bug**
When i try to change my password, i get the error: 

 invalid UpdateMyPasswordRequest.OldPassword: value length must be at most 70 bytes

**To Reproduce**
1. Go to 'Password and Security'
2. Click on 'set new Password'
3. enter old password and new password twice

**Expected behavior**
i would suspect a changed password 

**Screenshots**

![Screenshot from 2022-11-01 17-14-47](https://user-images.githubusercontent.com/66091263/199282941-eaa66a27-000c-46d3-8bb2-0d3f18440389.png)
**
**Additional context**

**Comment by livio-a** [comment]
Hey @cedegi 

We use bcrypt algorithm to securely hash passwords. The algorithm can take a maximum input of 72bytes. Any further input will result in the same hash.
A password with this length (and a decent complexity of course) is secure enough. If security is a concern, I'd suggest setting up 2nd factor. Best would be a WebAuthN / UTF based like TouchID/FaceID, WindowsHello and so on.
And you could then also setup passwordless authentication with that device: https://docs.zitadel.com/docs/manuals/user-profile#passwordless

**Comment by cedegi** [comment]
Hi livio,

I am fine with that, yes - otherwise we shouldn't allow user to set such a long Password as an initial one, so the user user can't change his password afterwards in the console. Passwort reset in logged out condition worked fine :)

**Comment by livio-a** [comment]
Sorry I didn't get that the initial password can be set longer than that. That's a bug then and i'll take this issue to track it.
Thanks for letting us know.

**Comment by livio-a** [comment]
we need to have a look on how to solve this. IMO we need to have some check based on the hash algorithm and we can set some limit sane max limit in the api.
and limiting the old password should then only be limited by the sane limit.

**Comment by hifabienne** [comment]
I have created a user story according to this bug, please subscribe to the new issue to track the status as we close this one: https://github.com/zitadel/zitadel/issues/4993
