### ISSUE TITLE
Confusing behaviour in the 2-Factor Setup screen

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4648]
**Describe the bug**
It is not clear that an option needs to be selected (we received complaints that nothing happens when clicking "next").
Also, the "skip" and "next" buttons change the cursor to a finger pointer, but the MFA options don't (it is not clear that they are clickable).

Possible solutions:
- preselect one of the two. In that case which one is selected should be clearly visible, currently the blue square is a bit hard to see. Also, the fact that the authenticator app section is colored as opposed to the other section might be misleading (at a first glance it looks like the colored one is the selected one).
- disable the "next" button unless on option is selected (displaying the reason on hover)
- display an error telling the user that they have to make a selection

**Screenshots**
<img width="426" alt="Screenshot 2022-11-02 at 10 58 18" src="https://user-images.githubusercontent.com/58290976/199460312-1fbb5b14-6b53-40a9-b320-7c20608be88d.png">

**Additional context**
ZITADEL Cloud 2.10.0

**Comment by juergrinaldi** [comment]
Hi Davide,
Thanks a lot for bringing this up. I'll have a look.
There's definitely some room for improvement here.

**Comment by juergrinaldi** [comment]
I suggest the following fixes:
- Make the selection border `3px` wide. This ensures that it's more visible to the user
- Additionally highlight the background of the button (more on that below _(1)_) to emphasize the selection even more
- set pointer to the mouse cursor as with the other buttons
- disable 'next' while nothing is selected _(2)_
- Add the text `'Please select one of the options below'` to the description to make clearer instructions.

here's an example:

![image](https://user-images.githubusercontent.com/48990649/199697229-39a4726f-8e90-4c0d-8583-bed684f993b7.png)  
![image](https://user-images.githubusercontent.com/48990649/199698459-b80d761b-042b-4459-a3e1-e2852849198f.png)

1) @peintnermax I think we have two options here: either go with a variation of the selected color theme (which can be difficult to anticipate) or we go with a fixed color for each theme. I'd go with the later. (I used `#303D5A` and `#DEDEFE` in the example above)  let's get some internal A/B testing on the colors, to see what works best.

2) I like the suggestion of @DavideWalder to include a tool tip on why a button is disabled. we should consider to implement that everywhere.

@DavideWalder Thanks again for your suggestions. Highly appreciated! 👍  As you can see I didn't include the preselection of one of the options. Reasons for this is, that it might get overlooked/-read and we don't want to influence the user to one of the two options. But with the above mentioned changes, confusion and errors should hopefully drop to a minimum.
