### ISSUE TITLE
Inform users about password change

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4653]
[BSI cloud computing compliance (C5) - PSS-05](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Kriterienkatalog-C5/C5_AktuelleVersion/C5_AktuelleVersion_node.html):
The user is informed about changing or resetting the password

Today, a user is being notified when the password was reset, but not when the password was changed.

**Acceptance criteria**
- [ ] When a password was changed, then the corresponding user receives an email informing about that change

**Considerations**
- [Discussion: 2/ Inform users/managers of sensitive actions](https://github.com/zitadel/zitadel/discussions/2162#discussioncomment-1999807)

**Comment by mffap** [comment]
fyi @cedegi

**Comment by fforootd** [comment]
@mffap do you know if that only applies to password changes? In my mind it could also be applicable to passwordless and mfa, otp changes.

**Comment by mffap** [comment]
> @mffap do you know if that only applies to password changes? In my mind it could also be applicable to passwordless and mfa, otp changes.

Yes. That's why I linked the original discussion about this feature (considerations). We could expand this. The must requirement for this task is password change.

**Comment by fforootd** [comment]
Ok, good to know 👍

**Comment by hifabienne** [comment]
As we start with SCRUM in Janaury I have created a user story for this task.
Feel free to track the following issue, as we close this one to avoid duplicates: https://github.com/zitadel/zitadel/issues/4912
