### ISSUE TITLE
console: make username copyable from delete dialog

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4681]
Move username to the description above as the label of the formfield is not suitable for copying

<img width="390" alt="Bildschirmfoto 2022-11-09 um 15 41 23" src="https://user-images.githubusercontent.com/10165752/200859823-c8c1e380-582e-4833-972c-98ca4616808c.png">

**Comment by mffap** [comment]
Yes, please 👍

**Comment by fforootd** [comment]
Yes 😁

**Comment by peintnermax** [comment]
didn't expect this to be so critical 😂

**Comment by fforootd** [comment]
> didn't expect this to be so critical 😂

Haha it is... doing demos often and you see this as problem 😁
