### ISSUE TITLE
[Bug]: registration ui breaks with long custom-domains

### ISSUE THREAD

**Issue by virth** [zitadel/zitadel#4706]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

registration and logn ui break with long custom-domains

### To reproduce

1. create ZITADEL Org
2. use looooong custom-domain
3. open register or login-ui

### Screenshots

![image](https://user-images.githubusercontent.com/18188015/202132413-41ada889-7bf3-4f08-b446-5449eb1e50f9.png)

### Expected behavior

no break

**Comment by fforootd** [comment]
FYI @peintnermax

**Comment by peintnermax** [comment]
https://github.com/zitadel/zitadel/pull/4672/commits/17e3b93489260c573db35685b9cac9f4c9e06ffa fixes the problem

**Comment by virth** [comment]
This is still happening in the registration form in version 2.14.5 in account.learnfox.ch

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/18188015/206716548-7cf022f0-28a2-40ba-ba5c-967a0211f5fc.png">

@hifabienne can we reopen this issue?

**Comment by virth** [comment]
thank you! 🙏

**Comment by virth** [comment]
Just so you know: This is not a priority anymore as we decided not show the domain anyway. It just caught my eye while testing something.

**Comment by hifabienne** [comment]
I have created a user story according to this bug. This issue will be closed feel free to subscribe to the new user story:
https://github.com/zitadel/zitadel/issues/4951
