### ISSUE TITLE
Event Sourcing Architecture

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#4708]
The purpose of this issue is to design a document to clarify how event sourcing is used in ZITADEL. RFCs for the event sourcing layer should always rely on this document. The document will change over time. Especially during the initialisation phase. Later the document will be stored as markdown file. This document is not meant to replace any parts of the docs pages.

The document:

# Eventsourcing Architecture

ZITADELs business logic is based on event sourcing. Instead of manipulating data, each action is written into an append only log, called eventstore.

This document is based on the docs of [cockroach](https://github.com/cockroachdb/cockroach/blob/master/docs/design.md). Especially their [RFCs](https://github.com/cockroachdb/cockroach/tree/master/docs/RFCS).

## Goal

This document builds the foundation of the event sourcing storage implementation, the framework to create write models, read models and projections for caching and storing data and build objects.

## Requirements

Every decision made on this topic must fullfil the following check list. This checklist might change over time.

### Eventstore requirements

- [ ] High throughput 
  - [ ] Read
  - [ ] Write
- [ ] Easy to implement additional commands/events
- [ ] Non blocking per instance
- [ ] Non blocking per aggregate root
  - [ ] Write has some conditions
  - [ ] Read must not contend write side
- [ ] ? in memory storage ?
- [ ] Regionality by event
- [ ] Possibility to subscribe to events
- [ ] Unique constraints

### Write models requirements

Data container to create commands

- [ ] Validate input
- [ ] Query events from eventstore in real time (blocking)
- [ ] create commands
- [ ] snapshotting

### Read models requirements

Data container to read events from the eventstore

- [ ] Query objects from projections
- [ ] Query events from projections 
- [ ] create objects (mainly to return to user)
- [ ] time travel

### Projection requirements

Cache which represents query data in denormalized format

- [ ] subscribe to events
- [ ] cache/store objects
- [ ] regenerate stored objects
- [ ] verify correctnes of object

## Index

| Word                  | Definition                                        | Links |
| :-------------------- | :------------------------------------------------ | :---- |
| event sourcing        |                                                   | -     |
| event store (storing) |                                                   | -     |
| cqrs                  | Command and Query Responsibility Segregation      | -     |
| event driven          |                                                   | -     |
| Pub/Sub               |                                                   | -     |
| Aggregate             |                                                   | -     |
| Aggregate Root        |                                                   | -     |
| subscription          |                                                   | -     |
| eventual consistency  |                                                   | -     |
| command               | Intent to create an event                         | -     |
| event                 | Action saved in the eventstore                    | -     |
| write model           | Data container to create commands                 | -     |
| read model            | Data container to read events from the eventstore | -     |

**Comment by fforootd** [comment]
Should this not be stored as PR template and triggered when something changes in folder xyz?

**Comment by adlerhurst** [comment]
> I like this approach!
> 
> On remark. Should this not be stored as PR template and triggered when something changes in folder xyz?

Thanks

My initial thoughts were that this document should be used during issue discussions. As soon as something is getting implemented different checks should apply, like [benchmarks](https://pkg.go.dev/golang.org/x/benchmarks) which should not decrease in speed, which might be a good metric for a PR template. 

With an issue discussion I mean something like a change to read models in the framework or adding fields in events/commands.

**Comment by fforootd** [comment]
Ok I see your point. In that case an issue template might make sense.

**Comment by adlerhurst** [comment]
@fforootd 

To be honest im not sure so far. I want to get a feeling of what feels right to the development proceds and afterwards manifest some business processes for that

**Comment by fforootd** [comment]
Ok so I ask differently how should "somebody" know that he should respect the content of this issue?

We certainly can start this way. I am only asking because I think nobody will know when and how to use this 😁

**Comment by adlerhurst** [comment]
I totally agree. My priority list looks like this: define the purpose of the doc > design document > fill doc > design processes

**Comment by hifabienne** [comment]
@adlerhurst @fforootd Is this relevant right now? Or should we close it? As I don't see what we want to do with it.
