### ISSUE TITLE
feat: Add Chinese translate document

### ISSUE THREAD

**Issue by hanrea** [zitadel/zitadel#4719]
Description
I hope to help your add Chinese documents , I suggest splitting the document directory into separate git repositories。
**Acceptance criteria**
- [Document ] Add Chinese translate document

**Comment by hanrea** [comment]
[💊 crowdin project](https://crowdin.com/project/zitadel)
[ 🧬  separate repositories](https://github.com/vecmat/zitadel_doc.git )  (Translating)

**Comment by fforootd** [comment]
Hi @hanrea 

Thank you for bringing this up. Do I understand you correctly that you would like to help translate ZITADELs documentations into Chinese?

I am asking because at the moment we lack the resources and skills to contribute in a meaningful way to this 😁

**Comment by hanrea** [comment]
Hey  @fforootd  
Yes, I will translate the documents into Chinese, Translate work in progress, maybe I need a little help. 
But I don't know whether you need the Chinese version. If you need it, I will contribute and submit it. If not, I will release it as a third party.
I have more ideas about promoting Zitadel in China. If you are interested, please contact me. In the early days, I was a technical support consultant, document manager and community manager of the [Cocos game engine](https://github.com/cocos2d/cocos2d-x) .

**Comment by fforootd** [comment]
Got it!

Let me check-in with the team how we would like to proceed with this. Should not take me too long to come around again.

Already thanks for your effort!
