### ISSUE TITLE
[Bug]: New auto-registered external IDP users get an email verification code

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#4730]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When a user auto-registers by logging in with an external IDP (Azure in our case), they get an email verification code. Is it possible to consider email addresses from external IDPs as verified?

### To reproduce

1. Create an IDP with auto-register on
2. Create a user by logging in with that IDP

### Version

v2.12.0

**Comment by hifabienne** [comment]
Hi @DavideWalder 

When registering with an external idp we take the attributes we get in the token from the idp.
Unfortunately Azure AD does not send the email_verified attribute. 

We have a solution for this, you can find it in our azure ad idp guide:
https://docs.zitadel.com/docs/guides/integrate/azuread-oidc#create-user-with-verified-email

**Comment by DavideWalder** [comment]
Perfect, didn't see that part of the docs. Thanks!
