### ISSUE TITLE
[Bug]: Migration 05 breaks Postgres compatibility

### ISSUE THREAD

**Issue by coelho** [zitadel/zitadel#4739]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Error Message:
 
```
time="2022-11-23T01:34:21Z" level=fatal msg="unable to migrate step 5" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:112" error="ERROR: relation \"instance_id_idx\" already exists
```

Relevant migration:
https://github.com/zitadel/zitadel/blob/main/cmd/setup/05.go

### To reproduce

Start v2.13.0 using Postgres.

### Version

v2.13.0

### Additional Context

My assumption is that CockroachDB allows duplicate index names, but Postgres does not.
See: https://stackoverflow.com/questions/26997441/why-cant-two-tables-have-an-index-of-the-same-name

SQL Example:

```
zitadel=> CREATE INDEX instance_id_idx ON adminapi.current_sequences (instance_id);
CREATE INDEX
zitadel=> CREATE INDEX instance_id_idx ON adminapi.failed_events (instance_id);
ERROR:  relation "instance_id_idx" already exists
```

There is also lot of `CREATE INDEX IF NOT EXISTS` in the code. However, this can just silently ignore the issue and not actually make the index! See this example:

```
zitadel=> CREATE INDEX instance_id_idx ON adminapi.current_sequences (instance_id);
CREATE INDEX
zitadel=> CREATE INDEX instance_id_idx ON adminapi.failed_events (instance_id);
ERROR:  relation "instance_id_idx" already exists
zitadel=> CREATE INDEX IF NOT EXISTS instance_id_idx ON adminapi.failed_events (instance_id);
NOTICE:  relation "instance_id_idx" already exists, skipping
CREATE INDEX
```

**Comment by coelho** [comment]
Confirmed this still exists in v2.14.0-true.1 branch.
https://github.com/zitadel/zitadel/blob/v2.14.0-true.1/cmd/setup/05.sql

**Comment by livio-a** [comment]
Hey @coelho Thanks for reporting this. I've already created a PR to fix this: https://github.com/zitadel/zitadel/pull/4740

**Comment by coelho** [comment]
Re: Additional Context (concern about other indexes), I did a quick check:

```
# fgrep -R 'WithIndex' . | pcregrep -o1 'NewIndex\("(.*)",' | sort
actions_ro_idx
api_client_id3_idx
app3_project_id_idx
auth_meth_ro_idx
domain_idx
enabled_idx
granted_org_idx
identifier_idx
idp_ro_idx
idp_user_idx
inst_memb_user_idx
instance_domain
is_default_idx
link_ro_idx
name_idx
oidc_client_id_idx3
org_memb_user_idx
pat_ro_idx
pat_user_idx
pg_ro_idx
proj_grant_memb_user_idx
proj_memb_user_idx
project_ro_idx
ro_idx
saml_entity_id_idx3
user_grant_ro_idx
user_grant_user_idx
user_ro_idx5
username_idx5
usr_md_ro_idx
```

Migrations:

```
write_model
active_instances
agg_type_agg_id
agg_type
agg_type_seq
max_sequence
```

Looks like there's no conflicts in the rest of the code, so no concerns there.
