### ISSUE TITLE
Back Button on Login Prompt not behaving as expected

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4745]
If I select one of the previously used accounts from the list, then press the 'back' button, I won't get redirected back to the previous screen with the list, but to the 'manual' inputfield.
Not only isn't this as expected (back to where I came from) but also not very helpful.

A) I select one of the previously used accounts from the list
![image](https://user-images.githubusercontent.com/48990649/203506594-99a85407-1c28-43d7-93eb-7a441dc3a79f.png)

B) I press on 'back' (because I want to select another entry of that list)
![image](https://user-images.githubusercontent.com/48990649/203506694-99aa04cb-2a9e-42c5-b0c3-a486bbcfae88.png)

C) I land on this page, instead of A)
![image](https://user-images.githubusercontent.com/48990649/203506752-ef65e7c3-64e7-4f8b-a86c-3e07011de482.png)

Expected behavior: When pressing 'back' button, I expect to get redirected to the first screen.
(Same issue with customer portal, btw)

**Comment by mffap** [comment]
Is this the same as #2097 ?

**Comment by juergrinaldi** [comment]
> Is this the same as #2097 ?

It is. 🙈 Sorry, couldn't recall that I already opened an issue for this.
