### ISSUE TITLE
[Bug]: Text customization code panel is always clickable

### ISSUE THREAD

**Issue by virth** [zitadel/zitadel#4788]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

The panel that you can use to insert codes into custom texts can be clicked even when you can not see it. 

This is really confusing when you don't understand what is happening cause it happens that you miss-click between the text fields instead of the next one which then edits the last field.

### To reproduce

1. Click between the fields

### Screenshots

![2022-11-30 13 51 22](https://user-images.githubusercontent.com/18188015/204807486-76df40ee-8b52-4d9b-8023-61a235837831.gif)

**Comment by hifabienne** [comment]
Thanks for your report, we will have a look at it.

**Comment by hifabienne** [comment]
I have created a releated user story for your bug to be able to take it into our scrum planning. Due to this, this issue will be closed. Feel free to subscribe to the new one: https://github.com/zitadel/zitadel/issues/4945
