### ISSUE TITLE
[Bug]: Custom text field editing is broken

### ISSUE THREAD

**Issue by virth** [zitadel/zitadel#4789]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When you edit one field and save, another field will be edited as well.

### To reproduce

1. Edit «Passwort Initialisierierung» -> Description
2. Code will be edited as well
3. Try to resset -> an error appears

### Screenshots

![2022-11-30 13 24 23](https://user-images.githubusercontent.com/18188015/204809686-abca5cec-05ce-4a9b-b32c-6f194b718ed7.gif)

*error after resetting*
![Screenshot 2022-11-30 at 14 32 00](https://user-images.githubusercontent.com/18188015/204809754-750c53e9-e642-4e1c-9f18-3956dac68c3e.png)

**Comment by fforootd** [comment]
CC @hifabienne

**Comment by hifabienne** [comment]
@stebenz I think you already fixed something in the custom text. is this included? Will this be deployed this evening?

**Comment by stebenz** [comment]
> @stebenz I think you already fixed something in the custom text. is this included? Will this be deployed this evening?

Unfortunately not, I just tested it locally, and the text gets filled in before sending it to the backend.
@peintnermax Can you please have a look at it?
