### ISSUE TITLE
Timestamp with 'one hour ago' and the like not very viable

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4794]
As an admin I want to be able to see what time a user got created, so If I created two users shortly I can see which one was first.

**Acceptance Criteria**
- [ ] I can see the exact timestamp on each user

**Additional Information**
Timestamps displayed like this are not very viable imo: ![console-timestamp01](https://user-images.githubusercontent.com/48990649/204834228-83946a4a-a228-43b6-89a8-db191ac7eb15.png)

Reasons is, that is pretty inaccurate, especially if more than one is present and I want to know which one is older.

Solutions:
a) make all timestamp in the regular format, i.e. 12.12. 2022 - 09:30
b) make a tooltip that shows the exact time stamp

**Comment by juergrinaldi** [comment]
Timestamps displayed like this are not very viable imo: ![console-timestamp01](https://user-images.githubusercontent.com/48990649/204834228-83946a4a-a228-43b6-89a8-db191ac7eb15.png)

Reasons is, that is pretty inaccurate, especially if more than one is present and I want to know which one is older.

Solutions:
a) make all timestamp in the regular format, i.e. 12.12. 2022 - 09:30
b) make a tooltip that shows the exact time stamp

**Comment by fforootd** [comment]
CC @peintnermax
