### ISSUE TITLE
Tables not usable with keyboard only

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4795]
As a console user I want to be able to navigate through tables by keyboard to better access all elements of console.

**Acceptance Criterias**
- [ ] I am able to navigate through all tables in ZITADEL console by keyboard
- [ ] I am able to go to the detail of a table entry all by keyboard
- [ ] As first action I can go through the table header¨
- [ ] As next action I go to the selection box and links, buttons, etc
- [ ] As next action I go to the whole line
- [ ] With pressing space I go to the detail of a line

**Additional Information**
In the current state the user can't navigate in tables with keyboard only.
there is a selection of single cells within the table (which has little use imo) but you can't enter the detail view of selected line.

![console-tableentry-select-withtab01](https://user-images.githubusercontent.com/48990649/204836490-a656bf73-045c-463b-8c27-91057b14e633.png)

related issue in customer portal: https://github.com/caos/customer-portal/issues/709

**Comment by fforootd** [comment]
CC @peintnermax

**Comment by hifabienne** [comment]
I will close this as it has not been relevant in the past, and no upvotes from customers
