### ISSUE TITLE
Console doesn't translate all elements on language switch (missing translations?)

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4796]
**Acceptance Critiera**
- [ ] Console UI does only change the translations when i saved the language on my profile, not when I change it

There are some missing tanslations in console, especially the audit trail (but also in subnavigations, on dates and the 'instance' button in the header)

![console-language01](https://user-images.githubusercontent.com/48990649/204840420-d77d61af-ffa4-40eb-8f9f-4a6cb7d931fb.png)

**Comment by juergrinaldi** [comment]
FYI: I added the frontend labe because of the date translations. They are probably frontend related (?)

**Comment by fforootd** [comment]
CC @peintnermax

**Comment by hifabienne** [comment]
At the moment as soon as I change the language in my profile, the console is translated. 
It should translate only if I save it.

**Comment by hifabienne** [comment]
will close this issue, had a look at the console looks fine to me
