### ISSUE TITLE
Make shortcut for keyboard cheat sheet available for keyboard use (tab)

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4797]
As a user of the console I want to be able to access the keyboard shortcuts by keyboard.

**Acceptance Criteria**
- [ ] I can navigate to the "?" button to open the keyboard shortcuts with my keyboard (tab)

**Additional Information**

The Button `? ` is not navigatable with `tab` and with that you can't see the shortcuts when you navigate with keyboard only (ironically).

I'm aware (thanks Max :)) that the user can press `?` to see the popup but that's pretty unusual and not very intuitive. (it also might conflict with some screen readers usages)

![console-keyboardshortcuts01](https://user-images.githubusercontent.com/48990649/204841443-dec3e3fe-1659-451b-8162-cb6c00773660.png)

Solution: Make the `?` navigatable with `tab`

**Comment by juergrinaldi** [comment]
The Button `? ` is not navigatable with `tab` and with that you can't see the shortcuts when you navigate with keyboard only (ironically).

I'm aware (thanks Max :)) that the user can press `?` to see the popup but that's pretty unusual and not very intuitive. (it also might conflict with some screen readers usages)

![console-keyboardshortcuts01](https://user-images.githubusercontent.com/48990649/204841443-dec3e3fe-1659-451b-8162-cb6c00773660.png)

Solution: Make the `?` navigatable with `tab`

**Comment by fforootd** [comment]
CC @peintnermax
