### ISSUE TITLE
[Bug]: {domain}/auth/v1/users/me/profile API not working 

### ISSUE THREAD

**Issue by JayKaneriya11** [zitadel/zitadel#4833]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

When we run that API on the self hosted version. we got the internal server error QUERY-Rfheq (zitadel error id) with status code 500. When we try it with in correct access token it's giving as expected result. Surprisingly when we downgrade our zitadel from version 2.14.2 to 2.13.1 then it's working properly.

### To reproduce

1. Create zitadel user
2. Get access token for that user 
3. Put that token inside postman or any other tool inside Authorization header with bearer tag
4. Got internal server error 

### Screenshots

Error
{
    "code": 13,
    "message": "An internal error occurred (QUERY-Rfheq)",
    "details": [
        {
            "@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
            "id": "QUERY-Rfheq",
            "message": "An internal error occurred"
        }
    ]
}
_No response_

### Version

2.14.2

### Operating System

Mac
Postman

**Comment by hifabienne** [comment]
Hei @JayKaneriya11 
Thanks for your issue.
I was able to reproduce it, we will further investigate and get back to you as soon as we know more.
