### ISSUE TITLE
Onboarding improvement console

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#4835]
As a developer using ZITADEL I want to be able to setup everything needed as fast as possible, to be able to login to my app.
The developer should be led through everything he needs to setup.

**Acceptance Criteria**
- [ ] I be led through the setup flow in ZITADEL, till I can login to my app the first time
- [ ] I see which steps I have successfully done
- [ ] I see wich steps are missing
- [ ] I can skip/hide the setup flow help
- [ ] Onboarding implemented according to the screen design only the stepper not the boxes

Based on #4564 

As discussed with @peintnermax beforehand, here is a first draft of a new starting page in console to improve/encourage onboarding process for new users:

![zitadel-onboarding01a](https://user-images.githubusercontent.com/48990649/205915502-9d30edcc-7ed3-4a04-bce5-57b6487bbfd8.png)
(Picture 1 showing the new starting page (Home))

![zitadel-onboarding01b](https://user-images.githubusercontent.com/48990649/205915519-008045a3-08e1-432b-91b1-24b1f5c3eddf.png)
(Picture 2 shows the omipresent progress bar and the hover state of it with the detail view visible)

The idea behind this is that we want to guide new users with the most essential setup steps as a progress process. 
If the user is experienced with ZITADEL or doesn't want to see this progress view, they can opt-out by clicking on the link bottom right of the detail view (see above).
Also once they have completed the progress to 100%, they can "close" the progress (the above mentioned link will change to 'Congratulations! You've done it') and the Home view loses the progress indicators.

Which steps are relevant for a MVP is to discuss (or see #4564) but I'd go with a min-maxed approach.

**Comment by hifabienne** [comment]
From my perspective this is exactly what I want:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/38692350/209170960-c1f52284-e684-429c-b305-d71bdf7223fc.png">

It is more clear than the boxes on the home screen.
@peintnermax I would implement this in the frontend, the data you need you can store in the user metadata with the version of the "onboarding" flow, so we have the possibility to react on updates of the flow.

**Comment by fforootd** [comment]
Just as an input, we can store in the user metadata weither a user already finished a wizard with a certain version

**Comment by juergrinaldi** [comment]
@hifabienne according to your input above, I went through my initial designs again to improve them.

First, my reasoning behind the card layout:

- The description texts on the cards can help new users to understand what these steps do/are needed for.
- the cards can act as supplementary quicklinks (especially for existing/veteran users)
- ...and are in line with the other (customizable) links/shortcuts

I tried to adjust the designs above to counter the issue that it might not be clear enough on what to do next:

**Empty state of the progress**
![zitadel-onboarding02a](https://user-images.githubusercontent.com/48990649/215735384-5cbabab5-f451-4661-a35e-d1e0a5e56de4.png)
1. A button to initialize a wizard that guides you through each necessary steps
2. re-arranged the checkmarks and visual empty ones on non-finished steps
3. highlighting a next suggested step

**Mid-through progress view**
![zitadel-onboarding02b](https://user-images.githubusercontent.com/48990649/215735392-2a2827ac-8d0d-47e1-b4d7-9c23176bc28b.png)
4. fading out, strike-through and re-arranged to the end of the list steps that have been done.


**Completed Progress View**
![zitadel-onboarding02c](https://user-images.githubusercontent.com/48990649/215735394-5d9889b7-54ba-4900-872a-db110e08e3f4.png)
With this view, the cards can act as shortcuts for further navigation (and it makes it faster as well) even after the setup progress is completed.

**Comment by juergrinaldi** [comment]
WIP: List view (as suggested) and inputs from Dakshitha.
(lunch break :-P )

**Comment by hifabienne** [comment]
Yes this is exactly what I had in my mind. I think it is ok to have it different as soon as I have completed (or say that I want to skip it)
My goal is to get them as fast as possible to the first meaningful action (login to my own application), and I do have to follow the steps, create project create application, login for that.
And after that I think it is good to show them some other tasks to be completed, so to guid them through ZITADEL

**Comment by hifabienne** [comment]
@juergrinaldi Is it clear what we want to implement in a first step? Can you maybe remove the other screenshots so it is not confusing? And add acceptance criteria maybe with the link to the designs that should be implemented?

**Comment by juergrinaldi** [comment]
I've made a new issue that is streamlined here: #5213

**Comment by hifabienne** [comment]
I will close this as we have a new issue for what we want to implement
