### ISSUE TITLE
Define new API Documentation

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#4839]
To showcase the functionality of the API's, a dedicated documenation application should be created.
This application will be built with NextJS and provide a server rendered page with the possibility to hydrate content with user relevant information. This page should show all available requests and responses of the API's (Auth, Management, Admin) and showcase them with curl examples or dedicated code snippets.
The MVP can be broken down to the following points:

Content:
- [ ] Use [Markdoc] as authoring framework for content
- [ ] Use [React Flow](https://reactflow.dev/) in combination with Markdoc for process descriptions
- [ ] Provide general information about how authentication works 
- [ ] Show core resources as a collection of all available ZITADEL objects/entities.
- [ ] Provide information about errors and debugging methods
- [ ] Provide information about pagination works within ZITADEL API's
- [ ] GRPC and REST resources (STUB generation for different technologies, Insomnia, Postman or other client request collection, swagger.json)
- [ ] Authentication Service
- [ ] Management Service
- [ ] Admin Service
- [ ] OIDC Documentation
- [ ] Add OIDC Playground
- [ ] SAML Documentation

Deployment:
- [ ] replace the actual docs path `/docs/api` with the new application

Cleanup
- [ ] Remove the current generated markdown

At a later stage, users should be able to log in and set a context on which the examples will be based. The context will then be shown in the header/nav. ZITADEL's Console will provide links to the API Docs from the object/entity pages or directly trigger a integration with [Vercel](https://vercel.com) where the environment will be created from scratch or used from an already existing project.

**Comment by hifabienne** [comment]
https://github.com/zitadel/zitadel/pull/5158
