### ISSUE TITLE
Login name casing

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4840]
As an end user I want to enter my loginname no matter which if upper or lower case, because with copy paste or auto fill it is not always the way I have created the user, to be able to always login.

**Acceptance Criteria**
- [x] I am able to login to ZITADEL no matter of upper or lower letters if the loginname is correct
- [x] I am able to login with my email (if this is allowed on my organization) if I have the wrong upper/lower cases

### Discussed in https://github.com/zitadel/zitadel/discussions/4732

<div type='discussions-op-text'>

<sup>Originally posted by **DavideWalder** November 21, 2022</sup>
A major complaint from our users is the case sensitive login. The local part of email addresses is case sensitive, but it is recommended not to treat it as such (to avoid having two users `john.doe` and `John.Doe` which might be able to access each others resources). The main issue is that when a user enters its login name with a different case, it is rejected (the same happens for external IDP users, even though the external IDP recognises them).

Proposition: make login names case insensitive (preventing the creation of duplicates)</div>

**Comment by fforootd** [comment]
Related OWASP recommendation:


> [User IDs](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#user-ids)
> Make sure your usernames/user IDs are case-insensitive. User 'smith' and user 'Smith' should be the same user. Usernames should also be unique. For high-security applications, usernames could be assigned and secret instead of user-defined public data.
> 
> [Email address as a User ID](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#email-address-as-a-user-id)
> For information on validating email addresses, please visit the [input validation cheatsheet email discussion](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html#email-address-validation).

**Comment by svenbeck27** [comment]
@hifabienne 
We get a lot of support cases for "reset password" where the user is also not found due to case-sensitivity.
Do you already have an idea when you plan to work on this?

**Comment by hifabienne** [comment]
@svenbeck27 This is actually planed in the current sprint that started this week. So should be done in the next two weeks.
