### ISSUE TITLE
Reuse current session if no prompt is selected

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4841]
As an end user I want to switch between applications and be logged in right away without choosing my account again, so I don't have to select the same user all the time.

**Acceptance Criteria**
- [ ] If I have an open session in app 1 and switch to app 2 I want to be directly in the app without seeing the login
- [ ] If the applications sends the "select_account" prompt, I want to see the select account page of the login, so I have to select my acount again before seeing the app 2

## Discussed in https://github.com/zitadel/zitadel/discussions/4636

<div type='discussions-op-text'>

<sup>Originally posted by **helmut72** October 29, 2022</sup>
Is there an option to enable auto redirect back to the app if an user is logged on in Zitadel?

For trying out Zitadel it's great to choose one my test users or the admin user. From work (Azure) and also from home with Keycloak or Authelia I'm used to be auto redirect back into the app when I'm logged on. IMHO it's unnecessary or do I oversee anything?

Thank you.</div>

**Comment by mffap** [comment]
Also had a similar topic today. User has two applications, one from a third party with SAML and an own web app based on OIDC.

Given a user has an active session already,
when the user logs into the third party appication via SSO,
then zitadel should not use the account picker or login prompt, but reuse the existing session,
and then redirect to the app automatically

**Comment by mffap** [comment]
@hifabienne @livio-a is there a known workaround?
Received another question about this via support channel.

**Comment by hifabienne** [comment]
@mffap No currently there is no workaround.
The next sprint will be about bugfixes and smaller issue. But as we already have a lot, I am not sure if we can get this one in aswell

**Comment by yueyub** [comment]
what's the status?

**Comment by hifabienne** [comment]
We have not yet planned when we will implement it.

**Comment by hifabienne** [comment]
This results in a breaking behavior change. I will sort out how we can inform our customers before the changes.

**Comment by mffap** [comment]
Again requested in a discovery call.
