### ISSUE TITLE
Improve API docs

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4844]
## Description

Currently the proto files contains wrong links. Which affects the data quality of our generated docs.
As we are working on #4839 we honestly need to improve that ASAP.

**Acceptance criteria**
- [ ] Remove generated proto docs from current docs page (e.g. https://zitadel.com/docs/apis/proto/auth)
- [ ] Get the protos in tiptop shape
- [ ] Generated openapi cocs that we can use to link with  #4839 (we don't want to duplicate but instead reference)

**Comment by fforootd** [comment]
@hifabienne honestly this feel super important to me.

**Comment by fforootd** [comment]
To give some examples of outdated elements

- https://github.com/zitadel/zitadel/blob/main/proto/zitadel/admin.proto#L1127
- https://github.com/zitadel/zitadel/blob/main/proto/zitadel/admin.proto#L84
- https://github.com/zitadel/zitadel/blob/main/proto/zitadel/admin.proto#L622

**Comment by hifabienne** [comment]
Does it really make sense to include doc links in out proto definitions?

**Comment by fforootd** [comment]
Relates to #4864

**Comment by hifabienne** [comment]
@fforootd is this replaced with this issue: https://github.com/zitadel/zitadel/issues/4839

**Comment by fforootd** [comment]
Yes, I can ammend the bullets in that issue
