### ISSUE TITLE
Reduce mental overhead in deploy examples

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4892]
As a developer unfamiliar to ZITADEL, I want to run ZITADEL on my platform of choice without having to take care about the multitude of configuration options and eventualities that ZITADEL offers, so I have a comfortable starting point of my own ZITADEL instance I can build upon.

**Acceptance Criteria**
- [ ] I have docs pages that show me how to deploy ZITADEL on my platform with as few commands as possible and with as less ifs and elses to consider as possible.
- [ ] The docs also explain how I can maximize deployment automation by using the Machinekey config.

**Background**

The question is, how we should document the ZITADEL setup that creates a service account instead of an admin user. There was disagreement in #4877. We decided to merge what we have and open a follow-up issue for discussion.

My take on this:
We should remove the service account handling from the deploy pages and instead describe it in a dedicated page beneath self-hosted. 

The deploy examples should let users run ZITADEL with as little mental overhead as possible on the platform of their choice. Having the service account handling on these deploy pages could suggest it is complicated to deploy ZITADEL. To me it's not clear that users have a real benefit from these step-by-step guides for each platform, while the maintenance overhead on our side is obvious.
When it comes to bringing a ZITADEL setup to production readiness or automating things, there are problem-specific pages beneath self-hosted that are linkable from other pages.

## Suggestions DL;DR

The following list summarizes the measures proposed in this issues comments

1. #6430
2. Clarify that the initial admin is either a machine or a human user.
3. Describe how a human user can be created using a set up machine user.
4. Add an explicit (interactive?) option to the setup command to specify if the first admin should be a human or a machine.
5. Move the platform specific machine user setup guides to a single platform-agnostic docs page.
6. ~~Describe the XOR condition in the steps.yaml~~ done
7. Also document ZITADEL setup options in the Helm chart repo or add a link to docs.
8. Exporting a steps.yaml from a configured runtime to use as a snapshot for other deployments.
9. Add an automation step to the docker-compose example that ensures that both a human user and a machine user are set up 
10. ~~Document env variables~~ done 
11. Introduce the concept of subinstances

**Comment by eliobischof** [comment]
@stebenz can you describe your opinion, please?

**Comment by mffap** [comment]
Couple of notes from my side. 

Docker Compose example: 
- Please add a note similar as in the Kubernetes example: "With this configuration you only get a service account with a key and no user admin account that allows you to login to Console." (note: some smaller edits)
- Add a note which permissions the service user gets by default; Link to our [manager roles](https://zitadel.com/docs/guides/manage/console/managers#roles)
- State that this configuration is XOR, meaning either you can create a user or a service user, but not both (eg, by adding env variables)
- Explain the steps how an admin user can be created after using the service user init (ie. creating the user and assigning the Manager role); include a link to our [guide](https://zitadel.com/docs/guides/integrate/access-zitadel-apis)

Kubernetes example: 
- Wrong headline level? https://zitadel.com/docs/guides/deploy/kubernetes#install-an-insecure-zitadel-release-that-works-with-localhost-with-a-service-account
- Replace the "!!!Caution!!! With this setup you only get a service account with a key and no admin account where you can login directly into ZITADEL." by an [docusaurus admonition](https://docusaurus.io/docs/markdown-features/admonitions)
- Add the same information as above (in case we leave the strucutre)

**Comment by mffap** [comment]
On topic: I would also prefer to maybe have a separate section for this use-case. I see the danger that people get confused and are held back by the additional steps you have to do to create a user to login to Console. The Deployment docs should be a quick, standard way of getting zitadel up and running with an easy default config (ie: Login to Console is typically the first step).

**Comment by fforootd** [comment]
My 2 cents are:

- Lets create a page that outlines how a service user can be leveraged during instance creation for "non interactive" cases
- Lets run zitadel **per default** in an "interactive mode" where the user needs to setup access (an improvement over the current mode)

**Comment by stebenz** [comment]
@eliobischof yes, I'm with you, we should restructure the deploy part, and maybe hold deploy with the normal setup only with the admin user as before.
In addition how to change the setup as described in the other comments, to show what additional value a setup only with a service account can give you, maybe with a full-blown example in combination with Terraform? To show how you can for example manage an automated dev environment?

**Comment by eliobischof** [comment]
> @eliobischof yes, I'm with you, we should restructure the deploy part, and maybe hold deploy with the normal setup only with the admin user as before. In addition how to change the setup as described in the other comments, to show what additional value a setup only with a service account can give you, maybe with a full-blown example in combination with Terraform? To show how you can for example manage an automated dev environment?

Yes, but I would keep it simple there. I think a link from the Terraform page to the new machine key page that describes the handling in detail would do. Also, maybe we should add a link from the Helm chart readme to the Terraform page and the new machine key page for further automation steps?

**Comment by fforootd** [comment]
Please be aware of the change i am going to propose with https://github.com/zitadel/zitadel/pull/4903

All inputs welcome for this :-)

Preview https://deploy-preview-4903--docs-zitadel-com.netlify.app/docs/

![image](https://user-images.githubusercontent.com/9879976/208423645-f7315dba-37ef-4138-97e7-8fa3e2754c20.png)

**Comment by mffap** [comment]
@stebenz We should also provide a proper description / comments in this file: 
https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/setup/steps.yaml#L26

I think that's the only doc we have at the moment for generated variables.

**Comment by fforootd** [comment]
In addition to that a question @stebenz is it correct that human and machine are in an XOR behaviour?

IMO it should be and / or to give freedom of choice

**Comment by stebenz** [comment]
@mffap Shouldn't we better have a full description on the contents of this file? Part is described in the zitadel-chart under [https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml) but am I right that there is not setup documentation as of now?

@fforootd yes, currently you can only create an instance with either a machine user or a human user, which was the result of the current logic with only one owner at the moment of creation. To do this we would have to refactor a part of the logic, should I create an issue for that?

@eliobischof I see that this issue is assigned to me, but also the documentation was already moved to a separate page under [https://zitadel.com/docs/self-hosting/deploy/overview](https://zitadel.com/docs/self-hosting/deploy/overview), does this mean we can close this issue?

**Comment by eliobischof** [comment]
> @eliobischof I see that this issue is assigned to me, but also the documentation was already moved to a separate page under [https://zitadel.com/docs/self-hosting/deploy/overview](https://zitadel.com/docs/self-hosting/deploy/overview), does this mean we can close this issue?

Why should it mean we can close the issue?

**Comment by hifabienne** [comment]
Do we have an outcome on what we want to change? If yes can someone write a user story with the acceptance criteria?

**Comment by fforootd** [comment]
I want to change this > https://github.com/zitadel/zitadel/issues/4892#issuecomment-1369973118

**Comment by eliobischof** [comment]
> I want to change this > https://github.com/zitadel/zitadel/issues/4892#issuecomment-1369973118

Let's create a dedicated issue for this.

**Comment by kostargmailcom** [comment]
We tried automating initial setup of Zitadel using docker compose, we  encountered several issues.
1. We had to go through your code and figure out that in docker compose the names of the env vars are supposed to be comprised with _ from yaml structure from defaults.yaml
2. Why can't I have both ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME and ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME? It only creates a machine user and doesn't create the human user?
3. It would be nice to be able to configure zitadel manually then export configuration and use it as part of automation by importing it.
Amazing project, good job guys

**Comment by mffap** [comment]
@eliobischof @stebenz could we provide both a human user and service user with IAM Owner rights when docker compose up? This might be very useful to get started, since we could provide instructions on how to setup certain things via API as well.

Also can we please just add the main ENV variables to the docs? They will probably not change too often. Let's prioritize having good docs on the most important ones.

**Comment by tothandras** [comment]
@kostargmailcom Have you managed to figure out a solution for 2. since?

**Comment by ramizpolic** [comment]
@kostargmailcom I agree, Zitadel has way too much (loosely organized) documentation about deployment and management. To overcome this issue, I have used the following approach:
- Production example of docker compose deployment (I am sure other examples are equally good, but docker compose provided the fastest way to start)
- Terraform for bootstrapping and configuration (easy to manage the zitadel resource)

**Comment by fforootd** [comment]
@peintnermax and I recently were just thinking if a hierarchal model would make sense.

We actually think this would ease up some pain since one could run one instance and then inside zitadel create sub instances.
With this zitadel could accept all connections and we would get rid of the "Instance not found" problem as well as a user/service account could easily manage sub instances.

And yes we certainly can improve the docs around our tenancy ideas for the sake of other struggling through here we describe [instances](https://zitadel.com/docs/concepts/structure/instance) and [organizations](https://zitadel.com/docs/concepts/structure/organizations) 

Today:
All instance run besides each other.

Possible future:
One root instance could be the parent to (n) child instances

**Comment by hifabienne** [comment]
As this issue has a lot of comments it is hard to know what has to be done.
I have created an issue for the create instance with service user and human user part: https://github.com/zitadel/zitadel/issues/6430

Do I have to create something else? Otherwise I would clous the issue here.
