### ISSUE TITLE
[Bug]: Not able to connect Yahoo because of ES256

### ISSUE THREAD

**Issue by CMiksche** [zitadel/zitadel#4899]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I want to connect Yahoo as a OpenID Connect Provider to my Zitadel Instance.

Yahoo itself describes that "ES256" and "RS256" is supported.

But when I try to connect as a User after setting up a App at Yahoo, I get the following:

`signature algorithm not supported: id token signed with unsupported algorithm, expected ["RS256"] got "ES256"`

### To reproduce

1. Follow https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html to setup a App at Yahoo
2. Try to login with Zitadel
3. You will see the Error Message

### Version

2.16.0

**Comment by fforootd** [comment]
Hm good question.

There [discover document](https://api.login.yahoo.com/.well-known/openid-configuration) clearly shows RSA Support.

With a quick glance i did not see how to switch this 🙈 

Maybe @livio-a has an idea.

Relates to #4431

**Comment by CMiksche** [comment]
Some OpenID Connect Providers like netID allow the selection in the application creation interface but I couldn't find anything there at Yahoo...

I send them (Yahoo) a Mail about it - lets see if they respond.

But couldn't Zitadel also support ES256? It seems like many Providers use ES256 as default (e.g. netID also uses ES256 besides RS256)

BTW: Off-topic but when a OpenID Connect Provider only allows one Callback URL, which one should I use - the Zitadel Register or Login Callback URL?

**Comment by hifabienne** [comment]
Hi @CMiksche 
At the moment our OIDC library does only support RS256.
I just created an issue for it: https://github.com/zitadel/oidc/issues/259
But I can't tell you a timeline on that right now.

**Comment by livio-a** [comment]
@hifabienne  i rechecked the implementation. It's already possible to handle token signatures other than RS256, but it's currently not that dynamic as needed. I'll add some info the oidc issue. Regardless of that, ZITADEL only need to update the library afterwards.

**Comment by hifabienne** [comment]
So I will close this issue since we track the progress in https://github.com/zitadel/oidc/issues/259
