### ISSUE TITLE
Search Events

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4906]
As an administrator I want to be able to query all events of an instance with the filters mentioned below, to be able to see the change track of my resources

**Acceptance criteria**
- [x] I want to make a search for events with the defined filters, pagination returning the event data
- [x] I want to be able to set a limit on my request
- [x] I want to be able to filter the following
       - Editor User ID
       - Event Types
       - Aggregate ID
       - Aggregate Type
       - Resource Owner id
       - Sequence
       - Creation Date
- [ ] ~~I can filter the event type on sub "parts" like users.human~~
- [x] I want to be able to get the following data from an event 
       - EditorUser (Object not only id)
       - Editor Service 
       - Event Type
       - Aggregate ID
       - Aggregate Type
       - Resource Owner
       - Sequence 
       - Creation Date
       - Data
- [x] I want to search for all aggregates to be able to filter by them
- [x] I want to be able to get the event types to filter by them
- [x] Users with the permission events.read should be allowed to request it
- [x] IAM_OWNER is allowed to filter this events

**Comment by adlerhurst** [comment]
@hifabienne is the instance id required in the response? because it's always the same id

**Comment by hifabienne** [comment]
> @hifabienne is the instance id required in the response? because it's always the same id
 You are right, I think we don't need it

**Comment by adlerhurst** [comment]
as discussed with @hifabienne we start without prefix filters for event types

**Comment by hifabienne** [comment]
> as discussed with @hifabienne we start without prefix filters for event types
Just to clarify, we need some kind of prefix filters. From my perspective it doesn't matter if we implement it in the backend or in the frontend.
This means it has to be implemented by the frontend

**Comment by adlerhurst** [comment]
@hifabienne I added the permission "events.read" to `IAM_OWNER` and `IAM_OWNER_VIEWER`

**Comment by hifabienne** [comment]
Currently is only possible to search by aggregate ID
It should be possible to search over all events
