### ISSUE TITLE
Action Possibility on Local Users

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4908]
As a developer I want to extend the workflow for local users that authenticate in ZITADEL so I am able to extend my register and login flow for my custom needs.

**Acceptance criteria**
- [x] I want to be able to add an action on local authentication
- [x] I want to be able to trigger the action Post Authentication
- [x] I want to be able to trigger the action Pre Creation
- [x] I want to be able to trigger the action  Post Creation
- [x] I want to be able to create the same actions as we have on external authentication

**Comment by adlerhurst** [comment]
@adlerhurst TODOS:

* [ ] add example 
* [ ] docs
