### ISSUE TITLE
Log logins to stdout

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4909]
As an administrator/developer I want to be able to see who (user) did when (timestamp) login (successful/failed) in which context (application, oidc scopes, oidc claims) and metadata (ip).

**Acceptance criteria**
- [x] I can see a log "successfull login" log when a user has logged in
- [x] I can see a log "authentication failed" when a user could not logg in.
- [x] I can create an action post authentication where I log the following informaiton to stdout: authenticated user, timestamp, successful login, app/client, request metadata (e.g ip)
- [x] I can create an action pre authentication where I log the following informaiton to stdout: authenticated user, timestamp, "authentication started", app/client, request metadata (e.g ip)
- [x] I want to be able to access request metadata and claims from the action
- [x] I want to be able to copy an example action from the actions marketplace (zitadel/actions)
- [x] I want to be able to see the end users IP

Depends on #4908

**Comment by hifabienne** [comment]
With @fforootd and @eliobischof we have decided to implement this possiblity as action

**Comment by eliobischof** [comment]
@hifabienne I think we don't need a pre authentication trigger as we have authentication errors in post authentication.

**Comment by mffap** [comment]
+1 custom claims requirement

**Comment by mffap** [comment]
Example for custom claims: 
https://github.com/zitadel/actions/blob/main/examples/add_claim.js
