### ISSUE TITLE
Log Category

### ISSUE THREAD

**Issue by thesephirot** [zitadel/zitadel#4913]
As an Administrator I want to be able to filter ZITADEL logs by their severity such as "Info", "Warning", "Error", "Notice" to be able to find errors and warnings quicker by their category.

At the moment the log entries do contain the strings "info/warning/error", but the json format needs to be amended that the severity class is recognized correct by monitoring tools instead of a string filter.

**Acceptance criteria**

- [ ] I want to be able to filter logs based on their severity 
- [ ] I do want to filter log entries such as "warning" and "error" specificaly

**Comment by hifabienne** [comment]
We have coresponding issues for the specific things we want to implement so will close the issue here.
