### ISSUE TITLE
Docs: Metadata must be base64 encoded

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4918]
When setting metadata the value must be base64 encoded. We describe in a couple of places that the values are encoded when pulling data, but it's nowhere mentioned that the data must be encoded when setting metadata on a user or organization. The encoding is a bit unexpected and it's easy to miss it.

**Acceptance criteria**
- [ ] Document the encoding on our API docs

**Context**
https://discord.com/channels/927474939156643850/1053234838859169902/1054722672505929768

**Comment by hifabienne** [comment]
In included that in the new API docs

**Comment by hifabienne** [comment]
I will close this, as we have included it in the new api documentation
