### ISSUE TITLE
Show possible identifications on user detail

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4929]
As an admin or end user I want to see which possibilities I have to login (username, email, phone) in the console.

**Acceptance criteria**
- [x] I can see the possible loginnames on the user detail
- [x] I can see the possible loginnames on my user profile page
- [x] The possible logginnames are based on the login policy of my organization
- [x] If the email login is enabled on the login policy, I see the email as additional login possiblity on the user page
- [x] If the email login is disabled on the login policy, I don't see the email as additional login possiblity on the user page
- [x] If the phone login is enabled on the login policy, I see the phone as additional login possiblity on the user page
- [x] If the email login is disabled on the login policy, I don't see the phone as additional login possiblity on the user page

based on #4928

**Comment by fforootd** [comment]
@fforootd will think about a better term for "loginnames"

**Comment by peintnermax** [comment]
@fforootd Renamed the label to `Login methods`. Visuals and translations are in the linked PR.

**Comment by hifabienne** [comment]
Currently it does show not verified email and phone as login method this should not be shown because you cant login with it
