### ISSUE TITLE
Long organisation domains break ui

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4951]
As an end user I want to see the the domain of my organisation if I register.

**Acceptance criteria**
- [ ] The domain is only shown if I have enabled the setting "username must contain domain"
- [ ] I can see the whole domain on registration even if it is really long
- [ ] The domain does not overflow on the input field
- [ ] Implement according to solution 3
- [ ] I have a label that shows me that it is my actual username: "your username"
- [ ] I have a copy to clipboard "button"
- [ ] My complete username is shown in the following color: #3FCABA

![image](https://user-images.githubusercontent.com/48990649/210538536-94c63625-568d-4c50-96e0-fa152e9d7999.png)

**Additional Context**
Mentioned in #4706 
![image](https://user-images.githubusercontent.com/18188015/202132413-41ada889-7bf3-4f08-b446-5449eb1e50f9.png)

**Comment by MostlyGenius** [comment]
Can you assign me this task?

**Comment by juergrinaldi** [comment]
First of all: I highly recommend to get rid of the suffix completely and/or encourage our customers to do so as well. As this is least confusing for most users as it common to use a single username (without suffix) or their email address.


![suffix-handling01](https://user-images.githubusercontent.com/48990649/210524169-6e71eecf-d7bb-42a8-a162-85daf68c6091.png)

1. Solution: make the whole username (incl. suffix) scaleable when necessary. This ensures that the whole username is readable (in one line) and it least effects most users (with reasonable short usernames/suffixes).
Another (cheaper) approach would be to just don't truncate the text and make the field "scrollable" (aka the user can still see and select the whole name by dragging right), allthough this might not be very intuitive.

![suffix-handling02](https://user-images.githubusercontent.com/48990649/210524171-18a66a54-3bc8-4f77-b942-b2038fef0884.png)

2. Scale the suffix text down (in the example it is 12px, adjust accordingly to rem/em), make a smaller line height and let it break if needed. Also let the input field scale vertically if needed. Ideally it will break at .zitadel.cloud first, to improve readability but be aware that this is still very hard to read.

![suffix-handling03](https://user-images.githubusercontent.com/48990649/210524176-61101844-44a9-4738-a9d4-ef2cd1b59d3f.png)

3. another cheaper solution: here i disconnected the username from the suffix in the input and show the whole username below the field. note that it might get overlooked by the user.

Note that these solutions still have its limits, but it should cover all reasonable long username/suffixes in one or another way.

My recommendation would be Solution 1.

**Comment by hifabienne** [comment]
> Can you assign me this task?

Yes. It would be great if you implement this. @juergrinaldi just added a screen design and we decided for solution 1, so including it into the input box but just with a smaller font so we can have 3 lines of the domain.

Since we now have changed the default of new instances to not using the domains completally we hope that most customers do not need them.

**Comment by juergrinaldi** [comment]
as discussed with @peintnermax we decided to go with variant 3. first and formost to not add unnecessarry JavaScript (bloating/security related) and to keep it as simple as possible, as this should only be a temporary problem (keeping in mind to get rid of the suffix eventually).

I updated the mockup (see below) with some additions:
- added a "label" to explain the user that this is his actual username
- added an accent color (#3FCABA) to counter the 'overlooking problem' and highlight it
- added a 'copy to clipboard' icon for easy access/use

2 notes:
a) make the font size approx. the same as other hints on forms or labels (around 12px)
b) if the username is still to long for 100% content width, make sure to have it break, so it's still be readable for the user.

![image](https://user-images.githubusercontent.com/48990649/210538536-94c63625-568d-4c50-96e0-fa152e9d7999.png)

**Comment by thepaperpilot** [comment]
I see this issue got de-prioritized. I happen to have a domain name that's just _slightly_ too long and gets truncated, even though I've made the organization not have a suffix (I made it use the "root" domain). Quite literally bumping the CSS max-width rule to 160px fixes it for me. As a stop-gap solution, could the default max-width be bumped up slightly?

**Comment by peintnermax** [comment]
> I see this issue got de-prioritized. I happen to have a domain name that's just _slightly_ too long and gets truncated, even though I've made the organization not have a suffix (I made it use the "root" domain). Quite literally bumping the CSS max-width rule to 160px fixes it for me. As a stop-gap solution, could the default max-width be bumped up slightly?

yeah sure. Could you provide a PR which improves it for you so we will look at it? Thank you 👍

**Comment by thepaperpilot** [comment]
@peintnermax PR submitted: #6590
