### ISSUE TITLE
[Bug]: can't create database schema for postgres

### ISSUE THREAD

**Issue by Gibheer** [zitadel/zitadel#4961]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Zitadel expects to be handed to postgres credentials to the database, which I am not willing to do.

So I tried to do the same with an admin user zitadel_admin which I granted access only to the zitadel database.
This failed because the setup/init doesn't expect the admin user to be confined to a specific database (see https://github.com/zitadel/zitadel/blob/main/internal/database/postgres/config.go#L142-L144).

Next I tried running the SQL statements myself as the admin user. There are a multitude of SQL scripts in the code base, for example in https://github.com/zitadel/zitadel/tree/main/cmd/initialise/sql and https://github.com/zitadel/zitadel/tree/main/cmd/setup
From the documentation it is not clear when what needs to run.

After I created all the tables, fixed all permissions Zitadel at least starts, but returns a lot of errors about not null constraints violated.

```
WARN[0000] unable to push first schedule succeeded       caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:266" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: null value in column \"resource_owner\" of relation \"events\" violates not-null constraint (SQLSTATE 23502))" projection=projections.idp_login_policy_links4           
INFO[0000] query failed                                  aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:141" error="ERROR: null value in column \"resource_owner\" of relation \"events\" violates not-null constraint (SQLSTATE 23502)" eventType=system.projections.scheduler.succeeded instanceID=
INFO[0000] query failed                                  aggregate=system aggregateId=SYSTEM aggregateType=system caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:141" error="ERROR: null value in column \"resource_owner\" of relation \"events\" violates not-null constraint (SQLSTATE 23502)" eventType=system.projections.scheduler.succeeded instanceID=
WARN[0000] unable to push first schedule succeeded       caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:266" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: null value in column \"resource_owner\" of relation \"events\" violates not-null constraint (SQLSTATE 23502))" projection=projections.instance_domains
WARN[0000] unable to push first schedule succeeded       caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:266" error="ID=SQL-SBP37 Message=unable to create event Parent=(ERROR: null value in column \"resource_owner\" of relation \"events\" violates not-null constraint (SQLSTATE 23502))" projection=projections.notifications
```

As it is it doesn't look like PostgreSQL support is working or in sync with the rest of the code base.

What would be nice is to get all necessary SQL statements printed to the console so that I can run them in the target database myself or at the least don't expect me to hand over superuser permissions.

### To reproduce

in Postgres:

```
create database zitadel;
create role zitadel_admin login;
create role zitadel login;
grant connect,create on database zitadel to zitadel_admin;
grant connect on database zitadel to zitadel;
```

prepare configuration /etc/zitadel/zitadel.yaml
```
Database:
  postgres:
    Host: localhost
    Port: 5432
    Database: zitadel
    DB: zitadel
    User:
      Username: zitadel
      Password: ""
      SSL:
        Mode: disable
    Admin:
      Username: zitadel_admin
      Password: ""
      SSL:
        Mode: disable
```

run setup
```
zitadel init database --config /etc/zitadel/zitadel.yaml
zitadel init zitadel --config /etc/zitadel/zitadel.yaml
```

### Version

2.17

### Operating System

OS: Archlinux
PostgreSQL: 14.6

### Relevant Configuration

```
Database:
  postgres:
    Host: localhost
    Port: 5432
    Database: zitadel
    DB: zitadel
    User:
      Username: zitadel
      Password: ""
      SSL:
        Mode: disable
    Admin:
      Username: zitadel_admin
      Password: ""
      SSL:
        Mode: disable
```

**Comment by adlerhurst** [comment]
Hi @Gibheer 

The admin user of postgres is used for the following statements:

- create the zitadel user
- create the zitadel database
- grant all of the zitadel database to the zitadel user

If you have created the user, db and grant manually, you should be able to run the following commands to setup and start zitadel without an admin user:

1. `zitadel init zitadel` this command creates the required tables and schemas inside the zitadel database
2. `zitadel start-from-setup` this command sets up initial data and afterwards starts zitadel

You executed `zitadel init database` as well, this command tries to create the database using the configured global admin user.

The statements executed during init can be found here: https://github.com/zitadel/zitadel/tree/main/cmd/initialise/sql/postgres
The 3 first files are executed using the database.admin afterwards database.user is used

**Comment by Gibheer** [comment]
Ah, thank you very much.
I gave the zitadel user the create permission on the database and after an init and setup run things started working.

Would you like to have a pull request for the [postgres documentation])https://github.com/zitadel/zitadel/blob/main/docs/docs/self-hosting/manage/database/_postgres.mdx).
That way one might not need to use the admin configuration at all.

**Comment by Gibheer** [comment]
Okay. Then I will work on a PR tomorrow :)

**Comment by hifabienne** [comment]
I will close this issue as the problem has been solved. Please open a new issue for other requirements.
