### ISSUE TITLE
Finish Quotas Feature

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4973]
As a system api user, I want to be able to configure quotas so that usage can be blocked and actions on certain thresholds are sent.

```[tasklist]
### Acceptance criteria
- [x] Quota notifications are end-to-end tested.
- [ ] Action seconds limitation is end-to-end-tested
- [x] Quotas have their own aggregate type (moved away from instance aggregate)
- [x] Reporting usage just depends on write models, not read models
- [ ] #4779 is merged
- [ ] Specifications: https://github.com/zitadel/zitadel/issues/4508
- [ ] Specifications: https://github.com/zitadel/zitadel/issues/4509
```

```[tasklist]
### Follow-up
- [ ] #5171
- [ ] #4424 
- [ ] https://github.com/zitadel/zitadel/issues/5030
- [ ] #5167
```

**Comment by eliobischof** [comment]
@hifabienne let's create a follow-up issue for the e2e tests for action seconds?
We will have less sunk work if we add e2e tests for actions as a whole in the first place.
The test code is already written but not meged yet. I will discuss how to go forward with it next week with @adlerhurst @livio-a and @stebenz.

**Comment by hifabienne** [comment]
> @hifabienne let's create a follow-up issue for the e2e tests for action seconds? We will have less sunk work if we add e2e tests for actions as a whole in the first place. The test code is already written but not meged yet. I will discuss how to go forward with it next week with @adlerhurst @livio-a and @stebenz.

Sounds good to me
