### ISSUE TITLE
Docs: Configuration options vs environment variables

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4976]
As Dev I want to understand how to configure zitadel for testing/dev and production.

Background: 
I was not able to fully understand how our system can be configured via code/variables for a dev and prod scenario, based on our documentation.

Observations:
 - [Docker compose](https://zitadel.com/docs/self-hosting/deploy/compose) uses env variables
 - [LB example](https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example) uses config files
- Both options are explained in the [Configuration Options](https://zitadel.com/docs/self-hosting/manage/configure) page
- The actual config parameters are in [here](https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml) and [here](https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml)
- Some relevant configuration parameters are missing a comment (eg, machine user vs. human user)
- Environment variables are not searchable in the docs, since we only point at the config files and explain how the variable names can be deduced from yaml files
- [Production Checklist](https://zitadel.com/docs/self-hosting/manage/production) makes no recommendation for envs vs config files

Proposal (to be discussed)
- Consistently use config with envs in the basic deploy examples
- Provide most important variables (see below) in the Configuration Options as list (and link to the files for full reference)
- Environment variables and their behavior should be described in more detail (variable name | mandatory (yes/no) | comments | defaults to)
- Reference the basic env variables from the deploy examples, such that people understand more easily how to change default values, as immediate next step (eg, password for admin)
- Make clear why our recommendation is config files in most cases (input from @fforootd about leaking values etc.)

Variables (incomplete, to be discussed)

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L21

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L24

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L29

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L56

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L57

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L58

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L65

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/setup/steps.yaml#L24

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/setup/steps.yaml#L11

**Acceptance criteria**
- [ ] ...
- [ ] ...

**Comment by mffap** [comment]
@eliobischof regarding my question how to properly configure zitadel. It is actually in the docs, but could be improved to make it easier for first time users. Please see above for a suggestion.

**Comment by mffap** [comment]
@fforootd you also got some questions around different variables, I guess. I think I got some of the important ones, please feel free to edit the list above with additional ones that seem most relevant.

**Comment by eliobischof** [comment]
> Environment variables are not searchable in the docs, since we only point at the config files and explain how the variable names can be deduced from yaml files

> Provide most important variables (see below) in the Configuration Options as list (and link to the files for full reference)
> Environment variables and their behavior should be described in more detail (variable name | mandatory (yes/no) | comments | defaults to)
> Reference the basic env variables from the deploy examples, such that people understand more easily how to change default values, as immediate next step (eg, password for admin)

To improve the understanding of config options, I'd suggest the following:

To keep maintenance in one place for guaranteed consistency over time -> source of truth for possible values, docs and defaults are in the yaml files beneith /cmd. To make the config options searchable, we could search a tool or mdx plugin to render a list in the docs context from the yaml files beneith /cmd.

For dependencies between configuration variables (aka specific use cases), we have pages for TLS Mode, Database and Custom Domain. They should be linked from list of config variables described above.

**Comment by mffap** [comment]
@eliobischof can you come up with an example how this could work? Else I would just do it manually for the start tbh. The variables outlined above will probably not change that often. I would prioritize the ability to search over consistency until it becomes a larger issue that needs to be addressed.

**Comment by doctor-eval** [comment]
If I might just add to this, I also find that the initial (steps?) vs config stuff to be really difficult to understand, and I agree that it's hard to find environment config docs. I am in the middle of configuring a new instance of Zitadel for the second time this year and I find it really quite frustrating and opaque, maybe it's because I use env exclusively. I do really like Zitadel but for whatever it's worth, I think this is the one key area that could be significantly improved. (Unfortunately right now I can't take any new projects on, or I might have offered to pitch in myself).

**Comment by mffap** [comment]
https://yaml.org/spec/1.2.2/#3233-comments

While trying to generate a md table for the variable names, values, and descriptions from the yaml files, I stumbled upon the issue that comments can't be associated with certain objects, as per Specification:
"In particular, comments are not associated with a particular node"

That makes parsing of comments into descriptions not viable. I will try to find an alternative solution (generate variables & values and have descriptions in the script but separate from the yaml comments), or we just have live with a static table and manual updates for now, until a better solution arises.

**Comment by mffap** [comment]
@hifabienne I've added a PR. Could you plan the review in for one of the next sprints, please?

**Comment by hifabienne** [comment]
Will close this issue, looks like it was merged with this: https://github.com/zitadel/zitadel/pull/6143

**Comment by mffap** [comment]
@hifabienne this follow up is open: https://github.com/zitadel/zitadel/pull/6336

at the moment you can't set arrays via env. that should allow it. ok, that this issue is closed, but the PR should be considered as part of the working solution
