### ISSUE TITLE
Remove Export Guide V1 to V2

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#4990]
With sunsetting of v1 completed, we should remove the guide on how to export from v1 to v2: https://zitadel.com/docs/guides/integrate/export-and-import

**Comment by hifabienne** [comment]
I would leave it for a moment in the docs. 
We may have self-hosting customers with V1 that want to migrate to V2

**Comment by mffap** [comment]
Sure, makes sense. Then as a reminder for later.
