### ISSUE TITLE
API: Login with Username Password

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5016]
As a developer, I want to be able to login my users with username password through an API ,so that I can build my custom login UI.

**Acceptance criteria**
- [x] I am able to authenticate a user with username password
- [x] Username password check
- [x] List Sessions
- [x] Teminate session
- [ ] Get session (either my session with the token or another session when I have permissions)
- [x]  I am able to send some key values on the session (for my own data)

**Additional Information**
Client should always be able to send that he has already checked something. e.g password checked instead of we check it

**Comment by hifabienne** [comment]
Inputs from customers:
- It should be possible to send some kind of metadata when authenticating
- It should be possible to make the biometric check outside of ZITADEL, and zitadel just states it in the token

**Comment by fforootd** [comment]
Verifying SMS and Email (aka Magic link) is also something we here.

**Comment by adlerhurst** [comment]
device authorization grant

**Comment by fforootd** [comment]
Also anonymous auth would be a thing.

I.e. we create a session for each visitor even if he did not yet setup an account.
