### ISSUE TITLE
Basic Implementation of Frontend which is using packages

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5018]
As a developer I want to include the basic components and apis from the sdk and implement the basic structure (e.g header, footer, ui componetns) for the login and register.

**Acceptance criteria**
- [x] I have a basic ui with the basic structur needed later on (e.g footer, header, etc)
- [x] The ui does use the typescript package for its components and api calls
- [x] Basic policies like branding taken into account
- [x] I am able to easily fork the login ui, to customise it for my needs

Depends on #5016

**Comment by peintnermax** [comment]
Implementation done with https://github.com/zitadel/typescript/pull/1

**Comment by eliobischof** [comment]
@peintnermax can you please link follow-up issues and then close this?

**Comment by peintnermax** [comment]
Follow ups https://github.com/zitadel/typescript/issues/4, https://github.com/zitadel/typescript/issues/3

**Comment by Davincible** [comment]
Fyi, links are broken

**Comment by peintnermax** [comment]
the repo is still private.. we'll publish it soon 👍
