### ISSUE TITLE
[Bug]: There is no comprehensive end-to-end example for Zitadel + PostgeSQL on Kubernetes

### ISSUE THREAD

**Issue by AndriyKalashnykov** [zitadel/zitadel#5025]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

There is no comprehensive end-to-end example for Zitadel + PostgeSQL on Kubernetes. It would be great to use Helm chart to deploy Zitadel pointing to PostgreSQL

### To reproduce

N/A

**Comment by doncicuto** [comment]
Hi @AndriyKalashnykov, I know this is an old issue, could the https://github.com/zitadel/zitadel-charts/tree/main/examples for postgres would be useful to you?

**Comment by AndriyKalashnykov** [comment]
> Hi @AndriyKalashnykov, I know this is an old issue, could the https://github.com/zitadel/zitadel-charts/tree/main/examples for postgres would be useful to you?

This is what I was looking for even though it was some time ago :)
Thanks! I can close the ticket now.
