### ISSUE TITLE
Improve error message and validation when creating new user

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5038]
As as Admin, I want get clear error messages when creating users so that I understand what changes are required.

**Acceptance criteria**
- [ ] Given I have a request with malformed userdata, When I submit the request, Then the error message returns information about the affected key/values and expected format, it should return a list
- [ ] Given I have a request with missing mandatory fields, When I submit the request, Then the error message returns information about the affected key
- [ ] (should) When I submit invalid userdata in Console, Then the UI highlights the fields and provides clear instructions how to resolve the invalid userdata

**Considerations**
- relates to: https://github.com/zitadel/zitadel/issues/4220
- Validation could also be done while typing based on expected format / settings

**Comment by eliobischof** [comment]
> it should return a list

@hifabienne we scoped this out from the first AC.
