### ISSUE TITLE
[Bug]: ID=QUERY-n0wng Message=Instance not found

### ISSUE THREAD

**Issue by SlimJUC** [zitadel/zitadel#5039]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

after starting zitadel using docker compose with default values
as stated in the documentation 

I get the following on browser

http://localhost:8080/ui/console
ID=QUERY-n0wng Message=Instance not found

### To reproduce

# Download the docker compose example configuration.
wget https://raw.githubusercontent.com/zitadel/zitadel/main/docs/docs/self-hosting/deploy/docker-compose.yaml

# Run the database and application containers.
docker compose up --detach

### Version

latest 

### Operating System

Ubuntu 20

**Comment by fforootd** [comment]
Hi There

I just tested this, and it is working with me like it should.

Can you provide with the log you see?

**Comment by hifabienne** [comment]
@SlimJUC Any updates on this issue? Can you provide the logs so we can help you? Without some more information it will be really hard to find out where the problem could be.

**Comment by aebling** [comment]
Definitely seeing the same issue. What/how logs do you want to see. I have deployed on 20.04 and 22.04 on AWS and VMware ubuntu instances running docker 20.10.23. Leveraging docker compose just as above.

**Comment by fforootd** [comment]
Do you run any kind of proxy in front of zitadel?

Because this error indicates that zitadel cannot map the domain name received in the host header.

Per default this is set to localhost, but it looks like that is not what is sent to the zitadel endpoint

**Comment by aebling** [comment]
Indeed, it was my issue. I needed to leverage my custom domain and tls. A few more tweaks of the compose and is working like a charm. I was trying to run on a remote instance and this default guide definitely refers to local install. I was causing my own issues.

**Comment by fforootd** [comment]
> Indeed, it was my issue. I needed to leverage my custom domain and tls. A few more tweaks of the compose and is working like a charm. I was trying to run on a remote instance and this default guide definitely refers to local install. I was causing my own issues.

Let me know if you need further assistance 😁

**Comment by hifabienne** [comment]
As it looks like this is resolved I will close the issue.

**Comment by ajvanegasv** [comment]
I get the same error, I am also using the docker compose configuration offered by the zitadel documentation but in my case the error appears when I want to generate the access token from another container, on my localhost the endpoint works perfectly

**Comment by fforootd** [comment]
> I get the same error, I am also using the docker compose configuration offered by the zitadel documentation but in my case the error appears when I want to generate the access token from another container, on my localhost the endpoint works perfectly

Usually this comes down to a proxy no passing along the http host header. We have some examples here https://zitadel.com/docs/self-hosting/manage/reverseproxy/reverse_proxy

**Comment by ajvanegasv** [comment]
> > I get the same error, I am also using the docker compose configuration offered by the zitadel documentation but in my case the error appears when I want to generate the access token from another container, on my localhost the endpoint works perfectly
> 
> Usually this comes down to a proxy no passing along the http host header. We have some examples here https://zitadel.com/docs/self-hosting/manage/reverseproxy/reverse_proxy

It is my first time trying to implement an identity provider to authenticate my applications, I have some doubts about the proxy configuration, should I configure the proxy in my applications or in the Zitadel container? I'm sorry if the question may seem somewhat absurd but I can't understand exactly where this configuration must be done (I ask it in case the configuration must be done where I have Zitadel hosted).

**Comment by leopku** [comment]
Same issue with and without proxy. 

  * zitadel was installed in remote server
  * docker compose file was direct from example without changed


1. access with proxy(caddy)

```shell
$ curl http://zitadel.nas.home/ui/login
ID=QUERY-n0wng Message=Instance not found
```

config of caddy

```
http://zitadel.nas.home {
  reverse_proxy h2c://10.0.1.232:8080
}
```

2. direct access without proxy

```shell
$ curl http://10.0.1.232:8080/ui/login
ID=QUERY-n0wng Message=Instance not found
```

Any advice?

**Comment by ovizii** [comment]
I'm running into the same issue. The comments here sound like you need to run zitadel on your current PC so you can access it via http://localhost:8080/ui/console

I'm running zitadel on my NAS so I am trying to access it via http://NAS-IP:8080/ui/console

No reverse proxy involved yet and its already failing.

**Comment by fforootd** [comment]
@leopku @ovizii you need to configure zitadel to allow you domainname of choice by setting the ExternalDomain.

More infos can be found here https://zitadel.com/docs/self-hosting/manage/custom-domain

**Comment by ovizii** [comment]
Thanks, I had just found that setting and I also saw that here: https://zitadel.com/docs/self-hosting/manage/configure 

it is mentioned:
![image](https://user-images.githubusercontent.com/837902/224000572-44c60ac3-0318-4921-afd2-508136b9de5a.png)

Maybe add a sentence there that with this setup you can only access zitadel if it's running on localhost? That would have saved some people including me some time :-)

**Comment by fforootd** [comment]
There is an ongoing effort on improving the UX of zitadel when managing it.

We just started discussing some changes here #5396 and here #5395

**Comment by jmls** [comment]
yeah, I've hit this issue on two occasions

1) running on gitpod - there is no localhost, and the url is random for every workspace that is started. Would be hard to try and develop in this scenario

2) running on localhost with the port mapping removed from the docker-compose 

I am going to try and see if I can map the ports in gitpod, but also make the host docker network available as "myhost" as an addtional network in the compose file. That may then work with port mapping

**Comment by leopku** [comment]
> @leopku @ovizii you need to configure zitadel to allow you domainname of choice by setting the ExternalDomain.
> 
> More infos can be found here https://zitadel.com/docs/self-hosting/manage/custom-domain

It works. Thanks a lot.

I came from [Docker compose deployment document](https://zitadel.com/docs/self-hosting/deploy/compose). Maybe it should be mentioned clearly at the document.
