### ISSUE TITLE
Confirmation for user deletion

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5042]
As a administrator I want to type a confirmation when deleting a user, so It doesn't happen by mistake. At the moment the confirmation differs depending on where I am and when I change the domain policy.

**Acceptance Criteria**
- [ ] Everywhere I can delete a user I need to confirm with an attribute from my user (username or login name)
- [ ] If its the loginname it should be the current login name no matter how the domain policy is set
- [ ] I need to confirm on my own user detail page
- [ ] I need to confirm on an other users page
- [ ] I need to confirm when deleteing in the list
 

**Additional Context**

Follow-up of #4982 

### Environment

ZITADEL Cloud

### Describe the bug

Sometimes, I have to confirm the user deletion with the org domain appendend, even when I want to delete a user that has no org domain suffix.

### To reproduce

Run e2e tests for machines or humans mutliple times with unskipped tests.

**Comment by hifabienne** [comment]
Did you try this for your own user? Or as an admin for another user?

**Comment by eliobischof** [comment]
The e2e tests use the default admin user for this. Probably it is caused by changing the domain policy back and forth.

BTW, I think we need an additional environment option "any" in the issue template.

**Comment by hifabienne** [comment]
I do not need to confirm anything, so thats why I am asking:
![image](https://user-images.githubusercontent.com/38692350/212684098-9bf96061-9703-48c6-9dca-37e25dc6b618.png)

**Comment by eliobischof** [comment]
Only on the list view, you have to confirm.
![image](https://user-images.githubusercontent.com/12727842/212710352-6d7a4911-f620-4fd1-924e-d6f3bc7148f8.png)
![image](https://user-images.githubusercontent.com/12727842/212710484-acc93fc9-78b2-4a0c-9e5d-808525ccf42d.png)

**Comment by hifabienne** [comment]
Ok thanks, I will rewrite the issue to it should always be the username, because its just a confirmation

**Comment by hifabienne** [comment]
@juergrinaldi What makes more sense from your perspective. enter the username or loginname? or something else

**Comment by juergrinaldi** [comment]
@hifabienne I'd just go with `'DELETE'` as usernames/loginnames can get pretty long and complicated. But I'd tell the admin **which** user they are about to delete.

But **IF** it needs to be more invasive/secure I'd go with user name.

**Comment by juergrinaldi** [comment]
btw: I wrote a lengthy explanation on this topic in a different issue here: https://github.com/zitadel/zitadel/issues/5107#issuecomment-1408113358

**Comment by hifabienne** [comment]
I have created a new issue accroding to this, because we want to change for typing "delete"
And this should not only apply for project, but also for orgs, users and apps.
Will close this therefore, please subscribe here: https://github.com/zitadel/zitadel/issues/5131
