### ISSUE TITLE
HTTP 1.1 Support

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#5054]
As an operator of ZITADEL I want to be able to run ZITADEL with HTTP1.1 only to ease up pain in certain cloud providers who do not support HTTP2. As operator I am aware that this prevent the usage of gRPC and because of that also prevents the usage of the official terrafom provider.

**Acceptance criteria**
- [ ] ZITADEL accepts HTTP1.1 on all non gRPC Services

**Additional Information**
Currently we force everyone to use HTTP2 when they are using tls. 
(h2c)

**Comment by fforootd** [comment]
If I remember correctly @livio-a mentioned once that he already had a fix for our http mux to allow plain http1.1 usage, right?

**Comment by hifabienne** [comment]
@fforootd Does it make sense to put this on hold, since we discuss the new apis anyways?

**Comment by fforootd** [comment]
Since we need to support the old APIs for some time I would be in favour of fixing this.

**Comment by livio-a** [comment]
> If I remember correctly @livio-a mentioned once that he already had a fix for our http mux to allow plain http1.1 usage, right?

yes i tried it some time ago and should have a fix. will need to test it again locally and on a dev system to be sure.

**Comment by livio-a** [comment]
@hifabienne we get requests / issues again and again regarding this. can we prioritise it into the next sprint or should i just take time in between to retest?

**Comment by hifabienne** [comment]
I would focus on the current sprint, if you finish earlier you can look into it. otherwise we can prioritise for the next sprint

**Comment by fforootd** [comment]
> I would focus on the current sprint, if you finish earlier you can look into it. otherwise we can prioritise for the next sprint

I would love to see this fixed since it would give users more flexibility in their deployment scenearios.

Relates to https://discord.com/channels/927474939156643850/1072014201561825401
