### ISSUE TITLE
[Bug]: Back button after creating a client app

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5069]
As an administrator I want to get to the project detail in the console when ever I click back from the application detail page.

## Acceptance Criteria
- [ ] I land on the project detail when clicking back (<--) on the application detail
- [ ] I land on the project detail when clicking back (<--) on the application detail when i just created the application

### Environment

ZITADEL Cloud

### Describe the bug

Inconsistent behavior on the back button when creating a new client application. After creating a new client and go on the back button the create app dialog starts again. However, editing the client and going back lands on the Project overview.

### To reproduce

Given I just created a client application (any type) on a project
When I click the back arrow
Then I get back to the create application dialog

Given I have already created an client application
When I go to my project and 
When I click on the application and
When I click the back button
Then I land on the project overview

### Screenshots

<img width="564" alt="Screenshot 2023-01-17 at 17 10 23" src="https://user-images.githubusercontent.com/1366906/212952438-c0c1135f-58b8-4b0c-9ba4-739fd51cb482.png">
<img width="600" alt="Screenshot 2023-01-17 at 17 10 32" src="https://user-images.githubusercontent.com/1366906/212952445-4304c7a7-9999-4dac-bdf2-6350aa4d2749.png">

### Expected behavior

 I think the behavior should be in both cases to land on the project overview.

**Comment by doncicuto** [comment]
@mffap this issue can be also seen if you create a new project (once you create a new one, back launches create project once again), a new user, etc. This is due to the BackDirective that always navigates back in history in the back arrow found in the detail-layout-component. I'll try to fix it.

**Comment by hifabienne** [comment]
@doncicuto Thank you.

**Comment by mffap** [comment]
> always

Nice :) Thank you
