### ISSUE TITLE
[Bug]: Main nav switches to wrong element

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5071]
As an administrator in the console I want to see highlighted in the navigation what I am currently editing, this is currently not working on the identity providers

## Acceptance Criteria
- [ ] When showing the idp table the settings menu is highlighted no matter if instance or organization level
- [ ] When I click on an idp and get to the detail, the settings menu is highlighted no matter if instance or organization level
- [ ] When adding a new idp and i get to the creation form, the settings menu is highlighted no matter if instance or organization level

### Environment
ZITADEL Cloud

### Describe the bug

When I set up an identity provider under `Settings` the main navigation highlights different elements through the process.

I start on `Settings` (which is also highlighted in the nav) and then click on `New` and with that the main navigation switches to `Organization` for some reason.

### To reproduce

1. Go to `Settings`
2. Go to `Identity Providers`
3. Click on `New`

### Screenshots

![image](https://user-images.githubusercontent.com/48990649/213088982-218cf5b8-dcc4-4878-9b1e-161dd5394048.png)

![image](https://user-images.githubusercontent.com/48990649/213089085-01e504ab-a911-48c3-a3d7-87a07fe0a668.png)

### Expected behavior

I expect to stay in the settings category through the whole process.

### Operating System

Windows/Mac
Chrome/Firefox

**Comment by hifabienne** [comment]
Will close the issue, as we are showing a message now that the view has changed, to not confuse the user
