### ISSUE TITLE
[Bug]: Can't debug "Invalid user data" error when registering from external IDP

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#5076]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When registering a new user through an external IDP (Azure in this case), I get the error in the screenshot below. This could be triggered for example by a missing required field (no email address or user name), but the only way to debug it is to look at source code or trial and error. Would it be possible to have a more informative error message?

### To reproduce

1. Add an external IDP and allow registering through that
2. Create a user in the external IDP without email address
3. Login with that user

### Screenshots

![Screenshot 2023-01-19 at 09 39 45](https://user-images.githubusercontent.com/58290976/213394371-6f7a5806-be12-4a64-9a4e-ab9dac9a94b5.png)

### Version

2.16.4

**Comment by hifabienne** [comment]
Hei @DavideWalder 
We have already an issue about this topic to send more meaningful error messages: #5038 
Would this be enough for you? In that case I would close this issue to avoid duplicates.

**Comment by DavideWalder** [comment]
> Hei @DavideWalder
> We have already an issue about this topic to send more meaningful error messages: #5038
> Would this be enough for you? In that case I would close this issue to avoid duplicates.

Sorry, didn't see that, feel free to close the issue
