### ISSUE TITLE
[Bug]: when requesting listMyProjectOrgs with a stateQuery, the request fails

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#5077]
As a developer/administrator I want to be able to filter listMyProjectOrgs with a stateQuery. At the moment this failes with response: code: 3, message: "List.Query.Invalid"

**Acceptance Criteria**
- [ ] I am able to filter List My Project Organizations per state

**Additional Context**
- The StateQuery is missing in the converter

**Comment by stebenz** [comment]
@peintnermax Just had a look at the code, seems this was solved with https://github.com/zitadel/zitadel/commit/2ec36bd63baf966d338a07ba17dbc3ac5a9fd689 right?

**Comment by adlerhurst** [comment]
looks good to me as well
