### ISSUE TITLE
[Bug]: Not able to fetch metadata added at Org level

### ISSUE THREAD

**Issue by ahmedsakri** [zitadel/zitadel#5098]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Not able to fetch/retrieve the metadata added at Organisation Level. Have added a screenshot below. 

For the metadata added at user level. I am able to retrieve it using `urn:zitadel:iam:user:metadata` scope. But, No scope is available to fetch at Org level.

<img width="1679" alt="Screenshot 2023-01-24 at 7 03 27 PM" src="https://user-images.githubusercontent.com/60789760/214308372-14adb0e5-2592-4ec8-a7e9-e872863fdc22.png">
the 

### To reproduce

Steps to reproduce the behaviour:

1. Add metadata to new or any existing organisation.
2. There's no way to access the metadata at org level.

### Screenshots

<img width="1679" alt="Screenshot 2023-01-24 at 7 03 27 PM" src="https://user-images.githubusercontent.com/60789760/214308740-5705dde8-48a1-4fe9-b170-920abef86763.png">

### Expected behavior

Should be able to fetch the Organization's metadata.

**Comment by fforootd** [comment]
This relates to https://github.com/zitadel/zitadel/issues/4419

I think currently only the mgmt api allows to access the org metadata, right @livio-a @hifabienne ?

**Comment by livio-a** [comment]
Yes as far as i remember you can only manage it using the Management API and Actions.
OAuth / OIDC based usage would require the implementation of the mentioned issue.

**Comment by hifabienne** [comment]
Yes. So in my opinion this splits into two different issues:
1. Be able to access the organization metadata in the console: https://github.com/zitadel/zitadel/issues/5099
2. Be able to access it with a scope in the token: https://github.com/zitadel/zitadel/issues/4419

@ahmedsakri as there are two issues releated to your topic, please subscribe to them. I will close this one to avoid duplicates. If you are missing something else please let us know
