### ISSUE TITLE
[Bug]: redirect to AzureAD not working correctly

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5106]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

I have azure configured and activated. When I try to login, I get prompted for a password, instead of redirect. When I enter the password, I get the message that method is not allowed. When I then click the "back" button, I get redirected to my AzureAD Tenant.

### To reproduce

I can reproduce the behavior (see screencast below) but not sure how I ended up in this spot.

### Screenshots

<img width="591" alt="Screenshot 2023-01-20 at 10 49 12 (1)" src="https://user-images.githubusercontent.com/1366906/214788301-5a04ddbb-9fe3-48eb-94fd-cec7b8a71f51.png">

https://user-images.githubusercontent.com/1366906/214788577-10e9b5fb-cc65-4a5e-8534-49453e6ff7d9.mp4

<img width="1059" alt="Screenshot 2023-01-26 at 09 22 37" src="https://user-images.githubusercontent.com/1366906/214788726-78b6ad3a-a5a5-40fd-94a1-607741cfc15c.png">

<img width="859" alt="Screenshot 2023-01-26 at 09 22 51" src="https://user-images.githubusercontent.com/1366906/214788731-c689b404-d09d-41cd-be77-34c4b21f48ba.png">

### Expected behavior

Redirect to AzureAD directly when the user is selected.

### Version

2.18.0

### Relevant Configuration

- AzureAD is configured and active as only IDP
- Username Password allowed is disabled
- External IDP allowed is enabled

HAR file provided in private message.

**Comment by mffap** [comment]
@livio-a clearing the cache does not solve the issue

**Comment by livio-a** [comment]
brain dump of the meeting we had:
1. user (only password set, no idp) is presented password check screen although org login policy does not allow password logins
2. when clicking "back", the user gets redirected to the idp 
    -> org was selected because of previous user selection, only idp allowed, single idp configured
4. after callback of the idp, there's an endless loop to the idp
    -> client secrets had expired, but error was not displayed in zitadel, might be because of a missing error handling in the autoredirect of (2)

**Comment by mffap** [comment]
> brain dump of the meeting we had:
> 
> 1. user (only password set, no idp) is presented password check screen although org login policy does not allow password logins
> 2. when clicking "back", the user gets redirected to the idp
>    -> org was selected because of previous user selection, only idp allowed, single idp configured
> 3. after callback of the idp, there's an endless loop to the idp
>    -> client secrets had expired, but error was not displayed in zitadel, might be because of a missing error handling in the autoredirect of (2)

Yes. Sounds about right. Thanks for looking into it.

**Comment by hifabienne** [comment]
@livio-a If I understand you right I can create a user story according to this that say errors of identity providers should be shown to the user?

**Comment by livio-a** [comment]
Yes and i think we should create another one for handling the case, where the user only has a password / passwordless login and local authentication has been disabled in the meantime.

**Comment by hifabienne** [comment]
We just decided to have a look that as soon as we have finished the idp templates. because some parts should probably be fixed already.

**Comment by mffap** [comment]
can this be tested again?

**Comment by muhlemmer** [comment]
Discussed with @livio-a, needs to be retested against a recent version to see if the bug still exists.
