### ISSUE TITLE
Wildcard return URL in developer mode 

### ISSUE THREAD

**Issue by buehler** [zitadel/zitadel#5110]
As a developer, I want to be able to set wildcard return urls in applications (in developer mode), such that I'm able to use various clients for testing or dynamic return urls from automated testing.

**Acceptance criteria**
- [ ] It is possible to set `*` as return url in dev mode
- [ ] It is possible to set `http://*` as return url in dev mode
- [ ] It is possible to set `https://*` as return url in dev mode
- [ ] It is possible to set `<protocol>://*:<port>` in dev mode
- [ ] Port is ignored if not specified
- [ ] Port is checked if specified
- [ ] It is not possible to set any wildcards in prod mode

**Comment by adlerhurst** [comment]
I think the user story describes what's defined in [RFC 4592](https://www.rfc-editor.org/rfc/rfc4592). Which should be considered.

**Comment by fforootd** [comment]
Relates to https://github.com/zitadel/oidc/pull/297

**Comment by alexandresoro** [comment]
Hi,

Not sure if it is directly related to the feature request mentioned above, but there's another use case for wildcard that I see, which may not be directly related to developer mode: allow wildcards for subdomains in redirect urls:

- [ ] It is possible to set `https://*.example.com`
- [ ] It is possible to set `https://prefix-*-suffix.example.com`

The use case could be for temporary deployed environments (e.g. netlify, cloudflare etc...) where a "random" subdomain is assigned and wherever the name cannot be known in advance. 
This would makes sense for developer mode, but possibly for non-developer mode too.

The acceptance criteria defined above would fit the need but would not be restricted to a single domain.

Example of such feature by Okta: https://support.okta.com/help/s/article/Does-Okta-Support-Wildcard-LoginRedirect-URLs?language=en_US or ongoing issue on Keycloack https://github.com/keycloak/keycloak/issues/14113

**Comment by yordis** [comment]
Related to https://vercel.com/changelog/urls-are-becoming-consistent

I am trying to give a try adding the feature myself, it is kind of critical for us at the moment, multiple clients that use nextjs

**Comment by yordis** [comment]
I am a bit confused: https://github.com/zitadel/oidc/pull/297/files

Maybe it is supported already?

**Comment by hifabienne** [comment]
> I am a bit confused: https://github.com/zitadel/oidc/pull/297/files
> 
> Maybe it is supported already?

its implemented in the library, but not in ZITADEL itself.

**Comment by yordis** [comment]
@hifabienne, my apologies for asking. When you say it is not in Zitadel itself, what do you mean precisely?

I tried to dig into it again, and the codebase goes from Zitadel itself into that dependency package, and not much is going on in Zitadel. So it feels that it is already there unless you are referring to the GUI or something else.

I want to try to implement it myself; I would appreciate it if somebody from the team shared some direction regarding what needs to be done.

**Comment by hifabienne** [comment]
With that I meant that for wildcard urls we first had to make a change in the oidc library, and now it would need some changes within ZITADEL. 

@livio-a @muhlemmer can you give some inputs, about what has to be implemented? So @yordis can give this issue a try?

**Comment by yordis** [comment]
👋🏻 I am gonna give it a try this incoming weekend again! If you can help me to know where is the entry point to the API call I need to change, that is good enough, I can trace later what is happening

**Comment by muhlemmer** [comment]
@yordis The management API endpoints would be:

- https://zitadel.com/docs/apis/resources/mgmt/management-service-add-oidc-app
- https://zitadel.com/docs/apis/resources/mgmt/management-service-update-oidc-app-config

With the `redirectUris` payload.

> @hifabienne, my apologies for asking. When you say it is not in Zitadel itself, what do you mean precisely?

## Current implementation

OIDC specifies interfaces that are then implemented in zitadel. In the case of this issue, the [ `op.Client`](https://pkg.go.dev/github.com/zitadel/oidc/v3/pkg/op#Client) interface looks like:

```go
type Client interface {
	GetID() string
	RedirectURIs() []string
	PostLogoutRedirectURIs() []string
	ApplicationType() ApplicationType
	AuthMethod() oidc.AuthMethod
	ResponseTypes() []oidc.ResponseType
	GrantTypes() []oidc.GrantType
	LoginURL(string) string
	AccessTokenType() AccessTokenType
	IDTokenLifetime() time.Duration
	DevMode() bool
	RestrictAdditionalIdTokenScopes() func(scopes []string) []string
	RestrictAdditionalAccessTokenScopes() func(scopes []string) []string
	IsScopeAllowed(scope string) bool
	IDTokenUserinfoClaimsAssertion() bool
	ClockSkew() time.Duration
}
```

And is implemented by zitadel here:

https://github.com/zitadel/zitadel/blob/1adfca9d281ab63beb5b0e2d031fd97ddda80291/internal/api/oidc/client_converter.go#L16-L21

## To be implemented

OIDC specifies a supplemental, optional, interface [`op.HasRedirectGlobs`](https://pkg.go.dev/github.com/zitadel/oidc/v3/pkg/op#HasRedirectGlobs):

```go
type HasRedirectGlobs interface {
	RedirectURIGlobs() []string
	PostLogoutRedirectURIGlobs() []string
}
```

In order to support redirect Globs from zitadel, the concrete `Client` type on zitadel will need to satisfy the additional interface by implementing those methods.

I would propose to return all redirect URIs from the glob methods when developer mode is enabled. Otherwise, return them from the current methods.

**Comment by yordis** [comment]
I made it work, waiting for CR! 🥳

**Comment by muhlemmer** [comment]
@buehler we used Go's [`path.Match()`](https://pkg.go.dev/path#Match) for wildcards in OIDC. Basically this allows glob-ing.  When I was locally testing https://github.com/zitadel/zitadel/issues/6912 against the acceptance criteria above, I became aware of a limitation I was not aware of before.

```
'*'         matches any sequence of non-/ characters
```

The pattern `http://*` would not match `http://example.com/auth/callback`. Every path node needs a separate `*`, like `http://*/*/*`.

Some further examples. The redirect `http://localhost:9999/auth/callback` works with the following patterns:

1. `http://localhost:9999/auth/callback`
2. `*//localhost:9999/auth/callback`
3. `http://*:9999/auth/callback`
4. `http://localhost:*/auth/callback`
5. `http://*/auth/callback`
6. `http://localhost:9999/*/callback`
7. `http://localhost:9999/auth/*`
8. `*//*/*/*`
9. `http://localhost:????/auth/callback`
10. http://localhost:????/*/*

Hope this is a workable solution for you?

**Comment by buehler** [comment]
Hey @muhlemmer,

Since you mentioned globbing; this would mean that `**` is allowed. Therefore, you could use `**/*` to match everything.

Like: `http://**/*` -> this matches each and every http call. (for example explained in https://web.mit.edu/racket_v612/amd64_ubuntu1404/racket/doc/file/glob.html)

**Comment by muhlemmer** [comment]
Hey @buehler. Good point. Go's [`path.Match()`](https://pkg.go.dev/path#Match) does not support double-star globs. However, I did find an alternative lib that we can use in our OIDC library: https://github.com/bmatcuk/doublestar

For now I will merge the above mentioned PR and I will open a follow-up PR on OIDC to switch to the doublestar package.
