### ISSUE TITLE
Instance Page Improvement

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#5137]
refers to [#627](https://github.com/caos/caos-internal/issues/627)

As a console user, I want to access and view the instance settings on a single page.

**Acceptance Criteria**
- [x] remove primary navigation (Organizations, Views, Failed Events, Settings, Customer Portal link)
<img width="613" alt="Bildschirmfoto 2023-01-12 um 13 39 51" src="https://user-images.githubusercontent.com/10165752/212068760-deb6c44b-ed2d-4e9e-b921-c4eb9c599dd8.png">

- [x] use `/instance` as single site with our basic overview, organizations, and sidenavigation where settings are shown
- [x] Failed events and views are displayed as seperate sidemenu items
- [ ] rename instance button to settings
<img width="178" alt="Bildschirmfoto 2023-01-12 um 13 34 33" src="https://user-images.githubusercontent.com/10165752/212067718-2754307b-a22e-4c7b-92ce-32686d34a071.png">

Benefits with the simplifications are the following:
- As instance settings are the fallback for all org settings we could hide irrelevant UI from the user, (b2c or single org) -> hide org settings, but show the navigation with multiple organizations.
- The above point ensures that instance settings are percieved as the main settings of the instance and reduces complexity.

**Comment by hifabienne** [comment]
Do I understand it correct that the part where I am on an organization stays as it is. 
The only thing thant changes is renaming of the button instance to settings and that we have it as a sidenav instead of top menu?

**Comment by peintnermax** [comment]
yes the org part does not change and theres a single page for all instance settings

**Comment by hifabienne** [comment]
I do have some open questions regarding this.
1. If we rename the Instance button to settings, we do have twice settings when the user is on an organization, Once for the organization in the nav and one in the top. Maybe name it default settings?
2. Do I understand it correctly that we would just take the settings page we currently have and add the points we have in the main nac Instance, Organizations, Events, etc to the sidenav.

@peintnermax did you discuss this with @juergrinaldi ? If not can you do it, so we are sure this makes sense from a ux perspective and we don't miss something?
