### ISSUE TITLE
[Bug]: OIDC Configuration not found (QUERY-s9nlw)

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5157]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

All values in https://abc.zitadel.cloud/ui/console/settings?id=oidc are empty and an Error `OIDC Configuration not found (QUERY-s9nlw)` shown in Console.

Setting all values and saving works. But as a user I can't see the default values.

### To reproduce

On your existing cloud instance to to /ui/console/settings?id=oidc 

### Screenshots

<img width="565" alt="Screenshot 2023-02-03 at 14 19 58" src="https://user-images.githubusercontent.com/1366906/216619778-6293e87e-3e3c-436e-a95d-01bf110d15a5.png">
<img width="996" alt="Screenshot 2023-02-03 at 14 20 02" src="https://user-images.githubusercontent.com/1366906/216620177-9b5764cb-ebda-4b6d-b766-dd153d7ecb17.png">

### Expected behavior

Show default values

### Version

2.18.1

### Additional Context

This is an older instance (July 15, 2022)

**Comment by hifabienne** [comment]
@livio-a was this the issue you already looked at together? I tried to reproduce but couldn't. On my instance it works fine

**Comment by hifabienne** [comment]
@mffap do you have any more information that could help us with this problem? Is it only on that instance? Or on multiple?

**Comment by hifabienne** [comment]
I tried again to reproduce this issue, also with a new created instance. Will close this for now. We can reopen if it reappears
