### ISSUE TITLE
Support Calendar Months

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5171]
As a ZITADEL provider, I want to be able to configure calendar months as quota periods, so I can develop an easy-to-understand pricing model

**Acceptance Criteria**
- [ ] I can choose the quotas reset configuration (Month or time)
- [ ] ZITADEL is able to handle calendar months

**Comment by eliobischof** [comment]
As discussed with @zitadel/engineers , we don't need this feature

**Comment by fforootd** [comment]
I yesterday did discuss this with @adlerhurst and have a different view on this.

Relying on an external system to make quota refreshments does not scale well and has an operational risk to it.
I.e if quotas are not refreshed some customers might hit the limit. 

This raises the needed guarantees that we need from the external scheduler quite a lot.

Also if we scale our cloud service this could mean that each month a huge amount of request would only be made to our api to refresh quotas, think multiple thousands and more. (this does not scale IMO)

We should integrate a quota refresh into ZITADEL and I am certain CRON expressions or something similair would do the trick.

**Comment by eliobischof** [comment]
We could implement Stripes concept for monthly anchor days.

![image](https://user-images.githubusercontent.com/12727842/219069541-45cb77b3-d8b9-4405-ba15-83b223c397a6.png)

https://stripe.com/docs/billing/subscriptions/billing-cycle

Also, I like Stripes terminology for that. So, we could give the quotas an additional configuration field `monthly_reset_anchor` with UTC DateTime type.

**Comment by fforootd** [comment]
Can you explain what use the `ResetInterval` is?

It looks to me that everything that we need is in place besides the logic to validate the resetinterval against the from.

**Comment by eliobischof** [comment]
the ResetInterval isn't aware of calendar months. It takes a fixed duration in seconds, minutes or hours but not in months. 720h means exactly 30 days, each period.

**Comment by fforootd** [comment]
Got it, but what is this information currently used for?

**Comment by eliobischof** [comment]
Closing in favor of https://github.com/zitadel/customer-portal/issues/539#issuecomment-1448292340
