### ISSUE TITLE
Code snippets in docs will get outdated

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5186]
As a docs reader, I want to have up-to-date code snippets references in the docs over time so that I can rely on their correctness.

```[tasklist]
### Acceptance Criteria
- [ ] Possibility of referenced code snippets getting outdated unrecognized is reduced 
```

Code snippets are currently referenced in the docs:
1. By copying
1. By GitHub file and line range
1. By GitHub file without line range

The first two options are very prone for becoming outdate and showing wrong results over time as the underlying source changes. I don't have a good solution in mind, yet, but I think we should investigate this.

**Comment by hifabienne** [comment]
@eliobischof can you add an example of code snippets?
I think for the examples we started referncing directly the github repositories.

**Comment by eliobischof** [comment]
Sure, sorry:

Angular example: https://github.com/zitadel/zitadel/blob/main/docs/docs/examples/login/angular.md?plain=1#L72-L84
NextJS example: https://github.com/zitadel/zitadel/blob/main/docs/docs/examples/login/nextjs.md?plain=1#L119
Found more in the Flutter example and elsewhere too.

The hard coded line numbers scare me.

**Comment by hifabienne** [comment]
Ah ok. Yes, I think its still better as before where we had the whole code in the docs. Now it is referenced. I know what you mean. But I don't know how we could change that.

**Comment by hifabienne** [comment]
Will close the issue for now, as I don't see a need to do something in that regards.
E.g when we update examples/code we will have to update docs as well.
