### ISSUE TITLE
[Bug]: 503 when registering users through external IDP

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#5193]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When loggin in for the first time with a new user through an external IDP (Azure in our specific case), the user is created in Zitadel, but actions are not run and the user is presented with the following message:
```
upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

The endpoint returning this is `ui/login/register/externalidp/callback` and it returns a 503, could this be related to Google Cloud Armor or the K8s ingress?

### To reproduce

1. Setup an external IDP
2. Allow registering
3. Login for the first time with a new user through the IDP

### Version

2.19.2

### Operating System

MacOS Ventura
Google Chrome (private tab)

### Additional Context

Can provide a HAR file if needed

**Comment by hifabienne** [comment]
Thanks @DavideWalder for reporting.
Did you follow the example to configure Azure AD: https://zitadel.com/docs/guides/integrate/azuread-oidc
@zitadel/engineers does anyone have an idea?

**Comment by livio-a** [comment]
was fixed with https://github.com/zitadel/zitadel/pull/5277 and release as v2.19.5 and v2.20.2
