### ISSUE TITLE
Onboarding Progress View

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5213]
As a (new) IAM Admin, I want a better guidance so that I know what to do next as I setup my ZITADEL.

### Acceptance Criteria
- [ ]  I be led through the setup flow in ZITADEL, till I can login to my app the first time
- [ ]  I see which steps I have successfully done (see [Mid-through progress view](https://user-images.githubusercontent.com/48990649/215735392-2a2827ac-8d0d-47e1-b4d7-9c23176bc28b.png))
- [ ]  I see wich steps are missing and how to get to the next (see [Empty state view](https://user-images.githubusercontent.com/48990649/215735384-5cbabab5-f451-4661-a35e-d1e0a5e56de4.png))
- [ ]  I can opt-out the setup flow help (which will be saved in the user metadata)
- [ ]  For users that finished or opt-out the progress we show the standard boxes (see [Completed Progress View](https://user-images.githubusercontent.com/48990649/215735394-5d9889b7-54ba-4900-872a-db110e08e3f4.png))

**Empty state of the progress**
![zitadel-onboarding02a](https://user-images.githubusercontent.com/48990649/215735384-5cbabab5-f451-4661-a35e-d1e0a5e56de4.png)
1. A button to initialize a wizard that guides you through each necessary steps
2. re-arranged the checkmarks and visual empty ones on non-finished steps
3. highlighting a next suggested step

**Mid-through progress view**
![zitadel-onboarding02b](https://user-images.githubusercontent.com/48990649/215735392-2a2827ac-8d0d-47e1-b4d7-9c23176bc28b.png)
4. fading out, strike-through and re-arranged to the end of the list steps that have been done.

**Completed Progress View**
![zitadel-onboarding02c](https://user-images.githubusercontent.com/48990649/215735394-5d9889b7-54ba-4900-872a-db110e08e3f4.png)
With this view, the cards can act as shortcuts for further navigation (and it makes it faster as well) even after the setup progress is completed.

**Additional Information**
- We can use the event api to get the information about what has already been created.

**Comment by juergrinaldi** [comment]
Follow up from #4835

**Comment by peintnermax** [comment]
@livio-a @stebenz In order to save user input like a dismiss of actions we add the metadata endpoint to the auth api.

**Comment by peintnermax** [comment]
After discussing with @juergrinaldi ,we decided to show the list of current open and done tasks initially and implement a stepper to guide through them at a later point.
The user can dismiss the progress tasks such that they are not shown in the UI again.. This user input is saved to the localstorage.

**Comment by hifabienne** [comment]
@peintnermax sorry maybe I understood it a little wrong yesterday. do we still have the order of the tasks? so the create project ist the first and create application the second?

**Comment by juergrinaldi** [comment]
@hifabienne are the suggested "tasks" final? (as the ones I've used for the screens were semi-random/placeholders.
but besides that: the initial order should be in a most logical way (so yes, project before app) but the user should be able to do it in any way if they prefer (except dependend tasks such as app (needs project)).

**Comment by hifabienne** [comment]
More or less. 
I think we should start somewhere.
Most important for me is project and application. I think it would be great to have then a step that shows or links to our exampels/quickstarts. But we should wait till we have reviewed the examples and docs page on that end. So with these 3 steps I think the user is on the best way to get started.
The others are just additional information and how to proceed afterwards.
We should maybe remove SMTP for now as we do not have the possibility to send test emails and don't want to get a lot of support messages afterwards. So we can include it as soon as we have improved that part aswell.

**Comment by juergrinaldi** [comment]
@hifabienne: @peintnermax and me discussed the other day if it would be better to make a two-stage onboarding regarding the dependencies on certain tasks. (first stage: primary tasks, second stage: dependend tasks)

Regarding your SMTP input, we could also do that in regard of most important tasks. (1st stage: only the bare minimum to get a 'hello world ready setup, 2nd stage: additional/complementary tasks (like smtp, branding)

That would lay more weight on how quick you can set up a viable enviroment. (just a first thought)

**Comment by peintnermax** [comment]
follow up to change the order https://github.com/zitadel/zitadel/pull/5331
