### ISSUE TITLE
Vue sdk and example/guide

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5223]
**Acceptance Criteria**
- [ ] We provide an authentication package extending popular oidc lib
     - [ ] Authentication is implemented with OIDC Standard and Authorization Code Flow including PKCE
     - [ ] The session of an authenticated users is persistent (e.g session cookie)
     - [ ] The user profile can be loaded from the userinfo_endpoint
     - [ ] It is possible to check if a user has a specific role (role can be taken from userinfo endpoint)
     - [ ] Logout is implemented, by using the end_session endpoint and local session must be deleted as well
- [ ] The usage is shown in an example, which included the following:
     - [ ] Example page, which redirects user to login if not authenticated
     - [ ] Example page, when user is authenticated, profile information is shown (loaded from userinfo_endpoint)
     - [ ] Example admin page, if user has a role admin, an additional page can be shown with the text "this is an administrator page"
     - [ ] In the example app I can press a logout button, after that the user can't access the profile page and has to re-authenticate.
- [ ] We provide a guide in the ZITADEL docs, which shows how to use/implement analog the angular guide: https://zitadel.com/docs/examples/login/angular
- [ ] Readme of the package includes the following:
  - [ ] Features
  - [ ] Link to documentation page and guide
  - [ ] Package structure
  - [ ] How to run examples

More specific description here: #5124

**Comment by elkon028** [comment]
I can't find a example repository for vue:  example-vue.
can you provide it?

Thanks!!!

**Comment by hifabienne** [comment]
HEi @elkon028 
We currently do not have a vue example
Its on our list to do in the next couple of weeks.
But I can't get you an ETA yet.

**Comment by kindlychung** [comment]
Please provide both vue3 and nuxt3 examples. Thanks.

**Comment by gandaldf** [comment]
I've tried with these solutions:
https://github.com/soukoku/vue-oidc-client
https://github.com/authts/oidc-client-ts (a mainteined version of: https://github.com/IdentityModel/oidc-client-js)
https://github.com/openid/AppAuth-JS
I don't understand if it's because of my frontend code or the configuration of my app in Zitadel, but in fact I can't log in... I end up in a loop where I am continuously asked to log in.

**Comment by hifabienne** [comment]
> I've tried with these solutions: https://github.com/soukoku/vue-oidc-client https://github.com/authts/oidc-client-ts (a mainteined version of: https://github.com/IdentityModel/oidc-client-js) https://github.com/openid/AppAuth-JS I don't understand if it's because of my frontend code or the configuration of my app in Zitadel, but in fact I can't log in... I end up in a loop where I am continuously asked to log in.

Can you tell us what you have configured?
Do you see an error after the login?
Is it possible, that somehow the token is not stored and therefore the user doesn't seem authenticated so you are redirected back to the login again?

**Comment by damjankuburovic** [comment]
Any news on when the Vue example will be available?

**Comment by mgsotelo** [comment]
Vue example would be great 👍

**Comment by fforootd** [comment]
Thanks for all your responses, will talk internally to see how we can improve this!

**Comment by Goran-n** [comment]
@hifabienne is there any update in terms of when we can expect this to be complete?

**Comment by hifabienne** [comment]
Hei, we do not have an ETA yet, but we want to work on our examples in the current and next quarter

**Comment by em1382** [comment]
Any update on this?
