### ISSUE TITLE
[Bug]: connecting to apache with saml through shibboleth not possible

### ISSUE THREAD

**Issue by jnull** [zitadel/zitadel#5236]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Connecting my self-hosted zitadel with apache 2.4 through shibboleth ist not possible. Shibboleth reports that the attribute StatusMessage can not be empty. The attribute itself is an optional Attribute. Capturing the SAML response issued by keycloack has this attribute not included, if empty.

Log entries: `WARN Shibboleth.SSO.SAML2 [2] [default]: error processing incoming assertion: StatusMessage must have TextContent.`

Used Versions:
Zitadel v2.19.2
Apache v2.4.41
Shibboleth v3.0.4

### To reproduce

When a application is set up with Apache and Shibboleth. Go on with the following steps:

1. Go to a location on Apache which require a authorization
2. After getting forwarded to Zitadel, log into a Account with access to registered Application/Clinet
3. When forwarded back to your Shibboleth SAML Endpoint you will receive the error

### Version

2.19.2

**Comment by stebenz** [comment]
dependend on https://github.com/zitadel/saml/pull/36
