### ISSUE TITLE
Access Log API

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5253]
As a developer, I want to be able to access the access logs per API, so that I can validate what happens on my ZITADEL instance.

```[tasklist]
### Acceptance Criteria
- [ ] I am able to make a request to the admin api to get the execution logs
- [ ] I am able to filter them analog the events api
- [ ] I am able to get a result analog the events api
```

**Comment by eliobischof** [comment]
Relates to #4458

**Comment by hifabienne** [comment]
I will close this issue for now, as we decided on a different approach
