### ISSUE TITLE
document action types

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5264]
As a user of the zitadel api, I want know where I can find the id's of the flow types and trigger types so that I know which id I have to send in the action calls.

```[tasklist]
### Acceptance Criteria
- [x] i know where I can find the id's in the docs
- [x] I know which API I have to call
- [x] Openapi documentation is done in the protos
```

**Comment by hifabienne** [comment]
Where should this be docuemented? A guide? API docs?

**Comment by adlerhurst** [comment]
I'd prefer the api docs because I'm looking for it there
