### ISSUE TITLE
[Bug]: Branding Settings not fully taken

### ISSUE THREAD

**Issue by dsiscout** [zitadel/zitadel#5289]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

We are using Zitadel integrated with our application. At the moment we do not offer the possibility to switch to dark mode on our application. To have a seamless UX, we are using on Zitadel the same branding settings for dark and light mode. The font color we set for some of the texts are not used though.
![Screenshot 2023-02-23 at 19 43 34](https://user-images.githubusercontent.com/55233123/221001720-44426e0f-d51c-4a77-9193-3867f3b9896b.png)
![Screenshot 2023-02-23 at 19 43 47](https://user-images.githubusercontent.com/55233123/221001744-504aea36-e0a1-4ddb-936c-ba65711b2960.png)

Can you adjust that all texts are using the configured setting? Or is it maybe possible to disable dark mode somehow?

### To reproduce

1. Set background color for dark mode white
2. Set font color for dark to black
3. Some texts on the login interface still appear in white color.

### Version

Cloud version

**Comment by hifabienne** [comment]
hei @dsiscout 
Thanks for your report.
I created an issue that we have to implement to avoid those breaking login UIs.
Our goal is to make it configurable if you only want to enable light design.
I will close this issue to avoid duplicates please subscribe to the new one: https://github.com/zitadel/zitadel/issues/5505
