### ISSUE TITLE
Actions for UX Measurability and Improvement

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5310]
We should enable us to measure some (anonymous) metrics about user behaviors and collect some feedback. This means Console as well as Customer Portal.

### Why we should measure user behavior
Measuring user behavior helps us to improve the experience in ZITADEL for our users and our product strategy. Right now our UX improvement is a lot of guess work and not trial and error. With some reliable user data directly from our users we have more information that we can analyse.

### Passive Metrics

Passive metrics describes any information that is recorded from ZITADEL automatically. This involves time spent on certain subpages or forms, to bounce points (where the user leaves a page (or ZITADEL)), to general customer/user numbers like how many users a customers has, how many use multi tenancy, who uses feature X, etc...)

- [ ] #5311 
- [ ] #5312 
- [ ] #5313 

### Active Metrics

Active metrics involves everything where we actively asking customers and users for feedback. This can be dedicated user tests (as we did with the login, for example), surveys on social media, our website or on Discord. Or we could ask new customers if we can have a detailed debriefing with them after their going-live.
Another good approach would be to observe first time users. 

- [ ] Usertests with selected user groups
- [ ] Surveys
- [ ] Detailed debriefing with new customers after going-live
- [ ] First time user observation

### Additional

- [ ] #5314

**Comment by hifabienne** [comment]
closed in favour of internal issue
