### ISSUE TITLE
UX Metrics - Bounce Points

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5311]
We should collect the bounce and exit points/nodes of our users. With that information we have a better insight to see what users do next (after a certain task), where they jump off to the documentation/help or abandon the application in general (i.e. onboarding process)

We should measure the following:

- [ ] what percentage of users use what link/button on a page
- [ ] list of pages with the most clicks on certain button/link (i.e. help)
- [ ] most clicked link/button on a page
- [ ] what pages has the most exits (terminated session)

Related issue/data:  #5312

**Comment by hifabienne** [comment]
close in favour of internal issue
