### ISSUE TITLE
UX Metrics - Time

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5312]
We should collect the average times on a certain page/step/form to identify possible (unnecessary) time sinks for users, unclear user flows and other anomalies and improvement points.

We should measure the following:

- [ ] avg. time spent on a page
- [ ] avg. time spent on a form
- [ ] avg. time spent on a wizard step
- [ ] nice to have: average session duration

While it is certainly helpful to know how long the time spent on a page is, it's much LESS helpful without breaking it down to certain substeps like in wizards for example. (example: it only so much helpful to know that a user is 20 minutes on the 'create app' subpage, without knowing where in the wizard he takes most time)

Related issue/data:  #5311

**Comment by hifabienne** [comment]
close in favour of internal issue (milestone times are collected)
