### ISSUE TITLE
UX Metrics - Customer/User statistics

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5313]
We should collect customer and user statistics automatically, so we have reliable and current data to tailor our product strategy and to plan features more accurately.

For that we need...
- [ ] write/present the collected data readable/accessible for UX/marketing
- [ ] it should be filter and search enabled

Possible data to collect (not a final list):
- [ ] How many users does a customer have?
- [ ] How many customers have more than X users?
- [ ] How many customers have more than X instances?
- [ ] How many customers have an account but never logged into console? (dead accounts)
- [ ] How many customers use multi tenancy?
- [ ] How many customers use feature X?
- [ ] What technologies are used with ZITADEL (in apps, for example)?
- [ ] nice to have: multi-argument-filter: How many Multi-Tenancy customers use feature X?
- [ ] nice to have: demographic data (i know, it's hard to come by, but region/country would help quite a bit to see what language we could implement next, look for cultural differences to optimize UX in certain regions, marketing targets, etc..

**Comment by hifabienne** [comment]
close in favour of internal issue
