### ISSUE TITLE
UX Metrics - Enabling A/B Testing on ZITADEL

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5314]
One of the most powerful tools to improve the user experience in general is A/B testing. (I know, I repeat myself 🙊 )
That's why I advocate strongly to enable it for console and customer portal (as we did on the website).

With proper A/B testing we can gather exact information if a new change is in fact an improvement or not, which version of a new feature we should go with, or to see if a new improvement is accepted in general, for example.

To enable A/B testing we need the following:
- [ ] to be able to "redirect" a certain percentage of our customers/users to a different live-enviroment
- [ ] to measure user behavior (time/bounces) to compare it with the other "branch" (see passive metrics in #5310)
- [ ] write/present collected data readable/accessible for UX/marketing for any given test
- [ ] nice to have: be able to identify a user later on which "branch" they were on for future surveys
- [ ] nice to have: multivariate testing: having more than 2 variations to test against each other simultaniously

**Comment by hifabienne** [comment]
close in favour of internal issue
