### ISSUE TITLE
Show all available organizations when creating (project) grants

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5317]
As a authorized Manager, I want see all available (to me) organizations so that I can create a project grant.

Considerations
- At the moment I have to go to the org overview on instance level and copy the domain string to enter in the field
- Search for "Customer" does not give me the expected result (I have two orgs called Demo-Customer and Demo-Customer2)

<img width="764" alt="Screenshot 2023-02-28 at 13 33 06" src="https://user-images.githubusercontent.com/1366906/221841890-f337da73-458d-44b5-b687-2b32e41d9433.png">

```[tasklist]
### Acceptance Criteria
- [ ] All available organizations are shown (based on user authorizations) directly on the first screen
- [ ] Search can filter for partial matches
```

**Comment by mffap** [comment]
@hifabienne I stumbled on this one today while doing a brief demo. I think it's somewhat a leftover from v1. A workaround is available, but might be hard to figure out for people who want to try out the multi-tenancy feature. To me this seems important since it's a key feature of zitadel; if the effort is not too high we should probably tackle this sooner rather than later.

**Comment by mffap** [comment]
@hifabienne can we maybe add the "good first issue"? Or is the required change too big to tackle without our help? Just saw it again in a demo and was wondering if that maybe would get picked up by the community.

**Comment by hifabienne** [comment]
> @hifabienne can we maybe add the "good first issue"? Or is the required change too big to tackle without our help? Just saw it again in a demo and was wondering if that maybe would get picked up by the community.

No I think it should be possible, as it is generally the same list as we show in the picker in the menu

**Comment by doncicuto** [comment]
I know it's not my first issue, but if you don't mind I'll try to fix this :smile:

**Comment by doncicuto** [comment]
@mffap could you confirm that you would like to change from this:

![image](https://github.com/zitadel/zitadel/assets/30386061/d7cff242-fae0-4bc0-87dc-7b16ee2cfca6)

to this?:

![image](https://github.com/zitadel/zitadel/assets/30386061/c6517c7e-414d-49f9-bba6-50a414fc5dec)

Of course, when you start typing in the organization input you'll have autocomplete
