### ISSUE TITLE
Async at least once delivery guarantee for quota notifications

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5319]
As a ZITADEL administrator, I want quota notifications to be delivered at least once so no data is lost in error cases.

```[tasklist]
### Acceptance Criteria
- [ ] ZITADEL retries to send notifications as long as their webhook endpoint doesn't return a successful response code.
- [ ] ZITADEL sends notifications asynchronously
- [ ] ZITADEL exposes a metric endpoint with an in-memory counter about failed endpoint calls
- [ ] Implementation like guarant email notification
```

**Comment by eliobischof** [comment]
Inspiration: https://github.com/ServiceWeaver/weaver/blob/main/runtime/retry/retry.go

**Comment by eliobischof** [comment]
@stebenz can you do an early review, please? Implementation is done, tests and metric are open.

I spent about 4-5 hours so far.

**Comment by adlerhurst** [comment]
review took 0.5 days

**Comment by livio-a** [comment]
discussions with elio took me about 0.5 hour
