### ISSUE TITLE
[Bug]: iFrame CSP error : User Agent does not correspond (Internal)

### ISSUE THREAD

**Issue by Badisi** [zitadel/zitadel#5332]
**Acceptance Criteria**
- [ ] samesite is set to none when iFrame is enabled

### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

I've tried the `Allow iFrame` option in my instance security settings but to no avail.

I'm getting the following message displayed in the iFrame:
> User Agent does not correspond (Internal)

I've found this [troubleshooting doc](https://github.com/zitadel/zitadel/blob/966df560264fb4779d32817a583993134fd23feb/docs/docs/manuals/troubleshooting.md?plain=1#L7) but I'm getting this issue on desktop not on mobile.

### To reproduce

1. Go here : https://badisi.github.io/auth-js/demo-app/auth-js/
2. Go to the **Settings** section
3. Select **Zitadel** in the dropdown
4. Click on **Login** at the top of the page
5. Log in with `demo` and `Pa55w0rd!`
6. Once back in the app, refresh the page
   - This should trigger a signin silent refresh with a hidden iframe

**Results**: iFrame is hidden but when testing locally I can see this message displayed "User Agent does not correspond (Internal)" (see screenshot below)

### Screenshots

<img width="1778" alt="Screen Shot 2023-03-01 at 12 21 28" src="https://user-images.githubusercontent.com/674862/222125431-04229631-7744-462c-97e4-c086dee770e1.png">

### Operating System

**OS**: macOS Monterey (version 12.6.1)
**Browser**: Google Chrome - Version 109.0.5414.87 (Official Build) (x86_64)

### Additional Context

I have tried cleaning any cookies or storages but same issue.

**Comment by fforootd** [comment]
Hm this usually means that some cookies are lost. Can you check if there are cookies being sent in the iFrame?

**Comment by Badisi** [comment]
Unfortunately no.. no cookies are sent.
<img width="1667" alt="Screen Shot 2023-03-01 at 13 21 27" src="https://user-images.githubusercontent.com/674862/222137905-7a3bc322-baa0-423c-ae95-847c1cdfbef1.png">

#### With "show filtered out request cookies" checked
<img width="1667" alt="Screen Shot 2023-03-01 at 13 21 42" src="https://user-images.githubusercontent.com/674862/222137953-1405ac07-82cd-4dbf-9813-77e1e1109ec0.png">
<img width="693" alt="Screen Shot 2023-03-01 at 13 24 44" src="https://user-images.githubusercontent.com/674862/222138644-276df76b-0fb8-423e-bf58-12d69607c49e.png">
<img width="1167" alt="Screen Shot 2023-03-01 at 13 25 20" src="https://user-images.githubusercontent.com/674862/222138725-f34f6310-b7fb-4a28-968b-875e4306b933.png">

**Comment by Badisi** [comment]
As a side note, compare to `Auth0`, their cookies are set with `SameSite=None` which avoid the cookie from being blocked.

**Comment by fforootd** [comment]
Hm true samesite lax might be the problem right there.

@livio-a whats you take on this. In my eyes the problem is that it is not a top-level request and get blocked by the browser due to lax.

I propose that we set cookies to `none` when `Allow iFrame` is used.

**Comment by Congee** [comment]
Caveat to those to came here later: Safari defaults to not send cross-site cookies even if you have SameSite=None.

https://stackoverflow.com/questions/58525719/safari-not-sending-cookie-even-after-setting-samesite-none-secure
