### ISSUE TITLE
[Bug]: No robots.txt

### ISSUE THREAD

**Issue by CMiksche** [zitadel/zitadel#5361]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

If I look at the Google Search Console, it seems like Google tries to index a lot of auth requests. This is completely unnecessary.

### To reproduce

Setup a Zitadel instance, visit the Instance and check if a robots.txt is there: 404 page not found

### Expected behavior

A robots.txt which blocks crawler from indexing e.g. auth requests

**Comment by fforootd** [comment]
True it makes sense to host a robots.txt.

@hifabienne I think it would be worth extending this in ZITADEL.

In the meantime @CMiksche you can workaround this in your proxy I hope 😁

**Comment by hifabienne** [comment]
I will close this issue as we have some duplicates. The open issue is this one: https://github.com/zitadel/zitadel/issues/5632
And @doncicuto has reported that he will contribute. 🙏🏼
