### ISSUE TITLE
Default to Single Instance Mode

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5395]
As a runtime admin, I want to be able to first run ZITADEL without the concept of multiple virtual instances so that I can easily start for simple use cases and configure my environment for more complex scenarios later.

## Acceptance Criteria

- [ ] All calls to ZITADEL map to FirstInstance created with `zitadel setup` if the host header doesn't match an existing instance.
- [ ] The docs guide the user from a single-instance configuration to a multi-instance configuration
- [ ] The difference between instance domains and organization domains is clearly described in the docs
- [ ] Add a flag for multi-instance-mode/virtual-instances-mode, per default it is started in single instance mode

Additional context: https://discord.com/channels/927474939156643850/927862361195442176/1082955222936191047

Depends on #6587

**Comment by eliobischof** [comment]
Opinions @fforootd @livio-a @mffap?

**Comment by fforootd** [comment]
I agree we should implement this as default. I.e map all traffic through to the first instance.

The one thing that needs discussion is the primary domain though, because it is needed to send mails and notifications.

**Comment by eliobischof** [comment]
> I agree we should implement this as default. I.e map all traffic through to the first instance.
> 
> The one thing that needs discussion is the primary domain though, because it is needed to send mails and notifications.

Thanks for the hint. I added an action item as discussed.

**Comment by eliobischof** [comment]
@hifabienne this one is ready for refinement

**Comment by eliobischof** [comment]
I think @livio-a had a blocking concern about the token issuer?

**Comment by eliobischof** [comment]
If we don't find the instance, we could then try to find it with the cut off subdomain? If we find it, we search an org by this subdomain and add the org ID to the context?

This would align ZITADELs behavior to the obviously much expected behavior and resolve much confusion about the org subdomains.

Could that work @livio-a? 
I guess we'd again have to pass the original domain though in go context and event bodies, so we can use it as an issuer, right?

**Comment by RomanSzabados** [comment]
> This would align ZITADELs behavior to the obviously much expected behavior of listening on org subdomains and resolve much confusion.

This would be really helpful!

**Comment by eliobischof** [comment]
It turns out that introducing a single instance mode would basically remove the external domain config. As we still rely on the external domain during instance setup, removing the external domain and introducing a new mode seems like too much overhead.

Instead, we can address the instance not found errors differently:

- Using forwarded, x-forwarded-* and x-zitadel-http1-host headers for the instance queries
- Improve docs about how to switch or add a domain (step-by-step guides, listing common scenarios etc)
- Improve UX for switching and adding a domain (like for example adding CLI commands that don't need authentication)

The following table shows which measures could have prevented the last few instance not found reports on discord.

  | Read proxy headers | Domain migration docs/ux | Domain adding docs/ux | Single instance mode | Already solved
-- | -- | -- | -- | -- | --
https://discord.com/channels/927474939156643850/1167741933800673290/1168163081675882526 | x |   |   | x |  
https://discord.com/channels/927474939156643850/927866013545025566/1166819682368626808 |   |   | x |   |  
https://discord.com/channels/927474939156643850/1166399185021567106/1166399185021567106 |   | x | x | x |  
https://discord.com/channels/927474939156643850/1166397936209494079/1166397936209494079 |   |   |   |   | x
https://discord.com/channels/927474939156643850/1165411331596370081/1166386616756097084 |   |   |   |   | x
https://discord.com/channels/927474939156643850/927866013545025566/1165914460205092904 |   |   | x | x |  
https://discord.com/channels/927474939156643850/1165772509405253732 | x |   |   | x |  
https://discord.com/channels/927474939156643850/927866013545025566/1164082196919885854 |   | x |   |   |  
https://discord.com/channels/927474939156643850/1074772204874633296/1155528889720901675 | x |   |   | x |  
https://discord.com/channels/927474939156643850/1074772204874633296/1074772204874633296 | x |   |   | x |  
https://discord.com/channels/927474939156643850/927866013545025566/1153739424660721684 | x |   |   | x |  
https://discord.com/channels/927474939156643850/1133698741795307571 |   |   | x |   |  
https://discord.com/channels/927474939156643850/1132156683829911552/1133037543391240316 |   | x |   | x |  
https://discord.com/channels/927474939156643850/1122953631029788713/1124280956946223104 |   |   | x | x |  
https://discord.com/channels/927474939156643850/1121795198784131165/1121808441715998780 |   | x |   | x |  
https://discord.com/channels/927474939156643850/1121387758250901657/1121387758250901657 | x |   |   | x |  

@livio-a I think this observation matches our discussions
