### ISSUE TITLE
Disable security controls with ExternalSecure

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5396]
As a runtime admin, I want to be able to first run ZITADEL without the need to match ExternalSecure, ExternalDomain and ExternalPort to my environment, so that I can start easily and iteratively harden ZITADELs security.

```[tasklist]
### Acceptance Criteria
- [ ] ExternalSecure=false makes ZITADEL serve all requests and disables all security headers
- [ ] The docs guide the user from a simple configuration to a more complicated configuration
```

Additional context: https://discord.com/channels/927474939156643850/927862361195442176/1082955222936191047

**Comment by eliobischof** [comment]
Opinions? Did I miss something?
@livio-a @fforootd @mffap

**Comment by eliobischof** [comment]
This doesn't seem to be a wanted feature.

**Comment by fforootd** [comment]
Well this single thing will not cut it IMO... we need to reduce mental overhead and redundant flags.
