### ISSUE TITLE
[Bug]: Primary Domain of Default Organization throws error Instance not found

### ISSUE THREAD

**Issue by matthiastz** [zitadel/zitadel#5411]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When I create a free-tier Instance and select the default Organization, copy the Primary Domain (zitadelroot2.zitadel.cloud) I always get an error `ID=QUERY-n0wng Message=Instanz nicht gefunden`

### To reproduce

When I create a free-tier Instance and select the default Organization, copy the Primary Domain and try to request it in the Browser

### Screenshots

![Bildschirm­foto 2023-03-09 um 16 54 29](https://user-images.githubusercontent.com/23010759/224079620-18c18bd1-3bf4-486c-a447-21bf3f6b106e.png)

**Comment by fforootd** [comment]
Well I think that is a wording thing we need to improve.

ZITADEL creates a domain name for each organisation and appends it to the usernames to allow for non redundant usernames across multiple organisations. Think of this like the name of an OU in an LDAP.

This domain can be verified or claimed by org owners to use their domain as suffix in the username.

However it is currently not used as a means of serving GUIs to customers. We were discussing in naming this easier something like verified domains or a such.

In zitadel cloud currently you only get a generated domain name which serves the GUIs and you can add one domain when switching to the payed tier. (the limit will be certainly be raised in the future)

Hope this helps

**Comment by hifabienne** [comment]
@fforootd can I close this issue? or do we have to implement something according to this?

**Comment by eliobischof** [comment]
Possible solution: https://github.com/zitadel/zitadel/issues/5395#issuecomment-1527193055
