### ISSUE TITLE
Standardize validation and normalization

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5412]
As a contributor, I want to have a standardized and DRY way of normalizing and validating user input so that I have a high chance of not forgetting important logic that can cause all kinds of bugs.

```[tasklist]
### Acceptance Criteria
- [ ] Validations are DRY
- [ ] Normalizations are DRY
- [ ] Validations are implemented in the domain package
- [ ] Normalizations are implemented in the domain package 
- [ ] Validations don't mutate state
- [ ] Normalizations don't mutate state
```

**Comment by hifabienne** [comment]
@eliobischof is this still relevant? Or should we close for the moment?

**Comment by eliobischof** [comment]
It's still a good idea, I guess, but not critical
