### ISSUE TITLE
Add PBKDF2 as hash algorithm

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5415]
As an administrator I can set and use PBKDF2 as hash algorithm for the passwords.

**Acceptance criteria**

- [ ] I'm able to configure PBKDF2 on an instance level
- [ ] I'm able to configure PBKDF2 on an organization level
- [ ] If I select PBKDF2 as algorithm, passwords of the users of the instance or organization will be stored with PBKDF2
- [ ] If I change the algorithm, new passwords will be stored with the new algorithm, but old passwords can still be read

depends on #5417

**Comment by fforootd** [comment]
Hm good question, it is not from me.

I think we should skip this since it is often not needed to provide the user with this choice

**Comment by hifabienne** [comment]
The title makes sense to me but not the acceptance criteria. 😁
This makes sense when i alreasy have an organization with bcrypt as default and I have to import users from another system with another algorithm.

**Comment by adlerhurst** [comment]
Import was a separate criteria on the epic. #5416

**Comment by hifabienne** [comment]
Ok. This issuebprobably doesnt make sense as separat issue. and should be included in the import as acceptance criterie. or it should state that it should be possible on the register api. but not on the ui. 
Somewhere we need to consider that this is possible. if it is separat or on the import doesnt matter for me.

**Comment by muhlemmer** [comment]
Vote to close.

- configuration criteria are covered by #5413 and #5417
- Hash algorithm itself (title) will now be covered by zitadel/passwap#1
