### ISSUE TITLE
Import users with different algorithms

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5416]
As an api user with `user.write` permission, I want to be able to set the hashing algorithm during the `ImportUser` call based on a predefined set of possible algorithms, so that I can overwrite the instance/org default.

**Acceptance criteria**
- [x] Ensure that the algorithm is used to store the password
- [x] I can import a user with a different algorithm than stored as default on the instance/organization
- [x] I am able to import a user with all the different available algorithms (bcrypt, PBKDF2)
- [x] Add the supported algorithms to the API description of the import user
- [x] Error like "Algorithm is not supported" should be sent if a password with an unsupported algorithm is sent

**Additional Information**
- Add new field hashed

**Comment by muhlemmer** [comment]
Closing as completed by https://github.com/zitadel/zitadel/pull/6196
