### ISSUE TITLE
Password hash algorithm is read from configuration

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5417]
As a ZITADEL developer I want that the password hash algorithm is read from the configured default in the defaults.yaml, instead of fixed to bcrypt, so we are able to extend ZITADEL with other algorithms.

**acceptance criteria**
- [ ] When registering/creating a user the password will be hashed with the algorithm stored on the configuration
- [ ] When a user changes the password the algorithm stored on the configuration
- [ ] When a password of a user is checked, the algorithm stored on the configuration is used
- [ ] If the algorithm has a max length for pws defined, this is considered as well

depends on #5413 

Additional Information: https://github.com/zitadel/zitadel/issues/4157#issuecomment-1468634232

**Comment by hifabienne** [comment]
This will be closed as it is implemented with: #5530

**Comment by muhlemmer** [comment]
See https://github.com/zitadel/zitadel/pull/6196
