### ISSUE TITLE
If a user is imported with PBKDF2 and changes the password later we choose the algorithm defined on the instance/organization

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5418]
As an (imported) user I want to change my password using the org's default algorithm so that I don't must have to knowledge about hashing algorithms.

**Acceptance criteria**

- [ ] Changing the passwords does not require to set a hashing algorithm
- [ ] The algorithm is set by the login policies setting

**Comment by hifabienne** [comment]
Duplicate
