### ISSUE TITLE
Device Authorization Grant

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#5420]
As a developer, I want use the OAuth Device Authorization Grant so that I'm able to authenticate users on device, which do not provide a browser (cli based) or can improve UX if an external browser can be used (e.g. TV).

```[tasklist]
### Acceptance Criteria
- [x] I'm able to allow Device Authorization Grant on a Client
- [x] I'm able to login on an authorized client through a Device Authorization Grant
- [x] I am able to set on the application if device authorization grant is allowed or not (like refresh token)
```

**Comment by livio-a** [comment]
Do we want to handle Console in the same issue or separate?

**Comment by hifabienne** [comment]
I would separate it. As we saw in the last sprints that it is easier to plan if we split issues up.
