### ISSUE TITLE
e2e test IDP template configurations

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5423]
As a developer, I want to e2e test the IDP template configurations so that I'm sure my code changes don't break them.

```[tasklist]
### Acceptance Criteria
- [ ] All IDP template configurations are covered in e2e tests
```

**Comment by hifabienne** [comment]
@eliobischof can we close this issue? I guess we will implemnt this with the new resource api directly, but not add them for the current implementation?
