### ISSUE TITLE
Define base structure for registration and login api

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5432]
As ZITADEL developers we want to have the basic knowledge how we want to implement the login and register API, so we can start with the implementation afterwards.

### Acceptance Criteria
- [ ] Output: Document as base for the following implementations
- [ ] How is the api designed, services?
- [ ] Basic structure of resources
- [ ] Basic structure of endpoints
- [ ] How do we handle the context? Administrator, self service, etc
- [ ] How do we handle backwards compatibility?
```

**Comment by adlerhurst** [comment]
@livio-a @peintnermax can you please describe the outcome of the spike here? thanks

**Comment by livio-a** [comment]
Basic decisions (see also [Jamboard esp. page 4](https://jamboard.google.com/d/1fAwPIvbxrcmkzn_2uU09anVFH9Yc3vkHBF5N6ASPI5o/viewer?f=3)):
- resource centric endpoints:
  - /users
    - /_search
    - / (<- create; auth methods need to be added / managed on separate resources)
    - /id  (Get User with all attributes incl. auth methods (based on permission))
  - /passwords
    - / (<-create with a userID in body)
    - /_check
      - Password will be checked for a user for an existing session (if provided by a session token in the body) or a new session created
      - a new session token will be returned
  - /passkeys
  - /sessions
    - /_search
    - /id
      - /terminate
  - /polices
    - /login
    - /domain
    - ...
  - IDPS
  - ...
- context (org / instance) in body or query params (GET)
  - GetLoginPolicy:
  `/policies/login?instance=true`
  `/policies/login?org_id=id`
  `/policies/login?org_domain=test.com`
  - SetLoginPolicy
  ```
  {
    "org_id": "id",
    ...
  }
  ```
- no My* endpoints, e.g. MyUser, MyOrg, ...

By having instance wide endpoints (e.g. UserByID) and without My* endpoints we need to check if a user is able to access a resource and what data within a resource after calling the database (compare AuthContext (Token / Session) to resource):
- "authenticated" (self service): authzCtx.UserID == resource.ID
- GetUserByID:
  - User within same organisation: all data / PII
  - User from other organisations: only id, display name, ?
  
SDKs (ongoing discussions):
- provide ability to build your own login (and generally use it for api calls)
- languages / frameworks
  - node.js
  - Android
  - iOS
- two SDKs: 
  - frontend (ability to create UI components; will require / include backend)
  - backend
    - create login flow with parameters
    - includes api calls
    - proxy OIDC / SAML endpoints?

idea: start with node sdk to be able to use it in the customer portal
