### ISSUE TITLE
Basic setup/structure of login / register UI

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5434]
As a ZITADEL developer I want to have the basic setup of the new login and register UI, so we can start implementing as soon as the api is ready.

```[tasklist]
### Acceptance Criteria
- [ ] I am able to set if default login should be deployed with ZITADEL or not
- [ ] Login/Register UI is buildable
- [ ] Login/Register UI is deployable
- [ ] Adding contribution guide for the new login
```

**Comment by peintnermax** [comment]
We'll have a discussion with @buehler @livio-a @adlerhurst on thursday 13.04. Moving the state of the issue therefore to READY. Outcomes of the discussion will be addressed seperately.

**Comment by hifabienne** [comment]
@peintnermax can we close this issue?
