### ISSUE TITLE
document idp templates in proto 

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5439]
As a docs user, I want know how to use the idp templates so that I don't have to scroll through code.

```[tasklist]
### Acceptance Criteria
- [ ] idp templates in admin.proto are documented
- [ ] idp templates in management.proto are documented
- [ ] messages in idp.proto are documented
```

**Comment by hifabienne** [comment]
I close this as this was done with the general documentation of the identity providers
