### ISSUE TITLE
[Bug]: Machine user creation sometimes fails with user already exists message

### ISSUE THREAD

**Issue by demircis** [zitadel/zitadel#5449]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When creating a machine user using the `AddMachineUser` request, the request fails with the following error message:

`AddMachineUser: rpc error: code = AlreadyExists desc = User already exists (SQL-M0dsf)`

I made sure that no machine user existed in the organization for which I want to create the machine user. 

In our case, we use the same username for our machine users across organizations, so maybe when trying to create a new machine user in an org which does not have any machine users, there might be a clash because of the name.

### To reproduce

Unfortunately, we could not reproduce this bug consistently, however, it might make sense to try and create machine users with the same name in different orgs and see if it fails. The request did not fail when sending the same request the second time.

### Expected behavior

The machine user should be created

### Version

2.21.2

**Comment by hifabienne** [comment]
Hei @demircis 
Thanks for the report.
Usernames have to be unique within the whole system.
If there is no way around the unique names, you would have to enable the domain suffix for the usernames, In that case ZITADEL suffixes all usernames with the domain so it is unique over the whole system. Be aware that this affects also normal users and not only machine accounts.

**Comment by hifabienne** [comment]
I will close this issue as the answer is state above, feel free to reopen, if you have more information
