### ISSUE TITLE
API: Register Passkey

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5469]
As a developer I want to be able to register a user with passkey through an API so I can build my own register ui.

**Acceptance Criteria**
- [x] I am able to start passkey registration
- [x] I am able to set which possibilities should be allowed to register (platform, platform independent)
- [x] I am able to set if i want to send an email (with or without template) or get the registration code as response,  (analog email verification)
- [x] I am able to verify passkey

**Comment by livio-a** [comment]
```
start registration:
POST /users/{user_id}/passkeys
  body: optional code
  return challenge, ...
  permission: myuser (authenticated or have a code) / user.passkey.write

verification:
PUT /users/{user_id}/passkeys/{passkey_id}
  body: signed challenge, ...
  permission: myuser (authenticated or have a code) / user.passkey.write

send registration link:
POST /users/{user_id}/passkeys/?
  body: oneOf (email, url_template, return code)
  return code if return code is set
  permission: user.passkey.write
```
