### ISSUE TITLE
API: Login with IDP

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5473]
As a developer I want to be able to login a user with a IDP through the API, to be able to build my own login ui.

**Acceptance Criteria**
- [ ] I am able to authenticate a user with a configured IDP
- [ ] I am able to set on the session which idp I want to login (either user is identified or not)
- [ ] I am able to get the idps of the instance/organisation (Solved with the policy issue)
- [ ] Return a token that includes idp has been checked
- [ ] Session is enriched with the new informations

Additional Information
Flow:

1. An endpoint to start the auth flow for xy provider (including success/endpoint url), will send an url back where you have to go
2. This url will include the provider url and a param with the callback url to get back to ZITADEL backend
3. Frontend has to call the url where user authenticates on provider xy
4. Automatically provider xy redirects to callback (ZITADEL backend)
5. ZITADEL handles all the infos (code exchange, userinfo, etc provider specific)
6. ZITADEL redirects to success/error page (sent in point 1)
7. Create user with infos returned from ZITADEL (including provider infos)

**Comment by quochuydev** [comment]
Hi team!
I have a question when `/authorize` call back, can I custom URL `https://login.example.com/login?authRequest=V2_224908753244265546` (example from the [document](https://zitadel.com/docs/guides/integrate/login-ui/oidc-standard#authorize-request)) and put more params on it.
I wanna put the orgId there (ex: `authRequest=V2_224908753244265546&orgId=100000`), so I can use API `idps/$IDP_ID/start` exact TOKEN orgId I want, If you have another solution/idea, hope you provider me.
Thank the team.

**Comment by muhlemmer** [comment]
Hi, for questions please join the Discord channel for community support. We do not track closed issues.

https://zitadel.com/chat
