### ISSUE TITLE
UI: Login with Username/Password

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5474]
As a developer I want to be able to login with username password in the default ui of ZITADEL, so I don't have to build it myself.

**Acceptance Criteria**
- [x] I am able to login with username password
- [ ] User is authenticated and will be redirected to requested app
- [ ] Domain policy is taken into account

**Comment by peintnermax** [comment]
Implementation in https://github.com/zitadel/typescript/pull/11
