### ISSUE TITLE
UI: Register Passkey

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5480]
As an enduser I want to be able to register my user with passkey authentication, so I don't have to remember my password

**Acceptance Criteria**
- [ ] The user has a description link to read more about passkey what it is and why it is useful
- [ ] I am able to choose the authentication method when registering my user
- [ ] I am able to either send password or passkey registration
- [ ] When choosing passkey registration the user doesn't need to give a name for the passkey
- [ ] I am also able to register both password and passkey so that I have the password as a backup authentication method
- [ ] After login the user should be asked if he want to register passkey directely
- [ ] The user is able to directly add the passkey after the login, the user is asked do you want to add passkey for easier login next time

**Comment by adlerhurst** [comment]
@hifabienne please migrate issue to the typescript repo.
