### ISSUE TITLE
[Bug]: Can't delete Identity Providers

### ISSUE THREAD

**Issue by CMiksche** [zitadel/zitadel#5489]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I can add new Identity Providers but can't delete the old ones.

I tried out the new Identity Provider Templates and wanted to delete my old (not working) ones.

Always when I try to delete a  Identity Provider, it shows `Identity Provider Configuration doesn't exist (INSTANCE-4M0xy)`

### To reproduce

Download the current Zitadel version, create a bunch of Identity Providers and then try to delete them.

### Screenshots

https://user-images.githubusercontent.com/9869391/226097302-57f4aa04-cfd2-47d5-996d-e5968f05c968.mov

### Version

2.22.0

### Operating System

Ubuntu with PostgreSQL

**Comment by hifabienne** [comment]
@CMiksche Thanks for the report. I could reproduce this issue. We will investigate to find out where the problem is.
