### ISSUE TITLE
SMTP Templates

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5503]
As a system administrator I want to be able to choose an SMTP template and default settings are already made, so I only have to give my configuration specific settings.

```[tasklist]
### Acceptance Criteria
- [ ] ...
```

**Comment by mffap** [comment]
I think we should provide the following templates: 
- Sendgrid
- Amazon SES
- Mailgun
- Postmark (known to be working, preconfigured)
- Google (known to be working)
- Generic SMTP provider

Additional AC: 
- #4504
- Documentation how to configure (missing at the moment)

**Comment by doncicuto** [comment]
@hifabienne assign this to me as I'm going to try #4504 too, thanks!

**Comment by hifabienne** [comment]
Hei. @doncicuto 
Thanks that looks great.
I am interested if you can figure it out with all the templates.
Not sure if thats really possible with the backend implementation. Or do you change something in the backend as well?

**Comment by doncicuto** [comment]
@hifabienne finally I'll use the Identity Providers settings component as the model to follow so it's more friendly for admins. Also, as I'm working on #4504 at the same time, thanks to this approach we could activate/deactivate a SMTP provider and test the configuration. Here's a screenshot:

![image](https://github.com/zitadel/zitadel/assets/30386061/e0f06160-b639-4bee-82fd-d547eac92509)

But now... some decissions to be made so I can continue

Would it be reasonable to allow admins to have several SMTP providers (only one active, the rest would be inactive) that they can activate/deactivate/test config? (I think the more flexibility the better) or do you prefer to keep the current behavior where we only have one SMTP configuration that can be shown and that should be deleted/replaced if we want a new one?

In the first case (several SMTP providers) I may have to add some new fields to projection smtp_configs1 like the state of the SMTP provider (active or not) so Zitadel knows which smtp configuration has to be used.

**Comment by hifabienne** [comment]
Hei @doncicuto 
This looks already great.
We quickly discussed this internally.

The best solution would be, that I am able to create multiple SMTP providers, but only one can be active.
I should be able to send test emails from all the providers no matter if they are active or not.
When I have two providers, example Google (current active), Mailjet ( not active yet) and I activate the new one (Mailjet) then Google should be deactiveted. 
Kind of like the primary domains, as there are multiple domains, but only one is primary.

In that case we could avoid sending multiple E-Mails at once.

**Comment by doncicuto** [comment]
Great  @hifabienne, thanks for the feedback:

> The best solution would be, that I am able to create multiple SMTP providers, but only one can be active

Perfect

> I should be able to send test emails from all the providers no matter if they are active or not 

I'll add a button in the providers list next to each provider's edit and delete button that will allow the test no matter the state

> When I have two providers, example Google (current active), Mailjet ( not active yet) and I activate the new one (Mailjet) then Google should be deactiveted

That will be the behavior

> In that case we could avoid sending multiple E-Mails at once. 

I'll deactivate the current active smtp provider first, then I'll activate the new one and if the activation goes wrong I will rollback and reactivate the first one

I'll open a discussion to request known SMTP configs from @fforootd and @eliobischof that I can't test (you know, some of then require a credit card or only allows email from verified domains to prevent spam).

**Comment by doncicuto** [comment]
@hifabienne I need some advice here. The sender email address, sender name and reply-to which are smtp settings too. I don't know if you prefer those to be common to any provider that we add or if you'd like those settings to be set individually for each provider.

An image worth a thousand words

You want this? I'd create a two step form for a clearer view and right now inputs has no template in action

![image](https://github.com/zitadel/zitadel/assets/30386061/e6616b37-1834-46e7-8ecf-078817a944b0)

Or something like this, where sender settings are common?

![image](https://github.com/zitadel/zitadel/assets/30386061/643851b5-2c7d-448c-a29c-2c4c2eaae31f)

Issue #3966 states that we may want sometimes to have different sender address, so it may be useful to have different sender address, email and reply-to address for each provider, but as you've contact with customers and users you could help me to decide the right way so I can work on the backend for the chosen solution. Also maybe it's the time to work in this issue right now, so orgs have stmp settings too.

Thanks in advance!

**Comment by hifabienne** [comment]
Hei @doncicuto 
Probably 90% of the time the sender name and adress will be the same. But to have the flexibility so the customers can choose, I would implement that you can have it different on each provider. 
So I would go with your first recommendation.

I am aboslutaly with you that it would be great to be able to set all of this on the organization as well.
But I would actually implement the providers first, and when that is trhough have a look at that. Just because it is easier to ship and test smaller features. And its also easier for reviews if not everything is together.

**Comment by doncicuto** [comment]
@hifabienne I'm still working on this after some heavy duty days at work.

Add a SMTP provider is a wizard with three steps:

- SMTP Provider Settings. In this screenshot host, port and user is autofilled with the settings documented by the provider

![image](https://github.com/zitadel/zitadel/assets/30386061/f43714ca-2163-44b2-b809-91b1424ae3bc)

- Sender Settings have the sender address, name, reply-to header

![image](https://github.com/zitadel/zitadel/assets/30386061/9bbe1a9e-ebb4-41c7-8489-ed6b19053fe9)
 
- Test SMTP Settings is not implemented yet, but it'll offer a summary of the configuration, a button to test the SMTP settings and a button to save the settings.

**Comment by hifabienne** [comment]
Hei @doncicuto 
Thanks this looks great.
Maybe it is easier to implement the templates first, and add the test email afterwards. 
Just to have smaller prs

**Comment by doncicuto** [comment]
Sure @hifabienne, I'll leave the test option out of this PR

**Comment by doncicuto** [comment]
Hi @mffap and @hifabienne, I'm still working on this, I try to save time every day but you'll have to wait a little more :smile: 

![image](https://github.com/zitadel/zitadel/assets/30386061/7c648c16-7a73-4e8c-8eb6-098ea77710fa)

Do you miss anything useful from the providers table?

**Comment by hifabienne** [comment]
Hei @doncicuto 
Thanks so much it looks already great.
I think thats a great starting point

**Comment by doncicuto** [comment]
Ok, right now we can activate/deactivate providers. Only one provider can be activate at a time, if we activate one another one gets deactivated, we're closer :smile: 

![image](https://github.com/zitadel/zitadel/assets/30386061/200e9f61-73f7-46fa-937d-015e5c95f7e3)

**Comment by doncicuto** [comment]
Hi @hifabienne and @mffap. I've a question about Google. When you think about the Google template, I guess that you refer to Google Workspace. In this case I've chosen option 2 from [Google options](https://support.google.com/a/answer/176600?hl=en#:~:text=filter%20suspicious%20messages.-,The%20fully%20qualified%20domain%20name%20of%20the%20SMTP%20service%20is,SSL%20and%20TLS%20protocols).

So I've something like this:

![image](https://github.com/zitadel/zitadel/assets/30386061/412f689e-f247-44bd-be3f-f6cb8a10d49e)

As this is a know configuration for you, it would be great if you could confirm this is the right template values to use or if you could provide me your good known values (I'm not familiar with Google settings...)

Thanks!

**Comment by doncicuto** [comment]
Also for Amazon SES this is my proposal. A region select will allow customers select the region and a valid smtp endpoint will be added...

![image](https://github.com/zitadel/zitadel/assets/30386061/993d0b97-2bfc-4c9f-a634-ced27214e52a)

**Comment by hifabienne** [comment]
> Hi @hifabienne and @mffap. I've a question about Google. When you think about the Google template, I guess that you refer to Google Workspace. In this case I've chosen option 2 from [Google options](https://support.google.com/a/answer/176600?hl=en#:~:text=filter%20suspicious%20messages.-,The%20fully%20qualified%20domain%20name%20of%20the%20SMTP%20service%20is,SSL%20and%20TLS%20protocols).
> 
> So I have something like this:
> 
> ![image](https://user-images.githubusercontent.com/30386061/279688802-412f689e-f247-44bd-be3f-f6cb8a10d49e.png)
> 
> As this is a know configuration for you, it would be great if you could confirm this is the right template values to use or if you could provide me your good known values (I'm not familiar with Google settings...)
> 
> Thanks!

@livio-a I think you are able to provide the values for google, or at least check which attributes are neccessary.

**Comment by Kremr** [comment]
Hello team, did you consider to include Azure Communication Services to support customer which rely on Microsoft Azure Services (https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email?tabs=windows%2Cconnection-string&pivots=platform-azportal)?

**Comment by doncicuto** [comment]
Hi @Kremr, I'm not part of the team and @hifabienne will answer you with Zitadel's view, but as a contributor I can give you mi opinion. 

Right now this issue is focused in providing mail templates for well known configurations that require a known host and port, a suggested username and has some hints as placeholders for good old SMTP notifications. 

I've checked your links about Azure Communication Services and as we should use an Azure endpoint and a key that is different for each user so I think that it doesn't fit with current templates right now.

IMHO this proposal would be a nice addition to Zitadel so I recommend you to open a different issue so SMTP support is enhanced and prospect Azure users could benefit. We could use https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager/communication/armcommunication for that purpose.

**Comment by Kremr** [comment]
You are right unfortunately Azure Communication Service does not provide a smtp endpoint, so it should not be included in this ticket. 

The key for Azure Communication Services is not different for each user, you can use the access key called "connect string" which is the same as an api key used by  sendgrid.

**Comment by hifabienne** [comment]
Hei @doncicuto Thanks for answering

I think you are right. I think we should focus on the templates for now, and have a look at further possibilities in a second step.

**Comment by doncicuto** [comment]
@hifabienne and @livio-a, if you could help me with Google values it'd great but I know you're busy so no worries, I'll comment Google code for now and enable it as soon as we can gather the right values.

**Comment by tomashora** [comment]
+1 for Office365 SMTP, willing to test @doncicuto  https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#how-to-set-up-smtp-auth-client-submission
