### ISSUE TITLE
Branding choose themes

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5505]
As a system administrator I want to be able to define what kind of themes I want to provide to my users (dark, light, both). So the UI doesn't break because I do have to configure both even when I am using only one. 

```[tasklist]
### Acceptance Criteria
- [x] I am able to set which themes I want to enable (BOTH, Light. dark)
- [x] Per default both are activated
- [x] When I only enable light, and my browser is set to dark, light is shown
- [x] When I only enable dark, and my browser is set to light, dark is shown
```

**Comment by dsiscout** [comment]
@hifabienne as this wasn't tackled until now, I fixed it myself. As this my first time contributing to this project, can you please support in aligning regaridng the review? Here is PR https://github.com/zitadel/zitadel/pull/6518

**Comment by hifabienne** [comment]
Hei @dsiscout 
Thanks for the contribution, we will have a look at the pr and get back to you

**Comment by hifabienne** [comment]
Can you have a look at this issue and estimate it? @livio-a @muhlemmer

**Comment by livio-a** [comment]
add an enum in the existing branding settings for the 3 options
