### ISSUE TITLE
[Bug]: Branding color not updating

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5547]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When I change the primary color on the branding page, it doesn't update everywhere (see screenshots below)

### To reproduce

Go to settings > branding
Change the primary color to a different color
Click Apply configuration
Change to different page (i.e. start page)
Check color of primary button/active menü item

### Screenshots

(note that I'm on current config)
![image](https://user-images.githubusercontent.com/48990649/227842932-80d384f2-c41c-4890-b3bb-f4839859563d.png)

(if I click on apply AGAIN, it changes on that screen...)
![image](https://user-images.githubusercontent.com/48990649/227843128-c6746316-249b-4bf3-a961-48c54eb6f0fa.png)

(...but as soon as I switch to another menu (i.e.: startscreen), it's back to the old one again)
![image](https://user-images.githubusercontent.com/48990649/227843263-5c1b184d-e73c-44f4-a4f2-55a804b4a2ac.png)

### Expected behavior

I expect that the branding settings are consistent through the whole application.

**Comment by hifabienne** [comment]
Hei @juergrinaldi 
I just tested this myself.
If you make a refresh it should work fine.
