### ISSUE TITLE
[Bug]: Placeholder displying without the proper error message

### ISSUE THREAD

**Issue by ShanChathusanda93** [zitadel/zitadel#5557]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

When the added Company name is not unique, the error message only displaying the placeholder as `form.organizationName.notUnique`. Please refer the below image.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/19262008/228030202-3d9c2168-544d-4228-a6e8-86fac0cb33e0.png">

### To reproduce

Go to sign up and add the company name with a existing one

### Expected behavior

Proper error message

**Comment by hifabienne** [comment]
Thanks for your report. I already fixed it, and it will be deployed to production in the next time.
