### ISSUE TITLE
Refinement Onboarding Guide

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5566]
After some testing I've found some issues with the new onboarding guide.
<img width="1436" alt="Bildschirm­foto 2023-04-05 um 18 20 52" src="https://user-images.githubusercontent.com/10165752/230142760-c32f6edf-1980-42c5-9350-d03ab803ce43.png">

- [x] **Mouse Handle on progress bar** (small)
- [x] Checkboxes unchecked are hard to see > put in border
- [ ] **Hover effect on cards** (material design (offset, dropshadow,lighter BG) _> to get a better habtic_
- [x] **Setup Link Label should be more specific** (otherwise it's pointless) _> see design draft_
- [x] **Icons missing** _(let me know if you need anything, but I've used our standard icon-set)_
- [x] IF we leave the old **additional links** (docs, get start., quickst.), it should be in the **same style** as the new ones _> see below_
- [x] **Your Onboarding progress should be a** (sub)**title**
- [x] **Additional Shortcuts** (sub)**title missing**
- [x] **Finished tasks do not differentiate enough from the open ones** _> strike through, slightly greyed out_
- [ ] If tasks are completed show a **ALL DONE splash site** (with a back to start button) _> see below_
- [x] **Wording needs to be progress neutral** _(Create new project instead of Create your first project, i.e.)_

Additional Links:
![image](https://user-images.githubusercontent.com/48990649/228563447-ca1b4487-4f26-48a9-893a-d00a2f746646.png)

ALL DONE Splash Site:
![image](https://user-images.githubusercontent.com/48990649/228567329-4e2fe2be-ee67-44f8-ac7e-f2161763fadc.png)
_(I might rework the graphic later, but this is for a first quick approach)_

Overview:
![image](https://user-images.githubusercontent.com/48990649/228571278-84ef393e-3b23-4c85-bdb7-a93cd0a08c8c.png)

See also #4835 and #5213

**Comment by hifabienne** [comment]
@juergrinaldi @peintnermax can this be closed?

**Comment by peintnermax** [comment]
Not completely.. Ill create a follow up with the last remaining parts 👍
