### ISSUE TITLE
[Bug]: Primary domain for organizations not being sanitized

### ISSUE THREAD

**Issue by sanvit** [zitadel/zitadel#5579]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Primary domain for organizations should be sanitized before being set.

### To reproduce

1. Log in to a Zitadel cloud instance
2. Create a new organization with non-alphanumeric characters.
3. Check the Primary Domain tab for the new organization
  - e.g. If I make a new organization named `test organization 3 ()`, the domain for it will be `test-organization-3-().my-zitadel-instance.zitadel.cloud`

### Screenshots

![image](https://user-images.githubusercontent.com/4323051/229104388-51ef0d3f-64c7-46e1-989a-7d2bb9814783.png)

### Expected behavior

The domain should be sanitized before actually being deployed
e.g. `test-organization-3.my-zitadel-instance.zitadel.cloud`

### Version

2.22.3

### Operating System

N/A

### Additional Context

Please feel free to log-in to my zitadel instance `instance1-4h3lvy.zitadel.cloud` to validate this issue.

**Comment by fforootd** [comment]
Thank you for reporting this, definitely worth looking into it.

**Comment by hifabienne** [comment]
Hei @sanvit looks like this can be improved on our side.
But I recommend adding your own domain, that is not suffixed with zitadel.cloud and make it your primary domain. In that case you will not have any problems with strange looking domains
