### ISSUE TITLE
[Bug]: Confirmation email link domain is always localhost

### ISSUE THREAD

**Issue by mrbodich** [zitadel/zitadel#5583]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I've deployed Zitadel to the remote hosting on fly.io, set ExternalDomain in config to the remote domain.
But once I send a confirmation email and receive it successfully, the "Click to verify" contains localhost as the domain name instead of what was set in ExternalDomain.

Here is the link I've received from Zitadel
https://localhost/ui/login/mail/verification?userID=2030...&code=0E...&orgID=203035...

### To reproduce

1. Deploy self-hosted Zitadel to the remote hosting, set correct domain in ExternalDomain in config
2. Send confirmation email from Zitadel admin dashboard, or when creating a user
3. Check the "Click to verify" button link

### Expected behavior

Confirmation link must contain a correct domain set in ExternalDomain

Example:
https://my.hostdomain.com/ui/login/mail/verification?userID=2030...&code=0E...&orgID=203035...

### Version

2.22.3

### Operating System

Mac OS Ventura 13.2.1
Safari 16.3

### Relevant Configuration

```
ExternalSecure: true
ExternalDomain: 'app-name.fly.dev'
ExternalPort: 443
```

**Comment by fforootd** [comment]
Relates to https://discord.com/channels/927474939156643850/1081518177390972958

**Comment by mrbodich** [comment]
Update:

After the discussion, I've made a fresh deployment of Zitadel, and the new instance did not have that problem. It did not contain localhost domains on it's Instance. I can't tell which version fixed that.
But fresh deployment works fine and correct.

**Comment by mrbodich** [comment]
I have some thoughts when it could happen, but not sure.
Maybe I've set ExternalDomain as localhost at first deploy, then fixed that with the correct ExternalDomain.
But Zitadel saved that first incorrect localhost ExternalDomain and did not remove it. I was able to delete "localhost" domain using API, but was not able to remove "zitadel-rg7ztb.localhost" (the second unwanted domain) because it's generated:true.

Possibly it could be a bug when Zitadel remembers old config after it was changed.

**Comment by hifabienne** [comment]
It looks like it works now for you. Due to this I will close the issue. Feel free to reopen if it happens again.

**Comment by xbexbex** [comment]
I have this exact same issue. I changed the ExternalDomain in zitadel-config.yaml to another, but the links in email still point to the old domain. 

I guess that part of the configuration is not updated when the domain changes. Is there anything I can do besides resetting everything?

**Comment by PDXUser** [comment]
I don't want to reset either, just spent the last 48 hour setting things up and hate to redo it again (Cloudfare OICD was in particular a PITA to do for me)  I am using the Docker version and don't have the zitadel-config.yaml and not sure how do edit it to change my domain the email as well.

**Comment by hifabienne** [comment]
For the email linkt the primary domain is taken into account.
You should be able to add and set primary domain trhough the system API:
Add domain: https://zitadel.com/docs/apis/resources/system/system-service-add-domain
Set as primary: https://zitadel.com/docs/apis/resources/system/system-service-set-primary-domain

**Comment by livio-a** [comment]
I've tried the calls locally and they worked out.  Maybe the guide about the system api helps as well: https://zitadel.com/docs/guides/integrate/access-zitadel-system-api

In case it still does not work, you might need to check the state in the database:
```sql
select * from projections.instance_domains;
```

**Comment by hofq** [comment]
How do i get a cli pod for a cockroach instance with a custom name? i've found no docs on this. 

I am currently having the same issue, that the Hostname in the E-Mails is not Updated (always localhost). My primary domain is set to my Domain (redacted)
![grafik](https://github.com/zitadel/zitadel/assets/54744977/62914292-ed53-42a0-9f50-9853f4a8613a)
![grafik](https://github.com/zitadel/zitadel/assets/54744977/61e50c1b-c5c0-459c-96ef-ce513ca1ecd5)

I am running:
<details closed>
<summary>Specs</summary>
<br>
Zitadel Helm 5.*.* (latest)
<br>
Cockroach Helm 11.* (latest)
</details>
<details closed>
<summary>Config</summary>
<br>
<h3>Cockroach Chart</h3>
<pre>
fullnameOverride: crdb
conf:
  single-node: true
statefulset: 
  replicas: 1
</pre>
<br>
<h3>Zitadel Chart</h3>
<pre>
zitadel:
  masterkeySecretName: zitadel-secret
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: ********
    ExternalPort: 443
    TLS:
      Enabled: false
  configSecretName: zitadel-config
replicaCount: 1
</pre>
</details>
