### ISSUE TITLE
Language: Spanish 🇪🇸

### ISSUE THREAD

**Issue by doncicuto** [zitadel/zitadel#5585]
As a Spanish speaking person I want to be able to read ZITADEL login, user profile and console in Spanish

Acceptance criteria

 - [ ] The whole login is shown in Spanish if I have Spanish as my default language set
 - [ ] The user profile is shown in Spanish if I have Spanish as my default language set
 - [ ] The console is shown in Spanish if I have Spanish as my default language set
 - [ ] Emails are sent in Spanish if I have Spanish as my default language set
 
As Spanish is my mother tongue, I'd like to assign this task to me :smile:

Related to issue #4244

**Comment by hifabienne** [comment]
Hei @doncicuto 
Would be really great to have ZITADEL speaking Spanish 😃🇪🇸
As none of us is Spanish speaking it would be great if you could contribute.
You can find a list of the files needed in our contribution guide: https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

**Comment by mrbodich** [comment]
> 

Hey @doncicuto. I'd love to add another language later too, but i am afraid I did not find the base files that could be translated by the attached link... Did not found the straightforward flow to contribute another language.

**Comment by hifabienne** [comment]
> > 
> 
> Hey @doncicuto. I'd love to add another language later too, but i am afraid I did not find the base files that could be translated by the attached link... Did not found the straightforward flow to contribute another language.

I am sorry. I just realised that i put a totally wrong link. 🙈 I just changed it. I hope this helps

**Comment by mrbodich** [comment]
Thank you @hifabienne!. What would the best way to contribute once I will have time?
I mean maybe creating pull request? But I guess some additional changes should be made to let Zitadel know about the new files? Or it will just automatically take them from that 4 folders?

**Comment by hifabienne** [comment]
> Thank you @hifabienne!. What would the best way to contribute once I will have time? I mean maybe creating pull request? But I guess some additional changes should be made to let Zitadel know about the new files? Or it will just automatically take them from that 4 folders?

In the language files for the console and for the login their is a list of the languages, where the new language should be added, after that ZITADEL just takes the files from the folders and lists the languages accordingly.

**Comment by doncicuto** [comment]
Hi @mrbodich, if you have any doubt once you read the contributing guide don't hesitate to ask me, I'm here to help
