### ISSUE TITLE
[Spike] integration testing of API

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#5598]
As we are starting with the login API we want to improve testing. For start testing the API we need to determine how we want to implement integration tests and what they should include.

Questions:

- [ ] What's the starting point of the test? (GRPC API, golang server implementation, ...)
- [ ] How should the outcome be verified? (mock of the eventstore which asserts the events, integrated database, ...)
- [ ] Which framework to choose? (golang, cypress)
- [ ] update the test concept

question to answer to improve testing in general

- [ ] what do we want to test?
- [ ] how can we implement tests easily?
- [ ] how can we assure quality?
- [ ] time goals to implement a test:
  - [ ] e2e test
  - [ ] backend unit test
  - [ ] frontend unit test
  - [ ] backend integration test
  - [ ] frontend integration test
- [ ] finish the test concept

TODO:
- [ ] Create user stories for test suite setups

**Comment by adlerhurst** [comment]
https://docs.google.com/document/d/1UxI33E-kXXlJf5Lh5kHdewkSu-E9V3DCry3i9WUJaf0/edit?usp=sharing

**Comment by hifabienne** [comment]
Just some thought i had if we test the apis backend side i guess we could mock the apis in the frontend so we know if a test doesnt run if it is backend or frontend
