### ISSUE TITLE
[Bug]: query/prepare_test: execScan eats up error when sql.Row is used

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#5635]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

When testing errors in a statement prepare function for a `sql.Row`, using `assertPrepare()`, errors are not being covered. This is because scan never gets executed, as the error is checked before:

https://github.com/zitadel/zitadel/blob/7eb8ecfc5195e73c6ec98dd89b407f82adaaf5a1/internal/query/prepare_test.go#L146-L150

It is safe to run scan on `sql.Row`, even in case of an error:

> QueryRowContext executes a query that is expected to return at most one row. QueryRowContext always returns a non-nil value. Errors are deferred until Row's Scan method is called. If the query selects no rows, the *Row's Scan will return ErrNoRows. Otherwise, the *Row's Scan scans the first selected row and discards the rest.

### To reproduce

Steps to reproduce:

1. write a prepare* function:

```
func prepareDeviceAuthQuery(ctx context.Context, db prepareDatabase) (sq.SelectBuilder, func(*sql.Row) (*DeviceAuth, error)) {
	return sq.Select(deviceAuthSelectColumns...).From(deviceAuthTable.identifier()),
		func(row *sql.Row) (*DeviceAuth, error) {
			dst := new(DeviceAuth)
			err := row.Scan(
				&dst.ClientID,
				&dst.Scopes,
				&dst.Expires,
				&dst.State,
				&dst.Subject,
			)
			if errs.Is(err, sql.ErrNoRows) {
				return nil, errors.ThrowNotFound(err, "QUERY-pCP8P", "Errors.App.NotExisting")
			}
			if err != nil {
				return nil, errors.ThrowInternal(err, "QUERY-0R2Nw", "Errors.Internal")
			}
			return dst, nil
		}
}
```

2. write tests, with only the error case:

```
func Test_prepareDeviceAuthQuery(t *testing.T) {
	type want struct {
		sqlExpectations sqlExpectation
		err             checkErr
	}
	tests := []struct {
		name   string
		want   want
		object interface{}
	}{
		{
			name: "other error",
			want: want{
				sqlExpectations: mockQueryErr(
					expectedDeviceAuthQuery,
					sql.ErrConnDone,
				),
				err: func(err error) (error, bool) {
					if !errors.Is(err, sql.ErrConnDone) {
						return fmt.Errorf("err should be sql.ErrConnDone got: %w", err), false
					}
					return nil, true
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assertPrepare(t, prepareDeviceAuthQuery, tt.object, tt.want.sqlExpectations, tt.want.err, defaultPrepareArgs...)
		})
	}
}
```

### Screenshots

No test coverage for the error case:

![image](https://user-images.githubusercontent.com/5411563/230638413-19fe043b-578f-4344-8855-e0b841f8caef.png)

### Expected behavior

Cover the complete code, including the errors.

### Version

main branch

### Additional Context

When the following is commented-out:
```
		/*
			if row.Err() != nil {
				return errCheck(row.Err())
			}
		*/
```
coverage is fine:

![image](https://user-images.githubusercontent.com/5411563/230638881-50e3b345-1153-4475-9912-a38451d67d5c.png)

**Important:** simply removing the code breaks many tests. As `object` is of type `interface{}` and now all error cases start returning a typed `nil`, resulting in non-equal tests. So in order to solve this, it requires some refactoring where we use proper typing for the expected `object`.

**Comment by hifabienne** [comment]
@adlerhurst @muhlemmer can you estimate this issue?

**Comment by muhlemmer** [comment]
I prefer to close this. It was merely a frustration as a beginning software engineer with zitadel. Although this can be improved, I don't see that we have time for that. Once you know, you know :shrug:
