### ISSUE TITLE
Auto-Link existing local org account to external IDP

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5636]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

[discord chat](https://discordapp.com/channels/927474939156643850/1092869803456335952)  

image: 'ghcr.io/zitadel/zitadel:v2.23.0'

**Goal**: create users in an org that have matching emails on an external IDP.  Zitadel when finding an email match must auto-link the existing local account to the the external identity.    It must do a case-insensitive email match.
test@idaho2324.onmicrosoft.com exists in the local org, and TEST@idaho2324.onmicrosoft.com exists in the external IDP.
When zitadel finds no match it must autocreate + autolink the accounts.

I created a user in an org upfront to simulate what will happen when I bulk import users from a legacy IDP.
The org,  Idaho2324, has a single exernal IDP.
The externalIDP is served from azureAD.  idaho2324.onmicrosoft.com
all my settings work for having zitadel autocreate an account and when I authorize using the org scope it redirects to azureAD automatically.    i.e. a user not in the local org signins in and zitadel does create an org account as expected.  

test case 1: 
No users exist in the Idaho2324 Org on zitadel
test@idaho2324.onmicrosoft.com does not exist in zitadel
This is when a user signs in for the first time using their External IDP.
USER NAME: TEST@idaho2324.onmicrosoft.com
EMAIL: test@idaho2324.onmicrosoft.com
EXPECT:  user is automatically created and linked to external IDP
PASS: This results in the account being automatically created and linked.

These next 2 cases deal with importing users before then ever sign-in to zitadel.
I have users with metadata on my old IDP, where that metadata contains critical information about the user.  This must be preserved.  The final step with importing the users is to have them auto linked to their external IDP.
-------------------------------------------------------------
test case 2:
No users exist in the Idaho2324 Org on zitadel
Manually create a user in the Idaho2324 Org on zitadel, 
USER NAME: TEST@idaho2324.onmicrosoft.com
EMAIL: test@idaho2324.onmicrosoft.com
EXPECT: as local user exists the local user is linked to the matching external IDP
FAIL: "External User not found" page is shown with error "user already exists"

test case 3:
No users exist in the Idaho2324 Org on zitadel
Manually create a user in the Idaho2324 Org on zitadel, 
Change the case on the username and email, 
USER NAME: test@IDAHO2324.ONMICROSOFT.COM
EMAIL: TEST@IDAHO2324.ONMICROSOFT.COM
EXPECT: as local user exists the local user is linked to the matching external IDP
FAIL: "External User not found" page is shown with error "user already exists"
The suggested username in the page is "TEST@idaho2324.onmicrosoft.com@idaho2324.localhost"

### To reproduce

[azuread-oidc](https://zitadel.com/docs/guides/integrate/identity-providers/azuread-oidc)  

Setup an org with a single IDP.
I have attached screen shots of my settings.

### Screenshots

![image](https://user-images.githubusercontent.com/201257/230655712-2a2742ff-ec19-4229-8d03-84e60099f8a9.png)
![image](https://user-images.githubusercontent.com/201257/230655736-b7de91a5-bdc5-4e08-81bb-875685c9054e.png)
![image](https://user-images.githubusercontent.com/201257/230655752-5ebdb328-6a1c-4a7a-b11b-9b1d4a97cd05.png)

### Expected behavior

Autolink on an email match when an existing org user exists.

### Version
   image: 'ghcr.io/zitadel/zitadel:v2.23.0'

**Comment by hifabienne** [comment]
Hei @ghstahl 
Thanks for your report.
If I understand it correctly it is about auto linking a user?
From our perspective this works currently as intended and is no bug, as we have not implemented auto linking.
But I see the use case and will create an user story for it.

**Comment by mffap** [comment]
One additional thing to consider is unique email addresses: 

Given I have a user with a unique email address in the organization, and
Given I have auto linking enabled (Org? Idp? Global?),
When the user logins the first time via the external IDP, 
Then the account is automatically linked based on the email address (without manual interaction)

Given I have a two users with the same email address in the organization, and
Given I have auto linking enabled (Org? Idp? Global?),
When the user logins the first time via the external IDP, 
Then then the user has to manually link the account

**Comment by ghstahl** [comment]
Is there a config to force email uniqueness per zitadel org.  Once an account has had a verified email, its locked, until that user logs in and changes it to another unique email that also has to be verified.

**Comment by hifabienne** [comment]
> Is there a config to force email uniqueness per zitadel org. Once an account has had a verified email, its locked, until that user logs in and changes it to another unique email that also has to be verified.

No there isn't at the moment. We are currently discussing User schemas and how customers are able to define it. #6433 
I added a comment for email uniqueness in there.
