### ISSUE TITLE
Domain Discovery should be case insensitive

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5647]
As an end user, I want to be able to enter my email in any variation of cases so that features like domain discover work properly.

Domains and emails, as per my mom, are not case sensitive.  A user will use the following forms of email and domains.

Greta@tonline.com, greta@Tonline.com, GRETA@TOnline.com, greta@TOnLine.COM etc.
All should work and all are the same thing.   

When doing any work that requires matching on email or domain, those matches should be case insensitive.

**Comment by fforootd** [comment]
Hm yes makes sense to sanitize.

@livio-a do you feel the same way?

**Comment by hifabienne** [comment]
@doncicuto Somehow I am not able to assign you to the issue right now, something strange with github. I try it again later on.
