### ISSUE TITLE
[Bug]: Editing an existing Microsoft IDP doesn't show existing scopes.

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5648]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I can't see the existing scopes when I try to edit the Microsoft Provider.  I don't know if this is a UI issue or the backend is not persisting the settings.

I would like to see the existing scopes, and really everything that was part of the configuration.  
I think Tenant ID isn't being shown either.

### To reproduce

Add a microsoft Provider, and take note of the scopes that are added.  i.e. openid profile email 

After you save it click on it to edit.  

### Screenshots

![image](https://user-images.githubusercontent.com/201257/230927500-aaa81adf-605d-48e7-8d8f-9ecad7f4c96c.png)
![image](https://user-images.githubusercontent.com/201257/230927624-d9847d91-ccc6-42cd-a7cb-78c8c66e58f2.png)

### Version

v2.23.1

**Comment by hifabienne** [comment]
Hei. @ghstahl 
Thanks for your report.
I just tested it myself. Looks like the problem with the scopes only exists on identity providers configured on the organization level. If I configure it on the instance level it works fine.
Also I could reproduce the problem with the tenant id.

**Comment by hifabienne** [comment]
This has been fixed.
