### ISSUE TITLE
[Bug]: Microsoft connection using Generic OIDC doesn't show link or register buttons.

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5660]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

I am adding all the known Identity Providers to my Zitadel organization.
google: works
github: works
microsoft personal: fails
microsoft personal Generic OIDC: fails

I assume that the decision to show the [link] and [register] buttons is on the organization level.

I have the microsoft OIDC provider configured to pass the following scopes;
```openid```, ```profile```,```email```, ```User.Read```

I don't know if this is realated to another bug where I am unsure if the generic OIDC provider is persisting the "Account creation allowed" and "Account linking allowed" configurations.

This is the URL that zitadal produced 

```
https://login.live.com/oauth20_authorize.srf?client_id=8b8cebf4-e037-4d48-8691-fc2edd4c60ea&scope=openid+profile+email+User.Read&redirect_uri=http%3a%2f%2flocalhost%3a8080%2fui%2flogin%2flogin%2fexternalidp%2fcallback&response_type=code&state=209260239214608387&prompt=select_account&uaid=a3f1c55d2dbb4a0095a29d8204949dad&msproxy=1&issuer=mso&tenant=9188040d-6c67-4c5b-b112-36a304b66dad&ui_locales=en-US&epct=PAQABAAEAAAD--DLA3VO7QrddgJg7Wevrm2BbEy2g8EBWmOTmuO2Vw_UsEJCHKM5BLxAUhPe-wD_S4cW56Z2AZjso70D6HtJQsNnCXSPqGgRfwv8S1rt-dfdBLAny_QWGs1Ft4S4Pdemj9SVpKt57ieEOBM7w-acYmLD76WSUsttuXTJj66QAsB54qeJDk0zmAg7OLkCBSAuFEDyg7ifkFUyL5116khqqjdZTYQ51YophisLhDNSDbyAA&jshs=0 
```

### To reproduce

I have posted screen shots of my configurations

### Screenshots

![image](https://user-images.githubusercontent.com/201257/231199122-fffbf6b6-1285-4dc7-ae10-4d5d50f8a035.png)
![image](https://user-images.githubusercontent.com/201257/231199268-c2bcaf7d-1e02-4ad8-9123-73bdb12db3b4.png)
![google idp ui](https://user-images.githubusercontent.com/201257/231202186-64a7b145-aa6a-47ad-ae2f-a23e5f06f289.jpg)
![microsoft generic OIDC idp](https://user-images.githubusercontent.com/201257/231202917-86ac9da4-bcd3-48b7-b167-72e622b2403e.jpg)

### Expected behavior

link and registration buttons need to be present.
The @zitadel.localhost needs to not be there, as this org is configured not to append that as a suffix.

### Version

v2.23.1

**Comment by hifabienne** [comment]
Hei @ghstahl 
Thanks for your report. 
We recommend using the personal account, and yes there are some bugs with the generic providers.
I already added an issue for the known bugs we have in the providers: https://github.com/zitadel/zitadel/issues/5654
Due to this I will close this issue, to avoid duplicates.
