### ISSUE TITLE
[Bug]: IDP search doesn't work

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5664]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

querying for idps of an org returns no results.
[reference docs](https://zitadel.com/docs/apis/mgmt/management-service-list-org-id-ps)

### To reproduce

my zitadel org contains 4 IDPs
my x-zitadel-orgid=208243952376086531
I have a service user that has all the needed permissions to make the call.  Using client_credientials.

my curl call
```curl
curl --location 'http://localhost:8080/management/v1/idps/_search' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-zitadel-orgid: 208243952376086531' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwOTI1NzQ1MjUwMjI1MzU3MSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJzdWIiOiIyMDgyNDQyMDU2MjgxNjIwNTEiLCJhdWQiOlsiMjA4MjQzOTUyMzc2MjE3NjAzIl0sImV4cCI6MTY4MTI3NDI3MywiaWF0IjoxNjgxMjMxMDczLCJuYmYiOjE2ODEyMzEwNzMsImp0aSI6IjIwOTI3MDcyNzUwNzk2ODAwMyJ9.VJ1qhNw2-ebhFuzRCD1M41RqCF1Jpt7BOWqxMU5451m9GH3d1jw43VH8JlYY4ZP5YHzwq_NlOWEUyCcbwOG8tnzH7g9kXEtjJj_QZKD5fS8aLSvPjS3Cobw8MZOX6mqbMdDtYEJv3iVqbM8MrQy-lJywYYBqFtodr9GGOBRG3IdnreeFMso7Ra6wykCHykl32OsExoRzrwKVvz6pzpm6JqpeqbMYkGHycrL9w0dAwKnBn62i8TzK7y_5ZKYKJe3mV7tnndarjGyKmztopqjd-qOcJ6W7btfbE3_qC46fbYGqTZogehmXXYbCDP_34_RGhI-b8H-kqlpepQxXMwS1_A' \
--header 'Cookie: zitadel.useragent=MTY4MTIzMTA3MnxRa0JGT2JScV9TN0ZZQUhKaXhIRXR6V3hMOUVVZktzWXhieEpNUVRKQjY1eWpHQ1Vvb3ZJSFp5dXczZ254MDhpLW1tYWtvLUFJQjAzM3B2dXkxMEpNQUJoTk4xaFZ6QT18f19nQ0CGUPXxWINs_6fnJZdfgH_HYc29Hk4VsOurbtc=' \
--data '{
  "query": {
    "offset": "0" 
  } 
}'
```

result:

```json
{
    "details": {
        "processedSequence": "450",
        "viewTimestamp": "2023-04-11T14:37:33.348676Z"
    }
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/201257/231228362-9e5e2d9c-4061-414f-a347-db425f2eaf79.png)
![image](https://user-images.githubusercontent.com/201257/231229080-985bd597-daf2-4373-9607-b7c8a7d10ea3.png)
![image](https://user-images.githubusercontent.com/201257/231229490-0ce74af5-7823-47bb-b490-c75d62ae6d6e.png)

### Version

v2.23.1

**Comment by adlerhurst** [comment]
hi @ghstahl thanks for your report. You are using a deprecated API. Please use `/idps/templates/_search` instead
