### ISSUE TITLE
Add ExternalDomain to the error message for `QUERY-n0wng Message=Instance not found`

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5673]
As a user, I want to get some help on typing a wrong instance domain so that I know where to go next.

Background
- Actual cases seen in ZITADEL Cloud: Given I have a domain `https://b2b-demo-rbxajm.zitadel.cloud/` and I type `https://b2b-demo.zitadel.cloud/` instead (not using the random generated part), then I get an error `ID=QUERY-n0wng Message=Instance not found` ([source](https://github.com/zitadel/zitadel/blob/main/internal/query/instance.go))
- The same problem occurs often also in self-hosted scenarios, thus we've provided [this guide](https://zitadel.com/docs/support/troubleshooting#instance-not-found)

Potential solution
- A user might want to get more guidance on where to go from here
- The best guess would be the configured [`ExternalDomain`](https://zitadel.com/docs/self-hosting/manage/custom-domain#standard-config)
- We could show this domain as part of the error message, for example `ID=QUERY-n0wng Message=Instance not found. Please return to https://zitadel.cloud`
- Bonus points for showing the actual domain that was navigated to
- With this users on cloud would land back on the customer portal and users on self-hosting could be helped easier because we they would see that they (probably) not configured ExternalDomain correctly

Context
- Some providers redirect to their main page (in our case zitadel.com) when a tenant is not found

```[tasklist]
### Acceptance Criteria
- [ ] Add ExternalDomain to the error message for `QUERY-n0wng`
```

**Comment by qvalentin** [comment]
Really sad that even with the log level set to debug, you get no info why the instance is wrong.

**Comment by doncicuto** [comment]
Hi @mffap, I've worked out this example:

![image](https://github.com/zitadel/zitadel/assets/30386061/2b48589b-f8fd-44e1-9481-1d9a9dc24d6d)

But as you can see in the screenshot I have only been able to test the "ID=QUERY-1kIjX Message=Instance not found" issue which means that I'm trying to access a domain that Zitadel doesn't know. For example if I try https://b2b-demo.zitadel.cloud/ I get the same error.

I've tried to look for ways to test the ID=QUERY-n0wng Message=Instance not found issue but I can't although I've seen many messages about it on Discord. Any hint that I could use to get that message?

**Comment by hifabienne** [comment]
> Hi @mffap, I've worked out this example:
> 
> ![image](https://private-user-images.githubusercontent.com/30386061/302118264-2b48589b-f8fd-44e1-9481-1d9a9dc24d6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTk4ODksIm5iZiI6MTcwNzExOTU4OSwicGF0aCI6Ii8zMDM4NjA2MS8zMDIxMTgyNjQtMmI0ODU4OWItZjhmZC00NGUxLTk0ODEtMWQ5YTlkYzI0ZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA3NTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNWU1ZmE5MmIwYTJhYWRhYzliNGU3MTg5YWYwZTcyODAzNmFjNzFjOGIyZDIwM2EyZjY5NmEwMjA2ODRmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fVbWnuIplIUFxuTT6z465O1XoDZofVOiW7pwofjc14)
> 
> But as you can see in the screenshot I have only been able to test the "ID=QUERY-1kIjX Message=Instance not found" issue which means that I'm trying to access a domain that Zitadel doesn't know. For example if I try https://b2b-demo.zitadel.cloud/ I get the same error.
> 
> I've tried to look for ways to test the ID=QUERY-n0wng Message=Instance not found issue but I can't although I've seen many messages about it on Discord. Any hint that I could use to get that message?

@eliobischof @stebenz I think you can help here
