### ISSUE TITLE
Show all settings in "pro mode" when setting up applications

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5680]
As a pro user, I want to configure all my settings on one page so that I can create an app in one step.

### Acceptance Criteria
- [ ] #5678 
- [ ] Can set all token settings

**Comment by doncicuto** [comment]
Hi @mffap this issue has an "issue" that prevents tasks to be rendered? Could you have a look? I'd like to try this issue. Thanks!

**Comment by fforootd** [comment]
I updated the list, now it should be fine

**Comment by hifabienne** [comment]
This is already implemented will close the issue
