### ISSUE TITLE
Add grant type device_code to console

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#5684]
Follow up issue on https://github.com/zitadel/zitadel/issues/5420#issuecomment-1465452228 and #5646, which added a new grant type in the back-end and proto:

https://github.com/zitadel/zitadel/blob/a66711b342e3cfe85a2e9597020b33261b6c1d6d/proto/zitadel/app.proto#L183

### Acceptance Criteria
- [x] The "Device Code" grant option to be available in the App configuration page.
- [ ] When "Device Code" is selected, "Authorization Code" is no longer a hard requirement and user should be able to de-select this grant type.
- [ ] When only "Device Code" is selected, redirect URLs are not needed. Warnings for missing URLs can be suppressed.

![image](https://user-images.githubusercontent.com/5411563/231887954-a6021d90-e60e-48a7-a5c6-b2c11f27a872.png)

**Comment by peintnermax** [comment]
App setup and detail page is done with #5771.
Currently the backend throws an error if the application is created or changed without grant type code
