### ISSUE TITLE
Sort tables by default

### ISSUE THREAD

**Issue by juergrinaldi** [zitadel/zitadel#5706]
As a ZITADEL user, I want to sort tables by table headers so that I can find relevant data more easily.

The sorting should be allowed on any column via click on the header label and be indicated by a little arrow.

There should also be a sorting by default and we should be able to set that default per table on what makes most sense.
(I can quickly think of either per creation/change date or alphabetic on the first row)

```[tasklist]
### Acceptance Criteria
- [ ] implement a sorting function for all tables in ZITADEL, to sort descending or ascending
- [ ] implement a default sorting - that can vary on different tables
```

**Comment by hifabienne** [comment]
I will close this issue, as we have specific ones for the different list requests when it is requested by customers
