### ISSUE TITLE
Delete Organizations

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5737]
At the moment the delete functionality in ZITADEL is implemented more as an "archive" function. As an administrator I want that when I click "delete" in the console or send "delete" to the API, that the organization is actually deleted.

```[tasklist]
### Acceptance Criteria
- [ ] I am able to delete an organization through the api or console
- [ ] A deleted organization is not returned in the list organizations request
- [ ] No resources of a deleted organization can be read or manipulated
- [ ] I can't manipulate a deleted organization
```

**Comment by doncicuto** [comment]
@hifabienne I've implemented the organization deletion. I understand that you want the organization to be deleted from the projection.orgs table, don't you? 

If that is the case I've a doubt. In #4148 code was added in the backend so the resources that depend on a removed organization would be kept in the database (at least is what I think) updating the owner_removed column whenever an org is removed. 

Do you want that if an organization is deleted, it is not only removed from the database but the rest of resources (personal access tokens, projects, users, user metadata, etc) are also deleted from the database, or do you want to keep the owner_removed column usage for auditing?

Thanks in advance!

**Comment by hifabienne** [comment]
I would say we remove everything. @livio-a what is your opinion?

**Comment by livio-a** [comment]
> I would say we remove everything. @livio-a what is your opinion?

yes i think the "delete / remove org" command should really remove everything. i'm unsure whether we should keep the current implementation as an additional archive mechanism.

As we're pretty busy this and next week, i was not yet able to check the PR.
