### ISSUE TITLE
Automated PostgreSQL Tests

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5741]
As a ZITADEL developer we want to test ZITADEL automated with a PostgreSQL, so we do not have to manally test and can ensure that ZITADEL works with PostgreSQL, even if we don't use it ourself.

```[tasklist]
### Acceptance Criteria
- [ ] Automated Tests with PostgreSQL
```

**Comment by hifabienne** [comment]
Hei @muhlemmer 
I just created this issue, so I can link it in our docs to state when we get out of the Beta.
If you can't include them easily with what you are working right now, we will take it into the refinement and a sprint.

**Comment by hifabienne** [comment]
@muhlemmer Are the postgreSQL tests included in the new test setup?

**Comment by bigbang4u2** [comment]
Any updates on when zitadel postgres will be out of beta state?

**Comment by hifabienne** [comment]
Hei @bigbang4u2 
We have just refactored our pipeline, which also includes the automated postgresql tests.
As soon as the following pr is merged and we have built a release with it, just to be sure that everything works as expected, we can remove the beta state: https://github.com/zitadel/zitadel/pull/5953

**Comment by shivamtiwari2009** [comment]
Since above PR is now merged, does this mean it is out of Beta

**Comment by hifabienne** [comment]
@shivamtiwari2009 yes you are right, I will change the documentation accordingly, and we will also add a note to the next release.

**Comment by bigbang4u2** [comment]
Any update on this ? https://zitadel.com/blog/postgresql-support still says its in Beta

**Comment by fforootd** [comment]
Since we introduced integration test for postgres it should work out of the box.

We since dropped the beta flag.
