### ISSUE TITLE
[Bug]: Unable to use postgresql without exposing admin credentials

### ISSUE THREAD

**Issue by Be-El** [zitadel/zitadel#5744]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Database initialization code in tries to access the postgresql instance with admin credentials. The name of the database to connect to is also hard coded in the backend code ("postgres").

This is fine for test and lab setup. But exposing admin credentials for a productions grade shared postgresql cluster is suboptimal security wise.

A simple solution is making the database use for the checks configurable. The documentation already requires to setup the database before deploying zitadel, so using the same account should be sufficient for connection, database and grant checks.

### To reproduce

1. configure zitadel with postgresql backend according to documentation _without_ extra admin account

**Comment by hifabienne** [comment]
Hei @Be-El 
I think you can just overwrite some env vars for the credentials.
This is how we do it. In that case there should be no credentials exposed.

**Comment by Be-El** [comment]
Hi,

env vars are just another way to expose information. So security wise nothing is gained by env vars.

The problem is the pg backend code in zitadel. It always tries to use the admins credentials to manage the user and the database. As I said this is fine for development and test setups. But for external databases the code may not attempt to alter the database. If the administrator did not configure either the database or zitadel correctly, it should simply fail.

The necessary change is really small. In case of the admin credentials the backend code uses a hard coded database name ('postgres', and "administrator's database" in postgresql...). If this database name would be configurable, I could use the same credentials for the admin access. The necessary checks should be fine if the database is configured correctly (user should be present, database and database access should be present etc.).

**Comment by hifabienne** [comment]
@adlerhurst @livio-a can you give a feedback please?

**Comment by mayoatte** [comment]
Any updates on this? It's a blocker for us.

**Comment by eliobischof** [comment]
The admin account is only used in the init phase.
If you prepare the database manually, you can skip the init phase and start zitadel using `zitadel start-from-setup` without specifying an admin user.
The steps you have to follow manually: https://zitadel.com/docs/self-hosting/manage/updating_scaling#the-init-phase

Please reopen the issue if that doesn't help.

**Comment by mayoatte** [comment]
Thank you, @eliobischof.
