### ISSUE TITLE
[Bug]: You can select same user infinitely on Authorization creating page

### ISSUE THREAD

**Issue by MadL1me** [zitadel/zitadel#5753]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

On authorization creating page, you can select same user for multiple times

### To reproduce

1. Create user with any name
2. Create project with any name
3. Create role with any name
4. Go to authorization page
5. Try to grant authorization for a user
6. You can select same user infinitely amount of times

### Screenshots

![image](https://user-images.githubusercontent.com/46647517/234560202-69aa6f69-104e-4a35-a32f-387708e8c514.png)

![image](https://user-images.githubusercontent.com/46647517/234560234-b4fbaf75-de0e-414c-b2a4-abdb441b6676.png)

### Expected behavior

You can select concrete user to grant authorization only once. After selecting to user, it disapears from list of all users to select

### Version

From documentation docker-compose example (latest version)

**Comment by hifabienne** [comment]
Hei @MadL1me 
Thanks for your report.
