### ISSUE TITLE
The setup phase should wait until setup events are projected

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5756]
As a system admin, I want the setup phase not to return earlier than the expected setup events are projected so that a new ZITADEL version is ready to serve traffic just when the projections are up-to-date.
I don't have to migrate newly added projections anymore, as they are computed in the background while old binary versions still serve traffic.
I can remove my probably wrong retry scripts from my automated installations.

```[tasklist]
### Acceptance Criteria
- [ ] `zitadel setup` returns just when all setup events are processed
- [ ] `zitadel start-from-init` and `zitadel start-from-setup` return an error response at the ready endpoint until all setup events are processed. 
- [ ] `zitadel setup`, `zitadel start-from-init` and `zitadel start-from-setup` have a flag that disable waiting so if something goes wrong in the setup phase a new version is still deployable.  
```

**Comment by eliobischof** [comment]
@muhlemmer @adlerhurst what do you think?

**Comment by eliobischof** [comment]
Helps implementing #5739

**Comment by adlerhurst** [comment]
another idea would be to add an additional command which does that job. so that the system admin can decide themselves if the projections must be computed before zitadel start is executed.

**Comment by eliobischof** [comment]
I'm a bit worried that with a new command we also add unnecessary mental overhead and confusion. 
I think the most common way is to run `zitadel setup` without special arguments.

With an optional flag `--omit-projections` system admins could filter projections with wildcard support as they like.
Then admins are free to deploy without waiting when things already went terribly wrong.
Also, they could split the work to multiple processes if a new version adds a lot of projection.

What do you think @adlerhurst?

**Comment by muhlemmer** [comment]
> muhlemmer adlerhurst what do you think?

Sounds like a good idea :). Related is that the [API documentation](https://zitadel.com/docs/apis/observability/health#ready) does mention that the `/debug/ready` endpoint should already behave the way that's mentioned in the user story, but it doesn't.

> The `Ready` endpoint is located on the path `/debug/ready` and allows systems to probe if a ZITADEL process is ready to serve and accept traffic. This endpoint is useful for operations like [zero downtime upgrade](https://zitadel.com/docs/concepts/architecture/solution#zero-downtime-updates) since it allows systems like Kubernetes to verify that ZITADEL is working on something (e.g. database schema migration) but is not yet ready to accept traffic.

**Comment by eliobischof** [comment]
> Sounds like a good idea :). Related is that the [API documentation](https://zitadel.com/docs/apis/observability/health#ready) does mention that the `/debug/ready` endpoint should already behave the way that's mentioned in the user story, but it doesn't.

IMO, the ready endpoint behaves as expected. ZITADEL is at least ready to accept commands when it returns a successful response at the ready endpoint. Also it accepts queries, but in our special eventsourcing case, the read side just might not be consistent, yet. But this is the case with all queries.
I think, normally, systems report readiness when the binary and the dependent systems are up.

IMO, awaiting for setup consistency should be specific to the setup phase. Not consistent != not ready, as we are never consistent, right?

**Comment by muhlemmer** [comment]
It seems that the integration tests no longer have issues with consistency during startup. The current polling of the ready endpoint seems all we need. Furthermore if we run a single binary in testing like proposed in https://github.com/zitadel/zitadel/issues/6684 we should even be less dependent on the setup consistency.

As polling the ready endpoint seems to give reliable results in integrations tests (not a single one failed on setup inconsistency in the last months) I would vote to close this issue and not spend time on optimizing something that isn't causing trouble anymore.

**Comment by muhlemmer** [comment]
@eliobischof any feedback on above comment?

**Comment by eliobischof** [comment]
I agree
