### ISSUE TITLE
[Bug]: Add authorization to external user - valid loginname could not be found

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#5761]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Given I have a user with the "login methods" `admin.alice@example.com` and `admin.alice@demo-customer.b2b-demo-rbxajm.zitadel.cloud` in OrgA
When I want to add an authorization for an external user in OrgB with `admin.alice@example.com`
Then I get an error that the user cannot be found

alternatively, 

When I want to add an authorization for an external user in OrgB with `admin.alice@demo-customer.b2b-demo-rbxajm.zitadel.cloud`
Then I can proceed to create an authorization

### To reproduce

see above

### Expected behavior

It should be possible to create an authorization with all valid login methods. The external user is most likely identified with the same login method that she uses for the system (eg, Email).

**Comment by adlerhurst** [comment]
IMO this issue is fixed.

![image](https://github.com/zitadel/zitadel/assets/27845747/b7dd16b7-4c07-45b0-b961-17d958bf33d7)

Please reopen if I'm wrong.
