### ISSUE TITLE
[Bug]: Can't set user metadata

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#5763]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

Can't set user metadata, I get a successful response, but nothing changes.
Also, the message looks wrong (see screenshots), it is the same as the message for MFA factors.

### To reproduce

1. Add metadata to a user

### Screenshots

![Screenshot 2023-04-27 at 10 20 27](https://user-images.githubusercontent.com/58290976/234803109-75ac7499-2a69-4907-98e0-e29b49a568e9.png)

### Version

2.25.3

**Comment by hifabienne** [comment]
Hei @DavideWalder 
I just tested this myself, and it worked fine:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/38692350/234862412-d344f327-546d-46ca-bfd7-2c7df7d20cb4.png">

Did you try this in the console for another user? Or for your own user?

**Comment by adlerhurst** [comment]
this issue was resolved by the latest release
