### ISSUE TITLE
Make period for TOTP configurable

### ISSUE THREAD

**Issue by karatekaneen** [zitadel/zitadel#5795]
As an authenticating user, I want to have more than 30s to complete TOTP validation so that I can use slower forms of TOTP, for example SMS or E-mail.

```[tasklist]
### Acceptance Criteria
- [ ] Modify the API to be able to configure the period if needed
```

### The problem

We have a lot of clients that have a lot of legacy (think like governmental agencies etc). 
Today we are using a custom SMS/Email solution for 2FA. We are looking to migrate all of our auth to Zitadel and during the transition we'd need some way to keep the "old" 2FA until everyone has updated to something more modern.

### Proposed solution

In the package used for TOTP it is [possible to configure the period](https://github.com/pquerna/otp/blob/v1.4.0/totp/totp.go#LL132C1-L132C1) and it is set to 30s by default. If there could be a way to change the API of [`AddHumanOTP`](https://github.com/zitadel/zitadel/blob/main/internal/command/user_human_otp.go#L42) to receive a `Period` (maybe even optionally?) somehow and then pass it down to [`NewOTPKey`](https://github.com/zitadel/zitadel/blob/main/internal/domain/human_otp.go#L20) it would solve our needs.

This would need to then surface this parameter up to the API:s by adding it as a field to [`AddMyAuthFactorOTPRequest`](https://github.com/zitadel/zitadel/blob/main/proto/zitadel/auth.proto#L1298). Another solution would be to add this as a configuration option on the organization level.

### Possible implications

I don't have deep knowledge of this codebase so I'm not sure if this will break some interface or other pattern that you are using. Since the change I'm proposing is additive it should not break existing code since the default value should still be the same.

Lastly, if this is considered a good idea I'm open to try to implement it myself, I just don't want to put in the work and then have it rejected.

PS: 
If you have an idea on how I could accomplish this without changes I'd be very happy to hear.

**Comment by hifabienne** [comment]
hei @karatekaneen 
We have now additionaly Email land SMS second factor. Would that solve your problem as well?
I just reread you issue, and I am not sure what the problem is you are trying to solve.
