### ISSUE TITLE
remove hard requirement of grant type authorization code for device code applications

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#5820]
follow up of https://github.com/zitadel/zitadel/issues/5684

As an application creator, I want to have a native application for device code without the authorization code grant type.

```[tasklist]
### Acceptance Criteria
- [ ] remove hard requirement for native app
- [ ] create device code app without authorization code as grant type
```

**Comment by hifabienne** [comment]
Close this issues as it is already implemented, but automatic closing didn't work
