### ISSUE TITLE
ZITADEL API: Standardize the way of writing and running acceptance tests.

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5832]
"As a developer, I want to have an easy way to run acceptance tests, so that I can easily maintain them.

**Acceptance Criteria**
- [x] An example acceptance test is easily runnable locally.
- [ ] The integration tests merged with this PR are renamed to acceptance tests: https://github.com/zitadel/zitadel/pull/5739.
- [x] Changes are just merged to main, if all acceptance tests succeed.
- [x] The CONTRIBUTING.md states the relevant Ready for review expectations:
   - Acceptance tests against the gRPC server ensure that one or multiple API calls that belong together return the expected results.
   - Acceptance tests against the gRPC server ensure that probable good and bad read and write permissions are tested.
   - Acceptance tests against the gRPC server ensure that the API is easily usable despite eventual consistency.
   - Acceptance tests against the gRPC server ensure that all probable login and registration flows are covered."

**Comment by hifabienne** [comment]
I will close this issue as it has been released
