### ISSUE TITLE
ZITADEL Login and Registration Server Side Golang UI: Standardize the way of writing and running unit and integration tests.

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5835]
As a developer, I want to have an easy way to run unit and integration tests, so that I can easily maintain them.

**Acceptance Criteria**
- [ ] An example unit and integration test is easily runnable locally.
- [ ] Changes are just merged to main, if all unit and integration tests succeed.
- [ ] The CONTRIBUTING.md states the relevant Ready for review expectations:
   - Unit tests ensure that non-trivial functions map certain inputs to expected outputs.
   - Integration tests ensure that given auth requests and policies are mapped to expected responses.

**Comment by hifabienne** [comment]
I will close this issue, as it is not planned, we rather work on it in the typescript login
