### ISSUE TITLE
ZITADEL Login and Registration Server Side Golang UI: Standardize the way of writing and running acceptance tests.

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5836]
As a developer, I want to have an easy way to run acceptance tests, so that I can easily maintain them.

**Acceptance Criteria**
- [ ] An example acceptance test is easily runnable locally.
- [ ] Changes are just merged to main, if all acceptance tests succeed.
- [ ] The CONTRIBUTING.md states the relevant Ready for review expectations:
   - Acceptance tests ensure that all login and registration flows work with a mocked UI Client and different policies as expected.
   - End-to-end tests ensure that all probable external login and registration flows work as expected with the SSR UI.

**Comment by hifabienne** [comment]
I will close this issue as it is not planned, we rather work on it in the new typescript login
