### ISSUE TITLE
Coding Principles: Add DRY to all PR templates

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#5859]
As a developer, I want to have a check in the PR template for DRY code, so my reviewer and I are reminded about this coding principle.

**Acceptance Criteria**
- [ ] Acceptance Criteria “My code has no repetitions” is added to all PR templates

**Comment by hifabienne** [comment]
ZITADEL: https://github.com/zitadel/zitadel/pull/5907
Customer Portal: https://github.com/zitadel/customer-portal/pull/776
OIDC: https://github.com/zitadel/oidc/pull/396

**Comment by eliobischof** [comment]
Thanks @hifabienne
