### ISSUE TITLE
External IDPS not showing up for existing users

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#5874]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

2.27.0

My default org has 3 external IDPS.  
I navigate to the [console](http://localhost:8081/ui/login/userselection) which only shows me a page to enter the email. (NO EXTERNAL IDPS)

I would expect that if the ORG has 3 external IDPS that they show up on the "enter email" page.  From the reproduceable steps this is the case when you follow the flow.

### To reproduce

My default org has 3 external IDPS.  
I navigate to the [console](http://localhost:8081/ui/login/userselection) which only shows me a page to enter the email. (NO EXTERNAL IDPS)

I enter the email which then shows me the password page.
I click the [BACK] button
I now see a page that ask me for the email and the 3 IDPS are displayed.

### Expected behavior

I expect that the external IDPs show up for an org on the main "enter email" page when navigating directly to the console.

### Version

2.27.0

### Operating System

Docker

**Comment by fforootd** [comment]
Thanks for raising this issue.

This relates to https://discord.com/channels/927474939156643850/927866013545025566/1107695305664774306 right @ghstahl

**Comment by ghstahl** [comment]
Yes. It was that [back] button that caused the idea to magically show up that turned it into an issue.

**Comment by ghstahl** [comment]
There is inconsistency on the flows.
1. It works one way when a client app uses the org scope to login (correctly in my opinion)
2. vs when zitadel is setup to have the same org as the default. (should work the same way as #1)

From a product requirement.
As a user I should be able to navigate to zitadel's console and login with all means provided by the default org.  In this case username/password and any external IDP.  
As a user I should be able to link and unlink external IDPS from my local username/password account only using the zitadel console.   

This is akin to my going directly to accounts.google.com.

**Comment by hifabienne** [comment]
Hei @ghstahl 
If I understand you correctly you have setup the idps on the organization level and you want to show the idps on the first screen.
This is only possible if you use the organization scope. urn:zitadel:iam:org:id:{id} https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes
As ZITADEL needs to know from which organization to trigger the settings. 
You can either setup the idps on the instance level in that case they are shown for all users. or sent the scope to identify which organization should be triggered

**Comment by ghstahl** [comment]
Product Requirement Suggestion:
From my perspective initiating a login passing the org scope from my webapp  should behave the same as if I set the same org as the default org and navigate to the zitadel console to sign in directly.

It seems odd that I would need to also put the same IDPS at the instance level the MUST exactly match what I call the default orgs setup.  

I don't know what would happen if I added 3 idps at the instance level and my primary org only has 1.  Who or what wins when you show the external IDP buttons.

**Comment by hifabienne** [comment]
I see your point. I think this is something we definitely can improve in the future.

However, at the moment it works as designed. Therefore I will remove the Bug label and put the issue into the backlog for future improvements.
Thanks for reporting

**Comment by ghstahl** [comment]
Ok, I moved my social IDPs out of my  primary org and into the Instance level.

**Comment by hifabienne** [comment]
We have changed the default behaviour of ZITADEL to use the default organization settings when opening the login without a org scope. So the instance settings will not be triggered anymore.
This is automatically like this when creating a new instance, for existing instance we have introduced a feature flag, as if we just would change it that could cause some breakin behaviour.

You can find everything in the following technical advisory, also how to change the behaviour for existing instances. https://zitadel.com/docs/support/advisory/a10003

Therefore I will close this issue
