### ISSUE TITLE
I'm trying to use the API but the doc is a bit confusing.

### ISSUE THREAD

**Issue by Sipioteo** [zitadel/zitadel#5916]
I'm trying to use the API but the doc is a bit confusing.
It says that it can be used to create your own "login ui" but i can't find how to convert a sessionToken to accessToken+refreshToken+idToken.

Can you provide some more explanations?

_Originally posted by @Sipioteo in https://github.com/zitadel/zitadel/discussions/5875#discussioncomment-5975558_

**Comment by hifabienne** [comment]
Answered in original discussion: https://github.com/zitadel/zitadel/discussions/5875#discussioncomment-5975558

**Comment by hifabienne** [comment]
Issue will be closed
