### ISSUE TITLE
Service account client credenitials popup client id is wrong

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#5919]
I follow this guide: https://zitadel.com/docs/guides/integrate/client-credentials

When I add a new service account and add client secret for it, in the popup of the client id, client secret, it does always show the username of the account and not the full loginname, not matter what I have configured in my settings.

When showing the client id the domain policy should be taken into account.

## Acceptance Criteria
- [x] When domain suffix is disabled client id should be the username
- [x] When domain suffix is enabled client id should be the whole loginname
- [x] Response should send the correct value
- [x] Console should show correct value

**Comment by muhlemmer** [comment]
Note that when enabling the policy, all current users are suffixed with the domain. When the option is disabled the suffix remains and can only be removed by changing the username on humans. For machines the names can't be updated and the change is permanent.

The mentioned fix takes the `PreferredUsername` which follows the same behavior:
- When domain suffix is disabled client id username is returned
- After it is enabled once, the username with domain will be returned always for existing users
- After domain suffix is disabled again,  only new machine users will return the short username.
