### ISSUE TITLE
[Bug]: Nil pointer error while creating an instance

### ISSUE THREAD

**Issue by arslan-gait** [zitadel/zitadel#5960]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.27.1

### Describe the problem caused by this bug

I am trying to create an instance using [REST API](https://zitadel.com/docs/apis/resources/system/system-service-create-instance). My goal is to create an instance with a machine user so that I can access the instance without UI. When I try to create an instance, the connection to server hangs up and I see nil pointer errors inside the Zitadel logs.

### Prerequisites
- Setup a self-hosted Zitadel instance
- Use Postman/curl or any other tools to send API requests
### Steps to reproduce
1. Send the following request to `{domain}/system/v1/instances/_create`:

```json
{
  "instanceName": "my-instance",
  "firstOrgName": "my-org",
  "customDomain": "my-domain",
  "machine": {
    "userName": "john",
    "name": "John",
    "personalAccessToken": {
      "expirationDate": "2025-04-01T08:45:00.000000Z"
    },
    "machineKey": {
      "type": "KEY_TYPE_JSON",
      "expirationDate": "2519-04-01T08:45:00.000000Z"
    }
  },
  "defaultLanguage": "en"
}
```

2. Receive nil error in Zitadel logs
[create_instance.log](https://github.com/zitadel/zitadel/files/11616149/create_instance.log)

### Expected behavior

A successful response from the server with personal access token

### Operating System

Device: MacBook Pro 14", M1 Pro CPU, 16GB
OS: macOS Ventura 13.4
Software:
Postman v10.14.6
Colima 0.3.4
Docker Compose 2.4.1
zitadel-tools v0.4.0 to generate JWT to access System API

### Additional Context

If I remove `personalAccessToken` from the JSON request, the instance is created as expected

**Comment by fforootd** [comment]
Thanks for raising this, let us investigate the cause.
