### ISSUE TITLE
[Bug]: IDP getting removed from users on Cascade when setting it as "not available"

### ISSUE THREAD

**Issue by lukasver** [zitadel/zitadel#5968]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.27.0

### Describe the problem caused by this bug

Changing a generic OIDC IDP as **not available** blocked several users from accessing with Zitadel to our app due to IDP configuration getting removed on cascade from all the users that have signed using that IDP. Enabling afterwards caused this users to have no IDP configured in the Zitadel user record, and got stuck in the "link" account screen without being able to link to existing account.

<img width="86" alt="image" src="https://github.com/zitadel/zitadel/assets/63676303/3bea65d4-206e-43ce-8192-e637db497d84">

 IDP I would expect it to be removed from the options for users to access the resources, and, after some time being able to enable it again allowing users that have already created a record with it being able to use it without even noticing a change

### To reproduce

Events to reproduce:
1) Create an IDP and set it as available
2) Create an user (or several) into Zitadel org by using this IDP
3) Set the IDP as "not available"
4) See event log to see how it gets automatically removed 

### Screenshots

Event log example
```
   {
      "editor": {
        "userId": "someid",
        "displayName": "somename",
        "service": "Admin-API"
      },
      "aggregate": {
        "id": "someid",
        "type": {
          "type": "user",
          "localized": {
            "key": "AggregateTypes.user",
            "localizedMessage": "User"
          }
        },
        "resourceOwner": "someresourceid"
      },
      "sequence": "6258",
      "creationDate": "2023-05-31T15:13:45.412200Z",
      "payload": {
        "idpConfigId": "someid",
        "userId": "someid"
      },
      "type": {
        "type": "user.human.externalidp.cascade.removed",
        "localized": {
          "key": "EventTypes.user.human.externalidp.cascade.removed",
          "localizedMessage": "External IDP cascade removed"
        }
      }
    },
```

### Expected behavior

By "disabling" the IDP I would expect it to be removed from the options for users to access the resources, and, after some time being able to enable it again allowing users that have already created a record with it being able to use it without even noticing a change.

I believe this should be considered a bug or at least notify the admin-user (in cloud console) about the consequences of current implementation by disabling the IDP . 

### Operating System

N/A

### Relevant Configuration

<img width="758" alt="image" src="https://github.com/zitadel/zitadel/assets/63676303/6ab6e104-9c30-494d-82bc-f0de6cff4894">
<img width="325" alt="image" src="https://github.com/zitadel/zitadel/assets/63676303/65fa726d-2d6b-4898-b917-449d36524517">

### Additional Context

N/A

**Comment by hifabienne** [comment]
Hei @lukasver 
Yes, at the moment this behaviour is intended, when you set it as not available the provider is removed from the organization. At that point we also remove all the links on the users as they should not be able to login anymore.
I think the labeling "avaiable"/"not avaiable" is miss. leading at the moment.
We will check if there should be i a change, and how it should work.

@peintnermax Would it make sense to change the labeling? And maybe ad a popup, that this results in the removing from all users?

**Comment by lukasver** [comment]
Hi @hifabienne ! Thanks for the reply!.

I would suggest to add a confirmation modal to avoid unwanted behaviour (in my case was a missclick that ended up affecting lots of users 😓) since the outcome has some "hidden" destructive action.

**Comment by peintnermax** [comment]
https://github.com/zitadel/zitadel/pull/6004 shows a warning if the idp is removed. This should improve the UX
