### ISSUE TITLE
[Bug]: Main page won't load when local OS language is not supported

### ISSUE THREAD

**Issue by alexbatashev** [zitadel/zitadel#5970]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.28.0

### Describe the problem caused by this bug

Zitadel seems to try to load non-existing languages. My system language is set to Russian. When I try to open https://auth.example.com/ui/control a blank page appears. Changing system or browser language to English fixes the issue. Below is a sample of console output.

<img width="780" alt="Снимок экрана 2023-06-03 в 18 49 32" src="https://github.com/zitadel/zitadel/assets/829678/d76ad279-89c8-4166-9445-500fce2728d4">

### To reproduce

1. Open browser settings.
2. Change primary language to any unsupported language (e.g., Russian)
3. Go to main Zitadel page (i.e., `/ui/console`)

### Expected behavior

Whenever a user language is not available, Zitadel default language is used.

**Comment by hifabienne** [comment]
Thanks @alexbatashev for reporting.
We will have a look at it.
