### ISSUE TITLE
[Bug]: Domain validation dialog has incorrect instructions

### ISSUE THREAD

**Issue by kraney** [zitadel/zitadel#6005]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.28.1

### Describe the problem caused by this bug

When adding a domain to an organization, and choosing the HTTP option, the dialog instructions say to place the validation file at https://<stuff>.txt.

But in actuality when you click "Validate", what's requested is https://<stuff> (i.e. without the .txt extension.)

If you follow the instructions as written, the validation will fail because the URL without the .txt extension will return 404. The error message provides no clue as to what the failure was, nor does any explanation appear in the event logs. I was able to determine the issue by looking at zitadel source code and then at my web server logs.

### To reproduce

1. For an organization, under domains, click "New"
2. Enter a domain with a web server you can control
3. Select HTTP as the validation method
4. Carefully follow the instructions including the full path, file extension included
5. Click "Validate"

### Expected behavior

1. The URL shown in the dialog should match what is used in the actual request
2. The error message when validation fails should provide some indication what the failure was that can help resolve the issue.

### Operating System

Environment: Kubernetes self-hosted

### Relevant Configuration

Nothing special

**Comment by hifabienne** [comment]
Thanks @kraney for reporting.
We decided to change the backend check, that it works with the txt.
