### ISSUE TITLE
On Demand Key Rotation and Revocation

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#6021]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

As an administrator of a self-hosted zitadel instance I would like to have a way to force a key rotation and revocation of public keys.

Given the use case where I configure zitadel to use the same key for 100 years, I will need the ability to force a rotation and revocation when I believe I have been compromised.  

### Describe your ideal solution

Both an API and  via the console would be nice to have.

### Version

all

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hei @ghstahl 
Thanks for the report.
Thanks for sharing your idea.
We appreciate your input and we beliebe it’s a valuable suggestion. We currently do not have an ETA for the implementation, but we keep you updated on the issue.

**Comment by fforootd** [comment]
I think this would be a valuable improvement since it gives people more control over how they want to create new key material.

We should have a thought for "pre-publishing" keys as we touch this, otherwise we might need to extend the API in dirty ways.

So IMO this relates to #5690

**Comment by hifabienne** [comment]
@muhlemmer @livio-a  I think we can close this as we implemented the new key management, is that right? https://github.com/zitadel/zitadel/pull/8508

**Comment by muhlemmer** [comment]
Yes, implemented in above PR and tracked by https://github.com/zitadel/zitadel/issues/7809
