### ISSUE TITLE
Storing the user agent on the session

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6028]
As a developer I want to be able to store the user agent of a user on the session. This gives me the possibility to show a list of sessions on a user detail and I can remove all sessions from a specific user agent.
Example: I lost my mobile phone and want to terminate all the sessions from that device. 

**Acceptance Criteria**
- [ ] I can save a user agent on a login session with an ID, Browser, Device, OS and IP, location?
- [ ] Request Headers
- [ ] Do we need more attibutes? All request headers?
- [ ] Extend search sessions with user agent filter 

**Additional Information**
This also gives ZITADEL the possibility to make thread detection based on ips, location. When the location changes  in a short time.

**Comment by hifabienne** [comment]
@peintnermax Can you add the information that are possible to get in the acceptance criteria?

**Comment by hifabienne** [comment]
Please write in this issue how much time the specific parts took:
- Extend Session: ...
- Extend Search: ...
- Testing: ...
- Review: ...
- Fix Review: ...

**Comment by muhlemmer** [comment]
> I'd structure the object like nextjs helpers provide them:
> 
> * isBot: `boolean`;
> * browser
>   
>   * name: `string | undefined`
>   * version: `string | undefined`
> * device
>   
>   * model: `string | undefined`
>   * type: `string | undefined`
>   * vendor: `string | undefined`
> * engine
>   
>   * name: `string | undefined`
>   * version: `string | undefined`
> * os
>   
>   * name: `string | undefined`
>   * version: `string | undefined`
> * cpu
>   
>   * architecture: `string | undefined`
>   
>   reference https://nextjs.org/docs/pages/api-reference/functions/next-server#useragent

@peintnermax, @hifabienne  From the above schema, what field(s) would you implement the search functionality on? For example. search on `cpu.architecture = arm64` doesn't make much sense.

Currently we use fingerprinting by means of a secure cookie. It would work if we add something like a fingerprint in the request, so that we can uniquely identify a browser/device and use that for session termination.

**Comment by muhlemmer** [comment]
In that case we should treat the user agent details as a separate resource, as there can be multiple sessions on a user agent it needs also a separate aggregate.

The logic would look like:

![user agent id](https://github.com/zitadel/zitadel/assets/5411563/f95522a7-2529-4ba3-88a4-ccc590cabfaf)

This assumes that the login server is capable off signing and verifying cookies, probably using symmetric cryptography and a master key set in the environment. (much like the current masterkey setting for zitadel back-end). An alternative would be to push this logic to the API, where the singed ID is just passed as-is.

**Comment by hifabienne** [comment]
Can we not let the front end do this?
As the data is anyway optional from backend perspective, as only the frontend can fill it.

**Comment by muhlemmer** [comment]
As just discussed, we will create a new sub-message for the session containing:

- fingerprint id
- IP address
- description (can be the user agent string or any other identifier)
