### ISSUE TITLE
Extend search user sessions

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6029]
As a developer I want to be able to show all sessions of a user on his profile, so he is able to terminate certain sessions that are not used anymore. 

**Acceptance Criteria**
- [x] I can Search Sessions with a user id filter
- [x] I can filter the sessions per creation date
- [x] I can order the sessions per creation date

**Comment by sp132** [comment]
I can take it on. Would you be willing to accept a PR for this?

**Comment by hifabienne** [comment]
hei @sp132 
Yes that would be great
