### ISSUE TITLE
[Bug]: Loop redirect if single IdP return error

### ISSUE THREAD

**Issue by megge-dream** [zitadel/zitadel#6033]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.27.1

### Describe the problem caused by this bug

I created single Identity Provider for my Zitadel organization and disabled "Username Password allowed" option. Now when I'm trying to log in via IdP and its return error for some reason, instead of login page with error message Zitadel redirect back to IdP, its return same error, and Zitadel redirect to IdP again, and this loop is infinite.

If I have several Identity Providers for one organization, I see login page with error message from IdP without any problem.

### To reproduce

1. Create Identity Provider with incorrect setting
2. Go to login page
3. See internal redirect between Zitadel and IdP

### Screenshots

<img width="992" alt="IdentityProviders" src="https://github.com/zitadel/zitadel/assets/5994161/5b14f818-e0e3-4a1d-9fec-101e016ddf0c">
<img width="454" alt="LoginBehaviorandSecurity" src="https://github.com/zitadel/zitadel/assets/5994161/86cd6d5d-5c74-4312-a3eb-49a296b71935">

### Expected behavior

In case of error from IdP Zitadel shows login page with error message.

### Additional Context

I checked code and saw this strange logic:
https://github.com/zitadel/zitadel/blob/main/internal/api/ui/login/login_handler.go#L98
Looks like Zitadel need to check `errID` and `errMessage` before calling `handleIDP`

**Comment by hifabienne** [comment]
Hei @megge-dream 
Thanks for reporting the bug. We will have a lookt at it.

**Comment by vs-gtadeu** [comment]
FYI - I encountered this problem today with a SAML IDP. The organization had the username and password login disabled while a misconfiguration on the IDP side (JumpCloud) was causing an error after the IDP returned to Zitadel.

Here is a video of the issue:

[Screencast from 23-04-2024 14:15:58.webm](https://github.com/zitadel/zitadel/assets/62257776/3fea4eb3-f1a2-4e87-9092-cbb87a7103cb)
