### ISSUE TITLE
Zitadel client id type

### ISSUE THREAD

**Issue by graforlock** [zitadel/zitadel#6041]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

Hello

I simply cannot find anywhere what is the id type, is it bigint / bigserial? What is the type?

Additionally, there is no mention how it is randomised (algorithm).

### Additional Context

Would also join ZITADEL chat but invite isn't working–it's crashing at the moment.

**Comment by hifabienne** [comment]
Hei @graforlock 
Our ids are stored as strings and are generated with sonyflake its an id generator inspired by twitters snowflake.

**Comment by graforlock** [comment]
Thank you for information @hifabienne, I think it's important to include this info in the docs!
