### ISSUE TITLE
Session API: SAML Create Session

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6053]
As a developer I am able to create an SAML session, so I can build my own login on top of ZITADEL.

**Acceptance Criteria**
- [ ] SAML Endpoints are implemented as in the current version
- [ ] Endpoint: SAML metadata
- [ ] Endpoint: certificate
- [ ] Endpoint: sso
- [ ] Logout
- [ ] Testing

**Additional Information**
- Separat Auth Request for SAML
- Integration into session of the SAML Auth Request

**Comment by hifabienne** [comment]
@muhlemmer @livio-a is it possible to break that down? to not have an issue with 6 points?

**Comment by livio-a** [comment]
Frontend including proxy handling needs to be solved as well

**Comment by muhlemmer** [comment]
@stebenz please note that we also need to add the new SAML session events to the events API examples. I added a TODO in PR #9020 :

https://github.com/zitadel/zitadel/blob/274fd2db1de8bab00cc4400a548ba79ef1b08f4f/docs/docs/guides/integrate/zitadel-apis/event-api.md?plain=1#L145-L150
