### ISSUE TITLE
console: SMTP trigger test mail

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#6077]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

As a user I want to send a test mail from the SMTP settings. This should improve debugging and increase velocity in setting up an instance.

### Describe your ideal solution

Implement a TEST button to trigger a mail.

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hei @peintnermax 
We already have an issue for that. Due to this I will close this.
https://github.com/zitadel/zitadel/issues/4504
