### ISSUE TITLE
Clean UI for unprivileged user

### ISSUE THREAD

**Issue by kraney** [zitadel/zitadel#6082]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

In production I expect the vast majority of users to have no memberships in Zitadel, only grants to various apps. When they are brought to the Zitadel UI, for example to change their own password, I would prefer to avoid tempting them with controls that are not useful or available to them.

To be specific
* Under General, I can edit my email. For an account created from an external IdP, I would like to prevent users from making their email diverge from the IdP email.
* Under Password and Security, when username / password login is disabled for the organization
  * I do not want to see the panel to edit password.
  * I should not be able to set passwordless authentication method is passwordless is not allowed. Also if login is via external IdP only, I believe passwordless is _effectively_ disallowed, even if that config item still says it is.
* I'm not sure I even need to view Identity Providers, but if the view is shown, it should not offer a "delete".
* For Authorizations, I should not see "New" or delete buttons if I do not have the privileges to make these changes. (Clicking "New" does nothing. Clicking delete returns an error.)
* Possibly the Memberships panel should not be offered to users who have zero memberships; there's nothing to view.
* The "Last Changes" area, while potentially useful, uses technical terms like "Access token created" that may be opaque to a nontechnical user.
* The link to Zitadel documentation should be optional, or have a configurable destination. Zitadel Docs are not targeted to a nontechnical user and expose internal implementation details

### Describe your ideal solution

As an unprivileged user, I want to not be confused by being presented features I cannot access or technical detail that is not relevant for my role.

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hei @kraney 
Thanks for opening up the discussion.
Generally we try to implement a default management UI, that can be used by everyone. If you have other needs than that or you need more customization we recommend building you own Profile Page for your users and using our APIs.
However, there is already an issue for your requested improvement, about customizing the profile page: https://github.com/zitadel/zitadel/issues/3965
Therefore I will mark this as duplicate and close it.
