### ISSUE TITLE
One time code as second factor

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6100]
As a administrator I want to enable my users to have a one time code as second factor, that is sent (by someone) to the user and they have to enter as a second step, so the accounts are more secure than only using password.

**Acceptance Criteria**
- [ ] I am able to use one time code as a second factor
- [ ] I am able to configure on an instance and organization if one time code as second factor is possible
- [ ] I am able to send on the request if the code should be sent by ZITADEL per email, or if I want to get the code back in the response, so I can send it myself

**Comment by binaryfire** [comment]
Just wanted to add my support for this! In particular, email codes for 2FA. It's what Slack, Microsoft and many other big companies use for "default" MFA when a user hasn't enabled TOTP MFA. Consumers are already very comfortable with this flow.

I understand email MFA might not be the right choice for financial institutions etc. but they're the best option for B2C platforms that want to enforce MFA by default. It's the only option regular consumers aren't annoyed by.

PS. Some people recommend Magic Links as an alternative but we've had users express their dislike for them in the past. People prefer to get MFA codes on their phones when logging into desktop apps and Magic Links make that UX impossible.

**Comment by hifabienne** [comment]
Will close this issue, as we have implemented email and sms as second factor.
