### ISSUE TITLE
[Bug]: Console won't load when browser language is set to Portugese (Brazil) 

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6104]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.29.1

### Describe the problem caused by this bug

Given Chrome is set to preferred language pt-BR, when I call the Console, then I see a white sceen and the browser console reports `ERROR Error: Cannot find module './pt.json'`

### To reproduce

1. chrome://settings/languages
2. Add Portuguese (Brazil) and move to the top
3. Load Console at $DOMAIN/ui/console/
4. Inspect Browser console

### Expected behavior

Console to load normally.

### Operating System

- MacOS
- Chrome

### Additional Context

Support case. Workaround is to change the preferred language to English (United States).

**Comment by livio-a** [comment]
closed with #5999

(now released in 2.29.2)
