### ISSUE TITLE
Show some basic information when running `start-from-init`

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6113]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When starting ZITADEL following the [docker compose guide](https://zitadel.com/docs/self-hosting/deploy/compose), I'm sometimes not sure if the right version was applied (uses latest). Also when changing external domains etc, I might not be able to access the Console as described in our docs.
It would be helpful to post some basic information to stdout so the user gets some basic properties and urls.

### Describe your ideal solution

It would be great to get some basic information and urls at startup, so I don't have to figure them out on my own. These could include: 

- Version
- url to console
- url to check healthz
- Security notice (eg, using tlsMode disabled)

### Version

2.29.0

### Environment

Self-hosted

### Additional Context

When using ZITADEL in combination with cockroachdb, then I get the crdb output at startup, which shows me some basic information and warnings that seem helpful.

**Comment by doncicuto** [comment]
Hi @mffap, how about this?

![zitadel_basic_info](https://github.com/zitadel/zitadel/assets/30386061/8c1292ee-a0ea-49ad-815d-c9a8b70fb421)

When showing the URLs, I can offer the port and if the url is http or https (based on tls/external secure) but can't provide hostname or IP address.

**Comment by fforootd** [comment]
> Hi @mffap, how about this?
> 
> ![zitadel_basic_info](https://user-images.githubusercontent.com/30386061/251237973-351fd7ba-e695-4d3f-bfb6-41304f159232.png)
> 
> The URL is created using the ExternalDomain and ExternalPort from the configuration.

Uh I would love to see this! 🚀

**Comment by mffap** [comment]
> Hi @mffap, how about this?
> 
> ![zitadel_basic_info](https://user-images.githubusercontent.com/30386061/251237973-351fd7ba-e695-4d3f-bfb6-41304f159232.png)
> 
> The URL is created using the ExternalDomain and ExternalPort from the configuration.

That looks even better than I've imagined 😊

The two flags are spot on. Will new users understand the risk involved? 

I'm a fan of giving some recommendations (eg, running with insecure configuration, check the production setup guide: https://zitadel.com/docs/self-hosting/manage/production). But for me also fine to roll with it as is for a start!

Thanks for the work! As always, much appreciated

**Comment by doncicuto** [comment]
Glad you like it 😄 @mffap and @fforootd 

I agree @mffap the more help we provide the better, so let me prepare those texts and will submit them to you for reviewing

If you don't mind I can also use some colors in the console 😃

**Comment by fforootd** [comment]
> If you don't mind I can also use some colors in the console 😃

No worries, go ahead

**Comment by doncicuto** [comment]
@mffap and @fforootd how about this new look?:

![image](https://github.com/zitadel/zitadel/assets/30386061/04c217e5-832e-490b-a01c-cde4a084f641)
