### ISSUE TITLE
[Bug]: management-service-add-oidc-app example data doesn't work

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6121]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.29.1

### Describe the problem caused by this bug

When calling the api with the data provided in the example, the call returns `Application invalid (PROJECT-1n8df)`. 

### To reproduce

Execute the example

### Expected behavior

Create a valid app from the example

### Relevant Configuration

Call

```bash
curl -L -X POST $DOMAIN/management/v1/projects/$PROJECT/apps/oidc \
--data "@create-oidc-app.json" -s \
-H "Authorization: Bearer $TOKEN" \
-H "x-zitadel-orgid: $ORG" \
-H 'Content-Type: application/json' 
```

create-oidc-app.json

```json
{
  "name": "MyOIDCApp",
  "redirectUris": [
    "http://localhost:4200/auth/callback"
  ],
  "responseTypes": [
    "OIDC_RESPONSE_TYPE_CODE"
  ],
  "grantTypes": [
    "OIDC_GRANT_TYPE_AUTHORIZATION_CODE"
  ],
  "appType": "OIDC_APP_TYPE_WEB",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_BASIC",
  "postLogoutRedirectUris": [
    "http://localhost:4200/signedout"
  ],
  "version": "OIDC_VERSION_1_0",
  "devMode": true,
  "accessTokenType": "OIDC_TOKEN_TYPE_BEARER",
  "accessTokenRoleAssertion": true,
  "idTokenRoleAssertion": true,
  "idTokenUserinfoAssertion": true,
  "clockSkew": "1s",
  "additionalOrigins": [
    "https://console.zitadel.ch/auth/callback"
  ],
  "skipNativeAppSuccessPage": true
}
```

### Additional Context

Workaround: When omitting `additionalOrigins` it works as expected.

**Comment by hifabienne** [comment]
@mffap Can you please link the example you used?

**Comment by mffap** [comment]
@hifabienne ah yes, sorry. Forgot to post the link: https://zitadel.com/docs/apis/resources/mgmt/management-service-add-oidc-app#create-application-oidc

Took the curl example from there. I think only the docs are wrong, call itself works without the additionalOrigin
