### ISSUE TITLE
[Bug]: Surname and Last Name

### ISSUE THREAD

**Issue by yaneony** [zitadel/zitadel#6137]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

There is difference in two forms, when registering as user (left) and create user as administrator:

### To reproduce

See screenshot.

### Screenshots

![GVG499J2](https://github.com/zitadel/zitadel/assets/12472001/e49bbd53-43cb-42b1-b1cc-9f1fe9836497)

**Comment by yaneony** [comment]
I think "First name" and "Last name" do look more consistent than "Surname".

**Comment by mffap** [comment]
Should be consistent

> I think "First name" and "Last name" do look more consistent than "Surname".

Surname or Family Name would be clearer. Some cultures have different naming conventions where the family name is in front and then followed by the given name. I think family name is wildly used in the identity world.

**Comment by yaneony** [comment]
Yeah, at least it should be consistent between both UIs.
