### ISSUE TITLE
[Bug]: Min height in dropdowns

### ISSUE THREAD

**Issue by yaneony** [zitadel/zitadel#6140]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

Min height in one-item menus look strange. Removing min-height fix the issue.

### To reproduce

See screenshot.

### Screenshots

![9LMMBXN7](https://github.com/zitadel/zitadel/assets/12472001/505bd0a7-5f88-4a42-b219-65125d4e69fe)

**Comment by hifabienne** [comment]
Hei @yaneony 
Thanks for the report.
It is currently not high in priority, but we will have a look at it, when we have time.
In the mean time, we also accept PRs from our community, if you would like to contribute.

**Comment by ARSHIL1804** [comment]
Hello, Can I work on this?

**Comment by fforootd** [comment]
> Hello, Can I work on this?

Yeah sure, let us know if you need any help.

Appreciate any PR 😁
