### ISSUE TITLE
[Bug]: Show user in Authorizations produce error

### ISSUE THREAD

**Issue by yaneony** [zitadel/zitadel#6141]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

When one user from ORG1 added to Authorizations in ORG2 showing user info produce "No associated user."

**ADD: I'm not sure, but user "TEST" is user from ORG2, why in the tabled it's being displayer as "ORG1"? It makes no sense beucase I'm already within ORG1 and this user is originally from ORG2.**

### To reproduce

1. Create ORG1
2. Create ORG2
3. Add some user to ORG1
4. Go to ORG2 Authorizations
5. Add user from ORG1
6. Click "show user..." for newly created user.

### Screenshots

![75LJ5O5A](https://github.com/zitadel/zitadel/assets/12472001/4ecf90e2-485e-45bc-8d21-a18700e172ad)

**Comment by mffap** [comment]
similar to https://github.com/zitadel/zitadel/issues/4531

**Comment by hifabienne** [comment]
This issue has been fixed. It now shows a nice message that you can't have a look at the user. 
Will close it.


![Image](https://github.com/zitadel/zitadel/assets/38692350/fab4b14c-8695-432f-aac1-a8d87aa78b15)
