### ISSUE TITLE
[Bug]: Disable registration for default organization still show button and form

### ISSUE THREAD

**Issue by yaneony** [zitadel/zitadel#6142]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

When you disable registration for main ORG and visiting the Console URL (your Zitadel instance), Register button is still displayed and register form is shown, where it makes no little sense when after filling it out it say "Registration is not allowed". Why not to disable/remove both, form and button in this case?

### To reproduce

See description and screenshot.

### Screenshots

![O5DKE593](https://github.com/zitadel/zitadel/assets/12472001/d3f27ef1-65aa-442d-b32a-afbef0b63834)
![V43VA5EL](https://github.com/zitadel/zitadel/assets/12472001/b065ab4a-710f-49fe-bb73-c141055339b8)

**Comment by hifabienne** [comment]
Hei @yaneony 
Thanks for your report.
When going to the login/registration without giving the scope of an organization, ZITADEL shows what is configured per default on the instance. Can you try if this works?
If you configure that the registration is not allowed on the instance configuration you should not see the button anymore.
We are aware that this is missleading, when the users are anyway registered to the default organization.

**Comment by hifabienne** [comment]
Will close this issue, as the problem can be solved, by configuring the instance settigns
