### ISSUE TITLE
Change instance domain or set CNAME

### ISSUE THREAD

**Issue by rhizoet** [zitadel/zitadel#6144]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

We have currently installed Zitadel with the domain `auth.example.com`. Now we want to change it to `login.example.com`.

We use the Helm chart and there is a configuration option `ExternalDomain`. Can I easily customize this so that the domains of the organizations are also customized? So that no more domains with `auth.example.com` appear anywhere?

Or how could I alternatively set a CNAME so that the application can be called via it? Is it possible to set multiple `ExternalDomain`s somehow?

### Describe your ideal solution

As a system administrator, I would like to be able to change the entire domains. This way you don't have to rebuild the whole system if you decide that the domain name doesn't fit later or you change your name or something like that.

### Version

2.28.1

### Environment

Self-hosted

### Additional Context

We use the helm chart in Version 5.0.0 with CockroachDB Helm 11.0.3

**Comment by fforootd** [comment]
Hm I think we allow changing the domain although it might have some side effects when old mails would be sent or something similar.

@adlerhurst I think you know more details about this

Lets document this once we are sure what the behavior is 😁

**Comment by hifabienne** [comment]
Hei @rhizoet 
I just saw that you are running still ZITADEL version 1. That is outdated since more than a year.
So not completely sure what happens if you change it.
If you only change the ZITADEL_ACCOUNTS env var it should work. If you change the default domain, at least the webauthn will not work anymore, as this is domain bound.

I suggest that you try it on a dev system first, just to make sure you don't break your production.

On a general note, you should consider migrating to ZITADEL v2, as we do not support and develop v1 anymore.

**Comment by rhizoet** [comment]
Hy @hifabienne 
sorry, that was just a typo. I mean version 2.28.1 as this is the version in the helm chart version 5.0.0.

**Comment by eliobischof** [comment]
Sorry for the late response @rhizoet.

You can change your ExternalDomain. When you run the setup job with the new ExternalDomain, zitadel setup adds a new domain to the instance. https://zitadel.com/docs/self-hosting/manage/custom-domain#changing-externaldomain-externalport-or-externalsecure

If you want, you can clean up the old domain using the system API https://zitadel.com/docs/apis/resources/system/system-service-remove-domain#removes-the-domain-of-an-instance

Does this answer your questions?

**Comment by rhizoet** [comment]
Thanks for respond. That helps me a lot.
