### ISSUE TITLE
Support email OTP

### ISSUE THREAD

**Issue by binaryfire** [zitadel/zitadel#6145]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Hi guys!

Are there any plans to support email OTP in the near future? I'm referring to 6-digit OTP codes, not Magic Links. We've had lot of people express dislike for Magic Links, mainly because people prefer to get OTP codes from their phones when logging into desktop apps. Magic Links make that UX impossible.

Also, Magic Links don't play nicely with PWAs. Even Apple mentions it in their recent announcement about Web App (PWA) support and suggests both email OTPS and Passkeys as 2 alternatives. See timestamp 7:35: [https://developer.apple.com/videos/play/wwdc2023/10120/](https://developer.apple.com/videos/play/wwdc2023/10120/). Unfortunately Passkeys aren't an option for everyone due to compatibility reasons.

### Describe your ideal solution

I understand email OTPs might not be the right choice for things like financial institutions but they're the best all-round option for B2C platforms that want to enforce 2FA by default. The only "enforced" 2FA regular consumers aren't annoyed by is email-based.

We really wanted to use Zitadel for our SaaS but we're probably going with our framework's built-in auth instead for this reason. But I thought I'd check just in case this was on the horizon for Zitadel.

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hei @binaryfire 
There is already an issue for this: https://github.com/zitadel/zitadel/issues/6099
Its about having one time code for authentication. email would just be one channel, sms could be another.

There is no ETA yet, but it is in the product backlog. We generally prioritize based on the customer and community requests. So if you would like to see it implemented please upvote or comment on the issue.

I will close this issue here to avoid duplicates

**Comment by binaryfire** [comment]
Hi @hifabienne. Great, thanks! I'll follow there.

**Comment by binaryfire** [comment]
Hi @hifabienne. It seems the issue you linked is related to OTP as an alternative login method. I was referring to email codes for MFA (i.e. after users have correctly entered their username and password, they are emailed a 6-digit code). It's what Slack, Microsoft etc. use for "default" MFA when a user hasn't enabled TOTP MFA.

Sorry, I wasn't very clear in my comments above! Are there any plans to add this to Zitadel? Consumers are already quite used to this flow because many of the big companies use it.

**Comment by hifabienne** [comment]
Hei @binaryfire 
Thanks for the clarification. There is also an issue for that, I could have linked both already before. 
So this is about the One time code as a second factor: https://github.com/zitadel/zitadel/issues/6100
In regard of ETA and time line, its the same as with the issue mentioned above.
So please add your comment/upvote there.
