### ISSUE TITLE
Extend User Profile with SMS Factor

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6207]
As an end user I am able to setup my phone number as a second factor for my account.

**Acceptance Criteria**
- [x] I am able to add a new Second Factor with Phone number
- [x] When Phone number is already verified I can directly add it
- [x] When Phone number is not verified I have to add and verify it, and then it is added as second factor
- [x] When removing a phone number that I have setuped as second factor I want a warning that I can't use it as second factor anymore
- [x] When adding a new phone number I want a field to enable it as second factor directly, when enabled, the second factor phone is enabled also
- [ ] Integration tests

**Additional Information**
When bool to add as second factor is enabled flow is:
- Add phone
- Verify Phone --> return ok
- Enable as second factor

**Comment by eliobischof** [comment]
Add second factor SMS on instance setup (incomment one LoC added in #6260)

**Comment by peintnermax** [comment]
`When Phone number is not verified I have to add and verify it, and then it is added as second factor`

will show a warning that the phone number has to be added on the corresponding account, and not automatically guide threw adding as this adds more unnecessary complexity. The part where the number can be selected as second factor directly on adding should be enough to simplify the process.
