### ISSUE TITLE
[Bug]: Cannot set user status + verified email

### ISSUE THREAD

**Issue by MichalNemec** [zitadel/zitadel#6209]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

Docker 81d82cbcbaefcc9be02c2c9a05ccee55e5eabc58f26c9eeb82d2c936cc9448f9

### Describe the problem caused by this bug

I created user in admin panel and i cant set dummy email and set it as verified, the save with making status active. The only button in actions is delete user.

It doesnt work even on this page: http://localhost:8080/ui/console/users?type=human
When i select used and click activate.

EDIT: Deleting user and recreating it again now works.

### To reproduce

1. spin up docker-compose from https://raw.githubusercontent.com/zitadel/zitadel/main/docs/docs/self-hosting/deploy/docker-compose.yaml
2. follow setup
3. create user
4. try to set email verified + password
5. see missing features.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5663019/18ba3efa-6cfa-42ca-8ff5-0dfb50141c3e)

### Expected behavior

See buttons to manipulate user.

### Operating System

OS: MacOS m1 13.4.1 (22F82)

**Comment by hifabienne** [comment]
Hei @MichalNemec 
When creating a new user, you can directly set the email as verified and set an initial password, in that case, ZITADEL will not send an initial mail to the user:

<img width="832" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/fa6eec5c-7f5e-45a0-a695-ecc27c22d374">

**Comment by MichalNemec** [comment]
Yes, i know about that, but when i was creating the user this way, then email was verified but i could not activate the user, screenshot still applied. When i deleted the user and created it again, then it worked normally. Maybe some anomaly.

**Comment by hifabienne** [comment]
> Yes, i know about that, but when i was creating the user this way, then email was verified but i could not activate the user, screenshot still applied. When i deleted the user and created it again, then it worked normally. Maybe some anomaly.

I am not sure what you mean, when I create the user with email verified checked, as well as set initial password checked, and then adding an initial password. The user is created and the state is activated. Can you explain, what you did differently?

**Comment by MichalNemec** [comment]
i did it exactly the same, but the state was initital and there was no way to set it to active. Maybe it was some setting or something, because i was exploring zitadel for the first time, maybe i clicked on something. 

result is:
i deleted the user, created another one, is automatically set as active and it works as intended

**Comment by hifabienne** [comment]
Great to hear that it works now.
