### ISSUE TITLE
[Improvement] Post update user hook

### ISSUE THREAD

**Issue by MichalNemec** [zitadel/zitadel#6212]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I would like to access event when i.e. name is changed, email verified, avatar uploaded in action, so that i can do api call to further work with the data.  I dont see any way of doing it right now.

### Describe your ideal solution

Pre / post hook to almost everything. In this usecase:
Post update user data, my main interest is avatar, all names

action then can do api call to check profanity in images and names and do replace it with *** and remove avatar + email notifying about profanity.

### Version

ghcr.io/zitadel/zitadel:846ddd4ee47545dc87c9620853c11f9900e4fe3a

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hei @MichalNemec 
We do have something called Actions. That allows you to write javascript action and run it on specific triggers.
At the moment this is only implemented in the login / register.
But we already have plans to extend it, so you can trigger on all api requests and after each event. 
https://github.com/zitadel/zitadel/issues/5101

**Comment by MichalNemec** [comment]
Is there any plan to have roadmap or timeframe? Because we are heavily relying on post user update. As i mentioned on discord issue, we moved from keycloak because we didnt want to do java hooks for this, actions in zitadel are much easier and are adjustable quickly.

**Comment by hifabienne** [comment]
> Is there any plan to have roadmap or timeframe? Because we are heavily relying on post user update (updated infrastructure). As i mentioned on discord issue, we moved from keycloak because we didnt want to do java hooks for this, actions in zitadel are much easier and are adjustable quickly.

The plan is to start the implementation by end of this quarter, but will probably take some time till we can finish.

**Comment by hifabienne** [comment]
I will close this issue, as it is included in the issue above, to avoid duplicates
--> https://github.com/zitadel/zitadel/issues/5101
