### ISSUE TITLE
[Bug]: Console favicon

### ISSUE THREAD

**Issue by MichalNemec** [zitadel/zitadel#6213]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

Docker 81d82cbcbaefcc9be02c2c9a05ccee55e5eabc58f26c9eeb82d2c936cc9448f9

### Describe the problem caused by this bug

I have uploaded Logo and icon in branding, but favicon in console is still the same.

Whenever im on login page, i see correct favicon.
Logged in in console i see icon which shows correctly next to orgs name.
Favicon is not set.

### To reproduce

1) Spin up docker instance with cockroachDB (basic docker-compose in documentation)
2) upload PNG images
3) see results

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5663019/eb233132-494c-4950-ac34-4d7a04539d0c)

### Expected behavior

Icon should react to favicon
OR
new field to upload favicon.

### Operating System

M1 MacOS 13.4.1 (22F82)

### Relevant Configuration

all default

**Comment by hifabienne** [comment]
Hei @MichalNemec 
Thanks for your report.
You are right, at the moment we only load the favicon on the login page but not in the console.
I will add the bug to our bug fixing day. We do have a look at those issues one day in each sprint, and will fix as many as possible.

**Comment by MichalNemec** [comment]
Is there a possibility of changing head title also?

Because if customer is on login page they see welcome back! title then password title and upon logging in they see Zitadel console and their user data. It can be a bit confusing if we follow specific branding and if you have multiple tabs open, it doesnt click straight away, that this tab is the auth system.

**Comment by hifabienne** [comment]
> Is there a possibility of changing head title also?
> 
> Because if customer is on login page they see welcome back! title then password title and upon logging in they see Zitadel console and their user data. It can be a bit confusing if we follow specific branding and if you have multiple tabs open, it doesnt click straight away, that this tab is the auth system.

You can change the texts of the login in the settings of the instance or a specific organization. https://zitadel.com/docs/guides/manage/console/instance-settings#login-interface-texts

**Comment by MichalNemec** [comment]
This is what i meant.
`<title>ZITADEL • Console</title>` is not in the login interface texts and not in message texts.

**Comment by hifabienne** [comment]
@max

> This is what i meant. `<title>ZITADEL • Console</title>` is not in the login interface texts and not in message texts.

@peintnermax can you give an answer to this?

**Comment by iFrozenPhoenix** [comment]
@hifabienne could you eventually ask again one of your colleagues if the title can be changed somehow?

**Comment by peintnermax** [comment]
> Is there a possibility of changing head title also?
> 
> Because if customer is on login page they see welcome back! title then password title and upon logging in they see Zitadel console and their user data. It can be a bit confusing if we follow specific branding and if you have multiple tabs open, it doesnt click straight away, that this tab is the auth system.

Hi @iFrozenPhoenix, generally we recommend you build your own customer facing UI. Changing the title in the console would require us to add texts in the settings, which currently do not exists. Setting title and favicon on runtime woult be no problem  then 👍

**Comment by hifabienne** [comment]
Would it be ok, if we just remove the ZITADEL from the title, so its just written Console?

**Comment by iFrozenPhoenix** [comment]
Yes this would be ok for my usecase.

Mit freundlichen Grüßen / Kind regards
________________________________

**Comment by doncicuto** [comment]
@iFrozenPhoenix and @MichalNemec, IMHO would you mind opening a different issue requesting the change of Zitadel - Console title? that way we could have separate issues that could be assigned for other prospect contributors.

@hifabienne could you assing this favicon issue to me?
