### ISSUE TITLE
Change "@" character in client_id for new applications

### ISSUE THREAD

**Issue by JanKaul** [zitadel/zitadel#6222]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

The client_id for applications created in Zitadel is of the form "id@project". For OIDC id tokens, this client_id has to be added to the "aud" claim. The "aud" claim of an OIDC id token specifies which clients should accept this token.

When trying to register Zitadel as an [identity provider for AWS IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html#manage-oidc-provider-console) the client_id has to be specified as an "Audience". Here AWS doesn't allow the "@" character which prohibits the use of zitadel with AWS IAM.

### Describe your ideal solution

Substitute the "@" with an alternative character (:-_./) for new applications created in Zitadel.

If only new applications are affected this shouldn't interfere with any existing applications.

### Version

2.28

### Environment

Self-hosted

**Comment by fforootd** [comment]
Personal take here.

But I see it as improvement if we represent the clientID the same way all ids are built with zitadel.

I think this helps reduce mental overhead and decreases problems in integrations.

**Comment by JanKaul** [comment]
That's a good point and totally understandable if that has priority. I just wanted to share that for my use case and all other users that want to use AWS IAM, it would be really helpful to not use the "@" character.

I made a quick grep on the codebase and I couldn't find other occurrences of the "id@project" pattern except for the clientID. Which ids did you have in mind?

**Comment by fforootd** [comment]
I meant that we generate all ids with sonyflake in zitadel. The only id suffixed, if I remember correctly, was the projectid. 😁

**Comment by JanKaul** [comment]
Okay, sorry for the misunderstanding. Then forget my previous comment.

**Comment by hifabienne** [comment]
I think our idea behind this was to represent in the same way as a loginname of a user and to have somehow something in the id, that helps a user to find out where it belongs.
I don't see a problem in changing it.
I would either just make the generated sonyflake id, or replace the @ with a - 
@fforootd @livio-a what do you think?

**Comment by hifabienne** [comment]
I think just using the sonyflake makes sense.
