### ISSUE TITLE
[Bug]: has yarn replaced npm for console? 

### ISSUE THREAD

**Issue by doncicuto** [zitadel/zitadel#6231]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

I'm not npm expert so not sure about this. 

I've cloned current's main repo to fix a frontend issue and when I try to `npm install` I get this ugly error with dependencies. 

I've tried to clear npm cache but finally I think that the issue is that package-lock.json is empty. I filled it with the content of previous commits and npm install worked fine.

Thanks!

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: console@0.0.0
npm ERR! Found: @angular/compiler@16.1.5
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"^16.1.2" from the root project
npm ERR!   peer @angular/compiler@"16.1.5" from @angular/compiler-cli@16.1.5
npm ERR!   node_modules/@angular/compiler-cli
npm ERR!     dev @angular/compiler-cli@"^16.1.2" from the root project
npm ERR!     peer @angular/compiler-cli@"^16.0.0" from @angular-devkit/build-angular@16.1.4
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"^16.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @angular/platform-browser-dynamic@"^16.1.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/compiler@16.1.4
npm ERR! node_modules/@angular/compiler
npm ERR!   peer @angular/compiler@"16.1.4" from @angular/platform-browser-dynamic@16.1.4
npm ERR!   node_modules/@angular/platform-browser-dynamic
npm ERR!     @angular/platform-browser-dynamic@"^16.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/doncicuto/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/doncicuto/.npm/_logs/2023-07-18T17_13_27_642Z-debug-0.log
```

### To reproduce

Clone the repo
Go to console
Run `npm install`

### Expected behavior

npm install should not fail with warnings about dependencies

### Operating System

Device: Linux
OS: Ubuntu

**Comment by doncicuto** [comment]
Ok, now I understand, you're now using yarn, don't you? 

If you don't mind I'm renaming the bug so we don't forget to change CONTRIBUTING.md for newcomers

**Comment by fforootd** [comment]
Oh good catch, I think that slipped in with the recent change to our CI.

You are absolutely right we should change this in the docs.

Personally I have no real preference 😁 

How about you @peintnermax

**Comment by peintnermax** [comment]
yes that was changed. This changes the `contributing.md`
https://github.com/zitadel/zitadel/pull/6233

**Comment by hifabienne** [comment]
I close this issue as it has been merged with the pr mentioned before
