### ISSUE TITLE
Adding reply-to header in email notification

### ISSUE THREAD

**Issue by redthorx** [zitadel/zitadel#6278]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When using a email sending service such as AWS SES to send notifications, the SMTP server might not come with an inbox. Users who have issues with their accounts might try to reply to the notification email, which will result in bounced emails.

### Describe your ideal solution

Adding a reply-to header for notification emails so that users are able to contact the owner directly through email

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hi @redthorx 
Thanks for sharing your idea.

We appreciate your input and we believe it’s a valuable suggestion.
We prioritise our issues based on the demand of our customer and community. So for now the issue will be added to our product backlog.
Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.
