### ISSUE TITLE
[Bug]: The "New" button from Authorizations is shown even if the user is not in charge of managing them

### ISSUE THREAD

**Issue by VladimirLogachev** [zitadel/zitadel#6290]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.31.1

### Describe the problem caused by this bug

The User User is just a simple user, but the UI shows the New button
However, this button does nothing.
It probably makes sense to hide the button.

### To reproduce

Steps to reproduce:
1. Be a simple user with no special permissions
2. Open Zitadel UI
3. Go to Authorizations
4. See the button which does nothing

### Screenshots

<img width="1087" alt="Screenshot 2023-07-28 at 15 50 43" src="https://github.com/zitadel/zitadel/assets/17773003/f21ea4c2-0486-45eb-bc9d-d280b40d9489">

### Expected behavior

- Either no button could be observed
- Or button is disabled

### Operating System

Mac
macOS
Chrome

**Comment by hifabienne** [comment]
Thanks for adding the bug report.
I think we should hide the button when the user doesnt have the user.grant.write permissions in ZITADEL

**Comment by prajwalrajbr** [comment]
I'm Interested. Please assign this to me.

**Comment by hifabienne** [comment]
Great to hear that. 
Thanks @prajwalrajbr I assigned you
