### ISSUE TITLE
[Bug]: Metadata values don't seem to work with Unicode.

### ISSUE THREAD

**Issue by VladimirLogachev** [zitadel/zitadel#6291]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.31.1

### Describe the problem caused by this bug

Metadata values don't seem to work with Unicode, but the metadata keys do.

### To reproduce

Steps to reproduce:
- Set the metadata values in several different languages (Unicode)
- See them broken in the view and in the edit layouts

### Screenshots

<img width="616" alt="1" src="https://github.com/zitadel/zitadel/assets/17773003/c943fa29-ee52-4937-9dd4-555c04d64868">
<img width="804" alt="2" src="https://github.com/zitadel/zitadel/assets/17773003/39ae26f5-cd20-4d0e-84c2-ea5b0f2e0f25">
<img width="610" alt="3" src="https://github.com/zitadel/zitadel/assets/17773003/c6d4b62d-a034-48e7-a2c3-cf286f6eac6d">

### Expected behavior

Metadata values support the same charset as metadata keys (or a descriptive error message is shown)

### Operating System

Mac
macOS
Chrome

**Comment by livio-a** [comment]
did a short test with emojis and can even see it being returned in the grpc-web response:

![Image](https://github.com/zitadel/zitadel/assets/9405495/dfc3164d-7c45-47fa-8275-fe55216f6a54)


@peintnermax can you have a look at it

**Comment by VladimirLogachev** [comment]
But the screenshot you attached shows emoji in **key**, and the problem seems to be with **values**...

**Comment by VladimirLogachev** [comment]
Thank you!
And other `ascii` things are expected to not cause similar problems, right?

**Comment by peintnermax** [comment]
> Thank you! And other `ascii` things are expected to not cause similar problems, right?
> 
> https://github.com/search?q=repo%3Azitadel%2Fzitadel+ascii&type=code

We'll clarify that 👍

**Comment by VladimirLogachev** [comment]
Can still be reproduced in:
- Zitadel self-hosted `v2.35.0`
- Zitadel cloud
