### ISSUE TITLE
Unify error messages about password being too long

### ISSUE THREAD

**Issue by vladimirlogachev** [zitadel/zitadel#6301]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Here are 3 screenshots:
- user changes initial password via the Login interface
- user changes their password via the ZITADEL UI
- admin resets the user password via the ZITADEL UI

All 3 of them have different errors, and only some of them are easy to understand

The password is:
```
Password__111112222233333444445555566666777778888899999000001111122222333334444455555666667777788888999990000011111222223333344444555556666677777888889999900000
```

![1](https://github.com/zitadel/zitadel/assets/17773003/1704a222-911e-4001-a8b5-65b108f06522)
![2](https://github.com/zitadel/zitadel/assets/17773003/85139031-3c3b-49f2-882c-54d53c5d5b6b)
![3](https://github.com/zitadel/zitadel/assets/17773003/893d0477-5859-4310-8e07-0f83704882d8)

### Describe your ideal solution

- Unify the error message
- If the page contains immediate feedback (check marks), we could probably check that the maximum password length is not exceeded.

### Version

v2.31.1

### Environment

Self-hosted

**Comment by sujoysb** [comment]
I would like to work on this issue. Can someone please assign it to me?

**Comment by vladimirlogachev** [comment]
Any progress? 😆
