### ISSUE TITLE
Releases page doesn't have the latest binaries 

### ISSUE THREAD

**Issue by ingria** [zitadel/zitadel#6308]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

GitHub releases page doesn't contain binaries since version [v2.31.0](https://github.com/zitadel/zitadel/releases/tag/v2.31.0), so the [installation docs](https://zitadel.com/docs/self-hosting/deploy/linux#unpack-the-archive) don't work

**Comment by fforootd** [comment]
Thanks for bringing this up.

We recently reworked our CI and kind of missed this 😢 

We will look into this, ASAP

**Comment by fforootd** [comment]
@stebenz FYI since you will look into this

**Comment by mffap** [comment]
+1 from a discovery call. Needs Linux-Binaries to test ZITADEL.

**Comment by yaneony** [comment]
Just found it out today. We need the builds. :D
