### ISSUE TITLE
Allow setting development mode when creating an application

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6397]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When I want to setup a client with local configuration, then I have to enable the development mode. Enabling the development mode is only possible after creating the application, requiring additional steps from a user after setup.

Currently only a warning is shown that the user needs to enable development mode. Development mode can't be directly enabled.

### Describe your ideal solution

When I add an insecure redirect url / post-logout url, 
Then I get a warning that this requires development mode enabled AND
Then I can toggle development mode on the same page

Should be possible both in Wizard Mode and Pro Mode.
<img width="1006" alt="Screenshot 2023-08-19 at 10 46 05" src="https://github.com/zitadel/zitadel/assets/1366906/bd0c4d50-2307-4524-b787-430361c329dd">
<img width="1341" alt="Screenshot 2023-08-19 at 10 46 13" src="https://github.com/zitadel/zitadel/assets/1366906/4e2db3be-85a0-4907-90ff-3b675a8a57e8">

### Environment

ZITADEL Cloud

### Additional Context

Current "Workaround": Create the application, then select the application, navigate to Redirect Settings, then toggle Development Mode

**Comment by mffap** [comment]
> @mffap I was thinking on adding the Development Mode toggle to the wizard for web apps but should this dev mode toggle switch be added for native apps too?
> 
> ![image](https://user-images.githubusercontent.com/30386061/267124185-bc72f637-734c-4ef1-9218-9123162870ed.png)

hey @doncicuto, thanks for the proposal. I thought it might be good on all OIDC clients? @livio-a what do you think?

**Comment by livio-a** [comment]
> hey @doncicuto, thanks for the proposal. I thought it might be good on all OIDC clients? @livio-a what do you think?

yes, i'd add it to all types... i mean SPA typically has the exact same problem as web, but also native apps might need it.

**Comment by doncicuto** [comment]
Cool @livio-a and @mffap, I'll start coding it right away.
