### ISSUE TITLE
[Bug]: (needs investigation) panic in logs

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6410]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

We observed two panics in the logs. the first one recovered, the second one resulted in an Error (and termination?).

Timestamps:
2023-08-18T06:56:28.101823Z
2023-08-18T06:56:28.210043Z

The log on 2023-08-18T06:56:28.210043Z refers to: 
https://github.com/zitadel/zitadel/blob/main/internal/auth/repository/eventsourcing/handler/user.go#L53

### To reproduce

Needs investigation asap to identify the cause.

### Additional Context

production environment

**Comment by hifabienne** [comment]
will close this as it is not possible to find the problem anymore
