### ISSUE TITLE
Naming: Secret Generators vs. Secret Appearance

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6418]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Different naming makes it hard to find the configuration options. In the [default YAML](https://github.com/zitadel/zitadel/blob/99e1c654a3c6cbe90c11dd171bfe3d172a343a0e/cmd/defaults.yaml#L548) these settings are called "Secret Generators", where in Console and our [docs](https://zitadel.com/docs/guides/manage/console/instance-settings#secret-appearance), we call them "Secret appearance".

Since I was looking for the expiration of these secrets, I was not looking into the secret appearance. Secret appearance I would have guessed the format of the secrets, but not the expiry and other settings. 

### Describe your ideal solution

- [ ] Propose to re-name "Secret Appearance" to Secret (Settings), or Secret Generators
- [ ] Cross reference either the default-yaml with the terms used in docs and vice versa (add the yaml terms to our docs) for finding this when coming from an self-hosted scenario (align general naming of things both in config and our docs)

### Environment

ZITADEL Cloud

### Additional Context

related: #5888

**Comment by hifabienne** [comment]
I quickly checked where we have what. As for now everything is named Secret Generator despite the console and corresponding docs.
So my suggestion is to rename Secret Appereance to Secret Generator for now.
And add it to the list of the inconsistent naming, to consider if we want to change it to Secret Settings in the future
