### ISSUE TITLE
Display current values in secret appearance settings

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6419]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

<img width="1506" alt="Screenshot 2023-08-22 at 15 41 53" src="https://github.com/zitadel/zitadel/assets/1366906/ded3bd1a-2432-435d-beee-ea4d74cf3a4c">

I have to click on the pencil individually to see the settings of the different secrets.

<img width="962" alt="Screenshot 2023-08-22 at 15 39 29" src="https://github.com/zitadel/zitadel/assets/1366906/47e687d1-31d9-49d6-a45d-3a55aace3d59">

### Describe your ideal solution

As admin, I want to see all secrets' settings without need to go into edit mode individually, to get a better and faster overview of the different settings.

When I open the Secret Appearance settings, 
Then I see all the configured settings of each Secret.

When I click on the pencil (edit), 
Then I can edit the configuration

Ideally we use the same pattern to read/edit configuration as in the other setting pages.

### Environment

ZITADEL Cloud

**Comment by doncicuto** [comment]
Hei @mffap, @hifabienne and @peintnermax do you agree that this would be the desired look and feel or do you need something different?

![image](https://github.com/user-attachments/assets/5b207629-9f29-428a-983c-1e814af115bb)

**Comment by mffap** [comment]
> Hei @mffap, @hifabienne and @peintnermax do you agree that this would be the desired look and feel or do you need something different?

Thanks! For me this looks more in line with the other settings.
