### ISSUE TITLE
Extend User Service

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6434]
We want to extend the user service with some methods of the old apis.

**Acceptance Criteria**
- [x] User CRUD
- [x] User deactivate/reactivate
- [x] User lock / unlock
- [x] API Tests are written for all functions
- [x] User relevant data for change prompts (password change, mfa add, passwordless)

Questions:
How do we want to handle list requests? Which data to return (example user with all data, with some data, small/fullblown)
Should we already mark old requests as deprecated? How do we state which ones are the new reqeusts?

**Comment by ARSHIL1804** [comment]
I would like to work on this

**Comment by hifabienne** [comment]
> I would like to work on this

Hi @ARSHIL1804 
Thanks for your offer.
Unfortunately this is the first issue that is about implementing the existing functionality in out new resource based API, and we do have some questions to clarify with that implementation (from an API perspective).
We actually like to implement this by ourself, so we can takle that questions. (Will probably be in the next sprint)
As soon as we have the first service migrated, we will provide issues for more migrations, where we will happily accept contributions.

**Comment by ARSHIL1804** [comment]
No Problem @hifabienne

**Comment by hifabienne** [comment]
The get user by id should have an attribute change Password Required: https://github.com/zitadel/zitadel/issues/6614

**Comment by hifabienne** [comment]
@peintnermax Please add other things that come to your mind

**Comment by DKlaper** [comment]
One important thing missing from the new User API is the ability to send a new email verification code without changing the E-mail address.
The old api can do that, but not the new one. The old of course does not take an UriTemplate.

**Comment by hifabienne** [comment]
> One important thing missing from the new User API is the ability to send a new email verification code without changing the E-mail address. The old api can do that, but not the new one. The old of course does not take an UriTemplate.

Yes you are right, we try to extend the new api, in an interative way. And its to much if we put all the reqeusts in one issue. So this is just the start

**Comment by demircis** [comment]
Hi @hifabienne,

Whats the status of these changes? For our use case having a request to get a user by ID across the whole instance would be very useful. Are there any ETAs for these requests?

Thanks for the info.

**Comment by hifabienne** [comment]
hei @demircis 
I think it should be implemented before the end of the year.

**Comment by hifabienne** [comment]
last duration: 4.5
