### ISSUE TITLE
Latest tag currently not on highest release version

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#6443]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Relates to this question https://discord.com/channels/927474939156643850/1019895518383583323/threads/1145864010407890994

Currently the latest tag gets assigned to maintenance versions as well, which can be confusing to the community.

### Describe your ideal solution

As a user of ZITADEL I want to have a clear indication on which version was the latest released one. I.e the highest number should be the latest.

### Version

all

### Environment

Self-hosted

### Additional Context

none

**Comment by hifabienne** [comment]
@muhlemmer @stebenz can you have a look at this, and estimate?

**Comment by muhlemmer** [comment]
As mentioned in [this answer](https://github.com/orgs/community/discussions/26281#discussioncomment-3251177), this is easy to implement using a check like:

```
if: "!github.event.release.prerelease"
```

It can be done in < 1 day / bugfix friday.

**Comment by livio-a** [comment]
> As mentioned in [this answer](https://github.com/orgs/community/discussions/26281#discussioncomment-3251177), this is easy to implement using a check like:
> 
> ```
> if: "!github.event.release.prerelease"
> ```
> 
> It can be done in < 1 day / bugfix friday.

but isn't the actual problem with maintenance releases, resp. that GH will tag the latest created release as "latest" and not the highest number
for reference https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
![image](https://github.com/zitadel/zitadel/assets/9405495/eddfdc0f-1b97-408c-8341-fcc1e256a676)
and semantic release will just not provide a `make_latest `
