### ISSUE TITLE
[Bug]: v2alpha session API, after login with TOTP all further requests fail with error: mfa required (AUTHZ-Kl3p0)

### ISSUE THREAD

**Issue by dimyle** [zitadel/zitadel#6450]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.35.0

### Describe the problem caused by this bug

Continuing from our recent discussion in https://github.com/zitadel/zitadel/pull/6362. 

Prerequisites:
- organization and user have MFA TOTP installed and activated
- use new v2 session API

When session is started with 3 checks (login + password + TOTP) `POST http://localhost:8080/v2alpha/sessions`, session token is returned in response. Further requests with this token to User API like:
```
GET http://localhost:8080/auth/v1/users/me
Authorization: Bearer <session token here>
Accept: application/json
```
fail with error "mfa required (AUTHZ-Kl3p0)". 
If I use OtpEmail instead of TOTP, everything works fine.

There is a comment left in code, that prevent TOTP from count in MFA check. I've tried to uncomment this piece of code, and TOTP started to work as expected: https://github.com/zitadel/zitadel/blob/f07e40c70b3947afd8d702448349d470595c476e/internal/authz/repository/eventsourcing/eventstore/token_verifier.go#L203-L208

### To reproduce

1. Set up TOTP for organization and user
2. Call `POST http://localhost:8080/v2alpha/sessions` with login, password and TOTP, get session token in response
3. Call `GET http://localhost:8080/auth/v1/users/me` with header `Authorization: Bearer <session token here>`
4. You get error "mfa required (AUTHZ-Kl3p0)"

### Expected behavior

Requests to User API with TOTP-confirmed session token work fine, like with OtpEmail, for example

### Operating System

Docker/Docker Compose/WSL

### Relevant Configuration

Standard Docker compose file

**Comment by quochuydev** [comment]
Same issue for internal authenticated user, seem checkbox `Force MFA for local authenticated users` on `Organization Settings` currently not work
