### ISSUE TITLE
Is it possible to initialize service users?

### ISSUE THREAD

**Issue by Elichkoto** [zitadel/zitadel#6457]
Hi there,

I'm interested whether a solution has been implemented?
I'm not sure whether my `steps.yaml` is not fulfilled correctly, but I'm not able even to create the Human user with different name than the default one.
Can you please advise?

Thanks in advance!

### Discussed in https://github.com/zitadel/zitadel/discussions/4451

<div type='discussions-op-text'>

<sup>Originally posted by **hugodutka** September 24, 2022</sup>
I cannot find a way to programmaticaly create a service user when I initialize Zitadel for the first time. I would like to access the API right after starting the app in order to automatically setup an IDP, users, and other resources in my development environment. However, I can see that it is possible to initialize only a human user through `steps.yaml`, who then has to click through the web UI to create a service user and generate a PAT for the new account. Is there another way?</div>

**Comment by hifabienne** [comment]
Hei @Elichkoto 
did you change the user in the FirstInstance before you setup ZITADEL?

**Comment by Elichkoto** [comment]
Hi @hifabienne,

I managed to do it through:
https://zitadel.com/docs/self-hosting/deploy/compose#docker-compose-with-service-account

But right now, I'm able to create a Human user, unfortunately, this user has no access to the Organization.
Seems that it

**Comment by Elichkoto** [comment]
Thanks, @hifabienne!

It worked perfectly!

Best regards,
Ellie
