### ISSUE TITLE
[Bug]: Performance problem on introspect endpoint

### ISSUE THREAD

**Issue by sschoeb** [zitadel/zitadel#6462]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

We use the following code to request the introspect endpoint:

```Typescript
const data = await axios.post(`${Configuration.getBaseUrl()}/oauth/v2/introspect`, {}, {
    params: {
        client_assertion: assertion,
        client_assertion_type: 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
        token: token
    },
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
});
```

We currently have severe performance issues on this endpoint. Here the measurement of the last 61 requests:

Description | Time
-- | --
Min Time | 531 ms
Median Time | 781 ms
Max Time | 3518 ms

We currently use the introspect endpoint on each call to check if the token is valid. Our application is slow as hell (especially as we have quite a few outliers with roundtrips above 1 second).

**Current Workaround:**
We have to implement a caching strategy for this. But this still has two drawbacks:

- The first page load is still slow. Worst case you hit a +3second roundtrip for the first call
- Reduced security as we cached the tokens (or do I miss something?)

**Similar/related topics**

- I mentiond this topic around 3 months ago in Discord, here the discussion: https://discordapp.com/channels/927474939156643850/1110479940882808882
- There is a "Performance optimization"-issue which is maybe related to that one? (https://github.com/zitadel/zitadel/issues/6306)

### To reproduce

- Call the introspect endpoint

### Expected behavior

As the introspect endpoint is a "to be used a lot" endpoint, I would expect to have fast roundtrips. Having median roundtrips close to 800ms makes this endpoint kind of unusable.

### Additional Context

If it makes more sense to add this information the the performacne issue, let me know.

**Comment by fforootd** [comment]
Thanks for raising this.

Let us have a look into this and come back to you ASAP.

Just out of curiosity, did you see severe degradation in the recent hours/days or is it this way since 3 months?
(I will anyway analyse our data internally but it helps confirm our data)

@livio-a @adlerhurst I will dive into this subject later today any thoughts of you on this subject will be helpful 😁

**Comment by sschoeb** [comment]
@fforootd thanks for checking. 

Since my first report it definitely got worse. In my first report I had around 300-400ms.

**Comment by fforootd** [comment]
Ok, thanks for the feedback, I will keep you posted.

**Comment by fforootd** [comment]
I just wanted to let you know that we deployed a first mitigation to some of the latency problems you observe.

We also identified multiple small issues that add up in the latency budget that we will start working in the coming days to improve the situation.

**Comment by sschoeb** [comment]
@fforootd that was a fast one :) 

By deployed you mean that I should already see a change? I hope not, but my first tests look more or less the same, except that I cannot see the big peaks anymore. So at the moment all the requests are between 600ms and 1 second (mostly 600 to 800). 

Thanks again for your Support on this and le me know if you need any further information.

**Comment by fforootd** [comment]
> By deployed you mean that I should already see a change? I hope not, but my first tests look more or less the same, except that I cannot see the big peaks anymore. So at the moment all the requests are between 600ms and 1 second (mostly 600 to 800).

The first mitigation was to stabilize (less jitter) the latency, so that looks successful. What intrigues me is that you see 600-800ms, while our data suggest we take around 450ms (which is too much, but that subject of ongoing optimization). Can you share privately on support@zitadel.com from what source (IP address) you are making the requests. This would help debug the latency.

**Comment by sschoeb** [comment]
@fforootd not sure what exactly I measured on friday, currently I see the following:
Most of the requests are between 420 and 600ms. But mostly in the area of 450 to 520. 

I've sent you my IP.

**Comment by fforootd** [comment]
> @fforootd not sure what exactly I measured on friday, currently I see the following: Most of the requests are between 420 and 600ms. But mostly in the area of 450 to 520.
> 
> I've sent you my IP.

Ok, at least it improved already a little :grin: 

Let me follow up privately and close this issue here
