### ISSUE TITLE
[Bug]: Console UI has an option "Set as default organization" for deleted organization (+typo in error message)

### ISSUE THREAD

**Issue by dimyle** [zitadel/zitadel#6467]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.35.0

### Describe the problem caused by this bug

Deleted organization is still present in organization list of Instance view. If I open it's menu, there is an option to set this organization as default (this is bug 1, see screenshot). This action is not allowed to execute, and if click it, error message appears. There is a typo in error message - now "organi_s_ation", have to "organization", this is bug 2 (see another screenshot).

### To reproduce

1. Create organization
2. Delete it
3. Go to organization list (in Instance view)
4. Open deleted organization context menu, you see item "Set as default organization" (forbidden action for deleted organization, this is bug 1, screenshot 1)
5. Click menu item "Set as default organization", error message appears (typo in text, this is bug 2, screenshot 2)

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/54911257/b5aa2b6b-51ac-4cd2-a5ec-8297514c5d44)
![image](https://github.com/zitadel/zitadel/assets/54911257/2fc66335-38b4-48f6-a01e-3ea1db03734f)

### Expected behavior

1. No menu item is present to set deleted organization as default.
2. Correct text in error if organization was not found

### Operating System

Docker Compose/WSL

**Comment by hifabienne** [comment]
Hei @dimyle 
Thanks for reporting.
Actually the deleted organizations should not be shown anymore.
We already have an open issue for that, with an open pr as well.
#2758 
So I think your issue should be solved as soon as deleted organizations are not shown anymore.
