### ISSUE TITLE
[Bug]: Handle non-ascii Organization name

### ISSUE THREAD

**Issue by kbumsik** [zitadel/zitadel#6471]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

When I use a non-ascii character, Hangul, one of CJK character. an empty domain name is created.

### To reproduce

1. Create an organization with name "한국어 테스트 ?!" (meaning Korean Test)

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/fa3b560f-c9db-4da2-858d-f4ffb2c1cdb7)

2. The created org doesn't have domain
![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/fed36e27-8fda-485f-af2b-d0a2ce19ad07)

### Expected behavior

Two possible solutions:

1. Reject non ascii characters at all
2. Always require setting an organization domain name (just like you uncheck "Use your personal account as organization owner"

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/80e5853a-1060-4fb5-8240-b06afbbdd322)

**Comment by ARSHIL1804** [comment]
@hifabienne  which of the solutions we should implement?

**Comment by hifabienne** [comment]
Thanks for reporting.
I had a quick look at the problem.
At the moment we only allow alphanumeric characters and remove everything else that doesn't match that.
So there are two problems:
1. If the first domain part is 0 characters after removing not allowed characters, it should return an error
2. As those domains are not used to host ZITADEL, but only for user names, the characters shouldn't matter that much. I think it is useful to not have symbols like ' ) ', etc. But other characters should be allowed.
