### ISSUE TITLE
[Bug]: Mail not being sent, log not helpful

### ISSUE THREAD

**Issue by some-user123** [zitadel/zitadel#6486]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Describe the problem caused by this bug

Emails upon account registration are not being sent and log does not contain any error.

### To reproduce

1. Setup zitadel using docker-compose, add these environment variables:
```
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_FROM=...
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_FROMNAME=...
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_REPLYTOADDRESS=...
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_SSL=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=...
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=...
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=...
```

2. Register an account, click "resend code"

3. The log shows these messages:
```
zitadel-zitadel-1  | time="2023-09-04T10:33:58Z" level=warning msg="missing translation" args="map[ChangeDate:2023-09-04 08:59:37.986524 +0000 UTC Code:L4L50S CreationDate:2023-09-04 08:59:37.986524 +0000 UTC DisplayName:<REDACTED> FirstName:<REDACTED> LastEmail:<REDACTED> LastName:<REDACTED> LastPhone: LoginNames:[<REDACTED>] NickName: PreferredLoginName:<REDACTED> UserName:<REDACTED> VerifiedEmail: VerifiedPhone:]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:210" error="message \"InitCode.Footer\" not found in language \"de\"" id=InitCode.Footer
zitadel-zitadel-1  | time="2023-09-04T10:33:58Z" level=warning msg="unable to process all events from subscription" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:231" error="ID=MAIL-83nof Message=Errors.Notification.Channels.NotPresent" projection=projections.notifications
zitadel-zitadel-1  | time="2023-09-04T10:34:15Z" level=warning msg="missing translation" args="map[ChangeDate:2023-09-04 06:59:49.124727 +0000 UTC CreationDate:2023-09-04 06:59:49.113191 +0000 UTC DisplayName:ZITADEL Admin FirstName:ZITADEL LastEmail:zitadel-admin@zitadel.<REDACTED> LastName:Admin LastPhone: LoginNames:[zitadel-admin@zitadel.<REDACTED>] NickName: PreferredLoginName:zitadel-admin@zitadel.<REDACTED> UserName:zitadel-admin@zitadel.<REDACTED> VerifiedEmail:zitadel-admin@zitadel.<REDACTED> VerifiedPhone:]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:210" error="message \"PasswordChange.Footer\" not found in language \"en\"" id=PasswordChange.Footer
zitadel-zitadel-1  | time="2023-09-04T10:34:15Z" level=error msg="trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:307" error="ID=MAIL-83nof Message=Errors.Notification.Channels.NotPresent" instanceIDs="[230375982907785219]" projection=projections.notifications
```

There should be an error message in the logs indicating why it was not possible to send this email.

**Comment by hifabienne** [comment]
Hei @some-user123 
Can you see something in your failed events?
https://zitadel.com/docs/concepts/eventstore/implementation#failed-events

**Comment by some-user123** [comment]
Failed events is completely empty.

**Comment by some-user123** [comment]
When accessing the database directly, `SELECT * FROM projections.smtp_configs;` returns 0 rows. Guess, that's not how it should be, right?

Any idea, how to further debug that? Why are my `ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_*` environment variables ignored? `ZITADEL_EXTERNALDOMAIN` in the same docker-compose file has an effect, though.

**Comment by hifabienne** [comment]
Yes the smtp_configs should return something. This looks like the settings have not been taken.

Did you change the SMTP Settings after you already have setuped ZITADEL in a first place?

If you like to test that, I would suggest to completely delete the cockroach and restart the docker compose.

You could also just set the SMTP settings through the ZITADEL Console UI, if thats an option for you.

**Comment by some-user123** [comment]
> You could also just set the SMTP settings through the ZITADEL Console UI, if thats an option for you.

Just found that out. Very frustrating experience. Maybe it would be worth a section in the documentation...

> Did you change the SMTP Settings after you already have setuped ZITADEL in a first place?

Yes, do the options only apply during setup phase? Maybe that would be worth a comment in the docs as well...

**Comment by hifabienne** [comment]
There is a link in the ZITADEL configuration for the SMTP Server config, you can find it here: https://zitadel.com/docs/self-hosting/manage/productionchecklist#zitadel-configuration

Yes, I think it makes sense to note that.
