### ISSUE TITLE
[Bug]: User registration using IdP asks for a phone number when using email doesn't

### ISSUE THREAD

**Issue by kbumsik** [zitadel/zitadel#6490]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

When registering with Google IdP, users are asked for Phonenumber.

However, it does not match with the registration flow using email.

### To reproduce

1. Login
2. Register
3. Google or username/password

### Screenshots

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/d16f849d-fd36-4a99-81fb-a7dbecf4c62b)

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/cc50a6bf-ad4b-4a44-9e2d-821412e726fd)

### Expected behavior

There should be a consistent configuration like "Add phone number on registration" in instance/org option.

Note: I personally don't want users to add phone number.

**Comment by hifabienne** [comment]
Hei @kbumsik 
This is on purpose like this. 
When registering from the idp, we show all the fields we could potentially fill with fields we get from the IDP.
The field is optional.
But it is mainly to be able to the data we get from the IDP, and that the user is able to update/remove, etc.
Therefore I will close the issue for now.
