### ISSUE TITLE
[Bug]: No back button on register with email page

### ISSUE THREAD

**Issue by kbumsik** [zitadel/zitadel#6491]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

No back on register with email.

This is inconsistent with the register page with IdP (Google)

### To reproduce

1. Login
2. Register with Google
3. Register with username password

### Screenshots

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/1a505e2d-0e26-4524-96be-0c150fb64713)

![Screenshot by Dropbox Capture](https://github.com/zitadel/zitadel/assets/7823583/28d78912-87b5-4866-b5af-91de27d5c343)

**Comment by hifabienne** [comment]
Hei @kbumsik 
Thanks for reporting.
You are right, there is a back button missing on the registration page.

**Comment by afobaje** [comment]
I will like to work on this

**Comment by hifabienne** [comment]
Hei @afobaje 
Great to hear that, in that case I will assign you the issue.
Thanks for your help. 🙏🏼

**Comment by afobaje** [comment]
@hifabienne please I am having difficulty starting the app on dev, how do I start it? Am I supposed to use npm or yarn or its solely based on go?

**Comment by hifabienne** [comment]
Hei @afobaje 
The backend and the login UI are written in Go.
Only the ZITADEL console is built with Angular.
So you should actually not need npm. 
Where do you struggle?

**Comment by doncicuto** [comment]
Hi @afobaje, your first step to contribute is https://github.com/zitadel/zitadel/blob/main/CONTRIBUTING.md in case you've missed it.

This issue is a frontend issue so as @hifabienne commented you'll have to work with Angular. The Console section in https://github.com/zitadel/zitadel/blob/main/CONTRIBUTING.md#console will help you step by step to run a development server that you'll use to test your changes.

You'll have to work with the code in the console folder (frontend).

As I'm also a contributor if you need any help let me know :smile:, welcome to Zitadel!

**Comment by hifabienne** [comment]
Hei @doncicuto 
Thanks for the additional information.
I have to correct one point.
It is a frontend issue, but the login frontend is not built in angular. Its built with golang html.
Never sure how to label those issues, as basically it is frontend. But mostly the backend engineers work on it as it is golang html. 😃

**Comment by doncicuto** [comment]
You're absolutely right didn't check that it was a login issue my bad 😅

**Comment by afobaje** [comment]
Thanks for the update, I will check it again.

**Comment by afobaje** [comment]
Please kindly reassign this task to someone else, as much as I will love to help out, my computer cannot run the program

![image](https://github.com/zitadel/zitadel/assets/34343091/dc15071a-d97f-4473-bb50-faded1f6dfec)

**Comment by doncicuto** [comment]
@afobaje if you still want to try this issue, I suggest you to increase NodeJS heap memory size. You can export the NODE_OPTIONS variable and set it like this before running yarn start:

` NODE_OPTIONS=--max_old_space_size=4096`

You can even add that option to your bash profile
