### ISSUE TITLE
Show endpoints on saml application settings

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6510]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

For OIDC apps we show the most important urls in the application settings. But not for SAML.

### Describe your ideal solution

Show the links to the [SAML endpoints](https://zitadel.com/docs/apis/saml/endpoints) on the app config page with the actual instance domain:

- Certificate
- Login 
- Logout (see: https://github.com/zitadel/zitadel/issues/5084)

### Environment

ZITADEL Cloud

### Additional Context

Logout is not at all documented: https://github.com/zitadel/zitadel/issues/5084
Relates also to: https://github.com/zitadel/zitadel/issues/6507

**Comment by doncicuto** [comment]
@hifabienne I have this issue #6510 and #6508 ready to send this weekend... if you can assign them to me... you know we now have more contributors which means great news but also more chances for collision :smile: 

Thanks!

**Comment by doncicuto** [comment]
@hifabienne maybe this can be closed? My PR #6841 included links for certificate, sso and slo
