### ISSUE TITLE
[Bug]: Login Texts doesn't trigger

### ISSUE THREAD

**Issue by om-surushe** [zitadel/zitadel#6511]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.36.0

### Describe the problem caused by this bug

I made some changes in the settings -> Login Interface Texts -> Login.
When it's first redirected to Login screen the changes made are not reflected but if you come back from Password screen the changes are reflected

Tried restarting the docker container and also tried on different browsers.

https://github.com/zitadel/zitadel/assets/83531291/1a3df994-3fb1-4fad-acec-f31438a6fc27

### To reproduce

Steps to Reproduce
1. Go to settings.
2. Select Login Interface Texts on the left sidebar.
3. In the Login Interface Texts screen select login in the drop down.
4. Make some changes and check if they are reflected.

### Expected behavior

It should have been reflected there.

### Operating System

I am using docker Version 4.22.0

**Comment by hifabienne** [comment]
Hei @om-surushe 
Where did you configure the settings?
On the instance level or on a specific organization?

**Comment by om-surushe** [comment]
> Hei @om-surushe Where did you configure the settings? On the instance level or on a specific organization?

on the instance level

**Comment by hifabienne** [comment]
I just tested this myself, in our Cloud, with chrome as well as with Safari. And it worked perfectly fine.
Which browser did you use?

**Comment by hifabienne** [comment]
Are you sure that you have put the settings in the instance?
I quickly checked what happens when I do the setting on my organization, and then I can reproduce your problem.

I have an organization ZITADEL and changed the settings there.
I don't see the text when I open my instance.
When I enter the name of the user in that organization i get to the password screen and go back. 
Then the text is changed

**Comment by hifabienne** [comment]
If you want to have it on the first page you need to set on the instance.
Or if you like to trigger the organization directly you have to send the organization scope so ZITADEL knows which organization to trigger: urn:zitadel:iam:org:id:{id}
https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

I will therefore close the issue.

**Comment by hifabienne** [comment]
> > If you want to have it on the first page you need to set on the instance. Or if you like to trigger the organization directly you have to send the organization scope so ZITADEL knows which organization to trigger: urn:zitadel:iam:org🆔{id} https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes
> > I will therefore close the issue.
> 
> It worked but I was trying to change colour, but I don't know why it's taking system default colour I strictly want to apply the light theme.

At the moment you can't only apply light theme. We show what is set in the system (dark/light), if the user overwrites the setting we show what is set (as soon as we have identified the user)
