### ISSUE TITLE
Machine Secret algorithm is only bcrypt

### ISSUE THREAD

**Issue by bcastellina** [zitadel/zitadel#6540]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.36.2

### Describe the problem caused by this bug

Machine Secret are only generated with bcrypt algorithm and passwap is not implemented. Due it, bearer generation and introspect is very slow (more than 1 second). Changing it and using scrypt, the performance will increasy considerably

### To reproduce

1. Generate Service User
2. Generate Bearer Token with /oauth/v2/token
3. Validate User with /oauth/v2/introspect

### Screenshots

<img width="1143" alt="image" src="https://github.com/zitadel/zitadel/assets/62736598/9425bd4c-167b-44da-9eb3-fe687d05e5f4">
<img width="1158" alt="image" src="https://github.com/zitadel/zitadel/assets/62736598/afc33851-96cc-4fc2-b357-08de366ed0e5">

### Expected behavior

An authentication and autorization less than 300~400 ms

**Comment by hifabienne** [comment]
Hei @bcastellina 
We decided to implement passwap in a first place for human users and will add it to service accounts at one point in the future.
As you are selfhosting, a possible solution to make it faster is to lower the hash cost. you can overwrite it in the defaults yaml.

I will remove the bug label for now, and replace it with improvements and add the issue to the backlog.
If we see that it is highly request we will prioritize higher.

Also if you need it faster, we always accept PRs.

**Comment by muhlemmer** [comment]
More people are giving feedback on the long response times as a result of Bcrypt hashing:

https://discord.com/channels/927474939156643850/1176657611014295574

**Comment by muhlemmer** [comment]
I would like to do an estimation on this @livio-a. As discussed it can greatly improve performance is we can lower the cost of existing hashes during runtime.
