### ISSUE TITLE
[Bug]: Organization Domain Ownership Verification modal when domain verification is disabled

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6545]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

<img width="1710" alt="Screenshot 2023-09-13 at 16 32 17" src="https://github.com/zitadel/zitadel/assets/1366906/f2814af9-fe18-4b05-a65d-93fc05c002df">

<img width="1710" alt="Screenshot 2023-09-13 at 16 32 49" src="https://github.com/zitadel/zitadel/assets/1366906/3d9bfa32-bc02-407a-92c9-d4bcbb8d6cd8">

### To reproduce

1. Disable "Validate Org domains"
2. Add a new organization domain
3. The modal appears; while in the background it says domain added and the domain is being added successfully

### Expected behavior

Don't show the modal

**Comment by hifabienne** [comment]
If the setting verify org domain is disabled on the domain policy, the popup should not be shown.

**Comment by doncicuto** [comment]
@hifabienne, I'll sent a PR for this issue this evening

**Comment by hifabienne** [comment]
Hei @doncicuto 
Thank you very much. Its great to hear that.
Highly appreaciated, as we try to solve the weird things around the organization domains right now.
Its hard to understand for the users, what it is about
