### ISSUE TITLE
[Bug]: Unclear instructions what to do with DNS TOKEN

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6549]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

When I create a DNS token for verification, then I get he following modal: 

<img width="512" alt="Screenshot 2023-09-13 at 16 50 15" src="https://github.com/zitadel/zitadel/assets/1366906/ab33b831-16a4-48e5-8467-5b87e48f638d">

Only the first part can be copied to the clipboard. It is unclear what to do with the second part `_zitadel-challenge.foobar.com`.

### To reproduce

1. Create an organization domain
2. Verify the domain with DNS challenge

### Expected behavior

Provide labels for the two values and guidance how to construct the value. Some domain registrars might require different configuration. If we can't provide this info on the modal, then we should point to a documentation that explains it for the major registrars.

### Additional Context

The verify button should be somewhere else according to the text. I would suggest to move it to the very bottom (not to the side of the token) and change the description.

**Comment by mffap** [comment]
Here is the instructions for Cloudflare: https://zitadel.com/docs/guides/manage/console/organizations#verify-your-domain-name

But f.e. on Google Domains (soon square space) the input looks different.

**Comment by doncicuto** [comment]
@hifabienne can you assing this issue to me? I'll work on it in parallel with #5503

**Comment by doncicuto** [comment]
@hifabienne I'm starting to work on this issue :smile:

**Comment by doncicuto** [comment]
Hi @mffap how about this?

First time we start validation:

![image](https://github.com/zitadel/zitadel/assets/30386061/6ccf77e9-06f2-4330-bbeb-ceae9918515b)

DNS validation chosen:

![image](https://github.com/zitadel/zitadel/assets/30386061/d539fd22-36c4-409d-b6e1-f026bbac3027)

**Comment by mffap** [comment]
Hey @doncicuto thanks for the proposal. I think that would make it clear and much better than the current state of the modal. Thanks!
