### ISSUE TITLE
Immediately trigger and IDP login

### ISSUE THREAD

**Issue by dsiscout** [zitadel/zitadel#6552]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

We are using Zitadel as IDP but want our users to be able to use external IDPs as well such as Google. We have configured the necessary settings in Google and the integration works.

What would be great though is, when initiating the auth request from our website, that we can pass to immediately trigger the external provider login.

### Describe your ideal solution

We can pass a prompt parameter during auth request (https://zitadel.com/docs/apis/openidoauth/endpoints). At the moment it allows four values:
- none
- login
- select_account
- create

Add the possibility to pass the provider id in the prompt e.g. "google:123123123". Based on the provider and id, it should automatically redirect directly to the correct external idp.

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hei @dsiscout 
The prompt is a parameter defined by the OpenID spec and has therefore only the defined values.
We do have a specific scope that you can use to directly choose the idp.
urn:zitadel:iam:org:idp:id:{idp_id}

https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

I will therefore close this issue.
