### ISSUE TITLE
Show "preferred login name" in user overview 

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6555]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

The user overview shows currently
- username
- email address

but not the "preferred login name", meaning the username + primary organization domain

Depending on the settings of the instance and the organizations users can have a different format of the "preferred login name" that they must use to authenticate. It is not guaranteed that this is either username or email address, but could be something different.

<img width="1422" alt="Screenshot 2023-09-14 at 12 05 20" src="https://github.com/zitadel/zitadel/assets/1366906/fc23ea3b-8572-4fa8-830b-070e33787ede">

It it hard to understand how the user can actually log in (what is the preferred login name) when looking at the overview. Also the detail view shows this info on the top/ side instead of more prominently on the user itself (eg, directly below the name or instead of "PROFILE").

<img width="1415" alt="Screenshot 2023-09-14 at 12 09 50" src="https://github.com/zitadel/zitadel/assets/1366906/a9257209-b7c3-462c-bc78-b29c90a17a9e">

### Describe your ideal solution

As Manager, I want clearly see what "preferred login name" a user has to be able to help them login to the system. This is the primiary information about a user and should be shown in all user lists and also more prominently on the profile page.

### Environment

ZITADEL Cloud

**Comment by doncicuto** [comment]
Greetings @mffap, I've added the preferred login name column but to keep the space, I've sacrificed the created at column.

![image](https://github.com/zitadel/zitadel/assets/30386061/bf86a4ab-602f-46f2-b9e4-a05f72bffa7b)

Do you want to remove any other column, or bring back the 'created at' column?

**Comment by doncicuto** [comment]
And @mffap, this would be the user detail card replacing PROFILE with user.preferredLoginName

![image](https://github.com/zitadel/zitadel/assets/30386061/f9d8c702-0b9a-4276-b90b-d837a136b26d)

Let me know if the previous screenshots work for you and I'll prepare the PR

Cheers!

**Comment by mffap** [comment]
> Greetings @mffap, I've added the preferred login name column but to keep the space, I've sacrificed the created at column.
> 
> ![image](https://user-images.githubusercontent.com/30386061/268457801-bf86a4ab-602f-46f2-b9e4-a05f72bffa7b.png)
> 
> Do you want to remove any other column, or bring back the 'created at' column?

I think we could replace username column?
The preferred login name consists of the user anyways. So no additional info in having around username. Created at would be more useful, I think.

**Comment by mffap** [comment]
> And @mffap, this would be the user detail card replacing PROFILE with user.preferredLoginName
> 
> ![image](https://user-images.githubusercontent.com/30386061/268459093-f9d8c702-0b9a-4276-b90b-d837a136b26d.png)
> 
> Let me know if the previous screenshots work for you and I'll prepare the PR
> 
> Cheers!

I like that actually. But maybe more up to @hifabienne, not sure if that should have label etc.

**Comment by hifabienne** [comment]
> > And @mffap, this would be the user detail card replacing PROFILE with user.preferredLoginName
> > ![image](https://user-images.githubusercontent.com/30386061/268459093-f9d8c702-0b9a-4276-b90b-d837a136b26d.png)
> > Let me know if the previous screenshots work for you and I'll prepare the PR
> > Cheers!
> 
> I like that actually. But maybe more up to @hifabienne, not sure if that should have label etc.

Maybe we could make a mix? loginname + Profile information?
I think its kind of usefull to know that this is the profule information from an oidc perspective, as this is what you get back when you add the profile scope

**Comment by doncicuto** [comment]
Ok @mffap and @hifabienne, then if you both agree, this would be the expected views:

User list:

![image](https://github.com/zitadel/zitadel/assets/30386061/e9ca8539-8ba1-4ae8-abc0-a12cec316b3f)

Profile: I've added a - between loginname and PROFILE:

![image](https://github.com/zitadel/zitadel/assets/30386061/5219f936-249e-4aad-90b6-554137f4ecef)

Thumbs up if you agree or leave any comments or need for change

Thanks!
