### ISSUE TITLE
[Question]: Cant integrate flow reset password

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#6556]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

as an admin manager, I create a verification code for user X because he forgot his password. Then user X uses verification code to change password (No session existing). I cant do it when use 2 this APIs
https://zitadel.com/docs/apis/resources/user_service/user-service-password-reset
https://zitadel.com/docs/apis/resources/user_service/user-service-set-password

I followed document https://zitadel.com/docs/guides/integrate/login-ui/password-reset  stuck at api change password, it returns error "Code not found" id: COMMAND-2M9fs

### To reproduce

1. Send request code API
2. Send request change password API

### Expected behavior

I can change user password successfull

### Additional Context

HTTP/1.1 400 Bad Request
cache-control: no-store
content-type: application/json
expires: Thu, 14 Sep 2023 10:43:57 GMT
grpcgateway-cache-control: no-store
grpcgateway-content-type: application/grpc
grpcgateway-pragma: no-cache
pragma: no-cache
vary: Origin
x-robots-tag: none
Content-Length: 172
date: Thu, 14 Sep 2023 10:43:57 GMT
server: Google Frontend
x-cloud-trace-context: a904f73c5f9e70565a626ee845af0134/9937339760903451922
traceparent: 00-a904f73c5f9e70565a626ee845af0134-89e885dcbd03f512-00
Via: 1.1 google
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Cache-Hit: uncacheable
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close

{
  "code": 9,
  "message": "Code not found (COMMAND-2M9fs)",
  "details": [
    {
      "@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
      "id": "COMMAND-2M9fs",
      "message": "Code not found"
    }
  ]
}

**Comment by hifabienne** [comment]
Hei @quochuydev 
I just tested this by myself again and it works perfectly fine.
Did you use the return code, or the send link function in the first request?
If you tried the send Link, can you test with the return code, and use the code you get back there for the second request?

**Comment by quochuydev** [comment]
Hi @hifabienne 
For me, it works when the Authorization Token from self user, BUT when with service user Token changes password for user (userId on path params), it fails. Answer your question, I use verificationCode

```
POST {{host}}/v2alpha/users/231561049109709235/password_reset
Authorization: Bearer {{TOKEN}}
x-zitadel-orgid: 226742452134923939
Content-Type: application/json

{
  "returnCode": {}
}
```
```
POST {{host}}/v2alpha/users/231561049109709235/password
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
x-zitadel-orgid: 226742452134923939

{
  "newPassword": {
    "password": "Qwerty@123"
  },
  "verificationCode": "{{verificationCode}}"
}
```
