### ISSUE TITLE
Trigger Default Organization Settings

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6567]
At the moment we trigger the instance settings when a user opens up the ZITADEL login. As a user is always bound to a organization, it doesn't really make sense to trigger the instance settings. 
Per default the settings (login and branding) of the default organization should be shown.

**Acceptance Critiera**
- [ ] Trigger login settings of the default organization
- [ ] Trigger branding settings of the default organization
- [ ] Users with other usernames should still be able to login they will be redirected to the next screen of their organization
- [ ] All settings should be taken from default org (password, domain settings)
- [ ] Restriction of users only happens when organization scope is sent
- [ ] This should be changed for newly setuped instances, for existing instances, we want to have it as it is for the moment. Maybe a setting where they can change to the new setting.

**Comment by hifabienne** [comment]
Use Cases:
B2B&B2C
- B2C Organization as Default (e.g Username/Password & Google Login)
- b2B with Azure AD

**Comment by mffap** [comment]
Given I have only one organization BETA (beta.com), and
Given on Beta is an external IdP (Okta) configured, 
When a user comes to the login screen, 
Then they get redirected to Okta for authentication

Given I have an org BETA (beta.com) and an org CIAM (no domain), and
Given on BETA is an external IdP (Okta) configured, and
Given CIAM is marked as the default organization,
Given domain discovery is default (enabled),
When a user comes to the login screen, 
Then they get the login screen with the policies of CIAM
AND
When the user enters [bob@beta.com](mailto:bob@beta.com) as email, 
Then they get redirected to Okta (from BETA login policy)

Given I have an org BETA (beta.com) and an org CIAM (no domain), and
Given on BETA is an external IdP (Okta) configured, and
Given BETA is marked as the default organization, and
Given domain discovery is default (enabled),
When a user comes to the login screen with the domain scope of CIAM,
Then they get the login screen with the policies of CIAM

**Comment by mffap** [comment]
Great stuff! This will make it for sure easier to understand. Thanks.
