### ISSUE TITLE
[Bug]: POST /admin/v1/events/_search returns empty body

### ISSUE THREAD

**Issue by nikzen** [zitadel/zitadel#6596]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.23.1

### Describe the problem caused by this bug

I want to listen for events using POST /admin/v1/events/_search with

```
{
  "asc": true,
  "limit": 1000,
  "aggregate_types": [
        "user"
    ]
}
```

Zitadel always returns `{}`. It returns always an empty body and in the Zitadel Console there are also no events. The user is IAM Owner.

### To reproduce

1. Perform POST /admin/v1/events/_search
2. The response looks like {}

### Expected behavior

It should return the events.

**Comment by hifabienne** [comment]
Hi @nikzen 
I just tested this myself and I can't reproduce it.
When I send the exact same request body as you mention above, I get the events back.

My complete curl looks like this, can you try this? : 

curl --request POST \
  --url https://$CUSTOM-DOMAIN/admin/v1/events/_search \
  --header 'Authorization: Bearer $TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
  "asc": true,
  "limit": 1000,
  "aggregate_types": [
        "user"
    ]
}'

**Comment by nikzen** [comment]
Hi @hifabienne , I also tried to reproduce it on your cloud offering and can't reproduce it there. It has probably sth to do with our deployment. Do you have an idea where we could look for the cause?

**Comment by hifabienne** [comment]
Would it be possible to update to a newer version of ZITADEL?
It looks like you are running on a pretty old version 2.23.1 newest is 2.37.1
Its hard to tell if that can cause something.

**Comment by nikzen** [comment]
Update to the newest version seems to solve the issue.
