### ISSUE TITLE
Add Session API method to remove user TOTP 2FA

### ISSUE THREAD

**Issue by dimyle** [zitadel/zitadel#6605]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Current Session API contains methods to remove SMS OTP and Email OTP, but no method to remove TOTP. There is now way to change user's TOTP but to use admin console interface (i.e. in a case of the user lost TOTP device).

### Describe your ideal solution

Session API contains method to remove user TOTP, like other OTP removal methods. This method can be called by other user (service user with user management permissions).

### Version

2.37.1

### Environment

Self-hosted

### Additional Context

![image](https://github.com/zitadel/zitadel/assets/54911257/e489c8be-8207-4e29-8e28-88dd3a213b1f)

**Comment by hifabienne** [comment]
Hei @dimyle 
The email and sms otp were implemented after the the release of our new resource apis, thats why they are already complete in there.
For older methods we have only migrated what we need to build the login at the moment. Other requests will be migrated later on.
You can find the totp in the auth or management API. (depending on your use case)
Auth (my own authenticated user) https://zitadel.com/docs/apis/resources/auth/auth-service-remove-my-auth-factor-otp
Management (as an admin for another user) https://zitadel.com/docs/apis/resources/mgmt/management-service-remove-human-auth-factor-otp

**Comment by hifabienne** [comment]
I will therefore move this issue to the backlog, it will be addressed for sure as we want to migrate all endpoints to the new apis, but can't give you an eta yet

**Comment by dimyle** [comment]
Hello @hifabienne 

Thanks a lot, management API method works like a charm.
