### ISSUE TITLE
[Bug]: Administrator cannot remove other user's Email OTP

### ISSUE THREAD

**Issue by dimyle** [zitadel/zitadel#6606]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.37.1

### Describe the problem caused by this bug

As instance admin I have an option to remove user's OTPs. But Email OTP removal button click do nothing - no errors, no messages, and Email OTP doesn't disappear. On the other hand, TOTP removal works good.

### To reproduce

Prerequisites: organization must allow Email OTP 2FA.

Reproduce:
1. Register new user
2. Log in with this new user and add Email OTP.
3. Login with administrator, go to created user profile, open tab 'Password and security', locate user's Email OTP, click 'Remove" button. Nothing happens.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/54911257/16416da9-fa87-402d-b042-c2d7a27c22b1)

### Expected behavior

When I (as administrator) click 'Remove' button on other user's Email OTP, this 2FA method is being removed. Like TOTP do.

### Operating System

Windows, Docker compose under WSL

**Comment by hifabienne** [comment]
Hei @dimyle 
Thanks for reporting this, I could reproduce it.

**Comment by hifabienne** [comment]
Quick check looks like if button "Delete" is clicked, that no api request is triggered
