### ISSUE TITLE
Missing documentation on groups and oidc claim name for groups

### ISSUE THREAD

**Issue by samip5** [zitadel/zitadel#6613]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

As an administrator of my org, I want to be able to specify groups that re-gains me Admin privileges after IdP auth, for example one example is Harbor.

I couldn't find really any information what is returned from the profile scope, and how I can configure Harbor to get user's groups as a result.

### Additional Context

Authentik as an example provides groups in profile OIDC scope as follows:
```py
return {
    # Because authentik only saves the user's full name, and has no concept of first and last names,
    # the full name is used as given name.
    # You can override this behaviour in custom mappings, i.e. `request.user.name.split(" ")`
    "name": request.user.name,
    "given_name": request.user.name,
    "preferred_username": request.user.username,
    "nickname": request.user.username,
    # groups is not part of the official userinfo schema, but is a quasi-standard
    "groups": [group.name for group in request.user.ak_groups.all()],
}
```

**Comment by hifabienne** [comment]
Hei @samip5 
We do not included, not standardized claims in the token.
But you can add any custom claims with the ZITADEL Actions.
You can find the documentation here: https://zitadel.com/docs/apis/actions/complement-token

**Comment by hifabienne** [comment]
I will close this issue, as we have the actions docuemented.
