### ISSUE TITLE
Custom Login UI: API detect user need to update his password (changeRequired)

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#6614]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Forward from https://discord.com/channels/927474939156643850/1153246325551415356

### Describe your ideal solution

1. As an admin manager, I create a user with API: `v2beta/users/human` 
`{ password: { password: '..........', changeRequired: true } }`

2. In Custom login UI: I wanna an API that I can detect user needs to update his password (get data object have field `changeRequired`)

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hei @quochuydev 
Thanks for adding the issue.
We do not yet have all the functionalities in our new API.
We discussed about where this attribute should go and came to the conslusion, that you should get that when requesting the user.
We do have an issue that is already estimated #6434 to extend the user api.
I added a note and liked this issue in there.
