### ISSUE TITLE
add application list in user portal

### ISSUE THREAD

**Issue by LeonDevLifeLog** [zitadel/zitadel#6620]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

add granted application list in user portal

### Describe your ideal solution

like keycloak account console:
![图片](https://github.com/zitadel/zitadel/assets/28891919/1e4cf625-981b-4ecd-9fbd-188ad723340c)

or 
authentik

![图片](https://github.com/zitadel/zitadel/assets/28891919/6a751da8-a48d-4304-845f-4b0e3c48191e)

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.
Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by doncicuto** [comment]
Hi @LeonDevLifeLog and @hifabienne maybe this issue can be closed as #4586 proposes the same thing. I promise you all that I've this on my radar once once I succesfully finish #5503

**Comment by LeonDevLifeLog** [comment]
> Hi @LeonDevLifeLog and @hifabienne maybe this issue can be closed as #4586 proposes the same thing. I promise you all that I've this on my radar once once I succesfully finish #5503

👍
