### ISSUE TITLE
Terminate Sessions without Session Token

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6623]
In certain cases I want to be able to terminate sessions of myself or of another user (if I am an Administrator), cases could be, when I lost a device.

**Acceptance Criteria**
- [x] I am able to terminate any of my own sessions without having a session token
- [x] I as an Administrator be able to terminate sessions of users in organizations where I am admin

**Comment by hifabienne** [comment]
@muhlemmer @livio-a please have a look at the issue and estimate it till the 11. Oct. 23

**Comment by livio-a** [comment]
it might be the easiest if we add the orgID when checking user so that we can use that information for the check (in case of an ORG owner)
