### ISSUE TITLE
[Bug]: Garbled characters in email notification subject

### ISSUE THREAD

**Issue by jinrenjie** [zitadel/zitadel#6631]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Describe the problem caused by this bug

When I switch the language to Simplified Chinese, the Chinese email subject received is garbled. 

The [RFC 5321](https://tools.ietf.org/html/rfc5321) document explains that SMTP protocol only supports US-ASCII encoding for subjects.

### To reproduce

1. Set the user language to Chinese
2. Send any email notification to this user

### Screenshots

On macOS device:

![mail](https://github.com/zitadel/zitadel/assets/5665135/649fe477-0a2c-429e-8aa4-bc5fda6f8d33)

On iOS device:

![IMG_0807](https://github.com/zitadel/zitadel/assets/5665135/f870ad3b-a7d9-4734-a59d-a92c69fa1b04)

### Operating System

Device: [Mac, iPhone 12 Pro]
OS: [macOS Ventura 13.5.2, iOS 16.6.1]

**Comment by jinrenjie** [comment]
@hifabienne Thank you, according to the instructions you provided, my problem has indeed been solved! I would like to know if there was any special handling for UTF-8 encoded strings in this setting?

**Comment by hifabienne** [comment]
Hei @jinrenjie 
So you just entered the same text in the custom texts again and this works?
I actually don't know if there is something special in the encoding.
Maybe @livio-a knows more?

**Comment by livio-a** [comment]
Hey @jinrenjie 

Thanks for pointing this out. I've just tested and seems like it's dependant on the provider, e.g. Google is still able to handle / display non-ascii, while Apple doesn't.
I'll create a fix for this.

**Comment by jinrenjie** [comment]
> Hei @jinrenjie So you just entered the same text in the custom texts again and this works? I actually don't know if there is something special in the encoding. Maybe @livio-a knows more?

Yes, I entered the same text again and saved it, then sent an email notification and the title was displayed normally!
