### ISSUE TITLE
[Bug]: Unable to select 2FA method during account setup on Firefox

### ISSUE THREAD

**Issue by skeletorXVI** [zitadel/zitadel#6657]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.37.2

### Describe the problem caused by this bug

During the signup process, the first account setup or after enforcing 2FA, it is impossible to select a 2FA method on Firefox, thus becoming stuck on the 2-Factor Setup screen.

### To reproduce

1. Configure your instance to enforce 2FA
2. Remove all second factors from your account
3. Sign out
4. Sign in again on Firefox

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/24981948/be71f117-aeba-4c34-aaa2-b019dbd7cc6d)

### Expected behavior

By clicking on a method it should be selected and the user able to click on next.

### Operating System

OS: Pop!Os 22.04 & Windows 10
Browser: Firefox 118.0.1

### Relevant Configuration

On Chrome it works as expected.

**Comment by hifabienne** [comment]
This has already been fixed with the following pr: https://github.com/zitadel/zitadel/pull/6632
Its included in the Rc 2.38.0 and will soon be released and deployed to zitadel.cloud
