### ISSUE TITLE
deactivate user grant does not have any effect

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#6661]
reported in discord (https://discord.com/channels/927474939156643850/1158365363453575188) if a user grant is deactivated, it's still listed active and will be returned in an introspection response, possibly also in other responses / objects (e.g. id_token, ...)

**Comment by livio-a** [comment]
a first code check revealed that the grpc converted always returns an an active state

**Comment by felixng313** [comment]
An error log occurred on the server.
```
level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:143" error="ID=PROJE-DGsKh Message=reduce.wrong.event.type user.grant.reactivated" instance=239052899294904323 projection=projections.user_grants3
```

**Comment by hifabienne** [comment]
> An error log occurred on the server.
> 
> ```
> level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:143" error="ID=PROJE-DGsKh Message=reduce.wrong.event.type user.grant.reactivated" instance=239052899294904323 projection=projections.user_grants3
> ```

@livio-a It looks like the converter for the reduce Reactivate event, takes the wrong event type (deactivate, instead of reactivate)

**Comment by stebenz** [comment]
Solved through https://github.com/zitadel/zitadel/pull/7123
