### ISSUE TITLE
api(v2): add feature flags

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6668]
As a user if zitadel I might want to enable experimental beta features.

Features will span certain "levels":

- system
- instance
- organization
- user

**To be clarified**

1. which resource does the flags belong? eg. does each level of feature to a the resource it applies to?
2. Does system level require an API call, or just static config?
3. Will we use enums, boolean fields or message fields (in case we need to set more then just on/off).
4. How do we handle storage?

**Acceptance criteria**

- [x] Basic API structure in gRPC defined
- [x] Basic storage defined, framework provided

**Comment by hifabienne** [comment]
@livio-a With the newest implementation of one of your features, we have already added some kind of feature flags.
What does that already include?

**Comment by muhlemmer** [comment]
Current implementation uses a set-once approach with an integer. Last week @livio-a and myself discussed that we should take a more elegant approach and this issue is the summary of that discussion.

**Comment by hifabienne** [comment]
@livio-a @muhlemmer Can you have a look at this for estimation?
