### ISSUE TITLE
zcli: Zitadel Command line Interface

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6669]
As a user I want to be able to send commands to Zitadel from the CLI.

The cli will be a separate binary and most probably a separate repository.

**Acceptance criteria**

- [ ] Non-interactive command line program to send JSON formatted requests
- [ ] Interactive  CLI, where message fields are asked from the user, based on the proto fields. These questions might be auto-generated based on proto reflect or a library.
- [ ] Integrate import migration (currently part of zitadel-tools)

**Comment by adlerhurst** [comment]
started a private project beacuse i was curious about proto generations: https://github.com/adlerhurst/protoc-gen-go-cli/tree/init

**Comment by mffap** [comment]
maybe related #6531

**Comment by mffap** [comment]
I would have loved to have this when testing the custom login. We could maybe even add a command that adds a service user to the default org with manager permissions, creates a pat, and displays the required parameters for the env file

**Comment by hifabienne** [comment]
@muhlemmer @adlerhurst I will close this issue here, as it is a duplicate of the other issue. And as we have reactions from the community/customer on the other it doesn't make sense to have this open.
