### ISSUE TITLE
SAML SP Console

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6687]
As an administrator I want to be able to administrate a SAML Idp from the console. The backend and APIs have already been implemented with the following issue: https://github.com/zitadel/zitadel/issues/2947

**Acceptance Criteria**
- [ ] I am able to choose SAML in the Identity Provider Section of the console
- [ ] I am able to fill the following SAML information: name, metadataXML, metadataUrl, binding, withSignedRequest
- [ ] I am able to either fill the URL to a SAML metadata file or a uploading a metadata xml (see screenshot in the comment below)
- [ ] General Provider Informations can be filled: isLinkingAllowed, isCreationAllowed, isAutoCreation, isAutoUpdate

** Additional Information**
- Add SAML IDP API: https://zitadel.com/docs/apis/resources/mgmt/management-service-add-saml-provider
- Update SAML IDP API: https://zitadel.com/docs/apis/resources/mgmt/management-service-update-saml-provider

**Comment by misko626** [comment]
Hi, Im Michael. I´m looking forward to contribude on this project. I have 2+y of experiences in Angular. Can I take this issue? And is there someone to help me navigate in code and explain me in more detail what exactly needs to be done? Or Im also open to take another issue, maybe a little bit simpler for my first issue there.

**Comment by misko626** [comment]
Great. I like this. So I would be happy work on this. Can you assign me to this issue and I will start work on this today.

**Comment by misko626** [comment]
Hi @hifabienne. I created PR 3days ago, but no one has made a review on it yet. Should I notify someone or do I just have to wait?

**Comment by hifabienne** [comment]
Hei @misko626 
Thanks for the pr. We have seen it and will have a look at it. 
Its already assigned to one team member. It can take some days till we can have a look at it.
