### ISSUE TITLE
One transaction for b2b onboarding (new org, create user, add manager roles)

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6691]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

In a b2b scenario you might want to create a new organization per customer, and also create the first user based on the registration information with a specific manager role. This requires multiple calls at the moment, but could be done in one transaction to ease implementation. 

We use the same pattern for zitadel.com and multiple users have the same use case to handle. 

### Describe your ideal solution

As a developer, I have an API call to create a new organization with a user and setting manager roles to that user, so I can create an easy onboarding/register in a b2b scenario.

Considerations: 
- Should check if the user already exists/ is unique
- Should check if the domain of the organization already exists
- Decision: If the organization already exists only register the user? (this would allow to have one call in a style of create if not already exists)

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hei @mffap 
I think what you describe in the issue, already exists.
There is a setup organization method.
You can send an orgnization, a user and roles directly in the body.
https://zitadel.com/docs/apis/resources/admin/admin-service-set-up-org
