### ISSUE TITLE
better PR descriptions

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6693]
As a developer I want to get a clearer overview of "why" something was changed in the product. This should be better explained in PR comments and the resulting squash commit. Therefore we should write down some rules and implemented an example in the PR templates.

Some examples can be taken from the Go project and perhaps other places.

**Acceptance criteria**

- [ ] Contributor guidelines explains commit title requirements
- [ ] PR template gives an example, or perhaps a Question form, to facilitate good commit message writing.

**Comment by hifabienne** [comment]
@stebenz @eliobischof would be great if you can have a look at this, as we get more and more feedback, that it is often not clear what our changes are about.
In my opinion this is not a task to plan in a sprint, but do next to it
