### ISSUE TITLE
Allow users to switch their login theme (dark / light / auto) 

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#6699]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Currently, the ZITADEL login always renders according to the users browser settings. They can't be overwritten and set explicitly.

### Describe your ideal solution

As a user, I want to configure my preferred theme, so the login pages are rendered in that theme.

### Version

latest

### Environment

ZITADEL Cloud

### Additional Context

Console currently sets the theme in localstorage whereas theme.js reads the cookie value.
There is no possibility to save a users preferred theme in the cookies via console.

**Comment by hifabienne** [comment]
@eliobischof I think this would better be handled with the issue: #5505 
Should we close this one therefore?
