### ISSUE TITLE
Management Requests Logging

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6706]
For the new pricing of ZITADEL we have some new metrics which we should be able to limit. To be able to collect the data outside of ZITADEL, ZITADEL has to log each time a request is done.

**Acceptance Criteria**
- [ ] ZITADEL logs when a request to the management apis is done (read/write)
- [ ] Excluded apis are oidc, saml, session (those are handled by DAU)
- [ ] Required fields in the log are user id, instance id, trigger/method
- [ ] Optional fields are organization id (nice to have, but not neccessary to limit the free tier at the moment)

**Comment by hifabienne** [comment]
@eliobischof @stebenz 
Can you please estimate this issue latest till lunch of 12. October?

**Comment by hifabienne** [comment]
Just had a discussion with @fforootd that we could also log the information of the user_id, instance_id at least, maybe additionaly  organization_id and user type.
In that case we can collect the data outside of zitadel 

This gives us also the possiblity to count when users access the apis, with a long-living token (e.g PAT)

To be able to limit in ZITADEL, this would mean an outside component should be able to trigger something in ZITADEL, that sets the limitation

**Comment by eliobischof** [comment]
> * As soon as the limit for management requests is reached, ZITADEL blocks

The ZITADEL API should return the exceeded statuses and console should show the exceeded dialog that redirects to the portal when it gets these responses, right?

**Comment by eliobischof** [comment]
Do we count and limit reads and writes or only writes?

**Comment by hifabienne** [comment]
> Do we count and limit reads and writes or only writes?

Both, basically the same as we have right now with the authenticated requests, but just without everything that is somehow login relevant.

**Comment by hifabienne** [comment]
> > * As soon as the limit for management requests is reached, ZITADEL blocks
> 
> The ZITADEL API should return the exceeded statuses and console should show the exceeded dialog that redirects to the portal when it gets these responses, right?

The users should not be able to do anything anymore. 
I discussed with @fforootd the possibility of just logging from the ZITADEL side, and handling everything else outside of ZITADEL.
Logs will be collected, and a view will be generated that is a list of customers/instances with the count, the customer portal can then read those views and create a rule on the loadbalancer.
In that case I think the user would not even get to the Console.

**Comment by eliobischof** [comment]
> > > * As soon as the limit for management requests is reached, ZITADEL blocks
> > 
> > The ZITADEL API should return the exceeded statuses and console should show the exceeded dialog that redirects to the portal when it gets these responses, right?
> 
> The users should not be able to do anything anymore. 
> I discussed with @fforootd the possibility of just logging from the ZITADEL side, and handling everything else outside of ZITADEL.
> Logs will be collected, and a view will be generated that is a list of customers/instances with the count, the customer portal can then read those views and create a rule on the loadbalancer.
> In that case I think the user would not even get to the Console.

I support the idea of externalizing the counting and limiting decision. Reacting on certain usage levels like sending mails and for billing can also be externalized and the logic within ZITADEL can be reduced a lot towards its core funtionality 👍

However, I'm a bit concerned about the user experience if we block the requests on the load balancer already, as we might be limited about failure messages.

What if we just maintained a simple table with limitable units per instance and a limiting true/false column that is manageable via the system API? In console we could still show the dialog with a call to action that directs to the portal instance management. I think that would be feasible and give freedom about choices for networking tools.

If we go this route, it might make sense to split the issue.

**Comment by fforootd** [comment]
I think the best thing todo is to create a nice error page for example in the portal(since we know the usage here) or a separate app and to proxy the traffic with GLB to that app where we can return a nice error

**Comment by hifabienne** [comment]
I rewrote the issue for the first part that should be implemented in ZITADEL (loggin)
Let me know if anything is unclear
