### ISSUE TITLE
[Bug]: Slow authentication requests (implicit flow and token request)

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#6709]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.37.3

### Describe the problem caused by this bug

When opening a new tab (therefore triggering login implicit flow and silent login through iFrames), requests to Zitadel take very long. The login part takes about 20 seconds, and the request to the /token endpoint after that takes about 5 seconds.

We started experiencing this about a week ago.

### To reproduce

Setup silent login with an external IDP (Google in our case) and access through a single page application.

Using `oidc-client-ts` and `react-oidc-context` in the frontend.

### Additional Context

Can provide HAR file in Discord if needed

**Comment by hifabienne** [comment]
hei @DavideWalder 
I assume, this is the same issue raised in our support channel, and therefore has been solved.
Due to this I will close the issue, feel free to reopen, if my assumption is wrong
