### ISSUE TITLE
[Bug]: Slow introspect endpoint + tracing

### ISSUE THREAD

**Issue by Vladbara705** [zitadel/zitadel#6712]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2023-10-11T14:47:20+02:00

### Describe the problem caused by this bug

Long wait for instrospect method.

I think the problem is in the `internal/eventstore/hanlder/(h *ProjectionHandler) TriggerErr` method, it is called too many times and its execution time slows down the request.

I am attaching the request trace

How can we speed up the execution time?

### To reproduce

curl --location --request POST 'http://localhost:8080/oauth/v2/introspect' \
--header 'Authorization: Basic MjMzNDYwNDc0ODU3OTgwNjc3JTQwb3JjaGVzdHJhOnNSbVJGdGkySEdZVU5kaE5zRng4MThmUDMwbGd0MzcxOFNNWVp1anBZdHQ1UE9RcVFBS2MxUWFrSjdjeks3UGc=' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'token=x_daZxhfuNcJwU_SKSW0aPKGZzeefQTrU_8fUCiWVVUxG_zJcO7yM-rcWBoPWBxPn0FQDvA' \
--data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
--data-urlencode 'client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIzNTc3MTY1NzE1Nzg3OTMyMyIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE2OTcwMzA1ODEsImlhdCI6MTY5NzAyNjk4MSwiaXNzIjoiMjM1NDkzOTA2NTIxODU5NjExQHRlc3QiLCJzdWIiOiIyMzU0OTM5MDY1MjE4NTk2MTFAdGVzdCJ9.fdVy9xUJ5-Qkhkraa1f5wuJX562I6tgF2HbWBulDyUgfQ94-0v8VovyzcZcchgAID0wYxnaxAKWOPkP7GS6D_N9fdvS-D4bOYexsax5ONNMoqlRjTVkIW-W9yWnXCYeFIeEsommcqVtUCIU8uAmtsztrP0ge4VPmpUaTwHENZFjyLGiR2iru2MGIZ4G4pO6xV6m1IhuzasKBJluCOGoQNTaz72gtbTaqtVUrJyT0QtyG1HjHaKlrAOuTDnifVMb_oC2r8zb545NO7yCxkPjWoC80VTprvDQOiidJmQMqBHjV7w-yYEl14tYBNgWEc9k-WvhapyOqq_PeLWe8Sa_T3w'

### Operating System

MacOs Ventura 13.0.1 (22A400)

### Relevant Configuration

[configuration.log](https://github.com/zitadel/zitadel/files/12870433/configuration.log)
[traces-1697028722918.json](https://github.com/zitadel/zitadel/files/12870436/traces-1697028722918.json)

**Comment by hifabienne** [comment]
@adlerhurst Can you have a look at this?

**Comment by adlerhurst** [comment]
Can you please retry with version 2.39.1? there were several performance improvements. There was another issue in the meantime which was fixed by adding a configuration: https://github.com/zitadel/zitadel/issues/6755#issuecomment-1770840457

**Comment by Vladbara705** [comment]
Thank you. We will update the version and report the results

**Comment by adlerhurst** [comment]
Please have a look at the release notes of 2.39.0 before you update ;)

**Comment by hifabienne** [comment]
As we didn't hear anything back and did a lot of performance improvements in recent releases.
I will close this issue.
Feel free to reopen if you still have a problem and can add new information
