### ISSUE TITLE
Audit Trail limit Events

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#6715]
For the new pricing we need a limitation of the audit trail. Audit trail means the change log on the specific objects as well as the events search filter. The limit (time) should be able to set per instance

**Acceptance Criteria**
- [ ] ZITADEL is able to get a limit (time) per instance for how many events should be readable 
- [ ] Limit is applied when the search events is performend
- [ ] Limit is applied when the change log of a specific object is requested (user, app, project, etc)

**Comment by hifabienne** [comment]
@eliobischof @stebenz I moved the issue to zitadel repo, as I initialy created it in the wrong repository. Can you estimate on this one pleasE?
Some clarifications can be found here: https://github.com/caos/caos-internal/issues/893

**Comment by eliobischof** [comment]
@hifabienne failed events are out-of-scope, right?

**Comment by hifabienne** [comment]
> @hifabienne failed events are out-of-scope, right?

yes
