### ISSUE TITLE
[Bug]: Unable to add secret to generic OAuth/OIDC IDP due to length

### ISSUE THREAD

**Issue by Repflez** [zitadel/zitadel#6719]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.38.1

### Describe the problem caused by this bug

As mentioned on the chat, I tried to add an OAuth IDP on my instance, however, due to a limitation on the form, I get this error:
```
invalid AddGenericOAuthProviderRequest.ClientSecret: value length must be between 1 and 200 runes, inclusive
```

The error mentions that it's due to the secret being limited to 200 characters, while the secrets provided to me is 418 characters. As such, here's a sample (already revoked):
```
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoLnRtcGltLnB3OnNlcnZlcjprZXk6NjM2YzE3ODJhYmUxNmI2ODFhYWE3ZjdhMjUxYzc2MGEiLCJpc3MiOiJhdXRoLnRtcGltLnB3OmNlbnRyYWwiLCJzZWNyZXQiOiJiL1o2NVBQNlkwTTZ3STNwL0NyRWJTSjdIZERlSUVvbTBUdDJRZ1RVY2ZvPSIsImlhdCI6MTY5NjcyNzg5MCwic3ViIjoiNjM2YzE3ODJhYmUxNmI2ODFhYWE3ZjdhMjUxYzc2MGEiLCJraWQiOiJlcyJ9.a9GX_yycUrYmJIMELYyvzi2oWeMTd2wPYYhANuaUVocHsfQ49CLb99rpd93O3EUXvw3EitWiDk-fT2ACxe5z2Q
```

### To reproduce

1. Go the the external IDP page
2. Create a generic OAuth provider
3. Use the secret provided
4. Create the provider

### Expected behavior

The provider should have been created successfully.

### Additional Context

The OAuth provider is not public or open source so I'm unable to provide a point of contact with their developers.

**Comment by hifabienne** [comment]
Hei @Repflez 
What type of provider do you try to configure?
Are you sure this is the right secret? As this looks like a token for me.

**Comment by Repflez** [comment]
> Hei @Repflez What type of provider do you try to configure? Are you sure this is the right secret? As this looks like a token for me.

I'm trying to create a generic oauth identity provider, and yes, I know it looks like a token, but I was told that *it's the secret*.

**Comment by hifabienne** [comment]
@livio-a @muhlemmer I think at the moment we restrict the length already on the api level.
Do you see any problem in extending the length?

**Comment by livio-a** [comment]
can't see any issue .i'll just extend it to 1000 characters
