### ISSUE TITLE
[Bug]: user change phone number does not use country selector

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6725]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

main branch

### Describe the problem caused by this bug

The phone number setting dialogue requires a `00` or `+` to be set, while there is already a country selector next to it. When a country code is used in the number that is not equal to the country from the selector, the code from the phone number is used and the resulting flag icon in the user view is not matching the one from the selector.

### To reproduce

Steps to reproduce:
1. Go to user view in organization;
2. In the "contact information" box, click the pencil to edit the phone number;
3. Let the default flag untouched (swiss) and enter a number without country code;
4. Now set a phone number that does not correspond the selector:
5. After pressing "save", observe that a dutch number has been added:

### Screenshots

Step 3:
![image](https://github.com/zitadel/zitadel/assets/5411563/5158cf93-fdc2-4d10-a1eb-270cedac43a4)

Step 4:
![image](https://github.com/zitadel/zitadel/assets/5411563/d14655a7-4823-4030-87cf-d1f2895d3868)

Step 5:
![image](https://github.com/zitadel/zitadel/assets/5411563/5c15ccd5-8ffb-49ef-8d2f-95e6929170ac)

### Expected behavior

Take the country code from the selector and dis-allow country code in the number box.

### Operating System

Device: Laptop
Browser: Chromium Version 118.0.5993.54 (openSUSE Build) stable (64-bit)
OS: OpenSUSE linux Leap

**Comment by doncicuto** [comment]
Hi @muhlemmer, thanks for reporting this issue. This country selector was one of my first contributions to the project so I may try to fix the issue and make it work as you desire.

Initially the country selector code was discussed here https://github.com/zitadel/zitadel/discussions/5115 and the intention was to have something similar to Google Contacts where you would use either the flag selector or use 00 or + followed by the prefix code to set the number. 

There are two possible scenarios, the one that you suggest that would imply that the country code can only be set by the flag while you can't set the country code or instead fix the current scenario where I'd try to detect the country code in the input and change the flag accordingly (in step4 using +31 would change the flag to The Netherlands before saving) which I agree that is wrong and indeed is odd for users.

@muhlemmer, @peintnermax and @hifabienne let me know if you want me to fix this issue and what path should I take

Thanks!

**Comment by doncicuto** [comment]
I've created a PR for the second scenario :smile:

**Comment by muhlemmer** [comment]
Thanks for the quick reply and PR :). Second scenario sounds great to me. I believe @peintnermax will do the review of the PR when he has some time.
