### ISSUE TITLE
[Bug]: Account Linking with Azure

### ISSUE THREAD

**Issue by scheibling** [zitadel/zitadel#6731]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.35.0

### Describe the problem caused by this bug

I'm experiencing somewhat of a weird error in regards to the Azure authentication. We have two scenarios:

1. User creates an account from the Azure provider. Zitadel picks up the UPN and links it correctly to the Zitadel account, and everything works as intended.

2a. User has an account, either created by self-registration or manually by an instance owner, which the user then links to the Azure provider after creation. Zitadel doesn't pick up the UPN, but chooses the DisplayName of the user as preferred_username.

2b. User creates the account from the Azure provider, removes and re-adds the Azure provider. Same behaviour as 2a.

The second scenarios have the consequence of messing up the login hints being sent to Azure when a user types their email into the username field and gets redirected

Checking the database, the difference seems to be the display_name-field in the projections.idp_user_links-table, which is the email/UPN in scenario 1 and the display name in scenario 2

I've tried about 50 different variations and configurations

### To reproduce

1. Create a user with the same email as an MS account
2. Finish registration, then log out and log in with MS Azure
3. When prompted, link the two together. Sign out when finished
4. Type the users email address into the Zitadel Username box, get redirected to Azure for auth
5. Zitadel sends the incorrect login_hint

### Expected behavior

Consistent behavior on linking and new account creation

### Operating System

Tested on Windows, Linux, Android
Firefox, Edge
Zitadel v2.35.0 (Fresh install)

### Relevant Configuration

Azure/Entra common endpoint
Scopes openid profile email User.Read
Automatic Update, Account creation allowed, Identity can be linked

### Additional Context

Tested with multiple users in different Azure tenants
Tested in multiple Zitadel Organizations (on the same instance)
No relevant exceptions/log entries (only the email footer one)
The User Linking form page shows the UPN for both username and E-mail

**Comment by scheibling** [comment]
I was also able to replicate this on Zitadel Cloud with a fresh instance in case you want to have a look at the logs

**Comment by hifabienne** [comment]
Hei @scheibling 
Thanks for adding the issue.
I could reproduce it.

It looks like the Display Name is not handled the same when adding a user as when linking a user.
I will add the issue to the bug fixing state. We have a Bug fixing day each sprint where we take those issues into account.
