### ISSUE TITLE
Review of first sentence of project's Read.me

### ISSUE THREAD

**Issue by Universe-stack** [zitadel/zitadel#6781]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

The use of english in the following sentence is wrong and should be corrected:

Wrong sentence: Do you look for a user management that's quickly set up like Auth0 and open source like Keycloak?

Proposed replacement: Are you searching for a user management tool that is quickly set up like Auth0 and open source like Keycloak?

I'd be more than happy to review and correct the entire documentation if it's approved. Thank you

**Comment by hifabienne** [comment]
hei @Universe-stack 
Thanks for the offer that would be great.

**Comment by Universe-stack** [comment]
Great.. Let me get on with it.
