### ISSUE TITLE
Get instance by domain request

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#6785]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

As a system API user I want to get an instance with a specific domain.

### Describe your ideal solution

A new `getInstanceByDomain` or the current `getInstance` request should be modified to provide a oneof id or domain

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Why is this needed? You do have the mapping of instance id to domain in the portal? So you could also directly request by id, or am I wrong?

**Comment by peintnermax** [comment]
> Why is this needed? You do have the mapping of instance id to domain in the portal? So you could also directly request by id, or am I wrong?

With the new pricing there is no connection to a instance. Its bound to the customer and his subscription but not his instances.

**Comment by muhlemmer** [comment]
Due to specifics in the gRPC interceptor, modifying the `GetInstanceRequest` with a `oneof` with a domain clause is not possible without lots of refactoring.

Instead, the linked PR uses the `ListInstances` endpoint with an additional Domains query.
