### ISSUE TITLE
Inconsistent back navigation in login

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6789]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

On some of the login pages we show a button "Back", on some pages we show a little arrow top-left, and some pages do have neither.

### Describe your ideal solution

All pages on the login flow should have a consistent UI element to go to the previous page.

### Environment

ZITADEL Cloud

### Additional Context

Related to thttps://github.com/zitadel/zitadel/issues/6788 but also asking for consistency of the UI elements.

**Comment by hifabienne** [comment]
The correct back button is the arrow on the top left:

**Comment by doncicuto** [comment]
Hi @mffap and @hifabienne, I've found a couple of back buttons that I've replaced with <-  in Register user and when we must introduce the password.

What about the Cancel buttons that we've in many login pages? Do you want to remove them too and replace them with the back arrow? For example when Zitadel asks us to change an init password that was set by an admin:

![image](https://github.com/zitadel/zitadel/assets/30386061/d950d692-c688-4f5a-86b1-2a0b1f2155d2)

**Comment by hifabienne** [comment]
Hei @doncicuto 
I quickly tested what happens when I press the cancel button.
It is going back to the "first" screen of the login.
I am not sure if it can be confusing when I click back, and I do not get to the screen I was before.
On the other hand, the step before, also doesn't make sense to go.

@peintnermax What is your opinion?
