### ISSUE TITLE
Transaction Retry Error

### ISSUE THREAD

**Issue by andar1an** [zitadel/zitadel#6793]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.39.1 and 2.38.1

### Describe the problem caused by this bug

With both 2.39.1 and 2.38.1 and CRDB 23.1.11 I get a [Restart Transaction Error - 40001](https://www.cockroachlabs.com/docs/stable/common-errors#restart-transaction). While different queries cause this error for the various versions, both point to [crdb.go](https://github.com/zitadel/zitadel/blob/main/internal/eventstore/repository/sql/crdb.go) for me. 

With both 2.39.1 and CRDB 22.2.2 I get a Slow Transaction warning, and a failed zitadel instance. Not error in CRDB though.

I did not test 2.28.1 and CRDB 22.2.2. 

### To reproduce

Steps to Reproduce:
1) Start and initialize a Zitadel Cluster with `vagrant up` in this repo(you will need to vary IP addresses in VAGRANTFILE or try private_network instead): https://github.com/stephenandary/dioxus_playground/tree/zitadel-restart-transaction-issue/deployment/vagrant
2) Browse to terraform directory and apply terraform
3) Browse to CRDB UI endpoint
4) Inspect the Insights Section (/#/insights) and view 40001 error

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/12686470/7e1d4c7c-a418-4c10-a125-f1d41a96c2d0)
![image](https://github.com/zitadel/zitadel/assets/12686470/d49c06bc-ce16-455f-ac49-82f0a606f67c)
![image](https://github.com/zitadel/zitadel/assets/12686470/1c59dfba-34f4-49e8-8da5-91dfc0476b6c)

### Expected behavior

There was not [contention](https://www.cockroachlabs.com/docs/v23.1/performance-best-practices-overview#understanding-and-avoiding-transaction-contention) with another concurrent or recent transaction attempting to write to the same data when starting zitadel ( I have only seen this when starting zitadel so far, but I am testing more).

### Operating System

ubuntu/focal64
zitadel="v2.39.1" or "v2.38.1"
crdb="v23.1.11"

### Relevant Configuration

See Vagrantfile and scripts

### Additional Context

I am unsure what version one should use with Zitadel at this point. I had initially thought 22.2.2, but I have had more success with 23.1.11.

**Comment by stephenandary** [comment]
I have not yet encountered this being a problem, and at this point believe an insert does still occur. Doubt this is severe at this point. Just making issue so more knowledgeable eyes can determine if worth keeping open or closing.

**Comment by adlerhurst** [comment]
Thanks for rising 👍 
There are several points you mention I try to go through them step by step:

**40001 error in versions < 2.39.0**: The table design of `eventstore.events` was based on instances, if two transactions inserted events on the same instance one of them had to be restarted client side

**40001 error in versions >= 2.39.0**: ZITADEL uses [`cluster_logical_timestamp()`](https://www.cockroachlabs.com/docs/stable/functions-and-operators#system-info-functions), if the calculated commit timestamp of the transaction is too old the client has to retry the transaction, as long as crdb does not provide a [`PENDING_COMMIT_TIMESTAMP`](https://cloud.google.com/spanner/docs/commit-timestamp#dml) function as spanner for example does we have to live with these retries.

**Slow requests warnings**: We are currently planning additional optimisations to improve query speed. See [this issue](https://github.com/zitadel/zitadel/issues/6306). There will be comments added which discuss improvements.

I hope this answers your questions :)

**Comment by stephenandary** [comment]
@adlerhurst, I will close this then. This is really great to understand, thank you very much for the explanation!
