### ISSUE TITLE
[bug]: CodeQL code scan fails globally 

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6796]
Seems that all CodeQL code scanning actions are failing for zitadel:

https://github.com/zitadel/zitadel/actions/workflows/codeql.yml

**Comment by livio-a** [comment]
i've managed to have it succeed again, but it only analyses between 60 and 80 files:
https://github.com/zitadel/zitadel/pull/6807

**Comment by hifabienne** [comment]
@stebenz whats the state on this?

**Comment by fforootd** [comment]
Since https://github.com/zitadel/zitadel/pull/6807 was merged can we close this?
