### ISSUE TITLE
[Bug]: login_hint is passed as undefined to IDP, causing a weird selection

### ISSUE THREAD

**Issue by DKlaper** [zitadel/zitadel#6800]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.39.1

### Describe the problem caused by this bug

When you were logged in and get redirected to the login page and then want to login with a different user using the IDP button in our case Azure the login_hint is passed with value undefined. This causes a strange entry to show up for the user in this case as displayed in the screenshot.

It literally just passes "&login_hint=undefined" as part of the query string.

### To reproduce

1. Login
2. get back to the login mask in some way so that it shows up in the state of Screenshot Step 1
3. Click "Other User"
4. Click the configured IDP in our case Microsoft
5. Observe how there is a weird undefined entry and the URL contains login_hint=undefined as showin in the second screenshot.

### Screenshots

Step 1
![grafik](https://github.com/zitadel/zitadel/assets/6404092/6d7a5202-c4fb-499e-b9ec-cdd5c8c7db16)

Then clicking on the Microsoft Login button we land on this, which shows the problem:
![grafik](https://github.com/zitadel/zitadel/assets/6404092/2c1fcbeb-9e68-43d7-8d24-e951b610a296)

### Expected behavior

There should be no "undefined" entry, the login_hint should simply not be passed.
Without login hint the user still gets his previously logged in accounts of Microsoft displayed:
![grafik](https://github.com/zitadel/zitadel/assets/6404092/283bd61f-7312-4dd9-9183-edb8654819b3)

(I simply just removed the &login_hint=undefined from the query for this screenshot)
definitely a minor issue imo.

### Operating System

OS Windows 11
Browser firefox

**Comment by stebenz** [comment]
@DKlaper Tried several times to replicate this bug, for me the login_hint is always empty, do you use any scopes or login_hint to call zitadel? If you would provide zitadel with a login_hint, this would also be used for the external IDP.

**Comment by DKlaper** [comment]
Hi @stebenz 
Upon further investigation it seems that we are already passing the wrong login_hint on initial authorize and Zitadel just remembers that. I wasn't considering that because I assumed that we pass something about the already logged in user if at all.
So I guess this can be closed. Sorry about that.
