### ISSUE TITLE
Optimize Discovery endpoint

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6810]
Through metrics we have observed that there is room to improve the `/.well-known/openid-configuration` endpoint. The way that the OIDC library was defining interfaces, there are cases where there are redundant unneeded calls.

Specifically, each discovery request would query the current ID token signing keys from the database to populate the `id_token_signing_alg_values_supported` field. This can actually be taken from the runtime config and the request can run entirely without database queries

**Acceptance criteria**
- [ ] No database queries
- [ ] By implementing the following oidc Server methods:

```
	Discovery(context.Context, *Request[struct{}]) (*Response, error)
```

**Comment by hifabienne** [comment]
@muhlemmer @adlerhurst Would it be possible to estimate this before the sprint starts?
