### ISSUE TITLE
e2e tests fail half of the times

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6811]
It seems that almost 50% of e2e fails at "cypress run". It happens randomly on either chrome or firefox tests on many (if not most) PRs at least once.

Can we improve this?

**Comment by doncicuto** [comment]
Hi @muhlemmer and @eliobischof maybe we should revert Cypress to  "cypress": "^12.2.0" and check again. Would Cypress 13 have some performance issues in lower resourced machines and affect some of our current tests randomly?

**Comment by muhlemmer** [comment]
If it is not too much work, feel free to give it a try and open a PR. We will see how it runs and take it from there.

**Comment by doncicuto** [comment]
Sure @muhlemmer I'll prepare a PR this evening reverting to the latest known working cypress version.

**Comment by muhlemmer** [comment]
We've upgraded to paid runners and reconfigured in https://github.com/zitadel/zitadel/pull/6916. At first look it seems to be the proper solution. Will analyze and close this issue if everything stays ok.

**Comment by muhlemmer** [comment]
e2e seem stable. Closing
