### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Universe-stack** [zitadel/zitadel#6838]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.39.2

### Describe the problem caused by this bug

The email verification code does not arrive to the user's imbox. 
I'm not sure if this is an issue with the code base or a gmail's.  Someone else might want to try it out for confirmation.

### To reproduce

1. Log into one of your instances
2. Click the link to a custom domain
3. No email is sent. However, Click the resend button also.

### Screenshots

![login trigger](https://github.com/zitadel/zitadel/assets/76141133/634fabd6-447d-4ecc-9063-468f4a461294)
![Login code](https://github.com/zitadel/zitadel/assets/76141133/f949e500-1bb5-4fba-a1af-571ac746b22a)

### Expected behavior

A verification email should be sent upon the loading of the page. Clicking the resend button should also trigger a resend.

### Operating System

Device: Windows
OS: 10

**Comment by Universe-stack** [comment]
I just noticed that the email was being sent to my old email which I previously changed in the console. Therefore, the problem may be that the email value wasn't being updated to the email verification page as it bore the wrong email.

**Comment by hifabienne** [comment]
hei @Universe-stack 
The admin user in your customer portal is not the same as the user of your zitadel instance.
So if you change the email address of the admin in the customer portal, this is not synced to the instance
