### ISSUE TITLE
[Bug]: 2-Factor Page unclickable on iOS and iPad

### ISSUE THREAD

**Issue by JimmyKmi** [zitadel/zitadel#6840]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.37.2

### Describe the problem caused by this bug

2-Factor Page unclickable on iOS and iPad

### To reproduce

1. Log in to an account on iPhone or iPad (touchscreen version of Safari) that hasn't enabled 2FA.
2. Setup 2FA
3. in the 2-Factor Setup page, can't select any 2FA way to continue (unclickable)

### Operating System

all versions of the iOS and iPadOS

**Comment by fforootd** [comment]
I just tested this on iOS 17.4.1 / zitadel v2.50.5 and it worked.

Going to close, feel free to open again if you still see this error.
