### ISSUE TITLE
console: virtual scroll org list for better performance

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#6850]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

<img width="347" alt="Screenshot 2023-10-31 at 12 53 31" src="https://github.com/zitadel/zitadel/assets/10165752/e86f425e-5928-407c-bce7-57157b2a1edf">

Having lots of organizations can lead to a deficiency in performance in the org context switcher component.
Virtually scrolling organizations should improve the behaviour of the component and reduce loading times.  

### Describe your ideal solution

Load a batch of organizations and increase load once the end of the list is reached.

### Environment

ZITADEL Cloud

**Comment by taivnaawawwsd** [comment]
j

**Comment by livio-a** [comment]
A customer reported that the Console UI completely freezes / crashes on their setup (thousands of organizations) when the use this component.
