### ISSUE TITLE
[Bug]: Console event viewer filter aggregate type cut off

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#6874]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.40.3

### Describe the problem caused by this bug

Makes it difficult to select the correct aggregate type 

<img width="434" alt="Screenshot 2023-11-07 at 09 34 13" src="https://github.com/zitadel/zitadel/assets/1366906/56d7dbd2-01ad-4ea2-8e52-0b38796b837a">

### To reproduce

1. https://b2b-demo-rbxajm.zitadel.cloud/ui/console/events
2. Press F
3. Click Aggregate Type dropdown

### Expected behavior

Aggregate types are readable

### Operating System

Chrome 118.0.5993.117

**Comment by vhugo-plume** [comment]
Hi, I would like to contribute to this issue, can u assign me?

**Comment by hifabienne** [comment]
Hei @vhugo-plume Thanks. I assigned you.

**Comment by doncicuto** [comment]
Hi @vhugo-plume are you working on this issue? I've a similar issue and I just want to check if you're fixing this UX issue so I could use that fix. Thanks in advance!

**Comment by muhlemmer** [comment]
@doncicuto, I have unassigned @vhugo-plume due to no response.
