### ISSUE TITLE
Optimize `query.GetUser` by name.

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#6884]
Currently the OIDC `ClientCredentialExchange` method uses the `query.GetUser` method where it searches for a name using a contains search.  This name column isn't indexed as well.

## Acceptance criteria

- [ ] Search names on equality
- [ ] Normalize the To Lower Case logic, so that we can index names
- [ ] Create a names index

**Comment by livio-a** [comment]
https://github.com/zitadel/zitadel/pull/6537 already improves the search, we want to first rollout that and then check if additional steps must be taken
