### ISSUE TITLE
Enable Option to Create Client Secret with PKCE Method

### ISSUE THREAD

**Issue by stephenandary** [zitadel/zitadel#6886]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Include an option to create a client secret to be used in conjunction with PKCE

### Describe your ideal solution

In the UI one can have a checkbox, in Terraform and additional field, in api an additional parameter or boolean to define whether a client secret will be created or not when using PKCE.

### Environment

Self-hosted

### Additional Context

This improvement encompasses all environments.

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by stephenandary** [comment]
I am happy to work on this today, but I don't write Go, so may need help along the way. 

I would like to point out that PKCE is meant to prevents authorization code interception attacks, it is NOT a replacement for a client secret which has the purpose of allowing the authorization server to validate the client application’s identity, proving that it is allowed to swap an authorization code in the first place.

While I have seen it become more common to just use PKCE, I think giving your users to option to have a more secure setup based on best practice is a good addition for an authentication product.

**Comment by stephenandary** [comment]
I have not forgotten about this, just don't have time yet.

**Comment by meyfa** [comment]
> I would like to point out that PKCE is meant to prevent authorization code interception attacks, it is NOT a replacement for a client secret

I agree with this assessment, and was somewhat surprised to find this option is missing. This would be a most welcome feature!

**Comment by stephenandary** [comment]
@hifabienne I would like to start revisiting this early to mid next week. Would it be possible to get some time with someone at zitadel to groom this issue so I can have some defined checkpoints?

**Comment by hifabienne** [comment]
hei @stephenandary 
The easiest is if you are joining our community chat https://zitade.com/chat
And ask your questions directly there, our team is also in the chat and will help you.

**Comment by stephenandary** [comment]
> hei @stephenandary 
> The easiest is if you are joining our community chat https://zitadel.com/chat
> And ask your questions directly there, our team is also in the chat and will help you.

I am in already in the Discord community, I will ask there when online, but I work in ET, so the time difference can be a challenge on Discord.

**Comment by stephenandary** [comment]
Closing issue to remove from my issue list, moved on to alternate solution. Please re-open if you still plan on this.

**Comment by meyfa** [comment]
Re-opened as #7110
