### ISSUE TITLE
Organization  & Project on Authentication

### ISSUE THREAD

**Issue by HungryHowies** [zitadel/zitadel#6887]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Using Zitadel Cloud
Created one Instance
Create two Organizations (ORG1, ORG2)
Create a Project for each Organizations.

Create a user  for each Organizations.( i.e., users are separate with no Grants)   
Description:

• Organization 1 is for administrators.
• Organization 2 is For Client
The Idea behind this.
Client  Organization can only  use there SAML Project 
Administrator Organization  can use any project.  So, I wanted to  Grant permission to Administrators to other Organizations and the client Organizations   are restricted. 
 
Two applications and both application are in the same Domain.
1. IPAM for admins
2. Zabbix for client

Before I set  grants/permission it seems the Client users can logon to  Administrator projects. I tested this with two separate  zabbix-servers, two separate IPAM servers, Nextcloud-servers, etc... to make sure it wasn’t my  application.
 I'm using this documentation or am I not understanding it correctly?

https://zitadel.com/docs/guides/manage/console/organizations 

 I guess the main question is how to keep clients  from being able to log on to my administrator Projects?  I was assuming  since each user is in their own Organizations this would prevent this from happing.

### Describe your ideal solution

To have Project on Authentication  enable when creating a project, as described “It is checked whether the user's organization has this project. If not, the user cannot be authenticated.”

This might prevent  issues  when a user creates a project and  other users are able to log on to a project not in their organizations. 

### Version

v2.40.4

### Environment

ZITADEL Cloud

### Additional Context

another solution  might be in the documentation,  perhaps highlight/link the project settings .

https://zitadel.com/docs/guides/manage/console/organizations

**Comment by hifabienne** [comment]
Hei @HungryHowies 
We do differ between authentication and authorization. The login is only authentication and can be done per default by any user. If you want to restrict the organization, you could send the org scope urn:zitadel:iam:org:id:{id} https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes

In that case we assume that authorization (permissions) are handled within your application.
The second possibility is to enable the setting "check authorization on authentication" in your project. If that is set the user needs a authorization in your project, without the user will not be able to login.
<img width="702" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/ae6c766a-0c11-4d0b-b3a5-d787dd6813a8">

**Comment by HungryHowies** [comment]
> Hei @HungryHowies We do differ between authentication and authorization. The login is only authentication and can be done per default by any user. If you want to restrict the organization, you could send the org scope urn:zitadel:iam:org🆔{id} https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes
> 
> In that case we assume that authorization (permissions) are handled within your application. The second possibility is to enable the setting "check authorization on authentication" in your project. If that is set the user needs a authorization in your project, without the user will not be able to login. <img alt="image" width="702" src="https://user-images.githubusercontent.com/38692350/281296270-ae6c766a-0c11-4d0b-b3a5-d787dd6813a8.png">

Understood and thank you for the reply,  I didnt know about the  first part ( `urn:zitadel:iam:org🆔{id}` ) but I   was able to  find the  "check authorization on authentication" and that worked.  I assumed that  users were restricted already per organization then "Grants" as needed.

Thanks again
