### ISSUE TITLE
[Bug]: (Console) Table selection/edit widgets stay visible even after the row is deleted

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#6893]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

Selecting a row in a table and then clicking on an inline row widget, like a delete button, does not reset the table editing state, even after that row has been deleted. For example, if you select a user row and then delete the user, the "1 Selected Elements", "Clear selection", and "Deactivate" buttons are still visible even after the user has been deleted.

### To reproduce

Steps to reproduce:
1. Navigate to the users table
2. Click on a selection box for a user
3. Notice that the table goes into the "edit" mode, where there's a "1 Selected Elements" field, "Clear selection" button, and "Deactivate" button visible.
4. Mouse-over the selected user and click on the delete button. Confirm the deletion.
5. Notice how the table stays in the "edit" mode, where there's still the "1 Selected Elements" field, "Clear selection" button, and "Deactivate" button visible, even though there's now no row selected (as it's been deleted).

### Screenshots

![Screenshot_20231108_161831](https://github.com/zitadel/zitadel/assets/131888729/6f4901f8-ff57-4feb-9a41-19b4a195ef30)
![Screenshot_20231108_161900](https://github.com/zitadel/zitadel/assets/131888729/65af3e21-b95d-4484-974d-472cd6373efe)

### Expected behavior

After deleting a user, the table should return to the non-edit state unless other rows are still selected.

### Operating System

Google Chrome (up-to-date) on Linux.

**Comment by doncicuto** [comment]
@jbvv1 can reproduce the issue, thanks for the detailed steps and the bug warning. @hifabienne I'm taking this one

Thanks!
