### ISSUE TITLE
[Bug]: "Log in >" link on /ui/console/ does nothing

### ISSUE THREAD

**Issue by gabrieldeal** [zitadel/zitadel#6901]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

Cloud version

### Describe the problem caused by this bug

Nothing happens when I click the "Log in >" link on https://myinstance.zitadel.cloud/ui/console/
﻿
The link points to a strange looking concatenation of two URLs: https://myinstance.zitadel.cloud/ui/console/https:/zitadel.com/docs/guides/integrate/login-users

### To reproduce

1. Go to https://MYINSTANCE.zitadel.cloud/ui/console/
2. Click the "Log in >" link

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/15224929/19ee2f27-37e0-4c3f-9090-51c14b902328)

### Expected behavior

I assume it should open https:/zitadel.com/docs/guides/integrate/login-users

### Operating System

Ubuntu 22, Chrome 111.0.5563.146

**Comment by hifabienne** [comment]
@eliobischof I think you made some changes recently, where should the link go?

**Comment by eliobischof** [comment]
> @eliobischof I think you made some changes recently, where should the link go?

This is fixed but the fix is probably not deployed. I'll check it.

**Comment by hifabienne** [comment]
is this deployed now? @eliobischof
