### ISSUE TITLE
[Bug]: Failing Go Zitadel Setup

### ISSUE THREAD

**Issue by Qodestackr** [zitadel/zitadel#6903]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.39.3

### Describe the problem caused by this bug

Failing ./main.go:43:59: undefined: http_mw.Token

I am following your docs demo

### To reproduce

package main

import (
    "flag"
    "log"
    "net/http"
    "time"

    http_mw "github.com/zitadel/zitadel-go/v2/pkg/api/middleware/http"
    "github.com/zitadel/zitadel-go/v2/pkg/client/middleware"
)

var (
    issuer = flag.String("issuer", "", "issuer of your ZITADEL instance (in the form: https://<instance>.zitadel.cloud or https://<yourdomain>)")
)

func main() {
    flag.Parse()

    introspection, err := http_mw.NewIntrospectionInterceptor(*issuer, middleware.OSKeyPath())
    if err != nil {
        log.Fatal(err)
    }

    router := http.NewServeMux()
    router.HandleFunc("/public", writeOK)
    router.HandleFunc("/protected", introspection.HandlerFunc(writeOK))

    lis := "127.0.0.1:5001"
    log.Fatal(http.ListenAndServe(lis, router))
}

func writeOK(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("OK " + time.Now().String()))
}

**Comment by stebenz** [comment]
@Qodestackr Closed as of inactivity and problem should be solved through the SDKs, if not so please reopen the issue or a new issue.
