### ISSUE TITLE
Don't remove user links when disabling an IDP

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#6907]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When an IDP is removed from a login policy, the user to IDP links are also removed.
This makes it impossible for these users to use this IDP again if it is readded to the login policy.
Especially if the IDP is unintentionally removed from the IDP, this behavior can cause troubles.

### Describe your ideal solution

As a ZITADEL manager, I want to have the opportunity to reenable an IDP with all its user links, so that the links don't have to be recreated from scratch. However, users should not be able to use an IDP that is not added to the login policy.

### Version

latest

### Environment

Self-hosted

### Acceptance Criteria
- [x] When an idp is deactived, users still have the link aferwards (deactivate = remove from login policy)
- [x] Users with a linked idp, that is not active are not able to login with that idp
- [x] IDP can be reactivated, after that the user is able to login with the idp again

### Additional Information
- When the user has an existing user session with an idp that got deactivated, the user should not be redirected directly to idp, instead other authentication possibilities should be shown (pw, passwordless, etc)

**Comment by hifabienne** [comment]
Acceptance Criteria is removed: 
- [x] In the user api the allowed authentication method should not return an deactivated idp

New api doesnt care about settings
