### ISSUE TITLE
[Bug]: Admin must be able to activate user after the fact

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#6919]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.38.1

### Describe the problem caused by this bug

As an admin I can create a new user in 2 ways.
1. Fully Active
pre-select ```email verified``` and ```set initial password```
All good, user ready to go

2. Not active
In this case I do not pre-select ```email verified``` and ```set initial password```

As an admin, I should be able to now go to this user and do the following;
a. add and verify an email
b. set a new password that isn't required to be changed.

After this is done the user must be the Active state as if I had initially added them in step 1.
<img width="487" alt="image" src="https://github.com/zitadel/zitadel/assets/201257/8a3ec550-334d-4fb0-91f0-c6a6aba21169">

Also, I must be able to achieve the same via api calls.

I can also get myself into another odd state.
1. The user has been verified and active with a good email.  
2. User changes their email to ```bob@notreal.xyz```

Now in the admin panel I can verify the non-existent email all because the state of the user is Active.
<img width="382" alt="image" src="https://github.com/zitadel/zitadel/assets/201257/e2e001c4-20ba-4545-bd90-de074ff019b9">

### To reproduce

Above

### Screenshots

<img width="501" alt="image" src="https://github.com/zitadel/zitadel/assets/201257/05caa2b6-f4c8-42dc-a7b2-35a2c39222d5">

### Operating System

Docker

**Comment by hifabienne** [comment]
Hei @ghstahl 
I think what you are trying to achieve is already possible trhough the apis.
With the requests: https://zitadel.com/docs/apis/resources/mgmt/management-service-import-human-user
You can set the email to verified, set a password, and set that it shouldn't be changed

**Comment by ghstahl** [comment]
We may have an api bug then. I cannot set the users email to verified after the fact using set email api. I get an error saying the user is not active. 

If I call the import user api I have to have set the email verified to true. If I mess that up my only choice is to delete the user and add them with all the right settings.

**Comment by hifabienne** [comment]
Ah sorry I missunderstood. I thought you meant to do it in one call.
Yes you are right at the moment the email has to be verified first, otherwise the user is in an initial state, where nothing can be done.
We do want to change that behaviour and will do so with the new api. We already got rid of the initial state with the new users service api.

**Comment by stebenz** [comment]
@ghstahl 
Hi, did you tried it already with the new API https://zitadel.com/docs/apis/resources/user_service/user-service-add-human-user?
