### ISSUE TITLE
[Bug]: not return idpIntent 

### ISSUE THREAD

**Issue by frnk-hackle** [zitadel/zitadel#6922]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.1

### Describe the problem caused by this bug

https://zitadel.com/docs/apis/resources/user_service/user-service-start-identity-provider-intent

not return idp intent

### To reproduce

url : https://test-7jcflz.zitadel.cloud/v2beta/idp_intents
body : 
`
{
  "idpId": "240645041574421503",
  "urls": {
    "successUrl": "http://localhost:3000",
    "failureUrl": "http://localhost:3000"
  },
  "ldap": null
}
`

return 
`
{
    "details": {
        "sequence": "1",
        "changeDate": "2023-11-15T09:24:34.411571Z",
        "resourceOwner": "239923096008610561"
    },
    "authUrl": "https://trial-6950553.okta.com/oauth2/v1/authorize?client_id=0oa9bec58mu8AxpFX697&prompt=select_account&redirect_uri=https%3A%2F%2Ftest-7jcflz.zitadel.cloud%2Fidps%2Fcallback&response_type=code&scope=openid+profile+email&state=240827329700431216"
}

`

### Expected behavior

`
  "details": {
    "sequence": "2",
    "changeDate": "2023-11-14T10:51:08.210Z",
    "resourceOwner": "69629023906488334"
  },
  "authUrl": "https://accounts.google.com/o/oauth2/v2/auth?client_id=clientID&callback=https%3A%2F%2Fzitadel.cloud%2Fidps%2Fcallback",
  "idpIntent": {
    "idpIntentId": "163840776835432705",
    "idpIntentToken": "SJKL3ioIDpo342ioqw98fjp3sdf32wahb=",
    "userId": "163840776835432345"
  },
  "postForm": "string"
}

`

**Comment by frnk-hackle** [comment]
i can't find user because idp start api not return idpIntent values

`
curl --request POST \
  --url https://$ZITADEL_DOMAIN/v2beta/idp_intents/$INTENT_ID \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer '"$TOKEN"''\
  --header 'Content-Type: application/json' \
  --data '{
  "token": "k50WQmDaPIazQDJsyKaEPaQPwgsytxqgQ3K1ifQeQtAmeQ"
}'

`

**Comment by hifabienne** [comment]
@livio-a @muhlemmer how should this behave? can you give your input?

**Comment by muhlemmer** [comment]
Please read https://zitadel.com/docs/guides/integrate/login-ui/external-login

On the first request we only return the AuthURL. When the flow is completed you will receive the `idpIntentId`.

**Comment by hifabienne** [comment]
I will close this issue for now, as we haven't heard anything back.
And the solution has been stated above.
Feel free to reopen, if you have additional information to share
