### ISSUE TITLE
[Bug]: Identity Providers: SAML SP does not show updated values in org settings

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#6940]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the problem caused by this bug

This view should show the current values of a SAML SP in the org settings. The view works for the instance settings

<img width="611" alt="Screenshot 2023-11-20 at 09 40 38" src="https://github.com/zitadel/zitadel/assets/10165752/cdcfc198-a6ec-463e-825c-f89a9ce62d13">

### To reproduce

Go to a detail view of a SAML SP and

**Comment by stebenz** [comment]
The view to add a SAML provider has also some problems:

![image](https://github.com/zitadel/zitadel/assets/46600784/410122f5-d082-40a4-95d4-d1664599efd0)

You need to either provide the XML directly or the URL to the XML, which works without a problem in the API.
