### ISSUE TITLE
[Bug]: A normal user can see the activity of the admin.  A user should ONLY see stuff that is in context of themselves

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#6977]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.4

### Describe the problem caused by this bug

A normal user should only see information that is in their context.  The activity of the zitadel admin should NOT be displayed.

### To reproduce

I logged in with zitadel-admin
I logged out all users.
I logged in with a normal user.
I went to that normal users page and to my surprise I saw things I never should have seen.  

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/201257/184ae75b-c101-41f7-9858-5e4776869862)
![image](https://github.com/zitadel/zitadel/assets/201257/eb0de20b-c58d-414c-a4aa-8c22694ec4dd)

### Expected behavior

Show only stuff that is in conext of the user.

**Comment by hifabienne** [comment]
I do not completally agree on that end. It might be the case in your use case that the user should not see what happend.
But in other use cases I also want to see if someone else did some changes on my user, e.g changing my password, etc.
I will add the issue to the product backlog for now, to collect if this is something important for other customers as well.

**Comment by ghstahl** [comment]
Tangentially related.  I still need to be able to completely remove that ```last changes``` UI panel all together through configuration for normal users.  

Also these panels;
```Metadata```
```Memberships```
```Authorization```

**Comment by chezgi** [comment]
also in metadata panel i can edit metadata.
