### ISSUE TITLE
[Bug]: Upgrade to zitadel v2.41.5 floods with errors

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#6998]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.5

### Database

PostgreSQL

### Database Version

14

### Describe the problem caused by this bug

 working v2.39.4 with idp configs, etc.
No users, just the zitadel-admin.
Fully configured though with orgs and such. 

Docker latest
windows

### To reproduce

Upgrade to zitadel v2.41.5
login with zitadel admin 

[Logs](https://gist.github.com/ghstahl/92607574d57eae613b4b3e3e17c84615)

**Comment by hifabienne** [comment]
@adlerhurst @stebenz can you help here?

**Comment by adlerhurst** [comment]
Postres version < 16 don't work on the latest release

**Comment by ghstahl** [comment]
I can't remember which version we had to pick up for a bug fix or feature.  Greater than the stable v2.37.3
Can you give me the latest that still works on postgres 14.

I will be the first to try the new one out once you certify it good for < 16.

Be Aware: we can't switch to postgres 16 because we get postgres via a DBaaS provider.  They only support 15.5 at the moment.

**Comment by adlerhurst** [comment]
https://github.com/zitadel/zitadel/pull/6971 is included in version 2.42 which should fix the error of postgres versions <= 15

The "migration already started, ..." error can be solved by executing `zitadel setup cleanup`-command

**Comment by ghstahl** [comment]
I am a little confused why I would need to call ```zitadel setup cleanup```.  Is there any reason that this isn't wholly managed by zitadel itself.  

I would expect all I should have to do is.
1. docker-compose up using zitadel ```v2.37.3```
2. docker-compose down
3. change zitadel image to ```v2.24.x```
4. docker-compose up

Migrated should be successfully and no errors.

**Comment by adlerhurst** [comment]
> I am a little confused why I would need to call `zitadel setup cleanup`. Is there any reason that this isn't wholly managed by zitadel itself.

There are cases where migrations might fail like lost of database connection during setup. At this point the admin might have to clean up states, implementing every corner case is difficult. 

> 
> I would expect all I should have to do is.
> 
> 1. docker-compose up using zitadel `v2.37.3`
> 2. docker-compose down
> 3. change zitadel image to `v2.42.x`
> 4. docker-compose up
> 
> Migrated should be successfully and no errors.

This is definitely what we aim for, but nonetheless this is the happy path and works for most migrations but not for every corner case.

Our goal is to make migrations as smooth as possible which exactly matches your expectation :)

**Comment by hifabienne** [comment]
As the solution has been provided I will close this issue.
Feel free to reopen if you still have the issue and can provide more information
