### ISSUE TITLE
update protoc plugin helper

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#700]
github.com/golang/protobuf/protoc-gen-go/generator is deprecated
exchange with google.golang.org/protobuf/compiler/protogen

**Comment by fgerschwiler** [comment]
@livio-a is this still relevant? Or can we close this?

**Comment by fforootd** [comment]
I have no opinion to this

**Comment by livio-a** [comment]
has been solved with #5708 and #5798
