### ISSUE TITLE
[Bug]: can't terminate user session using service account

### ISSUE THREAD

**Issue by sp132** [zitadel/zitadel#7011]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.0

### Database

CockroachDB

### Describe the problem caused by this bug

1. Can't terminate user sessions using service account with `Org User Manager` role (tried `Org Owner` as well). Error I'm getting is `membership not found (AUTHZ-cdgFk)`. Sessions were created prior to upgrade.
2. After granting `Iam User Manager` problem goes away, but sessions owned by the organization aren't actually deleted. They are still being returned by `/v2beta/sessions/search`
3. There is no migration path for adding `session.delete` permission to the Org/Iam roles. I had to go over PR to understand what was actually changed and add role permissions manually to our config file. If this a correct way to upgrade, it should probably go into release notes or upgrade instructions.

### To reproduce

The first part kinda tricky to reproduce, because reproduction scenario requires sessions that were created prior to 2.42.0. I assume this happens because of change in resource ownerships. Session have been owned by the organization, but since 2.42.0 it's owned by the instance, by the looks of it.

**Comment by hifabienne** [comment]
@stebenz @livio-a can you help here?

**Comment by livio-a** [comment]
Hey @sp132 

Sorry for the late reply... i now checked the case and could mostly reproduce it.

As you described, the sessions itself are now owned by the instance and it seems like there is an issue in handling the "old" sessions.
I'll try to provide a fix ASAP.

**Comment by sp132** [comment]
@livio-a appreciate it, thanks!
