### ISSUE TITLE
Actions: Use organization metadata in complement token flow

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7023]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Organization metadata can not easily be sent with a user token or userinfo endpoint. There are use cases where I want to define metadata that should be available for all users.

Learned through discovery call:
One such case would be where you have a custom org/tenant id that must be sent as part of the JWT to your application to cater for the migration from a legacy auth system to ZITADEL.

### Describe your ideal solution

As developer, I want to be able to access orgnization metadata in the complement token flow, so I can provide that information in tokens/userinfo endpoint.

### Environment

ZITADEL Cloud

### Additional Context

relates to https://github.com/zitadel/zitadel/issues/5101

**Comment by hifabienne** [comment]
@livio-a @adlerhurst 
If we would implement the org metadata scope to be able to request the metadata within a token, would that also solve this issue? Could the user then request the org metadata get that in the token and be able to access it from the actions?
Or would it be better to implement in the actions directly?

Org Metadata Issue: https://github.com/zitadel/zitadel/issues/4419

**Comment by hifabienne** [comment]
@mffap There are two different possiblities.
Do we need the metadata as custom claims? In that case extending the actions would be the right thing.
Or is is enough to just be able to return the metadata in the token/userinfo. in that case the org metadata scope would be suitable: #4419

**Comment by mffap** [comment]
> @mffap There are two different possiblities. Do we need the metadata as custom claims? In that case extending the actions would be the right thing. Or is is enough to just be able to return the metadata in the token/userinfo. in that case the org metadata scope would be suitable: #4419

Because of migration scenarios I would lean towards Actions

**Comment by hifabienne** [comment]
@stebenz @peintnermax can you please estimate this issue?

**Comment by mffap** [comment]
+1 from inbound call

**Comment by stebenz** [comment]
I think it should take 1-2 days.

Changes to do:
- userinfo_by_id.sql extend with org metadata (user_org contains already the organization)
- scope added to logic and documentation
- availability of org metadata in action for the possibility of adding to the claims (no setting of org metadata) 
- action examples 

@peintnermax opinion?

**Comment by peintnermax** [comment]
> I think it should take 1-2 days.
> 
> Changes to do:
> 
> * userinfo_by_id.sql extend with org metadata (user_org contains already the organization)
> * scope added to logic and documentation
> * availability of org metadata in action for the possibility of adding to the claims (no setting of org metadata)
> * action examples
> 
> @peintnermax opinion?

agree on that 👍
