### ISSUE TITLE
Extend User Service: Read Side

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7030]
We want to extend the user service with some methods of the old apis.

**Acceptance Criteria**
- [ ] List User (Search) existing Filters are included
- [ ] Get User By ID
- [ ] User Exists
- [ ] User by loginname (search user?)
- [ ] API Tests are written for all functions

Questions:
How do we want to handle list requests? Which data to return (example user with all data, with some data, small/fullblown)
Should we already mark old requests as deprecated? How do we state which ones are the new reqeusts?

**Comment by hifabienne** [comment]
@muhlemmer @livio-a Can you please have a look at this issue for estimation?
Its the follow up issue of the one in the current sprint.
https://github.com/zitadel/zitadel/issues/6434

**Comment by livio-a** [comment]
> How do we want to handle list requests? Which data to return (example user with all data, with some data, small/fullblown)
We propose the currently return the same fields in the list as we do now. When user schema is implemented we can change that to the user (caller) being able to specify what fields of the schema should be return.

> Should we already mark old requests as deprecated? How do we state which ones are the new reqeusts?
 I would do that only after going GA

> List User (Search) existing Filters are included
> Get User By ID
> User Exists
> User by loginname (search user?)
User by loginname and User Exists can be solved by list users

Additional change will be that users can now be retrieved from other organizations as well and the list users must be able to handle that (check permission) and also be able to specifically filter for an organization if wanted

**Comment by quochuydev** [comment]
Hi team. has the required password change attribute issue been resolved?
references:
https://github.com/zitadel/zitadel/issues/6434
https://github.com/zitadel/zitadel/issues/6614
