### ISSUE TITLE
[Bug]: id_token_hint invalid for user session after some idle time

### ISSUE THREAD

**Issue by roquie** [zitadel/zitadel#7035]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.42.0

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

https://discord.com/channels/927474939156643850/1178715038136148028

SPA OIDC client integration

I caught this error with my client that integrates with zitadel. The client is a JS library oidc-client-js (ts) with token update functionality in the background. 

> SilentRenewService._tokenExpiring: Error from signinSilent: Unfortunately, the user may not be logged in and/or additional interaction is required.

Apparently the bug is on the zitadel side as stated in this issue. Could you give me a hint, is it fixed?

https://github.com/dotnet/aspnetcore/issues/50812

Logs 1:
```
2023/11/28 12:54:49 WARN auth request oidc_error.description="Unfortunately, the user may be not logged in and/or additional interaction is required." oidc_error.type=interaction_required
2023/11/28 12:54:56 WARN auth request oidc_error.description="Unfortunately, the user may be not logged in and/or additional interaction is required." oidc_error.type=interaction_required
2023/11/28 12:55:02 WARN request error oidc_error.parent="token has expired" oidc_error.description="id_token_hint invalid" oidc_error.type=invalid_request
```

Logs 2 (I'm not sure if this is related, but it may well be):

```
2023/12/06 07:29:04 WARN request error oidc_error.parent="invalid signature (invalid signature: no possible keys matches)" oidc_error.description="id_token_hint invalid" oidc_error.type=invalid_request
time="2023-12-06T07:56:13Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:266" error="ID=APP-ASdgg Message=invalid token"
time="2023-12-06T07:56:13Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:266" error="ID=APP-ASdgg Message=invalid token"
time="2023-12-06T07:56:13Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:266" error="ID=APP-ASdgg Message=invalid token"
time="2023-12-06T07:56:15Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:266" error="ID=APP-ASdgg Message=invalid token"
time="2023-12-06T07:56:15Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:266" error="ID=APP-ASdgg Message=invalid token"
2023/12/06 08:39:09 WARN request error oidc_error.parent="invalid signature (invalid signature: no possible keys matches)" oidc_error.description="id_token_hint invalid" oidc_error.type=invalid_request
2023/12/06 08:39:12 WARN request error oidc_error.parent="invalid signature (invalid signature: no possible keys matches)" oidc_error.description="id_token_hint invalid" oidc_error.type=invalid_request
```

### To reproduce

1. Create project, create app with user-agent SPA settings
- Redirects URIs
http://localhost:8080/auth/signinpop/main
http://localhost:8080/auth/signinwin/main
http://localhost:8080/auth/signinsilent/main
then copy client_id 
2. Create a sample vue app and integrate it with package: https://github.com/soukoku/vue-oidc-client
3. Type login & password, close tab
4. Wait a some time, may be 1-3-5 hours 
5. Open a new tab with vue sample project and catch an error:

![изображение](https://github.com/zitadel/zitadel/assets/3214290/d9f4761f-2027-4de5-b1c4-35cb81bd9bf8)

### Expected behavior

working normally

### Operating System

OS: Mac 13.2.1
Browser: Chrome Version 121.0.6140.0 (Official Build) canary (arm64) or Firefox or any browser

**Comment by hifabienne** [comment]
@muhlemmer @livio-a can you help here?

**Comment by livio-a** [comment]
Looks like we just forgot about it: https://github.com/zitadel/zitadel/issues/5232

There are two reasons for this:
Either the token has expired (bug in our OIDC library)
or the the token was signed with a key, that is not available anymore.
The session (incl. access_token) will therefore not be valid anymore.

@hifabienne But looks like more and more people run into this and we should try to find a solution. With the integration of v3 we should now be able to handle it (custom implementation of EndSession)

**Comment by hifabienne** [comment]
hei @roquie 
I would close this issue to not have to handle the duplicates, i just asked for estimation for the other issue, so we can plan it for a future sprint.

**Comment by codersaadi** [comment]
still getting this error , is it solved?  i wonder why it has been closed when there is no solution , everyone is just assuming here what might be the problem

**Comment by muhlemmer** [comment]
This was closed as duplicate. Refer to the linked issue to see the resolutions we took. #5232
