### ISSUE TITLE
[Bug]: Zitadel account auto creation not working using Okta as an OIDC provider

### ISSUE THREAD

**Issue by oscarcalderonc** [zitadel/zitadel#7038]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.1

### Database

CockroachDB

### Database Version

v23.2

### Describe the problem caused by this bug

Currently we are trying to implement Okta within Zitadel. We already configured Okta as an authentication option in zitadel at the organization level.

We configured the OIDC provider to automatically create an user with the options in the first screenshot.

Also in "Login Behavior and Security" the option "Username Password allowed" was unchecked, and checked the "Disable login with email address", so that causes that, when loading the zitadel authorized link, it takes us to the Okta login directly (which is nice).

We authenticate in Okta without issues; however then, instead of landing into our application (the URL configured as callback), we are taken into a zitadel screen that just says "External User not found" (2nd screenshot).

It seems like auto creation feature is not working.

If I enable "Account creation allowed" I'm able to create an account, but that's not what we want. Also, it is weird that, having to create a zitadel account to link it to an external account, you are asked to verify the email, and being asked to enable MFA when you already have that on okta side, and verify the email address.

### To reproduce

- Configure Okta as an OIDC provider using these instructions: https://zitadel.com/docs/guides/integrate/identity-providers/okta
- Enabling the following checkboxes for the OIDC provider:
    - Automatic Creation
    - Automatic Update
- Enable the OIDC provider
- In "Login Behavior and Security":
    - Uncheck "Username Password allowed"
    - Check "Disable login with email address"
- Navigate to URL `https://[your-domain]/oauth/v2/authorize?client_id=243656644137910285%40some_pry&redirect_uri=http%3A%2F%2Flocalhost%3A3005%2Fcallback&response_type=code&scope=openid+profile+email+urn%3Azitadel%3Aiam%3Aorg%3Aproject%3Aid%3A243656593084776461%3Aaud&state=65f27fb8cd234dc992242a4f328cbb15&code_challenge=__16J2R6S_c6maMfpRxeUtPmZil7X1Gi2M8GlrlIch8&code_challenge_method=S256&response_mode=query` using your instance parameters
- Authenticate with Okta
- Zitadel user creation page loads instead of creating user automatically

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/70549595/1f29e7d5-aea2-44c9-a69c-2b273be837bc)
![image](https://github.com/zitadel/zitadel/assets/70549595/9ed5d1d8-d8cc-4612-a49d-125f7c13c655)
<img width="624" alt="image" src="https://github.com/zitadel/zitadel/assets/70549595/8b7edff0-ed00-473c-b9cb-c6967405ff6b">
<img width="616" alt="image" src="https://github.com/zitadel/zitadel/assets/70549595/13fb07d3-15c7-4023-8f4a-20243d3fec4b">
<img width="631" alt="image" src="https://github.com/zitadel/zitadel/assets/70549595/1957a705-4d5a-4bfa-a1a2-439940b96bc5">

### Expected behavior

To get the zitadel user account automatically created, and right after the okta login, get redirected to the configured redirect_uri

### Operating System

Device: Mac
OS: Sonoma 14.1.1
Browser: Firefox
Version: 120.0.1

**Comment by oscarcalderonc** [comment]
Regarding third bullet already found out what fields I do need to populate, using zitadel logger prints

**Comment by hifabienne** [comment]
Hei @oscarcalderonc 
You are absolutely right, I wasn't actually fully aware that those infos are not sent.
Will definitely improve the docs.
If you do have an example action that works, and fills the information correctly I would also be glad to get an example. Otherwise will figure out how to do it. But can't promise an eta yet. :)

**Comment by oscarcalderonc** [comment]
Sure! I ended up using zitadel logger to print the information coming from Okta and based on that I made this simple script:

```
let logger = require("zitadel/log")

function mapOktaOauth(ctx, api) {
  logger.log('Populating extra information for new Okta user');

  if (ctx.v1.externalUser.externalIdpId != "243980621926367243") {
    return
  }
  api.setFirstName(ctx.v1.providerInfo.name);
  api.setLastName(ctx.v1.providerInfo.name);
  api.setEmailVerified(ctx.v1.providerInfo.email)
  api.setEmail(ctx.v1.providerInfo.email)
  api.setPreferredUsername(ctx.v1.providerInfo.preferred_username)
}
```

**Comment by hifabienne** [comment]
I have added your action to the actions repository: https://github.com/zitadel/actions/pull/25
And extended the docs: https://github.com/zitadel/zitadel/pull/7060
Thanks for your help.

**Comment by robclancy** [comment]
> Hei [@oscarcalderonc](https://github.com/oscarcalderonc) ZITADEL is only able to auto create the user within ZITADEL, if all the required field are filled. If that is not the case we do show the screen with the values so the user has to fill the missing fields. In your case I can see that Given and Family name are not filled. So I guess Okta does not send those. You can autofill the fields by adding a zitadel action. you can find an example in the github guide (github doesn't send all the information either) https://zitadel.com/docs/guides/integrate/identity-providers/gitlab#optional-add-zitadel-action-to-autofill-userdata
> 
> If the email address is added as verified or not is also taken from the information that ZITADEL gets from Okta. If that field is not filled, and you want the email address to be verified you can also set that with the ZITADEL action.
> 
> If you do not want the mfa prompt, you can configure the multifactor init life time to 0, in that case the popup will not be shown anymore: https://zitadel.com/docs/guides/manage/console/instance-settings#login-lifetimes

The UI should mention this. How are we meant to magically know that there are required fields missing? We just get this (typo) error "Neither creation of linking is allowed on this provider. Please contact your administrator. (LOGIN-3kl44)".
