### ISSUE TITLE
[Bug]: Profile picture URL in token for self-hosted doesn't include port

### ISSUE THREAD

**Issue by mmurto** [zitadel/zitadel#7055]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.1

### Database

CockroachDB

### Describe the problem caused by this bug

The URL for profile picture embedded in the token doesn't include the used port for self hosted instance, so it doesn't work when developing.

`picture: 'http://localhost/assets/v1/244303919566618628/users/244306032539467780/avatar?v=eb20ec61f03375f4655798a1c0ccae51'` should be `http://localhost:8080/assets...`.

### To reproduce

1. Start Zitadel on localhost
2. Upload a profile pic for user
3. Check the URL in App

**Comment by stebenz** [comment]
Hi @mmurto 

There were already changes done some time ago, and as I successfully tested this again will close this issue.
Thanks for the report and if still a bug persists, please reopen the issue.
