### ISSUE TITLE
Login Lifetimes Subzero values

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7065]
As an administrator I should not be able to set the login lifetimes to subzero values, as this results in a loop on the login ui.

**Acceptance Criteria**
- [ ] The minimum value for the multifactor init lifetimes is 0
- [ ] All other login lifetimes should only be allowed to set positive numbers > 0 (As I am not able to login anymore otherwise)
- [ ] I am not able to set negative numbers
- [ ] I am not able to set invalid values through the api
- [ ] I am not able to set invalid values in the console

<img width="1001" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/c3d844d8-0d07-41c6-9a62-c54028e286d5">

**Comment by Sidd-77** [comment]
I would like to work on this issue
Can you assign it to me

**Comment by chay2199** [comment]
@hifabienne Please assign this to me.

**Comment by muhlemmer** [comment]
Fixed in https://github.com/zitadel/zitadel/pull/7113
