### ISSUE TITLE
UX: CSRF invalid token errors

### ISSUE THREAD

**Issue by roquie** [zitadel/zitadel#7074]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Sometimes users (myself included) encounter this error: CSRF token invalid (Internal)

This happens if you have forgotten the login form in the browser tab for a long time. Then you entered the login-password or decided to continue the session by selecting your user from the list and you get an error.

The user gets the error as part of Zitadel's built-in login UI. On the domain where Zitadel is hosted, not in the SPA application itself. And then you are at a loss not knowing what to do next or where to click. Even if you are a developer. In my opinion it adds to the feeling that "something doesn't work" and I would like to get rid of it.

### Describe your ideal solution

I'm not suggesting removing the security mechanism itself, it's absolutely necessary. I'm suggesting to make a "Try login again" button on this page or to show this error immediately where you can continue the login process with a new CSRF token that was issued after the page refresh.

### Version

2.42.1

### Environment

Self-hosted

### Additional Context

<img width="907" alt="Screenshot 2023-12-13 at 16 29 27" src="https://github.com/zitadel/zitadel/assets/3214290/6ad58ca6-d327-4d50-a000-bd885b0bd3a8">

**Comment by hifabienne** [comment]
@livio-a @muhlemmer can you give your input here?

**Comment by muhlemmer** [comment]
As CSRF has failed, we can't trust the payload of the form, like the auth request ID. Therefore we can't restart the login flow from the beginning. The user will just have to abandon the tab and go back to the app he wanted to login to.

CSRF will change anyway in the new login, as it will be build in NextJS. We probably do not even manage CSRF manually there either.

**Comment by muhlemmer** [comment]
But what is the user logging-in to? The user only gets to the login because an application redirected you there in the first place. Even the zitadel console is acting as a regular OIDC application.

So when we redirect a user back to login, we need to be able to tell the login which auth request we are handling. The only way to know this is from the request data. Which (as I mentioned before) cannot be trusted at this point.
