### ISSUE TITLE
fix states on user_grants3 projection

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7124]
https://github.com/zitadel/zitadel/pull/7123 fixed a type cast error which ignored reactivation of user grants. this means that the projection is currently wrong. we need to provide a fix which corrects the data

**Comment by hifabienne** [comment]
@adlerhurst can you please let me know the urgency of this.
Is it something we can fix in a bug fixing friday?
Do we have to plan it for a next sprint?

**Comment by muhlemmer** [comment]
After #7194 is merged we can bump the projection version to force re-projections. Can be done during bugfix friday.

**Comment by hifabienne** [comment]
can we close this issue?

**Comment by muhlemmer** [comment]
yes! The user grants projection has since been updated to version 5.
