### ISSUE TITLE
[Bug]: Unable to switch to Action to complement token.

### ISSUE THREAD

**Issue by sanjaypaudel35** [zitadel/zitadel#7150]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.3

### Database

PostgreSQL

### Describe the problem caused by this bug

I am unable to switch flow to complement token, When i switched and refresh the page it reset again to External Authentication, actually i was trying to add custom claim on access token.

### To reproduce

step1: Go to action
step2: Create action add some field on access token
step3: switched Flow Type from External Authentication to Complement Token
step4: Add trigger
step5: Select trigger type to "Pre Access token Creation:
step6: Select action to "Adding Custom Claim"
step7: Click to save
step8: Refresh the page
step9: Flow type reset to External Authentication.

### Screenshots

[
![zitadel_action](https://github.com/zitadel/zitadel/assets/42547119/5bd3a0e0-04cb-42ec-81f4-5c2860fb4fa0)
](url)

### Operating System

Chrome, ubuntu22

**Comment by sanjaypaudel35** [comment]
@hifabienne any update regarding the issue above ?

**Comment by hifabienne** [comment]
Hei @sanjaypaudel35 
I am not sure what you mean with your issue.
I just tried it myself, so you can't change an added action at a specific trigger, but you can delete it.
So if you want to have an action at an other trigger, you have to delete it on the old trigger and add it on the new one.

I tested it myself, and I can add the same action to each trigger if I want.

If that doesn't work, please send a screenrecording of what you are doing.

**Comment by sanjaypaudel35** [comment]
[Screencast from 10-1-24 10:45:46 पूर्वाह्न +0545.webm](https://github.com/zitadel/zitadel/assets/42547119/4ea03559-59e4-4eea-ae70-38f32e4df80a)

This is how i have done, But it did'nt work.

**Comment by sanjaypaudel35** [comment]
I have save the name of the action same as the function name, but is still does'nt work

[Screencast from 11-1-24 11:24:00 पूर्वाह्न +0545.webm](https://github.com/zitadel/zitadel/assets/42547119/27877dbd-cac5-4c86-b205-d0756fb29d1c)

**Comment by hifabienne** [comment]
@stebenz @peintnermax can you help here?

**Comment by sanjaypaudel35** [comment]
> @stebenz @peintnermax can you help here?

Yeah it's been already week i m stuck on this.

**Comment by stebenz** [comment]
@sanjaypaudel35 besides the action name which is not equal to the function in the action, I see no problem, as the first video unfortunately is cut where I guess a problem should arise.
That the ExternalAuthentication flow has no actions is correct as you added the action to the ComplimentToken flow.
So can you please elaborate on this problem further as to what should be the problem and what to expect?

**Comment by hifabienne** [comment]
I will close this issue due to inactivity.
Feel free to reopen, if problem still exists and you can provide more information
