### ISSUE TITLE
Identity Provider

### ISSUE THREAD

**Issue by arunrajac** [zitadel/zitadel#7168]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

<img width="1066" alt="Screenshot 2024-01-08 at 3 10 08 PM" src="https://github.com/zitadel/zitadel/assets/142791868/75e280b9-99ae-427d-804b-335596f9ffe0">
<img width="1063" alt="Screenshot 2024-01-08 at 3 10 20 PM" src="https://github.com/zitadel/zitadel/assets/142791868/69a1560b-f35a-4ee6-b88d-a115dd69be0b">
<img width="585" alt="Screenshot 2024-01-08 at 3 26 49 PM" src="https://github.com/zitadel/zitadel/assets/142791868/85f51567-a948-488d-ab4a-7cd7207e995d">

i referred documentation and added identity provider but still not showing in login screen

**Comment by hifabienne** [comment]
I will close this issue as the discussion is already started here: https://github.com/zitadel/zitadel/discussions/7155
