### ISSUE TITLE
Customize the profile 'Documentation' button

### ISSUE THREAD

**Issue by K-J-VV** [zitadel/zitadel#7175]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

On the user Home/Profile page there is a 'Documentation' button that hyperlinks to https://zitadel.com/docs . I would like to have this button be customizable (i.e., change the name of the button & the hyperlink

The code for the hyperlink appears to be located here? 
console/src/app/pages/home/home.component.html

The reason being: most basic users have no interest/need to refer to the Zitadel documentation from their profile page. They're already aware in my case it is zitadel since our url is zitadel.example.com. Something that would be **incredibly** useful is if this hyperlink could be changed to point towards **internal documentation**. That way we can use the profile page to help users navigate the sites we are using Zitadel to protect

`    <div class="home-grid-container">
      <a href="https://zitadel.com/docs" target="_blank" rel="noreferrer" class="grid-item">
        <div
          class="icon-wrapper"
          [ngStyle]="{
            background: (themeService.isDarkTheme | async) ? bluedark + 50 : bluelight + 50
          }"
        >`

### Describe your ideal solution

A UI interface would be ideal, specifically located within the Instance Settings section & the Organization Settings section. Since different organizations may have their own documentation sites. 

### Environment

Self-hosted

### Additional Context

hosted within docker

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog.

**Comment by doncicuto** [comment]
Hei @hifabienne can you assing this issue to me?

**Comment by doncicuto** [comment]
Hi, I'll start working on this issue on friday

**Comment by doncicuto** [comment]
As promised, I've already started to code this feature, I'll keep you informed. Thanks

**Comment by doncicuto** [comment]
Hi there, in case you have a different opinion about the implementation here's a brief.

The documentation link will be customized for Instance (Default Settings) and Ord showing in the side menu like this:

![image](https://github.com/zitadel/zitadel/assets/30386061/e38f1da2-cc2f-4e1a-8a72-6086f92ba278)

A simple component will allow us to change the link to the docs:

![image](https://github.com/zitadel/zitadel/assets/30386061/9d7d6ded-d2cd-4660-bdb2-485f90c90eaa)

Also the default docs url can be set using the ZITADEL_DEFAULTINSTANCE_DOCSSETTINGS_EXTERNALLINK env variable or setting a value in the defaults.yml:

```
 DocsSettings:
    ExternalLink: https://zitadel.com/docs 
```

Next week it will be finished, probably :smile:

**Comment by K-J-VV** [comment]
Looks great to me! 

Only additional wish I could think of is to change the text of the button from Documentation to anything custom (e.g., Home, Guides, Logout, Accounts, etc.). Just in case the button is supposed to send a user to a place other than Documentation

**Comment by doncicuto** [comment]
Thanks @K-J-VV, I'll think about it this weekend :smile:

**Comment by doncicuto** [comment]
Hi, let's see if this change is suitable for all people implied

I suggest creating two separate settings: one allows us to change the Docs link, the other one allows us to have a custom link that can be named as you prefer.

![image](https://github.com/zitadel/zitadel/assets/30386061/473d6cfa-eb6b-4391-9a61-580227ce9f52)

Custom and/or Docs links will only bee shown if the link setting is not empty:

All settings will be available in the same place where the rest of links live: policy, tos, support email...

![image](https://github.com/zitadel/zitadel/assets/30386061/38f27dc2-4370-49bf-adf4-17a198d88695)

And I suggest renaming the side menu to External Links as it's not only now about privacy policy:

![image](https://github.com/zitadel/zitadel/assets/30386061/6d0eb3a0-41f8-4325-9528-19152c933b24)

In my opinion I think it's best to have one setting for Documentation which is a fixed string that can be translated right now and another one for custom link that can be different from Documentation as @K-J-VV suggests. 

What do users or @fforootd, @hifabienne, @mffap, @peintnermax think about this proposal?

Thanks in advance

**Comment by K-J-VV** [comment]
@doncicuto your idea to separate these is actually ideal imo

link to internal documentation to for users to guide themselves through issues

extra button for extra stuff (most likely usecase I can envision is a link to a dashboard of services or an org homepage)

**Comment by hifabienne** [comment]
From my perspective this looks good. 
One question. I am not sure what the second link is about? and where it should be shown?
Also would be great to get the opinion of @peintnermax

**Comment by doncicuto** [comment]
Hei @hifabienne the other link would be a custom link that is available for any use the op can think about as @K-J-VV suggested, a link that can be customized both the text and the link. In this screenshot the custom button would be shown to the left of the Documentation button.

![image](https://github.com/zitadel/zitadel/assets/30386061/53b0c18e-05b8-4da5-a620-61668b48337b)

Of course by default that additional button is hidden.

**Comment by K-J-VV** [comment]
> Hei @hifabienne the other link would be a custom link that is available for any use the op can think about as @K-J-VV suggested, a link that can be customized both the text and the link. In this screenshot the custom button would be shown to the left of the Documentation button.
> 
> ![image](https://github.com/zitadel/zitadel/assets/30386061/53b0c18e-05b8-4da5-a620-61668b48337b)
> 
> Of course by default that additional button is hidden. 

@hifabienne my reasoning for this additional button is often in the Account/Security pages of most accounts (Google, NextCloud, etc.) there is some sort of "Home" button that takes users back to the platforms main/primary page after they are down resetting passwords or updating account info

**Comment by peintnermax** [comment]
thx @doncicuto and @K-J-VV for your collaboration. We highly recommend to build your own UI for your user self service. 
I like the change of having a external links section in the console though and appreciate if you have done any work on that 👍
As the custom button is optional, I am personally fine of introducing it 😎

**Comment by doncicuto** [comment]
Thanks @peintnermax  and @hifabienne. I'm therefore continuing with this PR as the suggested approach has been accepted. Once I finish adding some cypress tests I'll upload the PR

**Comment by K-J-VV** [comment]
> Thanks @peintnermax  and @hifabienne. I'm therefore continuing with this PR as the suggested approach has been accepted. Once I finish adding some cypress tests I'll upload the PR

Thank you for taking time to do the work and implement this idea/request, very much appreciated!
