### ISSUE TITLE
[Bug]: Custom Login UI - SMS code authentication - Call to v2beta/sessions/SESSIONID triggers too many sms

### ISSUE THREAD

**Issue by charanraj-golla** [zitadel/zitadel#7186]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.1

### Database

CockroachDB

### Database Version

11.1.5 using helm chart

### Describe the problem caused by this bug

I am trying the SMS code authentication flow for building custom Login UI which allows user to log in using SMS OTP. I am referring to this section of the documentation https://zitadel.com/docs/guides/integrate/login-ui/mfa#sms-code-authentication

The initial call to `[POST] /v2beta/sessions` triggers an SMS OTP. 
Next call to `[PATCH] /v2beta/sessions/SESSION-ID-FROM-PREVIOUS-RESPONSE` triggers too many SMS with the same message body. All the  SMS contains the same OTP. The OTP keeps getting sent till the application is stopped.
![image](https://github.com/zitadel/zitadel/assets/3887634/5c196464-fab3-4095-a676-438e1972e791)
![image](https://github.com/zitadel/zitadel/assets/3887634/d31db98c-26bc-4f60-948b-e5a7a31f1f67)

### To reproduce

Configure SMS provider in Zitadel Instance -> Instance Setting -> SMS/Phone Provider
Add details for Twilio account and activate the settings

 For an existing user in an organization ensure the phone number is added and verified.
![image](https://github.com/zitadel/zitadel/assets/3887634/da861f22-5202-4c4b-94b4-87f3b7731fcd)

Create a service account for the organization and generate a Personal Access Token to use as the bearer token for making API call.

Add Authorization header using Bearer token 
Make HTTP call to `[POST] /v2beta/sessions`
Body:
```
{
  "checks": {
    "user": {
      "loginName": "existing.email.verified.user@gmail.com"
    }
  },
  "challenges": {
    "otpSms": {
      "returnCode": false
    }
  }
}
```

Using the session id, session token and OTP from SMS from previous response 
Make HTTP call to `[PATCH] /v2beta/sessions/SESSION_ID_FROM_PREVIOUS_RESPONSE`
Body:
```
{
  "sessionToken": "A-BF2KbEj38o3f6NCMwZyjg4VjMVUkhZ_aT3QXRw7rf0VS0NkA4u0UJtOD2jzHobg1yG6fBORxu4RA",
  "checks": {
    "otpSms": {
      "code": "OTP_NUMBER_FROM_SMS"
    }
}
```

The application keeps sending OTP SMS till the application is stopped.

### Expected behavior

OTP should not be sent for the second HTTP call. User's session should be started.

### Operating System

Minikube on Windows 10 Home.
Application deployed using Helm chart version 7.4.0

**Comment by charanraj-golla** [comment]
Thanks for letting me know.

**Comment by quochuydev** [comment]
Hi @charanraj-golla, Are you aware of sms rate limiting? (Where will it be processed? Login BE or SMS service or Zitadel)

**Comment by charanraj-golla** [comment]
@quochuydev unfortunately I am not aware about this. And I am not sure if I have seen anything like this in Zitadel UI / configuration
