### ISSUE TITLE
Manage impersonation permission/allowance

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7209]
As a supporter I want to be able to get a token for another user, to be able to do requests on behalf of the specified user.
I need a possibility to restrict the allowance

**Acceptance Criteria**
- [x] The security setting are extended with an "enable impersonation"
- [x] I can set the setting through the API (v1 management & v2 reading)
- [ ] I can set the setting through console
- [ ] Documentation is extended
- [x] A new manager role is defined "ADMIN_IMPERSONATOR" with the permission "admin.impersonation" and "impersonation", this user is allowed to impersonate all users
- [x] A new manager role is defined "END_USER_IMPERSONATOR"  with the permission "impersonation" 
- [x] Both roles can be given on the Instances as well as on the organization level

**Comment by hifabienne** [comment]
@livio-a @muhlemmer can you please estimate the issue?

**Comment by livio-a** [comment]
we also need to make sure, the settings service is updated accordingly

**Comment by hifabienne** [comment]
@eliobischof @stebenz Realised it is actually resources, Can you please estimate?
