### ISSUE TITLE
`prompt=select_account` automatically go to "Other User" when there is no account to choose

### ISSUE THREAD

**Issue by Congee** [zitadel/zitadel#7213]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

If you log into zitadel by appending the query parameter `prompt=select_account` it always shows the account selection page even if there is no account to select. In this case, the user has to choose "Other Account" anyway. 
![image](https://github.com/zitadel/zitadel/assets/2083950/0c749fbb-f242-496f-bd70-e34795a50d5d)

### Describe your ideal solution

Can we just automatically go the "Other Account" path?

### Environment

Self-hosted

**Comment by hifabienne** [comment]
@muhlemmer @livio-a whats your opinion on that?

**Comment by livio-a** [comment]
I've checked the specs. from what i see the user has to select any account. it does not specify exactly how. as we already allow the `other user` option, the user has the possibility "select" a none existing session and still be compliant with the specs.
BTW. others (Google, Azure, ...) do the same

i'll move i into the backlog / small issues list
