### ISSUE TITLE
Ressource API GA

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7236]
As a ZITADEL customer I want to have the new APIs in a GA state, so I am sure I can rely on them and do not have breaking changes.
The beta APIs should still be available, so if I use them, I do not have to change on the date where ZITADEL does release the new APIS as GA.

**Acceptance Criteria**
- [ ] We have released all current resource APIs as GA
- [ ] Beta APIs are still accessible
- [ ] The API Documentation is clearly structured, and I know which APIs I should take
- [ ] On the old request in the management, admin, auth services I see that the request is deprecated, and I have a reference to the new implementation
- [ ] We do have a clear instruction about the new and the old APIs in our APIs introduction, which tells the current state the plans and where to search for API calls: https://zitadel.com/docs/apis/introduction
- [x] Remove deprecated organization fields for GA: https://github.com/zitadel/zitadel/issues/6718

**Comment by hifabienne** [comment]
@stebenz @eliobischof can you please estimate this?

**Comment by eliobischof** [comment]
> @stebenz @eliobischof can you please estimate this?

@stebenz 1.5?

**Comment by stebenz** [comment]
> > @stebenz @eliobischof can you please estimate this?
> 
> @stebenz 1.5?

I would do 2, as there are still a lot of moving parts, or is that too much?

**Comment by eliobischof** [comment]
@hifabienne done

**Comment by eliobischof** [comment]
should we close it in favor of #7821?

**Comment by fforootd** [comment]
> should we close it in favor of #7821?

Can you elaborate a little why #7821 can close this issue?
I do not fully comprehend the scope of the linked PR. 😁

**Comment by hifabienne** [comment]
@eliobischof @stebenz This issue goes back to investigation to find out how we get to the point to have our new api GA.
