### ISSUE TITLE
Command Side for  Executions

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7242]
As an administrator I want to be able to configure and manage executions in ZITADEL on an instance level. An execution is a definition of an external resource that should be called at a certain point.
Executions are highly dependent on the type:
- Response
- Request
- Event
- Function

## Acceptance Criteria
- [x] Feature is available as beta at the moment
- [x] This requests should be added in the "execution_service"
- [x] Executions are configurable on an instance level
- [x] The condition is the unique identifier of an execution
- [x] Only one execution per condition is allowed
- [x] Condition has to be verified to be available/existing
- [x] I am able to set an request execution, through the API with the fields stated below
- [x] I am able to set an response execution, through the API with the fields stated below
- [x] I am able to set an event execution, through the API with the fields stated below
- [x] I am able to set an function execution, through the API with the fields stated below
- [x] Condition is a required field
- [x] Target list can be empty
- [x] I am able to remove the execution
- [x] Based on the type of the execution only the corresponding conditions are allowed, I do get an error if I have an non matching condition
- [ ] circular dependency detection of includes is implemented

## Questions to answer
- Should the API have one generic endpoint? Set Execution where I can send a type in the body (Response, Request, Function, Event)
- Or should we do separate endpoints for each type?
- If its one endpoint for all types, do I have an endpoint to get conditions based on a type?

### Request Execution Fields

 - [x] Condition: A condition can either be a proto method, a proto service or all requests 
    - [x] each proto method (e.g. UserService.AddHuman)
    - [x] each proto service (e.g. UserService)
    - [x] all requests
 - [x] Targets: ordered list of one of the following types
    - [x] target: id of a predefined target
    - [x] include: id of another condition

### Response Execution Fields

 - [x] Condition: A condition can either be a proto method, a proto service or all requests 
    - [x] each proto method (e.g. UserService.AddHuman)
    - [x] each proto service (e.g. UserService)
    - [x] all requests
 - [x] Targets: ordered list of one of the following types
    - [x] target: id of a predefined target
    - [x] include: id of another condition

### Function Execution Fields

 - [x] Condition: Conditions should be analgo the actions v1, e.g ExternalAuthentication.Pre, ExternalAuthentication.Post, InternalAuthentication.PreRegister, ComplementToken
 - [x] Targets: ordered list of one of the following types
    - [x] target: id of a predefined target
    - [x] include: id of another condition

### Event Execution Fields

- [x] Condition: A condition can either be a specific event, or an event group (user.human.added, user.human*, user.*, *)
    - [x] specific event
    - [x] event group
    - [x] all event
- [x] Targets: ordered list of one of the following types
    - [x] target: id of a predefined target
    - [x] include: id of another condition

**Comment by hifabienne** [comment]
can you please estimate this?

**Comment by stebenz** [comment]
depend on #7243 for target definition

Estimation:
- service defintion: 1d
- conditions from proto service and method: 1d (@adlerhurst said he already played around with it)
- execution events: 1d
- hierarchical include: 1d
- hierarchical check in tests for include to avoid endless loop: 1d
