### ISSUE TITLE
Command Side for Execution Targets

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7243]
As a administrator I want to be able to configure execution targets on an instance level. A target specifies an endpoint that should be called by a certain execution.

## Acceptance Criteria
- [x] Feature should only be available as beta at the moment
- [x] This requests should be added in the "execution_service"
- [x] Targets are configurable on an instance level
- [x] I am able to create a target, through the API with the fields stated below
- [x] I am able to update a target, through the API with the fields stated below
- [x] I am able to remove a target, through the API
- [x] The name of the target should be unique
- [x] The url is validated as a valid url
- [x] timeout is > 0
- [x] Interrupt on error is false per default

## Additional Information

Target Object Data:
- [ ] id: uid
- [ ] name: unique name of the target (e.g. ip_allow_list)
- [ ] type: one of the below options
   - [ ] REST webhook: Only response status is used by ZITADEL, response payload is ignored
   - [ ] REST request/response: response status and payload are used. The payload is used to manipulate the object
- [ ] url: URL to the REST POST endpoint
- [ ] timeout: duration until ZITADEL cancels the query
- [ ] async: if true the call is executed asynchronously
- [ ] InterruptOnError: If true errors are thrown and flow is stoped, if false errors are allowed and process continues as normal, if async is true this field is ignored

**Comment by hifabienne** [comment]
@eliobischof @stebenz Can you please estimate this?

**Comment by stebenz** [comment]
Estimation:
- target events: 1d
- service defintion: 1d
- value validation in proto?: 1d
