### ISSUE TITLE
Allow Sessions on different org than service user

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#7253]
Currently the user checks of sessions fail if the user is located in a different organization than the service user which does the call.

**Acceptance Criteria**

- [x] Checks of session don't fail if the user has a different resource owner than the service account

**Comment by ldabrowskiairspan** [comment]
FYI after experimenting more I've discovered that setting the `x-zitadel-orgid` header to the correct organization ID fixes the issue. It might be that all that's needed here is to reflect this in the API docs.

**Comment by livio-a** [comment]
As discussed with @stebenz the IDP flow should probably be migrated to the instance as RO. Check of that and implementation was prosponed in #7641 to another PR.

**Comment by stebenz** [comment]
Created #7656 to fix the intent resource

**Comment by livio-a** [comment]
i close this since, the last know issue is tracked in #7656
