### ISSUE TITLE
Spike: impersonation

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#7255]
As follow up on the discussion published here: https://github.com/zitadel/zitadel/discussions/7070, I would want to have a spike to formalize the proposal into issues for the technical implementation.

## Acceptance criteria

- [ ] Issues to implement a storage model. Eg, authorization of user A to impersonate user B.
- [ ] Issues to implement [OAuth2 Token Exchange RFC8693](https://github.com/zitadel/zitadel/discussions/7070#discussioncomment-7838722)
- [ ] Issues to implement [Session API Extension](https://github.com/zitadel/zitadel/discussions/7070#discussioncomment-7838731)

**Comment by hifabienne** [comment]
hei @muhlemmer 
We already have created some issues about impersonation.
This is the epic issue: https://github.com/zitadel/zitadel/issues/7208
Then there are some sub issues to it. linked in there.
