### ISSUE TITLE
[Bug]: Possible memory leak

### ISSUE THREAD

**Issue by danielmichalichyn** [zitadel/zitadel#7266]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.43.5

### Database

CockroachDB

### Database Version

23.1.13

### Describe the problem caused by this bug
Hello @adlerhurst  and @muhlemmer 
I'm noticing a strange behaviour by the Zitadel application that looks like a memory leak. I'm hosting Zitadel on a docker swarm, but my Zitadel container is running on a host dedicated for him and from time to time the container restarts by a OOM kill. Following is the memory usage graph for that specific host. Can you help me debug this and identify if there is a potencial memory leak?

### To reproduce

I'm running Zitadel self-hosted on Docker Swarm. There is a specific node for CockroachDB and a node for Zitadel App.
The Zitadel App is being killed by OOM from time to time.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/52325588/dc91e7d6-c34a-4348-b2b1-aad67fe5953d)

**Comment by muhlemmer** [comment]
Can you please share you zitadel config as a `yaml`? On my "mostly default" configured zitadel I'm not observing any memory leak.
If there are details in there you wish not to share, please write `<redacted>`.


Also, can you give some details about usage. How is zitadel used mostly by you mostly. (Eg, classic login, OIDC flow, SAML provider, APIv2 based login etc.

**Comment by muhlemmer** [comment]
Another question, does memory also grow during idle hours. Eg, when zitadel has almost nothing to do. Or, can you deploy a replication of zitadel on a swarm node that will not receive traffic to find out.

**Comment by muhlemmer** [comment]
There are no other reports of memory leaks. Also our cloud product has been stable on memory for an extended period of time on v2.43 and we recently deployed v2.44.1 which has even lower memory consumption. Probably you have something else on your host mis-behaving.

For example, is it possible you have some [docker logging drive](https://docs.docker.com/config/containers/logging/configure/)r setup that fills up a `tmpfs` on the host? Zitadel can be pretty noisy if you have debug logging enabled.

As we didn't get any replies, closing this issue for now.

**Comment by Enissay** [comment]
@danielmichalichyn can you please share your stack file ? trying to deploy it in swarm as well...
