### ISSUE TITLE
[Bug]: Upgrade from 2.41 to higher version break the instance

### ISSUE THREAD

**Issue by giovannicandido** [zitadel/zitadel#7267]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.14

### Database

CockroachDB

### Database Version

23.1.14

### Describe the problem caused by this bug

Zitadel instances in unable to function.

Logs:

time="2024-01-20T01:38:18Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=159
 
22:38:18.893
time="2024-01-20T01:38:18Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:19.894
time="2024-01-20T01:38:19Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="ID=CRDB-YdOXD Message=create savepoint failed Parent=(sql: transaction has already been committed or rolled back)" projection=projections.apps6
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=197
 
22:38:20.397
time="2024-01-20T01:38:20Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:21.398
time="2024-01-20T01:38:21Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="ID=CRDB-pKtsr Message=exec failed Parent=(sql: transaction has already been committed or rolled back)" projection=projections.apps6
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=158
 
22:38:21.901
time="2024-01-20T01:38:21Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:22.462
2024-01-20 01:38:22.462 UTC [498] LOG stats: 0 xacts/s, 0 queries/s, 0 client parses/s, 0 server parses/s, 0 binds/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
 
22:38:22.902
time="2024-01-20T01:38:22Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:23.404
time="2024-01-20T01:38:23Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:24.405
time="2024-01-20T01:38:24Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=warning msg="unable to get failure count" aggregate=229919536432808994 caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/failed_event.go:53" error="ID=CRDB-Unnex Message=unable to update failure count Parent=(sql: transaction has already been committed or rolled back)" instance=227082933419115299 projection=projections.apps6 sequence=159
 
22:38:24.913
time="2024-01-20T01:38:24Z" level=warning msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:264" error="sql: transaction has already been committed or rolled back" projection=projections.apps6
 
22:38:25.914
time="2024-01-20T01:38:25Z" level=info msg="scheduled trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:153" error="sql: transaction has already been committed or rolled back" instance=227082933419115299 projection=projections.apps6

### To reproduce

1. Install version 2.41.14 in kubernetes.
2. Upgrade

### Expected behavior

Upgrade is sucessfull

### Operating System

Kubernetes v 1.28.2 OKE (Oracle Cloud)

**Comment by michelkaeser** [comment]
Same issue here.

    level=error msg="statement execution failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472" error="sql: transaction has already been committed or rolled back" projection=projections.users10
