### ISSUE TITLE
[Bug]: Issue running actions when unmarshalling response on external authentication with Okta

### ISSUE THREAD

**Issue by oscarcalderonc** [zitadel/zitadel#7275]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.41.6

### Database

PostgreSQL

### Database Version

14

### Describe the problem caused by this bug

Okta Workforce Identity has been registered as an IDP provider. Automatic user creation was enabled in the IDP provider configuration, so it is expected to get the user created automatically. As some fields cannot be obtained automatically from Okta data provided for zitadel, an action was needed to map the fields accordingly to Okta data (covered in this issue https://github.com/zitadel/zitadel/issues/7038 ).

This flow works fine for one of the Okta users, but for another one, the action execution fails. The action is configured as External Authentication -> Post Authentication. Printing the error with zitadel logger using this:

`logger.log("ctx", JSON.stringify(ctx.v1.authError));`

Gives us this output:

```
time="2024-01-22T16:05:50Z" level=info msg="log record emitted" caller="/home/runner/work/zitadel/zitadel/internal/logstore/emitters/stdout/stdout.go:19" record="{\"logDate\":\"2024-01-22T16:05:50.438418241Z\",\"took\":0,\"message\":\"ctx \\\"failed to unmarshal response: oidc: language: subtag \\\\\\\"us\\\\\\\" is well-formed but unknown into *oidc.uiAlias {\\\\\\\"sub\\\\\\\":\\\\\\\"00u1ppl2fDdImw6bQ000\\\\\\\",\\\\\\\"name\\\\\\\":\\\\\\\"John Doe\\\\\\\",\\\\\\\"locale\\\\\\\":\\\\\\\"US\\\\\\\",\\\\\\\"email\\\\\\\":\\\\\\\"hello@okta.com\\\\\\\",\\\\\\\"nickname\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"preferred_username\\\\\\\":\\\\\\\"hello@okta.com\\\\\\\",\\\\\\\"given_name\\\\\\\":\\\\\\\"Joe\\\\\\\",\\\\\\\"middle_name\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"family_name\\\\\\\":\\\\\\\"Doe\\\\\\\",\\\\\\\"zoneinfo\\\\\\\":\\\\\\\"America/Los_Angeles\\\\\\\",\\\\\\\"updated_at\\\\\\\":1702999806,\\\\\\\"email_verified\\\\\\\":true}\\\"\",\"logLevel\":\"info\",\"instanceId\":\"244777729604452470\"}"
```

It looks like the raw data coming from Okta contains some information (us) that breaks the unmarshalling of such information into zitadel. The key portion of the message is this:

`failed to unmarshal response: oidc: language: subtag "us" is well-formed but unknown into *oidc.uiAlias`

UPDATE: Here's another log that shows the line where the error is thrown:

```
time="2024-01-22T18:20:04Z" level=error msg="both external user authentication and action post authentication failed" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/external_provider_handler.go:1082" error="failed to unmarshal response: oidc: language: subtag \"us\" is well-formed but unknown into *oidc.uiAlias {\"sub\":\"00u1ppl2fDdImw6bQ696\",\"name\":\"John Doe\",\"locale\":\"US\",\"email\":\"jdoe@okta.com\",\"nickname\":\"\",\"preferred_username\":\"jdoe@okta.com\",\"given_name\":\"John\",\"middle_name\":\"\",\"family_name\":\"Doe\",\"zoneinfo\":\"America/Los_Angeles\",\"updated_at\":1702999806,\"email_verified\":true}"
```

https://github.com/zitadel/zitadel/blob/f9f9573e516f495866507b4a614290d7a933b20b/internal/api/ui/login/external_provider_handler.go#L1082

### To reproduce

- Configure Okta Workforce Identity as an IDP provider
- Configure an action that tries to auto create user in External Authentication -> Post Authentication with code like this:
```
let logger = require("zitadel/log")

function mapOktaOauth(ctx, api) {
  logger.log(ctx.v1.authError);
  api.setFirstName(ctx.v1.providerInfo.name);
  api.setLastName(ctx.v1.providerInfo.name);
  api.setEmailVerified(ctx.v1.providerInfo.email)
  api.setEmail(ctx.v1.providerInfo.email)
  api.setPreferredUsername(ctx.v1.providerInfo.preferred_username)
}
```
- try to login with your Okta account 
- Not sure about what piece of information makes unmarshalling to fail

### Expected behavior

Not getting the error described above

**Comment by oscarcalderonc** [comment]
Hello, sorry for bugging you, but, are there any updates/findings regarding this? We are relying on keeping one of our clients by making sure Okta authentication through zitadel works fine for all users, and some users are able to login while others experience the issue.

**Comment by livio-a** [comment]
Hey @oscarcalderonc 

Sorry for the late response. We've fixes this some time ago, but had to figure out on which versions.
Can you please upgrade to 2.41.14. This should solve the issue.

**Comment by oscarcalderonc** [comment]
@livio-a thank you very much, that did the trick.
