### ISSUE TITLE
Azure AD / Entra ID SAML IdP integration guide

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7278]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

There is no guide for setting up AzureAD as Identity Provider via SAML. Setting up SAML is not straight forward and requires some guidance on our end to make it work.

**Comment by adlerhurst** [comment]
example: https://github.com/zitadel/actions/pull/31
