### ISSUE TITLE
Provide IDP URL information in details

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7281]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When setting-up an identity provider, users need to know the URL information. Only provide (partial) information on these endpoint is provided in the docs. When integrating SSO configuration into an application, I want to request these endpoints to show it to the end-user.

### Describe your ideal solution

As Developer, I want to get the important URLs for my IDP, so I can show it to the end-user (Manager that sets up SAML for their org).

```[tasklist]
### Acceptance criteria
- [ ] The details of a SAML IDP show Metadata URL
- [ ] The details of a SAML IDP show ACS URL
- [ ] The details of a SAML IDP show Logout URL
- [ ] The details of google IDP show Callback URL
- [ ] The details of microsoft IDP show Callback URL
- [ ] The details of github IDP show Callback URL
- [ ] The details of github enterprise IDP show Callback URL
- [ ] The details of gitlab IDP show Callback URL
- [ ] The details of gitlab self hosted IDP show Callback URL
- [ ] The details of apple IDP show Callback URL
- [ ] The details of generic OIDC IDP show Callback URL
- [ ] The details of an Oauth IDP show Callback URL
- [ ] Update docs of IDPs (including picutres)
```

### Open questions

Should we show a popup after creation which shows these information as well? analog to application creation

### Environment

ZITADEL Cloud

**Comment by mffap** [comment]
related maybe #6717

**Comment by adlerhurst** [comment]
SAML idps:

![image](https://github.com/zitadel/zitadel/assets/27845747/942cf218-48bf-407f-adce-0e5fd7888ac7)

**Comment by adlerhurst** [comment]
OIDC:

![image](https://github.com/zitadel/zitadel/assets/27845747/f7ca248a-63c1-4759-92b3-eeb3509a8659)

**Comment by hifabienne** [comment]
> OIDC OAuth idps:
> 
> ![image](https://private-user-images.githubusercontent.com/27845747/312739478-f7ca248a-63c1-4759-92b3-eeb3509a8659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDE2NTksIm5iZiI6MTcxMDQwMTM1OSwicGF0aCI6Ii8yNzg0NTc0Ny8zMTI3Mzk0NzgtZjdjYTI0OGEtNjNjMS00NzU5LTkyYjMtZWViMzUwOWE4NjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YjE0YWI1YmI3ZTIxMjNlZjE1ZjNhMzU4YzMzOTkyZjkzNWY0YjYxMTVhNzE3MDRhNzc5Mjk3YTJmODZlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YLsJV400X_4Iodazxf_jNRfqIQaHB2N-i8Dy3w__H_E)

I think we should also add the logout url
