### ISSUE TITLE
Set icon on generic OAuth / OIDC Identity Providers

### ISSUE THREAD

**Issue by thepaperpilot** [zitadel/zitadel#7288]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I have a custom identity provider setup and it looks out of place without an icon like the google, github, etc. auth buttons have.

### Describe your ideal solution

I'd like to be able to either upload or include a link to an image within the identity provider settings, that will be displayed on the registration and login pages.

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hi @thepaperpilot 
thanks for adding an issue, but we already have one for the same improvement.
To avoid duplicates I will close this one here.
Would be great if you can leave a reaction on the other issue so we are able to track how many are interested in it.
https://github.com/zitadel/zitadel/issues/5455
