### ISSUE TITLE
Command Side for User Schemas / Objects on Instance Level

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7306]
As a ZITADEL Admin I am able to manage User Schemas through the API, to be able to define how my users objects should look like and how the different types of users can authenticate.

## Acceptance Criteria
- [x] CreateUserSchema: adds a new schema
- [x] UpdateUserSchema: changes an existing schema.
- [x] DeactivateUserSchema: moves the schema to a read only state. Users of this schema cannot be updated anymore. Users are still able to log in
- [x] ReactivateUserSchema: moves the schema state to active
- [x] DeleteUserSchema: Removes an existing schema. This operation is only allowed if there are no associated users

## Open Questions
- How to handle the permissions? admin/user? Something relating to the permissions we already have internally?

### User Schema
* **id**: read only unique identifier
* **state**: state of the schema
* **type**: single word which describes the schema
* **revision**: read only version of the schema, each update increases the revision
* **schema**: describes the user
* **possibleAuthenticators**: defines the possible types of authenticators. this allows creating different user types like human/machine without usage of actions to validate possible authenticators. Removal of an authenticator does not remove the authenticator on a user
  * TODO: move user.isOrgSpecific to here (on username and idp)

#### permission

Following permissions are allowed r (4), w (2), rw (6)
* admin: defines the permissions of the admin
* user: defines the user of the user

#### oidcClaim / samlMapping
It is needed to define the oidc Claim and saml mapping so ZITADEL knows how to map the user infromations to the oidc / saml responses/tokens

#### additional formats

* **phone**: possibility to add declare phone numbers
* **language**: language tag analog to [ietf bcp 47](https://www.rfc-editor.org/info/bcp47)

**Comment by hifabienne** [comment]
@stebenz @eliobischof 
Can you please estimate this issue?

**Comment by stebenz** [comment]
Depend on #7308 for DeleteUserSchema
depend on #7314 for possibleAuthenticators

technical estimation:
- schema events: 1d
- schema validation: 1d
- api definition: 1d
- permission checks: 1d
- integration tests: 1d
- command side definitions + unit tests: 1d
