### ISSUE TITLE
Query Side for User Schemas / Objects

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#7307]
As a ZITADEL Admin I am able to read User Schemas through the API, to be able to find out how my users objects should look like and how the different types of users can authenticate.

## Acceptance Criteria
 - [x] **ListUserSchemas**: lists latests states schemas
 - [x] **UserSchemaByID**: shows details of a specific schema

### User Schema
* **id**: read only unique identifier
* **state**: state of the schema
* **type**: single word which describes the schema
* **revision**: read only version of the schema, each update increases the revision
* **schema**: describes the user
* **possibleAuthenticators**: defines the possible types of authenticators. this allows creating different user types like human/machine without usage of actions to validate possible authenticators. Removal of an authenticator does not remove the authenticator on a user
  * TODO: move user.isOrgSpecific to here (on username and idp)

#### permission

Following permissions are allowed r (4), w (2), rw (6)
* admin: defines the permissions of the admin
* user: defines the user of the user

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you please estimate this issue?

**Comment by stebenz** [comment]
Depend on #7306 for content
depend on #7314 for possibleAuthenticators

technical estimation:
- projection definition: 1d
- unit tests: 1d
- permission checks: 1d
- proto definitions: 1d
- integration tests: 1d
