### ISSUE TITLE
Prevent users from accessing Console

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7316]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

We have received several requests for preventing users to access Console. 
The use cases include:
- User Management is integrated into their own app
- Users login via SSO and should not be able to change their data in Console
- Only Managers should be able to access Console to manage their organization's users

There is currently no simple configuration to turn off the console, thus we should describe the recommended workaround in our https://zitadel.com/docs/guides/solution-scenarios/configurations

## Self-hosted

- Recommended way is to restrict access via WAF/reverse-proxy for non-Manager users

### Default Redirect URI

The Default Redirect URI will be used, if a user calls the login page directly. More specifically, typically a client will initiate login with an [auth request](https://zitadel.com/docs/apis/openidoauth/authrequest). The auth request contains a client-id and a redirect uri, that must match the configuration in ZITADEL. If there is no auth request, users will be redirected to the Default Redirect URI, which is by default https://<custom_domain>/ui/console/

Change default redirect url of instance: https://<custom_domain>/ui/console/settings?id=login 

### Restricting Console in default-project

With this workaround, you will limit users from accessing the default-project, if they are not explicitly granted to use this project.

When setting the following setting on a project, only users (or organizations) with a grant to that project can access it. By default this setting is disabled, so all users can access the project.

<img width="573" alt="Screenshot 2024-01-30 at 12 36 25" src="https://github.com/zitadel/zitadel/assets/1366906/07a61b02-4e4e-4726-a74b-e28ff3b4e44e">

Start by granting the organization of your Managers the project: 

Click on the default-project > Grants > New +

<img width="997" alt="Screenshot 2024-01-30 at 12 45 18" src="https://github.com/zitadel/zitadel/assets/1366906/169960b7-04e0-43dc-ad6b-d0bc46629045">

On the next screen select the organization. Follow-the wizard to the end and click save.
<img width="707" alt="Screenshot 2024-01-30 at 12 45 05" src="https://github.com/zitadel/zitadel/assets/1366906/d83e1988-647d-4aaa-a7e6-7dcbf0750e19">

Make sure the grant is in now in the overview and marked as active.

To avoid accidental lock-out, the default project hides the checkbox "Check Project on Authentication" in the Console: 

<img width="1181" alt="Screenshot 2024-01-30 at 12 36 09" src="https://github.com/zitadel/zitadel/assets/1366906/8bf2d0b8-2be4-4e4b-b89d-4e517448b69a">

You need to use the [update project](https://zitadel.com/docs/apis/resources/mgmt/management-service-update-project) API call to set the configuration on the project.

First you need an User with Manager permissions to change the Project settings in that organization. This means either you add the manager to the organization or you use a Manager on the Instance level with IAM-Owner permissions.

Create a PAT for the Manager.

Then you have to send the following request:

```
CUSTOM_DOMAIN=
PAT=
PROJECT_ID=
PROJECT_NAME=
```

Where 
- CUSTOM_DOMAIN is your domain, f.e. b2b-demo-rbxajm.zitadel.cloud
- PAT is your service user's personal access token
- PROJECT_ID is the default-project's ID that can be found in Console, see screenshot above
- PROJECT_NAME is the default-project's name as shown in the Console

```
curl -L -X PUT "https://$CUSTOM_DOMAIN/management/v1/projects/$PROJECT_ID" \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H "Authorization: Bearer $PAT" \
--data-raw '{
  "name": "$PROJECT_NAME",
  "projectRoleAssertion": false,
  "projectRoleCheck": false,
  "hasProjectCheck": true,
  "privateLabelingSetting": "PRIVATE_LABELING_SETTING_UNSPECIFIED"
}'
```

You should be able to login with users that have the grant (in this example users of the organization "Demo-Vendor"). All other users should see the following error message after authentication:

<img width="723" alt="Screenshot 2024-01-30 at 13 01 28" src="https://github.com/zitadel/zitadel/assets/1366906/f0267f99-8c2d-4d2e-8ae8-b2f915f2f65e">

### Additional Context

- https://github.com/zitadel/zitadel/issues/5994
- https://github.com/zitadel/zitadel/issues/7077

**Comment by schettn** [comment]
> Default Redirect URI
> 
> The Default Redirect URI will be used, if a user calls the login page directly. More specifically, typically a client will initiate login with an [auth request](https://zitadel.com/docs/apis/openidoauth/authrequest). The auth request contains a client-id and a redirect uri, that must match the configuration in ZITADEL. If there is no auth request, users will be redirected to the Default Redirect URI, which is by default https://<custom_domain>/ui/console/
> 
> Change default redirect url of instance: https://<custom_domain>/ui/console/settings?id=login

I've already configured the redirect URL at the organization level, but it doesn't seem to be working as expected. Despite setting the redirect URL at the organization level, users are still being redirected to the console for actions like phone number verification, email verification, password reset, etc. I am aware that you described to set the redirect URL at the instance level (which works for me), but I'm wondering if there's a way to configure it at the organization level to ensure it applies universally across all relevant user actions. Is there a specific configuration step or additional setting required for this?

**Comment by nilsmehlhorn** [comment]
Even when setting up the default redirect URI at instance and organization level, the password changed notification e-mail will contain a login link pointing to the Zitadel console itself. Could this point to the default redirect URI instead? IMHO it's a bit too tricky to white-label Zitadel right now. Thanks for your consideration.

**Comment by holgerson97** [comment]
> Even when setting up the default redirect URI at instance and organization level, the password changed notification e-mail will contain a login link pointing to the Zitadel console itself. Could this point to the default redirect URI instead? IMHO it's a bit too tricky to white-label Zitadel right now. Thanks for your consideration.

Has there been an update on this already?

**Comment by dragetd** [comment]
I just stumbled over the same issue. We have a default redirect to our page but the Password-Reset Mail has a direct link: https://id.xxxxxx/ui/console?login_hint=draget@xxxx

The documentation https://zitadel.com/docs/guides/solution-scenarios/restrict-console#self-hosted suggests using the reverse-proxy. I am using traefik where I can filter the URL, but this would block it for any user. Reading the OIDC token info is a PITA.

It would be nice if these mails could be configurable somehow, and/or if we could disable the console selectively.

**Comment by feliwir** [comment]
We use Zitadel as a IAM and have some issues with the password-reset workflow.
The expected behaviour is like this:

1. User or Organization admin triggers password-reset workflow via https://zitadel.com/docs/apis/resources/user_service_v2/user-service-password-reset
2. User receives an E-Mail with a link where he can reset his password
3. After succesful completion of the password reset workflow he gets redirected back into our application
**Actually: The user does get redirected into his account overview in the console**
4. User receives an E-Mail that his password was changed together with a login link
5. When pressing the button the user gets redirected into our application
**Actually: The user does get redirected into his account overview in the console**

Another issue we're facing is that the password reset-workflow also features a back-button that takes the user into his account console aswell:

<img width="471" height="729" alt="Image" src="https://github.com/user-attachments/assets/b94960d0-151a-42a3-9284-f17dde470dc1" />

We'd like to hide that back-button altogether, since it makes no sense when opening that workflow via E-Mail
