### ISSUE TITLE
Setup Organization API - IAM roles

### ISSUE THREAD

**Issue by m-arre** [zitadel/zitadel#7339]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.44.1

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

The Setup Organization API (`/admin/v1/orgs/_setup`) only works if the IAM user role is `IAM Owner`. I'd expect it to be accessible even with `IAM Org Manager` and `IAM User Manager` roles.

### To reproduce

1. Assign `IAM Org Manager` and `IAM User Manager` roles to a user
2. Call the Setup Organization API
3. Request fails
4. Change the IAM user role to `IAM Owner`
5. Call the Setup Organization API
6. Request succeeds

**Comment by hifabienne** [comment]
Hi @m-arre 
For now we have defined that only the iam owner is able to setup new organizations.
As you are self hosting, you can also edit the roles and permissions in the defaults.yaml file

**Comment by m-arre** [comment]
@hifabienne thank you for the response. 
Is there any documentation about the necessary permissions for this endpoint?

**Comment by hifabienne** [comment]
Unfortunately we do not show the permissions in the documentation.
You can see which permission is needed here: https://github.com/zitadel/zitadel/blob/main/proto/zitadel/admin.proto#L823
