### ISSUE TITLE
[Bug]: Can't activate user

### ISSUE THREAD

**Issue by roquie** [zitadel/zitadel#7351]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.44.2

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

1. User have Initial status and have verified email in their profile.
2. I can't set up a new password for this user because it has Initial state. 
3. And I trying to use workaround via manually activating because sending emails doesn't work

### To reproduce

Select user on the users list page with Initial state and click on "Activate" green button. Nothing going here, only popup message about success. 

Then, I go to the Network tab in Chrome DevTools and I don't see any requests except ListUsers. I think I should see there requests to change user state....

### Screenshots

<img width="1728" alt="Screenshot 2024-02-07 at 12 46 32" src="https://github.com/zitadel/zitadel/assets/3214290/c330bc2e-a79b-422c-9cee-37e1de50d777">
<img width="1057" alt="Screenshot 2024-02-07 at 12 47 43" src="https://github.com/zitadel/zitadel/assets/3214290/1b222381-cf04-4de8-9cef-093b9b241364">

### Expected behavior

State changed and admin should have an alternative way to manage user password and state without external dependency like smtp which can crash.

**Comment by hifabienne** [comment]
Hi @roquie 
As long as the user is in an initial state, you need to active the user by sending the initialize email.
You should see a banner on the detail page to resend the initial email:
<img width="1200" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/1b5abefd-e552-4604-9d9d-965d9bb61b13">

**Comment by stebenz** [comment]
@roquie This initial state will be removed through usage of the v2 API.
If the user is created specifically that the user has to define a password, in my opinion it is correct, that the admin is not able to clear this state without the approval of the user. 
If you want to solve this situation as an admin, you can just delete and recreate the user with a verified email and a defined password.

I will close this issue, please reopen if there is any issue with this, or an idea how we can solve this problem.
