### ISSUE TITLE
[Bug]: Model window for changing email does not have correct container

### ISSUE THREAD

**Issue by roquie** [zitadel/zitadel#7352]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.44.2

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

see screenshots

### To reproduce

1. open any user
2. click on change email pencil icon

### Screenshots

<img width="561" alt="Screenshot 2024-02-07 at 12 57 12" src="https://github.com/zitadel/zitadel/assets/3214290/02fc2bc1-4395-416e-821f-afcd5c74cafd">

**Comment by fforootd** [comment]
I could reproduce this as well.

Might have something to do with this error 
<img width="405" alt="image" src="https://github.com/zitadel/zitadel/assets/9879976/69d9e251-3225-4e68-8d19-42e5ba1dbab1">

**Comment by hifabienne** [comment]
This has been fixed, will close the issue
