### ISSUE TITLE
[Bug]: repeated "reduce failed" errors reported

### ISSUE THREAD

**Issue by hexmode** [zitadel/zitadel#7353]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.44.2

### Database

CockroachDB

### Database Version

23.1.13

### Describe the problem caused by this bug

About once a second the following is logged in our zitadel container:
```
time="2024-02-07T14:55:04Z" level=debug msg="trigger failed"
    caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:261"
    error="ID=PROJ-0I91sp Message=Errors.NotFound" instance=242916770875179014
    projection=projections.user_grants4
time="2024-02-07T14:55:04Z" level=error msg="reduce failed" aggregate=usergrant
    caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/statement.go:47"
    error="ID=PROJ-0I91sp Message=Errors.NotFound" instance=242916770875179014
    projection=projections.user_grants4 sequence=1
time="2024-02-07T14:55:04Z" level=info msg="process events failed"
    caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:416"
    error="ID=PROJ-0I91sp Message=Errors.NotFound"
    projection=projections.user_grants4
```
We recently upgraded from 2.44.1 and, before that, 2.44.0 and 2.41.1

### To reproduce

We were importing some users, but I'm not sure why that would cause these errors to fill up the log even after we stopped.  We imported a few hundred users and had to stop when the container began consuming too much CPU.

### Operating System

Docker CE 25.0.1
Ubuntu Jammy (22.04.3)

**Comment by hexmode** [comment]
Found in Discord Just now: [Cannot add user grants](https://discordapp.com/channels/927474939156643850/1182569473165754398/1182569473165754398)

**Comment by hexmode** [comment]
From Discord:
> I saw this behavior from my system when I upgraded to 2.42. I was able to resolve by rolling back to 2.40 (what I was running before the upgrade). I believe it is related to the “spoiler stuck” issue that the 2.43 rcs appear to be aimed at fixing - if I understand the release notes correctly.

However, as noted above, we're on 2.44.

**Comment by hexmode** [comment]
Rolling back to 2.41.1 eliminated the errors in the log, so the problem is not fixed in 2.44 despite what the Discord comment says.

**Comment by fforootd** [comment]
Oh sorry to hear that, let us investigate what is going on here.

CC @livio-a @adlerhurst

**Comment by livio-a** [comment]
@stebenz can you please have a look at this as well? looks like there's an issue in getting the resourceowner of some part of the user grant
