### ISSUE TITLE
[Proposal] Migrate protos directory to its own repo.

### ISSUE THREAD

**Issue by Foxtrek64** [zitadel/zitadel#7354]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I am building my own API wrapper and want to consume the protobuf definitions you publish. However, cloning this entire repo just to get a small portion of the files is not really that appropriate, leaving me to either have to submodule the entire zitadel repo or manually maintain my local protos.

### Describe your ideal solution

Please break off the proto directory into its own GitHub repo that can be easily submoduled into other projects (like this Zitadel repo). This will allow Zitadel and third parties to consume the protobuf definitions in the same manner.

### Environment

ZITADEL Cloud

**Comment by fforootd** [comment]
Hm would it not be easier to use buf to generate your client code?

We use this in multiple places and the buf generator can fetch the protos of the subfolder directly.

Checkout the buf definiton here https://github.com/zitadel/zitadel/blob/main/proto/buf.yaml

This for example generates the client for angular https://github.com/zitadel/zitadel/blob/main/console/buf.gen.yaml

**Comment by hifabienne** [comment]
At the moment we don't intent to move the protos to a different repository.
Also as there was no reaction to the comment i will close this issue.
If we see a need in the future we can reopen it

**Comment by fforootd** [comment]
Just to add a thought here... buf can now use folders in the cli when generating stubs, so the UX is not as bad anymore as in the past 😁
