### ISSUE TITLE
[Bug]: Codecov PR reports are garbage

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#7357]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

NA

### Database

None

### Describe the problem caused by this bug

Codecov reports on PRs give incorrect (lack of) coverage. Usually the report complains about lines not touched by a PR. For example, this [documentation update](https://github.com/zitadel/zitadel/pull/7355).

### To reproduce

1. Create a PR
2. Wait for the pipeline to finish

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5411563/4d612755-a4c0-4864-ba4f-eb6912d1a1ee)

### Expected behavior

See a coverage report related to the diff of the current PR and no errors regarding missing uploads from `main`

### Additional Context

Ever since we have the new pipline Codecov reports are garbage. This seems to be because there are no coverage uploads for the `main` branch. We should enable the unit test and integration pipelines for the `main` branch again.

**Comment by fforootd** [comment]
I agree, the file is not found for the upload as it looks like on all branches https://github.com/zitadel/zitadel/actions/runs/7786217518/job/21230618774#step:8:26

**Comment by muhlemmer** [comment]
Code coverage reports are not posted on PRs at all anymore now. Did something change @stebenz?

**Comment by stebenz** [comment]
@muhlemmer seems like the token secret in the nested workflow for codecov was not provided so the report could not be uploaded, the token was updated a month ago but unfortunately I can't see who updated it in the repository
