### ISSUE TITLE
Suggestions for the Return Format of Token Payload

### ISSUE THREAD

**Issue by xianyu-one** [zitadel/zitadel#7362]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

During the debugging process of Oauth2 Connect, it was observed that when the "Assert Roles on Authentication" and "Check authorization on Authentication" features are enabled in Projects, the Token Payload returns in the following format:

```
{
 "amr": [
  "mfa",
  "user"
 ],
 "at_hash": "41-U7m3xI8XwsIWuF2MXcA",
 "aud": [
  "252731@xyz.io",
  "252827@xyz.io",
  "253077@xyz.io",
  "253084@xyz.io",
  "252699754973135882"
 ],
 "auth_time": 1707458703,
 "azp": "253084@xyz.io",
 "c_hash": "Ud8i49t31_k",
 "client_id": "253084@xyz.io",
 "email": "i@xyz.com",
 "email_verified": true,
 "exp": 1707501913,
 "family_name": "xyz",
 "given_name": "io",
 "iat": 1707458713,
 "iss": "https://sso.xyz.io",
 "locale": null,
 "name": "xyz",
 "nickname": "xyz",
 "picture": "https://sso.xyz.io.net/assets/v1/27c",
 "preferred_username": "xyzlezhi",
 "sub": "25270013460",
 "updated_at": 1707145456,
 "urn:zitadel:iam:org:project:2526997:roles": {
  "administrator": {
   "252699355457291274": "xyz.io"
  },
  "headscale": {
   "252699355457291274": "xyz.io"
  }
 },
 "urn:zitadel:iam:org:project:roles": {
  "administrator": {
   "252699355457291274": "xyz.io"
  },
  "headscale": {
   "252699355457291274": "xyz.io"
  }
 }
}
```

However, many applications that support role mapping are unable to recognize data in this format.

### Describe your ideal solution

It is suggested to add the following response format for roles:

```
{
  "roles": [
    "anonymous",
    "viewer"
  ]
}
```

This format is easier to use in some applications. For more information, please refer to the following links:

[ACL and RBAC Authorization](https://authp.github.io/docs/authorize/acl-rbac)
[Generic OAuth Role Mapping](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-role-mapping)

### Version

v2.37.3

### Environment

Self-hosted

**Comment by schettn** [comment]
In the meantime you could use https://zitadel.com/blog/custom-claims to modify the token through a [Action](https://zitadel.com/docs/concepts/features/actions).


For example:

```js
/**
 * Sets the roles as an additional claim in the token with roles as the value and project as the key.
 *
 * The role claims of the token look like the following:
 *
 * // Added by the code below
 * "grants": ["{projectId}:{roleName}", "{projectId}:{roleName}", ...],
 * "roles": ["{roleName}", "{roleName}"]
 * // added automatically
 * "urn:zitadel:iam:org:project:roles": {
 *   "asdf": {
 *     "201982826478953724": "zitadel.localhost"
 *   }
 * }
 *
 * Flow: Complement token, Triggers: Pre Userinfo creation, Pre access token creation
 *
 * @param ctx
 * @param api
 */
function flatRoles(ctx, api) {
    if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) {
        return;
    }
    let grants = [];
    let roles = []
    ctx.v1.user.grants.grants.forEach(claim => {
        claim.roles.forEach(role => {
            grants.push(claim.projectId + ':' + role)
            roles.push(role)
        })
    })
    api.v1.claims.setClaim('grants', grants)
    api.v1.claims.setClaim('roles', roles)
}
```

**Comment by livio-a** [comment]
Hey @xianyu-one 

The benefit of our format is, that we can supply multi tenant information.
You can however map the structure yourself into the required format: 
https://zitadel.com/docs/guides/integrate/services/google-cloud#zitadel-custom-claims
https://github.com/zitadel/actions/blob/main/examples/custom_roles.js

**Comment by xianyu-one** [comment]
Thank you for your reply! I have successfully attempted and tested as per the following links. Thank you for your assistance!

https://zitadel.com/docs/guides/integrate/services/google-cloud#zitadel-custom-claims
https://github.com/zitadel/actions/blob/main/examples/custom_roles.js
https://zitadel.com/blog/custom-claims
