### ISSUE TITLE
Avoid the use of gendered language in documentation

### ISSUE THREAD

**Issue by soupglasses** [zitadel/zitadel#7386]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

When registering a new account in a Zitadel SSO, the change-log states "Person registered himself".

I propose to use gender neutral language instead with the singular they, this would change the change-log example to "Person registered themselves" instead. This would follow what larger organizations like Github and Facebook do when referencing a person of unknown gender.

### Additional Context

This seems like a much deeper rooted issue, as it also seems to affect the documentation quite severely from looking over the following queries:

- https://github.com/search?q=repo%3Azitadel%2Fzitadel%20himself
- https://github.com/search?q=repo%3Azitadel%2Fzitadel+him
- https://github.com/search?q=repo%3Azitadel%2Fzitadel+his

**Comment by hifabienne** [comment]
Hi @soupglasses 
Thanks for pointing this out.
I have added a new section to our contribution guidelines.
I also searched the repository for himself, him, his and he and changed it to a neutral language.

It's still possible that we do have some places, where the language is not gender neutral, but we will give our best to avoid that in the future and change in the needed places.
