### ISSUE TITLE
Provide possibility to disable account creation if `auto creation` failed on IDP

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#7393]
IDPs currently offer the following two options, among others:
- `account creation allowed`: allow the user to create an account using an HTML form, which is pre-filled with the IDP provided information
- `auto creation`: automatically create an account based on the information, provided by the IDP, if it fails, show the form as well (with info). The user then can edit the necessary information and create the account themself.

A customer now reported, they would like to only allow autocreation. In case it fails, the user should not be able to edit / create themself.

**Acceptance criteria**
- [x] Provide mechanism to disable manual creation, but still allow `auto creation`
- [x] Login implements the new mechanism

**Comment by vs-gtadeu** [comment]
+1. We would really benefit from having this feature.

To give you some context, all our customers with external IDPs will be using enterprise identity providers like Okta and ADFS. In that scenario, the users' profiles are expected to be managed in those IDPs, meaning that the IDPs act as their source of truth. 

Displaying a form where users could update their profile information ends up being a problem for us. Users could update their information, causing mismatches between Zitadel and the IDP.

These mismatches can potentially cause communication problems between us and our customers. Additionally, more strict customers might not be happy to see that users can change their profile info without going through some formal internal process (e.g., emailing their IT department).
