### ISSUE TITLE
[Bug]: Can't delete current logged user

### ISSUE THREAD

**Issue by Yberion** [zitadel/zitadel#7395]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.45.0

### Database

CockroachDB

### Describe the problem caused by this bug

I'm trying to delete the current logged in user.
It seems to be possible with the following API call https://zitadel.com/docs/apis/resources/auth/auth-service-remove-my-user.

The error returned say `membership not found`.

The strange thing is that it is not possible with the UI Console (http://192.168.0.30:8080/ui/console/users/me).

### To reproduce

- Create an user account on a Zitadel
- Connect to http://192.168.0.30:8080/ui/console/users/me
- Get the value of `zitadel:access_token` from the Session Storage
- Execute the API from https://zitadel.com/docs/apis/resources/auth/auth-service-remove-my-user

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/4186385/fac3f423-a818-4d75-8316-1679f5a551df)

### Expected behavior

I should be able to delete my own account.

### Operating System

Windows 11

**Comment by hifabienne** [comment]
hei @Yberion 
To call the endpoint to delete my own account, you need a certain permission.
This permission is included in the ORG_USER_SELF_MANAGER role.
If you give the users that role, they should be able to delete themself

**Comment by Yberion** [comment]
Hello @hifabienne, thanks for the fast answer!

I have the scope `urn:zitadel:iam:org:project:id:zitadel:aud` in the lib config.

I added the Role to the project:

![image](https://github.com/zitadel/zitadel/assets/4186385/1da50322-87d6-4b86-b175-2f34e823e10d)

And then added the role to the user:

![image](https://github.com/zitadel/zitadel/assets/4186385/d6e417a1-81ae-4f83-918c-964f21a8f06a)

I disconnected and reconnected to get a new token.

Then tried a `GET` to `/auth/v1/users/me` and it worked.

I tried a `DELETE` to `/auth/v1/users/me` with the same token, but I'm still getting this error:

![image](https://github.com/zitadel/zitadel/assets/4186385/23dfc8c3-745e-49d6-80e6-65e404c912c9)

Am I missing something?

**Comment by hifabienne** [comment]
Yes you do not have to add that role to your project.
Memberships are the internal roles of ZITADEL.
You can find this on the organization detail, in the top left. (the avatar icons and the. + next to it)
Then search for the user and give him the ORG User Self Manager

<img width="1415" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/3b27ac9f-c947-49e5-9030-a1ad1560f34c">

**Comment by Yberion** [comment]
Hello @hifabienne,

Ok make more sens now, thanks again, it worked well. 😄
