### ISSUE TITLE
Bug: Device Authorization: Entering the redirect URL is not part of the app creation flow

### ISSUE THREAD

**Issue by dakshitha** [zitadel/zitadel#7397]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When creating a native app in ZITADEL and if I choose to go ahead with Device Auth, I am not asked to enter the redirect URLs as with the other flows but at the end, the UI shows a warning sign about the missing URLs. Shouldn't this be a part of the initial flow? 

<img width="1511" alt="image" src="https://github.com/zitadel/zitadel/assets/11885043/05946a82-509f-476e-8df5-c952ae35c3ac">

### Describe your ideal solution

The proposed solution will have a step to include the URL as with other flows. Or else remove the warning if it's not a compulsory step. 

### Environment

ZITADEL Cloud

**Comment by doncicuto** [comment]
Hi @hifabienne I'm taking this one. According to @peintnermax I think that redirect uris are not mandatory for the device code grant type so I'm modifying the backend code like this:

```
func checkRedirectURIs(compliance *Compliance, grantTypes []OIDCGrantType, appType OIDCApplicationType, redirectUris []string) {
	if len(redirectUris) == 0 && !containsOIDCGrantType(grantTypes, OIDCGrantTypeDeviceCode) {
		compliance.NoneCompliant = true
		compliance.Problems = append([]string{"Application.OIDC.V1.NoRedirectUris"}, compliance.Problems...)
	}
```

Just one thing I've a question is if the redirect settings menu entry should be available for this kind of application

**Comment by hifabienne** [comment]
@dakshitha Why do you need the redirect urls here?
Device Authorization doesn't need any redirect urls.

Hei @doncicuto Thanks for your offer. I am currently not sure why this redirect urls are needed. 
As device authorization doesn't need them, I would not shown them in the flow and also not in the menu.

So this is actually not a bug, but intended.

**Comment by dakshitha** [comment]
Yes, exactly. If it is not needed, why mention it at all? And as a warning.

**Comment by hifabienne** [comment]
ah got it the problem is, that the warning shows that we need a redirect url.
@doncicuto in that case the goal of the issue would be to change the warnings to reflect the device auth

**Comment by doncicuto** [comment]
Perfect @hifabienne, I'll remove the warning but if you don't mind I'll also tackle #5820 which is related with this one

**Comment by hifabienne** [comment]
perfect. thanks @doncicuto
