### ISSUE TITLE
Projects with SAML [Bug]: 

### ISSUE THREAD

**Issue by HungryHowies** [zitadel/zitadel#7405]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.45.0 

### Database

CockroachDB

### Database Version

v23.1.12

### Describe the problem caused by this bug

Creating  a Project  with SAML  Application for bookstack  using Option 1.  "Specify the url where metadata file is located".
 I recieve the following error.

```
SAML Metadata format error (SAML-bquso)
```

### To reproduce

Steps:
1. Latest version of Bookstack  with  apache2 and Let's Encrypt.
2. Using either Zitadel Cloud or  Self-host build v2.45
3. Create a new Project named "Bookstack"
4. Select SAML and name it Bookstack
5. Use Option 1  and place Bookstack  Metadat URL  in Option 1 slot
6. Click "Continue
7. Click Create

### Screenshots

Self-hosting v2.45, &&  v2.46 same results.

![image](https://github.com/zitadel/zitadel/assets/22652276/a85219d3-ba2e-46f4-8779-e5039b1f6adb)

Zitadel Cloud v2.45

![image](https://github.com/zitadel/zitadel/assets/22652276/8b330b7b-10eb-4ecf-bbdd-9be5c2f41609)
![image](https://github.com/zitadel/zitadel/assets/22652276/da9b1552-12a6-423f-a8a9-1b2ed6cf5ce6)
![image](https://github.com/zitadel/zitadel/assets/22652276/38af7dd2-8b92-4684-adb2-7f7bc13c888e)

### Expected behavior

 The Create button should make the XML file need for Bookstack.

### Operating System

Zitadel CLoud

Self-hosting = Ubuntu 22.0.4 4 CPU, 4 GB Ram

### Relevant Configuration

Basic  configuration on Zitadel Self-hosting. Only use HTTPS with Nginx.

### Additional Context

 
For testing purposes I created  a build with Version 2.37.3 and it worked. No error's or issues.

I then created  a couple more  Zitadel instance, ranging from ` v2.44.0,v2.45.0,v2.46.0`.   They  all failed. each on of these instance  was a fresh install.

**Comment by fforootd** [comment]
CC @stebenz 

Relates to https://discord.com/channels/927474939156643850/1019895518383583323/threads/1206913003312775188

**Comment by stebenz** [comment]
@HungryHowies Just to differentiate, the expected behaviour still exists but the error you are getting is in reading the Bookstack metadata.xml.
Could you please provide an example metadata.xml from your bookstack instance? So that we can try to sort out what the problem with this file format is? Did you also try to upload the file directly not only through the URL?

**Comment by HungryHowies** [comment]
Hey @stebenz 

Thx for the reply



> @HungryHowies Just to differentiate, the expected behaviour still exists but the error you are getting is in reading the Bookstack metadata.xml. 

This  is my  XML. 
NOTE: domain.com is my place holder.

```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2024-02-21T22:03:53Z" 
                             cacheDuration="PT604800S" entityID="https://bookstack.domain.com/saml2/metadata">
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" 
                             protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" 
                             Location="https://bookstack.domain.com/saml2/sls"/>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
                   <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" 
                               Location="https://bookstack.domain.com/saml2/acs" index="1"/>
            </md:SPSSODescriptor>
</md:EntityDescriptor>
```




> Did you also try to upload the file directly not only through the URL?

Yes that works great using the XML file upload and using Option 3: "Create a minimal metadata file on the fly providing ENTITYID and ACS URL". 

Also note that Zitadel Version 2.37.3 works great using the URL.  This works on all

**Comment by livio-a** [comment]
@stebenz i guess that the parsing might fail because of a missing header / content type mismatch when retrieving the metadata endpoint.

**Comment by eliobischof** [comment]
The console doesn't send the URL to the backend.
It's reproducible with [https://mocksaml.com/api/saml/metadata](https://mocksaml.com/api/saml/metadata) on save and update.
I'll try to fix it.
