### ISSUE TITLE
Login with email or phone number

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7409]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Some services, especially mobile-first, want users to login with their phone number. As alternative they let users register with email (or use email as recovery).

Examples are Facebook, Uber, Google etc. 

### Describe your ideal solution

As an end-user, I can enter my email or phone number or username on the login page, and continue to login with my user

### Environment

ZITADEL Cloud

### Additional Context

It is currently possible to login with [email](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-email-to-login) xor [phone number](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-phone-number-to-login) by changing the username format. This feature should allow users to be able to use either their phone number or email on the login screen, when this feature is enabled.

Seems like this feature is more useful in B2C cases than B2B cases.

**Comment by mffap** [comment]
> It is currently possible to login with [email](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-email-to-login) xor [phone number](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-phone-number-to-login) by changing the username format. This feature should allow users to be able to use either their phone number or email on the login screen, when this feature is enabled.

That's what I mentioned in the Additional Context, yes. Can a user enter either their email address or their phone number (not limited to one or the other) in the username field, like in the services mentioned above?

**Comment by hifabienne** [comment]
> > It is currently possible to login with [email](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-email-to-login) xor [phone number](https://zitadel.com/docs/guides/solution-scenarios/configurations#use-phone-number-to-login) by changing the username format. This feature should allow users to be able to use either their phone number or email on the login screen, when this feature is enabled.
> 
> That's what I mentioned in the Additional Context, yes. Can a user enter either their email address or their phone number (not limited to one or the other) in the username field, like in the services mentioned above?

yes they can use what they like to login.

**Comment by mffap** [comment]
Replaced by https://github.com/zitadel/zitadel/issues/7411
