### ISSUE TITLE
Localhost redirect without developer mode

### ISSUE THREAD

**Issue by xeor** [zitadel/zitadel#7415]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

There are multiple apps, that runs on the cli but wants to use oauth for authentication to the api running via web. A short trick they use is to fire up a oauth flow and start a tiny listener on localhost waiting for the auth via the browser. This is done by example git-credential-manager, argocd-cli and so on.

This flow can't be done without setting the developer-mode on the redirect page. Which doesnt feel good in production.

### Describe your ideal solution

Allow for "http" to be used when making a redirect url to "localhost" without toggling the developer-mode.
Example url "http://localhost:8085/auth/callback" (used with argocd)

### Version

7.4.0

### Environment

Self-hosted

**Comment by fforootd** [comment]
Hm out of curiosity. What type did you configure in zitadel for these applications?

Of the top of my head I think native should allow this already.

**Comment by xeor** [comment]
There doesnt seams to be a way to use argo-cli using the normal web-application I had.
I ended up creating a separate native application in zitadel for the cli since using the same integration as I did via web didnt work. I still had to use `http://localhost:8085/auth/callback` as the redirect url tho.

Feels a little better to have developer mode enabled only for the cli, but still. It is not a "test" :) I'm not sure what developer mode really does. If the only thing it does is to enable you to use localhost as a redirect url, it might be better changing the text from "developer mode", to "enable localhost url's", then having a little warning instead.

**Comment by muhlemmer** [comment]
You should use "Native app" configuration. That allows using localhost over http, even with random port assignment. So you will use http://localhost/auth/callback as a redirect config for the native app.

https://zitadel.com/docs/guides/integrate/login/oidc/login-users#application-type (click the "Native App" tab) for more details

**Comment by muhlemmer** [comment]
closing as there was no response from the OP and there is a valid solution for the usecase already
