### ISSUE TITLE
[Bug]: service user grants not present in "Pre access token creation"

### ISSUE THREAD

**Issue by davidkalosi** [zitadel/zitadel#7428]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.46.0

### Database

PostgreSQL

### Describe the problem caused by this bug

I have a registered action that creates additional token claims based on the user authorizations - I am adding scopes required by our API server. When a token is created for a human user ```ctx.v1.user.grants``` is populated correctly. however for a service user this is ```null``` although the service user has authorizations granted.  

### To reproduce

1. create a Pre access token creation action that is accessing ```ctx.v1.user.grants```
2. generate an access token for a service user

**Comment by davidkalosi** [comment]
any news here?

**Comment by livio-a** [comment]
We need to investigate.

**Comment by muhlemmer** [comment]
> 2. generate an access token for a service user

 Can you be more specific? How do you "generate" the access token? Some options:

- Personal access token aka PAT
- Client credentials grant
- JWT profile grant

**Comment by davidkalosi** [comment]
I am using the client credentials grant to get the token.

**Comment by muhlemmer** [comment]
If you do client credentials, the request does not happen in the context of an application / project. In order for zitadel to know which project you want to now the roles for, you need to explicitly pass the proper scopes in the request:

- `urn:zitadel:iam:org:projects:roles` so that zitadel will query the project roles
- `urn:zitadel:iam:org:project:id:261019893309125174:aud` tells zitadel which project. (replace the projectID with your own). Specify more times when adding more projects.

See the [reserved scopes](https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes) documentation section for more information.

When I use this [custom roles example](https://github.com/zitadel/actions/blob/main/examples/custom_roles.js) and make the following curl call, it works fine for me:

```bash
curl -L -X POST 'http://localhost:8080/oauth/v2/token' \
>   -H 'Content-Type: application/x-www-form-urlencoded' \
>   -u 'machine:zFDLnNlDcIkofxdbXHH34FoxwZqaN5t2qSWYVKwHmXvsb8tufl10Rl3nODIWNRwW' \
>   -d 'grant_type=client_credentials' \
>   -d 'scope=openid profile urn:zitadel:iam:org:projects:roles urn:zitadel:iam:org:project:id:261019893309125174:aud' | jq
```

```json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjI2MTAxOTM4MTc3MTgwOTMzNCIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiMjYxMDE5ODkzMzA5MTI1MTc0Il0sImV4cCI6MTcxMjEyMzc2MSwiaWF0IjoxNzEyMDgwNTYxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJqdGkiOiIyNjEwMjc1Nzg5ODUzMjkyMDYiLCJteTp6aXRhZGVsOmdyYW50cyI6WyIyNjEwMTk4OTMzMDkxMjUxNzQ6YmFyIiwiMjYxMDE5ODkzMzA5MTI1MTc0OmZvbyJdLCJuYmYiOjE3MTIwODA1NjEsInN1YiI6IjI2MTAxOTc1NDQ0NDEwODM0MiIsInVybjp6aXRhZGVsOmlhbTpvcmc6cHJvamVjdDoyNjEwMTk4OTMzMDkxMjUxNzQ6cm9sZXMiOnsiYmFyIjp7IjI2MTAxOTI5OTA3Njk3NzIwNiI6InppdGFkZWwubG9jYWxob3N0In0sImZvbyI6eyIyNjEwMTkyOTkwNzY5NzcyMDYiOiJ6aXRhZGVsLmxvY2FsaG9zdCJ9fX0.o-JMG6DU5kznFZe-E5eGtsHuAysxffc1zR6Ic8PIk8gcwUse3KZRwcm65nNzCkCalbc7lCa37rTWKMsnOWChLZLFQ18FDtXmqkdyxpjQQqlGePYg4A-avycxUlqAwc-WwpWUfxATbzrGpKo2sOQ-gZDeKzOU3SrI5GpcpyIZ2ZMnhBYoQBfRWp0goY1TI9jLQmHxqymWoKHuAkvfJJA6UHcml6blrJzDeuq41hTxHkdy55Bseg9OpnpJ0QakuBNGA-KRoe7yWgw6sKXadZ1K0taPmOohgXddCxleJ2rk8IWAjCNxOXewRy5KAikGKitnw7h69aKXOycn4rmE_kp4VQ",
  "token_type": "Bearer",
  "expires_in": 43199
}
```

Access token Claims:

```json
{
  "aud": [
    "261019893309125174"
  ],
  "exp": 1712123761,
  "iat": 1712080561,
  "iss": "http://localhost:8080",
  "jti": "261027578985329206",
  "my:zitadel:grants": [
    "261019893309125174:bar",
    "261019893309125174:foo"
  ],
  "nbf": 1712080561,
  "sub": "261019754444108342",
  "urn:zitadel:iam:org:project:261019893309125174:roles": {
    "bar": {
      "261019299076977206": "zitadel.localhost"
    },
    "foo": {
      "261019299076977206": "zitadel.localhost"
    }
  }
}
```

**Comment by muhlemmer** [comment]
I will close this issue now. Let me know if there are still problems / bugs that need to be solved.
