### ISSUE TITLE
[Bug]: 500 Error on Client Credential Login

### ISSUE THREAD

**Issue by maennchen** [zitadel/zitadel#7430]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

Cloud

### Database

None

### Describe the problem caused by this bug

When requesting tokens on the token endpoint, we get the following errors regularly:

`Errors.Internal`

### To reproduce

We use Zitadel in the conformance tests of [oidcc](https://github.com/erlef/oidcc).

Test: https://github.com/erlef/oidcc/blob/be27ca353b85db501da994b6994da168d9d4e3f4/test/oidcc_test.exs#L171

Example CI Run with failures:

* https://github.com/erlef/oidcc/actions/runs/7948872037/job/21699413202
* https://github.com/erlef/oidcc/actions/runs/7994909055/job/21834052121

### Expected behavior

Test passes every time

### Operating System

GitHub Actions on Ubuntu Latest

### Additional Context

Similar to #7202, the failure happens only sometimes.

There are tests executed in parallel. It could have something to do with the time between requesting tokens for the same client.

**Comment by muhlemmer** [comment]
It is the same underlying storage bug and it should get fixed by #7420. In that PR I explained what the actual problem is:

> Because we do a SELECT .. FOR UPDATE to establish the latest sequence number, many concurent pushes on the same aggregate ID might result in duplicate sequence numbers and the push will fail.

I will close this as a duplicate.
