### ISSUE TITLE
Missing docs on login users with SAML

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7436]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

As developer I want to understand how SAML works, how to sign-in and logout users with SAML, so I can integrate my SAML application with ZITADEL

### Additional Context

- [ ] concepts: what is saml
- [ ] concepts: what is oidc
- [ ] SAML vs. OIDC; link to blog
- [ ] move content from login/login-users to saml section
- [ ] link to saml from hosted login page
- [ ] link to Endpoints "apis/saml/endpoints"
- [ ] Explain how to get metadata
- [ ] Explain how to get certificates
- [ ] Explain difference to identity brokering/SAML SSO (As identity provider: "guides/integrate/identity-providers/mocksaml")
- [ ] SSO integration with SAML, SAML authentication
- [ ] Maybe add example with SP: https://github.com/crewjam/saml#getting-started-as-a-service-provider

**Comment by dakshitha** [comment]
Please find the first draft here - 

https://docs.google.com/document/d/1yJuAmY2-kxqYFXUVbxXpz0wtWi0D8ZPTIu07DC9tWpU/edit

@stebenz @mffap - please review this documentation. Thanks!
