### ISSUE TITLE
Check circular dependencies in executions with include of other executions

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#7445]
As a developer, I want to be able to check for circular dependencies in the SetExecution call, to avoid to overwork the system with circular logic.

## Acceptance Criteria
- [x] Include is checked that no circular dependencies are possible 
- [x] Include is checked to a maximum of defined levels 
- [x] Include documentation with information on maximum level and handling in introduction

**Comment by hifabienne** [comment]
@peintnermax @stebenz @eliobischof  can you please estimate this issue?
