### ISSUE TITLE
[Bug]: Switching between login and register loses track of the request id

### ISSUE THREAD

**Issue by jkoestinger** [zitadel/zitadel#7456]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.37.3

### Database

CockroachDB

### Database Version

22.2.2

### Describe the problem caused by this bug

When a user has to login and switches to register then back to login (using the "login" button, not the previous arrow), the authrequestId used for the login is getting lost in translation and the login flow falls back on default instance-level config

### To reproduce

1. Create an organization (optionally customize the UI colors)
2. Implement an auth flow with a custom redirect url
3. When trying to login on your app using the auth flow, click on "Register" on the login screen of Zitadel
4. On the register screen, click on "Login" (not the back arrow)
5. Complete the login

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5838342/7de599d3-9407-403d-a741-135241608fba)

### Expected behavior

**After step 4 if you changed the UI colors of the organization**

Expected: it still shows the correct branding of the organization the auth flow was started for
Actual: It shows the instance-level UI

**After all the steps**

Expected: you are redirected using the redirect url of your initial auth flow. 
Actual: you are seeing your profile in Zitadel

### Operating System

Linux Ubuntu 22.04, in Docker 20.10.21

**Comment by hifabienne** [comment]
Hi @jkoestinger 
Thanks for reporting this issue. I could reproduce it.

**Comment by vigneshsankariyer1234567890** [comment]
Hi @hifabienne , I would like to take on this issue!

**Comment by cyrillSMF** [comment]
@vigneshsankariyer1234567890 @hifabienne 
Thanks for taking on this bug. Can you provide a rough guess when this will be fixed and released? 

Thank you :)

**Comment by livio-a** [comment]
fixed by https://github.com/zitadel/zitadel/pull/7683. should be release within a week
