### ISSUE TITLE
[Bug]: SAML RelayState not optional? 

### ISSUE THREAD

**Issue by julianbrennum** [zitadel/zitadel#7458]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.37.3

### Database

CockroachDB

### Database Version

23.1.14

### Describe the problem caused by this bug

I tried to integrate Zitadel with Zammad but could not get it to work because Zammad does not use "RelayState" in its request. 

Zitadels documentation state that this should be optional but I can't get it to work. I tried to add "&RelayState=Hello" to the end of the request and it worked just fine, so it looks like Zitadel still requires "RelayState" from SAML request to work.

### To reproduce

Connect Zammad with Zitadel SAML and try to authenticate. You will just get redirected to an XML page. If you manually add &RelayState=Hello to the end of the request url it works. I have just tried this with Zammad, but I guess this issue is affecting all services that use SAML without an RelayState.

**Comment by livio-a** [comment]
Hey @julianbrennum 

I think you are using the stable tag version of zitadel. This has been updated recently, which also includes a fix of the SAML library.
Can you please update ZITADEL and check again?
