### ISSUE TITLE
[Bug]: cannot start any of the MFA registrations when authenticating on behalf of a service user

### ISSUE THREAD

**Issue by TraceLD** [zitadel/zitadel#7463]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.46.0

### Database

PostgreSQL

### Describe the problem caused by this bug

When implementing a custom UI one needs to provide a UI for setting up MFA. Within the context of a custom UI we are in server-side code authenticating on behalf of the service user for all of our custom UI actions as per the Integrate docs. However, when trying to start an MFA registration for a user via any of the registration APIs (e.g. `http://ZITADEL_URL/v2beta/users/:userId/totp`) the following error is returned alongside a 403 Forbidden status:

```json
{
    "code": 7,
    "message": "Request user not equal to authenticated user (AUTH-Bohd2)",
    "details": [
        {
            "@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
            "id": "AUTH-Bohd2",
            "message": "Request user not equal to authenticated user"
        }
    ]
}
```

What I'm expecting to happen: The request succeeds as I'm a service user with admin permissions

### To reproduce

Send a POST request to `v2beta/users/:userId/totp` with Bearer token belonging to an admin service user.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/46228022/c2eba5bf-3eef-41dc-b1b4-0a9bb4a32b0c)

### Expected behavior

 The request succeeds as I'm a service user with admin permissions

**Comment by hifabienne** [comment]
@livio-a @muhlemmer Any ideas?

**Comment by muhlemmer** [comment]
You should be able to call all zitadel APIs using the session token as Bearer. That request would be in the context of the user. You can use the user/v2 API like that to add the factors.

**Comment by TraceLD** [comment]
> Closing as we did not receive feedback from the OP and there is an existing solution to the issue.

The existing solution does not work as I'm in the middle of the OIDC flow in a custom UI, see earlier message: https://github.com/zitadel/zitadel/issues/7463#issuecomment-1969098520

**Comment by TraceLD** [comment]
@hifabienne @muhlemmer

**Comment by livio-a** [comment]
relates to [#7774](https://github.com/zitadel/zitadel/issues/7774)
