### ISSUE TITLE
[Bug]: Link to create project is broken 

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7481]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.46.0

### Database

None

### Describe the problem caused by this bug

Broken link

### To reproduce

1. Go to https://b2b-demo-rbxajm.zitadel.cloud/ui/console/projects/app-create
2. Click on "here"
3. Page with error

### Screenshots

https://github.com/zitadel/zitadel/assets/1366906/ac291025-e73f-4a5e-bd1f-aaecee6669a2

**Comment by hifabienne** [comment]
This is already fixed with the following pr: https://github.com/zitadel/zitadel/pull/7417
It will be published to our cloud with the next release.
