### ISSUE TITLE
Actions: Use organization metadata in external authentication flow

### ISSUE THREAD

**Issue by vs-gtadeu** [zitadel/zitadel#7482]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Following #7375, we have a use case where we plan to store a JSON object in the organization metadata and access it during the execution of an external authentication flow action.
However, the context available for external authentication flow actions doesn't provide a way to access the organization metadata.

### Describe your ideal solution

Access the org metadata via `ctx.v1.org.getMetadata()`, similar to what was done for #7023 (completed via #7263).

### Environment

ZITADEL Cloud

### Additional Context

Details of what we are trying to achieve with organization metadata and external authentication flow actions can be found in #7375.

**Comment by hifabienne** [comment]
@stebenz @peintnermax can you estimate this issue please?
