### ISSUE TITLE
SAML: Provide a way to set a different external user id for transient nameid-format

### ISSUE THREAD

**Issue by vs-gtadeu** [zitadel/zitadel#7483]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Following #7421, there are situations where the Subject NameID element of the SAML response might be transient (thus changing every time the user logs in, see `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` on [section 8.3.8 of the specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) for details) or not be present in the response at all (see [section 2.4.1](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)).

When a SAML user, who has previously logged in before, logs in and the IDP returns the same username but a different Subject NameID, Zitadel understands there is a new user logging in that has to be created, but since the username is already in use, it raises an error:

![image](https://github.com/zitadel/zitadel/assets/62257776/afa87fc7-63f9-4eb5-b10c-073be3174765)

### Describe your ideal solution

Having an `api.setExternalId()` or `api.v1.user.setExternalId()` available for external authentication flow actions would be a simple way to solve this problem.

This would allow the creation of an action that can retrieve one of the user attributes from the SAML response and use it as the external user ID.

### Environment

ZITADEL Cloud

### Additional Context

Details of what we are trying to achieve with the customization of external user IDs can be found in #7421.

---
As described in #[7421](https://github.com/zitadel/zitadel/discussions/7421#discussioncomment-9285482), an option for the mapping directly on the IdP works as well and also in case of a IdP intent (no actions v1 possible).
The change might also be done together with https://github.com/zitadel/zitadel/issues/7743.

### Acceptance criteria

- [ ] An admin is able to set a mapping attribute on the SAML IdP
- [ ] The attribute is used (instead of the nameid) to map the external user in an external authentication / IdP intent

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by lricardo** [comment]
This would be a great feature, useful when integrating with third-parties like HubSpot which expect the email to be sent in the saml nameid parameter.
