### ISSUE TITLE
Support for Apple Notification System as MFA

### ISSUE THREAD

**Issue by MatiMax** [zitadel/zitadel#750]
Supporting Apple's Notification System as an MFA type would leverage the comfort of users posessing any device of the Apple multiverse.

This comfort comes at the cost of a) being registered as an Apple Developer team ($99/CHF 109 per annum) and b) building up the knowhow to support the Apple Notification System. 

Implementation-wise there wouldn't be the need for client-side development as the notifications can be generated on the server with any technology that is able to connect to Apple's infrastructure and emit the payload with the according data (text, optional data for badges, and optional sound data). AFAIK you don't even need any Apple framework to implement a server-generated notification.

If this feature request was to be granted a milestone in ZITADEL's roadmap I'd have a deeper look into the possibilities of implementing the according MFA method for ZITADEL.

**Comment by fforootd** [comment]
We already have a apple developer account at hand 😁 and it definitely would be interesting to provide such a MFA provider.

I did a quick research into this Topic, but ended up with no proper lead of how someone could achieve something like this.
The only lead i had is to use "apple business chat".

**Comment by hifabienne** [comment]
I will close this issue since we do not see a lot of customers asking for this, We can reopen if this changes
