### ISSUE TITLE
[Bug]: Instant redirect to IDP does not work correctly 

### ISSUE THREAD

**Issue by Jank1310** [zitadel/zitadel#7502]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

Users should be redirected to the configured external IDP without requiring or showing the password form. Instead the password dialog is shown and the redirect happens only if the users clicks on the <- back arrow.

See discord: https://discord.com/channels/927474939156643850/1212425745180270632

### To reproduce

- Create new organization
- Setup domain matching
- Setup and active IDP
- Disable login with username / password
- try to login

### Screenshots

See https://discord.com/channels/927474939156643850/1212425745180270632

### Expected behavior

The user should be redirect to the configured idp

**Comment by hifabienne** [comment]
thanks @Jank1310 

I could also reproduce this issue. 
I am not 100% sure when exactly this happens, as I also could setup use cases where it worked.
As soon as I took a user that does have an email with the domain of the organization it didn't work.

I have disabled the domain suffix and setup the following two users and domain customer-e.com verified:
<img width="1146" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/a09c7551-3c03-4bc3-8868-d635d70d929b">

Both users do not work if I enter the loginname.
But if I additionally add the domain it works.
So fabienne-e@customer-e.com and test@customer-e.com@customer-e.com works
