### ISSUE TITLE
[Bug]: Authentication redirection flow

### ISSUE THREAD

**Issue by aeghprs** [zitadel/zitadel#7504]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

1.0.2

### Database

None

### Describe the problem caused by this bug

I cloned the following repo: https://github.com/zitadel/zitadel-react
I filled the necessary information for configuration and run the project. I clicked on login button and clicked on register button to register a new user. I was asked to verify the email, expected the user to be logged once my email verification code was verified and redirected to default redirect uri. But, I was redirect to default uri but the user was not logged in 

### To reproduce

1. Register for a new user.
2. Enter necessary information for registration.
3. A code is sent to user's email, there is a Finish initialization button, right click on button and click open in a new tab option.
4. Verify the code.
5. Click on Next button.
6. I am redirected to user activated page.
7. Then, I click Next button and I am redirected to homepage rather than redirect_uri page.

### Screenshots

https://github.com/zitadel/zitadel/assets/97692845/68b69bcb-5e6d-4579-9284-a8e095a24510

### Expected behavior

I expected the user to be logged in but it was not the case.

**Comment by hifabienne** [comment]
Hei @aeghprs 
Can you test what happens if you are coping the code from the email and put it directly into the code input? Instead of clicking the verify link in the email?

I am not sure where the problem is, but it might be that you loose the context of the authorization request.
You can also test this, if you now try to login with the user you have already created. Does that work?

**Comment by aeghprs** [comment]
Hi @hifabienne , thanks for response. 
Currently I have only tested for register button. 

Yes it works if I copy and pasted the code, in code input field and once the code is verified I am redirected to redirect uri, and the newly registered user is logged in too. 

But, if I follow the same steps but with minor change in steps where I copy the link address from Finish initialization button and open in new tab, I am redirected to default uri but the user is not logged in.

I expected the user to be logged in both cases as the user behavior is unpredictable. 
Also, can I ask if there is plan for feature to hide or show the Finish Initialization button in email verification message ?

**Comment by hifabienne** [comment]
> Hi @hifabienne , thanks for response. Currently I have only tested for register button.
> 
> Yes it works if I copy and pasted the code, in code input field and once the code is verified I am redirected to redirect uri, and the newly registered user is logged in too.
> 
> But, if I follow the same steps but with minor change in steps where I copy the link address from Finish initialization button and open in new tab, I am redirected to default uri but the user is not logged in.
> 
> I expected the user to be logged in both cases as the user behavior is unpredictable. Also, can I ask if there is plan for feature to hide or show the Finish Initialization button in email verification message ?

The problem is, that in case of the email the user looses the context of the authrequest, so ZITADEL does not know who did start the authentication process.
If you configure the default redirect url to your application, this is the url where ZITADEL does redirect if there is not existing auth request, then the user should be redirected to your app when no authrequest is existing and your app will then start one again: https://zitadel.com/docs/guides/manage/console/instance-settings#default-redirect-uri

**Comment by akaegi** [comment]
+1 for the additional possibility to hide the button "Finish initialization". 

When registering a new user in an app (phone) and then clicking "Finish Initialization" in an e-mail client (computer) the app (phone) gets "stuck" on the enter code page. For this scenario it would thus be helpful to just hide the button in the mail altogether.

**Comment by akaegi** [comment]
@livio-a What does "Done" mean? Does it mean it is available in production instances?

**Comment by hifabienne** [comment]
@akaegi As soon as we have implemented it and it is merged to our main branch it is marked as done.
As soon as it is built into a version you can see the following on the pullreaquest:
<img width="570" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/3008b91a-6c34-4f35-9839-994e6d0b0ff3">
(this screenshot is from another issue)

**Comment by livio-a** [comment]
Just a small addition: feature releases are deployed to zitadel.cloud within a week after their release

**Comment by akaegi** [comment]
> Just a small addition: feature releases are deployed to zitadel.cloud within a week after their release

Where do I see the used version in the cloud portal, is it the same for all instances?

**Comment by hifabienne** [comment]
> > Just a small addition: feature releases are deployed to zitadel.cloud within a week after their release
> 
> Where do I see the used version in the cloud portal, is it the same for all instances?

You can see it when you login to your instance, on the instance detail page. Yes at the moment it is the same for all instances

**Comment by akaegi** [comment]
Seems to be fixed on Android but not on iOS.
I filed another issue with a request to provide a more general solution: https://github.com/zitadel/zitadel/issues/7954.
