### ISSUE TITLE
[Bug]: Country selection for mobile verification needs bigger min width

### ISSUE THREAD

**Issue by sebastianbuechler** [zitadel/zitadel#7509]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

When I want to select a country selection and there was no value previously selected the min width is very small and it's not easy to find a correct country code:
![image](https://github.com/zitadel/zitadel/assets/42775578/db401ed8-7a7e-4402-ba48-587f461213bd)

Similar issue when a country is already selected:
![image](https://github.com/zitadel/zitadel/assets/42775578/eb05098a-0575-48c6-b31e-843ec2600a24)

### To reproduce

1. Go to a user in the console that has now phone number registered
2. Click on the pen icon to add a phone number
3. Select the country code select array

**Comment by adlerhurst** [comment]
changing numbers now look like following picture

![Image](https://github.com/zitadel/zitadel/assets/27845747/c4f2fd31-1693-452e-8535-dd3c03b57527)

**Comment by adlerhurst** [comment]
closed as selection now looks like this:
![image](https://github.com/zitadel/zitadel/assets/27845747/44189721-0301-49b6-86a3-134f09a36a6c)
