### ISSUE TITLE
[Bug]: Domain Discovery Issues - ID=QUERY-1kIjX Message=Instance not found.

### ISSUE THREAD

**Issue by K-J-VV** [zitadel/zitadel#7514]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

Hello,

Trying to setup my Zitadel instance to function with an alternative login page for an Organization and am running all via Docker Containers.

The primary domain/Instance is: login.example.com
The organization instance and verified domain is: alpha.example.com

I have set up both the organization and Instance to allow for Domain Discovery, but when I attempt to login via: alpha.example.com I receive the following error:

`ID=QUERY-1kIjX Message=Instance not found. Make sure you got the domain right. Check out https://zitadel.com/docs/apis/introduction#domains Parent=(unable to set instance using origin https://alpha.example.com (ExternalDomain is login.example.com): unable to get instance by host alpha.example.com: ID=QUERY-1kIjX Message=Errors.IAM.NotFound)`

I've tried referring to: https://zitadel.com/docs/guides/solution-scenarios/domain-discovery
and: https://zitadel.com/docs/self-hosting/manage/reverseproxy/nginx to troubleshoot but cannot figure it out.

Is the issue how my NGINX is configured? My instance is using External-TLS and I am using NGINX Proxy Manager specifically. I am wondering if the problem is I am not passing the following information:

```
        location / {
            grpc_pass grpc://zitadel-external-tls:8080;
            grpc_set_header Host $host:$server_port;
```

### To reproduce

As above

**Comment by K-J-VV** [comment]
When I try using:

```
        location / {
            grpc_pass grpc://zitadel-external-tls:8080
            grpc_set_header Host $host:$server_port;
       }

```

The error is an 'SSL handshake failed'

However, per this comment https://github.com/zitadel/zitadel/issues/4307#issuecomment-1245627184 , when I switch to the following NGINX config

```
        location / {
            grpc_set_header Host $host;
            grpc_set_header Host $host:$server_port;
       }

```

I see this OpenResty page:

![image](https://github.com/zitadel/zitadel/assets/113187314/ac38de94-7c1d-4089-a0e7-53870e70a561)

**Comment by K-J-VV** [comment]
Referring to this comment https://github.com/zitadel/zitadel/issues/4307

I have added the following nginx config:

```
location / {
            grpc_pass grpc://$server:$port;
            grpc_set_header Host $host;
}
```

And still receive the same error as above

**Comment by K-J-VV** [comment]
As an alternative to Domain Discovery

I see here: https://zitadel.com/docs/guides/solution-scenarios/configurations#custom-application-domain-per-organization

That we can 'Trigger organization in ZITADEL login' by sending the the organization id (urn:zitadel:iam:org:id:{id}) or organization primary domain (urn:zitadel:iam:org:domain:primary:{domainname}) scope on your authentication request. However I can't find clear guidance on how to do this, which is why I am trying to workout Domain Discovery

**Comment by hifabienne** [comment]
Hei @K-J-VV 
Only the domains setup in the instance domains (custom domains) can be used to access ZITADEL.
The organization domains (verified domains) are only used to suffix the users, identify the organization and domain discovery.

If you want to access ZITADEL on the alpha.example.com domain you need to add it to the custom domains in the customer portal
https://zitadel.com/docs/guides/manage/cloud/instances#add-custom-domain

**Comment by K-J-VV** [comment]
> Hei @K-J-VV 
> Only the domains setup in the instance domains (custom domains) can be used to access ZITADEL.
> The organization domains (verified domains) are only used to suffix the users, identify the organization and domain discovery.
> 
> If you want to access ZITADEL on the alpha.example.com domain you need to add it to the custom domains in the customer portal
> https://zitadel.com/docs/guides/manage/cloud/instances#add-custom-domain

I am self hosting, is this to say there is no way to achieve a multiple domain experience when self hosting?

**Comment by hifabienne** [comment]
Ah, because you choose ZITADEL Cloud in the issue description my assumption was that you are using our cloud.

Yes you can. If you get the instance not found error there can be different problems.
Have you looked at this guide? https://zitadel.com/docs/self-hosting/manage/custom-domain#why-do-i-get-an-instance-not-found-error

**Comment by hifabienne** [comment]
I think what you are looking for is the part in the ORganization Domains which tells about using the sstem api https://zitadel.com/docs/self-hosting/manage/custom-domain#organization-domains

**Comment by K-J-VV** [comment]
@hifabienne ahh my mistake selecting incorrect issue description!

But yes, I have tried referring to the online documentation guides (specifically both you've linked). However I am still unable to set this up to work correctly. Unsure if anyone else may be able to help me trouble shoot with the information I provided above. If not, Is it possible to request the documentation can be "cleared up"/simplified, with a specific example guide? 

For example: The documentation you linked describes how this can be done. But can there be an actual Tutorial on how to set this up so that it is working in a common self-hosted docker scenario with an extremely common reverse proxy (e.g., NGINX Proxy Manager)? 

I imagine it shouldn't take too long or be too much effort for someone to churn out a quick walk-through

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you help here?

**Comment by stebenz** [comment]
We are happy to add to them if it can help others avoid such scenarios as this, but first let us solve the problem at hand.

In general, if there are any questions regarding How-To's and help with self-hosting in different combinations, I personally would recommend to use our [discord](https://zitadel.com/chat) as maybe someone from the community can also help with nginx questions and we are also active there.

Anyway, we will still try our best to help you if possible, so can you provide me with additional information about your setup so that I can maybe try to reproduce your situation faster?
- nginx config?
- docker compose file?
- actions in ZITADEL like organization creation? 
- if you got your organization created, what is in the settings under "Verified domains" listed?

**Comment by K-J-VV** [comment]
Hi @stebenz, thanks for helping out! There is nothing remarkable about my setup, I simply have a default zitadel instance running with NGINX-PM acting as my reverse proxy. I'm also pretty good at troubleshooting/fixing setups so long as there is a detailed guide of how to create a basic example. For example, it may be simpler if someone were just spin up a docker instance of Zitadel and NPM-Proxy Manager, then immediately create a secondary organization and configure these containers to work so that login.example.com and alpha.example.com both work and allow users to login their respective organizations.

But hopefully the following info can help you in my case:


- NGINX Config
```
location / {
          grpc_pass grpc://$server:$port;
          grpc_set_header Host $host;
}
```

- Docker Compose File
Nearly identical to the guide, I only have it set with TLS-external: https://zitadel.com/docs/self-hosting/deploy/compose

- Zitadel Organization Creation
Following the guide by creating new organization from the drop down arrow: https://zitadel.com/docs/guides/manage/console/organizations

- Organization Verified Domains
alpha.example.com (set as primary domain)


One thing to note regarding the verified domains, I'm not sure if this may be a related. The default domain that is created is alpha.login.example.com. I then had to delete this domain and add my own, alpha.example.com. I'm not sure if there is something going on behind the scenes with organization/domain creation where the alpha.login.example.com is "passed"/"approved" but the newly added domains afterwards are not

**Comment by K-J-VV** [comment]
@stebenz still having trouble with this, if you've had a chance to take a look at the problem.

Again, I am just trying to setup a default instance of Zitadel to be accessible at login.example.com and for Organziation alpha to have it's login page accessible at alpha.example.com

Referring to the following guide, it should be possible: https://zitadel.com/docs/guides/solution-scenarios/domain-discovery
![image](https://github.com/zitadel/zitadel/assets/113187314/77d43915-0180-4237-b045-ed726a3972ae)

I also feel this should be a relatively simple thing to implement? If not, then maybe an additional feature may be set for organizations that allow users to put in a custom login url for each organization that then whitelist's this domain within Zitadel to then allow login at that organization's own landing page.

**Comment by K-J-VV** [comment]
> Hm let me try and help here.
> 
> I think you want that zitadel accepts traffic from multiple domains, correct?
> 
> In that case you can add multiple domains through the system api https://zitadel.com/docs/apis/resources/system/system-service-add-domain
> 
> 

That is exactly what I'm asking for, I did take a look at the section you linked regarding the system API. I guess what I'm asking for is some guide from Zitadel that can walk a non-developer/coder user on how to actually perform that task

I can't seem to figure it out myself, so an 'Explain it like I'm 5 - Guide" would be great

**Comment by fforootd** [comment]
> I can't seem to figure it out myself, so an 'Explain it like I'm 5 - Guide" would be great

No worries happy to lend a hand

> and, once an additional domain is added, how to have that new domain take users to the login page of that specific organization of Zitadel

At the moment zitadel does not (yet) support that out of the box 😢 but we understand what you want to have there.
Currently there are two ways to achieve this:

1) Create your own login UI
2) Your application tells zitadel the "context" by forwarding a scope parameter.

> Assuming this is the answer to my question, I'm just unsure how to do what is being directed here. Using my info above as an example (original Zitadel instance = login.example.com ; the url I am trying to set for an Organization's login page = alpha.example.com, assuming Instance ID of 12345), I'm entering the following into my terminal:

You need to send along an authorization header of a service-user https://zitadel.com/docs/guides/integrate/zitadel-apis/access-zitadel-system-api#system-api-user but this is not yet configurable in a UI way.

**Comment by K-J-VV** [comment]
> At the moment zitadel does not (yet) support that out of the box 😢 but we understand what you want to have there. Currently there are two ways to achieve this:
> 
> 1. Create your own login UI
> 2. Your application tells zitadel the "context" by forwarding a scope parameter.

Let's say I have 2x instances of Zitadel running via docker:

Instance 1 = login.example.com
Instance 2 = alpha.example.com

Step 1 "Create your own login UI" is taken care of by Instance 2, correct? Since I am just using that instance of Zitadel for a login UI

I'm quite stuck on Step 2 on how to forward the scope parameter. I believe this is the scope I need to pass  `urn:zitadel:iam:org:id:{id}` ( https://zitadel.com/docs/apis/openidoauth/scopes ). Step 2 is where an "explain like I'm 5" guide would be incredibly helpful

**Comment by fforootd** [comment]
I think we should not think of multiple instances here, but what might work is a solution with (n) oauth2-proxies.

You could deploy an oauth2-proxy that listenst for alpha.example.com... as soon as traffic hits it redirects to login.example.com with the `urn:zitadel:iam:org:id:{id}` <- you can configure this in the oauth proxies scope settings.
What it basically does it tells zitadel (login.example.com) that a certain organization is required and in turn renders the login ui in a design that is conigured.

**Comment by K-J-VV** [comment]
> I think we should not think of multiple instances here, but what might work is a solution with (n) oauth2-proxies.
> 
> You could deploy an oauth2-proxy that listenst for alpha.example.com... as soon as traffic hits it redirects to login.example.com with the `urn:zitadel:iam:org:id:{id}` <- you can configure this in the oauth proxies scope settings. What it basically does it tells zitadel (login.example.com) that a certain organization is required and in turn renders the login ui in a design that is conigured.

I'm close! 

I have Zitadel @ login.example.com and OAuth2 Proxy at alpha.example.com. Figured out how to pass the organization ID within OAuth so now when I go to alpha.example.com the user is immediately redirected to Zitadel @ login.example.com BUT the login page is actually for Organization Alpha (which is exactly what I've been trying to do)

However, now after successful login I'm taken back to alpha.example.com , where the webpage is simply an empty 404 error. I'm assuming this is because after login I'm taken to OAuth 2's page at alpha.example.com (which is nothing) and now this is where your mention of `(n) oauth2-proxies.` comes into play.

**Comment by K-J-VV** [comment]
@fforootd 

I now have 3x "parts"
- Zitadel @ login.example.com
- Alpha OAuth @ alpha.example.com
- Zitadel OAuth @ login.example.com/oauth2/

When I navigate to alpha.example.com I am taken to Zitadel's login page for Organization Alpha. This is all done from Alpha OAuth. After successful login I have the redirect URL set to: login.example.com. 

So it seems things are _working_ in the sense that after successful login I am being taken back to Zitadel at login.example.com . But the login page is a `500 Internal Server Error`. The issue seems to be with Zitadel OAuth? The following error is what I see:

` [oauthproxy.go:881] Error redeeming code during OAuth2 callback: could not verify id_token: audience from claim aud with value [262059315123282951@alpha 262059057139966983] does not match with any of allowed audiences map[262069694431847433@zitadel:{}]]`

**Comment by fforootd** [comment]
> @fforootd
> 
> I now have 3x "parts"
> 
> * Zitadel @ login.example.com
> * Alpha OAuth @ alpha.example.com
> * Zitadel OAuth @ login.example.com/oauth2/
> 
> When I navigate to alpha.example.com I am taken to Zitadel's login page for Organization Alpha. This is all done from Alpha OAuth. After successful login I have the redirect URL set to: login.example.com.
> 
> So it seems things are _working_ in the sense that after successful login I am being taken back to Zitadel at login.example.com . But the login page is a `500 Internal Server Error`. The issue seems to be with Zitadel OAuth? The following error is what I see:
> 
> ` [oauthproxy.go:881] Error redeeming code during OAuth2 callback: could not verify id_token: audience from claim aud with value [262059315123282951@alpha 262059057139966983] does not match with any of allowed audiences map[262069694431847433@zitadel:{}]]`

This looks like one client tries to use a token intended for another one.

Can you share how you config(s) look like?

**Comment by K-J-VV** [comment]
@fforootd 

Got it!

Took awhile to figure out but instead of having redundant OAuths pointing to one another I just setup an NGINX proxy to forward between domains and now everything seems to be working great

So, rather than part 3 being another OAuth container, part 3 is just NGINX redirecting between the two after successful login
