### ISSUE TITLE
[Bug]: Docker Compose files in `./e2e/` not usable since latest Docker Compose release.

### ISSUE THREAD

**Issue by lusu007** [zitadel/zitadel#7515]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

Unfortunately, the latest Docker Compose update breaks the `docker-compose.yml` files in the ./e2e/ folder and its child folders.

``docker compose --file ../e2e/docker-compose.yaml up --detach zitadel`` fails with the following error: 
```
WARN[0000] The "UID" variable is not set. Defaulting to a blank string. 
service "zitadel" can't be used with `extends` as it declare `depends_on`
```

see: https://github.com/docker/compose/issues/11544

### To reproduce

1. Install the newest Docker Compose version 2.24.6
2. Execute ``docker compose --file ../e2e/docker-compose.yaml up --detach zitadel`` out of the `./e2e/` folder

**Comment by fforootd** [comment]
Hey I will investigate the issue. But in the meantime you can downgrade to docker version 2.24.5 which still works 😁

**Comment by fforootd** [comment]
It looks like docker will fix this https://github.com/docker/compose/issues/11544#issuecomment-1987785162

**Comment by fforootd** [comment]
https://github.com/docker/compose/issues/11544#issuecomment-2010785963

If you do not mind I close this issue. Feel free to reopen if it does not work out 😓
