### ISSUE TITLE
[Bug]: Unable to setup project with brand-new installation

### ISSUE THREAD

**Issue by paustint** [zitadel/zitadel#7526]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

ghcr.io/zitadel/zitadel:latest 2b24385796e2

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

I just tried to go through the setup process and was unable to create my first project successfully due to bugs.

### To reproduce

follow steps here https://zitadel.com/docs/self-hosting/deploy/compose
```
# Download the docker compose example configuration.
wget https://raw.githubusercontent.com/zitadel/zitadel/main/docs/docs/self-hosting/deploy/docker-compose.yaml

# Run the database and application containers.
docker compose up --detach
```
Start new docker container with latest
Login to application
click "Create Application"
choose "other" framework
then application is in a bad state and am unable to continue

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5461649/d81c743a-bd26-4c7c-b3ae-5109ddedc578)

### Expected behavior

I should be able to create an application

### Operating System

macos

**Comment by fforootd** [comment]
Hey, thanks for reporting this.

I just tried to reproduce this but I was not able 😁 
Would you mind sharing if your browser reported errors in the developer console?

If I select "other" on the first screen I get the OIDC/SAML dialog and not the framework specific (see screenshot below) as next screen.

<img width="772" alt="Screenshot 2024-03-09 at 19 25 10" src="https://github.com/zitadel/zitadel/assets/9879976/238ba43b-335d-4d15-b5d4-0e9cc59b4729">
<img width="1308" alt="Screenshot 2024-03-09 at 19 25 17" src="https://github.com/zitadel/zitadel/assets/9879976/0bfb0097-6026-4616-9798-ad412f196821">

**Comment by paustint** [comment]
Yes, there are some errors in the console.

Here is a demo showing the reproduction: https://jam.dev/c/af355412-aa50-48ae-9cda-1a98517f7d25
(console output also displayed in Jam's UI)

```
ERROR TypeError: Cannot read properties of undefined (reading 'id')
    at template (5354.0b44a76c06355f73.js:1:4810)
    at Um (main.b0f002729bd33608.js:1:6204157)
    at ov (main.b0f002729bd33608.js:1:6214239)
    at sv (main.b0f002729bd33608.js:1:6215487)
    at uz (main.b0f002729bd33608.js:1:6215350)
    at lv (main.b0f002729bd33608.js:1:6215625)
    at ov (main.b0f002729bd33608.js:1:6215001)
    at sv (main.b0f002729bd33608.js:1:6215487)
    at av (main.b0f002729bd33608.js:1:6215320)
    at ov (main.b0f002729bd33608.js:1:6214524)
```
and later on

```
main.b0f002729bd33608.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'template')
    at n._attachOverlay (4630.81d90fa932d5c629.js:1:14800)
    at n._handleFocus (4630.81d90fa932d5c629.js:1:12418)
    at 4630.81d90fa932d5c629.js:1:19175
    at xv (main.b0f002729bd33608.js:1:6227374)
    at q (main.b0f002729bd33608.js:1:6227542)
    at HTMLInputElement.<anonymous> (main.b0f002729bd33608.js:1:6698235)
    at v.invokeTask (polyfills.fd4735676522f440.js:1:7171)
    at Object.onInvokeTask (main.b0f002729bd33608.js:1:6198602)
    at v.invokeTask (polyfills.fd4735676522f440.js:1:7092)
    at M.runTask (polyfills.fd4735676522f440.js:1:2536)
```

![image](https://github.com/zitadel/zitadel/assets/5461649/42c85055-7113-4600-8288-373a1626c9a3)

**Comment by paustint** [comment]
Also - in case I was not clear in the report, the "Create Application" button is the entry point where I run into the issue. I am able to create a project+app from other paths just fine.

![image](https://github.com/zitadel/zitadel/assets/5461649/06694495-cde7-4585-9bb0-2f4d27473209)

**Comment by hifabienne** [comment]
hei @paustint 
Thanks for reporting. I could reproduce this issue when choosing "Other" as framework.
It only happens when I want to create it in a new project.
When I choose an existing project, then the flow works fine
