### ISSUE TITLE
[Bug]: Incorrectly rendered SVG while initializing user

### ISSUE THREAD

**Issue by the-voidl** [zitadel/zitadel#7542]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.47.3

### Database

None

### Describe the problem caused by this bug

When initializing a new user, the TOTP-code is not rendered correctly.
It seems like the html is escaped and results in being printed as text. Unescaping the text results in the correctly rendered svg when copied into an html viewer.

On the initialization page we have this div: `<div id="qrcode" class="lgn-qrcode">`

When skipping TOTP in the first place, one can add it later on the profile-edit page. Here it works correctly and seems like resulting from some angular-module.

### To reproduce

1. Create a new user
2. As the new user, try to setup TOTP in the initialization process

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/63976048/26614ad6-6e2f-4203-bdc2-fb6da0328fd0)
![image](https://github.com/zitadel/zitadel/assets/63976048/18af70da-6bae-4d3d-ac37-f845e11b61eb)

### Expected behavior

Correctly rendered qr code in the form.

### Operating System

Browser:
- Firefox 122.0
- Chromium 121.0.6167.184

**Comment by mjunker** [comment]
Same problem here on Chrome 122.0.6261.112.

![Screenshot 2024-03-12 at 15 24 26](https://github.com/zitadel/zitadel/assets/528457/fa9bcfa6-e41d-4418-a70f-badd6c759bcd)

**Comment by livio-a** [comment]
Thanks for your report. We're looking into this one right now.

**Comment by livio-a** [comment]
Fix has been released as 2.47.4, deployed to zitadel.cloud and back ported to 2.44.4, 2.45.2 and 2.46.2
