### ISSUE TITLE
[Bug]: HTML editing in login text not working anaymore.

### ISSUE THREAD

**Issue by nielsNocore** [zitadel/zitadel#7556]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.46.2

### Database

PostgreSQL

### Describe the problem caused by this bug

We added som html tags in login screen. these are not woking any more:

### To reproduce

add html tags to login text:
 <a href=https://test.xxxx.nl > Click here to log in to TEST Proforma PayWays again.</a>

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/122032239/57f72d78-8ba6-4ce3-8203-75280b01a1dd)

### Expected behavior

Working html tags in the login text

**Comment by nielsNocore** [comment]
Small adition; was working in V2.44.1. 
I think not working due to https://github.com/zitadel/zitadel/pull/7522

**Comment by muhlemmer** [comment]
Security wise HTML / JS / CSS should be escaped in template data by the template renderer. We used the wrong renderer before which allowed injection. The fact that HTML worked was the actual bug which is now solved.

**Comment by nielsNocore** [comment]
Is there an example how to escape the HTML /CSS to be rendered correctly?

**Comment by nielsNocore** [comment]
Any updates about this?

**Comment by fforootd** [comment]
Yes it should be possible again soon with https://github.com/zitadel/zitadel/pull/7575

**Comment by nielsNocore** [comment]
Thank you for your answer.
Thanks for the quick response
