### ISSUE TITLE
[Bug]: "Default settings" missing in console mobile view

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7574]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

Can't access the default settings when viewing the console on mobile.

### To reproduce

1. On a small screen go to the console
2. Try to get to the "default settings" page

### Screenshots

![b2b-demo-rbxajm zitadel cloud_ui_console_(iPhone 14 Pro Max)](https://github.com/zitadel/zitadel/assets/1366906/553af99e-8c32-455c-b1c1-6d56ffe9fb7d)

### Expected behavior

Navigation should be accessible on the mobile device.

### Additional Context

When switching to landscape mode the button is visible; If this is the expected use, then that should be indicated to the user

**Comment by Tingzhueve** [comment]
I'm working on this.
