### ISSUE TITLE
Improve token introspection docs

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7576]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

https://zitadel.com/docs/guides/integrate/token-introspection

- [x]  Instead of using a generated index page, create an own index page (called `index.md`) (see below for template that includes the cards)
- [ ] Improve formatting
- [x] Make a link to the example https://github.com/zitadel/examples-api-access-and-token-introspection
- [x] Provide links to the API references

---
title: 
sidebar_label: 
sidebar_position: 1
---

... text goes here ...

import DocCardList from '@theme/DocCardList';

<DocCardList />

**Comment by muhlemmer** [comment]
Hi @mffap, it seems that most (if not all) of the above improvements were already done in https://github.com/zitadel/zitadel/pull/7492. I've checked-off the tasks that I already found implemented.

That only leaves "improve formatting", which sounds subjective to me and the current page seems pretty readable.

Is there anything you consider that still needs to be done for this issue?

**Comment by mffap** [comment]
> Hi @mffap, it seems that most (if not all) of the above improvements were already done in #7492. I've checked-off the tasks that I already found implemented.
> 
> That only leaves "improve formatting", which sounds subjective to me and the current page seems pretty readable.
> 
> Is there anything you consider that still needs to be done for this issue?

Thanks for me it's fine to be closed
