### ISSUE TITLE
[Docs]: Migrate CockroachDB to Postgres

### ISSUE THREAD

**Issue by hofq** [zitadel/zitadel#7586]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

As an Administrator, I want to have Documentation about how to switch between DB Providers, so I can have information about how to migrate correctly

### Additional Context

I saw you have a story for automatic Migration. Until then, I would want to have docs about how to do it manually.

**Comment by PinsonJonas** [comment]
I second this!
I have some pricing concerns with cockroachdb, so it would be great if we could get some documentation on how to do this until there is a way to do it automatically. (rather soon😇)

**Comment by HungryHowies** [comment]
+1

**Comment by krax0x** [comment]
+1
