### ISSUE TITLE
Resources API Design

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#7592]
As a developer, I want to have an API guideline that helps me changing the API while keeping consistency so it is intuitive to use and provides a good experience. 

### Acceptance Criteria
- [ ] We have a consesus about the contents of the API guidelines
- [ ] The CONTRIBUTING.md has a section that contains the API guidelines 

1. **Naming Register Compliance and Updates** - All naming conventions adhere to our established naming register.

2. **CRUD Operations and Action-Based Paths for Status Changes** - Resources (plural) support CRUD operations. However, for status changes other than POST and DELETE, we introduce specific action-based paths with an underscore prefix to make these operations explicit. PUT and PATCH return a successful response if the payload already matches the resource (no changes).

```
POST /orgs -> 201, 200 on success, 400 on bad/malformed request, 409 on state conflict
POST /orgs/{id}/_deactivate
PUT /orgs/{id} -> 200 (also if no changes)
PATCH /orgs/{id} -> 200 (also if no changes)
DELETE /orgs/{id} -> 200, 404
GET /orgs/{id} -> 200, 404
GET /orgs -> 200, also with empty array / totalResult 0
```

3. **Uniform Scope Restriction for API Calls** - All API calls accept a required or optional scope (e.g., Org ID, User ID, Project ID, Instance ID). The Instance ID can default to being derived from the Host header. If a scope is provided, read write is restricted to this scope. It treats resources that are out of the provided scope like if they were not existing.

4. **Authorization Checks** - For calls on a single resource, no context is necessary. The API just checks if the user is allowed. For bulk operations, no state is changed if the user is missing a permission on at least one resource. For List / Search queries, the result set is reduced to the resources for which the user has read permissions. If a scope is provided, the API checks the authorization on this scope before it computes the model.

5. **Default Limit and Pagination for List Queries** - All list queries have a default limit of 100 items (configurable in defaults.yaml). List / Search queries support pagination.

6. **Service-Specific Implementation and Versioning of Resources** - Resources should be implemented and versioned within their specific service to maintain clarity and manageability.

7. **API foreign information** - Translations, branding and other information, that is not relevant for the API or the new auth logic are not typed but rather stored as dynamic json bytes. Events hold references to the byte arrays. For example when an inexisting org translation is read, the API tries to default to instance level translations.

8. **Proto definitions**: We adhere [to the proto style guide](https://protobuf.dev/programming-guides/style/)

9. **Docs**: The API docs describe each service. Also each endpoint with at least one example and the most forseeable return codes is described.

**Comment by eliobischof** [comment]
- [ ] Do user schemas and actions need special treatment?

**Comment by eliobischof** [comment]
About POST, PUT, PATCH and DELETE:
- Better refine behavior and error handling by common use cases
- Define criteria that define if we provide these methods or not (input by @stebenz)

About Scopes:
- Are there security impacts if we return a 403 if scopes are requested without permission (by @stebenz)?

About resolving references
- Too complex to maintain and references between resources conflicts with the "resource based" principle (by @stebenz)

**Comment by eliobischof** [comment]
# Suggestion for **4.-8. POST, PUT, PATCH and DELETE**, based on reconciling and importing use cases:

## PATCH /resources/{id} for Reconciler Use Case

**Description**: This endpoint is designed for the Reconciler use case, where the goal is to ensure a resource exists with certain fields updated to specified values. It allows for partial updates to a resource, modifying only the fields provided in the request body. If the resource does not exist, the behavior can be controlled by an additional parameter or header in the request. This flexibility is crucial for reconciling state without overwriting unrelated fields.

**Use Case Relevance**: Ideal for scenarios where the client wants to maintain or "reconcile" the desired state of a resource, especially in cases where resources might be managed by different services or components (or humans). It supports idempotent operations, ensuring that repeated requests with the same data will not create unintended side effects.

**Parameters**:
`id`: The unique identifier of the resource to be patched.
`upsert`: An optional query parameter or header that dictates whether to create the resource if it does not exist (`true`) or to return an error if the resource is not found (`false`).

## POST /resources/new and POST /resources/import for Import Use Case

### POST /resources/new

**Description**: Attempts to create a new resource with the provided data. If the resource conflicts with existing unique constraints (other than the ID, which is assumed to be either not provided or generated by the system), the API returns a 409 Conflict error. This endpoint serves the basic need to create resources without handling complex conflict resolution logic.

**Use Case Relevance**: Suitable for straightforward creation scenarios where an ID is not already known, and the client expects to be notified of conflicts with unique properties. It ensures data integrity and avoids unintentional overwrites.

### POST /resources/import
**Description**: Customized for the Import use case, this endpoint facilitates the creation or updating of resources with advanced conflict resolution strategies. It supports additional parameters to control the behavior when conflicts with existing resources are detected.

**Use Case Relevance**: Designed for importing resources from external systems, where conflicts might arise due to overlapping unique properties. This endpoint allows for flexible handling of such conflicts, accommodating various import strategies.

**Parameters**:

`conflictStrategy`: Controls how conflicts with existing resources are handled.
- `ignore`: If a conflict is detected, the import operation is ignored for the conflicting resource.
- `overwrite`: Conflicting resources are completely overwritten with the imported data, resetting unspecified fields to their default values.
- `merge`: The API updates the conflicting resource with the specified fields in the payload, leaving other fields unchanged. This option allows for a more granular update, preserving non-specified data.

These endpoints and their configurations are crafted to address the specific requirements of Reconciler and Import use cases, providing flexibility for partial updates, resource creation, and sophisticated conflict resolution strategies. The design emphasizes idempotent operations, clear error handling, and the ability to specify desired behaviors, ensuring a robust and intuitive API experience.

**Comment by eliobischof** [comment]
- Refine Error handling

**Comment by hifabienne** [comment]
@eliobischof can this issue be closed?
