### ISSUE TITLE
[Bug]: Active Directory / LDAP external IDP fails when using objectGUID as the ID attribute

### ISSUE THREAD

**Issue by hinmanjp** [zitadel/zitadel#7601]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.48.0

### Database

PostgreSQL

### Database Version

16.x, 14.x

### Describe the problem caused by this bug

When the objectGUID value is selected as the ID attribute for an Active Directory IDP, Zitadel fails to convert the value from a binary / byte array into a GUID string value before attempting to store it as a json object in the auth.auth_requests.request field. Postgres throws an error with the following message: "invalid byte sequence for encoding "UTF8"" 

A related issue (and solution) for another project can be found on StackOverflow at:
https://stackoverflow.com/questions/18383843/how-do-i-convert-an-active-directory-objectguid-to-a-readable-string

### To reproduce

1. Configure an Active Directory / LDAP IDP (either at the global or org level).
2. Configure the ID attribute as "objectGUID" 
![image](https://github.com/zitadel/zitadel/assets/25162087/156b49e2-9f2b-46c5-9f58-80f809ccbc14)

3. Attempt to authenticate via the Zitadel login using a valid AD / LDAP user.
4. Get an error message
![image](https://github.com/zitadel/zitadel/assets/25162087/5fb46ea6-42d1-4cfd-b841-1ccea4deeae0)
5. Check the zitadel logs at the timestamp of the login to find the "invalid byte sequence for encoding "UTF8"" message.
```
time="2024-03-20T19:19:22Z" level=error auth_req_id=259147125936357754 caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/renderer.go:341" error="ID=QUERY-C1E4D Message=Errors.Internal Parent=(ERROR: invalid byte sequence for encoding \"UTF8\": 0xbc (SQLSTATE 22021))"
```

### Expected behavior

Expected behavior would be to convert the binary / byte array to a string GUID value before attempting to store it in as a json object.

Any future comparison of the LDAP objectGUID would also need to be converted before comparing to the json value in the auth_requests table.

### Operating System

Zitadel: Docker image running on Linux (TrueNas Scale)
Client: Windows 10, FireFox 123.0.1, Chrome 122.0.6261.129

**Comment by livio-a** [comment]
need to check if the id is utf-8 safe, otherwise we need to base64 encode it -> small bugs

**Comment by helmut72** [comment]
I run into the same problem. Never got Samba4 LDAP (like Active Directory) working with Zitadel.

Perhaps the following should be considered:
https://central.owncloud.org/t/ocis-with-samba-ldap-without-owncloud-schema/41377/19

**Comment by helmut72** [comment]
Thanks, works. But using Zitadel still for testing. Would be so cool if Zitadel integrate LDAP like the other ones (Keycloak, Authelia, Authentik).
