### ISSUE TITLE
Add feature settings to the console

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#7604]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Feature settings were introduced in https://github.com/zitadel/zitadel/pull/7356. At the moment we are adding optional features, like in:

- https://github.com/zitadel/zitadel/pull/7416
- https://github.com/zitadel/zitadel/pull/7516
- https://github.com/zitadel/zitadel/pull/7597

However, ZITADEL users do not have an option to enable features from the console. While writing a guide I find it awkward that a part of the setup steps is screenshots and some are direct API calls for the feature.

### Describe your ideal solution

As a zitadel instance admin I want to be able to manage instance features from the console.

## Acceptance criteria

- [x] `proto/zitadel/feature/v2beta` definitions added to the console generator
- [x] A tab is the "Default settings" overview that manages instance features
- [ ] `GetInstanceFeatures` shows the current state of the features. Use inheritance to show the user if the feature was already enabled from system level.
- [x] `SetInstanceFeatures` is called with the settings the user selected
- [x] `ResetIntanceFeatures` can be called to revert all instance features
- [x] Only users with the according permission are allowed to see/edit the features `iam.restrictions.write` ìam.restrictions.read`
- [x] Features can be enabled/disabled in the console
- [x] Features do have a clear description in the console about what it is and what happens if it is enabled

### Version

main branch

### Environment

Self-hosted

**Comment by hifabienne** [comment]
@eliobischof @peintnermax can you please estimate this issue?

**Comment by eliobischof** [comment]
@peintnermax 2?
