### ISSUE TITLE
[Bug]: Response Type Configuration Issue in ZITADEL with Implicit OIDC

### ISSUE THREAD

**Issue by Evsio0n** [zitadel/zitadel#7607]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Database

PostgreSQL

### Describe the problem caused by this bug

When attempting to authenticate using the OpenID Connect implicit flow with response_type=id_token for Guacamole integration, ZITADEL returns an error stating that the requested response type is missing in the client configuration. This issue prevents Guacamole from using the implicit flow for authentication.

### To reproduce

1. Configure an OpenID Connect client in ZITADEL for Guacamole with the implicit flow.
2. Initiate an authentication request from Guacamole with response_type=id_token.
3. Observe the error indicating that the response type is missing in the client configuration.

### Screenshots

<img width="1233" alt="Screenshot 2024-03-21 at 6 57 35 PM" src="https://github.com/zitadel/zitadel/assets/29672485/cc05b86f-4134-40c9-96a6-b537bd8d9124">
<img width="882" alt="Screenshot 2024-03-21 at 6 58 24 PM" src="https://github.com/zitadel/zitadel/assets/29672485/6806e844-a9ce-4331-953b-78d40b01b9a3">

### Expected behavior

ZITADEL should accept the authentication request with response_type=id_token when the client is configured for the implicit flow, allowing Guacamole to complete the authentication process without errors.

### Relevant Configuration

1. Guacamole is configured to use OpenID Connect with ZITADEL.
2. The authentication request from Guacamole includes response_type=id_token.
3. The client configuration in ZITADEL is intended to support the implicit flow, but the error suggests a mismatch in the expected response type.

**Comment by hifabienne** [comment]
hei @Evsio0n 
In your configuration you have set Token-Id-Token as response type.
Can you change that to ID Token and have a look what happens?
<img width="259" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/b2f01486-9983-4e52-8359-e1b3d6279d8d">

**Comment by Evsio0n** [comment]
<img width="731" alt="Screenshot 2024-03-23 at 8 13 37 PM" src="https://github.com/zitadel/zitadel/assets/29672485/bd39259c-5caf-448f-b98a-5229cab2cccd">

---

The *Guacamole* Return with error: 
Rejected invalid OpenID token: JWT processing failed. 


```log
12:15:04.723 [http-nio-8080-exec-9] INFO  o.a.g.a.o.t.TokenValidationService - Re
jected invalid OpenID token: JWT processing failed. Additional details: [[17] Una
ble to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Unab
le to find a suitable verification key for JWS w/ header {"alg":"RS256","kid":"25
9526132590707173","typ":"JWT"} due to an unexpected exception (java.io.IOExceptio
n: Non 200 status code (403 Forbidden) returned from https://[Zitadel WEB]/oauth
/v2/keys) while obtaining or using keys from JWKS endpoint at https://[Zitadel WEB]/oauth/v2/keys): JsonWebSignature{"alg":"RS256","kid":"259526132590707173","ty
p":"JWT"}->[JWT Payload] 
```


The payload with information above:


```json
{
  "iss": "https://[Zitadel WEB]",
  "sub": "251899268716167653",
  "aud": [
    "1@saas_service",
    "2@saas_service",
    "3@saas_service",
    "4@saas_service",
    "5"
  ],
  "exp": 1711239302,
  "iat": 1711196102,
  "auth_time": 1710660907,
  "nonce": "[nonce]",
  "amr": [
    "password",
    "pwd"
  ],
  "azp": "1@saas_service",
  "client_id": "1@saas_service",
  "name": "[Username]",
  "given_name": "",
  "family_name": "",
  "picture": "[User Picture]",
  "locale": "en",
  "updated_at": 1707386461,
  "preferred_username": "[User Email]",
  "email": "[User Email]",
  "email_verified": true
}
```

**Comment by muhlemmer** [comment]
> Non 200 status code (403 Forbidden) returned from https://[Zitadel WEB]/oauth
/v2/keys

The `/oauth/v2/keys` does never return a `403 Forbidden`. I checked the code and there is not a single codepath that would return this status. This sounds more like a reverse proxy issue to me.

**Comment by muhlemmer** [comment]
As for the response type:

- If you set Token-ID Token in the console, you must send `response_type=id_token token`
- If you set ID Token in the console, you must send `response_type=id_token`

See [reference docs](https://zitadel.com/docs/apis/openidoauth/endpoints#required-request-parameters) and [OpenID standard](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest) for the possible values.

**Comment by Evsio0n** [comment]
Hello, @muhlemmer,

Firstly, please give me my sincere appriciation for your guidance and suggestions.

Regarding the issue of `/oauth/v2/keys` returning a 403 Forbidden, I have identified the cause. It was due to our reverse proxy Cloudflare WAF. This issue has now been resolved.

However, we are still encountering error with guacamole, specifically that the expiration time (exp) of the JWT cannot be more than 300 minutes into the future from the evaluation time. 
```log

rejected due to invalid claims or other invalid content. 
Additional details: [[5] The Expirati on Time (exp=NumericDate{1711663521 -> Mar 29, 2024 6:05:21 AM SGT})
claim value cannot be more than 300 minutes in the future relative to the evaluation time Num ericDate{1711620317 -> Mar 28, 2024 6:05:17 PM SGT} 
(even when providing 30 secon ds of leeway to account for clock skew).] 

```



Here are the details of the JWT:


```json
{
  "iss": "https://oa.evsio0n.com:443",
  "sub": "*",
  "aud": ["*@saas_service", "*@saas_service", "*@saas_service", "*@saas_service", "*"],
  "exp": 1711663521,
  "iat": 1711620311,
  "auth_time": 1711601976,
  "nonce": "*",
  "amr": ["password", "pwd"],
  "azp": "*@saas_service",
  "client_id": "*@saas_service",
  "name": "Linkin Shan",
  "given_name": "Linkin",
  "family_name": "Shan",
  "picture": "https://[]",
  "locale": "en",
  "updated_at": 1707386461,
  "preferred_username": "*",
  "email": "*",
  "email_verified": true
}
```

I see that the exp value of the JWT is 1711663521, which corresponds to the time of 6:05:21 AM SGT on March 29, 2024. However, the evaluation time of the JWT is 1711620317, which corresponds to the time of 6:05:17 PM SGT on March 28, 2024. It appears that the exp value does indeed exceed the evaluation time by more than 300 minutes.

May I change this Issue to `JWT cannot be more than 300 minutes into the future from the evaluation time.` to match this issue?

Thank you!

**Comment by muhlemmer** [comment]
I don't understand why guacamole is being so difficult about that. But you can [configure the token lifetimes](https://zitadel.com/docs/guides/manage/console/default-settings#oidc-token-lifetimes-and-expiration) in zitadel as you see fit. If you need less than 300 minutes, set it to 5 hours or less.

If you don't mind I will close this issue because there are no actual bug[s], just requests for help. Please use the chat for community  support if you have any more questions.
