### ISSUE TITLE
[Bug]: Authorizations are broken after zitadel upgradations

### ISSUE THREAD

**Issue by AjayKuruvath** [zitadel/zitadel#7615]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.48.1

### Database

PostgreSQL

### Database Version

postgres 16

### Describe the problem caused by this bug

After Zitadel Version upgrade(2.48.1), the Authorisations list is empty. when we revert back to previous version(2.48.0) the Authorisations list is showing all users.
 

### To reproduce

Go to zitadel Admin Dashboard
Check "Authorisation" - the list is empty

**Comment by hifabienne** [comment]
@AjayKuruvath Did you enable --init-projections when upgrading?
This will ensure that all projections are uptodate when updating.
Otherwise it may take a moment till all projections are computed

**Comment by AjayKuruvath** [comment]
@hifabienne  Yes we have already enabled it. 

![image_2024_03_22T10_30_40_661Z](https://github.com/zitadel/zitadel/assets/121004161/cb32b25b-86b9-4c56-abde-a5fef7cae0e1)

**Comment by hifabienne** [comment]
> @hifabienne Yes we have already enabled it.
> 
> ![image_2024_03_22T10_30_40_661Z](https://private-user-images.githubusercontent.com/121004161/315976924-cb32b25b-86b9-4c56-abde-a5fef7cae0e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTU2NTYsIm5iZiI6MTcxMTExNTM1NiwicGF0aCI6Ii8xMjEwMDQxNjEvMzE1OTc2OTI0LWNiMzJiMjViLTg2YjktNGM1Ni1hYmRlLWE1ZmVmN2NhZTBlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMzQ5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzEzYjQxMGYxNjY4MDJjNzc4MzdjNDc5MTNlNWJhZDc1NDZiOGYxOGUzYTE2ZGRlNzY3ODYyNDEzNTgzYzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cBUkOk-33LxaXr71NdRfdSr9AnmmNs638kIw2Yul8d0)

Where did you set that? Why is it called Compose projections and not init projections?
I am not aware that we do call it like this somewhere.

**Comment by AjayKuruvath** [comment]
@hifabienne  We have added `--init-projections ` and it worked correctly. Thank you very much

**Comment by hifabienne** [comment]
Thanks @AjayKuruvath for the feedback.
In that case I will close the issue.
