### ISSUE TITLE
Instance settings title

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#7632]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

<img width="1356" alt="Screenshot 2024-03-25 at 13 27 27" src="https://github.com/zitadel/zitadel/assets/1366906/13567641-838d-4179-9f05-873fedccf96b">

Instance settings was renamed to "Default settings". The title is still Instance settings

### Describe your ideal solution

Title: 
Instance Settings -> Default settings

Description:
Default settings apply to all organizations and can be overwritten in the organization's settings.

### Environment

ZITADEL Cloud

### Additional Context

- Recommendation: Rename the button on the top right to "Organization settings"

**Comment by bilalqv** [comment]
Hi Team!
Can I work on this one

**Comment by fforootd** [comment]
@bilalqv Sure please go ahead!

thank you for helping us build this great oss product 🙇

**Comment by doncicuto** [comment]
Sorry @bilalqv, I've created a PR for this issue, I wan't sure it this issue was stalled so I hope you don't mind as I had some spare time and the Instance Settings title was a little outdated
