### ISSUE TITLE
[Bug]: change password API doesn't honor password policy

### ISSUE THREAD

**Issue by ashep** [zitadel/zitadel#7638]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.46

### Database

PostgreSQL

### Describe the problem caused by this bug

When a new password is being set via the [change password API](https://zitadel.com/docs/apis/resources/user_service/user-service-set-password), there is any non-empty new password is being accepted despite password policy settings.

### To reproduce

Create a new user in the instance that has default password policy set:

```shell
curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer TOKEN' --data '{"profile":{"givenName": "John", "familyName": "Doe"}, "email":{"email":"john@doe.com","isVerified": true}, "password":{"password":"theP@ssw0rd123", "changeRequired": false}}' http://zitadel:8081/v2beta/users/human
```

Then change the password to one that violates the password policy:

```shell
curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer TOKEN' --data '{"currentPassword": "theP@ssw0rd123", "newPassword": {"password": "1234", "changeRequired": false}}' http://zitadel:8081/v2beta/users/259982525009494018/password
```

And see no error in response.

### Expected behavior

The error describing password inconsistency should be returned.

**Comment by ashep** [comment]
Hello @hifabienne! Would you happen to have any updates on this issue?

**Comment by hifabienne** [comment]
Hi @ashep 
At the moment I don't have an update. You will get the updates on the issue if something changes
