### ISSUE TITLE
WSO2 not working as external idp (Generic OAuth or Generic OIDC) due to prompt=select_account query parameter

### ISSUE THREAD

**Issue by nikzen** [zitadel/zitadel#7640]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

WSO2 > v6.0.0 is not working as external idp (Generic OAuth or Generic OIDC) due to prompt=select_account query parameter.

### Describe your ideal solution

Add a config option to Generic OAuth or Generic OIDC identity provider to enable / disable prompt=select_account oder enable / disable PKCE.

### Version

latest

### Environment

Self-hosted

### Additional Context

This is the upstream WSO2 issue, however updating to a new version seems not possible for our customer: https://github.com/wso2/product-is/issues/6372

**Comment by hifabienne** [comment]
Hei @nikzen 
I think this is exactly what is described here: https://github.com/zitadel/zitadel/issues/6599
Beeing able to configure the prompt that is sent to the idp.
Due to this I will close this issue, to avoid duplicates, feel free to reopen if you think its about something else
