### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by tahaghafuri** [zitadel/zitadel#7642]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

mysql is popular and widely used as well as low consumption database.

### Describe your ideal solution

It is better to add mysql support.

### Version

Dev

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hi @tahaghafuri 
We already have an issue open where this has been discussed: https://github.com/zitadel/zitadel/issues/3598

At the moment we do not have the intention to support mysql or any other databases.
A new database always brings additional complexity into the product, as not every DB works exactly the same. We can already see that with cockcroach and PostgreSQL.
Right now, our focus is on improving the current integrations, not adding more. However, this might change in the future. So we still hold the issue open to get all your feedback and opinion.
