### ISSUE TITLE
[Bug]:  Unknown Content-type received.  Error In Console

### ISSUE THREAD

**Issue by tahaghafuri** [zitadel/zitadel#7655]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Database

PostgreSQL

### Database Version

latest

### Describe the problem caused by this bug

When I am in the console and after several requests and settings, the following error is observed:
 Unknown Content-type received. 
After a few seconds of this error, the server is unavailable and gives a 520 error.

### To reproduce

First, I enter the console, and after moving, see some pages and send an Unknown Content-type received error request. is received and the zidatel web server is stopped.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/82469904/412c8bca-d332-46fe-a5c6-44315a338383)
After:
![image](https://github.com/zitadel/zitadel/assets/82469904/48c876ac-a96e-4c71-9e7e-8fde85038cd0)

### Expected behavior

I expected that this was just an error and zidatel would not stop.

### Operating System

I Recerive It On Any Device.

### Relevant Configuration

Behind Nginx Reverse Proxy

**Comment by fforootd** [comment]
Hm this looks to me like there is a protocol issue with http2.

Can you explain how you host zitadel and if there is a proxy involved besides cloudflare?

**Comment by tahaghafuri** [comment]
Zitadel -> Nginx -> Cloudflare

**Comment by fforootd** [comment]
Can you share your nginx config?

Also have a look here https://zitadel.com/docs/self-hosting/manage/reverseproxy/reverse_proxy for nginx/cloudflare related configs

**Comment by tahaghafuri** [comment]
I Use In Plesk (NGinx):
<Proxy *>
	Order allow,deny
	Allow from all
</Proxy>
AllowEncodedSlashes NoDecode
ServerName auth.proginow.com
ProxyPreserveHost On
ProxyRequests off

SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off

ProxyPass / http://127.0.0.1:8080/ nocanon
ProxyPassReverse / http://127.0.0.1:8080/

**Comment by fforootd** [comment]
Ok so you might wanna use this instead of proxypass

```
            grpc_pass grpc://127.0.0.1:8080;
            grpc_set_header Host $host:$server_port;
```
