### ISSUE TITLE
Custom SMS Proivider Connector For OTP

### ISSUE THREAD

**Issue by tahaghafuri** [zitadel/zitadel#7658]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Example: http://sms-proivider/get?to=number&text=text here

### Describe your ideal solution

Add Send SMS Feature Over URL

### Version

latest

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hei @tahaghafuri 
Can you elaborate a little more on your use case, and what you need.
Why is that a feature you are looking for?

**Comment by tahaghafuri** [comment]
### I mean in the following example:
Sending SMS via GET method:
Address: https://example.com/SendMessageWithUrl.ashx
Indicators :

Username: UserName, for example: test123
Password: Password, for example: 123456 / SMS system password
Dedicated number: PhoneNumber, for example: 5000221030
Message text: MessageBody, for example: SMS sending test
Message receiver number: RecNumber, for example: 09116665601
Sending type: Smsclass must be 1
 

Complete example of the system:
https://example-sms-provider.com/SendMessageWithUrl.ashx?Username=test123&Password=****&PhoneNumber=5000221030&MessageBody=test&RecNumber=09116665601&Smsclass=1

Just copy the above address in the section using the address of the system bar and register and execute your choices.

important points:

If you are identified after sending code 8. This can mean that it does not enable the possibility of using the web service and url for you. To activate this possibility for free, register an activation request in the support section with a ticket or contact the company.
In the image where sending is used with a number greater than 200, it means that your SMS was sent without sending. and otherwise an error has been encountered.

**Comment by tahaghafuri** [comment]
This feature is also available in wso2 identity server, which makes it not limited to one SMS provider

**Comment by michelkaeser** [comment]
> [...] as there is no "standard" SMS protocol like SMTP we use for email [...]
> [...] We would need to implement code for each provider specifically [...]

I don't want to talk for OP but this is exactly the anti-goal of the request.

Basically the desire is to be able to specify an HTTP request that shall be send when ever internally a SMS (and/or email/notification etc.) is triggered.

Established providers almost always offer an HTTP API (e.g. SendGrid, Twilio, SMSAPI) and if ZITADEL would allow to send an HTTP request and use variables like `{{recipient}}`, `{{message}}` etc. most providers can easily be covered.

I'd argue that this makes sense even beside SMTP for emailing. For example we use SendGrid's HTTP API to send all our emails so we can use its dynamic templates feature.

Some example APIs:

* https://www.twilio.com/docs/messaging/api/message-resource#create-a-message-resource
* https://docs.sendgrid.com/api-reference/mail-send/mail-send
* https://www.smsapi.com/docs/#2-single-sms

> [...] which will allow calling webhooks at foreign APIs. This would be a good usecase for custom notification channels [...]

Yes!

**Comment by muhlemmer** [comment]
@eliobischof you have more knowledge on the notification system in zitadel, I will pass this issue over to you.

**Comment by eliobischof** [comment]
I see some benefit if we added the possibility to add an SMS provider (maybe also an Email provider) for arbitrary webhook calls instead of having only Twilio as a requirement.

We already have a webhook channel implemented for milestones. I imagine it gives users much flexibility for a relatively low implementation effort.

**Comment by karatekaneen** [comment]
@eliobischof For us it would be enough if we could override the SMS endpoint URL and we can replicate the Twilio API ourselves and send the data where we'd like. 
This feels like it could be very little effort to change and give most of the benefits to those that really need it?

**Comment by hifabienne** [comment]
We have just implemented http as sms provider so you can choose where to send the notification and implement something yourself. https://github.com/zitadel/zitadel/issues/8270

Can we close the issue here?

**Comment by karatekaneen** [comment]
@hifabienne It looks like exactly what we need. 
Did a quick search in the documentation but couldn't find any API spec/schema for what the custom SMS service will receive, do you know where I can find that?

Other than that this issue can be closed based on our needs at least

**Comment by hifabienne** [comment]
Hi @karatekaneen 
The documentation is in review and will be merged soon.
If you already want to have a look at it you can see it here: https://github.com/zitadel/zitadel/pull/8626

In that case I will close this issue for now, feel free to reopen if you still miss something
