### ISSUE TITLE
[Bug]: (Console) Key creation dialog and table show incorrect expiration date

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#7686]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

Cloud

### Database

None

### Describe the problem caused by this bug

When creating a new (service) user key, the expiration date shows the incorrect year.

For example, when creating a key to expire on 12/31/2024, the UI shows that the key is created with an expiration date of 12/31/2025, but the key material JSON file has a correct expiration date of 12/31/2024.

### To reproduce

1. Navigate to a user
2. Navigate to keys
3. Click on 'Add' and select 12/31/2024 as the expiration date
4. See that the dialog and subsequent keys table shows 12/31/2025 as the expiration date

### Screenshots

![Screenshot_20240401_161606](https://github.com/zitadel/zitadel/assets/131888729/eacf0f0b-75b9-4785-89df-5dc808b8fe17)
![Screenshot_20240401_161622](https://github.com/zitadel/zitadel/assets/131888729/c3b40716-2e42-4985-801c-295d428b815f)
![Screenshot_20240401_161640](https://github.com/zitadel/zitadel/assets/131888729/c38fa598-4a49-4c4a-a5a0-a46b7b2951fa)

### Expected behavior

Correct expiration date to be shown.

**Comment by doncicuto** [comment]
Hi, I've been able to reproduce it for self-hosted version. If I add an expiration other that 12/31/2024 it works fine:

![image](https://github.com/zitadel/zitadel/assets/30386061/39f6c9ae-6fde-4196-8b27-fb52fec2d68e)

Apparently events show the right date:

![image](https://github.com/zitadel/zitadel/assets/30386061/e79c81cf-b923-46fd-874f-911e65fee2b2)

@hifabienne let me check if it's something with how the frontend converts the date to show it to the user

**Comment by doncicuto** [comment]
Yeah, it was a format error but a strange one YYYY shows ISO Week-numbering year which is 2025 (wrong? for that date) so I've just changed YYYY in the date transformation pipe to yyyy and now it looks fine:

![image](https://github.com/zitadel/zitadel/assets/30386061/0c4ab5a7-2613-433b-876d-b436123d5664)

Uploading PR in a minute

**Comment by doncicuto** [comment]
Thanks @jbvv1 I've created a PR for this
