### ISSUE TITLE
Typo on the main Zitadel website

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#7690]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

I found a small typo in the footer of www.zitadel.com. The link to `GDPR` (https://zitadel.com/gdpr) has the text `GDRR`.

If this is the wrong place to report this issue, feel free to close the issue.

**Comment by muhlemmer** [comment]
Thanks for the report!

**Comment by fforootd** [comment]
Thank you, I just created a PR for this, should be fixed soon 👍
