### ISSUE TITLE
Search Applications API query syntax is unintentionally vague

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#7700]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

I have been testing the Search Applications API and it is not clear (to me) from the documentation that search results are only returned when all of the name queries match versus just one query (i.e. the query uses `AND` versus `OR` on the name query terms).

The documentation (https://zitadel.com/docs/apis/resources/mgmt/management-service-list-apps) says that the API allows for an array of name queries.

```
queries object[]
    Array [
        nameQuery object
    ]
```

Let's say that I have 3 applications: `Frontend`, `IAM API`, and `Purchases API`.

When I made an API call with the following queries payload, I expected that all three applications would be returned. However, zero applications were returned instead. I believe that this is because the underlying search logic uses an `AND` operation with the query terms versus `OR` (with de-duplication).
```json
[
    {
        "nameQuery": { "name: "tend", "method": "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE" }
    },
    {
        "nameQuery": { "name: "API", "method": "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE" }
    }
]
```

This difference in search query behavior took me a while to understand and troubleshoot. Please can the documentation be updated on this page (and perhaps others) to explicitly call out that results are only returned when all of the queries match, versus just one? Can I presume that this behavior is common across all of the other search queries in other Zitadel APIs?

**Comment by stebenz** [comment]
Yes this behavior is shared across all APIs, the idea is that you can provide a list of AND connected query objects, which is in this case limited to name.
If there would be a need of a list query for name it would be similar to https://zitadel.com/docs/apis/resources/mgmt/management-service-list-users inUserIdsQuery or inUserEmailsQuery.

**Comment by stebenz** [comment]
As there was no further communication, I will close this issue, please reopen it if there are any other questions.
