### ISSUE TITLE
Can we add the "setUserId" function in PreCreation so that we can support the use of the application's ID?

### ISSUE THREAD

**Issue by mario-shang** [zitadel/zitadel#7732]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I am currently integrating the existing application with ZITADEL. Previously, users were stored in MongoDB, and the id type is [ObjectId](https://www.mongodb.com/docs/manual/reference/method/ObjectId/), so I cannot directly use the ZITADEL id as application id. I need to add a ZitadelId field or use the email. 
At the same time, I am considering whether ZITADEL can use application id. I noticed that the "/v2beta/users/human" api supports setting the userId, so historical data is supported. However, for newly registered users, I expect to use the application id in the PreCreation action. Is it possible to support this? What are the risks?

### Describe your ideal solution

```
	apiFields := actions.WithAPIFields(
		actions.SetFields("setUserId", func(userId string) {
			user.AggregateID = userId
		}),
	)
```

### Environment

Self-hosted

**Comment by stebenz** [comment]
Theoretically it would be possible, I would recommend to still use the generated ID's in ZITADEL to differentiate the users.
The ID from the application is still on the user as a link to the external IDP, as you also can link multiple IDPs to the same user.

**Comment by stebenz** [comment]
As this was more of a question than a issue, and there was no communication I will close this issue, if the topic still arises please reopen the issue.
