### ISSUE TITLE
"External Users allowed" option on projects

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#775]
## Implement "External Users allowed" option on projects

Make it possible to configure wether a project allows AuthN from users not belonging to the same org.

- [ ] Implement Toggle on Project level in Console
- [ ] Expand Management API with bool

FYI @caos/zitadel

**Comment by fforootd** [comment]
this somewhat relates to #766

**Comment by hifabienne** [comment]
This can be achived by enable the setting "check for project on authentication", it checks if the organisation has access to the project. If enabled and no other organisation has a grant to it, it will not allow "external users"

![image](https://user-images.githubusercontent.com/38692350/209686643-b3200077-9b23-4c1d-a06a-851b88a16789.png)
