### ISSUE TITLE
Log the unique id used for sonyflake in stdout

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#7750]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When configuring the the place where zitadel can request its unique id for the process (hostname, ip, webhook) we currently do not provide a means of verifying what information has been used.

### Describe your ideal solution

As an operator it would be nice to see if my config has been applied in the stdout startup message along the ZITADEL logo.

### Environment

ZITADEL Cloud

### Additional Context

Came up as idea on discord here https://discord.com/channels/927474939156643850/1222631346678009947

**Comment by Norman-Lee** [comment]
Hey @fforootd do you mind letting me take this up? Been looking an issue to pick up to learn some golang.

**Comment by hifabienne** [comment]
> Hey @fforootd do you mind letting me take this up? Been looking an issue to pick up to learn some golang.

sure, thanks for offering your help. I assigned you to the issue
