### ISSUE TITLE
[Bug]: Deleting an organization redirects to an empty org page

### ISSUE THREAD

**Issue by jbvv1** [zitadel/zitadel#7751]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

When deleting an organization is successful, the Console redirects to an organizations list page that fails to load any data. Refreshing the page does result in data being loaded successfully.

### To reproduce

1. Navigate to an organization
2. Delete the organization
3. Web browser will redirect to `/ui/console/orgs` but the page will not load any data due to an `Organisation doesn't exist` error

### Screenshots

![Screenshot_20240410_143904](https://github.com/zitadel/zitadel/assets/131888729/3d2c1021-4660-42e3-82bb-24299469821d)
![Screenshot_20240410_143847](https://github.com/zitadel/zitadel/assets/131888729/fe1cdd82-4fea-4a16-8384-75eba0b19374)

### Expected behavior

Organization page should load data without an error being shown.

**Comment by doncicuto** [comment]
Hi @muhlemmer, can I get this one too?
