### ISSUE TITLE
[Bug]: wrongly returned internal server error (500) from token endpoint

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#7765]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.49.3, v2.50-rc1, main

### Database

PostgreSQL

### Describe the problem caused by this bug

We've been seeing HTTP status 500 - internal server error from time to time on the token endpoint on zitadel cloud. This is observed on the loadbalancer, which received the 500 from the zitadel backend. We strongly suspect this is because of a wrongly mapped error which should be in the 400 range, as we do not see any other alarming logs.

### To reproduce

Send some invalid input to the token endpoint. However we currently don't have information on which parameters are triggering a 500.

We've already fixed similar bugs in:
- https://github.com/zitadel/zitadel/pull/7419 (released and deployed with v2.47.0)
- https://github.com/zitadel/zitadel/pull/7730 (released and deployed with v2.49.2)

It greatly reduced the amount of 500s we are seeing, by unfortunately a few still pop-up from time to time. 

What is tested an excluded from v2.49.3+:
- sending an invalid base64 string as refresh token returns a 400
- sending an valid base64 string not encrypted by zitadel returns a 400
- using a refresh token twice returns a 404

### Expected behavior

Zitadel should always return a status code <500, unless there is a problem with the server itself, for example fatal database errors, IO errors etc.

### Additional Context

The purpose of this issue is to see if there are self-hosters that observe the same 500 statuses that might have a concrete "steps to reproduce" with request examples which trigger a 500.

**Comment by livio-a** [comment]
as seen in traces:
```
Internal Server Error: ErrorType=server_error Description=cache error Parent=ID=VIEW-qJBg9 Message=cache error Parent=(ERROR: invalid byte sequence for encoding "UTF8": 0xa2 (SQLSTATE 22021))
```
