### ISSUE TITLE
[Bug]: Invalid gender on the v1 `userinfo` & `id_token`

### ISSUE THREAD

**Issue by Yberion** [zitadel/zitadel#7787]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.1

### Database

PostgreSQL

### Describe the problem caused by this bug

Hello,

It seems that the `/oidc/v1/userinfo` endpoint as well as the `id_token` contain an invalid gender type/format.

Reading the doc, it should be something similar to this (eg: https://zitadel.com/docs/apis/resources/auth/auth-service-get-my-user):

![image](https://github.com/zitadel/zitadel/assets/4186385/fc0c25d6-dfdc-45c1-8ed1-abdc1329a2f5)

But instead we get `male`:

![image](https://github.com/zitadel/zitadel/assets/4186385/4995afaa-d425-4226-91c8-2a23ce20db62)

I construct my user object (Angular app) with the userinfo endpoint which is called my the lib I'm using (on connection & refresh token https://angular-auth-oidc-client.com/docs/documentation/configuration#autouserinfo)

I think it should return the same format on any API call or in the `id_token`.

This endpoint is part of the `authWellKnownEndPoints` that is probably in the spec:

![image](https://github.com/zitadel/zitadel/assets/4186385/efa54e31-c4c6-4b05-be31-0923efdd2cc1)

This force to create a user converter from the userinfo and another one to the API.

### To reproduce

- Call the userinfo endpoint
  - it will return the gender as `male`...
- Call any API from https://zitadel.com/docs/apis/apis
  - it will return the gender as `GENDER_MALE`

### Expected behavior

The gender should only have one format, whenever the source.

**Comment by hifabienne** [comment]
Hi @Yberion 
Our internal apis to manage resources do not neccessarily match the openid endpoints.
We have defined how to specify gender in our apis, this is what you can find with the GENDER_UNSPECIFIED, etc

But the userinfo endpoint does need to match the specification defined by openid, so we are compliant with the specs and therefore can get certified.

Therefore I will close the issue, as it is actually like it should be

**Comment by Yberion** [comment]
Hello @hifabienne, hm, I understand your point, it's a bit confusing to have to maintain different models/converters if we're using both the openid api and the Zitadel API.

~~I think I will just make my own "gender" with my own type and store it in the metadata of the users, this way I only have 1 implementation to update.~~ (nevermind, this will force me to make 2 request to update user info as we can't set metadata with v2 api - https://zitadel.com/docs/apis/resources/user_service/user-service-update-human-user)

Thanks for the answer!
