### ISSUE TITLE
[Bug]: Create project using system user

### ISSUE THREAD

**Issue by Loddan** [zitadel/zitadel#7794]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.1

### Database

PostgreSQL

### Database Version

15.5

### Describe the problem caused by this bug

When creating a project using a system user, the project is created but a 2 log entries are emitted:
```
time="2024-04-18T08:35:48Z" level=error msg="reduce failed" aggregate=project caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/statement.go:48" error="ID=PROJ-uahkkord22 Message=Errors.NotFound" instance=263290370509549573 projection=projections.project_members4 sequence=2
time="2024-04-18T08:35:48Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:416" error="ID=PROJ-uahkkord22 Message=Errors.NotFound" projection=projections.project_members4
```

and it continues to emit this 2 log entries every second.

The problematic event seems to be:
- `event_type`: `project.member.added`
- `payload`: `{"roles":["PROJECT_OWNER"],"userId":"system-user-1"}`

### To reproduce

1. Start zitadel `zitadel start-from-init --config config.yaml`
2. Generate token `export TOKEN=$(zitadel-tools key2jwt --audience=http://localhost:8080 --key=system-user-1.pem --issuer=system-user-1)`
3. Create project
  ```
  curl http://localhost:8080/management/v1/projects \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -H "x-zitadel-orgid: 263290370509615109" \
  --data-binary '{"name": "MyProject"}'
  ```

### Expected behavior

The project to be created without system user added as member.

### Relevant Configuration

```yaml
SystemAPIUsers:
  - system-user-1:
      Path: /system-user-1.pub
      Memberships:
        - MemberType: System
          Roles:
            - "SYSTEM_OWNER"
            - "IAM_OWNER"
            - "ORG_OWNER"
```

**Comment by Loddan** [comment]
Or are the system users intended use case only for the System API? If that is the case I suppose all interaction with the Management API should be rejected?

**Comment by jsjeon-um** [comment]
Can I work on this?

**Comment by hifabienne** [comment]
@eliobischof @stebenz Can you please clarify what the intention is here and how it is supposed to work?

**Comment by reactima** [comment]
The issue still exists and very confusing. I was trying to create organization, project, user, and grant add user as a project member using "system-user-1"

**Comment by reactima** [comment]
> * add an optional field to AddProjectRequest to determine an owner, if not the creator of the project

Temp alternative solution might be an extra method to do the same ?

**Comment by reactima** [comment]
```go
func (s *Server) AddProject(ctx context.Context, req *mgmt_pb.AddProjectRequest) (*mgmt_pb.AddProjectResponse, error) {
	ctxData := authz.GetCtxData(ctx)
	project, err := s.command.AddProject(ctx, ProjectCreateToDomain(req), ctxData.OrgID, ctxData.UserID)
	if err != nil {
		return nil, err
	}
	return &mgmt_pb.AddProjectResponse{
		Id:      project.AggregateID,
		Details: object_grpc.AddToDetailsPb(project.Sequence, project.ChangeDate, project.ResourceOwner),
	}, nil
}

```

looks like reconnecting "system-user-1" client set OrgID might solve the issue as it will set ctxData.OrgID ?

**Comment by reactima** [comment]
after going through source code, found orgID can be either added with zitadel.WithOrgID option for go sdk or 
in http header with "x-zitadel-orgid" if you are using rest API

Solution #1 Temp 
make a sql query which will fix empty resource_owner field, and assign resource_owner equal to Organization Resource Id

// response.OrganizationId = 282358120770963970
// projectID = 282358123019110914
update projections.projects4 set resource_owner = '282358120770963970' where id = '282358123019110914'

Solution #2
So I've just recreated a client 

```go
	createdOrgID := response.OrganizationId
	org := &v2beta.Organization{
		Org: &v2beta.Organization_OrgId{
			OrgId: createdOrgID,
		},
	}

	ZOptions = append(ZOptions, zitadel.WithJWTProfileTokenSource(idpZitadel.PATJWTProfileTokenSource(PATToken)), zitadel.WithOrgID(createdOrgID))

	zclient, err = idpZitadel.NewClient(
		confManagement.Issuer,
		api,
		ZScopes,
		ZOptions...)
```

if you are reading this, you are most probably building something similar. 

please feel free to ask more in private https://t.me/reactima

**Comment by stebenz** [comment]
@reactima just to mention, there is already solution 2 in our example of [zitadel-go](https://github.com/zitadel/zitadel-go/blob/bfb0be051aebe56f349d7b60529f74727dc24c7b/example/mgmt/mgmt.go#L62), which is our go sdk.

Unfortunately, your solution with the SQL will not work in this situation, or at least only as long as the projections are not touched. The events in your eventstore are not updated with the necessary information and only the missing information is added in the projections which get filled from the events.

**Comment by muhlemmer** [comment]
@stebenz  Sure you can. The eventstore does not do input validation, that should be handled by the API or command package. If it's empty in the BaseEvent, the `owner` column will simply be set to an empty string (`""`).

I think the problem arised when we added the new permission model to the system user. Normally we would take the org from the user's token in the authz middleware (or the organization header), but the system user does not have a org by default. 

I've seen this config on QA, but not sure if that helps, I'm not familiar with the system user middleware.

```
      Memberships:
        - MemberType: Organization
          Roles: "ORG_OWNER"
          AggregateID: "237917699039101112"
```

I think the fix we need here is explicit validation that the context has an org ID that can be used.

**Comment by JonnyMe** [comment]
Same issue here.

**Environment**
Self-hosted

**Version**
v2.67.1

**Database**
PostgreSQL

**Database Version**
16.6

**Relevant configuration**
```
SystemAPIUsers:
  - system-user:
      Path: /system-user.pub
      Memberships:
        - MemberType: System
          Roles:
            - "SYSTEM_OWNER"
            - "IAM_OWNER"
            - "ORG_OWNER"
```

**To reproduce**
**1.** Create token for `system-user`:
```
token () {
    NOW=$( date +%s )
    IAT="${NOW}"
    EXP=$((${NOW} + 3600))
    HEADER_RAW='{"alg":"RS256"}'
    PAYLOAD_RAW='{"iss":"system-user","sub":"system-user","aud":["https://'"$(zitadel_domain)"'"],"iat":'"$IAT"',"exp":'"$EXP"'}'
    HEADER=$(echo "$HEADER_RAW" | base64 | sed s/\+/-/ | sed -E s/=+$// | tr -d '\n' | tr -d '\r')
    PAYLOAD=$(echo "$PAYLOAD_RAW" | base64 | sed s/\+/-/ | sed -E s/=+$// | tr -d '\n' | tr -d '\r')
    SIGNATURE=$(echo -n "$HEADER.$PAYLOAD" | openssl dgst -sha256 -binary -sign $ZITADEL_SYSTEM_USER_KEY_PATH  | openssl enc -base64 | tr -d '\n=' | tr -- '+/' '-_' | tr -d '\n' | tr -d '\r')
    echo "$HEADER.$PAYLOAD.$SIGNATURE"
}
```
**2.** Create Organization:
`curl -Ls "https://$(zitadel_domain)/v2/organizations"`

**3.** Create User with `.organization.orgId` set to the created Organization id:
`curl -Ls "https://$(zitadel_domain)/v2/users/human"`

**4.** Set the created user as Organization owner (passing `x-zitadel-orgid` header):
`curl -Ls "https://$(zitadel_domain)/management/v1/orgs/me/members"`

**5.** Create a new project (passing `x-zitadel-orgid` header):
`curl -Ls "https://$(zitadel_domain)/management/v1/projects"`

Project payload:
```
{
    "name": "Homelab",
    "projectRoleAssertion": true,
    "projectRoleCheck": false,
    "hasProjectCheck": false,
    "privateLabelingSetting": "PRIVATE_LABELING_SETTING_UNSPECIFIED"
}
```

Once the project is created I start getting the exact same errors at the same rate.
