### ISSUE TITLE
[Bug]: Could not found the setting button after upgrade

### ISSUE THREAD

**Issue by rajubish** [zitadel/zitadel#7819]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.50.0

### Database

CockroachDB

### Database Version

23.2.4

### Describe the problem caused by this bug

We have upgraded the zitadel version recently from 2.40.10 to 2.50.0. After upgrade user not able to see the settings tab even he has ORG_OWNER access.
This is critical and it's in production, can you please help how to resolve it ASAP.

### To reproduce

Upgrade version from 2.40.10 to 2.50.0

### Screenshots

<img width="1423" alt="Screenshot 2024-04-22 at 10 45 58 AM" src="https://github.com/zitadel/zitadel/assets/74891056/7ebe117a-680a-4bf7-8253-7869f0a7c10d">

### Operating System

Ubuntu 22.04

**Comment by doncicuto** [comment]
Hi @rajubish, can you confirm if you only have one organization for your Zitadel instance?  

In this PR https://github.com/zitadel/zitadel/pull/7274 it is documented that: 

> On a newly created instance when having a single organization, settings are hidden from the organizations menu

So I'd like to check with you that it is your case. If you only have one organization maybe as you're in a hurry as a workaround you may add another empty organization and in that way your use may see the Settings button again. Test it in a dev environment first of course.

Example, instance with only one org, Settings is not found as Default Settings has all the settings you need

![Captura desde 2024-04-25 09-29-46](https://github.com/zitadel/zitadel/assets/30386061/f6571652-43b2-4727-8273-8265e8d719af)

Example, after creating a Test organization, now the Settings button is shown

![2024-04-25_09-30](https://github.com/zitadel/zitadel/assets/30386061/1dd74cbf-3202-4ef6-a92e-8beb5a1232e3)

I'll have a look to the code to see how to fix this, I assume it's a permission issue that prevents a user with ORG_OWNER to see the Default settings button unless she has IAM permissions, if that is the case I'll propose a PR to the team.

**Comment by rajubish** [comment]
thanks
