### ISSUE TITLE
[Bug]: Password complexity not checked on /auth/v1/users/me/password

### ISSUE THREAD

**Issue by akaegi** [zitadel/zitadel#7833]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

When using endpoint `/auth/v1/users/me/password` to change the password, password complexity is not checked. E.g. "123" is accepted as a valid password.

### To reproduce

1. Update password of a user using above endpoint

**Comment by hifabienne** [comment]
You are right, I quickly checked this myself and can confirm, that it allows all passwords.
Thanks for the report

**Comment by Techno-o76** [comment]
@hifabienne how can i contribute to this issue, I am new to opensource and want to contribute, I have programming experience in java and spring boot.

**Comment by hifabienne** [comment]
> @hifabienne how can i contribute to this issue, I am new to opensource and want to contribute, I have programming experience in java and spring boot.

We do have a contribution guideline here: https://github.com/zitadel/zitadel/blob/main/CONTRIBUTING.md
First task will be forking the repository and get it to run.
I recommend joining our community chat to ask questions zitadel.com/chat it is easier than asking questions on the issue.
Our engineers are in the chat as well and can help you with your questions

**Comment by akaegi** [comment]
Thank you, I can confirm that this now works as expected :-)
