### ISSUE TITLE
[Bug]: Incosistent UI and E-mail language when creating a new user

### ISSUE THREAD

**Issue by akaegi** [zitadel/zitadel#7834]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

When asking to create a new user and passing e.g. `ui_locales=de` the registration form as well as the E-Mail to "finish initialization" is shown in the correct language. When pressing "Finish initialization" however, the URL is again opened with default language. 
(As there is no user yet there is no possibility to set the user's preferred language beforehand...)

### To reproduce

1. Use `/oauth/v2/authorize` endpoint with `prompt=create` and `ui_locales=de` to request user creation
2. Check that registration form is indeed shown in German
3. Check that "Finish initialization" mail is indeed shown in German
4. Click "Finish initialization" button in E-mail
5. UI to confirm code is shown in English (wrong)

### Screenshots

<img width="953" alt="Screenshot 2024-04-23 at 15 06 29" src="https://github.com/zitadel/zitadel/assets/1681061/464e72be-0d8c-4feb-b133-9419e00c44c8">

![Screenshot 2024-04-23 at 15 08 04](https://github.com/zitadel/zitadel/assets/1681061/e4b98ece-b6f2-4042-bd9e-0e4791cfca16)

### Expected behavior

UI in step 5 is shown in German, too.

**Comment by hifabienne** [comment]
We just worked on a fix to have the authrequest included when the user gets an email.
@livio-a will in that case also the locales be taken from the authrequest, when the user pressed the button in the email?

**Comment by stebenz** [comment]
@akaegi As much as I see the the implementation also includes the ui_locales from the authRequest which is used in the "Activate User" screen.
I will close this issue as there was no further communication here, if there is still a problem with the translation, please don't hesitate to reopen this issue.

**Comment by akaegi** [comment]
Thank you @stebenz, I can confirm that it is working flawlessly now.
