### ISSUE TITLE
[Bug]: External login provider not allowed

### ISSUE THREAD

**Issue by DavideWalder** [zitadel/zitadel#7837]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.50.3

### Database

None

### Describe the problem caused by this bug

Many users saw the message in the screenshot below when logging in (preventing them to log in). Now we can't reproduce anymore. Any idea what the cause could be and if we can expect it again?

### To reproduce

We managed to reproduce by logging in in an org where log in is only possible through external IDP. Now we can't reproduce anymore

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/58290976/66bbe21f-97c7-42d6-b4c6-aa9e8a4d5090)

**Comment by hifabienne** [comment]
This error message is shown, when the used idp is not configured for the organization

**Comment by svenbeck27** [comment]
@hifabienne we have not changed our IDPs at all, and this appears to happen after your yesterdays release. 
as this is still happening to most of your customer I would ask you to escalate this issue on your side.

**Comment by DavideWalder** [comment]
Forgot to mention: this happens for customers using Azure AD (still setup using the old OpenID connect integration).

**Comment by DavideWalder** [comment]
Also happened for Google IdP, we still can't reproduce, so no more debugging information

**Comment by hifabienne** [comment]
Thanks, we are on it and get back to you asap

**Comment by hifabienne** [comment]
We have rolledback our deplyoment, can you please check again?

**Comment by u1040867** [comment]
@hifabienne Thanks, I got positive feedback from 1 customer so far

**Comment by u1040867** [comment]
@hifabienne Now got feedback from multiple more customers that the login is working again as before

**Comment by hifabienne** [comment]
Great, I will close this issue for now and we will investigating why that happend.
Thanks for the report
