### ISSUE TITLE
[Bug]: List MyMemberships API not working as expected throwing sql error

### ISSUE THREAD

**Issue by mahmoodfathy** [zitadel/zitadel#7841]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

1.49

### Database

PostgreSQL

### Database Version

latest

### Describe the problem caused by this bug

There is a bug in the Auth API : /auth/v1/memberships/me/_search :https://zitadel.com/docs/apis/resources/auth/auth-service-list-my-memberships
whenever you supply it a query filter it responds with the following response:
```
 data: {
      code: 2,
      message: 'ERROR: column members.grant_id does not exist (SQLSTATE 42703)'
    }
  }
```
for example when filtering with the projectGrantId , this happens with all possible query filters , for project id , project grant id and orgId , this is zitadel v.1.49 , haven't tested for the latest.

if you supply no filters it responds normally with all memberships 

### To reproduce

1. call the /auth/v1/memberships/me/_search with a valid user access token who has a membership
2. supply any query filter , you will get back the response above
```
const listMyMembershipsBody: V1ListMyMembershipsRequest = {
  queries: [
    {
      projectGrantQuery: {
        projectGrantId: "263164240339140617",
      },
    },
  ],
};
```

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/71036818/edbf8860-898c-44c5-8d7e-c143884fad7b)

### Expected behavior

it should filter the user membership according to the query filter

### Operating System

windows

**Comment by hifabienne** [comment]
Hi @mahmoodfathy 
Thanks for your report. I quickly tested it, and could reproduce

**Comment by doncicuto** [comment]
Hei @hifabienne, may I've a look at this one?
