### ISSUE TITLE
[Bug]: Searching users by email with "contains" method yields validation error

### ISSUE THREAD

**Issue by cskeppstedt** [zitadel/zitadel#7850]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.50.3

### Database

PostgreSQL

### Database Version

14.4

### Describe the problem caused by this bug

I have a use-case for searching for an incomplete email. Let's say a user has the email "foobar@gmail.com", I would like to have a hit when searching with the term "foobar" like so:

```
{
  "query": { "asc": true, "offset": 0,"limit": 50 },
  "queries": [
    { "emailQuery": { "emailAddress": "foobar", "method": 5 } }
  ]
}
```

This is for the v2 search users request: https://zitadel.com/docs/apis/resources/user_service/user-service-list-users

The way the search works today, it throws an error saying "foobar" is not a valid email address. The validation was a bit unexpected for the "contains", "starts with" or "ends with" methods – you'd usually not supply a fully valid email for those methods – but it makes sense for the "equals" methods.

It's a feature we really would like to have since it makes our lives easier finding the right users, so I wanted to ask if this is something that you've reflected on, planned for in the near future, and so on. I opened a question in the discord, and was recommended to open a bug report since this seemed like a bug.

### To reproduce

1. Create a user with email foobar@gmail.com
2. Make a v2 search users request: https://zitadel.com/docs/apis/resources/user_service/user-service-list-users with the body:
      ```
      {
        "query": { "asc": true, "offset": 0,"limit": 50 },
        "queries": [
          { "emailQuery": { "emailAddress": "foobar", "method": 5 } }
        ]
      }
      ```
3. See that the response contains a validation error saying "foobar" is not a valid email:
    > /zitadel.user.v2beta.UserService/ListUsers INVALID_ARGUMENT: invalid ListUsersRequest.Queries[0]: embedded message failed validation | caused by: invalid SearchQuery.EmailQuery: embedded message failed validation | caused by: invalid EmailQuery.EmailAddress: value must be a valid email address | caused by: mail: missing '@' or angle-addr

### Expected behavior

The following methods should permit search with a partial/incomplete email address:
- TEXT_QUERY_METHOD_STARTS_WITH
- TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE
- TEXT_QUERY_METHOD_CONTAINS
- TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE
- TEXT_QUERY_METHOD_ENDS_WITH
- TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE

### Additional Context

Opened a question in the discord: https://discord.com/channels/927474939156643850/1232766441107755099

**Comment by hifabienne** [comment]
Hi @cskeppstedt 
Thanks for the report, can you add the exact error message you get.
This makes it easier for us to find the problem

**Comment by cskeppstedt** [comment]
Of course! I updated the original description with the error message:
> /zitadel.user.v2beta.UserService/ListUsers INVALID_ARGUMENT: invalid ListUsersRequest.Queries[0]: embedded message failed validation | caused by: invalid SearchQuery.EmailQuery: embedded message failed validation | caused by: invalid EmailQuery.EmailAddress: value must be a valid email address | caused by: mail: missing '@' or angle-addr

**Comment by doncicuto** [comment]
@hifabienne I can reproduce the issue, if you can assign this issue to me I'm available
