### ISSUE TITLE
Actions - Human readable name vs JS function name

### ISSUE THREAD

**Issue by benr77** [zitadel/zitadel#7874]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When creating an action, I lost several hours working out why it was not running. 

It turns out that the action name must match the name of the JS function for it to run.

### Describe your ideal solution

This is all very counter-intuitive. Why even allow naming an action if its name can be derived directly from the JS method name anyway? 

Secondly, allowing creating a name for the action implies that you can use some kind of human-readable name such as "Flatten all roles" and then use a camelCase name for the JS method "flatRoles" etc.

Can I suggest either separating the requirement for these to be the same, which would allow more descriptive human readable names. Alternatively, put a note on the "create action" modal popup stating this name field must match the JS function.
Thanks

### Version

2.51.0

### Environment

Self-hosted

## Acceptance Critiera

- [ ] Add note to the ZITADEL management console, that the name and function in the javascript have to be the same
Example: 
<img width="446" alt="image" src="https://github.com/zitadel/zitadel/assets/38692350/8dc11a49-378b-43f5-acdc-beeab1df35db">

**Comment by hifabienne** [comment]
Hei @benr77 
Thanks for adding the issue. It is absolutaly valid, and I think its not really intuitive, that they have to match.
However, as we are currently implementing our new actions v2 I think it doesnt make sense to change that in the current implementation. 
You can find the new implementaction for tracking here: https://github.com/zitadel/zitadel/issues/7235
I

@stebenz @peintnermax what is your opinion?

**Comment by benr77** [comment]
It looks like v2 is still some way off. I would still recommend adding a textual note at least to the modal popup, simply reiterating the required matching of name and function name. This would not change the v1 behaviour but will likely save users a lot of frustration.

**Comment by hifabienne** [comment]
Yes, I think it would make sense to add a note in the management console. I will add some acceptance criteria to your issue to at least add a note.
