### ISSUE TITLE
Import TOTP secrets

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#7881]
As a developer I want to be able to add an existing TOTP secret when importing / adding a user in ZITADEL.

## Acceptance criteria
- [x] I am able to provide the TOTP secret in the [AddHuman request](https://zitadel.com/docs/apis/resources/user_service/user-service-add-human-user)
- [x] The newly created user is able to authenticate by TOTP (e.g. totp_challenge on session API / login UI) using the existing account / entry on their authenticator app.

**Comment by hifabienne** [comment]
@livio-a @muhlemmer can you estimate this issue, so we can take it into the next spring?

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you please estimate this issue before we start the next sprint?

**Comment by stebenz** [comment]
Estimation:
- additional function to directly create OTP through secret: 0.5d
- testing with user and session API: 0.5d
