### ISSUE TITLE
[Bug]: "Password Reset allowed" setting has wrong name

### ISSUE THREAD

**Issue by errnesto** [zitadel/zitadel#7908]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.51.0

### Database

PostgreSQL

### Describe the problem caused by this bug

On the login page no "reset password" link is displayed even when "Password Reset allowed" is checked unchecking the box will display the link

### To reproduce

- Check the  "Password Reset allowed" and "Username and Password allowed" options in the organistion settings
- log out and go to the login page
- enter a valid username

-> no reset password link is displayed

### Screenshots

<img width="475" alt="Screenshot 2024-05-05 at 15 26 14" src="https://github.com/zitadel/zitadel/assets/3065968/fe16eb7e-f9c3-4035-b71b-3cc1cd2b31c0">

### Expected behavior

The label text or the setting should be reversed:

<img width="528" alt="Screenshot 2024-05-05 at 15 27 30" src="https://github.com/zitadel/zitadel/assets/3065968/4c1adddf-26bb-4a0d-b495-1c49551ffd20">

**Comment by errnesto** [comment]
I realized just now that the setting simply has the wrong label, so I updated the issue.

if "Password Reset allowed" is unchecked then the reset link is still shown

**Comment by hifabienne** [comment]
Hei, @errnesto you are right, the label is wrong.
It should actually be Password reset hidden, as it is only about hide the link in the ui and not about allowing or disallowing the functionality. We will change that
