### ISSUE TITLE
[Bug]: Unable to Share Verified Domains Across Multiple Organizations

### ISSUE THREAD

**Issue by shanil-sasikumar** [zitadel/zitadel#7928]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.51.3

### Database

None

### Describe the problem caused by this bug

I'm encountering a challenge in managing verified domains across multiple organizations within my self-hosted Zitadel instance. Currently, I have two organizations configured, each with its own set of verified domains. While I've successfully added domains like xxxx.com, yyyy.in, and zzzz.org to one organization, I'm unable to include these verified domains in the second organization. Consequently, I'm unable to register users with these domain names in the second organization.

For instance, I've added the domain gmail.com to organization1's verified domain list. As a result, I can register a user with user_name1@gmail.com within that organization. However, I encounter an issue when attempting to register user_name2@gmail.com in the second organization due to the inability to share verified domains across organizations. 

### To reproduce

1. Go to the Organization settings page
2. Click on Verified domains
3. Add a new domain as 'gmail.com'
4. Go to another organization settings page
5. Click on Verified domains
6. Add a new domain as 'gmail.com'

### Expected behavior

The requirement is to be able to share verified domains across multiple organizations within the Zitadel instance. Similar to common domains such as gmail.com and yahoo.com, users with these domain names should be registered across different organizations.

**Proposed Solutions:**

1. Instance-Level Domain Verification: Implement domain verification at the instance level to allow sharing of verified domains across all organizations within the Zitadel instance. This would enable users with common domain names to be registered across multiple organizations seamlessly.

2. Organization-Specific Domain Specification: Alternatively, provide the option to specify certain domains at the organization level, allowing organizations to share common domains if needed while maintaining organization-specific domains for unique user identification.

### Additional Context

**Real-World Scenarios:**

Multi-Tenant Setup: In scenarios where Zitadel is used in a multi-tenant environment, having the ability to share verified domains across organizations is crucial for efficient user management. This ensures that users with common domain names, such as Gmail or Yahoo, can be registered across different tenants without redundancy.
Consultants and External Users: Users who are not part of any specific organization but provide consultancy services to multiple organizations may have email addresses from common domains like Gmail or Yahoo. Enabling the registration of such users across various organizations using their common domain emails streamlines user management and access control.

**Additional Notes:**
Implementing the ability to share verified domains across organizations would enhance the flexibility and usability of Zitadel, particularly in scenarios involving multiple organizations with users having common domain email addresses.

**Comment by hifabienne** [comment]
Hei @shanil-sasikumar 
Thanks for opening up this issue.
We don't see this as a bug, as it works as designed.

Verified domains are to claim a domain for a specific organization. ZITADEL does need that to be able to do domain discovery and find out where a user belongs to.
From our perspective, there is no need of adding general domains such as gmail, yahoo, etc.

The organizations define where a user belongs to and which organization does manage them.
You could do one "General" Organization where you can add all the users, which do not directly belong to an organization.

Or you could also just add those users to a specific organization, but there is no need of adding the domain to the verfied domains. the verified domain does not restrict users of an organization, so they are only allowed with the verified domain.
