### ISSUE TITLE
SMTP templates. Show activate provider as another optional step 

### ISSUE THREAD

**Issue by doncicuto** [zitadel/zitadel#7929]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

@eliobischof suggested in [Discord](https://discord.com/channels/927474939156643850/1229787441485844544/1229842480527315004) that it'd good if you can activate the SMTP provider in a similar way as the new IDP wizard works. 

### Describe your ideal solution

Here's the screenshot for a new Google IDP

![image](https://github.com/zitadel/zitadel/assets/30386061/bfb242b5-fe86-4115-8ffd-5cdcea16d33d)

I'd add the 'active this SMTP provider' as an optional step once you create the provider (the dialog would not be closed and this step would be shown). 

I agree and I missed that option when developing SMTP templates... so I open an issue to track this feature. 

Of course, feel free to assign this issue to me.

### Environment

Self-hosted

**Comment by eliobischof** [comment]
I think especially for self-hosters without a default smtp config this feature could help a lot to avoid confusion, as in the provider list it's not obvious that a provider is inactive after creation and where it can be activated.

**Comment by doncicuto** [comment]
Hei @hifabienne I'm starting to work on this issue right now
