### ISSUE TITLE
[Bug]: "Password Reset allowed" checkbox has inverted functionality

### ISSUE THREAD

**Issue by hstehling** [zitadel/zitadel#7939]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.51.3

### Database

None

### Describe the problem caused by this bug

The "Login Behavior and Security" page in the instance/organisation settings features a checkbox labeled "Password Reset allowed". However, the behevaior of this checkbox is reversed, meaning it allows the feature when **not** checked.

### To reproduce

1. Go to "Login Behavior and Security" in your org settings
2. Check "Password Reset allowed", save
3. Open the hosted login page for your project and enter a valid e-mail address to reach the passord prompt
4. Observe if the "Reset Password" link is shown
5. Go back to the settings, uncheck the checkbox, save again, and repeat the login

### Expected behavior

When the checkbox is checked, the reset link should be shown, and vice versa.

Alternative: The checkbox in the config should read "_prevent_ password reset"

**Comment by hifabienne** [comment]
hei @hstehling 
Thanks for adding this issue.
The bug was already found earlier and resolved, you can see it here: https://github.com/zitadel/zitadel/issues/7908
