### ISSUE TITLE
[self-hosted ]Update the version of image used in getting-started-with-zitadel.sh

### ISSUE THREAD

**Issue by cmacheret** [zitadel/zitadel#7947]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

The version used in the getting-started-with-zitadel.sh script should be updated. 

The Zitadel version is for example more than a year old (2.31.3) and has several security vulnerabilities (https://github.com/zitadel/zitadel/security). 

### Describe your ideal solution

Update the image version every few months. 

For example this setup works :
Zitadel image :
'ghcr.io/zitadel/zitadel:v2.43.11'

CockroackDB image:
cockroachdb/cockroach:latest-v22.2

### Environment

Self-hosted

**Comment by eliobischof** [comment]
Sorry for the delay, this issue slipped through the cracks.
From where do you have this file? Is this issue obsolete?

**Comment by cmacheret** [comment]
Hi @eliobischof 

Sorry for the late reply, I've just noticed now that I posted this issue in your github account (zitadel), this was for "netbird". They use your IDP but in their example they are using some old version of Zitatel...

This can be closed!
Best regards
