### ISSUE TITLE
[Bug]: Error with Feature-Policy header

### ISSUE THREAD

**Issue by sebastianbuechler** [zitadel/zitadel#7949]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

The login endpoint will provoke an error because of duplicate header entries:
![image](https://github.com/zitadel/zitadel/assets/42775578/e1d22839-2534-4617-92eb-f5444df2e252)
Here's what we get in the response headers:
![image](https://github.com/zitadel/zitadel/assets/42775578/e2cda967-58da-41dd-bc31-46d037a5779f)

### To reproduce

1. Login with an application that uses Zitadel Cloud (and probably also hosted?)
2. Observe console logs of the browser

### Operating System

Browser: Chrome, Version 124.0.6367.119 (Official Build) (64-Bit)

**Comment by livio-a** [comment]
Hey @sebastianbuechler 

This intentional and only a warning. The `Permission Policy` will replace the `Feature-Policy` in the future, but since not every browser already supports it, we currently makes sure it's taken up by either policy.
