### ISSUE TITLE
[Bug]: Umlaut in sender name not shown correctly

### ISSUE THREAD

**Issue by 0xd3e** [zitadel/zitadel#7976]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.52.0

### Database

None

### Describe the problem caused by this bug

I've added our SMTP provider to our cloud instance. Our company name is "RÄUMLICH" so I've set the Sender Name to this value. Unfortunately there seems to be an issue with umlauts because my mail client shows "RÃUMLICH".

The raw email message shows this =?UTF-8?Q?R=C3=83=C2=84UMLICH=20?=.

### To reproduce

1. Go to instance settings > SMT Provider
2. Click on the configured provider to edit
3. Click Continue
4. Enter a sender name that contains an umlaut
5. Click save
6. Create new user in an organization using an email address you can access
7. Check your email inbox and look at the name of the sender

### Expected behavior

Umlaut should be shown correctly

### Additional Context

The PR #6637 seems to fix a similar issue for the email subject.

**Comment by doncicuto** [comment]
Hi @0xd3e I can't reproduce the issue. I've sent several messages using SMTP2GO and Mailgun to my test mailboxes in Gmail and Exchange and web clients like Gmail, OWA and Outlook.com and heavy clients like Thunderbird and all of them show RAÜMLICH. 

Anyway I've added a quick fix based on #6637. Would it be possible to you to talk on Discord with me and test this fix against a test mailbox you control and check that the umlaut issue would be fixed before I create the PR?

**Comment by 0xd3e** [comment]
Thanks, yes that's possible. I'll send you a DM.

**Comment by doncicuto** [comment]
Thanks a lot @0xd3e for your time testing with me and documenting your findings. I think PR #8193 then will be useful to tackle these situations
