### ISSUE TITLE
[Bug]: Email verified attribute is not set as true for External user authenticated by LDAP Identity provider

### ISSUE THREAD

**Issue by singhajitk** [zitadel/zitadel#7991]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.52.0

### Database

PostgreSQL

### Database Version

Postgres 13

### Describe the problem caused by this bug

Email verified attribute is not set as true for External user authenticated by LDAP Identity provider.  

I have set action to  setEmailVerified(true)  which triggers Post-Authentication/Pre-Creation in External Authentication Flow but VerifiedEmail property is not set as true for the LDAP Authenticated user.    Instead, I am getting error in log that "message":"action run failed: function not found","logLevel":"error".

### To reproduce

1) Deploy Self hosted Zitadel
2) Add LDAP Identity provider 
3) Add Action to setEmailVerified(true) for External Authentication flow in triggers Post-Authentication/Pre-Creation
4) Login to Zitadel UI as External user using LDAP Identity provider

Zitadel UI lands on "E-Mail Verification"  and "code" required to input to login.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/147015877/339189b1-bc9b-4d12-b9f2-34795fdff7ed)

### Expected behavior

User should be able to Navigate to User Page without the need to input the "E-Mail Verification" code after authentication.

### Operating System

Kubernetes cluster
OS - Linux  5.15.0-101-generic  #111-Ubuntu SMP  x86_64  GNU/Linux
Browser - Chrome - Version 124.0.6367.208

**Comment by francescoVenuto** [comment]
Hi, I have the same problem. I would therefore be interested in finding a solution. I followed the guide at the following link:https://github.com/zitadel/zitadel/discussions/4145
but unfortunately it didn't work
Thanks for your help
Francesco

**Comment by livio-a** [comment]
Hey @singhajitk and @francescoVenuto 
Can you quickly check / confirm that the name of the actions is the same as the function name side the scipt?
This is currently required for actions to be executed.

**Comment by yann-soubeyrand** [comment]
Hi @livio-a, I confirm I’ve been able to automatically set `emailVerified` to true using an action which name is the same as the function name.

**Comment by singhajitk** [comment]
Thanks @livio-a ,  Got it working with this change.

**Comment by dragetd** [comment]
> Hey [@singhajitk](https://github.com/singhajitk) and [@francescoVenuto](https://github.com/francescoVenuto) Can you quickly check / confirm that the name of the actions is the same as the function name side the scipt? This is currently required for actions to be executed.

This is not that obvious in the documentation. Thank you for saying this, you solved my issue since I was using the wrong name!
