### ISSUE TITLE
The verify button in email should NOT be present

### ISSUE THREAD

**Issue by Ludocare** [zitadel/zitadel#8000]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I'm using Zitadel Login UI.
This UI is embedded in a mobile app.
We create a new user from V2Beta endpoint.
When doing the first authentication, the login UI ask to verify email.
I have to fill out the code received in the email.

However, in the email, there is a button to verify the email.
The link will open a new tab browser, will say it's ok.
But in the mobile app, then I'm stuck, I can't verify the code, I can't go back.

When verifying the phone number, there is no link in the SMS (and it seems normal).

Moreover, from security point of view, I think it's not a good practice to have a button to verify the email.
We should only have the code, and goes back to the first screen that the user opened intentionnaly.
This will avoid mistakes from users when receiving phishing emails.

### Describe your ideal solution

Remove the verify button from the verification mail.

### Version

v2.52.0

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.
