### ISSUE TITLE
[Bug]: There isn't any migration associated with the new table of privacy_policies4.

### ISSUE THREAD

**Issue by mario-shang** [zitadel/zitadel#8022]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.48.5

### Database

None

### Describe the problem caused by this bug

I used the older version where there is a "privacy_policies3" table, but this commit creates the new table "privacy_policies4," yet there isn't any associated migration for it.
15d5338: feat(cnsl): docs link can be customized and custom button is available (#7840) 

### To reproduce

1. test the new version from an older version database
2. run setup command 
3. run zitadel

**Comment by muhlemmer** [comment]
Hi @mario-shang we do not migrate tables. Instead, we use an event store. Once a new projection is defined all events are "replayed" to build the new projection.

Is there any data missing in the new table?
