### ISSUE TITLE
OIDC signing key usage

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8031]
As an admin I want to be able to create, rotate and disable signing keys for OIDC tokens manually. Keys only exist on instance level, as they represent the issuer (instance domain).

### api/oidc

- [x] The `jwks_uri`  endpoint (public endpoint) returns all public keys of the instance
- [x] Set a cache header on the `jwks_uri`
- [x] Replace the `Provider().Storage().SigningKey()` method with a query.Queries method to get the current active signing key
- [x] Serve key algorithms on discovery endpoint

**Comment by danielloader** [comment]
Congrats on shipping this, thanks a lot.
