### ISSUE TITLE
Remove Password Age Policy

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#8044]
The password age policy can be managed but it doesn't do anything. This is confusing and we basically maintain dead code. The feature has not enough requests that justifies finishing its implementation. Our data doesn't show any signs of usage. Therefore we deprecate the APIs and then delete them.

As a user, I only want to wrap my head around methods that actually matter, so that I don't waste my time.
As a developer, I want to maintain code that is actually used, so that I don't waste my time.

**Acceptance Criteria**
- [x] Methods are marked as deprecated and as noop methods in docs.
- [x] Logs print deprecation warnings when the methods are called.
- [x] Their removal is announced with an exact release version in docs and logs.
- [ ] Methods, code, default config and translations related to password age policies eventually are removed.

**Comment by eliobischof** [comment]
@hifabienne do you have something to add?

**Comment by hifabienne** [comment]
Do we need to deprecate them before we can delete? as they are actually not implemented can't we just delete them?

**Comment by eliobischof** [comment]
They are implemented, the policy just doesn't do anything. This means theoretically, clients could stop working.

**Comment by eliobischof** [comment]
I removed the webhooks from the website latency SLO, which is now green, and added the api/billing/report-usage webhook endpoint to the webhook success metric which is now worse

**Comment by hifabienne** [comment]
Ok. I missunderstood, I thought its not even implemented in the backend and we do not store it.
In that case I am fine with the deprecation warning, do we already have a timeline when we will remove after deprecation?

**Comment by eliobischof** [comment]
> Ok. I missunderstood, I thought its not even implemented in the backend and we do not store it.
> In that case I am fine with the deprecation warning, do we already have a timeline when we will remove after deprecation?

I'd have the warning in two minors and remove it in the third. I will deprecate the methods today.

**Comment by ashep** [comment]
Hi there. By the way, I have a related question about this functionality https://github.com/zitadel/zitadel/discussions/8048.

In short, in my project, I need to force users to change their passwords every N months, and I am trying to figure out how to achieve this after I've found than Zitadel doesn't implement this.

Can someone point me out how to at least find the time of the user's last password change?

Thenk you.

**Comment by eliobischof** [comment]
We rethought this and come up with another solution
