### ISSUE TITLE
[Bug]: v2.54.x - High CPU utilization

### ISSUE THREAD

**Issue by alexdelprete** [zitadel/zitadel#8059]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.1

### Database

PostgreSQL

### Database Version

16.3-1

### Describe the problem caused by this bug

2.54.x uses constantly 16% of cpu (average), 2.53.x uses 0.7%.

See screenshots below.

### To reproduce

Just start the container with appropriate versions.

### Screenshots

2.54.x
![image](https://github.com/zitadel/zitadel/assets/7027842/7181d0df-f621-4507-bd7f-407cd3ab8d4a)

2.53.4
![image](https://github.com/zitadel/zitadel/assets/7027842/fd8fd7d5-417f-4a20-a739-10c31c9066ab)

### Expected behavior

I expect zitadel 2.54.x to consume less resources, like 2.53.x.

### Operating System

- Debian 12 Bookworm
- Docker version 26.1.3
- PostgreSQL 16.3-1

**Comment by Aurel004** [comment]
I've the same issue running on Docker Synology. As it is not a high-end CPU, it hits to 90% usage for 2.54.x vs 3% for the 2.53.x versions and below

**Comment by ilbarone87** [comment]
Both my rke2 suffered of an increase in CPU usage since 2.54.0

![image](https://github.com/zitadel/zitadel/assets/5686347/c9979dd7-3dd9-4a2f-97b6-fe719f670ea8)

**Comment by gameserver-express** [comment]
On an idle instance the database usage is also *much* higher.
![Bildschirmfoto am 2024-06-02 um 08 45 29](https://github.com/zitadel/zitadel/assets/100069292/56ea23df-6399-4473-9720-7c1127c06d4e)

**Comment by alexdelprete** [comment]
> On an idle instance the database usage is also _much_ higher.

Indeed. That's why I suspect the issue is DB related, but it's just speculation.

**Comment by ilbarone87** [comment]
Yeap increase on the DB looks clear from logs and metrics
![image](https://github.com/zitadel/zitadel/assets/5686347/bb1530bb-bbf0-4bc6-bcf0-db06565d3d65)

![image](https://github.com/zitadel/zitadel/assets/5686347/63b11bbf-28b5-4701-8075-b9c3eb5d84ef)

![image](https://github.com/zitadel/zitadel/assets/5686347/e11759e4-098a-46cc-8ab7-037bb7ce8963)

![image](https://github.com/zitadel/zitadel/assets/5686347/51280897-0e4a-4e5b-80ce-2dac1b598f21)

**Comment by hifabienne** [comment]
Do you experience the high cpu only some time after the startup?
We do have some projections that need to be recalculated with that version, this can result in higher CPU utilizaiton till the projections are done. It depends on the events and user count on how long this takes after startup.

**Comment by np-13** [comment]
I'm experiencing the same issue with the clean installation (v2.54.1, Postgres). The instance is empty with no extra configuration, and CPU and network activity were high for the whole time the process was running (~8 hours). In addition to the high resource usage, on the database side, it's showing a constant rate of ~260 transactions per minute.

Another observed issue, which is likely related to this (although it could be database driver specifics), is that the Postgres server connection is configured to use a domain name instead of an IP address (TLS is enabled). This results in a high volume of DNS queries sent. Interestingly, in my setup, it was ~260 queries per minute, which I believe is done every time a connection is made to the database.

As a quick test, I just tried running v2.53.4 and have not observed high CPU usage. However, there was still a high volume of DNS queries sent to resolve the database hostname.

**Comment by adlerhurst** [comment]
Thanks for the additional we try to reproduce and come back asap

**Comment by np-13** [comment]
@adlerhurst thank you!

Also, ignore the bit about DNS queries - turns out it's the expected behaviour (see https://github.com/jackc/pgx/issues/913)

**Comment by alexdelprete** [comment]
> Do you experience the high cpu only some time after the startup?

Almost immediately...a few seconds...and it lasts forever (waited hours).

> It depends on the events and user count on how long this takes after startup.

I highly doubt that in a homelab scenario like mine and a few other people here, with only a few things configured and only 1 user in my case, it could take hours. I'm positive it's a bug.

**Comment by wmlele** [comment]
Just hit the same, on two instances, both new installs from docker/compose (although with the same compose, admittedly), but entirely different platforms. 
Hits 90-100% at start and stays like that for hours (forever?). No users or config. Just the default admin. Downgraded to 2.53.4, works fine.

**Comment by fforootd** [comment]
hey @alexdelprete 

Can you try something for us on the 2.54.1?

Pass this in the config:

```
Projections:
  RequeueEvery: 60s
```

Or as ENV `ZITADEL_PROJECTIONS_REQUEUEEVERY=60s`

**Comment by ilbarone87** [comment]
@fforootd seems that tps value is decreasing significantly after adding that in the config yaml
![image](https://github.com/zitadel/zitadel/assets/5686347/447ea4f8-eecd-4fb6-9388-0fdd44d16d57)

**Comment by fforootd** [comment]
Thank you! That confirms a hunch we had.

Looks like the "mirror" command introduced the value from the defaults.yaml is not applied anymore correctly.

@livio-a @adlerhurst I think this confirms what we today spoke about in the train 😁

**Comment by alexdelprete** [comment]
> hey @alexdelprete
> 
> Can you try something for us on the 2.54.1?
> 
> Pass this in the config:
> 
> ```
> Projections:
>   RequeueEvery: 60s
> ```
> 
> Or as ENV `ZITADEL_PROJECTIONS_REQUEUEEVERY=60s`

Sorry for the late reply, I was traveling: that change seems to have fixed the problem. Thanks.

![image](https://github.com/zitadel/zitadel/assets/7027842/0ad53ade-1a60-433f-8e62-464c8c7d69f7)

**Comment by fforootd** [comment]
Great to know that... so we will fix this in a bugfix on our end 😁

**Comment by alexdelprete** [comment]
Can I close the issue or do you want to keep it open?

**Comment by adlerhurst** [comment]
> Can I close the issue or do you want to keep it open? 

Please keep it open we will provide a fix within the next days

**Comment by alexdelprete** [comment]
Thanks for your support.

**Comment by ilbarone87** [comment]
@adlerhurst can we remove the configuration value added as a workaround to fix the issue previously?

**Comment by adlerhurst** [comment]
> @adlerhurst can we remove the configuration value added as a workaround to fix the issue previously after the new release?

Yes it should use the default afterwards as it did before.

**Comment by livio-a** [comment]
The fix is now release in 2.54.2: https://github.com/zitadel/zitadel/releases/tag/v2.54.2

**Comment by alexdelprete** [comment]
> The fix is now release in 2.54.2

Upgraded, seems to work fine. Thanks a lot for the great support.
