### ISSUE TITLE
[Bug]: Missing roles on token

### ISSUE THREAD

**Issue by sschoeb** [zitadel/zitadel#8066]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

We saw this problem only once, but as it looks like an inconsistency, I thought I want to report it to you.

After the login using your login-form, we get the access_token from the code-exchange. This works perfectly fine, except once we got no roles within the token (which then in our app leads to an error screen). 

Doing a new login we got the proper roles again.

Here is the content of the token where we missed the roles:
```
{
  "aud": [
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX"
  ],
  "exp": 1717267593,
  "iat": 1717137993,
  "iss": "XXXXXXXXXXXXXXX",
  "jti": "V2_269380088506630730-at_269512542009720164",
  "nbf": 1717137993,
  "sub": "119811590336930228",
  "urn:zitadel:iam:org:domain:primary": "micromate.ai",
  "urn:zitadel:iam:user:metadata": {
    "createdOn": "UHJvZHVjdGlvbg",
    "initialized": "dHJ1ZQ"
  }
}
```

And here the token how it usually looks like:
```
{
  "aud": [
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX@micromate",
    "XXXXXXXXXXXXXXX"
  ],
  "exp": 1717524539,
  "iat": 1717394939,
  "iss": "XXXXXXXXXXXXXXX",
  "jti": "V2_269943626686082197-at_269943626686147733",
  "nbf": 1717394939,
  "sub": "119811590336930228",
  "urn:zitadel:iam:org:domain:primary": "micromate.ai",
  "urn:zitadel:iam:org:project:XXXXXXXXXXXXXXXXXXXXX:roles": {
    "LEARNER": {
      "<roleid>": "XXXXXXXXXXXXXXXXXXXX"
    },
    .... <- here are some more roles, I removed them to simplify the example
  },
  "urn:zitadel:iam:user:metadata": {
    "createdOn": "UHJvZHVjdGlvbg",
    "initialized": "dHJ1ZQ"
  }
}
```

We did not add/remove roles during this time. So I would expect to get the same roles. 
I think this is not super urgent, as it works 99.9999% of the time, but maybe as a hint that there may be something somewhere wrong? Let me know if you need any further information.

### To reproduce

We cannot reproduce this.

**Comment by livio-a** [comment]
Hey @sschoeb 

This might have been an issue with 2.53.0. We noticed something similar and did a fix: https://github.com/zitadel/zitadel/pull/8046

Thanks for reporting. We'll close it since it should be fixed now.
