### ISSUE TITLE
[Bug]: users keep the domain suffix after turning off setting which adds domain to login name

### ISSUE THREAD

**Issue by demircis** [zitadel/zitadel#8073]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v.2.53.4

### Database

None

### Describe the problem caused by this bug

When the setting  "Add organization domain as suffix to loginnames" under domain settings is activated, the primary domain name will be added as a suffix for all users' (human and machine users) login name.

If this setting is turned off again, existing users will keep the domain suffix and only newly created users will not have the domain suffix.

### To reproduce

1. create a user (human or machine user)
2. activate the "Add organization domain as suffix to loginnames" setting
3. now the domain will be added for all users
4. turn off the setting
5. existing users will keep the domain suffix

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/22999224/e0e4983b-0f72-4434-a0a9-6082cc7668d5)

second user created prior to settings change and first user created after

### Expected behavior

the domain suffix should be removed from existing users as well and not only apply to newly created users after the settings change

**Comment by hifabienne** [comment]
hi @demircis 
At the moment this is implemented like this on purpose.
The domain suffix is added directly to the username of the existing users.
We do that, because otherwise the loginname of the user would change without their notice and they are not able to authenticate anymore.

**Comment by demircis** [comment]
Hi @hifabienne
Ok that makes sense. But this behavior did change recently, right? Because I remember that it behaved like I described in the expected behavior section.

Feel free to close this issue, since it is intended behavior.

**Comment by hifabienne** [comment]
> Hi @hifabienne Ok that makes sense. But this behavior did change recently, right? Because I remember that it behaved like I described in the expected behavior section.
> 
> Feel free to close this issue, since it is intended behavior.

No this didn't change recently, as far as I remember this has been like this since the start.
I will close the issue. thanks for your feedback
