### ISSUE TITLE
[Bug]: Microsoft Entra SAML - "Error: Response Invalid" but works when  SAML config saved again

### ISSUE THREAD

**Issue by rejochandran** [zitadel/zitadel#8078]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.1

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

When single sign on is configured with Microsoft SAML and when a user tries to login, the page throws  `Errors.Intent.ResponseInvalid` error on the sign in page. Ref Screenshot (1)

Logs on Zitadel when this error occurs:
```
time="2024-06-05T15:57:37Z" level=info msg="external authentication failed" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/external_provider_handler.go:342" error="ID=SAML-nuo0vphhh9 Message=Errors.Intent.ResponseInvalid Parent=(Authentication failed)" instance=270137843009978372 providerID=270292482518941699
2024-06-05 21:27:37 time="2024-06-05T15:57:37Z" level=info msg="log record emitted" caller="/home/runner/work/zitadel/zitadel/internal/logstore/emitters/stdout/stdout.go:19" record="{\"logDate\":\"2024-06-05T15:57:37.530765842Z\",\"took\":0,\"message\":\"action run started\",\"logLevel\":\"info\",\"instanceId\":\"270137843009978372\"}"
2024-06-05 21:27:37 time="2024-06-05T15:57:37Z" level=info msg="log record emitted" caller="/home/runner/work/zitadel/zitadel/internal/logstore/emitters/stdout/stdout.go:19" record="{\"logDate\":\"2024-06-05T15:57:37.531043467Z\",\"took\":277630,\"message\":\"action run failed: email is not found at userInfo (\\u003ceval\\u003e:59:7(177))\",\"logLevel\":\"error\",\"instanceId\":\"270137843009978372\"}"
2024-06-05 21:27:37 time="2024-06-05T15:57:37Z" level=warning msg="missing translation" args="map[]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/translator.go:161" error="message \"Errors.Intent.ResponseInvalid\" not found in language \"en\"" id=Errors.Intent.ResponseInvalid
```

We see the error is triggered suring `session.FetchUser`
https://github.com/zitadel/zitadel/blob/cedd992ab97a97755c7034528b8e72e3cf621076/internal/api/ui/login/external_provider_handler.go#L336-L347

Scenario 1:
- When configuring SAML, We had provided the metadata via the URL and Zitadel automatically sets the metadata
- Login attempted - results in error `Errors.Intent.ResponseInvalid`
- Go to the configuration page and add the metadata manually converting it to base64
- Login attempted - success! - the user is now able to login using SAML SSO
- again, we delete the SAML configuration and try adding it again using any method (via metadata URL or pasting base64 data)
- The login works and the error never appears again even when the config is deleted and added again any number of times

Scenario 2:
- When configuring SAML, We had provided the metadata by setting it directly by base64 encoding it
- Login attempted - results in error `Errors.Intent.ResponseInvalid`
- Go to the configuration page and add the metadata via URL
- Login attempted - success! - the user is now able to login using SAML SSO
- again, we delete the SAML configuration and try adding it again using any method (via metadata URL or pasting base64 data)
- The login works and the error never appears again even when the config is deleted and added again any number of times

In both the scenarios, login work when the setting is stores, edited again and the metadata source is updated and tried again.
We are not sure if its because of the metadata being changed or if just updating the setting makes the SSO work.

**NB: However, the error returns when the Enterprise Application on Azure is deleted and a new Enterprise Application is created and configured with Zitadel**

Since its a bit complex to reproduce the issue, please feel free to contact me for a quick meet to show the issue if required.

### To reproduce

In Azure Portal
1. Create an Enterprise Application
2. Go to the application settings and turn off "Assignment required?" under properties
3. Go to "Single sign-on", copy "App Federation Metadata Url"

In Zitadel,
1. Go to an organization -> Settings tab
2. Go to Identity providers on the left pane -> select "SAML SP"
3. Fill in any Name and paste the "App Federation Metadata Url" in the "Metadata URL" field that was copied earlier
4. in "Biding', choose "SAML_BINDING_POST" option
5. Enable "Signed Request"
6. Under optional, select "Automatic creation"
7. Finally click "Create"
8. Copy down the "ZITADEL Metadata", "ZITADEL ACS Login Form" and "ZITADEL Single Logout" for later use
9. Activate the identity provider
10. Click "Save" at the bottom

In Azure Portal,
1. Open the created Enterprise Application and go to "Single sign-on"
2. Click on "Edit" under "Basic SAML Configuration"
3. For "Identifier (Entity ID)", paste the "ZITADEL Metadata" copied earlier
4. For "Reply URL (Assertion Consumer Service URL)", paste the "ZITADEL ACS Login Form" copied earlier
5. For "Sign on URL", paste the "ZITADEL ACS Login Form" copied earlier
6. For "Logout Url (Optional)", paste the "ZITADEL Single Logout" copied earlier
7. Click "Save"

In your application (using Zitadel React wrapper):
1. Use the newly created SSO login
2. Results in error --- > Here we have the error

to get around the error:
1. Go to the "Single sign-on" page in App you had created in Azure
2. Download the metadata and base64 encode it
3. Go to Zitadel and edit the SAML configuration and paste the base64 encoded metadata and save
4. Try the login now - and it works

### Screenshots

Screenshot (1)
<img width="546" alt="Screenshot 2024-06-06 at 2 21 52 PM" src="https://github.com/zitadel/zitadel/assets/4696985/d2571650-8da6-4c3b-9065-be403ad9583c">

### Expected behavior

Once Microsoft Entra SAML is configured, the SSO should work without any changes being made over again.

### Operating System

OS: MacOS Sanoma 14.5 (23F79) and Windows 11
Browser: Google Chrome Version 120.0.6099.129

**Comment by stebenz** [comment]
Hi @rejochandran,
I tried to reproduce your error and found something in the [Entra documentation](https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol) with 'The cloud service (the service provider) uses an HTTP Redirect binding to pass an AuthnRequest (authentication request) element to Microsoft Entra ID (the identity provider).'

As I see that you specifically configure POST-binding, could you please either leave the binding option empty or use Redirect-binding? 
As it seems the binding when you update the provider gets set to empty unfortunately, and I suspect that to be the reason why it works then.
