### ISSUE TITLE
[Bug]: DocsLink empty value defaults to https://zitadel.com/docs

### ISSUE THREAD

**Issue by litetex** [zitadel/zitadel#8082]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.53.4 (as v2.54 series has [a bug](https://github.com/zitadel/zitadel/issues/8059))

### Database

PostgreSQL

### Describe the problem caused by this bug

Even when ``DocsLink`` is set to an empty string the "Documentation" Button is still visible on the UI and defaults to https://zitadel.com/docs
![g](https://github.com/zitadel/zitadel/assets/40789489/718c13d3-8e12-4cf3-9002-f65e85f6664b)

### To reproduce

1. Boot up zitadel with the following configuration:
```
DefaultInstance:
  PrivacyPolicy:
    DocsLink: ""
```
2. Create a new user
3. Login as that new user
4. Notice that the documentation button still shows up

**Comment by litetex** [comment]
Ok just did a quick recheck and it looks like ``DocsLink`` has no effect at all.
Even when I set it to some other value inside the org it always says https://zitadel.com/docs when logging in as another (non-admin) user

**Comment by eliobischof** [comment]
The DefaultInstance configs only take effect when you setup your first ZITADEL instance.
You can either change the setting via API/Console or you can reconfigure DefaultInstance as you mentioned and setup ZITADEL again on a clean database.

If you change the setting on an org, make sure [you pass the org context with your auth request](https://zitadel.com/docs/apis/openidoauth/authrequest#organization-policies-and-branding).

I will reopen the issue if my answer doesn't help.
