### ISSUE TITLE
[Bug]: PAT token modal overflow

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#8084]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.53.4

### Database

None

### Describe the problem caused by this bug

Modal for showing PAT tokens overflows which makes it hard to copy the token

### To reproduce

Create multiple pat tokens via Console

### Screenshots

As expected: 

<img width="406" alt="Screenshot 2024-06-10 at 08 52 17" src="https://github.com/zitadel/zitadel/assets/1366906/057e3512-544a-4271-b99b-ea2a471a7ca2">

Broken: 

<img width="419" alt="Screenshot 2024-06-10 at 08 51 45" src="https://github.com/zitadel/zitadel/assets/1366906/b7069f41-81e1-407c-8be1-17f9c32af29f">
<img width="402" alt="Screenshot 2024-06-10 at 08 51 55" src="https://github.com/zitadel/zitadel/assets/1366906/eaa31a8d-259a-4e55-82b5-5eedeac86af8">

### Expected behavior

The modal and field width should be fixed and the token string wrapped according to the field.

**Comment by fcenedes** [comment]
issue also present in **v2.51.3** fyi :
![Screenshot 2024-06-10 at 11 33 29](https://github.com/zitadel/zitadel/assets/3593569/903bd799-2bd2-4457-9e40-acc092f6f687)

**Comment by doncicuto** [comment]
@hifabienne if you'd like to assign this issue to me I'll try to prepare the PR this evening or tomorrow morning

**Comment by doncicuto** [comment]
Hi @hifabienne I've created a PR for this issue. It's a three line PR and as it's an ugly bug (ugly just because it's a UI oddity :smile: ) maybe it can be reviewed and merged quickly in this sprint and make users happy. I'm glad that I'm back again with Zitadel contributions
