### ISSUE TITLE
[Bug]: Secret generator modals broken (dark theme)

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#8085]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.53.4

### Database

None

### Describe the problem caused by this bug

Modals in the "secret generator" settings are broken: 
- Dark font on dark background
- No margins in the modal

### To reproduce

Open any detail setting on "secret generator"

### Screenshots

<img width="426" alt="Screenshot 2024-06-10 at 09 01 53" src="https://github.com/zitadel/zitadel/assets/1366906/edb18153-5a9c-45b6-b8f7-d82476fc2ab6">

**Comment by doncicuto** [comment]
@hifabienne if you'd like to assign this issue to me I'll try to prepare the PR this evening or tomorrow morning

**Comment by doncicuto** [comment]
Hei @hifabienne, one line PR this time to fix this issue :smile:
