### ISSUE TITLE
[Bug]: JWT of service user does not contain roles and has invalid "exp"

### ISSUE THREAD

**Issue by everesio** [zitadel/zitadel#8107]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.54.1

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

Following the https://github.com/zitadel/examples-api-access-and-token-introspection/ I have tested the "service-user-client-credentials" and "service-user-jwt" samples.
In both cases the service user roles were requested with the scope like 
```
openid profile email offline_access urn:zitadel:iam:org:project:id:{project_id}:aud urn:zitadel:iam:org:projects:roles urn:zitadel:iam:org:project:role:my_role

openid profile email urn:zitadel:iam:org:project:id:271182713795379205:aud urn:zitadel:iam:org:project:271182713795379205:roles urn:zitadel:iam:org:project:roles
```
The project has the "Assert Roles on Authentication" and "Check for Project on Authentication" options set. 

The returned JWT have following problems:
- missing role claims like e.g. `urn:zitadel:iam:org:project:roles`
- claims iat, `exp` and auth_time are equal

### To reproduce

* service user with roles / authorizations
* Reproduce with 

https://github.com/zitadel/examples-api-access-and-token-introspection/blob/main/service-user-client-credentials/client-credentials-token-generator.py

https://github.com/zitadel/examples-api-access-and-token-introspection/blob/main/service-user-jwt/jwt-profile-token-generator.py

* Check `roles` and `exp` claims 

### Additional Context

jwt-profile-token sample:

```
{
  "iss": "http://localhost:9080",
  "sub": "271182713610829829",
  "aud": [
    "271182713795379205",
    "271182713610829829"
  ],
  "exp": 1718135837,
  "iat": 1718135837,
  "auth_time": 1718135837,
  "azp": "271182713610829829",
  "client_id": "271182713610829829",
  "at_hash": "Yczzr_pxxNYs3V_Fatsxww"
}
```

client-credentials-token:
```
{
  "iss": "http://localhost:9080",
  "sub": "271182713610829829",
  "aud": [
    "271182713795379205",
    "java-service-sa"
  ],
  "exp": 1718135887,
  "iat": 1718135887,
  "auth_time": 1718135887,
  "amr": [
    "pwd"
  ],
  "azp": "java-service-sa",
  "client_id": "java-service-sa",
  "at_hash": "VfJqVa8Rc-2hJL-yrEwveg"
}
```

correct humen user id-token

```
{
  "amr": [
    "pwd"
  ],
  "at_hash": "0wJKQkkv4YMI5YXJVnQf9A",
  "aud": [
    "271182714063880197@mytest",
    "271182714097434629@mytest",
    "271182714147766277@mytest",
    "271182714281984005@mytest",
    "271182713795379205"
  ],
  "auth_time": 1718136658,
  "azp": "271182714063880197@mytest",
  "client_id": "271182714063880197@mytest",
  "exp": 1718179965,
  "family_name": "User",
  "given_name": "Genki",
  "iat": 1718136765,
  "iss": "http://localhost:9080",
  "locale": "en",
  "name": "Genki User",
  "nonce": "ftEZPizcINi_5_9XoS7E7l0cKqtN8OUC9d4W-gIJlXI",
  "preferred_username": "genki-user@genki.com",
  "sub": "271182713627607045",
  "updated_at": 1718133494,
  "urn:zitadel:iam:org:project:271182713795379205:roles": {
    "mytest_read": {
      "271182626855911429": "mytest.localhost"
    },
    "mytest_write": {
      "271182626855911429": "mytest.localhost"
    }
  },
  "urn:zitadel:iam:org:project:roles": {
    "mytest_read": {
      "271182626855911429": "mytest.localhost"
    },
    "mytest_write": {
      "271182626855911429": "mytest.localhost"
    }
  }
}
```

**Comment by livio-a** [comment]
Hey @everesio 

Regarding the roles:
The options `Assert Roles on Authentication` and `Check for Project on Authentication` will only apply to authentication though the login UI.
For m2m authentication you'll need request them by scopes. Providing the following should work in your case:
`openid profile email urn:zitadel:iam:org:project:id:271182713795379205:aud urn:zitadel:iam:org:projects:roles` (note the `s` at projects)

We cannot reproduce the problem of the `exp` being the same as `iat` / `auth_time`. Did you change any settings (runtime or in Console) regarding the token expiration?

**Comment by everesio** [comment]
Hi @livio-a 

I haven't change anything on the console. There are scripts I've used for tests (modification of your examples ) 
[test-bug-8107.zip](https://github.com/user-attachments/files/15803462/test-bug-8107.zip)

You can see that `id_token` has described problems.

I you want I can provide you all setup scripts i.e. docker-compose and terraform setup scripts.

**Comment by everesio** [comment]
The all setup scripts to reproduce the problem. In the zip there is a short README.md

[zitadel-bug-8107.zip](https://github.com/user-attachments/files/15807087/zitadel-bug-8107.zip)

**Comment by mogita** [comment]
Upgraded from v2.49.0 directly to v2.52.1, have not changed token_exchange process code, have not changed any config in the console, the `urn:zitadel:iam:org:project:roles` from the ID token claims was just gone. Not sure but looks related to this issue.

**Comment by muhlemmer** [comment]
@mogita

> Upgraded from v2.49.0 directly to v2.52.1

We introduced ID tokens for machine users only in https://github.com/zitadel/zitadel/pull/7822, as per feature request https://github.com/zitadel/oidc/issues/587. This was release in v2.53. So I'm confused here.

I can confirm the `urn:zitadel:iam:org:project:roles` is missing on the latest state of `main`. That's probably a bug, but not related to this issue.

@livio-a

> For m2m authentication you'll need request them by scopes. Providing the following should work in your case

 OP mentions ID Tokens, not access tokens. We introduced ID tokens at the above release. When I'm reproducing the issue, I see the roles in access tokens but not ID tokens. The https://github.com/zitadel/zitadel/pull/8046 fix hard-coded the `idTokenRoleAssertion` parameter to `false` here:

https://github.com/zitadel/zitadel/blob/2981ff04da1ed03f288b7a6dce09888aca683dda/internal/api/oidc/token_jwt_profile.go#L61

My question is: is that the behavior we want for **ID Tokens** in machine users? If so, we should document. If not, I can change it to `true` instead and always return the requested roles from the scope as with the access token.

**Comment by muhlemmer** [comment]
@mogita the `urn:zitadel:iam:org:project:roles` claim will only be present if we know the current project ID of the client application which made the auth request. As for machine users there is no parent project, the claim can't be asserted.

This is also [documented](https://zitadel.com/docs/apis/openidoauth/claims#reserved-claims):

>  This gives you the option to check in which organization a user has the role on the current project (**where your client belongs to**).

If somehow we did return this claim for machine users in older versions, than that was unintentional and a bug.

I've double checked with a human user and the claim is returned as it should, at least on current `main` / `v2.61.0`
