### ISSUE TITLE
[Bug]: User Registration disabled but still possible

### ISSUE THREAD

**Issue by sevensolutions** [zitadel/zitadel#8123]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.54.2

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

I've disabled public user registration via config file:
```yml
DefaultInstance:
  LoginPolicy:
    AllowRegister: false
```
I can confirm, that the setting is off, when looking at the UI:
<img width="828" alt="image" src="https://github.com/zitadel/zitadel/assets/84123899/fae87fcb-2084-487a-838c-0f883960b3e9">

There is no "Register" button on the login-forms. Thats ok, but if i manually navigate to https://login.mydomain.com/ui/login/register
i can fill out the form and a user will be created.

### To reproduce

1. Set config as described above
2. Spin up a new ZIATDEL using docker-compose
3. Validate User Registration is off by looking in the console
4. Navigate to: https://login.mydomain.com/ui/login/register
5. Try to sign up

### Expected behavior

I expect https://login.mydomain.com/ui/login/register to return 404.

**Comment by stebenz** [comment]
Through 'AllowRegister' only the option to register is switched off, there would need to be a check with the LoginPolicy in the renderRegister function.
Will move this issue to the Bugs section.

**Comment by sevensolutions** [comment]
@stebenz not showing the Register-form is one thing but this should also be handled in the API itself, i would say.
