### ISSUE TITLE
Add tooltip to indicator of the inherit button on "Feature Settings"

### ISSUE THREAD

**Issue by schettn** [zitadel/zitadel#8129]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Inside the “Feature Settings” of a zitadel instance most features are set to inherit. So the value is set to the programmatic default.

But how do I know what the default is?

There is some red bubble next to the “Inherit” button. Does this mean that the default is false or is it just decoration?

![image-4](https://github.com/zitadel/zitadel/assets/52858351/28f7d560-30e4-4a83-883c-92fc4cad9edf)

### Describe your ideal solution

A tooltip would be nice that displays the meaning behind the indicator.

### Environment

ZITADEL Cloud

### Additional Context

Maybe just highlighting the "Enabled" or "Disabled" button when "Inherit" is selected would be another way.

**Comment by schettn** [comment]
@hifabienne are the labels / product management automated via your account or are you just that fast?  xD

**Comment by hifabienne** [comment]
> @hifabienne are the labels / product management automated via your account or are you just that fast? xD

Some are automated. 😃 but in that case i think i was just that fast. I just started going through my notifications, and this was the first on top. Don't expect me to be always that fast. 😂

**Comment by andvvo** [comment]
I'm working on this

**Comment by hifabienne** [comment]
> I'm working on this

Great to hear, and thank you very much. I have just assigned you the task.

**Comment by andvvo** [comment]
Hi! Is something like this okay?

![Zitadel_Inherit_Indicator_Disabled](https://github.com/zitadel/zitadel/assets/121371226/d409d2c3-98a7-4f00-bc2e-627ef36b3290)

![Zitadel_Inherit_Indicator_Enabled](https://github.com/zitadel/zitadel/assets/121371226/4b00547e-6d4b-4d19-a058-da794461dd2d)

**Comment by hifabienne** [comment]
> Hi! Is something like this okay?
> 
> ![Zitadel_Inherit_Indicator_Disabled](https://private-user-images.githubusercontent.com/121371226/345151702-d409d2c3-98a7-4f00-bc2e-627ef36b3290.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUxNzAyLWQ0MDlkMmMzLTk4YTctNGYwMC1iYzJlLTYyN2VmMzZiMzI5MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1MTliMWNhMTk4ODVmYTIzZDM1YThjNjE0ZmU0YWMxZWNjOWMxMjg1NzJhNzE5YTVkMzA4MGQ5MDRhNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfsy5G_ttDBQZDggurNBnB8TJlCxeiwkaBNWNK5f6Zc) [ ![Zitadel_Inherit_Indicator_Disabled](https://private-user-images.githubusercontent.com/121371226/345151702-d409d2c3-98a7-4f00-bc2e-627ef36b3290.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUxNzAyLWQ0MDlkMmMzLTk4YTctNGYwMC1iYzJlLTYyN2VmMzZiMzI5MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1MTliMWNhMTk4ODVmYTIzZDM1YThjNjE0ZmU0YWMxZWNjOWMxMjg1NzJhNzE5YTVkMzA4MGQ5MDRhNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfsy5G_ttDBQZDggurNBnB8TJlCxeiwkaBNWNK5f6Zc) ](https://private-user-images.githubusercontent.com/121371226/345151702-d409d2c3-98a7-4f00-bc2e-627ef36b3290.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUxNzAyLWQ0MDlkMmMzLTk4YTctNGYwMC1iYzJlLTYyN2VmMzZiMzI5MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1MTliMWNhMTk4ODVmYTIzZDM1YThjNjE0ZmU0YWMxZWNjOWMxMjg1NzJhNzE5YTVkMzA4MGQ5MDRhNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfsy5G_ttDBQZDggurNBnB8TJlCxeiwkaBNWNK5f6Zc) [ ](https://private-user-images.githubusercontent.com/121371226/345151702-d409d2c3-98a7-4f00-bc2e-627ef36b3290.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUxNzAyLWQ0MDlkMmMzLTk4YTctNGYwMC1iYzJlLTYyN2VmMzZiMzI5MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1MTliMWNhMTk4ODVmYTIzZDM1YThjNjE0ZmU0YWMxZWNjOWMxMjg1NzJhNzE5YTVkMzA4MGQ5MDRhNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfsy5G_ttDBQZDggurNBnB8TJlCxeiwkaBNWNK5f6Zc)
> 
> ![Zitadel_Inherit_Indicator_Enabled](https://private-user-images.githubusercontent.com/121371226/345152521-4b00547e-6d4b-4d19-a058-da794461dd2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUyNTIxLTRiMDA1NDdlLTZkNGItNGQxOS1hMDU4LWRhNzk0NDYxZGQyZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjkyYmViYTIyODllOGE5YjUzNjU1MTA3YWU4Y2I1MjU5OTRiZWFlYjIyYWUwNWRkNDkyZDVhNWY4YzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V1YKBx5qsLITHbSUNQE1XC2XcpXN1SRp9oiyOKCi-Sc) [ ![Zitadel_Inherit_Indicator_Enabled](https://private-user-images.githubusercontent.com/121371226/345152521-4b00547e-6d4b-4d19-a058-da794461dd2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUyNTIxLTRiMDA1NDdlLTZkNGItNGQxOS1hMDU4LWRhNzk0NDYxZGQyZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjkyYmViYTIyODllOGE5YjUzNjU1MTA3YWU4Y2I1MjU5OTRiZWFlYjIyYWUwNWRkNDkyZDVhNWY4YzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V1YKBx5qsLITHbSUNQE1XC2XcpXN1SRp9oiyOKCi-Sc) ](https://private-user-images.githubusercontent.com/121371226/345152521-4b00547e-6d4b-4d19-a058-da794461dd2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUyNTIxLTRiMDA1NDdlLTZkNGItNGQxOS1hMDU4LWRhNzk0NDYxZGQyZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjkyYmViYTIyODllOGE5YjUzNjU1MTA3YWU4Y2I1MjU5OTRiZWFlYjIyYWUwNWRkNDkyZDVhNWY4YzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V1YKBx5qsLITHbSUNQE1XC2XcpXN1SRp9oiyOKCi-Sc) [ ](https://private-user-images.githubusercontent.com/121371226/345152521-4b00547e-6d4b-4d19-a058-da794461dd2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODcxNzgsIm5iZiI6MTcxOTk4Njg3OCwicGF0aCI6Ii8xMjEzNzEyMjYvMzQ1MTUyNTIxLTRiMDA1NDdlLTZkNGItNGQxOS1hMDU4LWRhNzk0NDYxZGQyZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNjA3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjkyYmViYTIyODllOGE5YjUzNjU1MTA3YWU4Y2I1MjU5OTRiZWFlYjIyYWUwNWRkNDkyZDVhNWY4YzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V1YKBx5qsLITHbSUNQE1XC2XcpXN1SRp9oiyOKCi-Sc)

This looks good to me, thanks!
