### ISSUE TITLE
[Operator] CRD support for IAM resources

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#816]
## Idea

When running **ZITADEL** in **K8s** it would be great to declare IAM resources like **Service Users**, **OpenID Connect** / **OAuth 2.0** clients as CRD.

This would be great, because application managed with GitOps would not need to implement the IAM api

> This was not actually my idea 😄 

## Possible solution

Extend the **ZITADEL-operator** to register those CRD's in the **k8s-api** and include a **Service User** into the **operator** to use the **zitadel-api**

**Comment by fgerschwiler** [comment]
@fforootd Is this still relevant? Or can we close this?

**Comment by fforootd** [comment]
Lets close this for now since we do not need an operator ATM

**Comment by dmolik** [comment]
I work in a regulated industry, and maintaining user access auditability is necessary, having a k8s-operator for an IDP is quickly becoming a must-have.

**Comment by fforootd** [comment]
> I work in a regulated industry, and maintaining user access auditability is necessary, having a k8s-operator for an IDP is quickly becoming a must-have.

At least the audit part is well covered in ZITADEL :grin: https://zitadel.com/docs/concepts/features/audit-trail

But I get the need for managing some thing declarative. ATM you can use terraform/pulumi
