### ISSUE TITLE
Update some get users APIs

### ISSUE THREAD

**Issue by quochuydev** [zitadel/zitadel#8172]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

forwarded from https://discord.com/channels/927474939156643850/1253214277553361026

### Describe your ideal solution

1. `GET /management/v1/global/users/_by_login_name `
As a developer, I would like to have `passwordChangeRequired` field in the result data, so I won't need to call another API
https://zitadel.com/docs/apis/resources/mgmt/management-service-get-user-by-login-name-global

2. `POST /v2beta/users `
As a developer, I would like to have `orgId` field in the result data for each user, so I won't need to call another API
https://zitadel.com/docs/apis/resources/user_service/user-service-list-users 

3. `POST /oauth/v2/introspect`
As a developer, I would like to have `user.state` field in the result data so I won't need to create an action to do it.

https://zitadel.com/docs/apis/openidoauth/claims

4.  `POST /oauth/v2/introspect`
As a developer, I would like to have `org.state` field in the result data when using the scopes `urn:zitadel:iam:user:resourceowner ` `urn:zitadel:iam:org:id:{id} `, so I won't need to create an action to have it

Hope you guys review and answer, thank team!

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hi @quochuydev 

Thanks for your feedback, we will have a look at the implementation.
1. and 2. make absolutely sense, and we will implement that.
3. and 4. are actually not neccessary, as you can only call the introspection with an active token, that you will only get if the user is active and the org is active. so we will not implement that.

**Comment by stebenz** [comment]
@quochuydev 
As you already use the user v2 API, did you try with the ListUsers endpoint for point number 1, with the LoginNameQuery?
This results in a resultlist with 1 user and the user already contains the passwordChangeRequired attribute under the HumanUser attribute.

**Comment by quochuydev** [comment]
> @quochuydev As you already use the user v2 API, did you try with the ListUsers endpoint for point number 1, with the LoginNameQuery? This results in a resultlist with 1 user and the user already contains the passwordChangeRequired attribute under the HumanUser attribute.

Ya thanks, just need to add organizationId for v2 search users, and then I can use only that API.

> Hi @quochuydev
> 
> Thanks for your feedback, we will have a look at the implementation.
> 
> 1. and 2. make absolutely sense, and we will implement that.
> 2. and 4. are actually not neccessary, as you can only call the introspection with an active token, that you will only get if the user is active and the org is active. so we will not implement that.

hi @hifabienne I just tested, when I login an user and then deactivate an Organization the next introspection is still active. (but correct when deactivating a singer user)
