### ISSUE TITLE
Actions V2 error message feedback

### ISSUE THREAD

**Issue by diegosz** [zitadel/zitadel#8177]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Forwarded from: https://discord.com/channels/927474939156643850/1253811958508032061

Using the new **Actions V2** functionality, when using `webhook` and `call` targets, currently there is no way to provide a proper error message to the user when we want to stop the execution.

Use Case: I'm planning to only accept user creation in Zitadel if the user is created in an external system first.
If the external system is not working or the action service is not working, no user could be created.
Beyond that the rest of the IAM functionality should work as usual.

Already tried it in a local deployment without any problem, was able to use `webhook` and `call` targets, both on the API and console using `/zitadel.user.v2beta.UserService/AddHumanUser` and `/zitadel.management.v1.ManagementService/AddHumanUser` executions.
Only tried with request executions.

When returning an HTTP error status and using the `interruptOnError` flag in the target, was able to stop the user creation.
The user was not created and the error was shown in the console as `ID=EXEC-dra6yamk98 Message=Errors.Execution.Failed`.

### Describe your ideal solution

I want to properly return an error message, so that on the API response or in the Zitadel console the user could see a better feedback.

### Version

v2.54.1

### Environment

Self-hosted

### Additional Context

Change the error returned on this line: https://github.com/zitadel/zitadel/blob/14aeb42cc29f2f1a14042eb44c20ea958395ddff/internal/execution/execution.go#L121

by adding the error from the body

**Comment by hifabienne** [comment]
@stebenz @adlerhurst I think this issue would absolutely make sense. Can you have a look at it, what it means in regards of implementation?

**Comment by adlerhurst** [comment]
Estimation: 1d
