### ISSUE TITLE
[Bug]: User not active when creating users with /v2beta/users/human api

### ISSUE THREAD

**Issue by nikzen** [zitadel/zitadel#8201]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.3

### Database

None

### Describe the problem caused by this bug

I try to import users using the v2beta/users/human api. The creation is successful, however it is not possible to login.

![image](https://github.com/zitadel/zitadel/assets/33399346/68d107e9-362e-4fb6-8513-2310e2d2e00f)

### To reproduce

Perform this call
```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/human' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
  "username": "minnie-mouse",
  "organization": {
    "orgId": "string"
  },
  "profile": {
    "givenName": "Minnie",
    "familyName": "Mouse"
  },
  "email": {
    "email": "mini@mouse.com",
    "isVerified": true
  },
  "phone": {
    "phone": "+41791234567",
    "isVerified": true
  },
  "metadata": [
    {
      "key": "my-key",
      "value": "VGhpcyBpcyBteSB0ZXN0IHZhbHVl"
    }
  ],
  "password": {
    "password": "Secr3tP4ssw0rd!",
    "changeRequired": true
  }
}'
```

Try to login with the user.

I realized that doing this call after the creation will fix it, however that is not quite ideal:

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/:userId/password' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "newPassword": {
    "password": "Secr3tP4ssw0rd!",
    "changeRequired": true
  }
}'
```

### Expected behavior

I expect that the user is able to login and needs to change the password.

**Comment by hifabienne** [comment]
thanks for opening the issue. 
This really sounds like a bug to me. 
We did have some problems previously when you either didn't set email to verified or no password, as we have the concept of initial state in the login. but got rid of that with our new api.
But as you are sending both i think that should work. 
I added the issue to investigating so someone will have a closer look.

**Comment by nikzen** [comment]
I tried out different things as well.

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/human' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
  "username": "minnie-mouse",
  "organization": {
    "orgId": "string"
  },
  "profile": {
    "givenName": "Minnie",
    "familyName": "Mouse"
  },
  "email": {
    "email": "mini@mouse.com"
  },
  "phone": {
    "phone": "+41791234567",
    "isVerified": true
  },
  "metadata": [
    {
      "key": "my-key",
      "value": "VGhpcyBpcyBteSB0ZXN0IHZhbHVl"
    }
  ]
}'
```

This API call does also not work. The user receives an email and when trying to set a password it fails with user not active.

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/human' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
  "username": "minnie-mouse",
  "organization": {
    "orgId": "string"
  },
  "profile": {
    "givenName": "Minnie",
    "familyName": "Mouse"
  },
  "email": {
    "email": "mini@mouse.com",
    "isVerified": true
  },
  "phone": {
    "phone": "+41791234567",
    "isVerified": true
  },
  "metadata": [
    {
      "key": "my-key",
      "value": "VGhpcyBpcyBteSB0ZXN0IHZhbHVl"
    }
  ],
  "idpLinks": [
    {
      "idpId": "270298635294474248",
      "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
      "userName": "minnie-mouse"
    }
}'
```

SSO with LDAP is working for the user after this request. I hope that might help you.

**Comment by livio-a** [comment]
Hi @nikzen i tried to reproduce the issue with the latest version and 2.54.3 but the created users were always active
Do you get an error id, for example in the logs?

**Comment by nikzen** [comment]
> Hi @nikzen i tried to reproduce the issue with the latest version and 2.54.3 but the created users were always active Do you get an error id, for example in the logs?

Hey @livio-a i digged into the issue a little bit deeper. So it actually happens if you create the user a second time with the same user-id. 

Steps to reproduce:

1. 

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/human' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
  "username": "minnie-mouse",
  "organization": {
    "orgId": "string"
  },
  "profile": {
    "givenName": "Minnie",
    "familyName": "Mouse"
  },
  "email": {
    "email": "mini@mouse.com",
    "isVerified": true
  },
  "phone": {
    "phone": "+41791234567",
    "isVerified": true
  },
  "metadata": [
    {
      "key": "my-key",
      "value": "VGhpcyBpcyBteSB0ZXN0IHZhbHVl"
    }
  ],
  "password": {
    "password": "Secr3tP4ssw0rd!",
    "changeRequired": true
  }
}'
```

2. Delete User

3. 

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/v2beta/users/human' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userId": "d654e6ba-70a3-48ef-a95d-37c8d8a7901a",
  "username": "minnie-mouse",
  "organization": {
    "orgId": "string"
  },
  "profile": {
    "givenName": "Minnie",
    "familyName": "Mouse"
  },
  "email": {
    "email": "mini@mouse.com",
    "isVerified": true
  },
  "phone": {
    "phone": "+41791234567",
    "isVerified": true
  },
  "metadata": [
    {
      "key": "my-key",
      "value": "VGhpcyBpcyBteSB0ZXN0IHZhbHVl"
    }
  ],
  "password": {
    "password": "Secr3tP4ssw0rd!",
    "changeRequired": true
  }
}'
```

4. User is shown as inactive

I hope this helps you to find the root cause.

Best,

Niklas

**Comment by livio-a** [comment]
> > Hi @nikzen i tried to reproduce the issue with the latest version and 2.54.3 but the created users were always active Do you get an error id, for example in the logs?
> 
> Hey @livio-a i digged into the issue a little bit deeper. So it actually happens if you create the user a second time with the same userId.
> 

Hey @nikzen thanks for that information. That for sure helps and will look into it early next week.

**Comment by livio-a** [comment]
Found the issue and already have a fix for it. Should be released in the next few days
