### ISSUE TITLE
[Bug]: SAML certificate has suddenly changed

### ISSUE THREAD

**Issue by rhizoet** [zitadel/zitadel#8206]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Version

7.15.0

### App version

v2.51.3

### Describe the problem caused by this bug

We use Kimai2 (latest helm chart) with Zitadel and SAML Auth.
Today one of our colleagues noticed that the login is no longer possible.

After some research, I realized that the SAML certificate has changed. I have not changed this or anything.

Is this renewed after a certain time or did it come with an update and was renewed in the process?

Is it possible to deactivate this automatic renewal, if there is one, or something similar? Because we also have instances with customers and it is annoying if they suddenly can no longer log in.

Unfortunately, I cannot provide any further information or data. I had compared the certificates and noticed it.

### To reproduce

You can't reproduce that. 

### Logs

none

### Expected behavior

I would expect the certificate to always remain the same and not change randomly. 

### Relevant Configuration

none

**Comment by fforootd** [comment]
I am not aware that we change the cert automatically but @stebenz will be able to confirm here.

**Comment by stebenz** [comment]
@rhizoet 
The certificate has a lifetime of 1 year in the default configuration, but can be changed.

@fforootd 
https://github.com/zitadel/zitadel/blob/d92717a1c60e3125eeb5227f3659c24cce130f2f/cmd/defaults.yaml#L529

As the keys are handled also with a lifetime in OIDC, do we need to have a look that it's also possible with no expiry?

**Comment by fforootd** [comment]
@stebenz thank you... I completely forgot about that.

**Comment by livio-a** [comment]
I'll close this issue, since there's no bug.
