### ISSUE TITLE
[Bug]: Errors.ExternalIDP.CreationNotAllowed (COMMAND-SJI3g)

### ISSUE THREAD

**Issue by nikzen** [zitadel/zitadel#8208]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.55.0

### Database

PostgreSQL

### Describe the problem caused by this bug

As the betav2 create user api call does not work work us right now, we want to use https://zitadel.com/docs/apis/resources/mgmt/management-service-import-human-user to create users. However this also results in an error.

Right now this means we can't really use the import apis to migrate users to zitadel.

### To reproduce

```
curl -L -X POST 'https://$CUSTOM-DOMAIN/management/v1/users/human/_import' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>' \
--data-raw '{
  "userName": "minnie-mouse",
  "profile": {
    "firstName": "Minnie",
    "lastName": "Mouse",
    "displayName": "Minnie Mouse"
  },
  "email": {
    "email": "minnie@mouse.com",
    "isEmailVerified": true
  },
  "phone": {
    "phone": "+41 71 000 00 00",
    "isPhoneVerified": true
  },
  "idps": [
    {
      "configId": "idp-config-id",
      "externalUserId": "external-user-id",
      "displayName": "minnie-mouse"
    }
  ]
}'
```

**Response**

```
{
  code 9
  message Errors.ExternalIDP.CreationNotAllowed (COMMAND-SJI3g)
  details
    
      @type type.googleapis.com/zitadel.v1.ErrorDetail
      id COMMAND-SJI3g
      message Errors.ExternalIDP.CreationNotAllowed
}
```

### Expected behavior

I would expect the user is created.

**Comment by hifabienne** [comment]
Is the option Create IDP Account allowed on the idp?
This needs to be enabled.

**Comment by nikzen** [comment]
> Is the option Create IDP Account allowed on the idp? This needs to be enabled.

No, it wasn't - my bad. So this means that the v2bet/human does not need this setting as this is working without allowing the account creation, however this api needs it?
