### ISSUE TITLE
[Bug]: critical bug in session's

### ISSUE THREAD

**Issue by AmirhoseinBrz** [zitadel/zitadel#8213]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Database

CockroachDB

### Describe the problem caused by this bug

According to the tests I had in the session section of version 1 
Regardless of the entries that I put in the header, they all return, and can this be considered a security bug?
In response to requests, all users and all sessions were returned

### To reproduce

https://zitadel.com/docs/apis/resources/auth/auth-service-list-my-user-sessions

after multi test with diffrente user sessionToken it always return a const value 
it always return a fixed value and that was all session values

**Comment by srividyaj** [comment]
I agree this is a critical bug and this can lead to serious GDPR violation. Request to fix this

**Comment by doncicuto** [comment]
Hi, thank you for opening an issue. I'm not part of the team but I'm a frequent contributor to the project. In my opinion, any issue is welcomed to improve or find bugs for any project like Zitadel but please consider providing the more information as possible so it's easier to help you and so the team can initiate a bug triage.

Now IMHO I'd suggest you to rename the issue to something like 'Unexpected response for Get My User Sessions V1 API request' as in this case you're uncertain about the expected results of your tests requesting this endpoint. Seeing something like critical bug scared me a little bit :sweat_smile: 

Second, as I did in #8212 I'd recommend you again to use Discord or alternatively you can open a discussion on GitHub to ask for any help or doubt about the project. Zitadel has a great community. 

Now, my two cents. I've done some tests as I haven't used the auth/v1/users/me/sessions/_search endpoint before and I'd say that it works fine and maybe there's a misunderstanding on what this endpoint do. 

The endpoint docs say 'Returns a list of a user session for the user agent ' and indeed the source code for this endpoint decodes the access token and get's the user agent associated to that token and performs a query. So if you've tried with different tokens but they all have in common the UserAgent you'll get the same result. In my tests I've five sessions, three of then created from a React application and two of then created using the API. If I try to retrieve user sessions,  depending on the token used, I get two sessions or three, but not all the sessions so the UserAgent check is working fine and not leaking information.

Perhaps you thought that this endpoint was going to give you some information about the user session and you expect to get only one result to work with, but I think that in this case the endpoint's description may be somehow misleading for newcomers.

Maybe @adlerhurst or @livio-a can confirm if my answer is right and this is not a bug

Thanks!

**Comment by livio-a** [comment]
@AmirhoseinBrz @srividyaj we're looking into it
