### ISSUE TITLE
Metadata Storage

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#823]
## Idea
Sometimes it would be useful to store additional data with IAM Resources.
We could provide a key / value storage to our customers.

## Limitations

- [ ] Limits size to (n)kb

## Which resources might be relevant

- [x] Organisation
- [x] User 

## Possibel Scopes

- urn:zitadel:org:metadata
- urn:zitadel:user:metadata

**Comment by fforootd** [comment]
WIP here https://github.com/caos/zitadel/pull/2025

**Comment by hifabienne** [comment]
I will close this issue, because we do have the possibility to store org and user metadata. only thing that is missing is the frontend part for org metadata
