### ISSUE TITLE
Single idp callback for old and new implementation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#8236]
At the moment I do have two different idp callback urls, depending on the login ui I use (go hosted login, or session api).
To be able to easily change between the different logins without the need of additional documentation and confusion, we want to allow one idp callback for all implementations

## Acceptance Critiera
- [x] Existing idp callbacks is able to handle old and new implementation
(/login/externalidp/callback)

**Comment by quochuydev** [comment]
I really hope you guys update in conjunction with this issue, when I build a UI with session API, I only wanna show the public login domain, not the private zitadel domain. The devops team would never open only 1 router for idps callback URL.
https://github.com/zitadel/zitadel/issues/8032
