### ISSUE TITLE
[Bug]: cannot start any of the Passkeys registrations when authenticating on behalf of a service user

### ISSUE THREAD

**Issue by borisroman** [zitadel/zitadel#8243]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.55.1

### Database

PostgreSQL

### Describe the problem caused by this bug

Similar to https://github.com/zitadel/zitadel/issues/7463 and discussed in https://discord.com/channels/927474939156643850/1206634195607363676/1252249863467438120.

When implementing a custom UI one needs to provide a UI for setting up MFA. Within the context of a custom UI we are in server-side code authenticating on behalf of the service user for all of our custom UI actions as per the Integrate docs. However, when trying to start an Passkey registration for a user via any of the registration APIs (e.g. http://ZITADEL_URL/v2beta/users/:userId/passkeys) the following error is returned alongside a 403 Forbidden status:

```
{
    "code": 7,
    "message": "Request user not equal to authenticated user (AUTH-Bohd2)",
    "details": [
        {
            "@type": "type.googleapis.com/zitadel.v1.ErrorDetail",
            "id": "AUTH-Bohd2",
            "message": "Request user not equal to authenticated user"
        }
    ]
}
```

What I'm expecting to happen: The request succeeds as I'm a service user with admin permissions.

### To reproduce

Send a POST request to v2beta/users/:userId/passkeys with Bearer token belonging to an admin service user.

### Expected behavior

The request succeeds as I'm a service user with admin permissions.

**Comment by Pedro642001** [comment]
I dont know if your final user has an access token in this stage. however, you can use the authenticated user access token to realize this call, i had the same problem, and that way I solved it.

**Comment by stebenz** [comment]
Douplicate of #7944 , including comments which solve the problem.

I will clsoe this issue, please refer to the other issue for a solution.
