### ISSUE TITLE
Referencing scripts is broken

### ISSUE THREAD

**Issue by mffap** [zitadel/zitadel#8250]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

Before upgrading Docusaurus we could reference Github snippets. Those are now broken. Seems to affect some or all ```js reference code blocks. 

Examples: 
- https://zitadel.com/docs/apis/actions/code-examples
- https://zitadel.com/docs/guides/integrate/identity-providers/azure-ad-saml

**Comment by hifabienne** [comment]
the plugin we are using is not yet docusaurus v3 compatible.
There is one fork: https://github.com/christian-bromann/docusaurus-theme-github-codeblock
We need to figure out what works
