### ISSUE TITLE
[Bug]: Login redirection issue

### ISSUE THREAD

**Issue by rajubish** [zitadel/zitadel#8257]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.2

### Database

CockroachDB

### Describe the problem caused by this bug

We are facing an issue with the Zitadel login process that started occurring after the latest release update.

When a user clicks on login, it redirects to the Zitadel login page. After entering the email, password, and 2FA, it redirects back to the callback URL. However, the Zitadel session is not created, so it redirects back to the Zitadel login page. On the second attempt, after entering the email, it doesn't ask for the password and 2FA and redirects back successfully.

We are unable to identify the root cause of this issue. Can you please help determine the cause and provide a resolution as soon as possible?

### To reproduce

1. Browse portal and click on login
2. redirect to zitadel login and enter username, password and 2fa
3. redirect back to portal but again redirecting back to zitadel login
4. second attempt after entering username successfully login

### Screenshots

<img width="1670" alt="image" src="https://github.com/zitadel/zitadel/assets/74891056/ec5936d2-cdc6-4c5e-aa51-f79f7a3d4294">

### Operating System

Device: Ubuntu
Version 22.04

**Comment by hifabienne** [comment]
Hi @rajubish 
We made some fixes on version 54, can you upgrade to 2.54.6?
If the problem still exists can you tell us from which version you did the upgrade?
And maybe provide us a har file?

**Comment by rajubish** [comment]
Hi

Current version is v2.54.2 and upgraded from 2.50.


Thanks

**Comment by rajubish** [comment]
Any update?

**Comment by livio-a** [comment]
Did the update to 2.54.6 fix the issue? If not, could you please provide us a HAR file showing the entire flow.

**Comment by rajubish** [comment]
We will update the Zitadel version to 2.54.6 over the weekend and provide you with the status afterward.

**Comment by rajubish** [comment]
Hi @livio-a 

We have upgraded the Zitadel version from v2.54.2 to v2.54.6, but we are still facing the same issue. I have attached the HAR file for your reference.

Additionally, we attempted to upgrade to version 2.55.2, but encountered a problem where not all users were migrated. We have 18k users in the users12 table, but after the upgrade, only 5k users were migrated in to users13 table. After waiting for 2 hours, we reverted back to version 2.54.6.

Below are the error logs after the upgrade to version 2.55.2:

time="2024-07-13T03:37:32Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:413" error="ID=SQL-KyeAx Message=unable to filter events Parent=(timeout: context deadline exceeded)" projection=projections.users13time="2024-07-13T03:37:32Z" level=info msg="commit of read only transaction failed" caller="/home/runner/work/zitadel/zitadel/internal/database/database.go:51" error="sql: transaction has already been committed or rolled back"time="2024-07-13T03:37:32Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:129" error="timeout: context deadline exceeded"time="2024-07-13T03:37:32Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:413" error="ID=SQL-KyeAx Message=unable to filter events Parent=(timeout: context deadline exceeded)" projection=projections.users13time="2024-07-13T03:37:33Z" level=info msg="commit of read only transaction failed" caller="/home/runner/work/zitadel/zitadel/internal/database/database.go:51" error="sql: transaction has already been committed or rolled back"time="2024-07-13T03:37:33Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:129" error="timeout: context deadline exceeded"time="2024-07-13T03:37:33Z" level=info msg="process events failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:413" error="ID=SQL-KyeAx Message=unable to filter events Parent=(timeout: context deadline exceeded)" projection=projections.users13

[authprod.myconnectsecure.com.har.txt](https://github.com/user-attachments/files/16200957/authprod.myconnectsecure.com.har.txt)

**Comment by rajubish** [comment]
Any update?

**Comment by livio-a** [comment]
I checked the HAR file and could not find an issue. Can you check if your application properly stored the state and nonce.
Because that would explain a lot and i've seen issues like this in the past. Since the client (app) does not have the state or nonce it cannot handle the code exchange and (re)starts the auth flow.

**Comment by rajubish** [comment]
@livio-a 
Thanks for response.

I can see state and nonce is passing to authorize request, anywhere else need to check the application state and nonce?
It was working fine with the earlier 2.38 version, but after the upgrade, this issue started.
We have version 2.55.2 in our staging environment, and it’s working fine there.

**Comment by rajubish** [comment]
Also any update on
Additionally, we attempted to upgrade to version 2.55.2, but encountered a problem where not all users were migrated. We have 18k users in the users12 table, but after the upgrade, only 5k users were migrated in to users13 table. After waiting for 2 hours, we reverted back to version 2.54.6.

**Comment by rajubish** [comment]
Hi @livio-a 

We need you help to resolve this issue.

**Comment by rajubish** [comment]
Any update please?

**Comment by rajubish** [comment]
Could you please provide insights or suggestions on what might be causing this issue and how to resolve it?

**Comment by rajubish** [comment]
Any update?

**Comment by livio-a** [comment]
I just noticed that you start your flow on `https://configuration.myconnectsecure.com/api/getPartner` and the callback ends up on `https://portal.myconnectsecure.com/overview`, which might cause problem on your end handling the state / nonce because of the domain switch. Or do you handle that as well?

**Comment by rajubish** [comment]
@livio-a  Actual portal url is https://portal.myconnectsecure.com and it calls the api from ui and callback is https://portal.myconnectsecure.com/overview. the same behavior working in qa zitadel.

**Comment by livio-a** [comment]
> [@livio-a](https://github.com/livio-a) Actual portal url is https://portal.myconnectsecure.com and it calls the api from ui and callback is https://portal.myconnectsecure.com/overview. the same behavior working in qa zitadel.

what version of zitadel do you run on your qa environment?

**Comment by muhlemmer** [comment]
Probably not a zitadel bug if it works on another environment.
