### ISSUE TITLE
[Bug]: console fetches lots of data after login

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8272]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.56.0-rc.4

### Database

PostgreSQL

### Database Version

15

### Describe the problem caused by this bug

When an instance has many (700k+) organizations, login as IAM owner is fetching a lot of data. This results in high memory consumption on the backend and a long response time before the console is completely loaded.

In my case, when the console is initially loaded, the `zitadel.auth.v1.AuthService/ListMyProjectOrgs` endpoint takes more than 20s to return all data. The size of all data returned during the console load is around 151MiB.

The console only loads the data once and then seems to cache it. We should evaluate where the data is used and if we really need to fetch so much data.

### To reproduce

1. Import 700k organizations
2. Login as IAM owner to the console

The issue was reproduced on our QA environment and some zitadel engineers already have IAM rights to the affected instance, to reproduce the issue easier.

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/5411563/bcde8128-7b1e-4a2d-9774-dfc56ad3eacc)

### Expected behavior

Fetch only data that is required to render the current UI.

### Operating System

Backend: Google cloud run, QA environment
Browser: Chromium 126.0.6478.126 built on Debian 12.5, running on Debian 12.5

### Additional Context

Issue occurred after we optimized organization imports as part of the https://github.com/zitadel/zitadel/issues/7639 effort.

**Comment by peintnermax** [comment]
Closing this due to merged PRs #8273
