### ISSUE TITLE
Domain Handling

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#8279]
## Current Situation

ZITADEL currently selects the instance context based on a HTTP header (see order below) and checks it against the list of instance domains. Let's call it instance or API domain.
For any context based URL (e.g. OAuth, OIDC, SAML endpoints, links in emails, ...) the requested domain will be used. Let's call it the public domain.

**Example**
| Instances | Generated Domain | Custom Domain(s) |
| --- | --- | --- |
| Test | test-asjklr.zitadel.cloud | - |
| Prod | prod-f4gss.zitadel.cloud | auth.mydomain.com |

| Request | Instance | Public Domain / Issuer |
| --- | --- | --- |
| https://test-asjklr.zitadel.cloud/.well-known/openid-configuration | test instance | https://test-asjklr.zitadel.cloud |
| https://prod-f4gss.zitadel.cloud/.well-known/openid-configuration | prod instance | https://prod-f4gss.zitadel.cloud |
| https://auth.mydomain.com/.well-known/openid-configuration | prod instance | https://auth.mydomain.com |

This led to some confusion / issues in the past for self-hosters, as you would need to set up / configure ZITADEL with the domain you'll expose it.
Additionally, the new login UI will require proxy functionality, which requires an easy way to select the instance and also the public domain, which might differ.

### Current implementation
HTTP1:
- configured header (if not `host`)
- "origin":
  - forwarded
  - x-forwarded-*
  - host

GRPC:
- HTTP1 host (see above)
- configured header (authority by default)

OIDC:
- forwarded
- x-zitadel-forwarded
- host

## Proposal
First of all we should allow the selection of the instance context and public domain separately. A client / developer must be able to do so by using preconfigured headers. This allows to address different scenarios

#### (Self-Hosting) single instance
An admin wants to just start ZITADEL “out-of-the-box” and all traffic routed to the binary just needs to be handled as is:
Automatically select the only instance and use the Host header (as default) for the public domain.
In case of a (reverse) proxy, a configured public domain header must be sent by the proxy and handled by ZITADEL.

**Single tenant mode**
To prevent fallbacks in multi instance setups, a flag for the single instance / tenant must be activated.
#### Multi instance setup
ZITADEL needs to be aware of the instance context and therefore needs this information from either the Host header or a preconfigured (instance) header.
In case of a (reverse) proxy, it can either just be sent as Host header or any other header, which just needs to be configured in ZITADEL.
If the instance header is not sent in the request, we fallback to the Host header.
#### ZITADEL cloud
Works like any other multi instance setup, but there are probably more external setups possible as we cannot control the clients as much as you could in a self hosted setup.
Therefore we need to have an explicit instance header, e.g. X-Zitadel-Instance and not rely on any predefined (forwarded, x-forwarded, …) header.
### Allow setting public domain by header
Additionally to support the scenarios where a reverse proxy, e.g. login UI needs the ability to overwrite the public domain, we should allow so by an additional header. In case the header is not set by the request, we fallback to the instance header, resp. it’s default the Host header.

**Example**
| Request                                                      | X-ZITADEL-INSTANCE | X-ZITADEL-DOMAIN            | Instance       | Public Domain / Issuer               |
|--------------------------------------------------------------|--------------------|-----------------------------|----------------|--------------------------------------|
|  https://test-asjklr.zitadel.cloud/.well-known/openid-configuration | -                  | -                           |  test instance |  https://test-asjklr.zitadel.cloud   |
|  https://auth.mydomain.com/.well-known/openid-configuration  |  -                 | -                           |  prod instance |  https://auth.mydomain.com           |
|  https://prod-f4gss.zitadel.cloud/.well-known/openid-configuration | -                  | auth.mydomain.com           |  prod instance |  https://auth.mydomain.com           |
|  https://api.zitadel.cloud/.well-known/openid-configuration  | auth.mydomain.com  | -                           | prod instance  | https://auth.mydomain.com            |
|  https://api.zitadel.cloud/.well-known/openid-configuration  | auth.mydomain.com  | customer1.auth.mydomain.com |  prod instance |  https://customer1.auth.mydomain.com |

### Redirect URI
We need to clarify how to handle the redirect_uri check in cases of automatic domain handling / public domain overwrites.

**Acceptance criteria**

- [x] When calling ZITADEL, I can send a specified header, which is used as "public domain"
- [x] When calling ZITADEL, I can send a specified header, which is used as "instance domain"
- [x] The "public domain" is used for all public endpoints and mails (internally known as "origin" / requested domain)
- [x] The "public domain" is checked against a list of preconfigured domains
- [x] The "instance domain" is used to determine the instance context and therefore checked against verified instance domains (as is)
- [x] Authentication into Console using OIDC is possible on all instance and public domains
- [ ] When the "single-instance" mode is activated the "instance domain" will be ignored and the only instance will be used as instance context

**Comment by livio-a** [comment]
@fforootd please add / update if i missed anything
@peintnermax FYI

**Comment by fforootd** [comment]
Going to check it in a few minutes!

**Comment by fforootd** [comment]
Some small thoughts:

- We should make a multi-tenant toogle and default to single-tenant 
- I would default to x-zitadel-publicdomain to be more explicit for the header that carries what public domain we run (it should anyway be configurable)

The rest looks good to me!

**Comment by livio-a** [comment]
> Some small thoughts:
> 
> * We should make a multi-tenant toogle and default to single-tenant
> * I would default to x-zitadel-publicdomain to be more explicit for the header that carries what public domain we run (it should anyway be configurable)
> 
> The rest looks good to me!

About the toggle: Defaulting to single-tenant would certainly improve DevX when starting from scratch but would also break all existing systems 😏 --> V3? 😄

**Comment by buzzie-bee** [comment]
>We should make a multi-tenant toogle and default to single-tenant

This would be very helpful for our use case. We currently host zitadel and our applications on a single server via docker-compose and have hit numerous very hard to debug and fix issues with wrangling zitadel to use the correct instance.

We currently have yet another auth bug because the email server is using the docker address as the base url for generating email links rather than the configured EXTERNAL_DOMAIN. Enabling a toggle to put zitadel into a single instance mode should prevent issues like this and would drastically reduce the unnecessary DevX complexity when using zitadel for a single organisation / application.
