### ISSUE TITLE
[Bug]: UI layout issue in `Upload your Profile Picture`

### ISSUE THREAD

**Issue by MSDNicrosoft** [zitadel/zitadel#8284]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.56.0

### Database

PostgreSQL

### Database Version

16.3

### Describe the problem caused by this bug

The UI layout is broken in `Upload your Profile Picture`. Please see a screenshot followed.

### To reproduce

1. Navigate to `Edit Account`
2. Click profile picture

### Screenshots

![image](https://github.com/zitadel/zitadel/assets/69967436/78bc3dc1-bc0b-48dc-a510-38e459a9b049)

**Comment by doncicuto** [comment]
Hei @hifabienne this https://github.com/zitadel/zitadel/pull/8293 is just two lines to review

**Comment by doncicuto** [comment]
Thanks @MSDNicrosoft for opening the issue
