### ISSUE TITLE
Clarification needed: PASSWORD CHECK setting description

### ISSUE THREAD

**Issue by zzzz0317** [zitadel/zitadel#8298]
## Description
I've noticed potential discrepancies in the description of the PASSWORD CHECK setting in ZITADEL's default configuration, both in English and other languages.

The current English description states:
https://github.com/zitadel/zitadel/blob/d7c0ec282ae34773d682e60f79bc9723e8f4c9ec/console/src/assets/i18n/en.json#L232-L235
> Your users have to change their passwords in these periods.

However, based on my understanding, this setting should refer to re-authenticating (verifying) the password after a certain period, not necessarily changing it.

Additionally, I've observed that translations in other languages, such as Chinese and Japanese, may also be inaccurate due to this misunderstanding.

## Expected Behavior
The description should accurately reflect the functionality of the PASSWORD CHECK setting in all supported languages. If my understanding is correct, it should indicate that users need to re-verify their passwords after the specified period, not change them.

## Suggested Changes
1. If my interpretation is correct, a more accurate English description might be:
   > Users will be required to re-authenticate (verify their password) after this period.

2. Review and update translations in all supported languages to ensure consistency and accuracy. For example:
   - Chinese (中文): 
     Current (assumed): 您的用户必须在这些时期内更改他们的密码。
     Suggested: 用户需要在此期限后重新验证（确认）他们的密码。
   
   - Japanese (日本語):
     Current (assumed): ユーザーは、これらの期間中にパスワードを変更する必要があります。
     Suggested: ユーザーはこの期間後にパスワードを再認証（確認）する必要があります。

**Comment by hifabienne** [comment]
This has been solved, but we forgot to link the issue.
Will close it.
