### ISSUE TITLE
Invite User Link

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#8310]
As an administrator I want to be able to invite users to my application with the API V2, some user data I will already prefill, the user should add the authentication method itself (password, passkey, sso).

## Acceptance Criteria
- [x] Create user request is changed to have the possibility to not send an email / phone code, if the isVerified is false and sendCode, and returnCode are not sent, the user will not get an email / message
- [x] Request invite code is added as a new method
   - [x] I can choose if I want to get a code as return message or if ZITADEL should send the email
- [x] The method will send an email, your user has been invited to application xyz, please click the link below to accept the invite
- [x] The invite code is accepted on ~all methods which accept a code~ the VerifyInviteCode endpoint.
- [x] A new message type invite user is added
- [x] I am able to manage the message texts for the email
- [ ] Please test the following usecases:
   - [ ] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add a password, user email is verified and password set
   - [ ] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add a passworkey, user email is verified and passkey set
   - [ ] Given user is created with firstname, lastname, email, email not verified, the user will get an invite code and can add sso, user email is verified and sso linked

## Additional Notes
How to be able to verified email and auth method?
What if i don't need email but phone, in that case i would need to verifiy the phone instead of email, how do i know what to verify?

**Comment by mffap** [comment]
This feature will be great for creating user management functionality in apps. One thing we should consider is that I might add already a role to the user when I send out the invitation. That would allow the user to finish the onboarding, and then login directly and work as they are supposed to. Maybe this is already possible, but it would be nice to have the ability to set the roles also in the same request (like creating an org and adding the first user and their Manager permissions).

**Comment by livio-a** [comment]
As discussed with @hifabienne:
We'll focus on providing all the options through the v2 login. V1 must be at least be able to handle to create a user with password (like with init code).
> What if i don't need email but phone, in that case i would need to verifiy the phone instead of email, how do i know what to verify?
As of now: only allow email (for backwards compatibility with v1 login)
