### ISSUE TITLE
Update user schema on user

### ISSUE THREAD

**Issue by stebenz** [zitadel/zitadel#8313]
As a ZITADEL Administrator I want to be able to change the user schema a user belongs to, so that the information on the user is either checked for the new schema or new information can be added.

## Acceptance Criteria
- [ ] Feature is behind a feature flag
- [ ] **UpdateUser**: Adds an authenticator
  - [ ] Change schema with current user information
  - [ ] Change schema with changed user information
- [ ] With a schema change, the authenticators get checked as well, and removed if necessary 

### User Object
* **id**: unchangeble, unique identifier of the system
* **schema**: 
    * **type**: schema type of the user (e.g. human/machine)
    * **revision**: read only, revision of the schema the user was stored the last time (e.g. 4)
* **authenticators**: list of possibilites how a user can authenticate itself. there can be multiple authenticators of the same type
* **contact**: email and phone of the user if provided
* **state**: one of `Active`, `Inactive`, `Locked`, `Deleted`
* **data/profile/traits**: custom fields of a user based on the type (whats the best name for this?)

**Comment by hifabienne** [comment]
@eliobischof @stebenz can you estimate this issue?

**Comment by stebenz** [comment]
@hifabienne As it is right now we can close this issue, because the functionality is the same as in #7898, with the only difference that instead of the current schema, another existing schema is used for validation.

**Comment by hifabienne** [comment]
should i add that as an acceptance criteria to the other issue and close this one here?
