### ISSUE TITLE
Clarification regarding the Zitadel connection

### ISSUE THREAD

**Issue by Iyyammal** [zitadel/zitadel#8348]
I have question, in the documentation you have provided the examples of connecting the frontend with zitadel cloud, yes ofcourse we understood, but we what about the backend, Do we need to setup the zitadel connection for backend also. If yes why didn't provide the document. Please consider this as high priority as we are in need to implement the zitadel in our application

**Comment by hifabienne** [comment]
We do have one quickstart that shows you how to integrate the login ui with all details. For that we choose one framework to give the general overview.

But we also have more examples for frontend and backend for different languages and frameworks.
You can find different backend examples in the Get Started - Backend Section
<img width="295" alt="image" src="https://github.com/user-attachments/assets/7fe7f024-627b-4a10-86de-36dc883b6317">

For example go: https://zitadel.com/docs/examples/secure-api/go

**Comment by hifabienne** [comment]
I will close this issue as it is answered.
Feel free to reopen if you have more information to share
