### ISSUE TITLE
Automatic unlocking of self-locked-out users

### ISSUE THREAD

**Issue by ashep** [zitadel/zitadel#8360]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

There is a Zitadel functionality that allows the locking of a user account automatically after several unsuccessful authentication attempts. The problem is when a user locks themselves in such a way, it would be impossible to authenticate anymore without the help from an administrator.

### Describe your ideal solution

It would be nice to have a feature allowing such self-locked-out users to be unlocked automatically after some configurable period of time, without a manual account manager intervention.

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by JayPe69** [comment]
#6502

**Comment by hifabienne** [comment]
thanks @JayPe69 for the notification of the duplicate.
In that case I will close this issue here, to avoid duplicates.
