### ISSUE TITLE
[Bug]: Userinfo endpoint failing

### ISSUE THREAD

**Issue by sschoeb** [zitadel/zitadel#8362]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

We request info from the userinfo endpoint but somehow sometimes get a 401 returned even when the token is still valid.

I discussed this issue before with @muhlemmer and we already could fix an issue on our side (setting the token lifetime to 36 hours was a bad idea, this we changed to 24hours). But we still from time to time see this problem. 

Given the token represented by the following screenshot:
![image](https://github.com/user-attachments/assets/6124fd16-e28a-4b02-a868-c19df2b1c6af)

You can see, that the token is valid up to the 1. July 14:26. 

Out request we did to the userinfo-endpoint failed at 2024-07-01 09:28:32.932 with a 401. So at this time the token should still have been valid. 

Currently we have the following feature settings:
OIDC Legacy Introspection: Deactivated
OIDC Trigger Introspectionprojection: Activated

Is there any other setting we should think about or is here something going wrong? We also mostly experience this when the lifetime is close to the end of the token.

Maybe related to:
- https://github.com/zitadel/zitadel/issues/8153 
- https://github.com/zitadel/zitadel/issues/7809

### To reproduce

Hard to reproduce, but we get it from time to time when our users use our app. 

### Expected behavior

When we get along with a valid token, we want to have a valid response :)

**Comment by muhlemmer** [comment]
@sschoeb I've prepared the two above PRs that will hopefully enable us to debug this issue. I will need to discuss internally if the proposal is ok.

As it is a new feature flag, it I don't imagine this getting back-ported. I hope this will get into the future v2.60 release and we can proceed with getting to the core of this issue.

**Comment by livio-a** [comment]
@sschoeb we just found some more logs and noticed that there was a token refresh at 2024-07-01 07:28:32.791960 UTC. So at during the userinfo request at 2024-07-01T07:28:32.926 UTC the token with JTI (V2_273895395543847877-at_273895395543913413) was not valid anymore.
Is it possible that the new access_token was not properly exchanged in your application or are there any processes running in parallel which access to the access_token?

**Comment by sschoeb** [comment]
@livio-a thanks for checking this, that could definitely be the root issue. I'm currently in vacation but will check this as soon as I'm back. Will post an update.

**Comment by muhlemmer** [comment]
Will close it for the moment. Feel free to reach out / reopen if something else is the problem.
