### ISSUE TITLE
[Bug]: ListSMTPConfigs returns state as int

### ISSUE THREAD

**Issue by james-emerton** [zitadel/zitadel#8377]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.57.0

### Database

PostgreSQL

### Database Version

14.11

### Describe the problem caused by this bug

When accessing the `/admin/v1/smtp/_search` endpoint via REST, the type of `result[n].state` is an integer rather than the documented enum values:

```
{'details': {'totalResult': '1',
              'viewTimestamp': '2024-08-01T23:25:53.639051Z'},
 'result': [{'details': {'changeDate': '2024-07-26T22:01:34.194026Z',
                         'creationDate': '2024-07-26T22:01:34.194026Z',
                         'resourceOwner': '277715149035405319',
                         'sequence': '115'},
             'host': '9d617355aa5a:25',
             'id': '277722138608140295',
             'senderAddress': 'no-reply@example.com',
             'senderName': 'Some Name',
             'state': 3}
}
```

### To reproduce

 1. Make an authenticated request to `/admin/v1/smtp/_search`
 2. Observe that the `state` field contains an integer

### Expected behavior

`state` field should contain a string corresponding to one of the enum values

**Comment by stebenz** [comment]
I just checked and for me both in GRPC and REST the Enum is correctly used.
![Image](https://github.com/user-attachments/assets/6e772a22-979d-4f22-b5cf-2a9636566113)

I will close this issue for now, if the problem still persists please don't hesitate to reopen it.
