### ISSUE TITLE
[Bug]: Zitadel Console timeout Errors.OIDCSession.Token.Expired

### ISSUE THREAD

**Issue by JayPe69** [zitadel/zitadel#8392]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.56.0

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

When settings the OIDC Lifetime like these ones :

{
    "accessTokenLifetime": "15s",
    "idTokenLifetime": "15s",
    "refreshTokenIdleExpiration": "30s",
    "refreshTokenExpiration": "86400s"
}

Then using the zitadel console to navigate in it you'll get some timeout Errors.OIDCSession.Token.Expired

https://discordapp.com/channels/927474939156643850/1260610461829828821

### To reproduce

timeout Errors.OIDCSession.Token.Expired

https://discordapp.com/channels/927474939156643850/1260610461829828821

**Comment by fforootd** [comment]
I promised to tag @peintnermax since it looks like an odd behavior from console.

**Comment by danielloader** [comment]
Can confirm it happens to me too on the cloud offering.

**Comment by peintnermax** [comment]
running requests with an expired token results in a 
```
grpc-message: Errors.OIDCSession.Token.Expired (QUERY-SAF3rf)
grpc-status: 7
```
this should be handled with a `grpc-status: 16` IMHO @livio-a @muhlemmer

**Comment by citos88** [comment]
When do you plan to release this bugfix? :)
