### ISSUE TITLE
[Bug]: all of the metadata is always included in the token, despite "User Info inside ID Token" being set to off

### ISSUE THREAD

**Issue by dimaip** [zitadel/zitadel#8435]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

Docer image `e5e4e202bd6e`

### Database

CockroachDB

### Database Version

Not relevant

### Describe the problem caused by this bug

All the metadata is always included in the authorization token, despite "User Info inside ID Token" being OFF.
It causes huge problems for me, as I often get header too long exceptions from my api, and in general it unnecessarily bloats the requests.
I have A LOT of metadta on my users, and I don't want it to be returned on the token.

Please help, it totally blocks me from using Zitadel, and I've already gone a long way!

### To reproduce

1. put some metadata on your user
2. authorise and check the bearer token contents.

### Screenshots

<img width="311" alt="image" src="https://github.com/user-attachments/assets/04cea097-a618-446b-8039-4785f2c27bb5">

<img width="702" alt="image" src="https://github.com/user-attachments/assets/c1a7e599-53c6-4c77-8f2d-a6938a8e3d70">

<img width="703" alt="image" src="https://github.com/user-attachments/assets/de029472-0680-4133-96eb-781b94ec329b">

### Expected behavior

We should either add a new setting like "User Metadata inside ID Token", or just make it work based on "User Info inside ID Token".

**Comment by hifabienne** [comment]
do you send the following scope in the auth request: urn:zitadel:iam:user:metadata ?

**Comment by dimaip** [comment]
OMG I do!
I had it from my initial implementation and forgot to remove it!
Thanks so much for the hint!
