### ISSUE TITLE
[Bug]: API for Listing identity provider links of user does not work

### ISSUE THREAD

**Issue by paustint** [zitadel/zitadel#8451]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.58.2

### Database

None

### Describe the problem caused by this bug

The API for listing a list of identities for a user returns an invalid response.

Thread: https://discord.com/channels/927474939156643850/1274180886367178824/1274180886367178824

https://zitadel.com/docs/apis/resources/user_service_v2/user-service-list-idp-links
And the bug is also present in [V1](https://zitadel.com/docs/apis/resources/auth/auth-service-list-my-linked-id-ps) api `/auth/v1/users/me/idps/_search`

1. My service user did not have permissions set up initially, and the API did not return an authz error
2. I have tried both self-hosted and cloud, both with the same results

```bash
curl -L 'https://xxx.zitadel.cloud/v2/users/281028630757863396/links/_search' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer XXX' \
-d '{
  "query": {
    "offset": "0",
    "limit": 100,
    "asc": true
  }
}'
```

response
Note: the local hosted version returns a valid date
```
HTTP/1.1 200 OK
x-cloud-trace-context: b7b7dd72498c117118a70c6bb9d71eb7/10822333412339995277
traceparent: 00-b7b7dd72498c117118a70c6bb9d71eb7-9630a6e63b5dd28d-00
```
```json
{
  "details": {
    "timestamp": "0001-01-01T00:00:00Z"
  }
}
```

### To reproduce

1. Create a service user with a PAT and correct permissions
2. Call curl example as shown on API docs page
3. Notice API returns success status code and an invalid response

### Expected behavior

API returns the response as described in the documentation

### Operating System

N/A

**Comment by hifabienne** [comment]
hei @paustint 
thanks for creating the issue, we will have a look at it
