### ISSUE TITLE
[Bug]: External OIDC providers that do not support `prompt=select_account` cannot be used

### ISSUE THREAD

**Issue by yoav-lavi** [zitadel/zitadel#8462]
### Preflight Checklist

- [ ] I could not find a solution in the documentation, the existing issues or discussions (https://github.com/zitadel/zitadel/issues/6599 exists but I was asked to open an issue in Discord)
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.59.0

### Database

PostgreSQL

### Describe the problem caused by this bug

External OIDC providers that don't support `prompt=select_account` cannot be used unless they have a bespoke implementation (like GitLab)

### To reproduce

Add a new external OIDC provider, try to connect with a Ping OIDC app. When signing in Ping returns `error=invalid_request&error_description=Invalid%20value%20for%20the%20prompt%20parameter:%20select_account` as it does not support `select_account` (https://support.pingidentity.com/s/article/OpenID-Connect-Prompt-Query-parameter)

### Expected behavior

A possible solution would be being able to select the prompt type for the provider

### Additional Context

Related implementation:
https://github.com/zitadel/zitadel/blob/5fd2061770c9e2e02c64fa64111d78c2b915c58b/internal/idp/providers/oidc/oidc.go#L75

GitLab provider custom fix:
https://github.com/zitadel/zitadel/blob/5fd2061770c9e2e02c64fa64111d78c2b915c58b/internal/idp/providers/gitlab/gitlab.go#L36

Prior discussion on Discord: 
https://discord.com/channels/927474939156643850/1275025729951760438/1275127674662027334

Also discussed here:
https://gitlab.com/gitlab-org/gitlab/-/issues/377368

**Comment by yoav-lavi** [comment]
See also https://github.com/zitadel/zitadel/issues/6599

**Comment by yoav-lavi** [comment]
An interim quick solution could be a special case for Ping in the current implementation
It's not a long term solution but it would unblock the service for everyone while a configuration is added

**Comment by hifabienne** [comment]
We already have an issue for this problem created here: https://github.com/zitadel/zitadel/issues/6599
To avoid duplicates, I close the issue here.
Please subscribe to the other issue, and upvote there.
