### ISSUE TITLE
[Bug]: User still able to login despite the Project is deactivated

### ISSUE THREAD

**Issue by gr4n73** [zitadel/zitadel#8478]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Database

PostgreSQL

### Describe the problem caused by this bug

When a project is deactivated, users are still able to log in through OpenID Connect. This behavior is unexpected as the system should prevent users from logging in once the project is no longer active.

### Steps to Reproduce
- Deactivate a project within the application.
- Attempt to log in as a user associated with the deactivated project using OpenID Connect.
- Observe that the login is successful despite the project being deactivated.

### Expected behavior

Users should not be able to log in through OpenID Connect if the project is deactivated. The system should return an error message indicating that the project is inactive.

### Relevant Configuration

Review the logic that handles project status during the authentication process.
Implement a check to ensure the project is active before allowing user login.

**Comment by gr4n73** [comment]
Hi, is it possible to convert this to security issue?

**Comment by muhlemmer** [comment]
> Hi, is it possible to convert this to security issue?

We are already working on a fix. Next time, when reporting security issue please follow the [security policy](https://github.com/zitadel/zitadel?tab=security-ov-file#readme), which is published in the root of this project.

**Comment by livio-a** [comment]
fixed with https://github.com/zitadel/zitadel/pull/8630
