### ISSUE TITLE
[Bug]: the instance becomes inoperable when /oauth/v2/introspection is called frequently

### ISSUE THREAD

**Issue by sp132** [zitadel/zitadel#8479]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.54.8

### Database

CockroachDB

### Describe the problem caused by this bug

It looks like event store can't keep up when introspection endpoint starts to receive a bit of traffic.

- I see a lot of `could not push event "project.application.api.secret.check.succeeded" ID=V3-5jU5z Message=Errors.Internal Parent=(timeout: context deadline exceeded)` in logs
- valid tokens are rejected `
{"time":"2024-08-20T18:44:24.879477677Z","level":"WARN","msg":"request error","oidc_error":{"parent":"ID=OIDC-Eib8e Message=token is not valid or has expired Parent=(issuer does not match: Expected: https://<DomainB>, got: <DomainA>)","description":"access token invalid","type":"access_denied"},"status_code":401}` where DomainA is a primary domain defined in the configuration file and DomainB is an additional domain added via system api.
- login via session API os broken - `ID=QUERY-Thee9 Message=Errors.AuthRequest.NotExisting Parent=(sql: no rows in result set)`
- latency is increased massively 

![image](https://github.com/user-attachments/assets/d995fcd6-6bbd-4a26-94ae-6e87eb2714af)

There are three instances of zitadel colocated with cockroachdb instances on three different 16c/32GB hosts. Neither crdb nor zitadel was resource-starved.

### To reproduce

1. Create 25 users
2. Create an application with `Bearer` token
3. Obtain 25 tokens
4. Once a minute issue an introspection request for each token

### Expected behavior

ZITADEL can keep up with any number of introspection requests as long as it's not resource-starved

**Comment by muhlemmer** [comment]
Probably a confirmation of https://github.com/zitadel/zitadel/issues/8430#issuecomment-2286965402. @fforootd

**Comment by fforootd** [comment]
> Probably a confirmation of [#8430 (comment)](https://github.com/zitadel/zitadel/issues/8430#issuecomment-2286965402). @fforootd

Hm yeah that could well be related, lets fix this and check if it gets better.

**Comment by sp132** [comment]
@muhlemmer thanks for the fix!

Will it be back-ported to 2.54.x? I'm wondering what's the policy here

**Comment by muhlemmer** [comment]
Can we backport https://github.com/zitadel/zitadel/pull/8481 @livio-a?

**Comment by sp132** [comment]
Folks, any updates? 

I'd like to check if this fix helped, but I would like to avoid an upgrade from 2.54 to 2.60 if the fix can be easily back-ported.

**Comment by livio-a** [comment]
Sorry missed that... need to check and will do so tomorrow

**Comment by livio-a** [comment]
The fix is backported to 2.54.9

**Comment by sp132** [comment]
Thank you so much!

**Comment by livio-a** [comment]
will do the backports to other version in the coming days

**Comment by sp132** [comment]
I'm glad to report that fix has helped tremendously. There are no more errors in logs and performance seems to be unaffected by the number of introspection requests.

Really appreciate it, thanks.

![image](https://github.com/user-attachments/assets/5de57ebe-6d92-4c85-83a1-2738b73f7356)
