### ISSUE TITLE
OIDC: sid claim for id_tokens created through login UI

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#8499]
id_tokens issued for auth requests created through the login UI currently do not provide a `sid` claim.
This is due to the fact that (SSO) sessions for the login UI do not have one and are only computed by the userAgent(ID), the user(ID) and the authentication checks of the latter.

This prevents client to track sessions and terminate specific session on the end_session_endpoint.

## Acceptance criteria
- [x] `id` column to the `auth.user_sessions` table is added
- [x] `id` is set whenever a session is added or updated to active
- [x] the id is set as `sid` claim in the id_token

**Comment by hiddewie** [comment]
I created a followup feature request for the sid claim in impersonated ID tokens: https://github.com/zitadel/zitadel/issues/11064
