### ISSUE TITLE
Required request parameters of Code Exchange for authorization method none (PKCE)

### ISSUE THREAD

**Issue by alfa-alex** [zitadel/zitadel#8506]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

For the authorization method "none (PKCE)", the [Code Exchange endpoint](https://zitadel.com/docs/apis/openidoauth/endpoints#authorization-code-grant-code-exchange) has the following "required request parameters" according to [the docs](https://zitadel.com/docs/apis/openidoauth/endpoints#required-request-parameters-1):
- `code`
- `grant_type`
- `redirect_uri`
- `code_verifier`

However, when passing only these four, ZITADEL returns a `400` error and logs: `level=WARN msg="request error" oidc_error.description="client_id or client_assertion must be provided" oidc_error.type=invalid_request status_code=400`.

As far as I can see, this boils down to [this line of code](https://github.com/zitadel/oidc/blob/52e8b651d36e638d462a00162af7fab16cb74734/pkg/op/server_http.go#L194) in the `OIDC` module where either a `client_id` or a `client_assertion` is required.

When passing a correct `client_id`, the call succeeds. Could it be that the docs are missing this detail?

**Comment by muhlemmer** [comment]
@alfa-alex, yes you are right. This should be in the docs under the `(code) PKCE` tab. Do you want to send a PR?

**Comment by alfa-alex** [comment]
> @alfa-alex, yes you are right. This should be in the docs under the `(code) PKCE` tab. Do you want to send a PR?

Thank you for your response! I just did in https://github.com/zitadel/zitadel/pull/8709.
