### ISSUE TITLE
Actions v3 in Console

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#8513]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I can't manage Action v3 targets and executions in the Console

### Describe your ideal solution

I can manage Action v3 targets and executions in the Console

### Environment

Self-hosted

**Comment by hifabienne** [comment]
there is already an issue for that: https://github.com/zitadel/zitadel/issues/7248
i will close this to avoid duplicates
