### ISSUE TITLE
[Bug]: domain suffix check does not handle org deletion

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#8514]
A customer reported, that they deleted an organization, which had a domain assigned.
If the later on try to create a user in another org (no suffix enabled) with that domain as suffix of the user they will receive the following error: `Domain is already reserved and cannot be used (COMMAND-SFd21) error`

At first glance it looks like the removed org event is not treated when checking to which organization the suffix belongs to.

As a workaround the domain can be assigned to the corresponding organization (and even deleted again), which will prevent the error.

**Comment by stebenz** [comment]
Checked the logic, and yes this is the case, the OrgDomainVerifiedWriteModel does only process OrgDomainVerifiedEvent and OrgDomainRemovedEvent.

Problem here is that we only have the domain to query the respective events, it's anyway not really performant as you have to check if the domain of the events is equal and discard a lot of events if there are a lot of events of the combination organizations and domains.

I created a PR with the fix, not quite sure about the performance and the ImprovedPerformance part.
