### ISSUE TITLE
[Bug]: Deactivate user grant not working properly

### ISSUE THREAD

**Issue by n84ck** [zitadel/zitadel#8521]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.59.0

### Database

PostgreSQL

### Describe the problem caused by this bug

The user's grant still appears as active in the queries, and it also remains in the token (roles). Moreover, the deactivation works partially, as the second attempt results in an error indicating that the grant is not active.

### To reproduce

1. Add user grant
2. Deactivate user grant
3. Get user grant (The state is still active.)
4. Deactivate again.

### Screenshots

![image](https://github.com/user-attachments/assets/62d81995-cb19-4f0c-bb36-65b5753e106e)
![image](https://github.com/user-attachments/assets/f2000418-1c6d-4b82-9015-947b9b5a352e)
![image](https://github.com/user-attachments/assets/75eae568-42b9-4a50-9a7b-6bac348465af)
![image](https://github.com/user-attachments/assets/0eecbdeb-cc51-458b-83b1-21d5853c359f)
![image](https://github.com/user-attachments/assets/5633f395-4550-461d-9984-ec58bc10a1b8)
![image](https://github.com/user-attachments/assets/243dd5ae-028b-4c55-bf31-f18cb73dbc0b)

### Expected behavior

The user grant is deactivated, status properly returned and the deactivated roles are not included in the tokens when requested

**Comment by livio-a** [comment]
fixed by https://github.com/zitadel/zitadel/pull/8634
