### ISSUE TITLE
Update `defaults.yaml`

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#8531]
The current `defaults.yaml` includes escaped characters which are no longer rendered as valid html.
The configuration file should have updated values for message texts such that html can be rendered accordingly

**Comment by shubhamsugara22** [comment]
@hifabienne looks a good first issue 
Would like to start working on it

**Comment by hifabienne** [comment]
@shubhamsugara22 thanks great to hear that.
I assigned you to the issue
