### ISSUE TITLE
[Bug]: Failed passwords count indefinitely for account lockout

### ISSUE THREAD

**Issue by jnedfde** [zitadel/zitadel#8546]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.53.9

### Database

PostgreSQL

### Database Version

16.3

### Describe the problem caused by this bug

A user can fail their login n-1 times one time and weeks or months later (with successful logins in between) just one time and still get locked out.

### To reproduce

1. Set the lockout policy to number n
2. Fail password logins n-1 times
3. Successfully log in one time
4. Fail password login again
5. Youre locked out of your account

### Expected behavior

I, and my users, expect that the policy resets after a successful login so an unssucessful login from months ago does not affect your current situation.

**Comment by hifabienne** [comment]
We tested this on version v2.60, and we couldn't reproduce.
Tested the following:
- lockout set to 3 times
- entered password wrong 2 times
- entered password correctly
- entered password wrong 2 times
--> didn't lock

- entered password wrong 3 times
- on 4 time, error message user already locked

Can you send a screen recording?
Can you also send a screenshot of the event list in the console, of that user?
please also verify, that the policy of the organzation of the user is set correctly.

**Comment by jnedfde** [comment]
Hey,

we just updated to v2.54.8 (the latest stable version) and the bug seems to be fixed there.

Thanks for  the help!
