### ISSUE TITLE
[Bug]: Integration problem with jira and portainer

### ISSUE THREAD

**Issue by SajjadManafi** [zitadel/zitadel#8577]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.59.2

### Database

PostgreSQL

### Database Version

v16

### Describe the problem caused by this bug

Hi
I tried to integrate jira with zitadel
And one of the fields that jira wants is groups, which zitadel doesn't send in claims.
So I get this error in Jira:
```
Received no groups claim in OIDC response, the group mapping may be incorrect.
```
I even tried to send this claim in a custom way with actions, but the problem was still not solved.
```
function addClaim(ctx, api) {
  api.v1.claims.setClaim('group', 'some-group-name')
}
```

Then I tried to merge portainer with zitadel.
And as it is clear from the screenshots, there is probably a problem in portainer at the stage of getting userinfo.

### To reproduce

Try to integrate the latest jira version with zitadel

### Screenshots

![Screenshot from 2024-09-07 13-19-32](https://github.com/user-attachments/assets/06802b42-e94e-4568-8ca0-af7b1922aa21)
![Screenshot from 2024-09-09 14-32-24](https://github.com/user-attachments/assets/e273f3cc-42f7-4e5a-b227-71e8e12f17c9)
![Screenshot from 2024-09-09 14-33-23](https://github.com/user-attachments/assets/e0abf291-72f0-4d50-9a8a-8027d97edbc1)

**Comment by hifabienne** [comment]
Hi @SajjadManafi 
After adding the ZITADEL custom action, with the roles, what was the problem?
can you verify that the claim you added through the action did exist in the token?

**Comment by SajjadManafi** [comment]
How can i find and check the token?
Jira does not put the token in the log.
Also, I could not find anything with the networks tab of the browser.
But for sure, now the groups will be sent in the same type that I entered them, because Jira's error has changed
I just don't know what type it should be to accept it

**Comment by livio-a** [comment]
I guess JIRA does the mapping on either Userinfo endpoint or directly on the id_token.
So you probably configured the action on the `Pre Userinfo Creation` trigger, correct?
You could also sign in to the ZITADEL Console and check the id_token (in the session storage of your browser)

**Comment by hifabienne** [comment]
Great to hear and thanks for the feedback.
