### ISSUE TITLE
[Bug]: JWT Profile Access Token is missing `sub`

### ISSUE THREAD

**Issue by maennchen** [zitadel/zitadel#8591]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

When requesting a JWT Profile access token with the `urn:zitadel:iam:org:project:id:[PROJECT_ID]:aud profile` scope, it should contain a `sub` field. This worked fine ~5 months ago when I last ran the CI of one of my projects. Now it is missing.

### To reproduce

1. Create JWT Profile Account
2. Exchange with access token (set scope to include `profile`)
3. Check access token claims

### Expected behavior

Contains `sub` claim

### Additional Context

Example token with issue:

```
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI4NDM1NjMzOTEyMjA4NTA3MCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2VybGVmLXRlc3QtdzRhOHoyLnppdGFkZWwuY2xvdWQiLCJhdWQiOlsiMjMxNDAyODMwOTM2Nzg5NDE1Il0sImV4cCI6MTcyNjAzODI3NywiaWF0IjoxNzI1OTk1MDc3LCJuYmYiOjE3MjU5OTUwNzcsImp0aSI6IlYyXzI4NDM3MjI2Mjg5NzkwMzk2OC1hdF8yODQzNzIyNjI4OTc5Njk1MDQifQ.rPlH0iZ5y8jhCUuVDIQ65sqgH6KXHrbbuMbn5OqyqNdBbgDXjg8Cq3_uycc7h9vxv8QCFIP6eI_SqhyqCfbMq2HqAtbebGkTy23IaxZuqHNIH4_eI5gbi-qdBdPgPlyPiD5X3vIDrsm6QJnjdgIAkRs86jieMUgUk92iw-8hI1HMXGPENeF37bQLo75A77tABVAbSofMniDuX1dyhIaK91QX08CScirVedjmp16ixZDIcu2sXkjfZ1CCbT5UfTxekF4-0z4NxN6nRLCetH819kVmve0KNXPgBPi2nx6I8SETZ2SD2KeYgRnvK5-V6RUEdSp0CTTa5GSn55Yfza3MNg
```

This token has been leaked on purpose. The connected JWT Profile credentials are part of a public test suite and do not secure anything.

 * Test: https://github.com/erlef/oidcc_plug/blob/ci/test/oidcc/plug/validate_jwt_token_test.exs#L164-L206
 * CI Output: https://github.com/erlef/oidcc_plug/actions/runs/10798920140/job/29953498821#step:7:58

**Comment by maennchen** [comment]
@muhlemmer Thanks for checking the issue. I can't see any difference so far. Has this been rolled out?

**Comment by pspurlock** [comment]
@muhlemmer This is not working for me either when using device code auth. No sub is returned.
