### ISSUE TITLE
[Bug]: dark mode theme logo not correct

### ISSUE THREAD

**Issue by rajubish** [zitadel/zitadel#8659]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.54.10

### Database

CockroachDB

### Describe the problem caused by this bug

Hi

On dark mode initial page log it's not rendering the correct logo. It seems this issue is fixed with https://github.com/zitadel/zitadel/pull/8355
But it's available with 2.57 and 2.59 version only.
Is it possible to get this fixed with version 2.54 please.

Thanks

### To reproduce

On dark mode initial page log it's not rendering the correct logo

**Comment by rajubish** [comment]
Could you please provide an update on this issue? We are looking forward to any progress or resolution.

**Comment by hifabienne** [comment]
As this is not a critical bug, we will not backport this fix, and recommend you to upgrade to a newer version.
I will close this issue as it is already closed.

**Comment by rajubish** [comment]
Hi @hifabienne ,

I attempted to update Zitadel, but the process got stuck. I've raised a ticket on GitHub regarding the issue: https://github.com/zitadel/zitadel/issues/8390.

In the meantime, could you please provide a fix for the current version? Alternatively, any guidance on how to resolve the upgrade issue would be greatly appreciated.

Thanks for your support!

**Comment by rajubish** [comment]
Updated the latest zitadel version 2.63 and now showing both logo.

![Image](https://github.com/user-attachments/assets/4e983b45-8826-4c5d-b52e-5e596c8a083d)

**Comment by rajubish** [comment]
Any update on this?

**Comment by livio-a** [comment]
@rajubish based on the discussion in https://github.com/zitadel/zitadel/pull/8834, I assume it's only a cache issue.
Can you clear the cache and check if it works?

**Comment by rajubish** [comment]
Hi @livio-a ,

After trying all possible solutions, the issue remains unresolved. Therefore, I have raised a ticket for further assistance.

Raju

**Comment by livio-a** [comment]
Can you please provide me a HAR file?
