### ISSUE TITLE
[Bug]: Service user receives "could not read projectid by clientid (AUTH-GHpw2)" error

### ISSUE THREAD

**Issue by benr77** [zitadel/zitadel#8676]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.62.1

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

Since sometime last week, I cannot create users via the API. Using v2.62.1 now, but upgraded with the latest releases a couple of times. 

My API request can authenticate and get a token successfully, but when I try to create a user, using either the v1 or the v2 endpoint, I get the following error:

```
could not read projectid by clientid (AUTH-GHpw2)
```

My code has not changed so I'm assuming this is related to the latest releases of Zitadel.

### To reproduce

1. Authenticate with the API and obtain a token
2. Use the token to hit an API endpoint, e.g. GetUserById
3. Receive the error message

**Comment by benr77** [comment]
From user Dionysussg on Discord:

I was facing the same issue but with terraform and created a Github issue in the terraform provider repository.
I downgraded to Zitadel version v2.61.1 which works.
https://github.com/zitadel/terraform-provider-zitadel/issues/199

**Comment by benr77** [comment]
I have also just switched my authentication method from client credentials to JWT and I am seeing the same error.

Another user has stated that authenticating with PAT is working, but I have not tried this yet.

**Comment by PurseChicken** [comment]
We also have this issue with any of the v2.62.x versions. Its a non-issue in any of the v2.61.x versions.

**Comment by fforootd** [comment]
Just as added context on discord we have multiple cases raised about this:

- https://discord.com/channels/927474939156643850/1288921816919707707/1288921816919707707
- https://discord.com/channels/927474939156643850/1288743963414495293/1288743963414495293
- https://discord.com/channels/927474939156643850/1286275111745359912/1286275111745359912

**Comment by danielloader** [comment]
This has now taken out production for me via my Zitadel Cloud Instance being updated to v2.62.3 and having no control to downgrade it. 

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/0125176e-af0d-43f3-bea0-18e03355fbe6">

**Comment by reskume** [comment]
This issue also hits us hard now. Production is severely impacted to the point of uselessness. We are on a managed ZITADEL cloud instance with pro plan.

**Comment by benr77** [comment]
If you can switch to authenticating with a personal access token it will work. This problem only affects authenticating with client credentials or JWT. I have had to switch my app to use a PAT whilst this issue is resolved. I know it's less secure but at least you can continue with full functionality for a while.

**Comment by reskume** [comment]
We heavily rely on JWT for our services. But issue seems to be fixed for some of us now - according to discord chat.

**Comment by benr77** [comment]
OK. I'm using a self-hosted install. Do you know which release the issue has been solved in? I've not seen it in any release notes as far as I can tell?

**Comment by hifabienne** [comment]
We rolledback to 2.60.3 now on zitadel cloud

**Comment by livio-a** [comment]
The fix is released on [v2.62.4](https://github.com/zitadel/zitadel/releases/tag/v2.62.4) and [v2.63.1](https://github.com/zitadel/zitadel/releases/tag/v2.63.1)
