### ISSUE TITLE
[Bug]: UpdateHumanUser not working on HTTP v2 api

### ISSUE THREAD

**Issue by mzaniolo** [zitadel/zitadel#8686]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.61.0

### Database

PostgreSQL

### Describe the problem caused by this bug

I tried to update a human user using the endpoint described by [docs](https://zitadel.com/docs/apis/resources/user_service_v2/user-service-update-human-user) and it didn't work. I got a 200 response but when I checked the user's information wasn't change. I tried to update the user last name. I also checked on the UI and the value wasn't changed. I was able to change it on the UI

Here is a wireshark capture of the requests and the logs from zitadel
[update_user.pcapng](https://github.com/user-attachments/files/17144977/update_user.pcapng.zip)
[logs.txt](https://github.com/user-attachments/files/17145000/logs.txt)

### To reproduce

Using the http v2 api:

1 - Get a token using a service account
2 - Create a new user
3 -  Get the created user using get_user_by_id
4 - Change the family name of the user using update_human_user
5 - Get user using get_user_by_id

**Comment by stebenz** [comment]
Fixed with PR #8635
