### ISSUE TITLE
[Bug]: Unable to login using only the username when "Add organization domain as suffix to loginnames" is enabled

### ISSUE THREAD

**Issue by sahar290** [zitadel/zitadel#8701]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.60.0

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

I encountered a problem when trying to authenticate users with the **same username** in two different organizations (s-organization1 and s-organization2) within the same Zitadel instance.

### To reproduce

> First, install Zitadel locally using Docker Compose by following this [documentation](https://zitadel.com/docs/self-hosting/deploy/compose).

1. In organizations settings, enable the "Add organization domain as suffix to loginnames" option under "Domain Settings" for both organizations.
2. Create two users with the **same login name** (username: sahar) in two separate organizations (s-organization1 and s-organization2).
3. Create projects and applications for both organizations (I used the WEB type).
4. Specify the following URL : http://localhost:8080/ui/console/auth/callback as both the redirect URI and post-logout redirect URI.
5. Call /authorize endpoint (to go to UI Zitadel login page) with following parameters:
response_type: Authorization Code

- **redirect_uri**: http://localhost:8080/ui/console/auth/callback

- **client_id:** The client ID obtained when creating the application in Zitadel

- **scope**: openid profile email urn:zitadel:iam:org:id:<organization_id>  urn:zitadel:iam:org:domain:primary:<primary_domain> (Ex : s-organisation1.localhost)

- Endpoint /authorize : GET http://localhost:8080/oauth/v2/authorize?response_type=code&client_id=286796973950959619&scope=openid%20profile%20email%20urn%3Azitadel%3Aiam%3Aorg%3Adomain%3Aprimary%3As-organisation1.localhost%20urn%3Azitadel%3Aiam%3Aorg%3Aid%3A286796116853260291&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fui%2Fconsole%2Fauth%2Fcallback

### Screenshots

When trying to authorize, with only the **username** : 
![image](https://github.com/user-attachments/assets/c76272a6-a712-495b-a9e3-59c514a42d6f)

### Expected behavior

I should be able to login through the UI using **only** the username (e.g., "sahar") without appending the domain suffix (i.e., @{domainname}.{zitadeldomain}).

### Operating System

Windows
Windows
Browser : Microsoft Edge
Version 129.0.2792.52

### Additional Context

**Current behavior:** 
When I attempt to login using only the username (without the domain suffix), the authentication fails. However, the /authorize endpoint has the correct organization ID specified in the scope.

**Comment by hifabienne** [comment]
can you try to only send the primary domain scope?

I am not 100% sure from the top of my head, but I think with the primary domain, we also set the domain, with the org id scope we just preselect the organization for the settings, branding,etc. in that case the user will also have to send the domain.

Not sure how it behaves when you send both scopes

**Comment by livio-a** [comment]
You can "Hide the loginanme suffix" in the branding settings: https://zitadel.com/docs/guides/manage/console/default-settings#branding

**Comment by hifabienne** [comment]
I will close the issue as it is solved, feel free to reopen if there is still something missing
