### ISSUE TITLE
Improve error logging for InvalidResponseError from crewjam/saml (SAML-nuo0vphhh9)

### ISSUE THREAD

**Issue by studouglas** [zitadel/zitadel#8717]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

SAML response validation can fail with error `SAML-nuo0vphhh9`, which indicates the underlying SAML library (crewjam/saml) has failed to parse the response. This can occur for a number of different reasons, e.g. invalid signature, mismatched entity ID etc etc.

When Zitadel throws the `SAML-nuo0vphhh9` error, the parent error is set to the error returned from crewjam/saml. However, crewjam/saml sets the `Error()` string to a generic "Authentication failed" message, regardless of the underlying cause.

This makes it extremely difficult to debug issues validating the SAML response.

### Describe your ideal solution

The error object returned from crewjam/saml contains a string field `PrivateErr` which contains the specific validation error that occurred. It is undesirable for this error to be returned to the client, however it would be very helpful if it was logged by Zitadel to stdout.

This can be accomplished by a type check on the `err` we receive from crewjam/saml, and if it is a `InvalidResponseError`, log the value of `PrivateErr` field to stdout, but still return the generic "Authentication Failed" message to the client.

Links:
- Call-site of SAML response validation error
    - https://github.com/zitadel/zitadel/blob/main/internal/idp/providers/saml/session.go#L70
- InvalidResponseError definition in crewjam/saml
    - https://github.com/crewjam/saml/blob/bbccb7933d5f60512ebc6caec7120c604581983d/service_provider.go#L576-L588

### Version

2.61.0

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Thank you for sharing your idea.
If there is a significant demand from customers/community, we will carefully consider implementing the feature.
Currently, the issue will be added to our product backlog to collect feedback.

Meanwhile, if you're interested in implementing it yourself, we also welcome pull requests.

**Comment by studouglas** [comment]
I'm happy to create a PR -- I'll do that. Thanks!

**Comment by hifabienne** [comment]
Hei @studouglas 
Thanks a lot, I assigned you to the issue

**Comment by studouglas** [comment]
Apologies for the basic question, but the contribution guideline stats that I should add a maintainer as a reviewer -- it doesn't look like I have permission to do so, is that something handled by you guys?

**Comment by hifabienne** [comment]
Yes we will do that, we usually go through all the contributions in our daily and directly assign them.
Thanks a lot 🙌🏻
