### ISSUE TITLE
Requsting a new Sign Up/Log In method

### ISSUE THREAD

**Issue by SaunakNandi** [zitadel/zitadel#8762]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

While doing a login we get 3 options ->
1. Google
2. Github
3. Zitadel account

### Describe your ideal solution

I think Zitadel should have a **GitHub** login option because I belive **GitHub** is more widely used then **GitLab**.

### Environment

ZITADEL Cloud

**Comment by hifabienne** [comment]
Hi @SaunakNandi 
Thanks for adding the issue.
Just to verify we are talking about the same.
You want to have the Github login for the customer portal of ZITADEL?
E.g. the login on zitadel.com?

**Comment by hifabienne** [comment]
as i didnt get any answer on the issue, i will close it for now.
I can reopen if we get some more information
