### ISSUE TITLE
[Bug]: Zitadel sends OIDC auth_token along with id_token even only id_token was configured

### ISSUE THREAD

**Issue by biglolka** [zitadel/zitadel#8776]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.62.2

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

In our Service Provider (SP) we setup the required OIDC response type to id_token, and we configured Zitadel to send id_token only, but even with this setting Zitadel sends the auth_token along with the id_token.
Confirmed by @muhlemmer on Discord  this is a bug in Zitadel

### To reproduce

configure an OIDC connection with a service provider, and setup to send "id_token" only as response type, and Grant Types "Implicit"
on the SP side configure the OIDCResponseType "id_token"

### Expected behavior

Zitadel should return the configured token only

**Comment by fforootd** [comment]
Relates to this [discord thread](https://discord.com/channels/927474939156643850/1294001717725237298)

**Comment by muhlemmer** [comment]
#8777 pinpoints the bug and still needs a bit of work to solve it completely. I'll continue on it as soon as I have some more time.
