### ISSUE TITLE
[Bug]: Restriction to allowedLanguages won't work

### ISSUE THREAD

**Issue by michaelwitt13** [zitadel/zitadel#8808]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

v2.62.7

### Database

None

### Describe the problem caused by this bug

I restricted the allowedLanguages to de, en, fr only.

But in the user profile every language can be chosen and can be saved.

So I think the restriction is never applied in user profile configuration.
Is this a bug?

### To reproduce

The following API call proved my configuration change:

GET {{authority}}/admin/v1/restrictions
Authorization: Bearer {{api_service_user_token}}
X-Zitadel-Orgid: my org-id

response:
{
 ...
  "allowedLanguages": [
    "de",
    "en",
    "fr"
  ]
}

### Screenshots

In the console the restriction looks like this:
![Image](https://github.com/user-attachments/assets/a3da0575-5dd7-4681-95bc-1c65e478fa65)

But a user can still change the language to any other language Zitadel offers in the user profile:
![Image](https://github.com/user-attachments/assets/028d8baa-1cf8-4d7f-a301-cc5756c6e43e)

### Expected behavior

I would expected that only the allowedLanguages can be chosen in the user profile but not the other languages.

### Operating System

Zitadel Cloud

**Comment by stebenz** [comment]
The decision was as follows:
- Allowed languages depend on the available languages that Zitadel is translated into.
- Preferred languages can be everything as it is only an indicator which language a user would prefer, if this language is not available the default language is used

I will close this issue as this is not regarded as a bug.
If there is a need or interest in improving this, please create another issue or reopen this issue with different content.
