### ISSUE TITLE
Docs: API for logging in actions inconsistent

### ISSUE THREAD

**Issue by karatekaneen** [zitadel/zitadel#8811]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

On the [modules page](https://zitadel.com/docs/apis/actions/modules#log) the Logging API is defined as having three methods, `log`, `warn` and `error`. 

In the examples it is shown as `info`, `warn` and `error`. It is confusing if you should use `log` or `info` for info-level logging.

Did a very quick search in the code and could not figure out the correct one, will dig some more when I find the time.

**Comment by hifabienne** [comment]
hei @karatekaneen 
Thanks for adding the issue.
You are right that is confusing.
I had a quick look at the code, and it is log not info, so the exampel is wrong.
You can find it in this file here: https://github.com/zitadel/zitadel/blob/main/internal/actions/log_module.go

Would you like to create a pr and fix the docs?

**Comment by karatekaneen** [comment]
@hifabienne Done!
