### ISSUE TITLE
Allow modification of login interface texts for Email / SMS OTP

### ISSUE THREAD

**Issue by thaddeuskkr** [zitadel/zitadel#8819]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I currently cannot customise the two-factor authentication screen for OTP by email. I assume it is the same for OTP by SMS, as I cannot find it in the dashboard. I’ve attached a screenshot of the page I’m referring to.

![Image](https://github.com/user-attachments/assets/cb010303-10f7-48d2-96af-23c2c2d2c6e5)

### Describe your ideal solution

As a host of a ZITADEL instance, I’d like the ability to customise the text on the two-factor authentication by email screen, as it is slightly confusing as of now. Users are not told what code they are sent / what second factor they are using, is it by email or by SMS?

### Version

v2.64.1

### Environment

Self-hosted

**Comment by hifabienne** [comment]
Hi @thaddeuskkr 
Thanks for adding this issue.
We already have an issue for that here: https://github.com/zitadel/zitadel/issues/8222
Due to this i will close your issue to avoid duplicates

**Comment by thaddeuskkr** [comment]
Alright, my bad - I saw that issue and thought that it specifically referred to the labels used for the buttons that lead to those pages. Apologies
