### ISSUE TITLE
HSTS Headers on all services

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#884]
Right now we do not set HSTS Headers on the services but only on the GUI.

We need to track this further.

This can be mitigated by enabling HSTS on the reverse proxies.

**Comment by fgerschwiler** [comment]
@fforootd Is this issue still relevant? Or can we close it?

**Comment by fforootd** [comment]
@livio-a should we solve this outside ZITADEL for the moment? I mean we can use GCLB to add this header

**Comment by fforootd** [comment]
relates to https://github.com/caos/zitadel-cloud/issues/15

**Comment by livio-a** [comment]
to ensure HSTS is set on all endpoints, adding it in GCLB is for sure the easiest and fastest way
but IMO we should solve this in ZITADEL itself later on

**Comment by fforootd** [comment]
So we should keep this open for a little while more

**Comment by fforootd** [comment]
This is no longer relevant since we have hsts rolled out
