### ISSUE TITLE
[Bug]: Redirect to Zitadel instead of application home page

### ISSUE THREAD

**Issue by SajjadManafi** [zitadel/zitadel#8854]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Database

None

### Describe the problem caused by this bug

hello everyone
I tried to integrate **Jira** and Confluence with Zitadel using the **miniOrange OAuth/OpenID connect plugin**.
And all the functionalities are working properly except for **redirecting when logging out**.
I have **set** the logout redirect url to the main page of Jira, but instead of the main page of Jira, it refers to a page in Zitadel.
I had done the same a month ago and this problem did not exist.
Is there a way to fix this problem or troubleshoot it?

### To reproduce

1. log out from Jira
2. call jira.example.com/plugins/servlet/oauth/logout?application=jira
3. redirect to https://auth.example.com/oidc/v1/end_session
4. redirect to /ui/login/logout/done page of zitadel

### Screenshots

![Image](https://github.com/user-attachments/assets/6695365f-8871-4044-b6e5-5b844e6d1ffd)
![Image](https://github.com/user-attachments/assets/32cd130a-abbc-421b-b72f-2d8c9430e4e6)

**Comment by livio-a** [comment]
Hey @SajjadManafi 

When using the RP Initiated Logout: a `post_logout_redirect_uri` (with an `id_token_hint` and/or `client_id`)  must be passed on the end_session request:
https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RedirectionAfterLogout

This seems like a bug in the miniOrange plugin.
Will close this issue.
