### ISSUE TITLE
[Bug]: user registration with existing email

### ISSUE THREAD

**Issue by MR4online** [zitadel/zitadel#8877]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.64.1

### Database

PostgreSQL

### Describe the problem caused by this bug

It is possible to register a User (via /ui/login/) with the same e-mail address with an existing user, who was registered via console with another username. 

It's not possible to log into this new user, even when the original one has been deactived.
Error: user not found.

### To reproduce

1. register user via console with USERNAME@abc.com and USERNAME 
2. confirm user
3. register user via hosted UI with USERNAME@abc.com
4. confirm user
5. login via hosted UI -> failed

### Screenshots

![Image](https://github.com/user-attachments/assets/c97c1b73-6065-4e04-9b6e-99e750565718)

### Expected behavior

It's not possible to register user 2.
-> Error: Account existing

### Operating System

Device: MacOS 15
Docker

### Relevant Configuration

Everthing default, just some data added to test Zitadel. I'm Zitadel beginner.

**Comment by bilalqv** [comment]
@MR4online , I have local setup of Zitadel. If we register user via console with email `USERNAME@abc.com` and try to register another user with same email via ui, we get _User already exists_ error.

**Comment by hifabienne** [comment]
In ZITADEL the username field is unique across all organizations. The email field is not.
This means if you create a user and you add the email address to the username field, you will not be able to create another user with the same.
