### ISSUE TITLE
Go v1.23 upgrade

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8906]
We need to upgrade to Go 1.23 in our complete ecosystem. This issue applies to all repositories where we use Go and can be used as a template for next Go versions.

## Libraries

Our [Go libraries](https://github.com/orgs/zitadel/repositories?q=sort%3Aname-asc+language%3AGo) always support at least the latest 2 Go releases. (1.22 and 1.23 in this case). Older version are allowed as long as that doesn't restrict the usage of new additions in the standard library we might need. For example, the `slices` package was included in Go 1.21. None of our libs should support any older version.

| Repository | Assigned to | PR | Done (incl. branch protection |
| -- | -- | -- | -- |
|   https://github.com/zitadel/logging  |   @livio-a    |  https://github.com/zitadel/logging/pull/24  | ✅ |
| https://github.com/zitadel/oidc    |    @muhlemmer  | https://github.com/zitadel/oidc/pull/681   | ✅ (done on main, no protection on next) |
|  https://github.com/zitadel/passwap   |  @muhlemmer    | https://github.com/zitadel/passwap/pull/49   | ✅  |
|   https://github.com/zitadel/saml  |   @livio-a   |  https://github.com/zitadel/saml/pull/90  | ✅  |
|  https://github.com/zitadel/schema   |  @muhlemmer    |  https://github.com/zitadel/schema/pull/6  | ✅ |
| https://github.com/zitadel/terraform-provider-zitadel    |    @stebenz  |  https://github.com/zitadel/terraform-provider-zitadel/pull/203  | ✅ |
|  https://github.com/zitadel/xk6-modules   |   @adlerhurst   |  already on 1.22 | ✅ |
|  https://github.com/zitadel/zitadel-analytics   |  @eliobischof    |  https://github.com/zitadel/zitadel-analytics/pull/13  | ✅  |
|   https://github.com/zitadel/zitadel-charts  |  @eliobischof    |  https://github.com/zitadel/zitadel-charts/pull/274  | ✅  |
|  https://github.com/zitadel/zitadel-go   |  @stebenz    |  https://github.com/zitadel/saml/pull/90  | ✅  |
|  https://github.com/zitadel/zitadel-tools   |  @adlerhurst    |  https://github.com/zitadel/zitadel-tools/pull/190 | ✅ | 

### Acceptance criteria

- [ ] If the library depends on `exp` packages now available in the second latest release, migrate the code and bump the `go.mod` version to that release.
- [ ] Run `go mod tidy`
- [ ] Remove builds older than the version in `go.mod` from the pipeline Go version matrix
- [ ] Add the latest Go release to the pipeline version matrix
- [ ] Update the "Supported Go Versions" entry in the README.md
- [ ] Once the PR with changes is merged, set the branch protection rules to require success for the builds of the 2 latest versions.

## Zitadel

Zitadel builds only on the latest version of Go.

### Acceptance criteria

- [ ] If zitadel depends on `exp` packages now available in the latest release, migrate the code
- [ ] Bump the `go.mod` version to the latest release
- [ ] Set the pipeline to use the latest version

**Comment by muhlemmer** [comment]
@livio-a saw your note about oidc/next. I will need to make some time for reconsiling main -> next in the near future. I'll pick up branch protection then.

**Comment by adlerhurst** [comment]
xk6-modules is already on go 1.22: https://github.com/zitadel/xk6-modules/blob/main/go.mod#L3-L4
