### ISSUE TITLE
Notification Handling

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#8931]
The current handling of notification follows the same pattern as all other projections:
Created events are handled sequentially (based on "position") by a handler. This leads to back pressure on the projection since the handling of events might take longer than the time before a new event (to be handled) is created.

To parallelize the process of notifications we want to change the following:

- [x]  Notifications are created as separate events on a notification aggregate
- [x] Notification workers query for unhandled notifications
  - [x] eventstore needs to provide a mechanic for that ("not in")
- [x] Notification workers process the notification event
  - [x] workers need to be able to lock their processing rows / events
  - [x] Every successful event dual writes success events (user / session event and the notification success event)
  - [x] a failure creates a notification failed event
- [x] The current notification handler needs to be changed from sending notifications to creating the corresponding notification events for the workers

**Comment by adlerhurst** [comment]
## workflow

1. session service creates `code.added`-event
2. notification producer picks up `code.added`-event
3. notification producer creates aggregate and writes `requested`-event to event store
4. message sender checks periodically for work by querying eventstore for not yet sent messages and locks a batch
5. message sender writes events if the messages were sent or not

## Notification aggregate

To achieve the workflow described before a new aggregate type `notification` is added.

### Event types

The following events can be written to the aggregate and contain the payload.

### notification.(email|sms).requested

- user (to send the message to)
- additional information

### notification.(email|sms).sent

### notification.(email|sms).attempt.failed

- cause why the send failed

## workers

### notification producer

Sequential projection as current handlers work. It listens for `code.added`-events and creates the initial `notification.(email|sms).requested`-event on the new aggregate.

### message sender

Queries not locked notification aggregates which only contains `notification.(email|sms).requested`-events, locks a batch, sends the notification to the requested channels and writes the outcome of the event to the aggregate.

## eventstore changes

### allow "not in" queries to exclude events

it must be possible for message sender to filter for all the the event of an aggregate which does not contain other events.

@adlerhurst

### allow locking of events

To allow the message sender to work in parallel the events its currently working on need to [be locked](https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-ROWS).

@muhlemmer

## notification package changes

@livio-a

The current notification projection needs to be rewritten to create the `requested`-event of the new aggregate.

Create a scheduled asynchronous worker which does the following inside a transaction:

1. query batch of events
2. query additional data
3. send requests to providers
4. write events to eventstore

Configuration for scheduling

**Comment by adlerhurst** [comment]
> Sorry, I think I also have a concern (or likely a misunderstanding) about the Notification Producer. If this is a normal projection handler, would that mean that it has to wait to be triggered by the spooler scheduler? Or is the spooler always poked when a new event arrives? 

It's poked when an event was written using a go channel

**Comment by adlerhurst** [comment]
hi @zhirschtritt 

Thanks for the feedback see our answers below:

> This looks great! Glad we're thinking in terms of requests v attempts.
> 
> One thing I'm thinking about is controlling the retry and backoff policy for notification requests. This will be especially important if we allow workers to batch notifications to send requests concurrently, which could potentially overwhelm recipients and hit rate-limits.

You are right that we can reach rate limits. If we get errors during sending we will create an additional event `notification.(email|sms).retry.requested` so that it is clear that we are talking about a retry, we will add the info [in this comment](https://github.com/zitadel/zitadel/issues/8931#issuecomment-2486865955). Zitadel will write two events in that case, `retry` and `failed`.

> 
> An example config for twilio-verify might look like:
> 
> TwilioVerify: 
>   BackoffMode: "exponential"
>   MinRetryDelay: 1000
>   MaxRetryDelay: 10000
>   MaxAttempts: 3
>   \# Automatically mark a notification as "abandoned" if any attempt fails 
>   AbandonFailedDeliveries: true
>   \# This might difficult to coordinate across multiple pods in a k8s deployment, but per-zitadel pod could still be a useful limit to tweak
>   MaxInFlight: 100
>   \# Automatically abandon messages if they are not handled within the specified time
>   MessageTtlMs: 60000
>   \# Pausing delivery is probably not a mvp feature, but could be very useful
>   Paused: false

The goal of the `retry`-event (this replaces your _new_`notificaiton.requested` event) is to add a duration which defines the min retry delay. The min delay is event.created_at + event.payload.retryDelay, because it might take some time until Zitadel picks up the event that delay is kind of random.

The maximum fields make sense (ttl, attempts), we will add them.

As a pod can have multiple workers sending messages you will be able to configure the amount or set it to 0 to disable it.

The backoff mode might be added later, you will be able to define a delay at least in the beginning.

> So, an example event flow for retries I'm picturing is:
> 
> 1. `...code.added` event created
> 2. `notification.requested` event created with a `not_before_time` == `created_at`
> 3. Notification worker picks up request and the request fails with a 500
> 4. `notification.attempt.failed` event created, and a _new_ `notificaiton.requested` event created with a `not_before_time` set according to the configured handler's backoff policy.
> 5. Worker picks up the new `notification.requested` event and fails again with 500
> 6. `notification.attempt.failed` event created and `notificaiton.request.failed` marking the request as terminal
> 
> The issue with this approach is how a worker can efficiently query for `notification.requested` events that are ready to be sent (`not_before_time <= now()`). I'm guessing we can lean on the new `fields` table to normalize that value?

We will first test querying the events and ignore the ones which are delayed to later in business logic.

> 
> Also thinking of other terminal states for a notification:
> 
> * "abandoned" - the message ttl elapsed or the AbandonFailedDeliveries = true
> * "cancelled" - the message was manually cancelled by a human
> * "failed" - max attempts reached
> * "completed" ✅

Great catch we will add these events. `completed` is the same as `sent`.
