### ISSUE TITLE
Search Users v2 default org

### ISSUE THREAD

**Issue by lukaslihotzki-f** [zitadel/zitadel#8961]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

https://zitadel.com/docs/apis/resources/user_service_v2/user-service-list-users:
> By default, we will return users of your organization.

However, this endpoint seems to return all users from all organizations if no `organizationIdQuery` is specified.

**Comment by hifabienne** [comment]
@stebenz is the documentation wrong here? For me it looks like we have just copied the docs from the v1 implementation, and we should just remove that sentence, that per default all users you are allowed to read, based on your permissions are returned
