### ISSUE TITLE
[Bug]: Generated IDs are not unique

### ISSUE THREAD

**Issue by sp132** [zitadel/zitadel#9075]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.60.2

### Database

CockroachDB

### Database Version

23.1

### Describe the problem caused by this bug

I'm in the process of setting up IaC for our ZITADEL installations, and it seems there is a significant issue with the ID generation process. The problem is severe, as the generated IDs are not unique when multiple resources are created at once, causing consistency issues.

### To reproduce

1. Setup Terraform
2. Install ZITADEL Provider 2.0.1
3. Provision a bunch of similar resources, such as machine users or project applications
4. `terraform apply`
5. It might not be manifested right away, try running `terraform destroy` and `terraform apply` again

### Screenshots

![Image](https://github.com/user-attachments/assets/72825e7e-00ea-4758-87c1-2b325bf483b8)
![Image](https://github.com/user-attachments/assets/b7134b38-176f-45c3-aab4-7db1a2156aba)

### Expected behavior

Generated IDs are unique.

**Comment by muhlemmer** [comment]
We use [sonyflake](https://github.com/sony/sonyflake) which requires a machine ID. If the machine ID is not unique, you may experience the problems you are facing. The default is to use the machine's private IP.

We experienced similar problems in GCP where there is not `PrivateIP` available. You might need to tune the following config section to match with what your deployment provider offers:

https://github.com/zitadel/zitadel/blob/77cd430b3a67cd95ad9deec1e5b44a17638def06/cmd/defaults.yaml#L342-L359

**Comment by sp132** [comment]
We have both of these options enabled. I can check whether they are unique on all three instances, but I'm positive that's the case.

What "PrivateIp" means in this context, though, there could be multiple network interfaces attached, how ZITADEL knows which one is "private"?

**Comment by muhlemmer** [comment]
We loop over all interfaces and take the first address with a private prefix:

https://github.com/zitadel/zitadel/blob/50d2b26a28656d5919247b07099a249e0958baf4/internal/id/sonyflake.go#L56-L90

**Comment by sp132** [comment]
Got you, thanks!

Indeed, two out of three instances had identical private IPs (docker containers running on different hosts).
