### ISSUE TITLE
`hasCode` and `sendCode` requests

### ISSUE THREAD

**Issue by peintnermax** [zitadel/zitadel#9096]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When verifying user emails, we have a scenario where a user never got a verification email. To react to such a state we need to send a mail whenever the verification page is shown to the user. We therefore need a `hasCode` and `sendCode` method.

### Describe your ideal solution

Provide methods `hasCode` and `sendCode` on the user service

### Environment

ZITADEL Cloud

**Comment by livio-a** [comment]
Do we really need both methods or couldn't we just create a `SendEmailCode` endpoint and deprecate the `ResendEmailCode` one. Can't think of any reason why we want to make sure that only a resend should be possible but not a first time send.

By that the login UI can always use the same method.

**Comment by stebenz** [comment]
Problem is that the hasCode is the indicator if the Send or Resend endpoint even has to be called, and as you have 3 options from there:
- there is a code, send none (Verify)
- there is a code, replace it (ResendEmailCode)
- there is no code, send one (SendEmailCode)

Be as it may, the HasCode seems to be necessary, if we do a SendEmailCode(only for the first code) and leave the ResendEmailCode, or do the SendEmailCode and deprecated the ResendEmailCode is more of the question?
At the same time it's besides the conditions on the call the exact same functionality.

**Comment by peintnermax** [comment]
I am fine by deprecating `ResendEmailCode` but the `HasCode` is required as the login needs to send a code immediately if the user did not get one yet.

**Comment by livio-a** [comment]
Ok I see the problem. Isn't there any other option?
It just feels like we're once again solving a specific use case only we might have and now add two methods for the email part and do not case about phone, TOTP, passkey or any other registration.

**Comment by stebenz** [comment]
As the information if a code exists is only carried in the events and no projections, we can for now only solve it this way.
We could technically add it to the user itself, but then we would need to handle all code added events in the projection as well.
The difference of resend and send we discussed already a few times, and I don't really see a problem with the change, but then I could also just leave the Resend endpoint be and add a Send endpoint.
